### ISSUE TITLE
Option to enable/disable spell-checking for inline code and code blocks

### ISSUE THREAD

**Issue by cknightdevelopment** [RickStrahl/MarkdownMonster#100]
I think it would be nice to have a feature to be able to optionally enable/disable spell-checking for inline code and code blocks. I would think that 99.9% percent of the time people are putting code in these blocks, which would obviously fail spell checking. Not having this leads to a lot of _red-squigglies_ that at best is just annoying/disrupting, and at worst makes it harder to identify the actual spelling errors in the text you care about. For instance:

![image](https://cloud.githubusercontent.com/assets/7575912/21657755/9a923a74-d278-11e6-8cd1-5ad47f58760e.png)

**Comment by RickStrahl** [comment]
Yep definitily agree on that, but it's tricky due to the way the spell checker works. It's been a while since I've looked at it. Will take another look.

**Comment by RickStrahl** [comment]
I've made the necessary changes to not spell check code blocks.

9acbbc4aa265969af1e6de18ee2caf357d9b94aa

No switch - just no spell checking in code blocks. I don't think that spell checking for code snippets is useful in most cases.

**Comment by cknightdevelopment** [comment]
Terrific!  I agree that having a switch is probably unnecessary. Thank you very much for addressing this so quickly!

**Comment by RickStrahl** [comment]
It'll be in post 1.1.6 releases probably tomorrow.
