### ISSUE TITLE
Strikethrough by design or issue?

### ISSUE THREAD

**Issue by iisfaq** [RickStrahl/MarkdownMonster#1003]
I am not sure if this is a bug or by design.

~~
line 1
line 2
~~

But if I select two lines and I want to strike through them both the strike though is not rendered in the preview (this may be by design since it does not render here either (see above). Also renders above as two lines, but the preview in MM is 1 line.

```
~~
Run the file
docker run --name linuxdockeridlcompiler -it linuxdockeridlcompiler:Dockerfile
~~

```

Rendered as

![image](https://user-images.githubusercontent.com/5828178/215843369-86fd7dfb-062a-42ef-97dc-6b312a0af1dd.png)

A strike-through on a single line or part of a line works fine.

```
~~Run the file~~

```
![image](https://user-images.githubusercontent.com/5828178/215843761-ee5dcfcd-c520-40d3-8f38-90675c8aed9a.png)

Maybe if this is by design, you could add the strikethrough to each line in the selected area automatically?

```
~~line 1~~
~~line 2~~
```

~~line 1~~
~~line 2~~

Version 2.8

**Comment by RickStrahl** [comment]
Strikethrough - along with bold, italic, underline, etc. - are all inline elements, so they don't work across lines. This is due to the way HTML handles those markup elements.

I do like the idea of automatically marking up multiple lines...

This would really apply to all inline elements...

**Comment by RickStrahl** [comment]
I sat down to implement this but just realized that doing multiline as suggested doesn't make any sense because logistically multiple lines that are single lines (without a line break character) are still treated as a single paragraph.

Here's what I mean:

![image](https://user-images.githubusercontent.com/1374013/215911916-6f1246ad-aeb9-43aa-b0b0-b4040cb890bc.png)

Seems too confusing to figure out what works and what doesn't if selectively applying multiline options. What would that apply to?

**Comment by RickStrahl** [comment]
Ok so more experiments. I added support for multi-line inlines and I suppose it works, even though I suspect this will raise more questions than it answers.

![MultiLineInlineMarkup](https://user-images.githubusercontent.com/1374013/215922220-eb7c1db6-8ef2-4186-839d-c82f615f1652.gif)

Note that the markup doesn't create breaking lines, it only puts the inline markup on every line. It doesn't automagically (and shouldn't) turn the lines into breaking lines. But this works now. You can also do multiple lines that are seperated by a blank line (a para break) and that works correctly as well.

I think I can live with this... Perhaps one more thing might be an option to enable this? `Editor.MultLlineInlineMarkup=true` perhaps?

**Comment by iisfaq** [comment]
Wow I was happy with your initial comments on this, you do work fast.

Cheers

**Comment by RickStrahl** [comment]
Any comments if this addresses your concerns?

I guess the main issue I have is that making mutliple lines that are essentially a single paragraph marked up is sub-optimal but it's simple that catches both the scenario of true multi-paragraph and single parargraph markup at least functionally.

**Comment by RickStrahl** [comment]
Please take a look at v2.8.2+ which includes these changes.

**Comment by iisfaq** [comment]
I just checked a couple of mins ago after I saw your email and it said no
updates. And now there it is.

I like the change, it feels logical to me, thanks for implementing it.:-)

Cheers

Chris

**Comment by iisfaq** [comment]
I spotted one thing - if you have a soft return embedded in the block to be formatted it gets lost.

![MarkdownMonster](https://user-images.githubusercontent.com/5828178/216192323-c4db034d-0607-43a0-81b2-8071d2e30194.gif)

Chris

**Comment by RickStrahl** [comment]
Yes found this one yesterday and fixed. You should now be able to format a block of text for soft returns and then mark up each line with the italic inside of the soft returns.
