### ISSUE TITLE
`Format Table` adds needless space to explicitly aligned columns

### ISSUE THREAD

**Issue by jbridgy** [RickStrahl/MarkdownMonster#1005]
The following examples in fenced code blocks demonstrate how the `Format Table` command of MM v2.8.2.6 adds a needless space to each explicitly aligned column, no matter whether left, right or center.

When the code fences are removed then all examples (before and after applying `Format Table`) are rendered correctly by MM, GitHub, GitLab, Azure DevOps and typora v1.5.5.

### Case 1: Table with implicitly left-aligned columns (default)

Before `Format Table`:

```markdown
| # | Column 2 | Column 3 |
|---|----------|----------|
| 1 | bla      | bla      |
| 2 | bla      | bla      |
```

After `Format Table` (OK, unchanged):

```markdown
| # | Column 2 | Column 3 |
|---|----------|----------|
| 1 | bla      | bla      |
| 2 | bla      | bla      |
```

### Case 2: Table with explicitly left-aligned columns

Before `Format Table`:

```markdown
| # | Column 2 | Column 3 |
|:--|:---------|----------|
| 1 | bla      | bla      |
| 2 | bla      | bla      |
```

After `Format Table` (BAD, needless spaces added):

```markdown
| #  | Column 2  | Column 3 |
|:---|:----------|----------|
| 1  | bla       | bla      |
| 2  | bla       | bla      |
```

### Case 3: Table with right-aligned columns

Before `Format Table`:

```markdown
| # | Column 2 | Column 3 |
|--:|---------:|----------|
| 1 | bla      | bla      |
| 2 | bla      | bla      |
```

After `Format Table` (BAD, needless spaces added):

```markdown
| #  | Column 2  | Column 3 |
|---:|----------:|----------|
| 1  | bla       | bla      |
| 2  | bla       | bla      |
```

### Case 4: Table with centered columns

Before `Format Table`:

```markdown
| # | Column 2 | Column 3 |
|:-:|:--------:|----------|
| 1 | bla      | bla      |
| 2 | bla      | bla      |
```

After `Format Table` (BAD, needless spaces added):

```markdown
| #   | Column 2   | Column 3 |
|:---:|:----------:|----------|
| 1   | bla        | bla      |
| 2   | bla        | bla      |
```

**Comment by RickStrahl** [comment]
Fixed.

Before:

```markdown
| # | Column 2 | Column 3 |
|:--|:---------|----------|
| 1 | bla  s    | bla    d  |
| 2 | bla sda     | bla d     |
```

After table format:

```markdown
| # | Column 2 | Column 3 |
|:--|:---------|----------|
| 1 | bla  s   | bla    d |
| 2 | bla sda  | bla d    |
```
