### ISSUE TITLE
MM 2.8.5 / "mermaid" gets replaced with a "div" statement on MD

### ISSUE THREAD

**Issue by rowtoripo** [RickStrahl/MarkdownMonster#1009]
Once you enter the word `mermaid` within the MD source editor it will become usually:

```html
<div class="mermaid">

</div>
```

Above may be prevented when hitting `<enter>` quick enough. 

This is independant from the "mermaid render" setting.

**Comment by sqlposh** [comment]
@rowtoripo 
This is simply the snippets expansion string getting expanded for you.  

1. Open the Snippets Template Expansions thinggy  
![image](https://user-images.githubusercontent.com/59573341/218578707-9cf82d72-4635-46f0-814e-92b7124d7a9f.png)
1. Find the ones related to mermaid on the left (I've altered mine so I don't know what's there by default)  
![image](https://user-images.githubusercontent.com/59573341/218578898-acf083b4-cbf4-4dd5-8581-352e967d40b1.png)
1. Notice the `Expansion String`  I usually double up on the last letter of the expansion string so it doesn't expand when I want to actually write the word `mermaid`  
![image](https://user-images.githubusercontent.com/59573341/218579162-c3207bde-12f0-467b-b43d-7192c4faf2ee.png)

So it's not really an "issue" with MarkdownMonster, I think maybe you didn't realize there was autoexpansion of snippets like this, maybe?

**Comment by RickStrahl** [comment]
That's not one of the default snippets in the Snippets addin - so, I think you much have added that snippet yourself...

**Comment by sqlposh** [comment]
Yeah, sorry, I was responding to rowtoripo, not indicating a problem with the product at all.

**Comment by rowtoripo** [comment]
Thanks for the quick response. It was in the "text-pander". I do not recall putting it there - but now it's gone and in case I see more weird appearances following that pattern :arrow_right: I am going to check out that place 1st.
