### ISSUE TITLE
Wrong focus tab.

### ISSUE THREAD

**Issue by yowko** [RickStrahl/MarkdownMonster#101]
When I switch between tabs, the cursor still stays at last edited tab.

**Comment by RickStrahl** [comment]
What the hell?

**Comment by yowko** [comment]
I am so sorry. 
I created the issue with wrong title and photos.
I have changed.

**Comment by RickStrahl** [comment]
Fixed in 36efa08edd2a0f93350a0b9353040c3ff9968152
