### ISSUE TITLE
Wrong visualization of Markdown Document Outline (when the headers contain italics or bold chars)

### ISSUE THREAD

**Issue by oscaretu** [RickStrahl/MarkdownMonster#1013]
If you choose *Activate Markdown Document Outline*

![imagen](https://user-images.githubusercontent.com/2979926/225285461-26e25a7d-5660-40fe-a781-d958350bcee2.png)

and the headers contains marks for italics or bold, the outline contains non-expected text, like `Markdig.Syntax.Inlines.EmphasisInline`

![imagen](https://user-images.githubusercontent.com/2979926/225285153-3d3a942f-24f1-4315-8cc9-a5a3549dc2a0.png)

Another *strange* behaviour is when I create a new document, and I have active the Markdown Document Outline. I add new headers, but there is no change in the outline view. I have to save the document, and load it again, and then I can watch the outline properly.

**Comment by RickStrahl** [comment]
Thanks... Fixed:

![image](https://user-images.githubusercontent.com/1374013/225476973-6443a3fe-4b62-422c-90b3-6f747e406f56.png)

**Comment by RickStrahl** [comment]
Re: Doc outline not updating: Separate issue please.

Please keep issues to one item at a time.
