### ISSUE TITLE
The preview mode doesn't respect the dark mode (after restoring the original mode)

### ISSUE THREAD

**Issue by oscaretu** [RickStrahl/MarkdownMonster#1014]
I've changed from dark mode to light mode in the editor, to test it, and then I went back to dark mode. But the preview remains in light mode.

Dark mode in the editor, and light mode in the preview:

![imagen](https://user-images.githubusercontent.com/2979926/225319788-8b104781-c500-43c4-a850-bac321cf6eb2.png)

My version:

Version 2.8.7
feb. 23, 2023

By the way, it would be interesting to have a button in the `Help -> About` screen that would copy the version information to the clipboard, so you don't have to copy it by hand (also it would avoid typing errors).

**Comment by RickStrahl** [comment]
No that's the correct behavior. The default theme associated with Dark mode is GitHub which is what you see. 

I can't recall off-hand I think all modes use GitHub as the default theme and you can change it after the fact.

**Comment by oscaretu** [comment]
The rendering of the preview and the generated HTML code before testing the light mode was different from the one I get now, after switching back to dark mode. 

Before I tried light mode, the rendering was something like this:

![imagen](https://user-images.githubusercontent.com/2979926/225539929-e17452b9-3cc7-494e-8107-cbf560e27444.png)


Now I get this rendering;

![imagen](https://user-images.githubusercontent.com/2979926/225539762-7feb4bb3-40b0-4835-bb6c-ecdfd63d1d8f.png)

How can I restore the original rendering?
