### ISSUE TITLE
Typo in Addin Manager (Pandoc Markdown Parser)

### ISSUE THREAD

**Issue by oscaretu** [RickStrahl/MarkdownMonster#1015]
I suppose that the right word is *recipes* instead of *recipies* (my mothern language is Spanish, so I'm not sure...)

![imagen](https://user-images.githubusercontent.com/2979926/225437123-48932cf4-7a94-4a87-9934-0acb33d3f5c8.png)

**Comment by RickStrahl** [comment]
Fixed thanks.
