### ISSUE TITLE
Suggestion - Insert as Mermaid Diagram

### ISSUE THREAD

**Issue by CheetahChrome** [RickStrahl/MarkdownMonster#1018]
As a feature, to be able to right click and `Insert as Mermaid` would be helpful. The action would take the mermaid code in the clipboard and surround it with the mermaid code block. ` tic tic tic mermaid` {Clipboard Text} `tic tic tic`.

**Comment by RickStrahl** [comment]
It's not going to be on the right click menu. none of the editor actions are there as there are way to many.

But I think it would be nice for the extra markup menu on the toolbar and also for the Command Palette (`Ctrl-Shift-P Mermaid`) to do what you ask.

**Comment by RickStrahl** [comment]
Another useful option might be the Insert Code dialog by adding Mermaid as syntax  in which case it becomes:

* ALt-c
* (auto pasted from clipboard)
* select Mermain
* Enter

**Comment by CheetahChrome** [comment]
Nice! Thanks for the feature.
