### ISSUE TITLE
Feature Request: Support Local Hexo

### ISSUE THREAD

**Issue by noirgif** [RickStrahl/MarkdownMonster#1022]
I highly appreciate the support for local Jekyll, as it bridges the gap between a static website generator and the editor -- a gap frustratingly apparent but seldomly solved.

I personally use Hexo so I definitely would be happy to see its support, as it is similar to Jekyll but differs in the ways:
1. different front matter for posts. Here is the [hexo documentation](https://hexo.io/docs/front-matter#Settings-amp-Their-Default-Values).
2. different directory structure: the path to the posts is different.

I also see the potential to generalize to other static site generators -- it can allow the user to set a post template, path to the posts and assets, and commands to generate html or start a local server, even if they CMS they use is not officially supported.

**Comment by RickStrahl** [comment]
I'm sorry this too obscure to support in the box.

But it's something that someone can build as a Markdown Monster addin.
