### ISSUE TITLE
Window Alignment is wonky

### ISSUE THREAD

**Issue by hypercube33** [RickStrahl/MarkdownMonster#1024]
Using the app (Paid) for a while I noticed something weird - its not a 50/50 split between the editor and the rendering frames. I'd expect this behavior by default unless changed. Also the margins go all weird when you resize the frames. Also resizing the window throws everything further out of kilter and is seriously impeding my workflows.

Add an option to keep a 50/50 window split and keep the padding 0 on the leading margin (left) of the editor so its not funky. Markdown is supposed to be the formatting language so I'm not sure where the padding is coming from or why in the editor wasting my monitor space for words.

Thanks!

**Comment by RickStrahl** [comment]
Not quite sure based on this description what you're talking about but I think you're talking about editor padding which is configurable:

* [Editor Padding and Centered Layout](https://markdownmonster.west-wind.com/docs/_5ed0rj891.htm)

Go into the View menu and uncheck the **Centered Layout** check mark and you get full width editor.

The default is off so this got triggered on somehow...
