### ISSUE TITLE
Scripts don't work anymore after upgrading to 2.8.16

### ISSUE THREAD

**Issue by realB12** [RickStrahl/MarkdownMonster#1027]
After updating from 2.8.12 to 2.8.16 Snippets containing {{...}} expressions are stalling with the messge: (20,26): error CS023. TextOnly Snippets are still working. 
The type or namespace name 'Data' does not exist in the namespace 'Westwind.Utilities' (are you missing an assembly reference?)
<img width="895" alt="image" src="https://user-images.githubusercontent.com/3463881/233323936-e1cb4135-2c0e-48f1-9b66-eb41509a38ae.png">

**Comment by RickStrahl** [comment]
Ugh... thanks for reporting this. 

It's due to a change in one of the dependencies that we use and a missing assembly.

I need to take a look and probably remove the base namespace for `Westwind.Utilities.Data` from the base library, which is the removed package/assembly.

**Comment by RickStrahl** [comment]
I've pushed up [a new version](https://markdownmonster.west-wind.com/download) with the fix: `v2.8.16.3`.

**Comment by realB12** [comment]
Works find now. thx!

**Comment by RickStrahl** [comment]
Great thanks!
