### ISSUE TITLE
"THe Editor WebView Control has failed and the application has to shut down."

### ISSUE THREAD

**Issue by rablinz** [RickStrahl/MarkdownMonster#1031]
this error started yesterday. I have tried reinstalling, but Markdown Monster shows this a few minutes after opening editor. Regardless of .md document, including new

Windows 10

**Comment by RickStrahl** [comment]
What version are you on? Please make sure that you are on the latest version (2.9+)... There have been a number of problems with recent Microsoft WebView releases that were causing problems in the 2.8 release that have been addressed in late version 2.8 and now 2.9.
