### ISSUE TITLE
Bug: MM v2.9.3 behaves badly when following a relative link in presentation mode

### ISSUE THREAD

**Issue by jbridgy** [RickStrahl/MarkdownMonster#1033]
MM v2.9.3 behaves badly when you follow a relative link to another Markdown file in presentation mode.

EXAMPLE:
You have the following two small Markdown files linked with each other. 
**Document_1.md** contains:
```markdown
# Document 1

See also [Document_2.md](./Document_2.md).
```

**Document_2.md** contains:
```markdown
# Document 2

See also [Document_1.md](./Document_1.md).
```

Initially MM looks as follows:

![image](https://user-images.githubusercontent.com/98041047/236624688-f7d95648-a336-4c09-bcb7-283cec3dfef6.png)

After pressing `F11` (Toggle Presentation Mode) it looks as expected:

![image](https://user-images.githubusercontent.com/98041047/236624743-96b8ae02-fefa-40b5-90c8-e5d16cf385f9.png)

However, after following the link to Document_2.md it looks as follows, although MM is still in presentation mode:

![image](https://user-images.githubusercontent.com/98041047/236624838-644f813f-cec3-46bd-89f1-61ac8aa02b72.png)

I think this is a buggy view of presentation mode because now you have to press `F11` **twice** in order to view Document_2.md in presentation mode properly. After pressing `F11` the first time it looks as follows (back to normal mode):

![image](https://user-images.githubusercontent.com/98041047/236624987-5d6eb572-5ef1-4c0a-9ceb-5ccc3276f88f.png)

After pressing `F11` the second time I finally get what I expected already when MM was in presentation mode and I followed the link within Document_1.md (shown in screenshot 2):

![image](https://user-images.githubusercontent.com/98041047/236625122-0b8f7579-9db8-4419-87f1-0ec188f25e6e.png)

**Comment by RickStrahl** [comment]
Fixed in 2.9.4.
