### ISSUE TITLE
Feature Request: Add commands for non-breaking space and non-breaking hyphen

### ISSUE THREAD

**Issue by jbridgy** [RickStrahl/MarkdownMonster#1034]
Please add commands for non-breaking space (`&nbsp;`) and non-breaking hyphen (`&#8209;`).
Occasionally these special characters are helpful, especially in table headers. Probably I am not the only one who forgets the cryptic notations and has to look them up again and again.

I think the menu of button `Extended Markup Operations (alt-x)` would be a good place to present the suggested commands.

![image](https://user-images.githubusercontent.com/98041047/236629744-4210f217-a5df-4bb0-9d5a-461b82e4abec.png)

The context menu of the editor would be an alternative place.

**Comment by RickStrahl** [comment]
Done.

![image](https://user-images.githubusercontent.com/1374013/236636810-3ebf33cf-2509-45b9-8943-7cc28a69f74f.png)

It'll be in the next update
