### ISSUE TITLE
Media Links are not rendering non-http links

### ISSUE THREAD

**Issue by zhouxinghong** [RickStrahl/MarkdownMonster#1035]
This tool is great! But want to make a feature request about video preview playback:
1. Video preview playback should support video file preview playback in Explorer, but currently only supports image preview in Explorer, not video preview playback.
![image](https://github.com/RickStrahl/MarkdownMonster/assets/54253524/2ff6eea8-2431-495a-9a35-18e12cf5439e)

2. The video preview playback should support the following video insertion preview forms:
```html
![video name](resource folder_files/video name.mp4)
```
Because this format is very convenient for inserting video files, it has been adopted by other markdown editors. Hope you can support this form of insert preview in the next version.
![image](https://github.com/RickStrahl/MarkdownMonster/assets/54253524/21a9b19b-faa6-465e-8a43-fd885202db31)

Windows10
3.0.5

**Comment by RickStrahl** [comment]
Looks like this is an issue in the Markdig parser which doesn't render media links for non `https://` links. When using relative or non-pathed links the media links are embedded as if they were images.

I've filed an issue on the MarkDig repo and probably will take a look later and see why that's not working in their code.

https://github.com/xoofx/markdig/issues/715

**Comment by zhouxinghong** [comment]
Other similar markdown editors support non-`https://` links to play local videos, and vscode also supports non-`https://` links to play local videos, so it is recommended to improve it to make it compatible with more...

**Comment by RickStrahl** [comment]
The following demonstrates the issue.

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/51b832b4-c245-4e22-a108-9dcef38a3b0a)

Like I said - the library that provides the markdown parsing has the issue so this needs to get addressed at that end.

**Comment by RickStrahl** [comment]
At the end of the day this probably doesn't matter because most target sites like GitHub likely don't support any of this.

**Comment by zhouxinghong** [comment]
I'm a layman and I don't know much about its analytical principles. If it is determined that there is a problem with the upstream library, then you can continue to report the problem upwards! Thank you for your hard work and effort! 👍👏😜

**Comment by RickStrahl** [comment]
I've added a pull request to MarkDig to get this issue hopefully addressed in the upstream library:

https://github.com/xoofx/markdig/pull/723

**Comment by RickStrahl** [comment]
Looks like my fixes have been integrated in the latest version of MarkDig, so local and relative links are now working.
