### ISSUE TITLE
Add split & resizable panelling like VSCode and other editors

### ISSUE THREAD

**Issue by kilasuit** [RickStrahl/MarkdownMonster#1037]
One feature that would be great is to have split panelling just like VSCode as I often am in multiple markdown files at once and would greatly benefit from a side by side view.

**Comment by RickStrahl** [comment]
Yup it would be a nice feature, but too much of an effort to implement without a complete rebuilding of the layout engine in use currently. That may happen in the future when a complete re-write is in order, but not with the current WPF app.

If you need to see content side by side you can use **Open in New Window** to open a second instance of MM and then switch between the applications. It's not the same, but allows at least arranging side by side if you really need .
