### ISSUE TITLE
Feature request:  Consider adding Pikchr support

### ISSUE THREAD

**Issue by getater** [RickStrahl/MarkdownMonster#1038]
Similar to how MM supports Mermaid diagrams, I would like to see Pikchr support:
https://pikchr.org/home/doc/trunk/homepage.md

It seems like it would be crazy simple to integrate.  There's a single .c file, no external dependencies, and a single interface function
https://pikchr.org/home/doc/trunk/doc/integrate.md

**Comment by RickStrahl** [comment]
That looks interesting but not sure how I can integrate easily with a .c file here short of busting out a C compiler and trying to build a Win32 callable DLL. :smile: Not something I plan on doing...

I've never heard of this library and searching around it seems like it's pretty obscure. Seems to me there's little advantage of using this over mermaid?

If you're interested in this, you can take a stab at creating an MM add-in and building a small render extension. 

[Implementing RenderExtensions to customize HTML output](https://markdownmonster.west-wind.com/docs/_5i30sba89.htm)
