### ISSUE TITLE
Feature Request: Add `Font Color` command using HTML

### ISSUE THREAD

**Issue by jbridgy** [RickStrahl/MarkdownMonster#1040]
Sometimes colored text is almost indispensable. Therefore I suggest to add a `Font Color` command and a corresponding button that is well-known for example from MS Word, LibreOffice Writer, MS Excel or LibreOffice Calc. The command should work as follows:

1. Present a dialog that allows the user to pick a color, preferably a **named color** according to https://developer.mozilla.org/en-US/docs/Web/CSS/named-color or any **hexadecimal color** (prefixed with #).

2. Enclose the current selection with the HTML fragments `<font color=`*PickedColor*`>` and `</font>` regardless of special cases that lead to unnecessary or invalid markup. However, if the selection consists of whole lines then the HTML fragments may be placed on separate lines. See example 2.

### Example 1

1. Initial text:
    ```markdown
    This is a bad value, use a good value instead.
    ```

2. After named color `red` has been applied to `bad value` and hexadecimal color `#00a933` to `good value`:
    ```markdown
    This is a <font color=red>bad value</font>, use a <font color=#00a933>good value</font> instead.
    ```
    
### Example 2

1. Initial text (multiple lines already containing colored text):
    ```markdown
    Paragraph 1 of section that can be skipped safely.
    
    This is a <font color=red>bad value</font>, use a <font color=#00a933>good value</font> instead.
    
    Paragraph 3 of section that can be skipped safely.
    ```
    
2. After color `gray` has been applied to multiple whole lines:
    ```markdown
    <font color=gray>
    Paragraph 1 of section that can be skipped safely.

    This is a <font color=red>bad value</font>, use a <font color=#00a933>good value</font> instead.
    
    Paragraph 3 of section that can be skipped safely.
    </font>
    ```

Both examples are rendered correctly by **MM**, **Typora**, **Visual Studio 2022** and **Azure DevOps**.
Unfortunately GitHub and GitLab ignore the HTML fragments.

**Comment by RickStrahl** [comment]
Not implementing since it's not supported by most end publishing services like GitHub etc. If they can't display it you don't want to promote the use of these enhancements since it will break the markdown. And definitely not using the deprecated `<font>` element which was discontinued for HTML 5. Same thing works with a `<div>` or `<span>` though.

FWIW you can do most of these things with the Snippets editor:

* Create a new snippet
* Add @@@ for current selection replacement
* Assign a hotkey (or not) (requires a restart of MM to take)

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/f780c2a8-6f76-4889-9ada-222fb48026b3)

**Comment by RickStrahl** [comment]
Another thing you can do is add custom markup to a toolbar button via configuration:

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/ac95b44d-67bc-4702-b89a-c6763904ae31)

You can set these up in the MarkdownMonster.json configuration file:

```json
    "AdditionalToolbarIcons": {
      "FileCodeOutline": "html|<div style=color:red>\n{0}\n</div>|Red Block Text",
      "Code": "html|<span style=color:red>{0}</span>|Red Inline Text"
    },
```

more info here:

https://markdownmonster.west-wind.com/docs/_5im10bjpw.htm

**Comment by jbridgy** [comment]
> Not implementing since it's not supported by most end publishing services like GitHub etc. If they can't display it you don't want to promote the use of these enhancements since it will break the markdown. And definitely not using the deprecated `<font>` element which was discontinued for HTML 5. Same thing works with a `<div>` or `<span>` though.

I hope and expect that some popular Markdown flavor (GFM, GLFM, ...) will sooner or later provide a compact notation for inline colors. Maybe for example `[color=red]@@@[/color]`. 
Both HTML elements `<font>` and `<span>` are not in the spirit of Markdown but `<font>` is shorter and still supported by most browsers. As mentioned above Azure DevOps and some Markdown editors already support `<font>` while GitHub and GitLab currently just ignore it (do not pass it to the browser). Therefore I think that a color picker applying `<font>` is a reasonable intermediate solution.

```markdown
[color=red]@@@[/color]              may be later in Markdown
<font color=red>@@@</font>          HTML (deprecated but still widely supported)
<span style="color:red">@@@</span>  HTML
```

> FWIW you can do most of these things with the Snippets editor:
> 
>     * Create a new snippet
> 
>     * Add @@@ for current selection replacement
> 
>     * Assign a hotkey (or not) (requires a restart of MM to take)

Thanks for the tip. However, MM 2.9.10 ignores the value in the `Keyboard Shortcut` field of the `Snippet Template Expansions` dialog. It works only when the value is entered directly into the snippetsaddin.json file.

```json
"Snippets": [
  {
    "Name": "Font Color",
    "SnippetText": "<font color=red>@@@</font>",
    "Shortcut": "fontcolor",
    "KeyboardShortcut": "Alt+F2", // needs to be entered directly, not via dialog
    "ScriptMode": "CSharpExpressions",
    "CompiledId": null
  },
]
```

Furthermore **Ctrl+Z** (Undo) does work when a snippet has been inserted with its hotkey, unlike when it has been inserted with the `Run Snippet` button of the snippet dialog. 

A color picker for the **color value** would be nice.
