### ISSUE TITLE
Problem with version 2.9.9;  was ok with version 2.8.9.15

### ISSUE THREAD

**Issue by jlewis111** [RickStrahl/MarkdownMonster#1042]
Hi,

I tried out Markdown Monster v2.8.9.15, and it was fine, so I went ahead and bought a license today and installed the latest 2.9.9 version.

The latest 2.9.9 version appears ro require a later version of MicrosoftEdgeWebView2 than v2.8.9.15 did.

I'm running on Windows 7. 

The automated install of the latest version of MicrosoftEdgeWebView2 on Markdown Monster fails silently on my box, and so it attempts to upgrade MicrosoftEdgeWebView2 every time I start Markdown Monster.

If I try to install the latest version of MicrosoftEdgeWebView2 outside of Markdown Monster, I get the following error:

MicrosoftEdgeWebView2RuntimeInstallerX64 error 0xc0000139

I've searched Google, and I can't find a relevant reference for the above error.

The net effect of the above is that if I just skip the install of the latest MicrosoftEdgeWebView2Runtime version, then in v2.9.9, the Markup and WebView windows just render as Empty windows, which means it's unusable.

If I revert back to version 2.8.9.15, then the Markup and WebView windows render just fine.

It looks like version 2.8.9.15 tries to also update the MicrosoftEdgeWebView2Runtime, which also fails, but at least version 2.8.9.15 can render correctly with my old MicrosoftEdgeWebView2Runtime version, whilst version 2.9.9 cannot.

version 2.8.9.15 displays the following message:
---------------------------
WebView Runtime is out of Date
---------------------------

The WebView Runtime is older than the WebView component:

Installed Runtime Build: 1518
Required Runtime Build: 1587

Do you want to want to try and continue anyway?

   Note: you can override this behavior by setting 
   this configuration value to `true`:
   `System.IgnoreWebViewVersionMismatch=true` 

---------------------------
Yes   No   
---------------------------

The 2.9.9 version shows the same message, but with a much later required WebView Runtime version.

**Comment by jlewis111** [comment]
I did previously install standalone as Administrator, so that didn't work.

When I uninstalled and re-installed, the version installed was 1518 not 1774, so it looks like the version MicrosoftEdgeWebview2Setup.exe installs depends on the underlying Windows OS version.

Setting the Ignore Version Mismatch setting as above had no effect.

I've tried on another Windows 7 box and the results are the same.

Can I suggest that you try reproducing the above this for yourself by installing on a Windows 7 box.

It looks like the issue is that, without the 1774 version of Webview, the app's windows do not render correctly, and it may be that the MicrosoftEdgeWebview2Setup.exe  falls back to a version that is supported by Windows 7.

Perhaps version 1774 of Webview is not supported on Windows 7, and this leads to the behaviour observed?

**Comment by RickStrahl** [comment]
I'm not sure honestly and I'm not going to try and get this to work as I don't have a setup to test this on. If Windows 7 breaks - it 5+ years out of support.

Taking a look at the compatibility matrix it looks like 1519 is the last version of the runtime that works with pre-Windows 10 and related versions of Windows. 

https://learn.microsoft.com/en-us/microsoft-edge/webview2/

What's odd is that v .1519 was released a long time ago so I'm not sure why 2.8.9.15 would have worked with it. The hundreds numbers rev every month and a half to two months in WebView so this would have been some time ago that it broke so that would put it back about half a year.

What happens when you turn off the version check in MM? Does it crash or fail? The runtime versions are largely compatible because the internal interfaces aren't changing - most of the changes we see in the updates (and why I keep up with them) is that the .NET components fix things that break. I'm surprised this wouldn't work with older versions.

Unfortunately I can't install an older version of the runtime as the runtime cannot be uninstalled as it's a Windows component in recent versions of Windows 11.

**Comment by jlewis666** [comment]
If I turn off the version check in MM in 2.9.9, then on Windows 7:

MM starts up, but the windows are rendered blank, i.e. nothing is displayed in them.

I guess the best option is provide an install setup binary download for v2.8.9.15 as a legacy version to continue to offer some form of Windows 7 support, and advise on the website that Windows 7 is only supported by that version, and not later versions.

**Comment by RickStrahl** [comment]
Can you try downloading v2.9.11 - I've reverted back to an older version of the WebView which I think should work. 

If this works, the plan is that v2 of Markdown Monster will stay pinned on this version. 

Version 3 (which will be released in a few months and runs on .NET Core) won't support Windows 7 so there will be a clear delineator of what works with older versions of Windows.

**Comment by jlewis666** [comment]
I tried v2.9.11 and it behaves in the same way as 2.9.9 - no rendering is performed and the windows are blank.

Also, the setup binary from the main "download" button on your website downloads a corrupted binary that will not run. I had to download the & unpack it to get a working binary.

If you can make the latest version's installer program behave in the same way as v2.8.9.15 - i.e. get the MM installer binary to install WebView v109.0.1517.100 when it is run on Windows 7, then I think that might fix it.

**Comment by RickStrahl** [comment]
One more try - can you try 2.9.11.1 - rolled back to the 1400's WebView interface version.

**Comment by RickStrahl** [comment]
So I took a closer look at recent changes made and it appears I was looking at the wrong thing - there was a change in the build process as we're switching over to build both .NET FX and .NET Core versions. In that dual target install script it looks like some of the required runtime files not needed in Core are missing for the 2.x version which likely accounted for the error.

I've added these files back in - this wasn't just a problem of Windows 7, but for every one.  There are conflicting reports exactly when the WebView Runtime stops supporting Windows 7 - the link I posted suggested it has already happened. Another post mentioned it'll be in October starting with the `1900` releases.

My plan is to freeze v2 (NetFX) at pre-1900 WebView releases or whatever works with Windows 7 and v3 of Markdown Monster won't support Windows 7.

Latest update with the fixed runtime output is 2.9.12.

**Comment by jlewis666** [comment]
Thanks. I confirm v2.9.12 is working fine for me on Windows 7.

**Comment by RickStrahl** [comment]
Thanks for confirming.

Good news - the .NET SDK library used is the latest version in this update, so apparently that does still work with the runtime that is installed on your Windows 7 machine.

**Comment by RickStrahl** [comment]
One more related question with a few implications:

When you run the WebView install (as admin) does it install the latest runtime (18xx at this point) on your Windows 7 box? I assume from what you said earlier - not.

If there is no WebView runtime installed, does it still install the last supported version (it should but I'm not sure)?

**Comment by jlewis111** [comment]
On Windows 7, if I uninstall WebView, when I run the install it installs the version 1518 WebView.

**Comment by RickStrahl** [comment]
Thank you! 

So I think the plan to stick with below 1900 releases for v2 should then work for the foreseeable future and the last v2 release.
