### ISSUE TITLE
Virus-Warning in G-Data for 2.9.11

### ISSUE THREAD

**Issue by rluetke** [RickStrahl/MarkdownMonster#1045]
Hi Support,

when installing the newest version 2.9.11 my anti virus programm from G DATA says:
Beim Schließen der Datei "C:\Users\rl\AppData\Local\Markdown Monster\is-00F0H.tmp" wurde der Virus "Gen:Variant.MSILHeracles.55377 (Engine A)" entdeckt. Zugriff verweigert. (Engine A: AVA 25.35960)

In english:
When closing the file "C:\Users\AppData\Local\Markdown Monster\is-00F0H.tmp", the virus "Gen:Variant.MSILHeracles.55377 (Engine A)" was detected. Access denied. (Engine A: AVA 25.35960)

After Installation the virus is found in the file mm.dll.

Is this a false negative error of my anti virus programm?

v 2..9.10 from https://github.com/RickStrahl/MarkdownMonsterReleases/blob/master/CurrentRelease/MarkdownMonsterSetup.exe does not give me that virus warning!

Regards, Ralf

**Comment by RickStrahl** [comment]
Hmmm... those files shouldn't even be there...

Last release has gotten an update for cross building for the .NET FX version and .NET Core version and some mm.dll is a file that should only be in the Core version. 

I've updated the build to not output those files on the v2 (NetFX) version. 2.9.12 won't copy mm.dll, mmcli.dll and markdownmonster.dll.

I suspect that should address this issue... OTOH they are just DLLs that contain the same binary code that the corresponding EXE files hold. Definitely a false positive but a good reminder to remove those files.

**Comment by rluetke** [comment]
Hi Rick,

thank you.

My Edge-Browser still warns me:

- https://markdownmonster.west-wind.com/download
- Microsoft Edge, Version 114.0.1823.37 (Offizielles Build) (64-Bit)
- Windows 10

Warning:
"Stellen Sie sicher, dass Sie MarkdownMonsterSetup.exe vertrauen, bevor Sie es öffnen.
Microsoft Defender SmartScreen konnte nicht verifizieren, ob diese Datei sicher ist, da sie nicht häufig heruntergeladen wird. Stellen Sie sicher, dass Sie der Datei, die Sie gerade herunterladen, oder die Quelle aus der sie stammt vertrauenswürdig ist.
Name: MarkdownMonsterSetup.exe
Herausgeber: Unbekannt"

In english: Make sure you trust MarkdownMonsterSetup.exe before opening it.
Microsoft Defender SmartScreen could not verify whether this file is safe because it is not frequently downloaded. Make sure that you trust the file you are downloading or the source it came from.

Microsoft Defender SmartScreen also warns me not to start the exe.
If I insist, then there is the error: The setup files are corrupted".

I can downlaod with Google Chrome, but Microsoft Defender SmartScreen gives the same warning and error on installation.
The MarkdownMonsterSetup.exe has 2 MB only!

When I use https://www.softpedia.com/get/Office-tools/Text-editors/Markdown-Monster.shtml#download then the file size is 20 MB, installation is possible, no virus warning: everything is fine!

I just wamt to inform you about the windows problems.
Thank you for fixing the dll's.

Regards, Ralf
