### ISSUE TITLE
Can't change the default Font

### ISSUE THREAD

**Issue by edb616321** [RickStrahl/MarkdownMonster#1046]
No matter what I do, I can' t change the font from the default font "Consolas".  I've edited the settings and I've edited the json file. It always defaults back to Consolas. I have hundreds of verified fonts on my system. I have triple checked to make sure that I am typing in my new font exactly as worded. Amazon Ember Regular. Nothing works.  PLEASE HELP. 

![image](https://github.com/RickStrahl/MarkdownMonster/assets/97626015/c62ece54-d686-43da-a429-5022634625c7)

**Comment by RickStrahl** [comment]
The editor only supports Fixed Width fonts. You can't use proportional fonts...

**Comment by edb616321** [comment]
Thanks for the quick response. Yeah, I tried a couple of mono fixed width fonts as well. Inter mono and roboto mono.  Both are mono fixed width fonts. I installed them and no matter what I do it always goes back to Consolas.

Let me know. I really need to get a table updated for a meeting.

Thanks,
Edward
________________________________

**Comment by edb616321** [comment]
So I was able to get Lucida Console to work. It's not the font I want. This font does not change the table font when I copy and paste. Is that possible or does it just copy the existing font. Any way to list the possible fonts available?
________________________________

**Comment by RickStrahl** [comment]
I don't think you understand how Markdown works...

If you're looking for a WYSIWYG editor then this isn't the right tool for you.

Markdown is an HTML markup format - formatting of text is not something that you typically do with markdown - it's meant for document content that typically will be merged into pre-defined templates for output.
