### ISSUE TITLE
Mouse scrolling for left and right split screens (editing and previewing) is not fully synchronized.😜

### ISSUE THREAD

**Issue by zhouxinghong** [RickStrahl/MarkdownMonster#1048]
Mouse scrolling for left and right split screens (editing and previewing) is not fully synchronized.
Recently found a problem during use?
Problem Description:
When using the left and right split screens (editing and previewing), it is found that the mouse scrolling of the left and right split screens (editing and previewing) cannot be completely synchronized. Do you plan to improve and fix this problem? Thank you so much for an awesome editor 😜👍
Windows10
3.0.0.24

**Comment by RickStrahl** [comment]
You're going to have to be more specific. What exactly are you seeing - *completely synchronized* is not much to go on.

**Comment by zhouxinghong** [comment]
![image](https://github.com/RickStrahl/MarkdownMonster/assets/54253524/972d0c98-3da9-4e5e-b8ca-110ab62670f2)

**Comment by zhouxinghong** [comment]
Add a question:
Hello! May I ask if the editor can open the folder, because I want to view multiple *.md files in the folder

**Comment by zhouxinghong** [comment]
![image](https://github.com/RickStrahl/MarkdownMonster/assets/54253524/972d0c98-3da9-4e5e-b8ca-110ab62670f2)
During the mouse scrolling process, the editing content on the left should be kept on the same level as possible with the preview content on the right. You can also use different documents to try the effect😜

**Comment by RickStrahl** [comment]
Stop with the re-open and close already, man!

**Comment by zhouxinghong** [comment]
👌

**Comment by zhouxinghong** [comment]
When using the left and right split screens (editing and previewing), it is found that the mouse scrolling of the left and right split screens (editing and previewing) cannot be completely synchronized. Do you plan to improve and fix this problem? Thank you so much for an awesome editor 😜👍
Windows10
3.0.24

**Comment by RickStrahl** [comment]
There's no easy way to determine exact placement matching. if you look at other editors like VS Code or WebStorm you'll find that they too don't do per page matching of content to the cursor. MM (like those editors) syncs to a certain position on the page when you scroll more than a page or use your mouse cursor to click into a specific location, but while editing and using arrow keys only an actual  page scroll (where the entire page scrolls or text rolls off the page) causes re-alignment.

This won't be fixed.
