### ISSUE TITLE
AutoSaveBackups not creating *.bak files

### ISSUE THREAD

**Issue by WaltRitscher** [RickStrahl/MarkdownMonster#1049]
I have AutoSaveBackups set to true in the config file. I've verified it is set in the Settings screen.

![image](https://github.com/RickStrahl/MarkdownMonster/assets/6786189/75293f79-0062-4a5f-b51b-f2a06ff87c8b)

According to the docs, there should be a .bak file created while editing a document.
_Auto-Backup backs up typed content as you are typing. Backups are saved in a youFile.md.saved.bak backup file format. Whenever you save or close the file in the editor, the backup file is deleted....  
If a backup file is found when Markdown Monster opens or re-opens a file, it'll show the *.md.saved.bak file next to the opened file. You can then compare the two files and copy the content out of the backup file into the primary file as needed.
you want to see or access the file, you can toggle the Show All Files toolbar button in the Folder Browser's toolbar, or open the folder in Explorer._

The app crashed and I didn't see the file comparison.  I checked whether the .bak file is create in anywhere on the hard drive and I'm not seeing it anywhere.  After reopening the app, I edited a file and there doesn't seem to be a .bak file.

Also, I'm curious about this statement in the settings screen. "If non-zero creates a backup in the number of minutes
specified. 0 turns this feature off."  I have the setting set to  true  "AutoSaveBackups": true, and don't see where to change the minutes specified.

**Comment by RickStrahl** [comment]
FWIW you must not be on a recent version because the message is different now.

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/8dec3cf5-b445-41cc-be77-3ebe3a10f7bb)

So, maybe try updating to latest and see if that works. You might be on v1.x?

**Comment by WaltRitscher** [comment]
I'm on V2.8.12 , I'll update to the latest (2.9.12) and see if it makes a difference.

![image](https://github.com/RickStrahl/MarkdownMonster/assets/6786189/8823997c-8ab5-48b2-9605-a4ef1019c076)

**Comment by WaltRitscher** [comment]
Updating to the latest version solved the issue.

![image](https://github.com/RickStrahl/MarkdownMonster/assets/6786189/79b32213-7670-4220-87e8-0eaeec8d91e9)

**Comment by RickStrahl** [comment]
Ok, good. 

Surprised it was as late as 2.8.19 that this wasn't working... Ugh. And surprised nobody else (but the bug report at the time) had run into that.
