### ISSUE TITLE
Programs often freeze completely after a period of use

### ISSUE THREAD

**Issue by zhouxinghong** [RickStrahl/MarkdownMonster#1052]
Programs often freeze completely after a period of use
Windows10
3.0.0.24
log:
`

2023/7/16 21:54:08 - Editor WebView Control Process Failed: BrowserProcessExited Unexpected

2023/7/17 5:51:33 - Editor WebView Control Process Failed: BrowserProcessExited Unexpected

`

**Comment by zhouxinghong** [comment]
3.x version is a huge improvement in quality from the 2.x versions, so I'm coming back to try it again.👍

**Comment by RickStrahl** [comment]
Not saying this isn't happening but there's nothing to go on here.  I've seen this myself - but usually after MM sits for a long time idle or after the machine has been in Sleep mode and then comes back.

It looks like the WebView process is dying or getting killed - perhaps externally by some other process or AV?
