### ISSUE TITLE
backup file not working

### ISSUE THREAD

**Issue by zhouxinghong** [RickStrahl/MarkdownMonster#1053]
backup file not working
![image](https://github.com/RickStrahl/MarkdownMonster/assets/54253524/72363a97-5a10-485a-ae02-8e72b40e4427)
backup file not working
Actually it does not generate backup xxx.md.bak file

Windows10
3.0.0.24

**Comment by RickStrahl** [comment]
Works for me.

Backup files are not there if there are no changes in the document - ie. if you save the back up file goes away.

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/1e0347e8-8ebc-4240-9621-999fc7e1f34d)

**Comment by zhouxinghong** [comment]
Why does the backup file disappear after saving the file?
Can the backup file continue to exist after I want to save the file?
You can provide a setting option to adapt to the needs of different users for this function.

**Comment by RickStrahl** [comment]
If you've saved the file, there's no need for the backup file as you are up to date.
This won't be changed.
