### ISSUE TITLE
Shortcut key setting invalid

### ISSUE THREAD

**Issue by zhouxinghong** [RickStrahl/MarkdownMonster#1054]
Every time Master Monser is restarted, the shortcut keys will be reset, resulting in the failure of some user-defined shortcut key settings.

Windows10
3.0.0.24

**Comment by RickStrahl** [comment]
???

**Comment by zhouxinghong** [comment]
Every time Markdown Monster is restarted, the custom shortcut keys will be reset, causing some user-defined shortcut key settings to become invalid.

**Comment by zhouxinghong** [comment]
The shortcut keyboard defined by the user will be reset again after each startup, and finally the shortcut keyboard set by the user will not work. It's frustrating...

**Comment by zhouxinghong** [comment]
You can try it, in the case that mm does not work. Modify the json key bindings to save, and then restart again to see how it works?

**Comment by sharonxmcd** [comment]
!!!

**Comment by sharonxmcd** [comment]
???

**Comment by sharonxmcd** [comment]
...
