### ISSUE TITLE
Unable to insert image via image link in clipboard

### ISSUE THREAD

**Issue by zhouxinghong** [RickStrahl/MarkdownMonster#1055]
Unable to insert image via image link in clipboard
Windows10
3.0.0.24
![image](https://github.com/RickStrahl/MarkdownMonster/assets/54253524/ab505564-a1df-45b4-8a6d-4999062ef990)

```html
2023/7/16 21:33:47 - Couldn't retrieve image from Clipboard. Formats: System.String,UnicodeText,Text,Locale,OEMText

2023/7/16 21:33:50 - Couldn't retrieve image from Clipboard. Formats: System.String,UnicodeText,Text,Locale,OEMText
```

**Comment by RickStrahl** [comment]
There's no image on your clipboard. You have text on your clipboard.

**Comment by zhouxinghong** [comment]
[Video_2023-07-17_111203999999.zip](https://github.com/RickStrahl/MarkdownMonster/files/12065839/Video_2023-07-17_111203999999.zip)

**Comment by zhouxinghong** [comment]
Can you see the reproduction process?

**Comment by RickStrahl** [comment]
I'm not going to open a wmv image file... if you want to share a video post it somewhere and link.

Regardless. Whatever you're doing you're not pasting an image, you are pasting text or a URL - the error message shows it's text on the clipboard, not binary image information. I assume you're doing this from within the image dialog which expects an image.
