### ISSUE TITLE
[enhance] It would be more efficient to allow the user to enter a language match for the lookup 

### ISSUE THREAD

**Issue by zhouxinghong** [RickStrahl/MarkdownMonster#1056]
It would be more efficient to allow the user to enter a language match for the lookup
Windows10
3.0.0.24
![image](https://github.com/RickStrahl/MarkdownMonster/assets/54253524/6ed94b3b-3649-4a4e-b3b8-b38b45063eb0)
Hope this feature can be improved!

**Comment by RickStrahl** [comment]
???
