### ISSUE TITLE
Update Available Title Issue

### ISSUE THREAD

**Issue by kkbruce** [RickStrahl/MarkdownMonster#1058]
See 
![image](https://github.com/RickStrahl/MarkdownMonster/assets/2024682/b89e45a4-7254-4f3b-a483-501a9b10ee63)

**Comment by RickStrahl** [comment]
Hmmm... I suspect you have `Generic Attributes` disabled or you're not using the default renderer.

Can you check:

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/6e6db924-d531-45fc-abc8-d6aa64b0482d)

With that set it should work.

The dialog uses the same Markdown parser as is used to render the preview so settings applied to the main rendering also apply to the dialog. This could be the above setting or use of an alternate renderer but the default markdig renderer.

**Comment by RickStrahl** [comment]
I've made some changes so the generic dialog display used to display system messages like the Registration info doesn't use Markdown Monster's default configuration options other than the theme. This way the dialog is completely independent of the Markdown Parser or custom settings.

Update will be in 3.0.0.36+
