### ISSUE TITLE
Suggestion:  Add setting to exit the application after last document is closed

### ISSUE THREAD

**Issue by longtimedeveloper** [RickStrahl/MarkdownMonster#1060]
Suggestion:  Add setting to exit the application after last document is closed, or provide a command to close all windows and exit.

Thank you!

**Comment by RickStrahl** [comment]
Personally I find that annoying and it's also not the way other dev tools work - browser do though. Most other dev tools do what MM also does which is display an overview screen with things to do after the last document has been closed.

Unless there's more feedback for people requesting this, I don't think I will add this.

**Comment by longtimedeveloper** [comment]
I like what Notepad ++ does, they have a command to close all windows, and close the application.

I use MM as an editor and not a developer tool.  I don't like opening a file in MM and then seeing all the files from the previous session, since I do not want to view or edit them.  So, I have close all the documents and then close MM each time I use it.  

I was hoping to be able to close everything and MM with one command, similar to Notepad ++

Thank you.

**Comment by RickStrahl** [comment]
These are not really the same issue.

You can close all windows from the tab context menu, or the Window menu. But it won't close the application. In that case just click the big X and exit or  use `Alt W-L`.

You can also set up MM to not re-open with any of the previously loaded documents - or any number that you want to remember:

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/14b51675-2131-456e-9411-4a36d3dd78f0)

If you set up that value MM opens with an empty environment or - if you clicked on a file or opened from the command line - just with the file you specified.

**Comment by longtimedeveloper** [comment]
That is

**Comment by longtimedeveloper** [comment]
**that is exactly what I was looking for. thank you.**  I did search the settings but must have put the wrong search text.
