### ISSUE TITLE
Error sending post to Weblog

### ISSUE THREAD

**Issue by blackghostosint** [RickStrahl/MarkdownMonster#1061]
Hello.
I'm having a bit of an issue setting up my first WordPress blog.
A little backstory. I have a self-hosted wordpress on cloudways and registered with Cloudflare.
When adding Name and password the password the password doesn't show after saving. (probably for a reason)
I have checked to see if xmlrpc.php is valid on my site and it appears to be.
I get an error that only says that there was an error and I did not have any images added to the post. Just text.

![](https://support.west-wind.com/PostImages/2023/_6OY0REEHR.png)

*The output from MarkdownMonsterErrors log doesn't offer much to me. (I'm a bit lost.)*

8/20/2023 5:36:52 PM - Error sending post to Weblog at https://<removed>.com/XmlRpc.php: 
DTD is prohibited in this XML document.
-- Response from server does not contain valid XML.
Markdown Monster v3.0.0.37
10.0.19041.1.amd64fre.vb_release.191206-1406 - en-US - NET 4.0 - 64 bit
MicroElectronics B242, AMD Radeon(TM) RX Vega 11 Graphics, hw-acc: True
en-US - en-US    
---
System.Private.Xml
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at CookComputing.XmlRpc.XmlRpcSerializer.DeserializeResponse(Stream stm, Type svcType)
System.Xml.XmlException
---------------------------

Any guidance s greatly appreciated. I'm excited to get this fired up!

Frank

**Comment by RickStrahl** [comment]
Sorry I don't have any idea without seeing what the server is sending back.

I just double checked my test Wordpress blog and I don't have any issue with that. I'm thinking that you're not getting an actual XML response here since it talks about a DTD - that sounds like you are getting back perhaps an HTML response.

Make sure your username and password are correct by clicking on the check button. The button should turn green if you have the correct uid/pwd. The password should show blank.

**Comment by RickStrahl** [comment]
Actually looking at the error message it looks like the URL you have is bad. 

Make sure you have a fully qualified URL to your Web site. It looks like you're missing the domain name. `https://.com/XmlRpc.php` is certainly not valid.
