### ISSUE TITLE
Problem when Markdown Monster is launched via InfoQube

### ISSUE THREAD

**Issue by 1comvox** [RickStrahl/MarkdownMonster#1063]
InfoQube allows the use of a default markdown program for editing those document panes that use markdown. I am thinking to switching to Markdown Monster (MM) for this. So I set MM as the markdown editor in  IQ's "Tools>Options>Markdown Editor Path.".  The following odd thing takes place:

On one hand, when I have MM already open and seek to editor a document file in IQ that is a markdown file, it works fine.

But on the other hand, if MM isn't open yet, then -- upon IQ calling it -- MM launches with the correct file, **but MM now lacks one of its tool bars and otherwise misbehaves  and the file is displayed in a weird way**.  This is mystifying as  IQ is sending MM the correct parameter (and I couldn't find any parameter that would make MM behave this way). I know that IQ is sending the correct parameter because I tried replacing the MM path with the path to a batch file that catches the parameter IQ sends, displays it in a message box so I can see it, and then itself calls up MM with that parameter. When using that batch file, the result is the same as if I were using MM directly.

I don't have this problem when I use MarkdownPad2 as IQ's markdown editor, which works well with IQ but doesn't have the same range of features as Markdown Monster.

I find this mystifying as MM will work with the parameter IQ sends, but not if IQ sends the parameter. This doesn't makes sense. Nor does the fact that MM can launch in such a weird way that I can't figure out what command-line parameter would launch it in that way.  Maybe this is just a problem of my computer configuration, but it is hard for me to see what could cause this. 

This issue is  rather minor, as I simply have to launch MM first before having IQ call it. In that case, as I mentioned above, MM works fine. But something must be causing this problem, although it's not clear if its MM, IQ, or something in my configuration..

(I am using registered copies of  Windows 11,  Markdown Monster3.0.0.37, and InfoQube 122s.)

**Comment by RickStrahl** [comment]
Can you duplicate the behavior from the command line with mm.exe or markdownmonster.exe?

im not sure I understand what the issue is and what launch command causes it, so I’m going to need repro case.

**Comment by 1comvox** [comment]
Thank you for your reply. 

Oops, I didn't realize that mm.exe was also a file that could be used to launch Markdown Monster.exe, so I retried everything with mm.exe. So far I get the same results with MarkdownMonster.exe and mm.exe.

I also tried with a markdown file being passed to Markdown Monster with a total name and path of only 78 characters. No difference from my previous results. But I doubt think the problem is in the file names,  as the correct file is displayed in Markdown Monster -- it's how it is displayed, as well as what happens to Markdown Monster itself, that is the issue.

If Markdown Monster is already open, then everything works right when IQ calls it.

If Markdown Monster is not already open, then it calls up Markdown Monster, but it displays the file in a weird way, with even a row of Markdown Monster icons missing (I'm not sure what to call this, a taskbar? toolbar?). I have attached two pictures. The top one shows what the malfunction is like, and the bottom line is what happens when things go right.

(The pictures show I was using Tiles2 from Stardock. I tried again without Tiles2, and it didn't make a difference.)

Malfunction:
![MM malfunction](https://github.com/RickStrahl/MarkdownMonster/assets/143130462/cc3e1a3f-8983-49f2-a181-0f10328523dc)

Correct: 
![MM correct](https://github.com/RickStrahl/MarkdownMonster/assets/143130462/a895bd7b-3ab4-41de-bc15-7d8db09658dc)

As for the calling up Markdown Monster from the command line, everything works right.

This is true even if the command line is in a batch file -- so long as I don't have IQ calling the batch file.
In order to check if a suspect parameter was being passed to MarkdownMonster, I tried using a batch file, MarkdownMonster.bat, consisting of four lines:

echo off
echo %1
pause
C:\P\W\MarkdownMonster\MarkdownMonster.exe %1

I nstalled MarkdownMonster.bat in IQ via Tools>Options>Markdown Editor Path. 
This allowed me to see the parameter passed by IQ, which was the file name and path, as it should be.
The parameter was right, but again, the result depended on whether MarkdownMonster was already open or not prior to my calling it up with IQ.

Let me try to explain more about what I did in IQ. 
I have already tried to indicate how I configured IQ to use Markdown Monster.
What is left is how IQ edits "documents" attached to items in a grid.

In InfoQube I focused on the document pane of an item.
I use Menu>File>New>New Markdown FIle.
It asks for a file name, which I enter.
I can then add text to the file in one of two ways.
I can use Menu>Edit>Edit Document (it has the shortcut F2).  That works. But it edits the document pane with IQ's own internal editors.

But later I decide to edit this item with Markdown Monster, so I use
Menu>Edit>Edit With Markdown Editor.
Since I have configured IQ to use Markdown Monster, it calls Markdown Monster
and passes the name of the file which is displayed in the document window.

If Markdown Monster is already open (for example, if I opened it before calling up IQ, or at least before I tried to use it to edit the document pane), then the file opens properly in Markdown Monster.

If Markdown Monster is not already open, then it calls up Markdown Monster, but it displays the file with the malfunction I have described above.i

I hope this is clear; I don't seem to have the skill of clear technical writing.

**Comment by RickStrahl** [comment]
I understand what you're saying but I have no idea about what's different between how InfoCube is launching MM and how it's launched from the command line. The behavior should be the same.

There must be something about how InfoCube launches the application...

From the looks of it seems the previewer is not launching. We did have a brief problem in .36-.37 with parameters passed to the browser, but that should ALWAYS cause a problem not sometimes. Unless - you have multiple copies of MM installed and are actually launching a different executable that's a different version?

**Comment by 1comvox** [comment]
Thank you very much for the reply, and sorry to take so long to reply. I ended up at an impasse but good news-- **the problem is gone** in the latest version of InfoQube v122u., which plays well with Markdown Monster!

**Comment by RickStrahl** [comment]
I really wonder what the heck they could have been doing for this to fail. MM is pretty flexible - only thing I can think of is some weird permissions.
