### ISSUE TITLE
How does one register the software on a VM which is offline and can't be connected to the internet?

### ISSUE THREAD

**Issue by JimStamperJR** [RickStrahl/MarkdownMonster#1064]

**Comment by RickStrahl** [comment]
This is not supported at the moment. Registration has to be done online and a periodic check for license validity is performed. 

I hate to do this sort of thing, but unfortunately we had major issues with license violations and forcing online validation at least brought the license compliance to a reasonable level (still plenty of fraud happening).

I might implement one time license generation in the license manager which would allow generating an offline license for an existing license that's valid only on a specific machine but haven't quite figured out how to put that together.

**Comment by JimStamperJR** [comment]
Thanks for the update ... I really want to comply with license requirements ...

For now, I use a central repo (edit on compliant box - push code up) and download to non-compliant box for packaging ... I bit more work until a time I can properly license the VM machine and work from there.

Thanks again
-j
