### ISSUE TITLE
Feature request: Change tabs with the keyboard

### ISSUE THREAD

**Issue by tbleken** [RickStrahl/MarkdownMonster#1066]
In a new project I have several documents open at the same time, as separate tabs.
In most programs I can use Ctrl-Tab to go to the next tab, and Shift-Ctrl-Tab to go to the previous one. I would like to have this behavior in MdM also.

**Comment by RickStrahl** [comment]
That should work. There's a key mapping for this... and it works for me.

That said, it behaves a bit funky when the follow document in Folder Browser is enabled as focus switches to the folder browser, so a second ctrl operation is needed in that case. I have to look and see if I can fix that.

**Comment by RickStrahl** [comment]
I've fixed the tab behavior when **Track Active Document in Folder Browser** is enabled, so focus now stays in the editor if you tab across documents.

Note: It only works out of the editor, not from within the sidebar, as that is its own set of tabs (ie. tabbing across sidebar tabs).

**Comment by tbleken** [comment]
I will try it as soon as I can upgrade using Chocolatey, no hurry.
