### ISSUE TITLE
Portable MM is adding itself to the PATH

### ISSUE THREAD

**Issue by SMTStuck** [RickStrahl/MarkdownMonster#1067]
Rather self-explanatory and would be understandable if this was an installation, but why is the portable version of MarkdownMonster modifying the PATH (Windows, latest version of MM at time of writing)? Could we please not, or at least get an option included...

**Comment by SMTStuck** [comment]
Also, it is also reading/writing from %appdata%, again this is the portable version!

**Comment by RickStrahl** [comment]
Portable version will not use `%appdata%` **unless you are running from a protected folder**. It'll use portable settings.

We use `%localappdata%` for WebView temp file and registration to guarantee the app can run.
