### ISSUE TITLE
Previous Portable versions

### ISSUE THREAD

**Issue by jwoodard80** [RickStrahl/MarkdownMonster#1069]
Hello, I bought MM right before the grandfathered upgrade. I'm perfectly happy with the previous version, however, I lost the portable installer. When I look in the folders there is no portable version for those versions. 

Could you put a portable version of the last v2 build at least? 

Thank you! :-)

**Comment by RickStrahl** [comment]
You can use the Portable Chocolatey installs...

Or if you really want to, do the full install and install into your folder of choice. Don't auto-run. The open a terminal in that folder and do:

```ps
mmcli -setportable
```

You now have a portable install. You can copy and zip that as needed.

Can you send me a private message and if you really were right before the upgrade I can probably shoo you into a free upgrade :smile:

**Comment by RickStrahl** [comment]
I found a portable install for the last release, and I've added it to the archive as well.

https://github.com/RickStrahl/MarkdownMonsterReleases/tree/master/v2/v2.9

**Comment by jwoodard80** [comment]
Thank you for this!!! I meant to send you a private message but I wasn't sure how to. HAHA!

I went back to look at the license and it was about a month outside the upgrade window so it's ok. 

Thank you again for putting the portable out there! Great software! :-)
