### ISSUE TITLE
OpenAI Integration

### ISSUE THREAD

**Issue by HamedFathi** [RickStrahl/MarkdownMonster#1072]
Hello, 

As I shared a tweet in the X application I was thinking about OpenAI/Azure OpenAI and Markdown Monster integration.

I think using Markdown Monster for noting is a use case and OpenAI/Azure OpenAI integration helps us to summerise, make it short, or apply other scenarios.

For the UI maybe following what Microsoft did for Copilot for Word helps.

![image](https://github.com/RickStrahl/MarkdownMonster/assets/8418700/34562518-6b66-4a0c-a0f4-c18e6daa1a92)

[Microsoft 365 Copilot in Word](https://www.youtube.com/watch?v=C8WDGKaOt2s)

1. If I select the content by calling OpenAI (via a button, shortcut, or sidebar) I ask a prompt, and the result from AI is replaced with my current selected content. This helps us to summarize the content and replace it.
2. If I did not select anything by asking a prompt the result from AI should be added in the cursor position.

I think this is the way Word works with Copilot.

**Comment by RickStrahl** [comment]
First step - added image generation:

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/caacd571-5fa2-498a-9877-c7fb2192bd95)

This works well for image generation that can be embedded as it's really a free standing operation.

### For chat
I'm just not sure that it's any more efficient to use an inline chat prompt vs. opening up CoPilot or ChatGPT in a browser. I just don't see the benefit. Not sure how we could add context in a way that is cost effective as you'd have to bring your own API key.

Microsoft has large resource availability and already has document content as part of Word online. Just hard to match that with a third party account and your own key that you have pay for token usage.

**Comment by HamedFathi** [comment]
Thanks for your effort, actually I use Markdown Monster a lot and on my personal computer I don't have Word or Office so I was thinking for taking notes, summarizing and more I can count on Markdown Monster and Open AI integration for example copy/paste part of a doc in MM and ask for shorter text or ... I still believe this is a cool feature in MM and I cannot see any issue for setting my API key in MM.
