### ISSUE TITLE
Feature request: language setting per document

### ISSUE THREAD

**Issue by hermanslagman** [RickStrahl/MarkdownMonster#1073]
Right now, the language setting (spelling checker) is editor-wide.
Please make it document-specific.

**Comment by RickStrahl** [comment]
There's no official support for that in a document. Where would this be stored? We would have to force a setting into the document.

**Comment by hermanslagman** [comment]
Hi Rick,

Thanks for the reply.

Markdown-wise probaly not, although one can think of an optional entry 
in the frontmatter.

But there is nothing that restricts the application to keep track of a 
language (at least spell checker) setting of a document in its own 
metadata.

Regards,

Herman

------ Oorspronkelijke bericht ------
Van "Rick Strahl" ***@***.***>
Aan "RickStrahl/MarkdownMonster" ***@***.***>
CC "Herman Slagman" ***@***.***>; "Author" 
***@***.***>
Datum 18-12-2023 21:21:27
Onderwerp Re: [RickStrahl/MarkdownMonster] Feature request: language 
setting per document (Issue #1073)
