### ISSUE TITLE
Registration email address case sensitive

### ISSUE THREAD

**Issue by matthewDDennis** [RickStrahl/MarkdownMonster#1076]
When registering my license, I found that the email address was case sensitive which is not expected.

**Comment by RickStrahl** [comment]
Hmmm... no that's not correct. Email addresses are automatically adjusted to all lower case and set so when you put them in.

I just tried this with an all caps email address which is definitely not how it's stored and I registered just fine. 

Could it be something else?

**Comment by matthewDDennis** [comment]
This is happening on the License Activation Management page when I used an all caps email address that works when lower case.
![image](https://github.com/RickStrahl/MarkdownMonster/assets/8105715/81b79236-c174-48f5-b870-1917a6e13b78)

**Comment by RickStrahl** [comment]
Ah - OK that's a different story :smile:

The actual lookup should be case insensitive, but there's a post check that compares the stored value with the entered value.

I've updated that to ignore case, so that should now work.

BTW, I'm going to have to invalidate your license now that you've posted it here... :smile: I'll issue you a new one and send another confirmation.

**Comment by matthewDDennis** [comment]
Damn I’m an idiot. I masked my email and not my key.
Sorry, but thanks for invalidating it

My excuse is we’ve been fighting a DDOS attack.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by matthewDDennis** [comment]
I think you issues a new license for my old 2x upgrade rather than my 3x upgrade
The old license is still active and there is no new one available

**Comment by matthewDDennis** [comment]
My Old license is no longer working but I don't see a new license key.
Help!

**Comment by matthewDDennis** [comment]
I see the issue.  You created a new license for order `ab304bad` rather than `sjrxrf37`

**Comment by matthewDDennis** [comment]
You created a new license for my version 2 upgrade, not the version 3 upgrade

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by RickStrahl** [comment]
That shouldn't matter. Please check your email for the confirmation email I just resent. Use the last email that was sent as I had a reissued id but the account was still marked as revoked. It should be working now...

**Comment by matthewDDennis** [comment]
Thanks, all fixed.
Love the product.
Also love your blog posts as the are very informative and understandable.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
