### ISSUE TITLE
Add-in's Missing

### ISSUE THREAD

**Issue by EdCharbeneau** [RickStrahl/MarkdownMonster#1077]
I recently upgraded to MM 3.1.15.1 and the Add-in's toolbar is missing.

![add-in](https://github.com/RickStrahl/MarkdownMonster/assets/945168/20cf967a-d6ab-469d-ae60-63a30c242270)

![add-in2](https://github.com/RickStrahl/MarkdownMonster/assets/945168/9c23fe3c-19f0-4726-836c-f05ea4dfa758)

There are normally three add-ins available here by default:
- Screen Capture
- Snippets
- Weblog publishing

This version should also have:
- OpenAI Image Generator

## Settings

The "Disable Addins" setting is **unchecked**

## Logs

[MarkdownMonsterErrors.txt](https://github.com/RickStrahl/MarkdownMonster/files/13922879/MarkdownMonsterErrors.txt)

![add-in3](https://github.com/RickStrahl/MarkdownMonster/assets/945168/bf8fdc60-71d7-4b73-a686-1afcfed4fa56)

**Comment by RickStrahl** [comment]
Thanks Ed.

This is a result of the update to full .NET 8.0 runtimes - I missed moving the addins from their new deploy folders, although it was working for testing... oops.

I've updated the build process and republished for 3.1.16 for both download (ready now) and Chocolatey (when approved).

**Comment by EdCharbeneau** [comment]
Nice quick fix, thanks!
