### ISSUE TITLE
Couldn't find a compatible Webview2 Runtime installation to host WebViews

### ISSUE THREAD

**Issue by sangeetha0708** [RickStrahl/MarkdownMonster#1081]
I have downloaded and using FixedVersionRuntime.120.0.2210.144.x64 and using the Webview version -1.0.2210.55.

I Couldnt find the exact version for both runtime and webview version. and i have followed all the steps available in webview documentation.

but my facing the "Couldn't find a compatible Webview2 Runtime installation to host WebViews"

**Comment by RickStrahl** [comment]
What version of Windows are you on? 

Windows 10/11 should auto-update to the latest version and AFAIK when you're auto-updating you can't install any other version unless you install as Administrator.
