### ISSUE TITLE
Error when dragging an *.md file from Folder Browser Panel to Page

### ISSUE THREAD

**Issue by realB12** [RickStrahl/MarkdownMonster#1082]
When dragging a reference to an _*.md file_ from the  Folder Browser Panel to an already open page in edit-mode, the following error-message is displayed and the following written to the Log (see below). 

When I "continue" everything seems to work normally properly. 

It is just anoying to close the error-box over and over again. 

---

28.02.2024 09:02:05 - App: Object reference not set to an instance of an object.
Object reference not set to an instance of an object.
Markdown Monster v3.2.2.0
10.0.19041.1.amd64fre.vb_release.191206-1406 - de-DE - NET .NET 8.0.1 - 64 bit
Prime Computer PrimeMini 3, Intel(R) HD Graphics 520, hw-acc: True
de-CH - de-DE
C:\Users\reneb\AppData\Local\Markdown Monster
Portable: False
---
Microsoft.Web.WebView2.Core
   at Microsoft.Web.WebView2.Core.CoreWebView2PrivateHostObjectHelper.RawHelper.<>c__DisplayClass10_0.<SetAsyncMethodContinuation>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
System.NullReferenceException
---------------------------

![2024-02-28 09_02_11](https://github.com/RickStrahl/MarkdownMonster/assets/3463881/3123a692-77ce-430e-8965-e09a20b47455)

**Comment by RickStrahl** [comment]
Hmmm... I can't duplicate that behavior.

![DragMdFromFolderBrowser](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/a6bc2230-7cce-47e2-93be-86817c6afab9)


Is this what you're referring to?

**Comment by realB12** [comment]
It is not happening all the time, must after a while when I have clicked/doubleclicked something in  the file browser. But when it starts, it does not stop and appears with every single drag.
