### ISSUE TITLE
How to apply the KeyBinding Manager to invoke an external program configured for the `OpenWith...` command?

### ISSUE THREAD

**Issue by jbridgy** [RickStrahl/MarkdownMonster#1083]
I am glad to see that mm's KeyBinding Manager has been improved recently, especially because I hope that it would fulfill also the last part of feature request #947. However, I could not figure out how to extend `MarkdownMonster-KeyBindings.json` properly.

I also asked ChatGPT 4 which responded:

> In Markdown Monster version 3.2, you can bind any of MM's internal commands, **including custom commands like invoking an external program**, to a keyboard shortcut.
> ...
> However, the exact details on how to specify this binding for an external program invocation are not directly provided in the release notes.

Please give me an example which may also be added to the fine [Markdown Monster Documentation](https://markdownmonster.west-wind.com/docs/).

**Comment by RickStrahl** [comment]
It's not currently supported since the external programs are not bound to known commands.

However, after giving this some thought I think what I can do is add an option to provide a "KeyboardShortcut" to the entry in ExternalPrograms and then attempt to add that shortcut to the keybindings.

The main issue with a short cut is that there will be no context. So this would have to be generically tied to the editor surface. It won't work in the folder browser.

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/70ea1c28-e596-473a-a418-2d8ee7e45ff2)

**Comment by jbridgy** [comment]
Applying the "KeyboardShortcut" option for "ExternalPrograms" always to the current document (if one exists)
would be a pragmatic solution for me. However, for the sake of safety the current context could be taken into account as follows:

- If no specific file can reasonably be associated with the current context then mm could ignore the shortcut (or invoke the external program without "Args"). Example: The Table Editor is closely related to the current document. Nevertheless it seems not reasonable to edit the current document with an external editor while the Table Editor is open. Furthermore the option "SaveBeforeActivation" would probably be hard to handle in the context of the Table Editor.

- Otherwise the external program is invoked. If the line number (`{1}`) and column number (`{2}`) are not available in the current context then use the default value 1.

**Comment by RickStrahl** [comment]
The keyboard bindings are not global - they are tied to the editor anyway so they won't work outside of that context regardless. There are bindings in the UI that forward to other tasks, but those are implementation specific and is not something that you would be linking to. External programs thus are tied to the editor surface only. So it won't work in the table editor.

The External program shortcuts are added to context menus in various contexts so they may apply to files in the folder browser, the editor and a few other places, but that's explicitly made so by the application. There's no way to make this more generic. As it is it'll be hard enough to find key combos that can actually be used and not interfere with existing behavior.

I've renamed the key to `EditorKeyboardShortcut` to make it more explicit - the editor opens the file and if line and row are available they are applied (depends you your command line format ie. `"{0}:{1}:{2}" -g` for example for VS code).

**Comment by jbridgy** [comment]
I tested the new option of `ExternalPrograms` with mm v3.2.5 and found the following issue:

Pressing the **keyboard shortcut** configured with the new option `EditorKeyboardShortcut` and clicking the corresponding **context menu item** such as `Open...>Edit With MyFavoriteEditor` do not behave identically if the current document has been modified and the external program is configured with `"SaveBeforeActivation": false`.
The former shows the following dialog as expected:
![image](https://github.com/RickStrahl/MarkdownMonster/assets/98041047/159ad514-66d8-48d1-abe2-d770861be3b2)

The latter opens the modified document with the external program immediately, without confirmation. This is risky when you switch often between mm and a source code editor, as I do.

**Comment by RickStrahl** [comment]
Ah that's a good point. I have to move the original code into the command and then use the command in both places. Currently the shortcut menu option is inline.

Will take a look.

**Comment by RickStrahl** [comment]
Updated in 3.2.6

**Comment by jbridgy** [comment]
It works like a charm. Thank you so much! I can use this little time saver very often when writing documentation.

**Comment by RickStrahl** [comment]
Thanks for the feedback! Aloha.
