### ISSUE TITLE
How to enter a tab character (`\t`) in the "Import CSV to Markdown Table" dialog?

### ISSUE THREAD

**Issue by jbridgy** [RickStrahl/MarkdownMonster#1086]
The Table Editor of MM v3.2.5 has a `Load from...` button which allows a CSV file or the Clipboard to be imported.
However, I could not figure out how to specify a non-printable character such as tab (`\t`) in the following dialog:

![image](https://github.com/RickStrahl/MarkdownMonster/assets/98041047/5f46df38-76f3-427e-abed-f4ab12d1403d)

It would be nice if MM offered radio buttons for the most commonly used CSV separators including `,` , `;`, `|` and `\t`.
Furthermore I suggest that MM uses the **most recently used CSV separator** instead of `,` as default value.

**Comment by RickStrahl** [comment]
Added a dropdown that allows selecting common values and set up the input to support \t .

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/f83a9fa8-b808-4aae-b617-f0db6a27da23)
