### ISSUE TITLE
Hello! When will version 3.3 be released?

### ISSUE THREAD

**Issue by zhouxinghong** [RickStrahl/MarkdownMonster#1087]
Hello! When will version 3.3 be released?
I want to verify whether version 3.3 has solved the long-standing problem.

**Comment by RickStrahl** [comment]
Seriously?

**Comment by zhouxinghong** [comment]
Um! Yes.

**Comment by zhouxinghong** [comment]
I remember I reported a related issue to you, but I'm not sure if you have resolved it.
