### ISSUE TITLE
Outline numbering in preview & TOC

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1089]
when writing larger documents with many levels of headings, it's sometimes easy to get lost. It can be difficult to see in the preview which heading level you have (OK, can see that in the Markdown if synced). It is also difficult to see where in the overall structure you are. Outline numbering (like pandoc's "numbersections") would be great, both in the preview and (also optionally) in the TOC

![image](https://github.com/RickStrahl/MarkdownMonster/assets/14021625/4ac4d9ca-0a9d-4472-a661-33973a8695ea)

**Comment by RickStrahl** [comment]
Can't you use the  Document Outline side bar? Click on the second icon down on the left.

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/ad9bc979-bc49-4465-83da-295be5444a96)

Maybe a useful feature would be to add the outline level to the tooltip (currently it only shows the ID of the header element in the output).

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/b4f66718-a574-4c56-b155-1468b8b30390)

**Comment by RickStrahl** [comment]
Maybe something like this is more ubiquitous:

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/9bb75468-755f-4268-8935-83fcc2976c0a)

**Comment by internationils** [comment]
It's less about the heading level itself, but the numbering (enumerating) inside each level. Like "Event Syntax to PDF file" would be 1.3.1.5
I like the small numbers that you have, if they can count at each heading level that would be good enough, you can always look at the parent levels to see where you are. So next to "Event Syntax to PDF file" there would be a 5, etc.

**Comment by RickStrahl** [comment]
That kind of numbering is not something that's supported in Markdown at least not with headers (you can get something like that with lists). And I'm not sure how that would be useful in a bookmark type view.
