### ISSUE TITLE
Minimum tab width for easier closing of many tabs

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1090]
Have an option to have the tabs with a minimal (equal) tab width as long as there is space on the screen. Longer filenames would have larger tab widths to not have truncated filenames (and have to rely on tooltips). This lets you close multiple tabs faster (many web browsers do this) by clicking on the same spot. When you have too many to fit on the screen, then make them as bigger / smaller depending on their filename (current behavior). 
I'm currently working with many files in parallel where I have to link and cross-reference, so being able to close tabs more quickly would be quite helpful. I would specify a minimum width that applies to most filenames and the ones that are longer then have wider tabs.

**Comment by RickStrahl** [comment]
I don't think that's something I want to implement. Most common editors don't do this and it's a pain to implement.

If you want fast tab closing you can use command keys (Ctrl-W). I see you have another related issue (#1097)  to Ctrl-W and focuse which has been addressed.

**Comment by internationils** [comment]
OK, fair enough, thanks. Feel free to close.
