### ISSUE TITLE
Click-and-drag moving moves wrong file

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1091]
When clicking on a file and wanting to drag it up or down to another folder, MM (most of the time) selects the file above or below and moves that file instead. It seems that the dragging after selection takes a little time to start so that the file directly above / below the one you want is selected and dragged.
Currently, I click on a file and drag sideways a little before dragging up / down to avoid this issue.

**Comment by RickStrahl** [comment]
Yeah, this is really screwed up... 

I think this is a regression, when the way files are selected was changed. What's happening is that the file selection is made at the mouse move operation rather than when initially clicking on an item to drag.

**Comment by RickStrahl** [comment]
Fixed logic to handle the correct selection by capturing the initially clicked item(s). 

Now works for single selections. 

3.2.17.3

**Comment by internationils** [comment]
Yep, seems to work in 3.2.17.3, thanks!
