### ISSUE TITLE
New last folder or file in a tree or directory sorts incorrectly

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1094]
- Create a folder
- Create subfolders s10_aaa s20_bbb s30_ccc
- Create a subfolder s_25_b2 - works
- Create a subfolder s40_ddd - gets sorted / shown before s30_ccc
- See s50 and s60 before s40 in the screenshot
- NOTE: ALSO... same thing happens when renaming files

![image](https://github.com/RickStrahl/MarkdownMonster/assets/14021625/7d67eb9b-6352-49d7-9f4b-7d9656aad1a4)

**Comment by internationils** [comment]
Update: I created the s99_ folder on my tablet (in Dropbox), and when it showed up in MM it also showed up not sorted correctly (i.e. second to last instead of last in that folder):
![image](https://github.com/RickStrahl/MarkdownMonster/assets/14021625/ba422997-223a-42b9-89a9-1fc6060c2b02)

**Comment by internationils** [comment]
This also applies when renaming files to the last file in the directory. It also shows up as second to last.

**Comment by internationils** [comment]
I inserted a new file in a directory (save from a web browser), and that file which should have been last also shows as second to last.

**Comment by RickStrahl** [comment]
Yeah I'm not going to worry about this - too trivial to worry about. Refresh puts this right.

**Comment by internationils** [comment]
Could you then "fake-fix" it with an automatic refresh when a new file / folder is added or detected?
