### ISSUE TITLE
Moving a folder shows a ".." subfolder that leads to c:\

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1095]
Moving a folder shows a ".." subfolder right after the move. When clicking this, it takes me to C:\
- make a folder
- make a subfolder t10_aaa and t20_bbb
- move t20_bbb into t10_aaa
- see screenshot
- FYI, same thing happens with files

![image](https://github.com/RickStrahl/MarkdownMonster/assets/14021625/f1e973d5-2bbe-41b7-827c-0e2b6b1bf690)

**Comment by internationils** [comment]
Update: the ".." folder also showed up when I created a subfolder on my tablet (in the dropbox), when going to the folder in MM the first time. After closing and re-opening MM it was gone.

![image](https://github.com/RickStrahl/MarkdownMonster/assets/14021625/ef8a2469-c645-4cab-ba78-519a6369e020)

**Comment by RickStrahl** [comment]
Please check in 3.17.3 which has drag and drop fixes.

Going to close this, please re-open if still a problem after the update.
