### ISSUE TITLE
Ctrl-W closing a window does not refocus input

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1097]
- open a few tabs
- go to the last one
- CTRL-S to save, then CTRL-W to close (works
- CTRL-S on the next window does not work, even though it is shown to be active by the tab color

This is useful when saving and closing a lot of files.

**Comment by RickStrahl** [comment]
Ok I can duplicate that although it's a bit intermittent - sometimes focus resets others it doesn't. I've added an explicit focus reset to the newly activated window.

**Comment by RickStrahl** [comment]
Fixed in 3.2.9.2
