### ISSUE TITLE
Can't add external handler program

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1098]
I've tried adding notepad++ both through tools->settings as specified in https://markdownmonster.west-wind.com/docs/_6if1ephjm.htm and also through right clicking on a file and Open ... -> Edit External programs. I get taken to the line
```
"ExternalPrograms": [],
```
and then edit it to
```
  "ExternalPrograms": [
  {
    "Name": "Open in Notepad++",
    "Executable": "C:\Program Files\Notepad++\notepad++.exe",
    "Args": "{0}",
    "Extensions": "TEXT"
  }
  ],
```
...but when saving and closing, then reopening it reverts to the intial [] state. After noticing that I need double backslashes "\\\\" I tried that and it saved it and expanded it to
```
  "ExternalPrograms": [
    {
      "Name": "Open in Notepad++",
      "Executable": "C:\\Program Files\\Notepad++\\notepad++.exe",
      "Args": "{0}",
      "SaveBeforeActivation": false,
      "Extensions": "TEXT",
      "EditorKeyboardShortcut": null
    }
  ],
```
... so it saved, but didn't work.

It would be great to have a) an error message if the config is invalid (I was wondering why the initial version never got saved) and b) it still doesn't work, i.e. nothing shows up:

![image](https://github.com/RickStrahl/MarkdownMonster/assets/14021625/c9293444-2952-4b45-a4f4-3db2b1c34191)

**Comment by internationils** [comment]
Ah, figured something else out. It DOES work on .sh files (I guess those are TEXT?), it does not work on .m4 (preprocessor) files. Adding `"m4": "m4",` to the `EditorExtensionMappings` works and notepad++ is shown.

What's strange: I can click on the .m4 file to view and edit it in MM, but clicking on a .sh file (which is already listed in the mappings) does nothing in MM.

Any chance you can clarify that in the documentation link above?

**Comment by RickStrahl** [comment]
It looks like there is a special case on .sh as an executable file that doesn't need to be set.

I've adjusted the logic so that it's treated like a text file as normal. You should now be able to single click to a see a preview in the editor then click in (or double click) to keep the file in the editor.

This should now work for all the extensions that are mapped - previously there was only some selected formats that were shown this way and you had to double click.

**Comment by RickStrahl** [comment]
I've also added an additional pre-save check when saving the JSON. If the JSON is invalid you will now see a status bar notification and the file state will stay as changed.

**Comment by RickStrahl** [comment]
Updates are in 3.2.9.3+

**Comment by RickStrahl** [comment]
So tried out setting up Notepad++ as an external program and it works fine now (probably did before too except for the saving issues most likely).

```
  "ExternalPrograms": [
    {
      "Name": "Open in Notepad++",
      "Executable": "C:\\Program Files\\Notepad++\\notepad++.exe",
      "Args": "\"{0}\"",
      "SaveBeforeActivation": true,
      "Extensions": "TEXT,FOLDER",
      "EditorKeyboardShortcut": "Alt-F9"
    },
  ]
```

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/7faca361-fe72-4536-b69f-f831d026bd56)
