### ISSUE TITLE
Nice to have: Multiple Metadata sets

### ISSUE THREAD

**Issue by weggetor** [RickStrahl/MarkdownMonster#11]
Hi Rick,
I often post my blog posts to different blogs (my personal blog, dnn-connect.org blog, dnnsoftware.com blog). Would be nice to have the possibility to include multiple metadata for the different blogs (blog url + post-id)

**Comment by RickStrahl** [comment]
How would you envision that to work?

In theory I suppose MM could switch to a proper XML structure that includes a collection of blog-postId items but frankly I think this makes it more confusing for most users.

As it is you can currently post to multiple blogs easily enough if you know the post Ids. Clearing the PostId will post a new entry to another blog easily enough.

Maybe something like a <notes></notes> field that is maintained would allow you to at least store the post ids or notes on what to use?

**Comment by weggetor** [comment]
![2016-06-22_23-50-32](https://cloud.githubusercontent.com/assets/5718742/16285091/a89646d0-38d4-11e6-993d-eac25465e965.png)

If you put the combobox with "Web Site to post to:" to the top and "bind" the other information like abstract, postId etc. to this information in the metadata, its simple and clear, even for the user. Changing the Website changes all corresponding metadata.

**Comment by RickStrahl** [comment]
Ok... let me noodle with that.

**Comment by RickStrahl** [comment]
I'm going to close this out as this is something that doesn't seem a very common requirement.
