### ISSUE TITLE
Suggestion: ChangeLog link in Help menu

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1103]
Hi, it would be great to have a link to the latest ChangeLog in the Help menu, else you need to search for it... I would put it right under "Check for a new version". Maybe a link to the github page too?

Google first shows the old https://github.com/bc3tech/MarkdownMonster/blob/main/Changelog.md ... you have to go via https://markdownmonster.west-wind.com/docs/_4ug0n96ns.htm to find the current https://github.com/RickStrahl/MarkdownMonster/blob/main/Changelog.md

![image](https://github.com/RickStrahl/MarkdownMonster/assets/14021625/0022c05b-8312-40dd-aeee-1eac9dc62c6e)

**Comment by RickStrahl** [comment]
Good suggestion. Added:

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/74fe4db8-3fb3-4c2b-b113-af56e5b55711)
