### ISSUE TITLE
Feature Request. .ahk Autohotkey syntax highlight

### ISSUE THREAD

**Issue by indigofairyx** [RickStrahl/MarkdownMonster#1107]
im new to coding, been playing with Autohotkey for about 5 months. love it!

and even newer to the wonderful world of *Markdown*, i decided i need to learn this 4 days ago. ive tried about 5 MD editors in the past week, liking this on the best so far, but i digress.

one feature that none of them have had, even obsidian with its 1600 plugins, has been syntax highlighting for ***Autohotkey.***

this might be a Feature Request i can do myself, just not sure how or where to put the syntax outlines.

theres [this](https://github.com/floegerer/brackets-autohotkey/tree/master) .ahk repository on github, as well as a [couple dozen more](https://github.com/search?q=autohotkey%20syntax&type=repositories) User Defined Languages, i have loaded a few of them into Notepad++ using `.xml` in the %APPDATA% folder.

is there way i add or amend these into MM? or make this a feature request?

thanks
tavier

**Comment by RickStrahl** [comment]
MM isn't really meant as a general purpose editor so I think you wouldn't use that for editing of your keyboard shortcut file. If you have `.ahk` linked in the Windows to a specific editor (ie. Notepad++ or VS Code) in Windows, double clicking the file in the file browser should open it in that editor.

**Comment by indigofairyx** [comment]
oh, im not asking about opening or editing them. i dont want to edit code in MM, only MD. i will stick to vscode, scite or npp for that.

i should clarify a bit more.

what i was asking is for syntax highlight for .ahk in code blocks. [i think i forgot to mention code blocks altogether in the first post. im sorry i was vague]

for example... with screen shot... top block is `xml` . the bottom block is `ahk`. [im noticing github is coloring the syntax automatically here] in MM the `ahk code block` is simple white text.

```xml

<colours id="Default">
 	<element id="DefaultIconName">MusicBee</element>
	<element id="TitlebarActiveForeColour" bg="brightgreen" />
	<element id="TitlebarInactiveForeColour" bg="text_inactive" />

	<element id="ApplicationBackColour" bg="84,60,0" />
	<element id="WindowBackColour" bg="grey_4" />

	<element id="HeaderBar" bg="grey_3" bg2="11,12,11" fg="142,140,194" bdr="126,92,0" />
```

```ahk
!^b::
    send ^c
    thisvar := clipboard
    thisvar := "<!--" . thisvar . "-->"
    clipboard := thisvar
    send ^v
return
```


![image](https://github.com/RickStrahl/MarkdownMonster/assets/126439010/229c0379-24aa-44d4-9f25-922fe73a8ade)

compared to NPP using User Defined Languages just for syntax highlighting.

![image](https://github.com/RickStrahl/MarkdownMonster/assets/126439010/457d8291-c181-4590-ac48-1b56a9882934)

**Comment by RickStrahl** [comment]
There are only a few common languages that are supported with inline highlighting, not even close to all of those that syntax support using editor files. 

Reason is that any language added bloats the size of the Markdown display parser for the editor and as it is the Markdown syntax file is massive so we won't be adding anything to it unless it's a very widely used language.

If I recall supported languages are

* Html
* XML
* JSON
* JavaScript/Typescript
* CSS
* CSharp
* Powershell
* Bash
