### ISSUE TITLE
Statistics in footer bar don't change when opening a file

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1109]
When clicking on a file in read-only mode or double clicking to edit, the statistics (lines, words, characters etc.) don't change. They only change once you actually click in the editing window. It would be very useful to have those change immediately when the file is opened to be able to compare versions of a text.

**Comment by RickStrahl** [comment]
Ok I've added the explicit stat refresh when a new 'preview' tab is created.

Also: If you want document information the better way to see that is to hover over the file in the Folder Browser, or over the tab.

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/0b3ae267-97f7-4dba-bd43-b7e343260c5e)
