### ISSUE TITLE
When tab focus changes, change the focus in the file selector on the left as well

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1110]
I often jump between tabs. It would be great to have an option to allow the highlight in the left file explorer window to focus on the file that you select in the tab. Sometimes I have files with the same name in different folders (readme.txt for example) and then the only way to see which one it is is to hover over the tab title for the tooltip vs. just being able to look on the left side.

**Comment by RickStrahl** [comment]
There is:

![Uploading TrackDocumentInFolderBrowser.gif…]()

**Comment by internationils** [comment]
OK, just saw this, thanks! 
Quick Q... what are you using to make these screen capture videos?

**Comment by RickStrahl** [comment]
ScreenToGif
