### ISSUE TITLE
Repeated ctrl-f or ctrl-h should jump to next occurrence

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1113]
Repeated ctrl-f or ctrl-h should jump to the next occurrence. Sometimes this works, sometimes this doesn't. In the screenshot below it doesn't. I haven't figured out the logic behind it yet though...

![image](https://github.com/RickStrahl/MarkdownMonster/assets/14021625/1acfba3c-a7fa-496e-b566-61bbdcac688b)

**Comment by RickStrahl** [comment]
F3 is the command you're looking for. It'll repeat the last search or replace operation.

Well - it looks like the WebView is interfering with that. For now the menu or the buttons can be used.

**Comment by RickStrahl** [comment]
So I fixed the F3 issue (mostly) so F3 now works as it should from inside of the document.

I also made Ctrl-F (or mapping) work for repeating a find if the find dialog is open.

I did not do anything with Ctrl-H Find and Replace since the action you take there is ambiguos. However, if you press Ctrl-F to find again it will go to the next item.

3.2.17.2

**Comment by internationils** [comment]
Thanks! Everything I filed the last few days was with 
![image](https://github.com/RickStrahl/MarkdownMonster/assets/14021625/4b93b06e-58b9-49c8-9847-84a7cefce4f2)

**Comment by RickStrahl** [comment]
BTW, You can click on the  info icon to copy version info to the clipboard.

For these fixes I'm doing right now, you'll need to update to the latest builds frequently :smile:

**Comment by internationils** [comment]
Good hint, thanks, will do : )

**Comment by RickStrahl** [comment]
I removed the Ctrl-F find next operation. I thought I had posted, but I don't see the comment here. 

That's not the behavior you want - you want Ctrl-F to jump you to the find window so at any point you can always get back. if Ctrl-F finds next then you end up with the cursor in the document, which is confusing and not desirable. Checking other tools they don't do this either. All use F3/Shift F3 for Find Next/Previous.

You can also use ENTER in the find dialog to keep searching forward, or the arrow buttons of course.

F3 and Shift-F3 work now, but only if you're in the document. Inside  of the control there's a bug in the editor control that brings up the Edge search panel - I don't know how to disable that at this point.


In theory those keys should have (and have in the past) worked automatically in ACE Editor, but I think Edge changed behavior to support these keys and they are somehow overriding the explict overrids the ACE provides.

IAC, it does work with the exception of F3/ShiftF3 when focus is in the edit box.

**Comment by internationils** [comment]
OK, thanks, makes sense, feel free to close.
