### ISSUE TITLE
Can open file multiple times

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1114]
Clicking on a file multiple times sometimes opens the file multiple times:

![image](https://github.com/RickStrahl/MarkdownMonster/assets/14021625/21f2f6bb-c662-4988-81cf-a74b6aad04d6)

In this case, the backup files contain data (and show it in the tabs), the original file does too, but both tabs show no data:

![image](https://github.com/RickStrahl/MarkdownMonster/assets/14021625/83b098a2-5f26-47d1-8067-a27a2617bc85)

This may be a consequence of a previous rename.

**Comment by internationils** [comment]
The backup files are actually the "correct" edited versions with a little more text:
![image](https://github.com/RickStrahl/MarkdownMonster/assets/14021625/18a4c370-0246-4537-a255-ad7968da67ec)

**Comment by RickStrahl** [comment]
The files shouldn't be named like this anymore unless you're running an older version. The backup files should be `~filename.md.saved.bak` or `~filename.md.saved-3ut21t.bak`...

Can you please download the latest version. Also backup files should clean up better with those same changes.

**Comment by RickStrahl** [comment]
Going to close this because this is likely related to one of the other issues reported. You can re-open if you still see this with the updates.

**Comment by internationils** [comment]
This was on 3.2.16, I just upgraded to 3.2.17.2... will see how it goes. Thanks for all of the quick fixes! These are definitely making working with MM more robust and easy.

**Comment by RickStrahl** [comment]
Thanks for your help!
