### ISSUE TITLE
FB refresh icon shows selected when unselecting FB sync

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1115]
So here's a small buglet... when setting and unsetting sync in FB, the refresh icon gets a border. Not the most critical of bugs, but ... : )
![image](https://github.com/RickStrahl/MarkdownMonster/assets/14021625/2ef27a2c-446d-461b-bc7f-7f3a8cc4b1f3)

**Comment by RickStrahl** [comment]
Fixed
