### ISSUE TITLE
Have a way to keep read-only files open in tabs (pin?)

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1116]
I have some image files in my directory that I use for reference, and I would like to keep those open in tabs. The problem is that they (obviously) open read-only, and then disappear as soon as I click to another file. It would be great to be able to "pin" them to stay in a tab.
I guess this might be problematic since you could theoretically pin a read-only text file that you can then accidentally edit.

**Comment by RickStrahl** [comment]
I think you're trying to run MM into a File manager :smile:

You can use the various Open Links to open the images in your image viewer - that's as close as you're going to get with this.

**Comment by internationils** [comment]
OK fair enough : )
But one buglet: the status bar at the bottom should probably clear (or show the graphic file information instead)... it retains the last text file status content.
