### ISSUE TITLE
Different context menu after first opening MM

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1118]
When first opening MM and right clicking on a file (I wanted to rename it), a shorter context menu appears. I tried this on several different files (no extension, MD, txt, etc.) and all showed the same menu. After opening a file once and closing it, the normal context menu showed up.

![image](https://github.com/RickStrahl/MarkdownMonster/assets/14021625/bb1c92a8-3afc-4b9c-94de-c4b685ca68a3)

**Comment by RickStrahl** [comment]
Issue is related to #1119.
