### ISSUE TITLE
Enable "Open link in new window" by default

### ISSUE THREAD

**Issue by kkbruce** [RickStrahl/MarkdownMonster#112]
Can add new setting to enable "Open link in new window" by default?

**Comment by RickStrahl** [comment]
Already there - use the `RenderLinksExternal` property in the Settings.

**Comment by kkbruce** [comment]
Hi 

I try setting RenderLinksExternal to true, but I not see "Open link in new window" default, 
This is my capture: http://giphy.com/gifs/markdownmonster-3o7P4ycjA6W8zyUMOA
MM Version: 1.1.8

How enable it?

Thanks.

**Comment by RickStrahl** [comment]
Oh I see what you mean. The switch does something different - it renders all URLs embedded in the document as external links (target="top"). That option is still there and will continue to the way it works now.

Implemented a `LastLinkExternal` configuration option that remembers the last setting you used.

3a5b6d71de8fbf62b2580b47cec0a739a0260133

**Comment by RickStrahl** [comment]
Please check 1.1.14 to see if this addresses your request.

**Comment by kkbruce** [comment]
Yes, Love it.
Thanks.

**Comment by RickStrahl** [comment]
Thank you for pointing out.
