### ISSUE TITLE
Preview window always opens

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1123]
The preview window opens every time I open a file or switch windows. I need to close it every single time.
And I can't resize it after that. 
And when switching files it does not update the preview.
If I f12 "officially" open it it resyncs, then if I close and reopen I can resize it.

Markdown Monster v3.3.5
64 bit • .NET 8.0.6
Microsoft Windows 10.0.22631
WebView Runtime: 125.0.2535.92
WebView Sdk: 1.0.2478.35

**Comment by RickStrahl** [comment]
What do you mean exactly? The external preview window? 

Turn off the external preview flag on the preview window and make sure your settings actually save (ie. you're not storing the configuration in a read-only folder).

**Comment by internationils** [comment]
No, the internal preview window...

**Comment by internationils** [comment]
Not part of this bug, but I'll put it here... one file is greyed out for some reason, but no different from the others and opening / working with it is fine...
![image](https://github.com/RickStrahl/MarkdownMonster/assets/14021625/05a154a1-86dc-4199-96cd-449693470625)

**Comment by RickStrahl** [comment]
I see it now. 

Yup that's a regression related to the preview zoom updates in the recent release.

Fixed for next update.
