### ISSUE TITLE
Error in UI

### ISSUE THREAD

**Issue by pabbasi** [RickStrahl/MarkdownMonster#1125]
I believe that rather than <strong><kbd>Shift</kbd>+<kbd>F3</kbd></strong> being labeled the same as the action associated with <strong><kbd>F3</kbd></strong> as shown below:
<code>Find previous occurrence</code> rather than:

![image](https://github.com/user-attachments/assets/1b92f2fc-dae3-44bd-baaf-25bb47d74c67)

it should be labeled: <code>Find previous occurrence</code> instead.

**Comment by RickStrahl** [comment]
Thank you, fixed for next release.
