### ISSUE TITLE
Prevent empty copy/cut from overwriting paste buffer

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1127]
When copy-pasting, it can happen that you
- select some text
- ctrl-C (or ctrl-X) it
- switch to a different tab (or somewhere in the same tab)
- click where you want to paste
- accidentally hit ctrl-C instead of CTRL-V

This deletes the paste buffer since nothing is selected. If nothing is selected, ctrl-X/C should not touch the paste buffer.

**Comment by RickStrahl** [comment]
I've run into this as well, but... I don't think it's wise to break standard copy/paste behavior for this. There are legitimate reasons for wanting to clear the clipboard with empty text.

**Comment by internationils** [comment]
I'm switching a lot between a laptop keyboard and a full-sized normal keyboard and it's driving me nuts : ) That said, your logic makes sense. An Option might be nice though...
