### ISSUE TITLE
It is very frustrating that every time you start `MM` and exit `MM`, `MM` initializes the settings file causing user settings to be lost.

### ISSUE THREAD

**Issue by zhouxinghong** [RickStrahl/MarkdownMonster#1129]
It is very frustrating that every time you start `MM` and exit `MM`, `MM` initializes the settings file causing user settings to be lost.

Hi friend! It is very frustrating that `MM` initializes the `MarkdownMonster-KeyBindings.json` and `MarkdownMonster.json` files every time you start `MM` and exit `MM` resulting in a loss of user settings.

https://github.com/user-attachments/assets/9ff1032c-7018-47d9-a206-2ed39ca42b39

Windows 10 19044
MM 3.4.0
File Path F:\tool\MarkdownMonsterPortable\PortableSettings

**Comment by RickStrahl** [comment]
I can't duplicate what you describe.

Since you're using the portable version, you need to have permissions to write files in the folder if you use the Portable version. If you can't figure that out, use the full version instead and it'll put it into a location that is writable.

Markdown Monster Portable Version[](https://markdownmonster.west-wind.com/docs/_4t90rhfy9.htm)

**Comment by zhouxinghong** [comment]
The same thing happens even if you install the full version of Markdown Monster.exe... You can try...

**Comment by RickStrahl** [comment]
Well I don't know - look at the file dates. If they are not updating after exiting then there's a problem writing out the configuration.

I have no issues with saved settings and I've not seen anybody complaining that the settings are not updating

Look where the settings are actually going to in your Settings:

![image](https://github.com/user-attachments/assets/a8750a55-736d-433a-a4ea-969165321be0)

This will point at the actual location that is being used when MM is running and this is the folder that has to have permissions for your account to be writing.

**Comment by zhouxinghong** [comment]
Or I can re-download Markdown Monster.exe to see if the situation improves...

**Comment by zhouxinghong** [comment]
There is another problem that you need to fix.
https://github.com/RickStrahl/MarkdownMonster/issues/1130

**Comment by zhouxinghong** [comment]
![image](https://github.com/user-attachments/assets/a2c91010-449b-48dd-9f8a-c37f8329bb98)

![image](https://github.com/user-attachments/assets/c6bba969-8e13-44a3-aa4d-147cf243e25e)


https://github.com/user-attachments/assets/190f82db-a570-4f61-ad47-d2e1ae88f795

I re-installed Markdown Monster.exe. This is the latest problem reproduction process.

Markdown Monster.exe Version:
3.4.4

**Comment by zhouxinghong** [comment]
I re-installed Markdown Monster.exe. This is the latest problem reproduction process.

https://github.com/user-attachments/assets/a5b2cc75-fb7a-4e7e-bea0-d03e86af3a9d


When I started the Markdown Monster program, the MarkdownMonster-KeyBindings.json file was reset.

When I closed the Markdown Monster program, the MarkdownMonster.json file was reset.

**Comment by zhouxinghong** [comment]
I re-installed Markdown Monster.exe. This is the latest problem reproduction process.

https://github.com/user-attachments/assets/a5b2cc75-fb7a-4e7e-bea0-d03e86af3a9d


_**When I started the Markdown Monster program, the `MarkdownMonster-KeyBindings.json` file was reset.**_

_**When I closed the Markdown Monster program, the `MarkdownMonster.json` file was reset.**_

**Comment by RickStrahl** [comment]
Don't know what to tell you. 

I can't duplicate any of that. Perhaps you have Anti-Virus keeping you from writing out updates to files in that folder.

I've not heard this from anybody else, and it certainly isn't happening on my end. MarkdownMonster.json gets re-written with current settings when MM is shut down. The keybindings file is written after loading keys.  If the keybindings file has invalid data in it it will re-write as default. Same with the main configuration file. But once it's been re-written any changes you make should be written and that should be valid.

If that's not working I don't know what would cause that from MM's end unless there's something else interfering on your system. If old files are being re-written I would suspect anti-virus.

**Comment by zhouxinghong** [comment]
You just need to change the write mode of program startup, program shutdown, and program exit to read-only mode only, and all problems are solved.

**Comment by zhouxinghong** [comment]
You just need to change the write mode of the `MarkdownMonster-KeyBindings.json` and `MarkdownMonster.json` files at program startup, program shutdown, and program exit to read-only mode, and all problems will be solved.

**Comment by RickStrahl** [comment]
No - those locations should be writable in the system. If you files are not writable or read-only for some crazy reason in your configuration that's up for you to fix.

Those folders are explicitly designed to support writable user data per Windows specs.

**Comment by pa-0** [comment]
This may help.  Open a command prompt. (You _might_ need to run as administrator). Use the following command to reset the permissions for the "Markdown Monster" folder in the `Roaming` folder:

```
icacls "%AppData%\Markdown Monster" /reset /t /c /l
```

**Comment by RickStrahl** [comment]
@pa-0 Wonder what would reset the permissions in those folders in the first place.

If I had to guess I'd say it's some sort of Anti-Virus screwery that's doing this.

Regardless, that's not something that MM can or should fix - that's a system configuration issue, so closing.

**Comment by pa-0** [comment]
I definitely would'nt rule out AV, but I've encountered something similar on my work laptop a few times, e.g., when attempting to update VS Code. This was the fix for me, so it's my first go-to whenever there is a permissions-related error during file operations.
