### ISSUE TITLE
Suggestion/Comment on documentation: about weblog publishing

### ISSUE THREAD

**Issue by awright18** [RickStrahl/MarkdownMonster#113]
This probably speaks more to my ignorance than the documentation, but just wanted to let you know it took me 3 days to figure out what I needed to add /xmlrpc.php to the end of my wordpress URL in order for the posting to work.   After figuring it out and re-reviewing the docs I noticed a page called "Some Common MetaWeblog API Endpoints" in the docs.  Maybe the Setting up a weblog page could link to that one to help others in the future.  Thanks for creating this.

**Comment by RickStrahl** [comment]
Yeah I'm aware of this :-) I can see in the error logs that quite a few people are tripping up on this.

I added a tooltip to the endpoint url for yesterday's release as a stop gap, but your idea of putting a button next to it with help is probably a good idea.

Most of us are used to LiveWriter figuring out the actual end point on its own and I have a work item for that in place actually, But it'll be a little bit and I need to figure out the right UI to make this work.

The Weblog endpoint has to be the actual final API endpoint not just the root of the site. 

Thanks for opening this issue to track this.

**Comment by RickStrahl** [comment]
So RDS support is coming. I have the basic RDS parsing and discovery working, should get the UI hookup integrated hopefully tonight.

**Comment by RickStrahl** [comment]
Ok, so I've implemented and hooked up RSD Endpoint discovery. You can now put in your Blog's home page click on the discover button and MM goes out to discover the actual Endpoint URL and Blog ID. This works as long as the blog engine supports RSD (Real Simple Discovery).

Here's what this looks like now:

**Comment by awright18** [comment]
That sounds awesome! I can't wait to try it out.

**Comment by RickStrahl** [comment]
It's out in 1.1.14...

**Comment by awright18** [comment]
This looks, and works great for me. Thank you so much. I'm closing this issue now.  Also, I think the help button and the updated documentation will also be a big help for others.

**Comment by RickStrahl** [comment]
I think this was an important thing to add and should have been done a while ago :-)

Thanks for pushing this out front and center so I wouldn't put it off any longer :-)
