### ISSUE TITLE
Unable to paste image from clipboard

### ISSUE THREAD

**Issue by zhouxinghong** [RickStrahl/MarkdownMonster#1130]
Unable to paste image from clipboard
`https://c0.jdbstatic.com/samples/y3/y3Vvv_l_9.jpg`

The files are large, so I had to zip them up.
[Video_20240823_164928.zip](https://github.com/user-attachments/files/16726368/Video_20240823_164928.zip)
Windows 10 19044
MM 3.4.0

**Comment by RickStrahl** [comment]
If that doesn't work the image link or format is bad.

**Comment by zhouxinghong** [comment]
https://github.com/user-attachments/assets/5e185b5a-0ddb-4e69-9c9b-5425c81e11c8

**Comment by zhouxinghong** [comment]
![image](https://github.com/user-attachments/assets/49a10579-a0be-42a8-8461-e08cf7621d0e)

**Comment by RickStrahl** [comment]
Well, no wonder:

![image](https://github.com/user-attachments/assets/11b45178-fad9-4688-9eea-2e31951e695d)

**Comment by zhouxinghong** [comment]
This problem is caused by Markdown Monster's incorrect handling of the upper and lower case of the image path string.
