### ISSUE TITLE
[Feature Request] Option to Hide Hidden Files and Folders in the Folder Browser Sidebar

### ISSUE THREAD

**Issue by pa-0** [RickStrahl/MarkdownMonster#1132]
If I'm not mistaken, MarkdownMonster shows all files and folders (including hidden System files/folders) by default. I think it would be useful to clear some of the clutter that appears in this browser, if we had the option to (much like the native File Explorer) hide those system files/folders and -- one step further -- also hide all files/folders that have the hidden attribute.

Alternatively, if just mirroring file explorer's configuration (Show hidden files/folders and show hidden system files/folders only if the user has set the same in Windows File Explorer) would also work just fine.

**Comment by RickStrahl** [comment]
Yup it shows, but you can set filters on what types of files and folders to filter out:

![image](https://github.com/user-attachments/assets/997dbb2b-d4d8-4a38-bdd8-28d291831d85)

The filter applies automatically unless you click the 'Show All Files' button in the browser toolbar or the checkbox in Settings.

I don't see the need to filter beyond this, as it's pretty unlikely you're going to show folders that have hidden files or system files. I mean you're not likely to browse for markdown files in the Windows system folder? :smile: The 99% use case is you're going to have certain document folders that contain only your own files that relate to documentation, notes, text etc.

**Comment by RickStrahl** [comment]
Maybe one thing I would consider is hiding Hidden files/folders in the default filtered mode. Show all files would then show everything.

But no extra options for that.

**Comment by pabbasi** [comment]
> The 99% use case is you're going to have certain document folders that contain only your own files that relate to documentation, notes, text etc

Good point!  No real value in hiding some of these files/folders users rarely - if ever - will be setting their working directory to C:\Users and the like.  Filtering things out in the sections you highlighted should suffice. Thanks.

**Comment by pa-0** [comment]
>The 99% use case is you're going to have certain document folders that contain only your own files that relate to documentation, notes, text etc

Good point! No real value in hiding some of these files/folders. Users rarely - if ever - will be setting their working directory to C:\Users and the like. Filtering things out in the sections you highlighted should suffice. Thanks.

**Comment by RickStrahl** [comment]
I did add hidden files to be ignored in the default filtered view as that was an easy fix and it doesn't require any additional UI. They are visible when Show All File is enabled. 

It'll be in the next update.

**Comment by pa-0** [comment]
Awesome. Thank you!
