### ISSUE TITLE
Feature Request: Option to vertically split the Sidebar into multiple panels

### ISSUE THREAD

**Issue by nonplayer** [RickStrahl/MarkdownMonster#1134]
It would be a neat feature to be able to split the sidebar into multiple panels. For example, I'd like to be able to have both the favorites list, folder browser, _and_ document outline open on the left side, with the Favorites on top, the folder browser beneath that, and the document outline below. Being able to drag and resize them would be cool too.

For an example of this in action, the QOwnNotes app allows repositioning of panels all over the place, and by default has them all open on the left. While I don't expect _that_ level of repositioning here, it'd still be super cool to have is just in the sidebar.

Thanks for consideration!

**Comment by RickStrahl** [comment]
That's a good idea, but not an easy one to get in mainly as it pertains to the UI. Getting a split panel and hosting say the bookmarks on the bottom would be easy enough, but if it's all configurable or memorized through sessions it becomes a lot more complicated to manage the window. And how do you know where what goes etc.

I have to give this some thought, but I like the idea and it would be certainly useful to me as well.

**Comment by RJS32** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Siphompeks** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by RickStrahl** [comment]
Taking a first swipe at this:

![image](https://github.com/user-attachments/assets/2d69aa47-8ddc-4db0-8e44-b95291ad35a3)

For now it's just the Document outline that can be placed here, but it's a start. 

I have a way to generically load panels, and move them around, but haven't figure out yet how to store the configuration. for now the Document outline is hardcoded explictly.

**Comment by nonplayer** [comment]
This looks fantastic!

**Comment by RickStrahl** [comment]
Some more updates on this: The left sidebar is now configurable with the ability to re-position all three of the stock panels. Here's what this now looks like:

![image](https://github.com/user-attachments/assets/2c5a1584-635e-4487-9404-9b839d196cd3)

There's no UI for this at this point - it has to be configured via the config file and then while MM is not running. 

First UI step should probably be a context menu that lets you set:

* Position of the current tab (top and bottom)
* Option on whether the panels are splittable

For this first update probably just stick with the non-UI interface. 

The default interface will be what we see now.

Current version is in the Preview release (v3.5.0.16+)

**Comment by RickStrahl** [comment]
More progress here and getting close to done. There's now a context menu that lets you move tabs and set the split mode.

![SplitPanelNavigation](https://github.com/user-attachments/assets/33e9bc76-bc93-443f-a33a-1f361b19be94)

**Comment by RickStrahl** [comment]
Done as of v3.5

**Comment by nonplayer** [comment]
This is FANTASTIC. Thank you!
