### ISSUE TITLE
Request: Add "post as page" as an option to weblog post tool

### ISSUE THREAD

**Issue by nonplayer** [RickStrahl/MarkdownMonster#1139]
(Apologies for the flood of posts today, I'm trying to overhaul my personal writing flow and Markdown Monster is positioning to be a central component.)

When posting to a Wordpress weblog, I'd love to be able to set it to upload as a Page instead of a Post. For one of my design projects I use Wordpress solely as a collection of pages, with posts hidden on the site. I have a handy plugin that can convert content to different types, but it'd be nice to remove that from the flow and just upload directly as a new Page.

Thanks!

**Comment by RickStrahl** [comment]
That's not supported and I'm not bound to add this. We're basically providing a convenience feature that maps to other Weblog engines and that one doesn't work with the old Metaweblog API that is used to publish to Wordpress. May look at this again in the future but this is such an underused feature as it is, that I'm not keen to spend the time to rebuild the Wordpress support for the new APIs (especially given the latest Wordpress drama).

**Comment by nonplayer** [comment]
Ah, that's totally fair. Thanks for the information!
