### ISSUE TITLE
Save as keyboard shortcut not working

### ISSUE THREAD

**Issue by alexwiese** [RickStrahl/MarkdownMonster#114]
The Save As command shows the key binding as "Ctrl+Shift+S" but it isn't implemented.

![image](https://cloud.githubusercontent.com/assets/2103355/21827276/e338b1c4-d7da-11e6-9f54-184b005e16bd.png)

**Comment by RickStrahl** [comment]
Actually that may not be necessary. Not all hotkeys need to be forwarded from the editor to WPF. A WPF keybinding is probably all that is needed. Checking.

**Comment by RickStrahl** [comment]
Looks like WPF command binding does not work in this case so your code is the right way to go.

**Comment by alexwiese** [comment]
Yes I noticed that doing the key bindings this way doesn't allow you to save when the preview window, or other control, has the focus (eg. click on the HTML preview then Ctrl-S and it doesn't save). Using the `PreviewKeyUp` event on the `Window` would probably work, not sure if there is a nicer way to bind that to a command though. Might be worth opening another issue for that limitation.

**Comment by RickStrahl** [comment]
Fixed with 3548c57a1fa3a4cb3f9e62523f2c6cf68f3739bc.
