### ISSUE TITLE
Spellchecking Bug

### ISSUE THREAD

**Issue by pa-0** [RickStrahl/MarkdownMonster#1143]
### Spellchecking does not work as expected.

When spellchecking is disabled, spelling errors are highlighted when a file is opened:
![image](https://github.com/user-attachments/assets/2d459b40-35e4-4674-a479-a8213f5fc781)

If window focus is lost, spellchecking errors are no longer identified, but then when actually enabling spellchecking, it does not appear to work correctly, still:

![image](https://github.com/user-attachments/assets/6c085882-1d30-4494-802c-36a745a64811)

**Comment by RickStrahl** [comment]
Hmmm... yeah this is a bug but an odd one. There should be no spell checking in JSON files and it looks like spell checking only is applied on initial load and then goes away when the editor loses and then regains focus.

Looks like somewhere the spell checking is applied incorrectly (like reversed) for non-Markdown files. Same thing happens for any other non markdown or plain text file.

**Comment by RickStrahl** [comment]
Fixed: Turns out that the initialization code for non-Markdown files was setting the flag incorrectly. As suspected occurs during initialization only but then on reactivation of the editor it's set properly and the spell checking goes away for non-markdown files.

Fixed.
