### ISSUE TITLE
[FEAT} Option to use ssh for cloning

### ISSUE THREAD

**Issue by pa-0** [RickStrahl/MarkdownMonster#1144]
Please consider offering the option to use SSH authentication to clone remote repositories.

### Some (possibly unneccessary) context:

With `git`/`ssh`, multiple accounts can be managed easily either by 'telling' `git` to choose which account with which to authenticate based on directory patterns, e.g., `[INCLUDEIF gitdir:]` in `.gitconfig`.   Alternatively, in the `ssh` config file, host aliases can be set, so to clone from account A (or account B).  Both of these workflows are pretty commonly used to juggle authentication for multiple users/remote hosts. With the latter, I can do the following:

#### account A:

```bash
git clone ssh:alpha OWNER/REPO 
```

#### account B:

```shell
git clone ssh:bravo OWNER/REPO
```

### In Markdown Monster

Attempting to clone a private repository from account B returns:
![image](https://github.com/user-attachments/assets/908dd850-7505-4429-b557-8dfee7a65e36)

This wouldn't be the case if we were able to use SSH, or alternatively, even being able to send custom git commands to clone.

**Comment by RickStrahl** [comment]
Can't you externally clone, and then once connected shouldn't all other commands work?

You can shell to terminal or use the Open in External Git Client from most context menus, clone and once connected you should just be able to use other commands?

**Comment by RickStrahl** [comment]
Off the top of my head I'm not sure if SSH wouldn't just work, since this particular command is piped through the Command line. But you need to give it an SSH address not hte HTTPS address.

I don't use SSH  so not familar with it to be honest but should you be using something like:

```
git@host:username/repository.git
```

for the 'url'.

**Comment by pa-0** [comment]
Oh ok! Will give it a try. Thanks.

**Comment by pa-0** [comment]
So using the built in tool to clone a remote repo via ssh did not workf or me BUT on your other suggestion, I tried cloning the remote locally first via terminal and then committing using the in-app git tool and that works without a hitch, so I am closing this. 

On another note, in case anyone else looking for help/ideas finds this issue, the developers of GitJournal (another notes app I believe) released this nifty Go tool called [git-auto-sync](https://github.com/GitJournal/git-auto-sync) which complements MarkdownMonster (or any note-taking tool) very well for anyone who wants to keep their notes synced with git automatically.  It's a small (~7MB), portable, single-file executable with a pretty simple setup.
