### ISSUE TITLE
.markdownlint.json

### ISSUE THREAD

**Issue by monkey-knuckles** [RickStrahl/MarkdownMonster#1145]
Are there any plans to allow Markdown Monster to take a '.markdownlint.json' file? This would be awesome!

**Comment by RickStrahl** [comment]
I looked into this before but wasn't quite sure what to do about the UI for this.

It would be an addin most likely rather than a core feature.

But how would you expect this to work given the current editor setup.

**Comment by monkey-knuckles** [comment]
You would probably run the config alongside something like markdownlint and pull the results from that rather than redesign the wheel.

**Comment by RickStrahl** [comment]
Not going to implement this. Too many issues with having to install markdownlint and not sure about the UI etc.

But it's something that can be created as an Addin if someone is interested in that functionality.
