### ISSUE TITLE
Default Keybinding for `Paste HTML as Markdown` not working

### ISSUE THREAD

**Issue by pa-0** [RickStrahl/MarkdownMonster#1147]
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>V</kbd> is not working to paste HTML as Markdown.  Selecting the entry from the <kbd>Edit</kbd> works exactly as expected.  It is just the keyboard shortcut that returns nothing.

**Comment by pa-0** [comment]
Windows 11 Enterprise 64-bit, OS Build: 22631.4317

Keybinding.json unmodified, keyboard combination at issue not mapped as custom hotkey anywhere else.  Tested with all third-party apps closed.

**Comment by pa-0** [comment]
So just following up.  After restarting the app, it began to work once more. However, after some time, it once again ceased to function.  Seems the workaround is restarting app.

**Comment by RickStrahl** [comment]
You may have a double mapping or the mapping is no longer valid? Perhaps Vim mode?

Ctrl-Shift-V works for me.

**Comment by pa-0** [comment]
You are correct.  I realized today this was occurring not because of the keybinding, but because I was copying only portions of webpages (resulting in malformed in HTML).  If I <kbd>CTRL</kbd>+<kbd>A</kbd> and copy the entire page, it works as expected.  The inconsistent behavior was a result of my selections changing in between pastes before.  Closing this.
