### ISSUE TITLE
Cursor appears in wrong position when text in the editor is italicized. 

### ISSUE THREAD

**Issue by pa-0** [RickStrahl/MarkdownMonster#1149]
### Picture > 1000 words:
![image](https://github.com/user-attachments/assets/d4f47f6f-e0b5-49b1-a652-79f43c8096f6)

Notice the discrepancy between where highlighting begins between the matched selections and original selection. Also note that this effect spans beyond just highlighting.  When typing, the cursor appears in one place (misleadingly) whereas typed text appears 2 spaces before the cursor. For the first few seconds of typing, I made a mess of the page before I realized what was going on 😆

**Comment by pa-0** [comment]
Closing this.  I misadvertently chose Nerd Font of type "Proportional" instead of "Mono" so this was my fault.  Apologies!

**Comment by pa-0** [comment]
On a separate note, and I will create a separate issue for this if you like, but as a feature request, it would be nice if HTML meant to be parsed in Preview mode (rather than displayed as raw HTML) were excluded from the Markdown WSIWYG styling.

**Comment by pa-0** [comment]
I spoke too soon on this.  Even with a true mono font set for the Editor, the moment something is formatted as italic, i.e., `The title of the book is *Moby Dick*`, the caret and selection highlighting in the editor becomes off by 1 or 2 characters.

**Comment by RickStrahl** [comment]
I don't know that looks alright be me.

![image](https://github.com/user-attachments/assets/c6f1afd9-014b-4180-95ed-a842eb5d05d3)

Is it possible you have some oddball hidden control characters in your text? 

Try something simple and see if you get the same behavior with the same font configuration.

**Comment by pa-0** [comment]
Honestly not sure.  I was able to duplicate this with a monospaced font, but now I can't remember which font.  At any rate, I've since been using Reddit Mono patched with ligatures and nerd fonts and have not had any issues at all.  I guess, I'll close this for now, and just keep an eye open for any reproducible instances.  Thanks for taking the time to check it out though.
