### ISSUE TITLE
Tofu Bug

### ISSUE THREAD

**Issue by monkey-knuckles** [RickStrahl/MarkdownMonster#1150]
I am getting tofu output with some ASCII characters.

[DEVELOPER.pdf](https://github.com/user-attachments/files/17716520/DEVELOPER.pdf)

**Comment by RickStrahl** [comment]
I'm not sure what I'm looking at here...

**Comment by monkey-knuckles** [comment]
I apologise. Page 5.  MD026 It's not displaying the characters correctly. I believe this to be a bug with the PDF rendering. I'm happy to be corrected.

**Comment by RickStrahl** [comment]
That would be missing font information. whatever characters those are they are not finding matching font characters.

What PDF print theme  are you using for the print output? And what version of MM are you running? 

Does it work in the preview? Can you try using the same theme you're using in the previewer?

What are those characters? Special? Font Specific?

**Comment by monkey-knuckles** [comment]
Changing the theme to GitHub solved the problem. Thanks.

**Comment by RickStrahl** [comment]
Great. With the new PDF engine we should probably change to the same fonts that the GitHub theme uses for the PDF Output print theme. With wkHtmltoPdf previously we had to rely on base system fonts, but the new engine embeds font information from linked fonts so it's more flexible.

Thanks for the feedback.
