### ISSUE TITLE
Link-check from within the editor

### ISSUE THREAD

**Issue by warbe-maker** [RickStrahl/MarkdownMonster#1153]
Is there any way to perform a Link-Check from within the editor? I was looking for a menu-item but couldn't find one. I would be happy if there's any other means available to do this within the editor but I couldn't find anything in the help documentation.Sorry in case I've just overlooked something.

**Comment by RickStrahl** [comment]
I've been thinking about this a bit and played around with finding links. 

Haven't quite figured out how to display those links.

What I would like to see is:

* List of all links grouped by success and failure links
* Links should navigate to the location they're referenced
* Links should also have an option to navigate:
    * navigate to Web links 
    * images should  preview for local links

**Comment by warbe-maker** [comment]
This sounds pretty promising. The lust of links with a passed or failed state is probably the best one can get 

Kind regardsW. Rauschenberger
***@***.***



10. Dez. 2024, 01:25 von ***@***.***:

**Comment by RickStrahl** [comment]
So I have an implementation of this working. Still a bit rough but the core functionality is there.

![CheckDocumentLinks](https://github.com/user-attachments/assets/dd29af58-d088-4285-8733-256a62ad6948)

Some features:

* Keeps in sync with document while active
* Tracks changes as you type
* Reloads when switching documents
* Explicit refresh button to force full reload
* Checks Web Http, Local file and document links
* Click to navigate to link reference in document  
  (from there you can control click to navigate link)
* On Tools -> Check Document Links
* Command Palette: Check Document Links

There are still some UI oddities and the refresh is in need of some optimizations to avoid checking links that have not changed.

**Comment by warbe-maker** [comment]
This looks definitely even more promising than expected. A great job done already. I'm looking forward to an update which includes this feature. Thank you so much.
