### ISSUE TITLE
pdf not works in latest version 

### ISSUE THREAD

**Issue by johnfelipe** [RickStrahl/MarkdownMonster#1156]
![SNAG-0170](https://github.com/user-attachments/assets/f3c6114a-7091-4bfb-95de-aab8dfd5d4dc)

https://gist.github.com/johnfelipe/039ab259d9f28f4df291826454dbd0e9

how can solve this?

**Comment by RickStrahl** [comment]
Took a quick look and saw this was still not fixed in the current release. It is fixed in 3.5.6 which is live on the download site now and should be updated on Chocolatey and WinGet later today or tomorrow.
