### ISSUE TITLE
Admonition Extension

### ISSUE THREAD

**Issue by Benko111** [RickStrahl/MarkdownMonster#1159]
Just trying out the Monster and it's been great so far, if it wasn't for one dealbreaker. I'm working on a large project making extensive use of Admonition Extension which isn't rendered in MarkdownMonster. Any chance to get that to work? Thanks.

**Comment by RickStrahl** [comment]
This is something that is best left for an addin if somebody wants to implement it. Could be accomplished with a [RenderExtension](https://markdownmonster.west-wind.com/docs/_5i30sba89.htm)  most likely.

This is not something that needs to be in the core rendering engine.
