### ISSUE TITLE
Feature: User-definable key shortcuts for inserting & changing markdown headers

### ISSUE THREAD

**Issue by nonplayer** [RickStrahl/MarkdownMonster#1164]
As I'm adapting to using MM almost completely for my Markdown writing, one thing I find that I am missing from a few other apps is the ability to quickly insert a Header from the keyboard. It would be nice to have some options for defining these in the keybinds json, even if they're left disabled by default.

Two suggestions on this from other tools I've used. One is probably the most straightforward, using a command to set a number of hash marks followed by a space at the beginning of a given line. The other (which VSCode uses) is to use a different shortcut to increase or decrease the header size by similarly modifying the amount of hashes by plus or minus one (in VSCode's example, it's CTRL+SHIFT plus left or right bracket to decrease or increase, respectively).

Use Case: I'd like to do as much editing and note-taking as possible without removing my fingers from my keyboard. Being able to insert, remove, and adjust header hashes direct from the keyboard would be a great benefit to that process.

Thanks again for an awesome tool!

**Comment by RickStrahl** [comment]
After taking a look in the keybindings and noticing that the Ctrl-1 - n shortcuts are not working (meant for the sidebars but that hasn't worked for some time) I've reassigned those keys for H1-H5 assignments. 

These keys work like the toolbar does, ie. they add the ## combo to the beginning of the line or replace an existing set with a new one.

Update is in 3.5.10+
