### ISSUE TITLE
I submitted an issue that appears to be removed   Please, refund my money.

### ISSUE THREAD

**Issue by DrBobbyW** [RickStrahl/MarkdownMonster#1165]
I purchased this application on the 24th.   I continue to get two error messages as follows:  
![image](https://github.com/user-attachments/assets/271751f7-1167-4c55-8cd2-112957f8c4c9)  and the other will not allow me to log into a different computer.   The issue associated with the error message shown, pops up even when the systems first start up or when I try to save as a pdf for after copying the markup to Markdown Monster and awaiting the rendering process.  Then, you have to restart the application.   As previously stated, this was submitted a few days ago when I purchased the application.  In brevity, it does not perform as expected and I have spent a large amount of time trying to resolve this issue on multiple machines with the same results.

Please, refund my money.

Thank you.
you

**Comment by RickStrahl** [comment]
Uhm, you closed the issue you submitted?

![image](https://github.com/user-attachments/assets/d58248b2-3b7f-46f5-9939-7797db01c9a4)

**Comment by RickStrahl** [comment]
If you want to persue this reopen the issue and provide more info on what version you're using (About -> click on the info icon to copy all version info to clipboard if you can get there).

**Comment by DrBobbyW** [comment]
I didn't close it, I added an additional issue.    The issues are there.   If you can resolve them, please do so without delay.   Sent from Samsung Galaxy smartphone.Get Outlook for AndroidFrom: Rick Strahl ***@***.***>Sent: Thursday, December 26, 2024 12:29:34 PMTo: RickStrahl/MarkdownMonster ***@***.***>Cc: DrBobbyW ***@***.***>; Author ***@***.***>Subject: Re: [RickStrahl/MarkdownMonster] I submitted an issue that appears to be removed Please, refund my money. (Issue #1165)
If you want to persue this reopen the issue and provide more info on what version you're using (About -> click on the info icon to copy all version info to clipboard if you can get there).

**Comment by DrBobbyW** [comment]
Hello Rick,

 

I hope this message finds you well.

 

To clarify, my primary requirement for this application is to enable me to copy my history from CoPilot in the same format as the responses were rendered. I purchased the application based on the information provided, which indicated that saving to a .pdf file necessitates a purchase. Unfortunately, this functionality is not working as expected. I have already shared the error messages with you.

 

As someone who writes a significant amount of code, it is crucial for me to have accurate and formatted responses from CoPilot. If you can resolve this issue, I kindly request that you do so promptly. Otherwise, I will need to seek an alternative solution due to the urgency of this matter.  I’ve attached a screenshot of application version information.

 

Should you be unable to resolve this issue, please process a refund without delay.

 

Thank you for your attention to this matter

.

Best regards,



Bobby

**Comment by RickStrahl** [comment]
???

You know what I'm going to refund your money. I don't think this is going to work out for either of us...
