### ISSUE TITLE
MM Stopped Updating Itself at ver 1.1.8

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#118]
I just realized, MM has stopped updating itself at ver. 1.1.8
I could see 1.1.15 went out and installed it.
Just letting you know.

**Comment by RickStrahl** [comment]
Update checks are once a week by default so you perhaps shouldn't have seen it yet. You can change the update frequency in the configuration using the `ApplicationUpdates.UpdateFrequency` key.
