### ISSUE TITLE
Save document dialog does not remember last folder

### ISSUE THREAD

**Issue by HeyJoel** [RickStrahl/MarkdownMonster#120]
I'm writing a lot of markdown documentation for a github wiki and whenever I create a new document the save dialog always reverts to the windows libraries folder rather than remembering the directory I last had opened. 

The open file dialog seems to remember my working folder so it would be handy if the save dialog did too.

**Comment by RickStrahl** [comment]
Yes that would be a bug. Supposed to remember last used folder or if there is none or it no longer exists then the windows libraries folder.

**Comment by RickStrahl** [comment]
Fixed. 72af0814aaa35d8b7af255451beff89fce6c12d0
