### ISSUE TITLE
Integrated file/solution explorer panel

### ISSUE THREAD

**Issue by HeyJoel** [RickStrahl/MarkdownMonster#121]
I'm writing a lot of markdown documentation for a github wiki and tend to move between files quite regularly. Have you considered having a file explorer panel? It would work a bit like the solution explorer in visual studio, but would simply allow navigating between documents in a working folder.

I'm not sure how common this use case it but since I spend most of my day in visual studio it was a feature I went looking for.

**Comment by RickStrahl** [comment]
Yeah it's a common use case, but I'm wary to add too much functionality into the core editor that ends up cluttering up the UI even if optional.

 I think it's a good suggestion but it's not high priority at the moment. I think we have a previous request for this as well.

**Comment by RickStrahl** [comment]
I've finally had some time to add a base implementation of a new file browser - experimental for now.

![image](https://cloud.githubusercontent.com/assets/1374013/25785450/73041036-3335-11e7-973a-4bd1ed89fffd.png)

Features:

* Collapsible panel (not visible by default)
* Open a folder by typing in or picking with Folder Picker
* Double click or Enter to open in editor for known document types
* Images opened in configured Image Editor
* All others opened with Shell
* Basic File management - Add, Rename, Delete
* Open Explorer, Terminal or File In Shell

**Comment by HeyJoel** [comment]
This is really cool! It seems to do everything I need plus some extra things I hadn't though of - I like that you can right-click and open the folder in explorer. One extra feature I could see as possibly being useful is being able to drag an image into a markdown file to get a reference but it's not something I would do very often and you can already do it from the explorer window so it's not that bigger deal.

I've finished my major documentation work for the time being but I'll be working with it again in the not too distant future so I'll give it a more thorough run through then.

I did get an exception with opening images from the folder browser, do you want the details here or as a separate issue?

**Comment by RickStrahl** [comment]
> One extra feature I could see as possibly being useful is being able to drag an image into a markdown file to get a reference 

You can do that now.  Take a look at:

* [Embedding Images](https://markdownmonster.west-wind.com/docs/_4s01ezteq.htm)

for all the different ways you can get images into Markdown Monster.

> I did get an exception with opening images from the folder browser, do you want the details here or as a separate issue?

Yes please open new issues for each item - this makes it easier to track things.

I think this is caused by the image editor not being available - you can go into **Tools -> Settings** and then change the **ImageEditor** key to a path a valid Image Editor path (or Paint.exe if you don't have one installed). Make sure paths are properly escaped with double slashes.

**Comment by HeyJoel** [comment]
Ok that's in issue #189.

In terms of the image reference drag and drop, I meant dragging from the Folder Browser sidebar to the markdown editor window, that feature doesn't seem to be supported.

**Comment by RickStrahl** [comment]
Can you open a new issue for this enhancement for that please. 

Great use case I didn't even think about.
