### ISSUE TITLE
Crashing with Protected Memory Error

### ISSUE THREAD

**Issue by pkellner** [RickStrahl/MarkdownMonster#122]
I tried to File/Open a new file.  The file was in my file system but the file came up as if it were empty (with no error).  tried to open it again and I got the "Yikes" pictured below.  I'm also including the error log below.  

In addition, I've had 3 or 4 crashes in the last day or so (I just started working on some mark up. I've not been doing any markup for weeks so have not used MarkdownMonster for a while.

![error](https://dl.dropbox.com/s/hwpx10mr7loztuj/mmfail1.png?dl=0 "error")

1/24/2017 10:27:38 AM - Last Resort Handler
Markdown Monster v1.1.19
10.0.10586.672.amd64fre.th2_release_sec.161024-1825 - en-US - .NET 4.6.1 - 32 bit
---
PresentationFramework
   at MS.Internal.AppModel.IFileDialog.Show(IntPtr parent)
   at Microsoft.Win32.FileDialog.RunVistaDialog(IntPtr hwndOwner)
   at Microsoft.Win32.FileDialog.RunDialog(IntPtr hwndOwner)
   at Microsoft.Win32.CommonDialog.ShowDialog()
   at MarkdownMonster.AppModel.<CreateCommands>b__97_7(Object s, ICommand e)
   at MarkdownMonster.CommandBase.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------

**Comment by RickStrahl** [comment]
Ugh - that looks like system exception from the open file dialog in Windows - ie. it's bonking in the innards of Windows.

Where was this file being loaded from? Permissions could be an issue although you should get a different error from that.

**Comment by pkellner** [comment]
Local file system

**Comment by RickStrahl** [comment]
Special location? Could permissions be a problem? File open elsewhere and locked?

I'm going to slap an exception handler around this just in case it happens again - that way more info can be available in the future.

I just tried to open some files in protected folders or folder that I don't have access to but the file picker won't even let me go there or won't show me the files (like applicationhost.config which must be edited by a 64 bit editor).

**Comment by RickStrahl** [comment]
Added handlers to log for these cases:

81d95db48284c0ba37b29b3ae486711283b9ff5f  and b8e444bb5f95b2124271f40e00102c6fa66b1c7c

If it happens again you should get an error message.

Updated to 1.1.20.1 which is live on the Web site.

**Comment by pkellner** [comment]
No errors today. One odd thing was I installed MM on a new computer from the web and first time I ran it, it told me there was a new version on the web.  could have been my error somehow.

**Comment by RickStrahl** [comment]
Can happen if you install from Chocolatey and I have a newer version out. Version checks should only happen after a while, unless you had it previously installed - the config with those settings isn't removed so if you reinstall the old settings may still be there.

**Comment by RickStrahl** [comment]
Going to close this since this seems to be a one off crash. If you run into another crash like this and there's more info feel free to re-open this issue.
