### ISSUE TITLE
Flatten Menu Items

### ISSUE THREAD

**Issue by JonDouglas** [RickStrahl/MarkdownMonster#126]
Today is my first day exploring Markdown Monster. I've been a very avid VS Code/Markdown Pad2 user in the past. One thing I've noticed is that the menus are very "noisy".

For example the "Help" section includes lots of things that are helpful, but might be better suited for a nested menu.

One major change that seems reasonable is to put all the "Documentation" items in it's own nested menu called "Documentation". 

**Note:** Please feel free to reject this issue. It's just a minor thing I've noticed compared to other editors.

**Comment by RickStrahl** [comment]
Usually I would agree with keeping menus clean, but for the Help Menu I think it's somewhat important for things to be visible front and center - especially the documentation links. Putting in a submenu is easy enough but I think it's actually going to keep people from going there who looks at documentation after all :-)  But Help is often used to check for new versions and about so the help links pop up.

If we end up putting more stuff on the menu then yeah it's time to trim, but for now I think it's not too noisy.
