### ISSUE TITLE
Be nice to have the release date of the version in help/about

### ISSUE THREAD

**Issue by pkellner** [RickStrahl/MarkdownMonster#129]

**Comment by RickStrahl** [comment]
I'd rather not do that for a) clutter in the about dialog and b) for making it obvious when things stabalize and get more 'stable' later in the product cycle :-) Yeah you know when the app is 'done' and only needs to get updated occasionally for bug fixes.

You can always check the file date to find out the actual time the build was created.

**Comment by RickStrahl** [comment]
I've added this now:

![image](https://cloud.githubusercontent.com/assets/1374013/22880890/06c11ca0-f188-11e6-89c6-2b53a2211a18.png)

in the process of rearranging the About screen.

**Comment by pkellner** [comment]
Thanks.  I'd be happy with a conditional that said something like "hide date if more than 60 days ago".  

Thanks for adding it.
