### ISSUE TITLE
Command line addin

### ISSUE THREAD

**Issue by M-Zuber** [RickStrahl/MarkdownMonster#131]
As a spin off from #119, an addin that allows running a generic command line exe with specified params

Configuration:
- Path to exe (or name if it is already on the users PATH)
- command line arguments
  - key value boxes or just one big text box?
  - do we handle escaping or leave that to the user

For future work - it would be nice to have a in-app display of the (copy-able) output

**Comment by RickStrahl** [comment]
Yup good idea. 

However, I'm going to hold off for a little bit on this one until I get all the issues ironed out on the Snippets addin. There are a few more features that would be nice like being able to assign hot keys combinations to snippets/execution sets. 

I think most of the UI pieces for this can be taken directly from the [Snippets addin](https://github.com/RickStrahl/Snippets-MarkdownMonster-Addin).

**Comment by RickStrahl** [comment]
Ok so I have all the pieces I want from the snippets addin in place. Probably start on this next week.

**Comment by RickStrahl** [comment]
I've created a new repository for the Commander Addin, which really is turning more into a scripting adding.

The repo is here:
https://github.com/RickStrahl/Commander-MarkdownMonster-Addin

The lets you create small scripts that behave like addins.

You can basically run any C# code as script:

![image](https://cloud.githubusercontent.com/assets/1374013/22998550/6189dd44-f37b-11e6-8587-8f54cd968d8f.png)

And you can of course start new processes or batch files using the Process API:

![image](https://cloud.githubusercontent.com/assets/1374013/22998596/875bfd40-f37b-11e6-8c2a-5856a492bfa4.png)

Code can obviously be more complex, but for more complex code debugging becomes an issue.
