### ISSUE TITLE
Stylesheet Formatting for Print Output

### ISSUE THREAD

**Issue by RickStrahl** [RickStrahl/MarkdownMonster#132]
Moving discussion I've been having @mauricedb regarding print output from Markdown Monster. Posting here for open discussion on how we can integrate print styling better as there are quite a few issues to deal with:

* How to handle specifying whether Print styling should be applied (PDF vs. Print)
* Browser PDF Generation differences (IE **always** clears backgrounds regardless of styling)
* Managing styles

### Maurices approach
Maurice mentioned that he wanted to customize the print output so he can produce a PDF file that uses the full HTML output, without the special Print formatting that the default Bootstrap styles impose.  The main concern here was Code Styling when using a codestyle that has a dark background (like Dharkhan and Hipster themes for example).  Bootstrap kills background colors and changes foreground colors to black which is Ok for print, but for PDF output you want those colors intact.

Markdown Monster actually supports custom preview themes and so he created a customized Bootstrap build and created a custom theme. To do this he did:

* Copy an existing theme into a new folder below `PreviewThemes`
* Customize Theme.css, Theme.html or add custom styles
* Maurice added custom bootstrap.min.css
* Changed Theme.html to point at local bootstrap.min.css
* In Markdown Monster select new theme on bottom right dropdown

This totallly works, and is how MM was designed - you should be able to totally customize rendering and in Maurice's case he simply changed the style sheet.

It works but it's a shlog.

### Distilling down the changes
The actual style changes can be traced back to Bootstrap's @media print styling, specifically this `after:` block:

```css
@media print {
  *,
  *:before,

 *:after {
    color: #000 !important;
    text-shadow: none !important;
    x-background: transparent !important;
    -webkit-box-shadow: none !important;
            box-shadow: none !important;
  }
...
}
```
Commenting out the *:after block leaves the original background and colors in place. 

Unfortunately, because the setting is made with !important, and because those settings override `inherit` settings initially, there's no good way to override the above override. There's really no way that I know of to go back to `inherit` after the value is overridden in bootstrap.css. Which means the change has to be made in bootstrap.css. :-(

### Approaches
So there are a couple of approaches here.

1. **Leave the default behavior**   
Obviously that's the easiest path. The default behavior works for printing but for PDF output it wouldn't be so great. Overrides could be done by explicitly overriding as described above. We can perhaps ship the no print version of bootstrap so it's easy to just change the style sheet.

1. **Change bootstrap.css permanently**   
This is also pretty easy to do. We can just ship with a custom bootstrap,min.css and now output automatically would always be displaying original colors. This would work great for PDF printing, but obviously might be a drag when actually printing to paper.

1. **SomeSort of Switching Mechanisms**
Not quite sure what this would look like, but perhaps an option in configuration like `DontUsePrintStyles` or something along those lines. With this in place we ship both style sheets and dynamically switch between the two. This would require some work to get the style sheet passed into templates making it the template little more obscure to decipher as the html wouldn't point directly at the bootstrap css.

Personally I'm leaning towards #2. Physical printing is pretty rare, while PDF output generation on the other hand is probably pretty common. So I'd rather error on the side of what's more common.

### Other Issues

* **Microsoft Browsers never print backgrounds**
Chrome and Firefox do OK generating PDF documents with the original colors but Internet Explorer's print output or print to pdf output always ignores background colors.

* **Totally Dark Themes**
If you use themes like Blackout printing without a print style will get you into trouble as the whole page attempts to print in black. Eeeek.

Lots to think about here, please discuss.

**Comment by mauricedb** [comment]
I would also go for option 2 unless there is a lot of objection. So far there isn't.

I find I rarely print to paper these days. In almost every case I _print_ so I can get a read-only and cross-platform copy I can email. So I really just want a PDF. As most software doesn't have a **save as PDF** option there is almost always the option of printing and choosing a **Save as PDF** in the print dialog which is my default anyway.

If people really want to paper they still can even with option two. The only restriction is not choosing a dark template like Hipster. Select a light one like Github and printing to paper will be just fine although slightly different from the way it is currently printed.

**Comment by RickStrahl** [comment]
Yes so adjusted the themes selectively. Github, Dharkan and Hipster now print with the no-print version (ie. original code snippets) and with print theme for Blackout.

I have a feeling few people will print and as you point out using a lighter theme like Github will fix that. Maybe I should add another print friendly theme which could be be a slight variation of Dharkan but with Print styles intact.

**Comment by mauricedb** [comment]
No harm in adding another style and could helpful to some people.

**Comment by RickStrahl** [comment]
The updated styles are in 1.1.25 (but not a print friendly version).
