### ISSUE TITLE
Allow All Plugins Update At Once and no Restart

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#133]
Instead of being in a need to update each plug in and forced to restart MM it'd be nice to have them updated all at once without a restart.

**Comment by RickStrahl** [comment]
Not possible.  Addins load in process and once loaded cannot be unloaded without a restart. 

New addins now (1.1.23+) don't require a restart at all, but existing addins require a restart when updated. 

You don't have to restart when prompted if you know you're installing additional addins - just say No and add the next one. Then when done with all of them restart.
