### ISSUE TITLE
Publish buttons grayed out / disabled until restart

### ISSUE THREAD

**Issue by Mehul** [RickStrahl/MarkdownMonster#134]
![image](https://cloud.githubusercontent.com/assets/174004/22758546/f9c83948-ee03-11e6-8a9c-581acae38da4.png)

Sometimes, not always, when I start MdM, it displays the the publish buttons as disabled/grayed out until I restart. Not sure why. Any log I can provide that might help solve that?

**Comment by gep13** [comment]
I have noticed this happening as well.

**Comment by RickStrahl** [comment]
If no documents are open those buttons should be greyed out.

**Comment by Mehul** [comment]
Two documents were open. Previously saved/published documents if that helps. 

>>Blog publishing should always be available 
+1

**Comment by RickStrahl** [comment]
Are you on a recent version? There were updates that deal with the refreshing of addin `CanExecute()` logic. v1.1.24 should have this fixed and if not switching tabs should definitely refresh the execution status.

**Comment by Mehul** [comment]
Yes, 1.1.2.4 portable

**Comment by Mehul** [comment]
It's not a major issue as restarting tends to fix it. I'll keep an eye on when it happens again and I'll update this ticket.

**Comment by RickStrahl** [comment]
And addins are up to date as well?

Shouldn't be happening - I'm not seeing the behavior here. What happens when you:

* Close all Windows (should disable)
* Open a document (should enable)

You should see the status toggle.

**Comment by Mehul** [comment]
Ok, I think I figured out steps to reproduce.
1. close all documents, button is disabled.
2. close mdm
3. open mdm
4. open recent document
and publish button is still disabled. 

Do you see that as well?

**Comment by Mehul** [comment]
I don't have any addins installed

**Comment by Mehul** [comment]
1. Close all Windows (should disable)
2. Open a document (should enable)
This doesn't work for me either. Button is still disabled.

**Comment by RickStrahl** [comment]
Take another look at this with 1.1.25 when it is release (or you can download it now from the site).

**Comment by Mehul** [comment]
Tried v1.1.26 and the issue is still there.

**Comment by RickStrahl** [comment]
Ah ok - I guess I should have to follow your steps exactly :-)

Can you just verify for me though: If you're running MM and you close all documents it disables. Then when you re-open a window it re-enables - that's working for you? It only fails when starting up from scratch on startup with no windows open.

**Comment by Mehul** [comment]
>>Then when you re-open a window it re-enables - that's working for you? 

No, that is not working. I close all docs, close MM, reopen and button is disabled.

**Comment by RickStrahl** [comment]
That's not what I was asking :-) Don't close MM in between. 

IAC, this is fixed. Check with 1.1.27.

e707b7679f0b6bfcd42860ecac7e8c622687e3b8
0624521cec9d079011d9abbb7d9334d79acc0bb9
03a0aada16675ec83db5d5f6420936bc792c7cda

**Comment by Mehul** [comment]
In latest and previous it's fixed (after closing).

Tested it not closing MM in between and it worked fine. Thanks!
