### ISSUE TITLE
Save button greyed out

### ISSUE THREAD

**Issue by jantenhove** [RickStrahl/MarkdownMonster#135]
The save button is greyed out when something has changed (version 1.1.25). MDM detects the change (asterisk behind the document name), but the button stays disabled.
The menu item and Ctrl->S are working.

**Comment by RickStrahl** [comment]
Fixed. eb4e766257b3075e845bc5103b21ca2aed887a89

Will be in post 1.1.25 releases.

**Comment by RickStrahl** [comment]
1.1.25 is out so you can check it out.
