### ISSUE TITLE
Customize keyboard shortcuts

### ISSUE THREAD

**Issue by thomaslevesque** [RickStrahl/MarkdownMonster#139]
Is there a way to customize keyboard shortcuts? I use an AZERTY keyboard, and some of the default shortcuts are not usable (e.g. inline code).

I'm willing to implement it myself if it's not currently possible. It could be a new section in the settings file, something like this:

```json
"KeybordShortcuts": {
    "FormatBold": "Ctrl+B",
    "FormatInlineCode": "Ctrl+K",
    "Hyperlink": "Ctrl+L"
}
```
(commands not specified here would keep their default shortcut)

**Comment by RickStrahl** [comment]
Unfortunately it won't be that easy. There are a number of issues. First shortcuts are maintained both in the JS editor as well as in WPF. We try to use WPF shortcuts if possible to keep the editor as responsive as possible but some keys are more easily handled in the JS code. So there are mappings in both places. 

Operations aren't currently going through explicit command definitions which was probably a bit shortsighted, but right now there's nothing to map keys to - it's more or less hardcoded to those keys.

So, unless there are a lot more people requesting this I'm probably not going to tackle this at least not at this point. Maybe further down the line after other priorities have been taken care of.

**Comment by RickStrahl** [comment]
Since there hasn't been any more feedback I'm closing this issue for now.

**Comment by RickStrahl** [comment]
Re-opening as an enhancement request. Things have changed a bit since I last looked at this with most WPF operations now mapped to Commands which are relatively easy to map. Looking into a way to handle the JavaScript mappings in a separate way. 

Leaving open as a reminder and Todo item.

**Comment by RickStrahl** [comment]
So I've now added rudimentary support for keyboard mapping via a `MarkdownMonster-KeyBingings.json` file, which maps commands to keyboard shortcuts. This doesn't cover all keystrokes, but a fairly significant set of those commands that have shortcuts both in the main UI (ie. Document and Application level and in the editor).

```json
[
  {
    "Key": "alt+shift+return",
    "CommandName": "DistractionFreeMode",
    "HasJavaScriptHandler": false
  },
  {
    "Key": "f11",
    "CommandName": "PresentationMode",
    "HasJavaScriptHandler": false
  },
  {
    "Key": "ctrl-n",
    "CommandName": "NewDocument",
    "HasJavaScriptHandler": true
  },
  {
    "Key": "ctrl-o",
    "CommandName": "OpenDocument",
    "HasJavaScriptHandler": true
  },
  {
    "Key": "ctrl-s",
    "CommandName": "SaveDocument",
    "HasJavaScriptHandler": true
  },
  {
    "Key": "ctrl-shift-s",
    "CommandName": "SaveAs",
    "HasJavaScriptHandler": false
  },
  {
    "Key": "alt-shift-s",
    "CommandName": "SaveAll",
    "HasJavaScriptHandler": false
  },
  { ... }
]
```

**Comment by thomaslevesque** [comment]
Nice, thanks!

**Comment by RickStrahl** [comment]
Feature is live as of 1.12.10.
