### ISSUE TITLE
Downloading post from Codeplex

### ISSUE THREAD

**Issue by weggetor** [RickStrahl/MarkdownMonster#14]
Codeplex is also using  Metaweblog API to edit the project description. (See https://codeplex.codeplex.com/documentation?title=WindowsLiveWriter). But it does not work with Markdown Monster. I get the following error when trying to download posts from Codeplex:

> 07.07.2016 08:55:07 - Not Found
> ## Not Found
> 
> CookComputing.XmlRpcV2
>    bei CookComputing.XmlRpc.XmlRpcClientProtocol.ReadResponse(XmlRpcRequest req, WebResponse webResp, Stream respStm)
>    bei CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke(Object clientObj, MethodInfo mi, Object[] parameters)
>    bei XmlRpcProxy90dfa107-9835-4a86-9329-23d25236f610.GetRecentPosts(Object blogId, String username, String password, Int32 numberOfPosts)
>    bei WebLogAddin.MetaWebLogApi.MetaWeblogWrapper.<GetRecentPosts>d__8.MoveNext()
>    bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>    bei WeblogAddin.WebLogForm.<ButtonDownloadPosts_Click>d__19.MoveNext()
> --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
>    bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
>    bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

---

**Comment by RickStrahl** [comment]
Thanks for pointing this out. Will take a look. The download is pretty rough at the moment - it'll take a bit of reporting from various implementations to see what fails here.

Will take a look tonight. Thanks.

**Comment by RickStrahl** [comment]
Tosten can you check this one more time to see if if this works now? There have been a number of updates to the blog manager since we last talked about this issue. Before I take another look, please give this another try.

**Comment by weggetor** [comment]
Hi Rick. No does not work, sorry. You could check with url https://bbimagehandler.codeplex.com. Credentials sent with facebook chat

**Comment by RickStrahl** [comment]
Awesome. Thanks Torsten.

**Comment by RickStrahl** [comment]
So I was able to download a list of articles. Actually it only pulls in the home page, but that's a start :-)

ps
I hooked up LiveWriter to figure out the URL that needs to be accessed and it created a temporary post. I tried to look for it but I don't see it but pretty sure you need to get rid of it somehow. Not sure where in the admin interface that can be done.

ps ps
I suspect there are other issues there with posting. I'm going to set up a seperte site that I can hack on better here.

**Comment by RickStrahl** [comment]
On a side note it looks like Live Writer uses /rfd link to retrieve the API and Preview Urls. That's soomething that MM should do also but for now you have to plug in the hard metaweblog endpoint.

**Comment by RickStrahl** [comment]
Did you get a chance to check this out? Is it working for you now?

**Comment by weggetor** [comment]
Hi Rick, sorry for not answering. I only looked at the emails that are generated from github -and your explanations how to set up the metaweblog api for codeplex wasn't in there. So I tried with the old settings and it doesn't work.

But now I saw your detailed explanation and changed my settings according to your explanation and : IT'S WORKING! Nice work! Thank you !
