### ISSUE TITLE
F3 should find next occurrence of searched text

### ISSUE THREAD

**Issue by thomaslevesque** [RickStrahl/MarkdownMonster#140]
MarkdownMonster is missing a "find next" command. This is usually mapped to F3 in most editors.

**Comment by thomaslevesque** [comment]
Well, I thought it would be an easy one, but I'm stuck... can't figure out how to make ACE find the next occurrence. How did you even know to use `execcommand("find")`? The documentation doesn't seem very clear to me...

**Comment by RickStrahl** [comment]
Yeah the Ace Docs aren't the greatest. Usually find things like this by searching on SO, their GitHub issues and Google group. 

I have to take a look - this got implemented years ago for other stuff, so I don't recall offhand. Find and Replace commands are built-in - I don't think Find next will be a built in command.

**Comment by RickStrahl** [comment]
this works:

```javascript
"f3": function () { te.editor.execCommand("findnext") },
```

Added and fixed in 1.1.27.2 and later. 

798cc7bc53c63ea836b07f26a644b24461581454

**Comment by thomaslevesque** [comment]
awesome, thanks!

**Comment by thomaslevesque** [comment]
I made a PR for adding it to the Edit menu
