### ISSUE TITLE
MM being 1.1.27 keeps offering to upgrade to 1.1.27.2

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#143]
MM being 1.1.27 keeps offering to upgrade to 1.1.27.2 but the version about says 1.1.27
Upgrading it repeats the story

**Comment by RickStrahl** [comment]
Sigh - yeah. I forgot about this when updated the way the version number is displayed. 

This needs a proper fix I suppose with full version number comparisons and the display value getting special consideration (don't want to show .0 for the build numbers).

**Comment by RickStrahl** [comment]
For now this will clear up when 1.1.28 goes out probably tomorrow - and if you bump your version check frequency to a slightly higher value :-)

**Comment by ArthurZ** [comment]
Appreciate tackling it so quick Rick!

**Comment by RickStrahl** [comment]
Version numbers now work of the full version string and the full version string is also displayed in the UI:

![image](https://cloud.githubusercontent.com/assets/1374013/22880956/607c1c68-f188-11e6-82fd-41a4bf5ed58e.png)

This should work consistently now as the same version scheme is used in all places:

* About form
* Internal version number used for version check
* Version stored in online version download file
