### ISSUE TITLE
When Selecting Multiple Files on Open, Open them all

### ISSUE THREAD

**Issue by pkellner** [RickStrahl/MarkdownMonster#145]
I can't remember if I submitted this issue before but I don't see it on the open list. I thought that the open dialog can restrict to one file selection.  Maybe not.

If so, if I can only select one file while opening files, don't let me select multiple (or open all the ones I selected)

**Comment by RickStrahl** [comment]
Yeah that's a bug.  We should definitely be able to open multiple files at once.

**Comment by RickStrahl** [comment]
Fixed

963a6e0fcb4ccec8ae48d19b1fdf8cc2b39749e2
