### ISSUE TITLE
Superscript (^) and subscript (~) similar to Pandoc extension

### ISSUE THREAD

**Issue by schungx** [RickStrahl/MarkdownMonster#147]
I use `pandoc` to format most of my MarkDown documents, and I really miss the support for super/sub-scripts.  It is a pain if you need to sprinkle TM's and (R)'s in your document and not have them render correctly.

Perhaps an optional setting?

**Comment by RickStrahl** [comment]
That should work:

![image](https://cloud.githubusercontent.com/assets/1374013/23144995/739d9438-f76f-11e6-9513-7075eea7fc03.png)

Make sure you're using a recent version.

**Comment by schungx** [comment]
Oh.  I was using 1.1.30.0.  Downloaded from your website I think recently.  Now I see 1.2.0.0 is out.  I'll try it and report back!

**Comment by schungx** [comment]
Installed 1.2.0.0 and it doesn't work.  Now I know why.

`This is text ^super^ ~sub~` works fine.

`This is text MyBrand^&reg;^ and MyTrademark^&trade;^` doesn't work.

So it doesn't work on anything inside which is encoded.

Further:

`This is text: MyBrand^xyz&reg;^ works, but MyBrand^&reg;xyz^ still doesn't.

In other words, the combination of `^&` is causing the break.

**Comment by RickStrahl** [comment]
Forwarded over to the MarkDig parser:

https://github.com/lunet-io/markdig/issues/97

**Comment by ArthurZ** [comment]
I suggested Pandoc integration some time ago, would be a win for the MM community.

**Comment by RickStrahl** [comment]
I - @MissaouiChedy really - just added a new interface that makes it easy to add new markdown parsers to Markdown Monster. @ArthurZ Why not roll up your sleeves and create a parser along with options that let you configure what of the plethora of features PanDoc provides you want support. 

* [Creating a custom Markdown Parser in an Addin](https://markdownmonster.west-wind.com/docs/_4ut0j7xoe.htm)

**Comment by ArthurZ** [comment]
Hi @RickStrahl I would love to, it sounds like a fun project to do, alas, I am tied with so many other errands. No chance any time soon. Sorry.
