### ISSUE TITLE
Add Ghost Blog support

### ISSUE THREAD

**Issue by spboyer** [RickStrahl/MarkdownMonster#150]
Current client example that uses the REST Client is here

https://github.com/tryghost/ghost-desktop

It uses electon and wraps the admin web portion I believe from a high level look at it.

**Comment by RickStrahl** [comment]
Looks like the API doesn't support updating yet. From what I can see and heard the desktop app uses a Web View for administration against the Web site :crazy: . A posting API is under construction but apparently not available yet.

**Comment by spboyer** [comment]
Yes. sad.  Interesting bug as well, dragging an image onto the editor surface browses to the `file:///`  and all content is lost. 😠

**Comment by RickStrahl** [comment]
Can you post a separate bug report for the image thing? You can paste, but drag and drop doesn't work due to IE WebBrowser security policy - no way to pick up files there that I've been able to work out unfortunately.

**Comment by spboyer** [comment]
Was addressing the WebView drag/drop for the desktop Ghost.

**Comment by RickStrahl** [comment]
Oh :smile: 

Yes MM at least doesn't do that. But image dragging is something I tried to get working and found no way to do. But at least image pasting works and you can drag documents into MM as long as you drop them into the Window header (anywhere but the editor and preview).

Drag and drop should be a lot easier to deal with :sad:

**Comment by RickStrahl** [comment]
Looks like Ghost will not support any sort of posting API in the future so MM can't post to it. Closing this issue. Please re-open if Ghost comes out with some way to publish.

**Comment by sstjean** [comment]
It looks like Ghost now has a REST API for posting.  Can you check it out an maybe add MM support for it?

https://grantwinney.com/what-is-the-ghost-api/
https://api.ghost.org/v1.22.0/docs

Thanks.

**Comment by RickStrahl** [comment]
There seems to be no news on a Ghost API that supports POSTing so I'm closing this. 

If anybody hears of changes with their API, we can reopen this issue and see about integration.

**Comment by hasokeric** [comment]
Perhaps we can remove the word "Ghost" from the homepage, it was a bit misleading to see. That lead me to start browsing and figuring out how to connect to Ghost, unless it was meant for something else.
```
Supports document based blogs (Jekyll, Wyam, Ghost etc.)
```
