### ISSUE TITLE
Unable to build WeblogAddin

### ISSUE THREAD

**Issue by thomaslevesque** [RickStrahl/MarkdownMonster#152]
Apparently it uses methods that were recently added to WestWind.Utilities (`AddPostFile`, `GetLines`), but the NuGet package wasn't updated, so the methods can't be found.

**Comment by RickStrahl** [comment]
Yes I meant to update the NuGet package for Westwind.Utilities last night but I forgot. For the time being I'd just pushed the code into the local package folder.

I'll update this in a bit.

**Comment by RickStrahl** [comment]
Project should build again. Updated Westwind.Utilities with new NuGet package.

There's been some major refactoring over the weekend and this was one unfortunate casualty :-) I messed up my internal branch and had to revert to master to get back to stable.

Thanks for reporting - I wouldn't have noticed right away.

**Comment by thomaslevesque** [comment]
Thanks 👍
