### ISSUE TITLE
Allow addin to customize Markdig parser

### ISSUE THREAD

**Issue by thomaslevesque** [RickStrahl/MarkdownMonster#153]
I saw #148, which is awesome, but I have a slightly different need.

I need to customize the rendering process, but I don't really need a whole new markdown parser; Markdig works fine, in fact it's what I already use in a [LINQPad script](https://gist.github.com/thomaslevesque/5252ba98381552492708f7a3e6970164) to do my own rendering. It would be nice if there was a way to customize the default markdown parser. There are at least two extension points that could be useful:
- configuring the pipeline
- configuring the renderer

(currently MarkdownMonster doesn't explicitly use a renderer, it just uses `Markdown.ToHtml`, but it could do introduce a renderer by using `Markdown.Convert` instead)

Obviously, I could make my own full `IMarkdownParser` implementation, but then I would lose some features implemented in `MarkdownParserMarkdig`

**Comment by RickStrahl** [comment]
Hi Thomas,

Thanks for this discussion.

Did you see the markdown customization section in the config file? This allows you to effectively specify which pipeline addins run for MarkDig (and some additional ones):

```json
  "MarkdownOptions": {
    "AutoLinks": true,
    "AutoHeaderIdentifiers": true,
    "StripYamlFrontMatter": true,
    "EmojiAndSmiley": true,
    "MediaLinks": true,
    "ListExtras": false,
    "Figures": false,
    "GithubTaskLists": true,
    "SmartyPants": true,
    "RenderLinksAsExternal": false,
    "AllowRenderScriptTags": false,
    "MarkdownParserName": "MarkDig"
  },
```
It doesn't have all of them but quite a few of them. Not exactly what you're looking for but perhaps close enough.

The reason I'm a little hesitant about adding this functionality you request is that we want to support alternate, non-markdig parsers so dealing with the pipeline or using Convert is going to be a stretch. The simple IMarkdownParser interface just has a Parse method and that should be able to handle whatever needs to happen. 

It does provide you with the abillity to subclass the existing Markdown parser. So you can get all the features that are there except perhaps overriding the pipeline creation. Not sure exactly what you're trying to do, but it looks like overriding the constructor would do what you want as described in #148.

Haven't looked at the PR yet but will do later.

Thanks.

**Comment by thomaslevesque** [comment]
> Did you see the markdown customization section in the config file? This allows you to effectively specify which pipeline addins run for MarkDig (and some additional ones):

Ah, thanks, I hadn't seen it. It does solve the problem of configuring the pipeline, I guess. I still need to customize the rendering, but with #154 merged, I can do it just fine.

> Not sure exactly what you're trying to do

My goal is to render code blocks between `[sourcecode]...[/sourcecode]` tags, so that [SyntaxHighlighter](https://wordpress.org/plugins/syntaxhighlighter/) renders it correctly. And now I can do just that :). Thanks!
