### ISSUE TITLE
Plan for sub-list support?

### ISSUE THREAD

**Issue by conspacer** [RickStrahl/MarkdownMonster#156]
As far as I know, sub-lists were not part of the original MD syntax ([DaringFireball syntax guide](http://daringfireball.net/projects/markdown/syntax#list)), yet a lot of MD editors have support for sublists. MarkdownMonster is very slick and easily becoming one of my fav editors, is there plan to support sub-lists either by feature or plugin?
Thanks

**Comment by RickStrahl** [comment]
Most of this should work:

![image](https://cloud.githubusercontent.com/assets/1374013/23383829/4fc4d7ce-fcec-11e6-9dbc-64ae2454223e.png)

Looks like instead of spaces though using tabs works. Sketchy behavior with spaces.

**Comment by conspacer** [comment]
Thanks @RickStrahl . 
Yes, I noticed its possible to get some fashion of sub-lists. MM uses strict-compliance MD (thats a good thing) so:
- 4 spaces after a sub list item
- for ordered sub-list the numbering must begin with '1' (the following pay no mind)
