### ISSUE TITLE
Context menu from right click on a spelling typo hidden

### ISSUE THREAD

**Issue by conspacer** [RickStrahl/MarkdownMonster#157]
When performing spell checks using right click, at the bottom of the window the full menu is hidden under the MM window making the "+ add" menu unreachable.
![mm_hidden-context](https://cloud.githubusercontent.com/assets/23648459/23355997/85048434-fcd8-11e6-8dff-b7f44388dd03.PNG)

**Comment by RickStrahl** [comment]
This is a known issue, but a bit of a pain to fix in the JS code. it's on my internal buglist but way down in priority. I'll leave this open here and we'll get to it at some point.

Thanks for posting.

**Comment by conspacer** [comment]
You are right, its definitely not critical. I just added some carriage returns at the end so there is more room to display the whole menu.

**Comment by RickStrahl** [comment]
Fixed in 2b2b31e8d4983f6f9ae3ebbf53c0ab2ed637fd9b
