### ISSUE TITLE
Error trying to use Snippets 

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#160]
Hi,

Using build 1.2.5

and tried to insert a snippet which resulted in

![image](https://cloud.githubusercontent.com/assets/701808/23381646/36424978-fd0d-11e6-8fbf-1011fad756aa.png)

**Comment by RickStrahl** [comment]
Yes you need to update the addin... There are a few breaking changes in 1.2.5.

Go to the addin manager and update to the latest version for the Snippets and Commander addins they both have the same issue.

v1.2.6 and later has better error handling around this scenario as well - not crashing MM.

**Comment by ArthurZ** [comment]
Who knew.
Yeah that did.
