### ISSUE TITLE
When only 1 document open, titlebar is not updated

### ISSUE THREAD

**Issue by conspacer** [RickStrahl/MarkdownMonster#163]
A saved document does not reflect as its saved name in the titlebar (or in the Windows taskbar). Opening a second document and then switching back to the original document updates the titlebar.
![mm_titlebar-untitled](https://cloud.githubusercontent.com/assets/23648459/23505963/27c343a8-ff46-11e6-82e2-742a82287378.PNG)
Its not a huge deal, just sharing a minor bug (since MM is on its way to becoming a fav 👍 )

**Comment by RickStrahl** [comment]
Fixed.

b89293348b24bd811d595be3ce001343ef28ebd0
