### ISSUE TITLE
Indentation for bullets and lists

### ISSUE THREAD

**Issue by mattnield** [RickStrahl/MarkdownMonster#164]
I've just moved to MarkdownMonster form MarkdownPad, the one thing I miss greatly is the ability to quickly indent lists with `<tab>` and unindent with `<shift>`+`<tab>` much as I do in most text editors.

**Comment by RickStrahl** [comment]
What are you indenting exactly? tab and shift+tab should work with any selection including lists.

**Comment by mattnield** [comment]
Hi Rick,

That's interesting - maybe it's just me using it incorrectly.  I'll explain what I'm doing anyway, just in case :)

I'm running v1.2.8 on Windows 10 and I have the following:
```
1. This is a thing
2. This is another thing that wants a child
3. This is the child
``` 

After typing point 2, I hit `<enter>`, this creates the **3. ** for me, but when I hit `<tab>`, it just adds a **tab** after the number and does not indent.  So what I end up with is: 
```
1. This is a thing
2. This is another thing that wants a child
3.  This is the child
``` 
rather than
```
1. This is a thing
2. This is another thing that wants a child
    3. This is the child
```

Additionally, at this point, I need to manually reset the numbering for the child point to **1.**.  This changes the rendered HTML from 
```
<ol>
<li>This is a thing</li>
<li>This is another thing that wants a child
3. This is the child</li>
</ol>
```

to

```
<ol>
<li>This is a thing</li>
<li>This is another thing that wants a child
<ol>
<li>This is the child</li>
</ol>
</li>
</ol>
```

I hope this provides some clarity into what I'm doing (also happy to be told I'm doing it wrong!)

**Comment by RickStrahl** [comment]
Got it.

Yeah that doesn't work. I'm basically relying on the Markdown formatting that comes with Ace Editor. Bullet lists are not that great in the default behavior in the first place.

I'll take a look and see if there are some gestures that can be added, but most likely the answer on this one will be no-can-do.
