### ISSUE TITLE
Wordpress post meta (custom fields) are not added when publishing

### ISSUE THREAD

**Issue by thomaslevesque** [RickStrahl/MarkdownMonster#165]
The `mt_markdown` post meta is not inserted.

This seems to be because MM specifies both `id` and `key` for custom fields, but WordPress expects only `key`. Clearing `id` solves the problem. I'd send a PR, but I'm worried it could break things for non-WordPress blogs... Do you have a way to test it?

**Comment by thomaslevesque** [comment]
I eventually found a way to fix it without affecting non-WordPress blog.

**Comment by RickStrahl** [comment]
I'll take a look at the PR, but what actually happens when you look at the data on the server? mt_markdown doesn't make it there?

**Comment by thomaslevesque** [comment]
> mt_markdown doesn't make it there?

No, but it does with my fix

**Comment by thomaslevesque** [comment]
As mentioned in https://github.com/RickStrahl/MarkdownMonster/pull/168#issuecomment-284854076, `id` is actually the database id of the custom field. If `id` is set, WordPress (and presumably other platforms) attempt to update the custom field with that id. If `id` is _not_ set, WP inserts a new custom field (even if one with the same key already exists).

**Comment by RickStrahl** [comment]
Added support for pulling the IDs from a post when it is returned after posting and updating any custom fields we have defined explicitly in our metadata.

39c1d5a7871f2da4c7e50ac80ae72ac0d16c7bf6

**Comment by thomaslevesque** [comment]
@RickStrahl great, thanks! I'll try it ASAP.

**Comment by thomaslevesque** [comment]
Doesn't seem to work... the custom field ids are not updated in the post's metadata, and it still creates duplicates. Looking into it now.

**Comment by thomaslevesque** [comment]
Oh, wait... I forgot that just starting the app didn't rebuild the addins.

Looks like it partially works:
- for custom fields defined in the post's metadata, it retrieves the ID from the server and updates the metadata, but my Wordpress workaround which removes the `id`s from the `XmlRpcPost` still causes duplicates; the workaround needs to be removed now that we understand what's going on (*).
- for custom fields defined at the blog-level, the ID isn't persisted. The custom field should probably be added at the post level.

(*) if I remove it, it solves the duplicate issues, but the other fields are still not sent... I think this is because their id is set to an incorrect value.

**Comment by thomaslevesque** [comment]
Also, MM doesn't retrieve the id for `mt_markdown`, so it's always inserted even if it's already present. The same issue probably exists for `wp_post_thumbnail` as well.

**Comment by thomaslevesque** [comment]
I'm working on a fix. Not sure I'll be able to finish today, but probably this weekend.

Just a question: is there a reason to add the `wp_post_thumbnail` custom field in `MetaWebLogWordpressApiClient.PublishCompletePost`? It would make things easier if I could do it in `WebLogAddIn.SendPost` instead (like `mt_markdown`)

**Comment by RickStrahl** [comment]
Lots of stuff here.

Weblog level fields should be added to the post level custom fields when the post is created and then be persisted. This should sort of work, but there needs to be logic to not keep adding those values over and over again. I think there needs to be a generic add method that checks whether a field exists already and if it does update it leaving ID intact if there is one.

mt_markdown/wp_post_thumbnail - I explicitly filtered those out, mainly because mt_markdown will be large (essentially the full markdown). So maybe that one needs a special case that deals with a placeholder value that gets replaced from the actual markdown when posted.

wp_post_thumbnail in PublishCompletePost - the reason there is that is that that's where we can deduce a thumbnail picture based on the first picture in the post automatically - that can only happen when processing the post and posting images. The alternative to move it out of there would be to store the image somewhere and pick it up later, but I think that would be even more obtrusive.

I'm going to stay out of that code for now if you want to take a crack at this. Otherwise let me know - I think most of these should be minor tweaks.

**Comment by thomaslevesque** [comment]
> mt_markdown/wp_post_thumbnail - I explicitly filtered those out, mainly because mt_markdown will be large (essentially the full markdown). So maybe that one needs a special case that deals with a placeholder value that gets replaced from the actual markdown when posted.

Yes, mt_markdown is a special case. We need to persist its ID, but not its value.

> wp_post_thumbnail in PublishCompletePost - the reason there is that is that that's where we can deduce a thumbnail picture based on the first picture in the post automatically - that can only happen when processing the post and posting images. The alternative to move it out of there would be to store the image somewhere and pick it up later, but I think that would be even more obtrusive.

OK, but we still need to persist its ID. Perhaps in the same way as for mt_markdown?

**Comment by RickStrahl** [comment]
The problem with the thumbnail is that the URL comes from the server so it can only be gotten in one place after an image upload. But that said we CAN store that value in the meta data and resend it each time. Mm only adds it if the value is blank. So that one is easy.

**Comment by thomaslevesque** [comment]
I just realized something: MM doesn't really need to persist the custom fields... It could just fetch the post before publishing to get them. Of course, publishing would take a bit longer, but it might be an acceptable trade-off.

**Comment by RickStrahl** [comment]
Well in theory all the information about a post is stored on the server, right so we might not need any meta data at all :-) Just pull the existing post down, update the html and markdown plus whatever changes the user makes and we're done. 

Hmmm... that seems too simple :-)

Would still need the blog info and post Id but beyond that everything else is in the post itself.

Gotta sit on that a bit and think.

**Comment by thomaslevesque** [comment]
Some more thoughts: in hindsight, maybe saving *all* custom fields from the post wasn't such a good idea. Wordpress can generate more custom fields for technical purposes, that don't ever need to be seen by the user. For instance, in a post I published today, I got this:

```yaml
customFields:
  mt_markdown:
    id: 738
    key: mt_markdown
    value: 
  _syntaxhighlighter_encoded:
    id: 739
    key: _syntaxhighlighter_encoded
    value: 1
  _encloseme:
    id: 760
    key: _encloseme
    value: 1
  _jetpack_dont_email_post_to_subs:
    id: 747
    key: _jetpack_dont_email_post_to_subs
    value: 1
  _edit_lock:
    id: 754
    key: _edit_lock
    value: 1490918216:1
```

Having these in the YAML just adds noise. I think only the custom fields that need to be sent by MM should be persisted (sorry for the back and forth about this... saving all the fields was my idea 😳).

Anyway, if you decide to not persist the custom fields at all (except the ones explicitly set by the user), as suggested above, the problem goes away.

**Comment by RickStrahl** [comment]
Yeah I'm going back and forth on this as well.

I think it might be best to pull all the customfield data from the server and then update it with whatever MM tracks locally. So you get the full list from the server, and MM adds or updates any matching keys. That way the user never sees the server maintained ones. This also removes mt_markdown (which is implicit) and potentially the featured image.

I was going to go with just pulling all the data from the server, but this is a problem if you post to multiple blogs as the meta data then is lost if you go to another blog.

Current state works reasonably well for me - but then I'm not running Wordpress and my custom solution on the server doesn't do any custom field processing short beyond values I actually use :-)

OTOH, hard to test for me, as I don't see all the noise you're describing from my WordPress test account...

**Comment by RickStrahl** [comment]
So I wonder what happens on the server when you update a post you don't update all the fields that are already there? Are those existing fields deleted? Do they stay? 

In my own server implementation on my server I kill all the custom fields and update only with what was sent.

So one way to fix this would be to download the post from the server, add all the existing custom fields, then overwrite any values that are set by MM (explicit value):

```cs
// Custom Field Processing:
            // Add custom fields from existing post
            // then add or update our custom fields

            var userMetaCustomFields = meta.CustomFields; // reset when done!
            var customFields = new Dictionary<string, CustomField>();

            if (!string.IsNullOrEmpty(meta.PostId))
            {
                var existingPost = GetPost(meta.PostId, weblogInfo);
                if (existingPost != null && meta.CustomFields != null)
                    customFields = existingPost.CustomFields
                                               .ToDictionary(cf => cf.Key, cf => cf);                
            }

            if (meta.CustomFields != null)
            {
                foreach (var kvp in meta.CustomFields)
                {
                    customFields.Add(kvp.Key, kvp.Value);
                }
            }
            if (!string.IsNullOrEmpty(markdown))
            {
                AddOrUpdateCustomField(customFields, "mt_markdown", markdown);
            }
            if (weblogInfo.CustomFields != null)
            {
                foreach (var kvp in weblogInfo.CustomFields)
                {
                    if (!customFields.ContainsKey(kvp.Key))
                        AddOrUpdateCustomField(customFields, kvp.Key, kvp.Value);
                }
            }

            WeblogModel.ActivePost.CustomFields = customFields.Values.ToArray();
```

I think this would work but you effectively could never delete any server generated keys as they would always be implicitly added.

**Comment by RickStrahl** [comment]
If updated the code in the repo to use the above logic. In testing against my Wordpress test account it looks like this is now doing what we want:

* Leaves existing meta data from the server intact
* Updates custom keys, leaving the ID intact
* No duplicates :-)

Give it a shot and see if this work.

**Comment by thomaslevesque** [comment]
> I think it might be best to pull all the customfield data from the server and then update it with whatever MM tracks locally. So you get the full list from the server, and MM adds or updates any matching keys. That way the user never sees the server maintained ones. This also removes mt_markdown (which is implicit) and potentially the featured image.

Yes, this is what I had in mind. It would also eliminate blog-level custom fields, which would no longer need to be persisted at the post level.

> So I wonder what happens on the server when you update a post you don't update all the fields that are already there? Are those existing fields deleted? Do they stay?

They stay. If you want to delete a custom field, apparently you have to send its ID with null as the key.

> So one way to fix this would be to download the post from the server, add all the existing custom fields, then overwrite any values that are set by MM (explicit value):

Basically, yes.

> Give it a shot and see if this work.

I will!

**Comment by thomaslevesque** [comment]
Seems to work fine so far, nice work 👍 . It's much better like this, the custom fields no longer pollute the front matter header.

I just see one more thing that could be improved, if it's not too late: now that the id no longer needs to be serialized, the `customFields` property in YAML could be made simpler. Currently it looks like this:
```yaml
customFields:
  foobar:
    key: foobar
    value: 42
```
The key is repeated twice for no good reason. Instead it could be like this:
```yaml
customFields:
  foobar: 42
```
