### ISSUE TITLE
Support custom post metadata

### ISSUE THREAD

**Issue by thomaslevesque** [RickStrahl/MarkdownMonster#167]
A plugin I use on my blog requires that posts have a specific metadata ("custom field") set in wp_postmeta. When I create the post from the web UI, this metadata is inserted automatically, but not when I publish from MM. If I could specify custom fields to always set for this blog, it would be very helpful.

I realize it's a very specific use case, but without this change I can't publish directly from MM, or if I do, I have to add the metadata manually in the database, which is a pain... Anyway, the change is very small, as you'll see in the PR. The concept could also be extended to per-post custom fields.

**Comment by RickStrahl** [comment]
Actually this is something I've been thinking about myself. Markdown Monster already sends up custom field data (mt_markdown sends the raw Markdown text so server can store that optionally).

I need to review and make sure this doesn't break things. I don't have a ton of Metaweblog API test blogs I can test against.  

Will take a look tonight.
