### ISSUE TITLE
javascript error appear when program is loading

### ISSUE THREAD

**Issue by qnote** [RickStrahl/MarkdownMonster#169]
I see it every time when the program is loaded. I can assume that the error appear because I have not installed latest version of Internet Explorer, it's that?
![md-mm2](https://cloud.githubusercontent.com/assets/21096180/23577930/47ff5a6e-00ed-11e7-9750-d8edb67188cd.png)

**Comment by RickStrahl** [comment]
Can you retry with 1.2.9.2 please? There was an issue in 1.2.9.1.
