### ISSUE TITLE
Button icons missing (cosmetic only)

### ISSUE THREAD

**Issue by daughtkom** [RickStrahl/MarkdownMonster#17]
I am on Win 7 as provided by my client.  When I click to add a hyperlink, this dialog displays and the icons on the buttons are missing.  The functionality is not affected.  This is just a cosmetic issue.

![2016-07-19 07_43_50-embed formatted code](https://cloud.githubusercontent.com/assets/1824392/16954192/2d85d85c-4d8d-11e6-855f-79cf305b85f8.png)

**Comment by RickStrahl** [comment]
I've seen this happing for a few people and I'm not sure exactly what's causing this. I have several machiens I test on (all newer versions of Windows though Win10 and Win2012) and it appears to work there.

The icons are FontAwesome fonts, but they are loaded as resources embedded in the app so in theory this should work fine. Not sure what difference there is that this might be happening.

What locale are you running in? The ones I've seen were all non en-US locales.

**Comment by daughtkom** [comment]
I think I just figured out the problem.  I didn't actually have FA installed as a font on my laptop.  If I add to the Fonts control panel, the buttons display correctly.

**Comment by daughtkom** [comment]
To answer your question, English US, Win 7 SP1 Enterprise.

**Comment by RickStrahl** [comment]
Added FontAwesome to installer.

Fixed in d3c5122beb07f3481c28a1d42735f7c51bf17a3e
