### ISSUE TITLE
Distraction free mode doesn't hide enough

### ISSUE THREAD

**Issue by dracan** [RickStrahl/MarkdownMonster#170]
Hi. First, great work on the editor! :)

It's great having the distraction free mode, but seem odd that the menu bar is still there.

What would be amazing, is if it worked almost like vscode's "Zen mode" - where it literally hides everything except the editor and preview pane. So menubar, titlebar, statusbar, and toolbar hidden.

**Comment by RickStrahl** [comment]
Well the menu isn't exactly 'spacey' and it does leave you access to features. Without the menu there are literrally no features accessible (other than hotkeys and what's on the Window bar). Maybe I'll add another flag that allows for the two modes and also maximize the display perhaps (like VsCode)?

**Comment by dracan** [comment]
I guess it depends on the definitely of a distraction. Personally, it's not about freeing up space, but more about having a mode that I can switch to which removes all other clutter. In vscode, I quite often toggle the zen mode via the shortcut to get rid of everything other than the code. Where it literally becomes a full screen app. For a markdown editor, I'd personally still want the preview displayed. So my screen would literally be the splitscreen display "wall to wall" :)

**Comment by RickStrahl** [comment]
So I've added a new property.

```
string DistractionFreeModeHideOptions = "toolbar,statusbar,menu,preview,tabs,maximized";
```

The things listed are hidden except for maximized if set maximizes the form and resets when turning off.

Tabs is not working yet - can't quite figure out how to hide the tab headers. (@thomaslevesque any idea?)

It's in 1.2.14.5 (on the site)
ef0fb6791ea6bf975dd3a9656f42dca31560790f

**Comment by dracan** [comment]
Wow, that was quick! :-) Thank you for doing that, it sounds perfect! I've not had chance to try yet (kids, etc!), but will have a look a bit later.

Thanks again for doing this :-)

**Comment by dracan** [comment]
Just tried that - so much better! :) Thank you for this. One little issue I've noticed, is that when coming out of distraction mode, the window is no longer maximized - it becomes a much smaller window. Not a biggie, as to be honest, I'd probably stay in distraction free mode most of the time anyway - just thought I'd mention it so you knew about it.

**Comment by thomaslevesque** [comment]
> Tabs is not working yet - can't quite figure out how to hide the tab headers. (@thomaslevesque any idea?)

`TabablzControl` doesn't seem to have an option for hiding the tabs, so you'll need to edit the template. The easiest way is to subclass `TabablzControl`, add a `ShowTabs` dependency property, create a template for this new control (based on the default `TabablzControl` template), and add a trigger in the template to show or hide the tabs based on the `ShowTabs` property.

**Comment by RickStrahl** [comment]
I have a custom template for the headers already so maybe I can just use TabItem.Visibility to handle this.

**Comment by thomaslevesque** [comment]
> I have a custom template for the headers already so maybe I can just use TabItem.Visibility to handle this.

`TabItem` represents the whole tab (header and content), so hiding it would also hide the editor

**Comment by RickStrahl** [comment]
Yeah but it doesn't work that way for the TabablzControl. So I can hijack the property :-)

**Comment by RickStrahl** [comment]
@dracan - fixed the WindowState reset - now when you come out of distractionfree mode it'll remember your previous window state (normal or maximized). It'll be in the next drop (post 1.2.14.5)

b506939d96e66ff0f16ab24d8405b51058f5f4e1

**Comment by RickStrahl** [comment]
So this seems to work in the tab template:

```xml
<Style x:Key="TrapezoidDragableTabItemStyle"  TargetType="{x:Type local:DragablzItem}">
...
 <Setter Property="Visibility" Value="{Binding RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type mm:MainWindow}}, Path=Model.Configuration.WindowPosition.TabHeadersVisible}" />
```

A bit wonky though - The tabs don't collapse, but hide (@ButchersBoy)

**Comment by RickStrahl** [comment]
1.2.14.6 is out with these changes included.
