### ISSUE TITLE
Specifying a featuredImage when updating a WordPress post fails

### ISSUE THREAD

**Issue by thomaslevesque** [RickStrahl/MarkdownMonster#171]
If you specify a `featuredImage` URL in the metadata for a post that is already published, it gives this error:

> [404] Invalid attachment ID

Apparently, when editing a post, WordPress expects the attachement id, not a URL. It's only when creating the post that you can specify a URL.

Apparently there is some code to account for this (`FeaturedImageId` property in post metadata), but it's never set.

**Comment by thomaslevesque** [comment]
> It's only when creating the post that you can specify a URL.

Scratch that. It doesn't work with a new post either. Looks like you can _never_ pass a URL as wp_post_thumbnail (at least for Wordpress)

**Comment by RickStrahl** [comment]
Yeah - I remember now when I tried to find this info (which is hard to come by). I think you upload an image, get the ID and then post that. Of course for anything but wordpress this is worthless since nothing else stores everything in a db.

**Comment by thomaslevesque** [comment]
> Of course for anything but wordpress this is worthless since nothing else stores everything in a db.

Yeah, WordPress is awful in so many ways. For instance, I realized that when it returns this "Invalid attachment ID" error, it still inserts the custom fields specified in the (invalid) request. Perhaps the developers had never heard about transactions 🙄

**Comment by RickStrahl** [comment]
So are you getting errors when you post every time, or are you getting an error and it all goes through and the post makes it?

When I post to my WordPress test account I get no errors with a a featured image AND the featured image - sent as a URL seems to work. I see the first image on post listings page.

**Comment by thomaslevesque** [comment]
> So are you getting errors when you post every time, or are you getting an error and it all goes through and the post makes it?

I get the error every time, and the post is created on WordPress in status "auto-draft", whatever this means. It's not visible anywhere except in the database.

**Comment by RickStrahl** [comment]
Local Wordpress install? Older version? I wonder what's different. You can see the post I linked right? I just posted that after we talked here with the auto-featured image pulled in.

**Comment by RickStrahl** [comment]
Where are we on this issue? I think this is all addressed with the latest set of changes of pulling custom field data from the existing post and then updating only as needed.

**Comment by thomaslevesque** [comment]
Hi @RickStrahl, sorry, I somehow missed your previous message. I had tried on a hosted Wordpress install, which was up to date.

I didn't try again to set the featured image explicitly, but it did set an image when I reported #178, so I guess it works now.
