### ISSUE TITLE
Post is not marked as modified after first publication

### ISSUE THREAD

**Issue by thomaslevesque** [RickStrahl/MarkdownMonster#172]
When a post is published for the first time, MM persists the post id (among other things) in a comment at the end of the markdown. But it doesn't save the post, and doesn't mark it as modified, so it can't be saved. If the user closes MM, when he reopens the post, it will still be considered new.

**Comment by RickStrahl** [comment]
Fixed.

bb3edce63de31c9369104fab0f7f8c90fcbae3dc

**Comment by thomaslevesque** [comment]
Thanks Rick!

**Comment by RickStrahl** [comment]
FWIW all of that should now persist as YAML at the top of the post, not at the end.
