### ISSUE TITLE
Suggestion: Remove bullet or number when hitting return on empty item

### ISSUE THREAD

**Issue by bleroy** [RickStrahl/MarkdownMonster#176]
When I write a bulleted list or numbered list, the editor writes the next bullet or number automatically on return. So far, so good, but when hitting return for the second time without entering text for the new item, I would expect the editor to behave like Word in the same situation, which is to understand that I want to break out of the list and resume the document flow with a new paragraph, and as such remove the empty bullet or number.

**Comment by RickStrahl** [comment]
Yeah that one bugs me too :-) Not easy to fix unfortunately though as it's buried deep in Ace's internal Markdown syntax processing. 

I need to dig into that though - there are a few other things that I'd love to address.

**Comment by RickStrahl** [comment]
I've taken a closer look trying to track down where this logic is fired in the ACE Editor Markdown render tooling but I haven't had much luck. I've made a few other tweaks in the process but I couldn't find the logic for the bullet default.

**Comment by RickStrahl** [comment]
Added the ability to turn off bullet auto-complete - actually it's now off by default and you have to explicitly turn it on with a new switch: `Editor.EnableBulletAutoCompletion`.

db0c4c7ca9753641a25166e6ffdfd776684cec6c
