### ISSUE TITLE
How can I prevent the creation of a featured image?

### ISSUE THREAD

**Issue by thomaslevesque** [RickStrahl/MarkdownMonster#178]
Apparently MM uses the first image in the post as the featured image. But I don't want that... Is there a way to prevent it?

**Comment by RickStrahl** [comment]
I thought there was a way to do this, but it looks in all the reshuffling we did the override got wiped out :-)

I'm adding an InferFeaturedImage property to the meta data, that if false, won't try to retrieve a featured image by default. Thinking about also allowing editing for the FeatureImageUrl and FeatureImageId in the UI. But for now it'll go into the meta data.

**Comment by RickStrahl** [comment]
Ok so now you can do:

![image](https://cloud.githubusercontent.com/assets/1374013/24389049/6d178224-131a-11e7-94f2-8ea8dea121c1.png)

f63cdc500a1d1a8ead547a12bfc4d5a07d695d1b

**Comment by thomaslevesque** [comment]
Thanks @RickStrahl, I'll give it a try.

**Comment by thomaslevesque** [comment]
It's not working. The "infer featured image" option is always forced to true on publish, whether I set it in the YAML or in the UI. Apparently the problem is in `ButtonPostBlog_Click`, where the comment says "Update the Markdown document first". The serializer apparently ignores the `InferFeaturedImage` property if it's false (probably because it assumes that false is the default value). So when the YAML is deserialized later, this property isn't set by the deserializer, and keeps the value set by the property initializer, which is true.

**Comment by thomaslevesque** [comment]
OK, apparently there are two ways to fix it:

- Add the `EmitDefaults()` option to the `SerializerBuilder` to force it to serialize properties even if they have the default value
- Add the `[DefaultValue(true)]` attribute to the `InferFeaturedImage` property.

I think the first option would be better, because it would make the settings more discoverable.
