### ISSUE TITLE
Use IME (CHT) sometime will output alphabet

### ISSUE THREAD

**Issue by kkbruce** [RickStrahl/MarkdownMonster#18]
I use Chinese IME input Chinese word, like: 

"IFL記"

Input "IFL" should output "記"，but Monster sometime output "IFL記"。

**Comment by RickStrahl** [comment]
I'm not familiar with how these special characters work. Markdown Monster outputs UTF-8. Can you describe how this input works correctly with UTF-8 output normally?

Also you say *sometimes* - any hint on when it works and when it doesn't?

**Comment by RickStrahl** [comment]
Closing due to not enough feedback.
