### ISSUE TITLE
Open document at previous position

### ISSUE THREAD

**Issue by gsej** [RickStrahl/MarkdownMonster#181]
When opening a document which I've edited recently, it would be nice if it opened scrolled to the previous position rather than back at the start of the file. I've got a couple of larger files I work with and this would be a great convenience.

**Comment by RickStrahl** [comment]
Already implemented for 1.2.17 and later. Works only for recent files that are opened when mm starts.

**Comment by gsej** [comment]
That's great - thanks. I didn't realise it did that (I've always launched the app by double-clicking the document) - just what I need.
