### ISSUE TITLE
Chocolatey releaseNotes url goes to a 404.

### ISSUE THREAD

**Issue by Spunkie** [RickStrahl/MarkdownMonster#183]
Just a small caplization bug I found in the chocolatey pkgs (install/portable), the url used is https://github.com/RickStrahl/MarkdownMonster/blob/master/Changelog.md and it should be
https://github.com/RickStrahl/MarkdownMonster/blob/master/ChangeLog.md

Also your latest version just got approved at lightspeed, what's your secret? :shipit:

**Comment by RickStrahl** [comment]
Fixed. Thank you.

Once a package was approved once, it goes through automatic review and approval so subsequent submissions are much quicker. I think it's still on some sort of queue, that gets batched by choco at some point, because it definitely takes longer on some occasions than others.

**Comment by gep13** [comment]
@Spunkie @RickStrahl just to add some clarity to this...

All packages that are submitted to chocolatey.org are held until they are ran through the package-verifier and the package-validator.  The first is a tool that ensures that the package in question installs correctly, without errors, on a fresh VM.  The second is a scanning tool that inspects the actual content files of the package to ensure that there are no identifiable issues.

As I said, ALL packages got through this part of the process.

However, some packages can be marked as trusted (as is the case with MarkdownMonster).  At this point, assuming that both the package-verifier and package-validator succeed, the package version is then immediately marked as approved.  For any other package, they are then held in a queue until a human comes along to manually verify that there is nothing suspicious going on with the package.

Depending on the number of submitted packages, you will see a difference the time it takes for package-verifier and package-validator to complete.

Hope that helps to explain things.

**Comment by Spunkie** [comment]
@gep13

**Comment by RickStrahl** [comment]
FWIW I fixed the links back to the old proper syntax (Changelog.md). This got changed by accident I guess and I wasn't able to fix it with Git on Windows, but I could fix on Github. Posting here just as a reference to myself :)
