### ISSUE TITLE
Folder Browser: Drag & drop image files to editor window

### ISSUE THREAD

**Issue by HeyJoel** [RickStrahl/MarkdownMonster#192]
It would be handy to be able to drag and drop an image file from the new folder browser sidebar onto the markdown editor window and get a markdown reference to that image file. This would work in the same way that it already does when you drag a file from the file explorer onto the editor window.

**Comment by RickStrahl** [comment]
Added support for Dragging files into markdown text as image link. 25b77f53fd6ac9dbae3ebe40171dedbfd9f1e704

Pushed out with 1.3.8.2.
