### ISSUE TITLE
Find does not work

### ISSUE THREAD

**Issue by mawibo** [RickStrahl/MarkdownMonster#193]
I'm using 1.3.8.2 and 'Find in document' does not work. When I select it in the Edit menu or when using Ctrl-F, nothing happens. When selecting text however, pressing F3 moves the caret to the next occurrence of the selected text.

**Comment by RickStrahl** [comment]
Thanks for reporting this. Regression from a previous update where editor extensions were accidentally removed.

Fixed: 99723af318f4e35a5da9aece4b34cfe650459e2b

will be out shortly in 1.3.10.
