### ISSUE TITLE
Support publishing as Private on Wordpress blogs

### ISSUE THREAD

**Issue by brandonh-msft** [RickStrahl/MarkdownMonster#196]
Draft is good, but Private would also be nice.

I've not yet figured out how to do this with Custom Fields. Perhaps instructions in this and/or a pre-defined custom field for Wordpress blogs that can be set to 'true/false' or something would suffice.

**Comment by RickStrahl** [comment]
Hmmm... Yeah there's a post_status field in the WordPress API. It's not mapped currently by MM.

I've added the field, but need to think bout how to hook up the UI for this.

**Comment by brandonh-msft** [comment]
That might be enough for a stopgap. i'm going to set it to `private` and see what it does. will comment on this issue so ppl have a way to do it in the meantime.

**Comment by brandonh-msft** [comment]
didn't work :sadpanda:

**Comment by RickStrahl** [comment]
Ah hell...

![image](https://cloud.githubusercontent.com/assets/1374013/26224425/2c8b55f6-3bd7-11e7-952d-327d5b48556f.png)

😅
