### ISSUE TITLE
Suggestion: GitHub Flavored Markdown support

### ISSUE THREAD

**Issue by daughtkom** [RickStrahl/MarkdownMonster#20]
Please consider adding some GFM support to the preview pane, especially support for tables.

**Comment by RickStrahl** [comment]
Currently this isn't supported as the underlying renderer (CommonMark.NET) doesn't support it. 

One of the things on my list to explore is to use the GitHub API to handle html rendering for Github flavored Markdown, but it'll require credentials to make this workable which is something I'd like to avoid having to store locally.

**Comment by lextm** [comment]
Hi, DocFX from Microsoft features a GitHub flavor compliant Markdown parser, https://github.com/dotnet/docfx so that you don't need to do it yourself.

As this is the project behind the new http://docs.microsoft.com I believe its quality is high enough to enable this scenario.

**Comment by RickStrahl** [comment]
I'll take a look next week when I have more time. Thanks for the reference - did not know about that one.

**Comment by RickStrahl** [comment]
I've added support for the MarkdownLite and MarkDig parsers and they are integrated in the latest builds. They're not released yet, but you can build from source as of today.

The parser is configurable via the `MarkdownParser` configuration setting in MarkdownMonster.json. The following values are supported:

* CommonMarkNet
* MarkdownLite
* MarkDig

The latter two both support Github Flavored Markdown including tables.

This is currently experimental.

Some thought needs to be given to how tables should be rendered in the previewer for each theme as tables render without any CSS tags.

**Comment by daughtkom** [comment]
For anyone else that comes here: per the release notes, the two choices are CommonMarkNet and MarkDig.  MarkdownLite does not appear to be supported in the current release.

**Comment by RickStrahl** [comment]
Yeah I removed that after playing around with MarkDig a bit. It looks like MarkDig is much more flexible both in terms of feature support as well as extensibility so that's what I think will be the eventual replacement for CommonMarkNet.

MarkDig is now the default engine loaded. Any feedback on rendering problems would be useful. The MarkDig folks also seem uber responsive to bug reports which is awesome.

https://github.com/lunet-io/markdig
