### ISSUE TITLE
Suggestion Make selected tab more prominent.

### ISSUE THREAD

**Issue by aGiftKit** [RickStrahl/MarkdownMonster#200]
First, I do love this tool.  You have done a great job making it dirt simple to edit the Markdown files that are starting to get scattered all over my hard drive.

My one suggestion is to consider making the selected tab easier to identify.   I am used to the old school lighter Visual Studio colors, although I understand the world is going dark.   I did play with the different themes provided, but they only change the content area, and the main app is still "dark".   

Again, I know many "true devs" prefer this darker theme.  I am not a fan, but if we are going to be stuck with it, can we at least make it clear which tab is selected?     

Again, just a suggestion, and by no means a bug.    Thanks again for a great product.

In the following screenshot, the two tabs are different, but in my brain (coming from that lighter side), I am seeing the 170528_next.md file as the selected tab. :-)

![image](https://cloud.githubusercontent.com/assets/5102553/26548766/bc149524-4443-11e7-961d-7ab7d58a34a4.png)

**Comment by RickStrahl** [comment]
Well the UI is meant to be dark so there's not a lot I can do without using a loud color for the selected tab which is really not something I'd like to do :-)

I did make s slight change and made the text on the tab a little darker yet, so it's clearer that the tab is not active.

![image](https://cloud.githubusercontent.com/assets/1374013/26568453/53646908-44b8-11e7-9686-c062b2e4393c.png)

**Comment by aGiftKit** [comment]
This change helps.  The unselected tabs appear more "grayed", so it does direct me better to the selected tab.
Thanks for considering this change.   You do know that now somebody else is going to "complain" that the text for the unselected tabs is hard to read and needs to be more prominent. :-)

Thanks again for a great tool.
