### ISSUE TITLE
Check for update seems broken

### ISSUE THREAD

**Issue by mawibo** [RickStrahl/MarkdownMonster#201]
Although 1.3.20 is out, my 1.3.8.2 version still says that it's up to date.

**Comment by RickStrahl** [comment]
Update checks only occur once a week or 10 days I think. The update frequencycan be set in the settings.

Could that be it?

**Comment by mawibo** [comment]
Hi Rick,

No, I performed a manual check for an update and it said I was using the latest version, when clearly that was not the case.

Maarten

**Comment by RickStrahl** [comment]
Thanks - will take a look.

**Comment by RickStrahl** [comment]
Ugh - thanks for pointing this out. This code was hopeless broken. The check version check fails silently because it's a non-essential feature, but a recent refactoring broke out all the URLS used by app and the structure wasn't initialized.

This will be fixed in the next update.
