### ISSUE TITLE
Dragging selected text to a new location does not work

### ISSUE THREAD

**Issue by mawibo** [RickStrahl/MarkdownMonster#203]
See below picture:

![markdown monster dragging text](https://cloud.githubusercontent.com/assets/19243524/26657099/541ae826-4662-11e7-95bd-8fea0cdfb6b6.jpg)

Maarten

**Comment by RickStrahl** [comment]
Unfortunately this is not supported. 

Checked into it and looks like ACE supports drag and drop, it doesn't work with IE. IE will grab the entire control instead of the selected word and even in  a standalone instance will do some very strange stuff when the dragged content is dropped.
