### ISSUE TITLE
Add support for summary/details elements

### ISSUE THREAD

**Issue by batzen** [RickStrahl/MarkdownMonster#205]
Hi there,

great project!
I just noticed that summary/details elements are not support and not rendered correctly.

As you can read in https://github.com/dear-github/dear-github/issues/166 this is at least supported on GitHub.

Could you add support for this?

Here is a sample of what i mean:

<details>
  <summary>Click to expand</summary>
  whatever
</details>

One more advanced sample:

<details><summary>Click here to show the list of replaced/renamed/removed things</summary><p>

|Old|New|
|---|---|
| ButtonDisabledBackgroundBrush | --- |
| ButtonDisabledBorderBrush | --- |
| SliderShadowBrush | WhiteBrush |
| SliderLightenBrush | WhiteBrush |
| BackstageBackgroundBrush | WhiteBrush |
| BackstageControlHoverBorderBrush | Fluent.Ribbon.Brushes.Button.MouseOver.BorderBrush |
| BackstageControlActiveBorderBrush | Fluent.Ribbon.Brushes.Button.Pressed.BorderBrush |
| ButtonBorderBrush | Fluent.Ribbon.Brushes.Control.BorderBrush |
| ButtonHoverOuterBackgroundBrush | Fluent.Ribbon.Brushes.Button.MouseOver.Background |
| ButtonHoverOuterBorderBrush | Fluent.Ribbon.Brushes.Button.MouseOver.BorderBrush |
| ButtonPressedOuterBackgroundBrush | Fluent.Ribbon.Brushes.Button.Pressed.Background |
| ButtonPressedOuterBorderBrush | Fluent.Ribbon.Brushes.Button.Pressed.BorderBrush |
| ButtonCheckedBrush | Fluent.Ribbon.Brushes.HighlightBrush & Fluent.Ribbon.Brushes.Button.MouseOver.Background |
| CheckBoxHoverBackgroundBrush | Fluent.Ribbon.Brushes.Button.MouseOver.Background |
| CheckBoxHoverBorderBrush | Fluent.Ribbon.Brushes.Button.MouseOver.BorderBrush |
| CheckBoxPressedBackgroundBrush | Fluent.Ribbon.Brushes.Button.Pressed.Background |
| CheckBoxPressedBorderBrush | Fluent.Ribbon.Brushes.Button.Pressed.BorderBrush |
| CheckBoxOutterBorderBrush | --- |
| CheckBoxOutterBackgroundBrush | --- |
| CheckBoxInnerBorderBrush | --- |
| CheckBoxInnerBackgroundBrush | --- |
| CheckBoxHoverOutterBorderBrush | --- |
| CheckBoxHoverOutterBackgroundBrush | --- |
| CheckBoxHoverInnerBorderBrush | --- |
| CheckBoxHoverInnerBackgroundBrush | --- |
| CheckBoxPressedOutterBorderBrush | --- |
| CheckBoxPressedOutterBackgroundBrush | --- |
| CheckBoxPressedInnerBorderBrush | --- |
| CheckBoxPressedInnerBackgroundBrush | --- |
| GalleryBorderBrush | Fluent.Ribbon.Brushes.Control.BorderBrush |
| InRibbonGalleryBorderBrush | Fluent.Ribbon.Brushes.Control.BorderBrush |
| BackstageGalleryItemHoverBackgroundBrush | Fluent.Ribbon.Brushes.Button.MouseOver.Background |
| BackstageGalleryItemSelectedBackgroundBrush | Fluent.Ribbon.Brushes.Button.Pressed.Background |
| BackstageToggleButtonCheckedBorderBrush | Fluent.Ribbon.Brushes.HighlightBrush |
| BackstageToggleButtonCheckedBackgroundBrush | Fluent.Ribbon.Brushes.Button.MouseOver.Background |
| QuickAccessToolbarPopupBackgrondBrush | {Binding Background, RelativeSource={RelativeSource AncestorType=Window}} |
| WindowContentBorderBrush | Fluent.Ribbon.Brushes.Separator.BorderBrush |
| GroupBoxSeparatorBorderBrush | Fluent.Ribbon.Brushes.Separator.BorderBrush |
| GroupBoxSeparatorBackgroundBrush | Fluent.Ribbon.Brushes.Separator.Background |
| ContextMenuSeparatorBrush | Fluent.Ribbon.Brushes.Separator.BorderBrush |
| KeyTipBackgroundBrush | Fluent.Ribbon.Brushes.KeyTip.Background |
| KeyTipBorderBrush | Fluent.Ribbon.Brushes.KeyTip.BorderBrush |
| GalleryHeaderBackgroundBrush | Fluent.Ribbon.Brushes.Gallery.Header.Background |
| TextBoxBorderBrush | Fluent.Ribbon.Brushes.TextBox.BorderBrush |
| TextBoxBackgroundBrush | Fluent.Ribbon.Brushes.TextBox.Background |
| TextBoxHoverBackgroundBrush | Fluent.Ribbon.Brushes.TextBox.MouseOver.Background |
| TextBoxHoverBorderBrush | Fluent.Ribbon.Brushes.TextBox.MouseOver.BorderBrush |
| TextBoxDisabledBackgroundBrush | Fluent.Ribbon.Brushes.TextBox.Disabled.Background |
| TextBoxDisabledBorderBrush | Fluent.Ribbon.Brushes.TextBox.Disabled.BorderBrush |
| RibbonSeparatorBrush | Fluent.Ribbon.Brushes.GroupSeparator.Background |
| GroupSeparatorBrush | Fluent.Ribbon.Brushes.GroupSeparator.Background |
| CloseButtonHoverBackgroundBrush | Fluent.Ribbon.Brushes.WindowCommands.CloseButton.MouseOver.Background |
| CloseButtonPressedBackgroundBrush| Fluent.Ribbon.Brushes.WindowCommands.CloseButton.Pressed.Background |
| MenuItemBackground | Fluent.Ribbon.Brushes.MenuItem.Background |
| MenuItemCheckBoxBackgroundBrush | Fluent.Ribbon.Brushes.ApplicationMenuItem.CheckBox.Background |
| MenuItemCheckBoxBorderBrush | Fluent.Ribbon.Brushes.ApplicationMenuItem.CheckBox.BorderBrush |
| RibbonThemeColorBrush | Fluent.Ribbon.Brushes.AccentBaseColorBrush |
| TransparentBrush | --- |
| BackstageFontBrush | Fluent.Ribbon.Brushes.IdealForegroundColorBrush |
| TabItemFontBrush | Fluent.Ribbon.Brushes.LabelTextBrush |
| Fluent.Ribbon.Brushes.LabelTextBrush | Fluent.Ribbon.Brushes.LabelTextBrush |
| GroupHoverBrush | Fluent.Ribbon.Brushes.RibbonGroupBox.Collapsed.MouseOver.Background GroupHoverBrush |
| GroupHighlightBrush | Fluent.Ribbon.Brushes.RibbonGroupBox.DropDownOpen.Background |
| GroupBoxFontBrush | Fluent.Ribbon.Brushes.RibbonGroupBox.Header.Foreground |
| ActiveTabBackgroundBrush | Fluent.Ribbon.Brushes.RibbonTabItem.Active.Background |
| TabItemSelectedFontBrush | Fluent.Ribbon.Brushes.RibbonTabItem.Selected.Foreground |
| RibbonBackgoundBrush | Fluent.Ribbon.Brushes.Ribbon.Background |
| RibbonTopBorderBrush | Fluent.Ribbon.Brushes.RibbonTabItem.BorderBrush & Fluent.Ribbon.Brushes.ColorGallery.Item.BorderBrush |
| ScrollButtonDefaultBorderBrush | Fluent.Ribbon.Brushes.ScrollButton.Default.BorderBrush |
| ScrollButtonDefaultBackgroundBrush | Fluent.Ribbon.Brushes.ScrollButton.Default.Background |
| ScrollButtonHoverBorderBrush | Fluent.Ribbon.Brushes.ScrollButton.Hover.BorderBrush |
| ScrollButtonHoverBackgroundBrush | Fluent.Ribbon.Brushes.ScrollButton.Hover.Background |
| ScrollButtonPressedBorderBrush | Fluent.Ribbon.Brushes.ScrollButton.Pressed.BorderBrush |
| ScrollButtonPressedBackgroundBrush | Fluent.Ribbon.Brushes.ScrollButton.Pressed.Background |
| ScrollBackgroundBrush | Fluent.Ribbon.Brushes.ScrollBar.Background |
| ScrollVerticalBackgroundBrush | Fluent.Ribbon.Brushes.ScrollBar.Background |
| ScrollThumbDefaultBorderBrush | Fluent.Ribbon.Brushes.ScrollThumb.Default.BorderBrush |
| ScrollThumbDefaultBackgroundBrush | Fluent.Ribbon.Brushes.ScrollThumb.Default.Background |
| ScrollThumbHoverBorderBrush | Fluent.Ribbon.Brushes.ScrollThumb.Hover.BorderBrush |
| ScrollThumbHoverBackgroundBrush | Fluent.Ribbon.Brushes.ScrollThumb.Hover.Background |
| ScrollThumbPressedBorderBrush | Fluent.Ribbon.Brushes.ScrollThumb.Pressed.BorderBrush |
| ScrollThumbPressedBackgroundBrush | Fluent.Ribbon.Brushes.ScrollThumb.Pressed.Background |
| ScrollViewerButtonBorderBrush | Fluent.Ribbon.Brushes.ScrollViewer.Button.BorderBrush |
| ScrollViewerButtonBackgroundBrush | Fluent.Ribbon.Brushes.ScrollViewer.Button.BackgroundBrush |
| local color | Fluent.Ribbon.Brushes.ScrollViewer.Menu.RepeatButton.Fill |
|  |  |

  - The following default values changed:

|Name/Location|Old|New|
|---|---|---|
| Button.BorderThickness | 0 | 1 |
| ContentGapHeight | 5 | 1 |

  - The following styles got removed/renamed:

|Old|New|
|---|---|
| NonEditableComboBoxItemStyle | is now the default style |
| EditableComboBoxItemStyle | --- |
</p></details>

**Comment by RickStrahl** [comment]
I'm looking at this but I don't actually see the actual markdown syntax proposed for this?

Maybe the easiest way to do this is with a Code Snippet:

![image](https://user-images.githubusercontent.com/1374013/27155118-83f7566a-510c-11e7-9a35-a5e157527490.png)

You can just type `summarydetails` (or whatever *Expansion String* value you give it) to expand that text and put the cursor in between the `<summary>` block. You can also assign an optional hotkey.

You'll need to add the `Snippets: Scripted Text Expansions` addin for this to work.

**Comment by RickStrahl** [comment]
So I took a look at this today and it turns out that this will be a bit more complicated than I thought. The main issue is that text content in `<details>` is inside of an HTML block which means it won't be parsed by the Markdown Parser by default. While I can use `<script>` and CSS to manipulate the area to show and hide and even moving the elements around, there's no way to make this work purely on the client side unfortunately. This has to be handled in the server Markdown Rendering somehow to force the markdown inside of the HTML to render.

Markdig supports a ton of GFM but it looks like this is not one of them. Implementing a custom parser is the only way this will work. I don't have time to look at this at the moment, but if somebody wants to take a look at this as a Markdig extension that would be awesome. 

In fact this would make a good ER to[ Markdig](https://github.com/lunet-io/markdig/issues).

**Comment by RickStrahl** [comment]
Closing since there's been no movement on this. Ideally this is something that would be handled by the Markdown parser itself (ie. Markdig) rather than some custom hacks with script code.
