### ISSUE TITLE
Cut, copy, paste commands should be on the context menu

### ISSUE THREAD

**Issue by Xansky** [RickStrahl/MarkdownMonster#207]
When editing text, cut copy and paste operations should be on the context menu when I right-click on selected text within a document.

**Comment by RickStrahl** [comment]
Unfortunately I can't control that context menu - it's not accessible through the editor interface. It's either take it completely away (ie. no right click menu at all other than for spell checking).

Ultimately what's needed as a custom context menu, but it's actually quite difficult to get proper mouse position info over the editor (ACE Editor).

It's not a high priority item, but we'll leave it here to look at in case somebody wants to tackle that.

**Comment by RickStrahl** [comment]
Added in 1.6 along with other context menu improvements...

**Comment by Xansky** [comment]
Yes!
