### ISSUE TITLE
Close document should be on File menu

### ISSUE THREAD

**Issue by Xansky** [RickStrahl/MarkdownMonster#208]
The **Close document** and **Close all documents** commands should be on the **File** menu and not the **View** menu. This is how Close commands are implemented in other Windows apps.

**Comment by RickStrahl** [comment]
Well it depends. Often it's on a Window menu that shows open documents. In MM the Views menu serves both View and Windows or Documents. The View menu has bloated a lot recently so it might make sense to move it somewhere else, but not sure if the file menu is the best choice.

**Comment by RickStrahl** [comment]
Moved to File menu. Thank you.

**Comment by Xansky** [comment]
Thanks!
