### ISSUE TITLE
Current document tab should be the lighter color

### ISSUE THREAD

**Issue by Xansky** [RickStrahl/MarkdownMonster#209]
With multiple documents open, the currently active document should have the lighter colored tab and the inactive documents should have darker tabs. It's currently _VERY_ confusing since it works the opposite of other multi-tabbed document apps.

**Comment by RickStrahl** [comment]
FWIW, this isn't the first comment on this request, but...

It is a dark theme :smile:... The dark theme tab styling is based off of Sublime's tabs:

![image](https://user-images.githubusercontent.com/1374013/27204220-b67c78cc-51de-11e7-823d-03f34d6acc71.png)

and MM already has a little more contrast in the selected tab and low lights the other's text. 

If you want different contrast maybe the light theme works better for you:

* [Markdown Monster Theme Support](http://markdownmonster.west-wind.com/docs/_4rg0mw5c2.htm#ApplicationTheme)

**Comment by RickStrahl** [comment]
Made a couple more minor tweaks including making the selected tab semi-bold which makes it stand out a little better:

![image](https://user-images.githubusercontent.com/1374013/27205190-3706f01c-51e4-11e7-9cc0-8a75d4ed8a94.png)
