### ISSUE TITLE
Add a button to toggle word wrap

### ISSUE THREAD

**Issue by Ackara** [RickStrahl/MarkdownMonster#212]
Can we get a button and a keyboard shortcut to toggle word wrap? please.

**Comment by RickStrahl** [comment]
Curious: What's the use case? Do you really ever want Markdown to be rendered without Word Wrapping?

There's an option in Settings, but it's global currently.
```json
 "EditorWrapText": false
```

**Comment by Ackara** [comment]
When I have a long urls in the doc (typically for badge images) its hard to see where I'm at in the doc when the live preview is active. In other editors I like to toggle the word wrap so I can visually track where I'm at in the doc in comparison with the preview. The word wrap will often offset the text and the preview by several lines.

And a global toggle is fine.

**Comment by RickStrahl** [comment]
Ok, so I've added both Word Wrap and Line Numbers to the View menu as toggle switches:

![image](https://user-images.githubusercontent.com/1374013/27565759-1e9fcdf0-5a95-11e7-8080-a24e6210f4a8.png)

The toggle is global and basically sets the configuration setting but you can hot key it with **alt-v-w** via View menu shortcut.

**Comment by Ackara** [comment]
Thank you for making the change I really appreciate it. It works as excepted.
