### ISSUE TITLE
no more GUI for settings?

### ISSUE THREAD

**Issue by brandonh-msft** [RickStrahl/MarkdownMonster#214]
I'm trying to add a new weblog to my MM installation and when I click "Weblog publishing configuration" (or even Tools | Settings) I'm taken to a JSON file that defines it... the GUI is gone. Is this expected? What happened? Do we have documentation on how to set up additional weblogs within the JSON definition somewhere?

Thanks!

**Comment by RickStrahl** [comment]
It's still there, just not from the Settings link. Just open the main Blog window and go to the Web Logs tab.
