### ISSUE TITLE
Images not uploading for WordPress Blog

### ISSUE THREAD

**Issue by brandonh-msft** [RickStrahl/MarkdownMonster#215]
Recently wrote a rather lengthy post including many screenshots. For each screenshot, I used Windows' built-in screen capture to capture to the clipboard, then MM's _awesome_ functionality to simply paste that in to my post. During the prompt to save the image, I chose the directory where the post resides and it inserted markdown like `![](path_to_image.png)` which I thought would work well.

When I published the blog (Wordpress endpoint), however, it only published the text. No images were uploaded and none appeared in my post.

Am I doing something wrong? What's the right way to do this?

Thanks!

**Comment by RickStrahl** [comment]
That should just work. As long as the images are local (ie. live in a relative path that MM can find) it should push those images up to the Weblog.

Let me double check uploads for WordPress - I know it works with Meta WebLog API as I use that all the time for my blogs, but I figure I would have had other people report this if it didn't work.

There were some changes a while back in the way images are uploaded to Wordpress to properly represent the image ids. I wonder if that might have an effect on whatever provider implementation of the Wordpress API that you're using.

**Comment by RickStrahl** [comment]
Ok, so just checked this out by posting my most recent blog post to my WordPress test site:

https://rickstrahl.wordpress.com/2017/07/14/javascript-debugging-in-a-web-browser-control-with-visual-studio/

And no problem sending up local images. If it's not working there must be some issue with the Wordpress implementation that you are posting too perhaps?

Can you try running Fiddler to see what gets pushed up - you might be able to see an error message that might give more insight in what's going wrong with the media uploads.

**Comment by brandonh-msft** [comment]
👍
The blog I was hitting was the MSDN one. I've since moved to using the Azure Blob Storage extension but if I get a wild hair I'll give it another shot w/ Fiddler wired up and let you know.

**Comment by RickStrahl** [comment]
I know a number of people are using the MSDN blogs, so I would think we'd have more complaints but i haven't heard from anybody else yet. 

Hard to debug though since this likely is an implementation specific issue.

**Comment by MattHoneycutt** [comment]
I was able to reproduce this (or at least something similar) while posting to Wordpress.  It seems to be caused by spaces in the image filenames.  I usually escape spaces with hyphens myself when I'm embedding images in posts, but I forgot to do that in a post today, and the image silently failed to upload.

**Comment by RickStrahl** [comment]
I’ll taje another look but it’ll be next week.
