### ISSUE TITLE
Azure Blob Storage upload doesn't escape resulting URLs

### ISSUE THREAD

**Issue by brandonh-msft** [RickStrahl/MarkdownMonster#216]
If you upload an image that has spaces in it to blob storage, the resulting URL also has spaces in it. However, the `![]()` syntax of Markdown doesn't like this. Rather, you must escape the spaces with the usual `%20`.

I imagine this follows for all non alphanumeric characters...

**Comment by RickStrahl** [comment]
Added code to add space encoding (%20) to the Urls generated.

![image](https://user-images.githubusercontent.com/1374013/28229387-73892568-6897-11e7-986b-a011752b792d.png)

As an aside though, if you're looking for clean URLs, spaces are probably not a good idea in the first place - use dashes or camelCase instead - it sure will look nicer than %20 in the URL 😃
