### ISSUE TITLE
Open document at previous position

### ISSUE THREAD

**Issue by gsej** [RickStrahl/MarkdownMonster#218]
When a document has been opened after previously being worked on, it should open at the last scroll position.

A pdf reader I often use (sumatrapdf) does this simply by storing the full path to the file against a line number. 

It should probably be made possible to turn off the behaviour for people who find it annoying.

**Comment by RickStrahl** [comment]
That behavior should already be there as long as you have MM re-open open documents (by default last 3). MM stores the last position of docs that are re-opened. 

You can control how many open documents are remembered when you reopen with `"RememberLastDocumentsLength": 3,`.

The `OpenDocuments list in the config file should hold the `LastEditorLineNumber`.
