### ISSUE TITLE
Suggestion: Mermaid support for diagrams

### ISSUE THREAD

**Issue by onovotny** [RickStrahl/MarkdownMonster#22]
It'd be great to have support for Mermaid code blocks. http://knsv.github.io/mermaid/

If you haven't seen it before, Mermaid uses a markdown-compatible syntax for generating complex diagrams and is great for sequence diagrams, decision trees and more.

Even better would be if MM had an option to generate a png for use when exporting MD to other places that don't support Mermaid (like wordpress).

**Comment by RickStrahl** [comment]
Oh wow, that's pretty cool - and something I never heard of.

But I don't think that's something that's going to be easy to fit into the main editing flow. However, it could be added as a custom file type perhaps with custom parsing managed as a add-in. 

I'm going to close this for now, as this won't be addressed directly but maybe you can think about how it might be integrated as an add-in.

**Comment by onovotny** [comment]
Here's a thought -- given that it's just JS and you're using a web browser control, can you package the JS and simply include the scripts in the html you're feeding the browser? Let the browser do the work.

Then the rendering/export question can be addressed separately.
