### ISSUE TITLE
System.IO Exception when OpenInPresentationMode set to True

### ISSUE THREAD

**Issue by ericnsmith** [RickStrahl/MarkdownMonster#220]
## Steps to reproduce:
* Set OpenInPresentationMode: true
* Open a markdown doc in MarkdownMonster
* Close MarkdownMonster
* Open MarkdownMonster which should open the previously opened doc in presentation mode
* Hit F11 key to toggle presentation mode
* System.IO.IOException: The process cannot access the file '...\AppData\Local\Temp\_MarkdownMonster_Preview.html' because it is being used by another process.

## Work arounds:
* Set OpenInPresentationMode: false, or;
* Close all docs prior to exiting MarkdownMonster

**Comment by RickStrahl** [comment]
Thanks Eric I can duplicate. Might take me a bit to fix this as I'm on vacation for a couple of weeks - i'll get that taken care of as soon as a I get somewhere with some time.

Looks like the issue is switching out of presentation mode - and only when Presentation Mode is set.

**Comment by RickStrahl** [comment]
Added a try/catch guard clause around the render file deletion. There's some old code that deleted render file when each tab was closed, which dates back to previous versions where the render file was created in the same folder as the editor document. That caused the repeated deletions that could overlap and cause the issue. Removed the tab deletions which should speed up shutdown slightly as well.

Thanks.

25a78bdbddc66384e9934055b1792f78e4dd6462
