### ISSUE TITLE
Markua Support

### ISSUE THREAD

**Issue by PaulHMason** [RickStrahl/MarkdownMonster#221]
Has any thought been given to support Markua, which is the LeanPub extensions to make markdown more book friendly?  I haven't looked at the MM addin support, but I presume the best approach would be to write a custom markdown parser?

https://leanpub.com/markua/read

Another useful feature would be to be able to concatenate a bunch of separate markdown files into a single html or pdf file on export based on a "toc" type configuration markdown file. I suppose this could also be done with a custom markdown parser and import tag that will pull the external file content into the input stream before processing.

**Comment by RickStrahl** [comment]
It looks like Markua is mostly just plain Markdown using the standard Markdown format plus a couple of additional tags. To make this work you'd probably need to create a custom Markdown Parser (which [can be added as an Addin](http://markdownmonster.west-wind.com/docs/_4ut0j7xoe.htm)) that can handle the additional tags by extending the existing one.

What are you looking to do - just support he syntax, or handle the packaging process as well? This is another thing that a addin can help integrate with.

I have been looking at various book publishing related tools like Pandocs moby support, but it's all a bit fuzzy to me - those things have tons of steps that need to be automated which is a great use case for an addin, but it takes someone with more intimate knowledge of how these tools do work.

**Comment by RickStrahl** [comment]
Since there's no further discussion or any takers that might want to build an addin I'm closing this issue.
