### ISSUE TITLE
Adding new items on existing ordered list

### ISSUE THREAD

**Issue by gomnet** [RickStrahl/MarkdownMonster#222]
Hi Rick,

After working with my new project under .NET Core 2.0, I tried to create Readme.md file with your tool and I figured out when new items are added into ordered list (with numbers), the numbering of items are not refreshed, i.e if I include in a list of 10 items, a new one with position 6, all item numbers below are not refreshed.

![image](https://user-images.githubusercontent.com/25245116/29492811-57779e96-8588-11e7-8556-18055bc1f1d4.png)

Thanks for your time.

Best regards,
David.

**Comment by RickStrahl** [comment]
No :-) 

But the rendered output doesn't care what the numbering is. You can write all items with 1. and the rendered output will be correct. I would recommend that approach.

Not sure if we want to get into re-arranging already typed text for users...

**Comment by gomnet** [comment]
Thx Rick for the reply, this behaviour was odd from my point of view, and indeed you are right about rendered result which is correct ;)
