### ISSUE TITLE
Repopulate the markdown parser and themes drop-down boxes upon addin installation

### ISSUE THREAD

**Issue by DVaughan** [RickStrahl/MarkdownMonster#224]
Presently, MM doesn't repopulate the markdown parser and themes drop-down boxes when a new addin is installed. It means that MM must be restarted before new items are displayed.

**Comment by RickStrahl** [comment]
Yes, that's because parsers (and addins) are initially loaded when MM starts and that code is not called again once the addin runs. 

Should be easy enough to fix though - just have to explicitly call any of the registration APIs after a non-restart installation.

**Comment by RickStrahl** [comment]
Fixed:
83bd8453d6333677c03aff9803ab0152c5c34596

Note: This will only work on first load of an addin - updating an addin will require a restart to load the new addin.
