### ISSUE TITLE
Why are links in exported PDF not links?

### ISSUE THREAD

**Issue by HamedFathi** [RickStrahl/MarkdownMonster#227]
I created some links like 

`[.NET Core SDK](https://www.microsoft.com/net/download/core)`

in my markdown file but when I export it to pdf All links are text with blue color !

I think it would be better if links were clickable in exported pdf not only blue string !
![untitled](https://user-images.githubusercontent.com/8418700/29818396-6f79ae1c-8cd1-11e7-964f-fe4e83b38ebd.png)

**Comment by RickStrahl** [comment]
Not sure why that's the case - it works for me. Are you sure your viewer is not resfusing you to navigate links?

For example, I use Nitro and it warns me on links that it's going to an external location and prompts me before I can navigate. Other viewers (or policy) may prevent you from navigating out of a document.

The links are definitely in the document however.

**Comment by HamedFathi** [comment]
@RickStrahl 

Yes, you right I changed my pdf viewer. it works perfectly.

Thanks
