### ISSUE TITLE
Enable support for additional Markdig extensions

### ISSUE THREAD

**Issue by kenmuse** [RickStrahl/MarkdownMonster#230]
MarkDig has several other options available which are incredibly helpful or useful (for example, UseGenericAttributes). At the moment, the only way to enable those extensions -- or new ones -- is to create a custom plugin.

I would propose one of the two approaches:
 - Add support for the method ```public static MarkdownPipelineBuilder Configure(this MarkdownPipelineBuilder pipeline, string extensions)``` to the configuration. A single configuration value, MarkdigExtensions could be added. This would be applied after the other existing configuration settings and would allow a user to enable any of the available built-in extensions by name, separated by +. See the class [MarkdownExtensions,line 481](https://github.com/lunet-io/markdig/blob/master/src/Markdig/MarkdownExtensions.cs#L481). Optionally, the default value could be the extensions that are currently enabled by the code but not configurable (```emphasisextras+pipetables+gridtables+footers+footnotes+citations```).
 - Add each of the additional settings as options which can be enabled in configuration. This is the most intuitive for a user, but requires ongoing maintenance.

This would not automatically support custom local extensions until Markdig changes the method to support registration of custom extensions, but it would enable the use of any of the built-in extensions.

**Comment by RickStrahl** [comment]
Ugh - I wish Markdig wouldn't use + for those values - that's really ugly. Commas would be much more consistent with what other config settings do. Can we change that + to , and just do a string replace on the +?

**Comment by kenmuse** [comment]
I don't see a problem with comma-separated values. Seems generally more intuitive. Seems a string replace in MarkdownParserMarkDig.cs would be an easy enough approach. Alternatively, could implement it as a JSON string array configuration. We could join those with a "+" before passing the string to Markdig.

**Comment by RickStrahl** [comment]
I think comma delimited list is better in this case. Arrays tend to be a bit verbose and generally only want to use them for object arrays or dictionaries. Single vals work well as delimited list.

**Comment by RickStrahl** [comment]
Updated to comma delimited list:
a19ea88b1385b85b16070a84d287229a693093b5

**Comment by kenmuse** [comment]
You beat me to it! :-)
