### ISSUE TITLE
The GitHub Gist integration plugin fails to install

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#233]
The GitHub Gist integration plugin fails to install

**Comment by RickStrahl** [comment]
Saw that... It's fixed in 1.6.0 - not sure what changed though. I believe there was a fix that didn't make it into 1.5.12 related to a new addin interface method. Give it another try in 1.6.0.

**Comment by ArthurZ** [comment]
Confirming as can install in 1.6.0
Thanks for the fix.
