### ISSUE TITLE
Multiple windows

### ISSUE THREAD

**Issue by jmclain** [RickStrahl/MarkdownMonster#234]
Markdown Moster 1.6

Double click on an .md file to open in mm, mm opens. Double click on the same .md file again and mm opens the file in a new window. There are now two window editing the same file. If that's how the app is suppose to function, okay, but both instances of mm also open copies of the files that were previously open when the user quit mm. I don't think that's the correct behavior, nor do I recall that being the behavior a month ago when I last used mm.

**Comment by RickStrahl** [comment]
Hmmm... the window behavior is determined by a configuration setting:

```json
 "UseSingleWindow": true,
```

SingleWindow meaning all documents open in tabs when opening from a shortcut or explorer. This is the default. If `false` each externally shell opened window gets a new separate desktop window.

I suspect that somehow that setting got set to `false`. If not report back and we'll look into why you might be seeing the odd behavior you describe.

**Comment by jmclain** [comment]
"UseSingleWindow" was set to false. I've never made changes to the config file so I don't know how that happened. In any case it now only opens a single window.

My mildly held opinion is that if "UseSingleWindow" is true that an instance should open with the file selected at launch time (double clicked, or otherwise selected), or with no files open if the user launched without the file.

Thanks

**Comment by RickStrahl** [comment]
@jmclain The behavior you describe is what `UseSingleWindow=true` is supposed to do. If you double click a file it should load the file in the single instance running and make it active. Likewise if no instance is open it'll open MM and show that file.

Now you may be referring to previously opened documents which are also loaded and open by default. If you don't want to remember previously open documents, set

```
  "RememberLastDocumentsLength": 0,
```

Once that's set when MM opens no documents will be remembered.

What do you see?

**Comment by jmclain** [comment]
I am referring to previously open documents.

I have no argument with what you are saying, mm works as you describe. However, I suggest that in the context of `UseSingleWindow=True` that mm should work as if `RememberLastDocumentsLength` is set to 0. Having the same document open in multiple editors is (at least for me) problematic. But, I suppose this is not much of an issue since folks will choose to use a single window, or not.

Thanks

**Comment by RickStrahl** [comment]
If you have `SingleWindow=true` how would you have multiple windows open? There may be some edge cases where MM was already open from before, but under normal usage there should only be a single window anywhere on the desktop.

**Comment by jmclain** [comment]
Sorry, I meant _**UseSingleWindow=False**_

 I suggest that in the context of UseSingleWindow=False that mm should work as if RememberLastDocumentsLength is set to 0. Having the same document open in multiple editors is (at least for me) problematic. But, I suppose this is not much of an issue since folks will choose to use a single window, or not.

**Comment by RickStrahl** [comment]
Hmmm... never thought about that but that makes sense. An additional check for UseSingleWindow when trying to restore windows should do it:

978c26d5ab1d6e3fb4b3a5c7bf8d4575abd6c7d2
