### ISSUE TITLE
Addin window almost invisible

### ISSUE THREAD

**Issue by jmclain** [RickStrahl/MarkdownMonster#235]
markdown monster 1.6

Addin opening on primary display with only a few pixels showing, remainder of window
offscreen. There are three active displays on the system. I don't think this is a bug
per se, part of the window is visible, but it did take me a number of relaunches before
I spotted the window. I don't know if it's mm or windows setting the addins opening
location, but it probably should be opened mid display if most of the window is off
screen.

**Comment by RickStrahl** [comment]
Which window are you referring to specifically? The Addin Manager?

I think that one I don't specify a specific Window location - I should probably pin that one to the owner window like most other windows.

**Comment by RickStrahl** [comment]
Fixed add in manager window location:
0bcca399cfddfb010262d9779b06355b37b69698
