### ISSUE TITLE
Markdown Parser Loading Broken

### ISSUE THREAD

**Issue by jmclain** [RickStrahl/MarkdownMonster#236]
markdown monster 1.6

Okay, so I'm trying to create a markdown parser addin, the idea is I have a macro processor and I'm going to pre-process the markdown and then pass it on to MarkDig. Problem is I can't get mm to call `GetMarkdownParser(bool usePragmaLines, bool force)` in my addin. Reason is when the main mm window is being initialized the combo box that holds the name of the available parsers gets a list of parsers from the parser factor, sets the selection to the only one available (MarkDig) and this updates `MarkdownParserName' with "MarkDig" which wipes out the name of my addin (whose name was loaded from the configuration file).

In addition I don't beleive the documentation mentions you need to set `MarkdownOptions.MarkdownParserName` to the id of the addin to use as an alternate markdown parser. Using this configuration method I don't see how you can have more than two parsers, MarkDig and a single alternate named in the configuration file.

I will look at the "old" method of adding a parser and see if that works.

Thanks!

**Comment by jmclain** [comment]
The "old" method of adding a parser works, however it selects the last item in `MarkdownParserNames` as the active one. Should probably programmatically select the default parser in code before the window displays,

**Comment by RickStrahl** [comment]
This should work. You might have to restart after adding the addin in order for it to show up in the parser drop down especially if the addin was already installed, but once you restart it should show up there and you can select it and it will remain set when you restart next time.

**Comment by jmclain** [comment]
Unfortunately that does not work because `GetParserNames()` will never locate an addin using the newer `GetMarkdownParser()` method because `GetParserNames()` calls the "old" version to determine of the method to discover addin parsers.

The workaround is to support the old `GetMarkdownParser()` method to allow `GetParserNames()` to identify the addon as a parser; mm will then call the new get parser method when it actually wants a "real" parser. I'd suggest adding a flag to IMarkdownMonsterAddin to indicate whether the addin provides a markdown parser.

**Comment by RickStrahl** [comment]
Thanks. There's a bug there in that the existing methods are not calling the newer GetParser() method. Looks like I didn't think this all the way through :-) The change came from an contributor and some fix up - I thought we had the backwards compatibility handled but missed the calls that actually get the parser instances.

Anyway, this should be fixed with this:
f66534205a3956f50a063c6210ac18b47c973837

**Comment by jmclain** [comment]
Verified, it now works as advertised!

**Comment by RickStrahl** [comment]
Thanks for checking! Aloha.
