### ISSUE TITLE
Close with unsaved documents

### ISSUE THREAD

**Issue by jmclain** [RickStrahl/MarkdownMonster#237]
When you close mm with unsaved documents mm prompts you to save them. Shouldn't it prompt you _before_ the main window is removed from the display? The problem I have with the current method (mm window is hidden) is that there is this small old style dialog sitting on the display where it might not be seen.

Also (I just noticed) that if mm is running on a secondary monitor the save dialog opens on the primary monitor.

**Comment by RickStrahl** [comment]
Hmmm... the reason I close the window prematurely is for perceived shutdown performance. Shutdown includes a couple of operations that check for updates and analytics that can be slow if there's no IP connection or the connection is slow etc. There are a few other timing related issues - like configuration needs to be saved before tabs are closed to capture open windows etc.

I'm going to take the `Hide()` code and move it back **after** this block of required code that needs to happen before saving off settings before tabs are closed and see how it goes. Testing just now I really see no slow down of any sort but then there's an IP connection that's fast and probably cached.

a30cf103d83d632a28676f8df0c2413caa1e0d69
