### ISSUE TITLE
Path to HTML preview file for "View in Web Browser" not escaped correctly

### ISSUE THREAD

**Issue by Structed** [RickStrahl/MarkdownMonster#239]
When having Markdown Monster installed in your User Profile (which is done by by default if installing via Chocolatey) and your user profile path happens to contain spaces, the path will not be correctly loaded when clicking "View in Web Browser".

Markdown Monster Version: 1.6.5
Install Method: Chocolatey
Browser Used: Google Chrome 61.0.3163.91 (Official Build) (64-bit) (cohort: 61_Win_91)
OS: Windows 10 Pro
Prerequisites: Have a user profile path with a space, e.g. `C:\User\Johannes Ebner\`

### Steps to Reproduce

1. Open & Edit Markdown file
2. Click `View` --> `View in Web Browser`
3. Browser opens two tabs, with the following content, given the user profile base path of `C:\User\Johannes Ebner\`, both will naturally show a 404 error:
    1. `file:///C:/Users/Johannes`
    2. `ebner/AppData/Local/Temp/_MarkdownMonster_Preview.html`

**Comment by RickStrahl** [comment]
Yup. Looks like this is the problem:

![image](https://user-images.githubusercontent.com/1374013/30781281-0418b9ba-a0b8-11e7-9554-e76fb0a9bcf7.png)
