### ISSUE TITLE
Introduction to markdown

### ISSUE THREAD

**Issue by jmclain** [RickStrahl/MarkdownMonster#240]
On your help page "An Introduction to Markdown", at the end in the section on code blocks you end with this:

> This no longer works.
> This is really what I want to see. I can no longer recognize what's happening in this document

I don't know if you meant to leave this text, or you were frustrated about something and just gave up and forgot to return to it!

**Comment by RickStrahl** [comment]
LOL... thanks. Making up random text for some test I suppose.

Thanks. Fixed.
