### ISSUE TITLE
Find TextBox is smaller

### ISSUE THREAD

**Issue by shaggygi** [RickStrahl/MarkdownMonster#242]
Noticed the Find (ctrl-f) TextBox is small and cutting off text in v1.6.5.  Updated from 1.5.5 today.

**Comment by RickStrahl** [comment]
Yeah it depends on your scale level in Windows and the zoom level in the document. 

Unfortunately this is an artifact of the underlying ACE editor and the way the searchbox is styled. I've experimented with a bunch of ways of customization for the CSS and the current way of a fixed size box with fixed size elements was the only way I could keep the searchbox rendering reasonably consistent over various sizes and zoom levels.

FWIW I don't see it cutting off text at any size. What are you Windows scale settings and font size setting in the editor?

If anybody is more savvy with CSS than me, maybe they can take a look at the CSS and play around with different settings. The relevant custom styling is in `editor.css` here:

https://github.com/RickStrahl/MarkdownMonster/blob/master/MarkdownMonster/Editor/editor.css#L70

**Comment by shaggygi** [comment]
Text setting in MM is...  "EditorFontSize": 18,

I attached an example of what I'm seeing.
![monstermarkdownfindtext](https://user-images.githubusercontent.com/2956825/30786943-7b684df2-a14c-11e7-9c10-6f9bdc953973.png)

**Comment by RickStrahl** [comment]
Hmmm that's odd. The Editor font size shouldn't be affecting the find dialog at all:

![image](https://user-images.githubusercontent.com/1374013/30830527-fb9ff2ac-a1df-11e7-81a3-b7fac73f32d6.png)

I've tried this at various Windows scaling levels too, so I wonder what's different in your configuration.

What you see used to be a problem with the original ACE rendering of the find box, but I changed the layout to be fixed size. 

What are your Windows scaling settings? Also can you check the date on `Editor\Editor.css`?

**Comment by shaggygi** [comment]
Windows scaling... do you mean text %?  If so I'm using 150%, but I've tried different values.

Where do I find the Editor\Editor.css?

**Comment by shaggygi** [comment]
I just tried uninstalling and reinstalling for 1.6.5 and see same results.

I found Editor.css file and date is 5/31/2017 12:11 PM.

**Comment by RickStrahl** [comment]
Not sure then. 

What OS are you on? If not Windows 10, then perhaps you need Internet Explorer 11 that might be making the difference. Windows 7-8.1 can use IE 11 but has to be explicitly upgraded.

https://www.microsoft.com/en-us/download/internet-explorer-11-for-windows-7-details.aspx
