### ISSUE TITLE
SnagIt 13 Screen Captures with Delay Failing

### ISSUE THREAD

**Issue by RickStrahl** [RickStrahl/MarkdownMonster#25]
When doing screen captures with SnagIt 13 MM fails to capture images when a capture timer is set. With a timer set the capture immediately aborts. Without a time the capture works sometimes, but not at others.

Checking with Techsmith they have confirmed this is a bug in the SnagIt13 COM server implementation that MM relies on. The COM Server behavior around delayed (and sometimes non-delayed) captures is broken and there is no workaround using SnagIt 13. Techsmith have an internal bug report for this now and plan on fixing this but according to info I got it doesn't sound like it will get fixed very soon as it's low priority to them.

For now the only workaround is to revert back to SnagIt 12 or use the less capable built in screen capture feature (ie. disable SnagIt captures).

Leaving this open as a reminder to check back with Techsmith.

**Comment by RickStrahl** [comment]
The latest release (dated October 25th, 2016) seems to have mostly fixed this problem, but it's still behaving a little wonky with what seems like long delays after the capture is complete...

**Comment by RickStrahl** [comment]
Workaround if you have access to SnagIt 12:

You can install SnagIt 13 and SnagIt12 side by side. 

If you want to capture with Markdown Monster you can first open SnagIt12 so that it runs on the desktop in the task tray. Make sure you see the Blue SnagIt icon, not the new orange one. Once SnagIt12 runs, the COM capture uses the active instance that's open, so you end up using SnagIt12 to do the capture. The editor that pops up however will be SnagIt13s.

Realize this is hacky, but it's a potential workaround for now, until Techsmith fixes this bug. They don't seem to be very responsive or motivated to fix this which is a shame.

**Comment by ArthurZ** [comment]
I think I have the same issue. And I have the latest SnagIt 13.0.3 installed. I start the screen capture, but if I decide not to take the screenshot then any subsequent time upon clicking the screenshot toolbar button I get MM minimizing itself for a fraction of a second and coming back without providing the possibility for a screenshot.
As an aside, I suspect MM comes with an editor for images pre-set to `C:\Program Files\paint.net\PaintDotNet.exe`. Which I do not have. In my view, it makes sense to point to the SnagIt's editor or at the very least the built into OS `%windir%\system32\mspaint.exe`.

**Comment by RickStrahl** [comment]
SnagIt 13 doesn't work - it's broken for the interop. You can either revert to SnagIt 12 which does work properly or turn off SnagIt screen captures in the Screen Capture config which then uses the built in capture which is a little less flexible. The configuration window shows this clearly:

![image](https://cloud.githubusercontent.com/assets/1374013/21561905/7d15e96a-ce17-11e6-9209-3484bf23f830.png)

You can change the editor in the `ScreenCaptureConfiguration.json`. I have mine set to the SnagIt 12 editor (the 13 Editor seems terribly slow). 

The reason it's not being set to the SnagIt Editor is that if you are using SnagIt the screen shot will automatically open in SnagIt's Editor. It's only if you're not using SnagIt that the external editor is used.

**Comment by JonDouglas** [comment]
I can confirm that Snagit 13 Editor with the January 20th 2017 update seems to resolve this issue. Prior to that, I had the November 6th? update and it would fail with all the descriptions above. However with this new update, it seems to work well.

One issue here however is that the path it creates when saving a file does not seem to render well. One must save a file first, and secondly it's easier if they are in the same directory (relative paths seem very iffy).

**Comment by RickStrahl** [comment]
Thanks for posting - I didn't see the update and tried and it seems to be working now which is great!

Can you clarify what you mean by *doesn't render well*?

I think what you mean is: If the file is Untitled and you save it creates the file link as a physical location. Once you save a file with a name, then you get the file to save in the location of the Markdown Document as you'd expect.

I'm not sure what workflow would make this better though - unless you have **some** file location to save to we can only guess. I suppose we could bring up a dialog and let you know or offer to save the document first, but that seems pretty intrusive and complex as well.

**Comment by RickStrahl** [comment]
So for me it still doesn't work :-( I still get the immediately aborting capture which sucks. are you sure you're running SnagIt 13 and not 12? SnagIt 12 certainly works for me but 13 still blunders.

**Comment by RickStrahl** [comment]
So I spent a bit more time experimenting with the January 20, 2017 release of SnagIt,  and the same issues as before still exist. @JonDouglas if it works for you it might be under very limited parameters of operation:

* SnagIt isn't already running
* Not using delayed capture

Without those I can get it to work although as soon as SnagIt is already running (via Task Manager check) it no longer works. Again all is fine in SnagIt12, but 13 is a  total Fail.

I have another followup support request up in the SnagIt Support area, but I'm not hopeful since while they have acknowledged and confirmed the bug, they have not bothered to fix it.

So still on holding pattern. In the meantime I've uninstalled SnagIt 13 and reverted to SnagIt 12 which works fine.

**Comment by ArthurZ** [comment]
Just my curiosity - do we want to stick to Snagit?
Why not to instead connect the built into Windows Snipping Tool? 
Or may be [although I'm sure] there is a dozen of other tools that can be packaged for free with MM.

**Comment by RickStrahl** [comment]
You don't have to use SnagIt. MM includes its own screen capture tool and that's what's there by default. But SnagIt has many, many more features than anything basic built into Windows or my own tool so it's very nice to have the integration. It's optional.

The simplest thing to do is use Windows capture PrintScreen (full desktop) and Alt-PrintScreen (Active Window) and then paste into a document. MM will prompt to save the clipboard image to file and embed it directly into the page. 

Windows Clipping tool can't be automated so that's a non starter.

**Comment by adammarks** [comment]
on Monday, I'll hook this up in the debugger on Snagit 13 and see what's going on.

**Comment by RickStrahl** [comment]
Thanks @adammarks- any progress on this would be much appreciated.

**Comment by JonDouglas** [comment]
I can't really replicate the failures now with the January 20th update. I do not believe it's under any specific parameters as I've also closed Snagit completely and it would start Snagit and then take the screenshot. I also set the delay to 0 seconds, so I'm not sure if it's my environment if I was previously failing as described with previous updates of Snagit13.

Without first saving the file, there is not a proper relative path for the image. One has to save before using the SnagIt addon or else it will not render the preview.

On this same note, the relative paths do not seem to play nicely given a project is in a different folder than the images. I was only able to get this functionality to work if I placed the images in the same directory of the file. I did not dig into this much, but it was behavior I noticed.

**Comment by RickStrahl** [comment]
Can you give an example of relative paths in your case? In fact if that's the problem please open a new issue. Can you also check the image dialog and see if it has what you might think of the same issue. I guess I'm not sure what you mean. 

Relative paths should work, but MM will fix up below document relative links (ie. ..\ based links and turn them into physical paths if you use the dialogs. You can most definitely fix them up though after they are embedded.

But again this warrants a separate issue and it might be easier to pin down and get a scenario in the image insertion dialog.

**Comment by adammarks** [comment]
I have verified what you already know and that is that it is related to the capture delay.  If I use a capture delay through the Snagit UI ( by creating a new profile that has a 5 second delay ),  it works fine, but  if I do the same from the COM API, everything falls apart and the code path taken isn't right.    

A workaround to use Snagit 13 with MM is to set the capture delay to 0, that is working well for me.   If that isn't working for you with the latest 13.1 release of Snagit, let me know the exact screen capture settings in MM that you are seeing trouble with.

I've spent some time reviewing the code involved in Snagit and I haven't pinned down a good way to fix this yet.  My working theory of what the problem is  :  When using the COM API in Snagit we take a lot of precaution to not overwrite existing settings in Snagit so that you could use the COM API and not have it mess up the Snagit UI and those extra precautions might be a bit too aggressive while doing a delayed capture.  

I'm going to think on it some tonight and will probably try a couple of things tomorrow or the next day.

**Comment by RickStrahl** [comment]
Hi Adam. Many thanks for checking this out. I for one would really love for SnagIt 13 to work, just for my own personal use as I live on SnagIt :-)

For me working with Capture Delay 0 I see it sometimes work sometimes not. The determining factor seems to be whether SnagIt is already running (when the icon is on the toolbar) so there's seems to a some other issue related to how the COM server attaches to an existing running instance of SnagIt.

IAC, I appreciate you or anybody else on your team taking a look at this. 

Not to be a brat about this, but any reason why this didn't get to you before me getting obnoxious about it on Twitter :-) ? I reported and nagged Nate about this on three separate occasions since September and it sounds like it was never even looked at other than to confirm that there was a problem?

**Comment by adammarks** [comment]
We did have had at least 1 other dev look at this issue before, back in September.  After spending a few solid hours on it today I can see what probably happened was since this wasn't going to be a quick fix at that time, we probably made a call then to delay fixing it so we could either fix other issues or implement new features.  

I'm spending more time on this now because I'm interested in keeping MM's application of Snagit's COM interface working since it's the only open source application that uses it( that I know of ).   The first time I was aware that this problem was with the COM API in relation to MM was seeing your tweet this weekend. So thank you for tweeting your frustrations and sorry we haven't given this much attention.

**Comment by RickStrahl** [comment]
Actually I have integrated SnagIt in several tools and utilities for a **long** time.

Live Writer Addin:
https://github.com/RickStrahl/Live-Writer-SnagIt-Screen-Capture-Plugin

(which I don't care much about anymore because I use MM for that now :-)

Also West Wind Html Help Builder:
https://helpbuilder.west-wind.com/

All of those are also broken :-)

It's a killer feature - surprised not more applications integrate with it.

**Comment by adammarks** [comment]
2 more good examples to show how the Snagit COM API can be used by external applications successfully!  

Ok,  I have found a decent fix to the problem.  When COM api is used we were constantly refreshing/resetting capture related settings causing Snagit to forget it was even doing a capture while performing a delay capture.   I changed this slightly so that rather than constantly refreshing/resetting these settings, we keep them alive until the whole COM API initiated capture occurs.

It should be a safe fix,  I need to do more testing and get it reviewed and tested and hopefully we can get it into the next maintenance release that goes out.

There is still the other problem outstanding that you mentioned where if Snagit isn't started, the COM api doesn't work.  I haven't looked into that one.

**Comment by RickStrahl** [comment]
That sounds great Adam, thanks for checking this out. I suppose it should be relatively easy to check on since this did all work in SnagIt 12 :-) The COM code for re-attaching (GetObject()) to an existing SnagIt instance's gotta be similar between these versions.

Appreciate the feedback and if you could drop a line here or update the bug report that'd be awesome.

**Comment by RickStrahl** [comment]
@adammarks Looks like the latest release has fixed this problem. I need to do a little more testing but initial tests show that this now works. 

As a bonus it seems the COM capture works a heck of a lot faster now than it did with older versions. The delay that was there before seems to have disappeared.

Thanks for getting this looked at!

**Comment by RickStrahl** [comment]
For those of you lurking on this post, you can go here to directly download the latest versions:

https://www.techsmith.com/download/oldversions

**Comment by adammarks** [comment]
Great,  I can confirm that my fix went into 13.1.1 that was released on 2/28,  so happy that it is working better now.   Please let me know directly if you see any other issues with the COM API that are as serious as this one was.

**Comment by RickStrahl** [comment]
There

**Comment by RickStrahl** [comment]
@adammarks Just a heads up. For the most part the COM component works as expected. I do still occasionally see situations where the COM object will do a count down, and then just exit rather than do the capture. I haven't been able to reliably repo it though, but in all cases it seems to be related to the the screen capture window being active on the desktop. Again not always, and rarely repeatable. 

It would appear there's some path through the COM capture that fails to aquire an already running instance in some scenarios.

It's not a huge issue, but something to consider. I'll update if I can find a more reliable repo scenario.

Again, thanks and I appreciate the work that went into getting this issue resolved to this point.

**Comment by adammarks** [comment]
ok, cool, I'll take a look at this soon.   In the code, the countdown is separate from the capture so there could still be a timing issue in there.   Does the countdown time make a difference?

**Comment by RickStrahl** [comment]
I'm seeing this a lot more frequently lately. Once it goes off I can't seem to get the COM object to work again until I reboot. This includes restarting my host application (MM) and shutting down all Snagit instances explicitly in Process Explorer.

What's frustrating about this is that it's so inconsistent. Sometimes I works for a long time - capturing many images without fail. Other times 1 or 2 captures in it fails and then stays bonked. :-(
