### ISSUE TITLE
Markdown Moster Solution does not build correctly

### ISSUE THREAD

**Issue by jmclain** [RickStrahl/MarkdownMonster#253]
I mentioned in my last pull request that I was unable to successfully compile the full Markdown Monster solution which is why I removed the web project. My bad. I should just have left it in. Additionally the two addins would not compile. Here is what I discovered.

In the latest Markdown Monster on Github the Screen Capture and Weblog Addin reference Westwind.Utilities but they are not listed in there respective packages.config file; so they do not restore and we have compilation errors. You probably reference the library locally. The utilities are referenced correctly by Markdown Monster.

I also get an error for the Website project when the solution builds.

```
"Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, 
Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.3.0, Culture=neutral, 
PublicKeyToken=31bf3856ad364e35" could not be located.	
```

Don't know what this error is. I have the ASP.NET bits installed but I don't use it.

thanks,

Joe McLain

**Comment by RickStrahl** [comment]
I updated project and fixed the references in the various projects. Also updated the CodeDOm provider to the latest package version which should help with the Web Project loading. It's a Web site project so this should work with a minimal Web package install in VS.

**Comment by jmclain** [comment]
On a first build everything builds without errors. Build a second time and no issues with Markdown Monster and the addins; however, I get this error for the website:

```
Severity Code Description Project File Line Suppression State Error The CodeDom provider 
type "Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, 
Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.7.0, Culture=neutral, 
PublicKeyToken=31bf3856ad364e35" could not be located. 
D:\Work\2017 Forward\Markdown Monster Addins\temp\MarkdownMonster\MarkdownMonsterWeb\web.config	58
```
Don't know what's going on there.

thanks,

Joe McLain

**Comment by RickStrahl** [comment]
That path looks funky - is that where things should be? The extra temp folder?

**Comment by jmclain** [comment]
That's where I put a clean download of mm, did not want to mess up my modified version which is at:

```
D:\Work\2017 Forward\Markdown Monster Addins\MarkdownMonster
```

Since you don't see the web project error I'm going to assume I'm missing something on my machine, and close this issue!

Thanks,

Joe McLain
