### ISSUE TITLE
Changes to MarkdownParserMarkdig.cs

### ISSUE THREAD

**Issue by jmclain** [RickStrahl/MarkdownMonster#254]
In reference to [my last pull request](https://github.com/RickStrahl/MarkdownMonster/pull/251) and the markdig host class, rather than build another pr I've attached the markdown parser hosting class to this issue. If you want the whole pull request just let me know.

[MarkdownParserMarkDig_cs.zip](https://github.com/RickStrahl/MarkdownMonster/files/1383688/MarkdownParserMarkDig_cs.zip)

thanks,

Joe McLain

**Comment by RickStrahl** [comment]
Added a813c6ff0f2c43648eb993b8a17ccf40145b5231
