### ISSUE TITLE
Spec says that editPost should return a boolean but MM doesn't like it.

### ISSUE THREAD

**Issue by shawnwildermuth** [RickStrahl/MarkdownMonster#255]
Maybe not a bug but a difference in the spec (vs. what other Metaweblog providers do), but my .NET Core middleware for Metaweblog returns a boolean for success or failure of an update and MM doesn't like it:

![image](https://user-images.githubusercontent.com/568272/31578477-051cf0b8-b0f0-11e7-8b5a-a4afe4186aef.png)

**Comment by RickStrahl** [comment]
Hi Shawn,

The api is set up to work with boolean values. It should work with `true` as a result - my blog returns true and it works as do WordPress blogs (which technically isn't MetaWeblog but the schemas overlap).

The interface definitely works on boolean:

![image](https://user-images.githubusercontent.com/1374013/31588935-c1e17d64-b194-11e7-9bb6-79803ed668ca.png)

Can you check your response and make sure that your result is properly turned into an RPC boolean?

A valid response that works should look something like this:

```xml
<?xml version="1.0"?>
<methodResponse>
  <params>
    <param>
      <value>
        <boolean>1</boolean>
      </value>
    </param>
  </params>
</methodResponse>
```

You can run with Fiddler while updating a post and see what goes over the wire to see what might be happening that fails to produce a valid bool result.

**Comment by shawnwildermuth** [comment]
Ah, I'm returnign <boolean>True</boolean> I must have misread the spec.
