### ISSUE TITLE
PreviewMarkdown() called too early on tab change

### ISSUE THREAD

**Issue by jmclain** [RickStrahl/MarkdownMonster#256]
When the user changes tabs to select a different file the method shown below 
is executed. 

```csharp
    private void TabControl_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
      if (batchTabAction)
        return;

      var editor = GetActiveMarkdownEditor();
      if (editor == null)
        return;

      if (mmApp.Configuration.IsPreviewVisible)
        PreviewMarkdown();

      SetWindowTitle();

      foreach (var doc in Model.OpenDocuments)
        doc.IsActive = false;

      Model.ActiveDocument = editor.MarkdownDocument;
      Model.ActiveDocument.IsActive = true;

      AddRecentFile(Model.ActiveDocument?.Filename, noConfigWrite: true);

      AddinManager.Current.RaiseOnDocumentActivated(Model.ActiveDocument);

      Model.ActiveEditor.RestyleEditor();

      editor.WebBrowser.Focus();
      editor.SetEditorFocus();
    }
```
<p>&nbsp;</p>

`PreviewMarkdown()` is called before the `Model.ActiveDocument()` is changed or the `RaiseOnDocumentActivated()` is called. I have an addin that modifies the markdown before being passed on to markdig and it keeps track of some internal information by tracking the current document. This won't work correctly because the new document is rendered before the active document is changed.

I suggest moving `PreviewMarkdown()` to after `RaiseOnDocumentActivated()`.

thanks,

Joe McLain

**Comment by RickStrahl** [comment]
Yeah that makes sense...

54572ac40d89dd2bbf83fb5aa280d11ccf643074
