### ISSUE TITLE
Current directory

### ISSUE THREAD

**Issue by jmclain** [RickStrahl/MarkdownMonster#259]
It's not my intent to be a PITA, but as I move through the mm source code there things I notice here and there that I think should be pointed out even though I'm sure you're aware of 99% of them.

Todays note from the field is that a lot of code is going to do wrong things if a plugins ever changes the current directory. I count 16 occurrences of
```
Path.Combine(Environment.CurrentDirectory, ...)
```
across 10 files.

Thanks for paying attention,

Joe McLain

**Comment by RickStrahl** [comment]
Hmmm... Ok. MM depends on the root path being in the install folder - I make no bones about this. We do track the original folder (added later as App.initialStartDirectory) and I could change that to point at that folder. But there are other things that heavily rely on the startup path, like finding templates and related resources that are accessed via relative paths.

If an addin changes the path the app is likely hosed anyway regardless of the Environment.CurrentDirectory. :-)
