### ISSUE TITLE
Markdown Monster dies

### ISSUE THREAD

**Issue by jmclain** [RickStrahl/MarkdownMonster#261]
Create a new edit window. Try to open in web browser.

```
[Window Title]
Markdown Monster

[Main Instruction]
Markdown Monster has stopped working

[Content]
A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available.

[Debug] [Close program]
```

**Comment by RickStrahl** [comment]
What are you doing to 'create a new Edit Window'? Ctrl-N/New Document?

If that's it, it seems to be working for me.

**Comment by jmclain** [comment]
Sorry, my bad. A null reference in my code somehow went unnoticed by the debugger, and me.

Thanks,

Joe McLain
