### ISSUE TITLE
OnDocumentActivated incorrectly documented

### ISSUE THREAD

**Issue by jmclain** [RickStrahl/MarkdownMonster#262]
```csharp
        /// <summary>
        /// Called whenever a new document is activated in the editor 
        /// (when tabs change). Note on startup if multiple documents
        /// are open this method is called for each document.
        /// </summary>
        /// <param name="doc"></param>
        public virtual void OnDocumentActivated(MarkdownDocument doc)
        {                                    
        }
```
` Note on startup if multiple documents are open this method is called for each document`

OnDocumentActivated()  is not called for any files on startup. Wish it was!

Thanks,

Joe McLain

**Comment by RickStrahl** [comment]
It shouldn't be called for all documents - it should be called for the active document though. Only as documents are actually accessed should this method be called.
