### ISSUE TITLE
Installer does not support unicode characters

### ISSUE THREAD

**Issue by savornicesei** [RickStrahl/MarkdownMonster#263]
Hello,

My computer is configured to use Romanian language and keyboard. During MarkdownMonster install, it does not show correctly the ș character so it displays 'Fi?iere program (x86) instead of  'Fișiere program (x86)'. It's not a critical issue; it's just annoying :)

![image](https://user-images.githubusercontent.com/917232/32214128-802ea98e-be26-11e7-9531-b4ab3a224074.png)

Thank you.

**Comment by savornicesei** [comment]
After looking into the MM installer: the InnoSetup 5 unicode variant must be used. http://www.jrsoftware.org/ishelp/index.php?topic=unicode

**Comment by RickStrahl** [comment]
Thanks for letting me know - I would have never noticed this one!

**Comment by RickStrahl** [comment]
Looks like simply switching to the Unicode installer for compilation fixes the problem. Next release will have this fixed.

Thanks for bringing this to my attention.

**Comment by savornicesei** [comment]
Great! I look forward to check the next-release installer!
