### ISSUE TITLE
Feature Request: Wrap words in Grave accent like quotes

### ISSUE THREAD

**Issue by Mehul** [RickStrahl/MarkdownMonster#264]
Is it possible to select a word and hit the Grave accent (`) and wrap the word in the grave accents please? Like how this works currently for quotes and double quotes.

**Comment by RickStrahl** [comment]
It's already on the menu and can be accessed with **ctrl-`**.

![image](https://user-images.githubusercontent.com/1374013/32724205-6f85741c-c814-11e7-8242-cf4afbc355a9.png)

**Comment by Mehul** [comment]
Awesome, thanks!
