### ISSUE TITLE
Feature request: Add hotkey for Insert Image

### ISSUE THREAD

**Issue by tbleken** [RickStrahl/MarkdownMonster#266]
The title says it all, I hope

**Comment by RickStrahl** [comment]
Not sure what you're asking for as this already supported.

* Alt-i to bring up the image dialog (alt-i)
* Paste an image from the clipboard (ctrl-v)
* Drag and drop images into the editor from Explorer
* Drag and drop images into the editor from the File Browser
* Use the integrated screen capture (SnagIt or built in)

What else do you need?

**Comment by tbleken** [comment]
Alt-I is not documented, so I didn't know about it. At least it's not in the list Editor Hotkeys in Help. It's not a part of the tooltip for the button either.

**Comment by RickStrahl** [comment]
All the menu items have tooltips with their corresponding hotkeys...

+++ Rick ---

**Comment by tbleken** [comment]
No, the Insert Image button doesn't have any hotkey reference with its tooltip. I just downloaded version 1.7.3.0, and checked. I also just checked Help at https://markdownmonster.west-wind.com/docs/_4rd0xjy44.htm, no reference to this key there.

BTW, I received an error during the update installation: 
![image](https://user-images.githubusercontent.com/3491804/32831250-070e8f28-c9f8-11e7-8da8-1ab403d831f5.png)

**Comment by RickStrahl** [comment]
This:

![image](https://user-images.githubusercontent.com/1374013/32859524-d79ede5a-c9f2-11e7-8565-93bda5fca4d6.png)

As to install error - not sure. Give this another try with 1.74 which is out now. Tried here and in two other locations and all works or better yet:

```
c:/> choco install MarkdownMonster
```

**Comment by tbleken** [comment]
I checked the error, and found that the problem is that the installer isn't allowed to write to my desktop folder because of added security. No deal, I don't use the desktop for any shortcuts.
