### ISSUE TITLE
Feature request: Show preview in a separate window

### ISSUE THREAD

**Issue by tbleken** [RickStrahl/MarkdownMonster#267]
I want an option to show the preview in a separate window, so that I can have it on a second monitor. So far I work around this by stretching the application over two monitors and move the divider so that it is at the edge of the left monitor. Far from perfect, but it works.

**Comment by RickStrahl** [comment]
Closing - same as #56.

It's a low priority item though - not likely to get addressed any time soon.

**Comment by RickStrahl** [comment]
This has been implemented in 1.7.8.

https://markdownmonster.west-wind.com/docs/_4ni0v22ad.htm#PreviewLocation
