### ISSUE TITLE
Right click commands in Folder Browser Window

### ISSUE THREAD

**Issue by jmclain** [RickStrahl/MarkdownMonster#268]
If the selected folder browser directory is empty then none of the right click folder browser commands work, e.g. New File.

thanks,

joe mclain

**Comment by RickStrahl** [comment]
Well if it's empty there's no location specified. What should happen in that case? You don't want to start assuming things - I think the folder needs to be there. Probably should disable options to do anything in the non-existant folder.

**Comment by jmclain** [comment]
I need to improve my communication skills.

A valid directory is selected but there are `no files in the directory.` I would think at least "new file" should function.
