### ISSUE TITLE
Selecting a new Folder Browser Directory

### ISSUE THREAD

**Issue by jmclain** [RickStrahl/MarkdownMonster#269]
When you click to select a new Folder Browser directory shouldn't the select directory dialog start in the current folder browser directory?

thanks,

joe mclain

**Comment by RickStrahl** [comment]
That seems to be working for me no matter where I select from:

![image](https://user-images.githubusercontent.com/1374013/33007839-85dbc742-cd74-11e7-825e-6eb63074d02a.png)

What are you doing exactly? Clicking the `...` to pick a new folder? The location icon will navigate to the current document's folder.

**Comment by jmclain** [comment]
I can no longer reproduce this, so I'll close it. Next time I will take a picture!

joe mclain
