### ISSUE TITLE
Fails to start as an unelevated user

### ISSUE THREAD

**Issue by ruusty** [RickStrahl/MarkdownMonster#27]
Install using chocolatey in an elevated administrator `choco install MarkdownMonster`
Fails to start, displays
![sshot-12](https://cloud.githubusercontent.com/assets/6316370/19414086/01055c84-938e-11e6-9b22-0f691ba90b0d.png)
then exits

**Comment by RickStrahl** [comment]
Can you do me a favor and reinstall 0.54 from http://markdownmonster.west-wind.com/download.aspx.

I've changed the logic for the sample file to open from temp folder and - handle the permissions issue more gracefully.

Thanks for reporting...

**Comment by RickStrahl** [comment]
Resolved with various fixes in v0.54/0.55.
