### ISSUE TITLE
Directory when opening terminal window

### ISSUE THREAD

**Issue by jmclain** [RickStrahl/MarkdownMonster#271]
When running the current release (download) version of mm the Open Terminal command the ends up in the Markdown Monster directory. However, a locally compiled debug version of the same code opens the terminal window in the current document's directory (where it should be). Also built a release version and it opens in the current document's directory.

I have no clue as to what's going on.

Thanks,

Joe McLain

**Comment by jmclain** [comment]
Just noticed that while it opened in the mm directory on the c: drive, the path on my d: drive where the markdown files were located was set to the correct directory.

**Comment by jmclain** [comment]
```
  "TerminalCommandArgs": "/k \"cd {0}\"",
```
Ok, so what is happening is the change directory on the command line is changing the directory on the drive where the markdown files are located, but the terminal window is opening on the drive where markdown monster is located. On my system the debug/release version of mm I'm compiling (as well as the markdown files) are on drive D so it works as expected. The downloaded version of mm is on C so that is where the terminal ends up looking at, not where the markdown files are.

Need to set the working directory for Process.Start()

**Comment by RickStrahl** [comment]
Which open terminal are you referring to? There are a number of places you can open a terminal.

If you open in a document (from a tab) it should always open in the folder of the document. It'll use the document's path to figure out where to open, so as long as the path to open is a full path that includes a folder that will work. I don't think there's a way to get a partial path there.

The other place is in the terminal and again it depends on context. Generic context (ie. no file or folder selected should open in the same folder as the folder browser's current path. If you are selected on a file the file or folder the folder or file path should be used.

**Comment by jmclain** [comment]
Tools -> Open Terminal

Make sure the current markdown file is on a different drive than the Markdown Monster installation.

**Comment by RickStrahl** [comment]
When you hover over the tab for the document - what does the filename show? Is it a fully qualified path with a drive specifier?

**Comment by RickStrahl** [comment]
FWIW I'm using this:

```json
  "TerminalCommand": "powershell.exe",
  "TerminalCommandArgs": "-noexit -command \"cd '{0}'\"",
```

for my terminal. I guess I should check and see what the default is doing :-)

**Comment by RickStrahl** [comment]
Ok I see what's happening now - yeah the issue is that in the `CMD` shell `cd {0}` will change the folder but won't take you to the new drive. I guess you'd need two commands. 

I think I'll just switch the default to powershell, which is a better choice anyway.

**Comment by jmclain** [comment]
I'm using tcc.exe (take command). Also tested with cmd.exe.

BTW, lots of folks are not powershell users. I'm ambivalent, unless I use it on a daily basis (which I do not) I totally forget how to use it!

**Comment by RickStrahl** [comment]
That's why you can change it :-)

This should work for cmd.exe:

```json
  "TerminalCommand": "cmd.exe",
  "TerminalCommandArgs": "/k cd /D \"{0}\"",
```
