### ISSUE TITLE
File Browser Rename issues

### ISSUE THREAD

**Issue by jmclain** [RickStrahl/MarkdownMonster#272]
When you rename a file in the file browser there is no attempt to check and update the Document object if the successfully renamed file is currently open in mm. 

Additionally when a file has been renamed HandleSelection() is called which in turn tries to open the file that has just been renamed with the old file name in a new tab; I stopped following the code there and assume the open tab code will see that the file is already open (and not open a new tab).

Only discovered this because I have some addin code that checks that the source file exists, which it doesn't after the rename.

Thanks,

Joe McLain

**Comment by RickStrahl** [comment]
I think this fixes it: 
f831b8916c4111f4e96fe26180731050a8d4439b

This handles renaming of the tab if an open file is renamed. Also adds a useful GetTabFromFilename() method that retrieves a TabItem and its Tag that contains the MarkdownDocumentEditor.
