### ISSUE TITLE
MarkdownParserMarkDig member Pipeline is static, why?

### ISSUE THREAD

**Issue by jmclain** [RickStrahl/MarkdownMonster#273]
I'm looking at class MarkdownParserMarkDig and I see that the `Pipeline` member is static, this means that all instances of the class will share the same pipeline.

```
        public static MarkdownPipeline Pipeline;
```

The problem I see with this (a problem I've run into) is that it is impossible to keep multiple instances of the class around that have different `_usePragmaLines` values since the (static) Pipeline will have been built with the value of `usePragmaLines` passed most recently to the ctor. So, I might create an instance that does not use pragma lines, but if I hold on to that instance and the next instance generated somewhere else in mm  uses pragma lines I will get those pragmas lines when I use my instance.

`Pipeline` is only used  in MarkdownParserMarkDig and I'm not sure why you'd want to access it outside of that class. I think is should be non-static and protected.

Thanks,

Joe McLain

**Comment by RickStrahl** [comment]
I'm caching the pipeline because it takes time to initialize it - ie. it slows down rendering.

You can always force the pipeline to refresh by using the `force` parameter on the rendering method.

**Comment by RickStrahl** [comment]
On second look, making the pipeline static is not really necessary as the parser is cached in a static instance which handles the caching. FWIW, MM doesn't really use the caching - all places actually force a load.

This is for a more generic use case in an application like a Web app where you would use the same parser for each operation. 

IAC, I've made the Pipeline `protected` and not static.
