### ISSUE TITLE
All the sudden it crashed and there is no error log......

### ISSUE THREAD

**Issue by tom10271** [RickStrahl/MarkdownMonster#274]
`There are no errors log in your log file.`

WTF? Luckily I have typed a few lines only

**Comment by RickStrahl** [comment]
Hi Tom,

Sorry to hear that you had an issue.

Can you be more specific when and how it crashed? Was it a hard crash (ie. Windows crash dialog - most likely if there's no log entry). If there's no log entry in the MM log that means it was a hard Windows crash in which case there might be more info in the Windows Event log.

If things were working before and are consistently crashing on startup you can try deleting or renaming `MarkdownMonster.json` so a new configuration file is created with default settings. This effectively resets MM.

If it is a hard Windows crash the most likely problem is video card issues in which case you can try turning off the GPU acceleration in the configuration. Here's a related issue to do with hardware acceleration, which shows how to turn off video hardware acceleration:

* [Turn off Hardware Accelleration](https://markdownmonster.west-wind.com/docs/_4uj0kfglm.htm)
