### ISSUE TITLE
Shortcut for "Delete Entire Line"

### ISSUE THREAD

**Issue by n-develop** [RickStrahl/MarkdownMonster#275]
I use Visual Studio and VS Code a lot. Both editors provide the shortcut `Shift+Del` for deleting the current line entirely. Is use this shortcut quite often and would love to see the same (or something similar) in MarkdownMonster.

**Comment by RickStrahl** [comment]
Interesting - never even knew that existed in VS Code/VS. It's not part of ACE editor, so this would have to be manually implented. Not difficult to do - but wonder how many would actually use that.

And 'active' line in MD really would mean 'active paragraph'  which might have unexpected consequences?

**Comment by n-develop** [comment]
Thanks for your response, @RickStrahl.

Hmm... if it would delete the entire paragraph, this would be too much, I think.
Is there no way to determine the current "editor line" and delete just that one?

**Comment by RickStrahl** [comment]
In Markdown a paragraph is a single line - the paragraph-ing comes from  word wrap.

Yes you can figure out the current line and delete it, but I'm not sure if that would be expected behavior. I think that would be odd. I'd have to check what VS Code does with that in Markdown Mode.

**Comment by RickStrahl** [comment]
So VsCode also deletes an entire paragraph if word wrapping with Shift-Del.

**Comment by n-develop** [comment]
Ah, ok. We are talking about active word wrapping. Then I would say deleting the entire paragraph is expected. Because technically (for the file) it's one line. I think it would be cool to have that. Maybe make it configurable and disabled by default?

**Comment by n-develop** [comment]
Just to clarify why I was confused about the "paragraph" and "word wrapping". If I insert a single line break, the text will still be rendered inside a single paragraph. Like in this screenshot.
![grafik](https://user-images.githubusercontent.com/13137880/33545356-34fe9c9e-d8de-11e7-890a-9589ec4fde62.png)

If I do the same in VS Code and hit Shift+Del on the "one paragraph" line, only that line with this two words will disappear.

**Comment by RickStrahl** [comment]
Right - I was talking about a 'paragraph' in the editor not the rendered output which are two distinctly separate things.

**Comment by n-develop** [comment]
That's pretty cool. Thank you for the quick responses and the fast implementation, @RickStrahl.
