### ISSUE TITLE
Spellchecking strange behaviour

### ISSUE THREAD

**Issue by anders-eriksson** [RickStrahl/MarkdownMonster#279]
I'm using MM 1.8 and OpenOffice Swedish dictionary SV_SE.
Some word don't exist in the dictionary and I get a red squiggle line. Normally I just right-click and get a dialog where I can add this word. But for some words I don't get the spelling dialog, just the copy, cut, paste dialog. E.g. Cejn, Elajo, DCAdmin.

I can add the words directly into SV_SE_custom.txt, BUT then I need to restart MM to make it re-read the dictionary..._

Also if I use a abbreviation, e.g. **ev**, then MM suggest that I should use **ev.**, so I accept this, but the red squiggly line is still there!

**Comment by RickStrahl** [comment]
Hmmm... you should still see the **Add to Dictionary** option.

Looks like if there's absolutely no match then the option doesn't show. But in most cases - even using very bogus words **something** just about always comes up and then it shows.

I'll check to see why we're not getting the **Add to Dictionary** when there's no items from the JavaScript code.

**Comment by RickStrahl** [comment]
This should do it:

d2b03e8ef02a9bfcccba450c3b932eaabd2ae014

![image](https://user-images.githubusercontent.com/1374013/33635910-eb84ec90-d9bd-11e7-98ae-699f2f4e8cf7.png)
