### ISSUE TITLE
White on black. 

### ISSUE THREAD

**Issue by genericeventhandler** [RickStrahl/MarkdownMonster#28]
Hi, 
I have a laptop that has a highly reflective screen, I cannot see the text with the twilight EditorTheme, what  other values can I enter in there to change to a black on white screen?

**Comment by RickStrahl** [comment]
You can change the editor (and preview) theme on the bottom right:

![image](https://cloud.githubusercontent.com/assets/1374013/19742898/b6cd7fca-9b62-11e6-9fb0-83105f76319d.png)

Or you can type one of those theme names into the settings editor for the `EditorTheme` property.
