### ISSUE TITLE
Feature Suggestion: Drag and Drop from Explorer

### ISSUE THREAD

**Issue by thnk2wn** [RickStrahl/MarkdownMonster#280]
It'd be great if MM supported drag and drop to open a markdown file. Often I'm already in explorer and it's sometimes easier or more intuitive to drag and drop to open vs right click, open with or going File Open in the app.

![2017-12-05_14-03-27](https://user-images.githubusercontent.com/120529/33633317-3880b6a8-d9c5-11e7-8f94-28162af23048.png)

**Comment by RickStrahl** [comment]
That should work. Just checked and it works for me.

Make sure you're not running MM (or Explorer) as an Administrator though - Drag and Drop in Windows doesn't work if either client or server in D&D operations are running as Administrator.

**Comment by thnk2wn** [comment]
Thanks, that must be the issue. Unfortunately I currently have to run as Admin because the company has a frustrating policy in place that does not allow .exe to be run in the appdata folder.

![mm-blocked](https://user-images.githubusercontent.com/120529/33634262-797d1a0e-d9c8-11e7-8a43-d5960530390d.png)

I can try reinstalling to another location maybe though at the moment I can seem to uninstall either :)

![mm-uninstall](https://user-images.githubusercontent.com/120529/33634337-aad06980-d9c8-11e7-9c72-89c5d9eaeb51.png)

**Comment by RickStrahl** [comment]
The installer will run without elevation. Try explicitly to run the installer with Run As Administrator which should allow you to uninstall.

This seems a bit odd - I explicitly moved to the AppData folder (by default) to allow for a portable install that requires no admin privileges for any installation related issues, including the installer. Installing into Program Files requires admin rights :-) 

So if you do reinstall to Program Files (x86) make sure you run the installer as Administrator.

**Comment by thnk2wn** [comment]
Thanks. Ran the uninstall exe within the MarkdownMonster install directory to remove. Reinstalled to to a different location and ran normally. Drag and drop worked fine.

I think the company and others like it block AppData and sometimes temp folders because they're areas that the user's account should expect to have some level of access to and malware often runs from these locations. The downside is it blocks legitimate apps like Markdown Monster and Fiddler, at least by default.

https://serverfault.com/questions/574724/what-are-the-pros-cons-of-blocking-a-program-from-running-in-appdata-temp

**Comment by RickStrahl** [comment]
Yeah I'm not sure it was a good idea to move to %LocalAppData% - it seems to be more of a hassle just to allow running in non-admin mode. Program Files just seems like a more reliable and **expected** location.

FWIW, once you switch to a new location uninstall and re-install automatically remembers that location so you should be able to use things like Chocolatey after the initial install. I recommend to install into **Program Files (x86)** which would be the preferred *alternate* location.
