### ISSUE TITLE
Wild text editor selection problem

### ISSUE THREAD

**Issue by thnk2wn** [RickStrahl/MarkdownMonster#281]
I can't seem to select a block of text when it involves scrolling the editor, regardless of whether the mouse and/or keyboard is used. I suspect it has something to do with the auto preview but it happens even when in full screen edit mode with preview closed.

The problem is also reproducible without scrolling by doing something like quickly selecting a paragraph of text. This can cause lost changes if quickly selecting a paragraph and then doing paste for example as the selection gets reset and you end up overwriting something you didn't intend to.

I've attached a screencast and sample markdown in the attached zip:

[Temp.zip](https://github.com/RickStrahl/MarkdownMonster/files/1533373/Temp.zip)

**Comment by RickStrahl** [comment]
Yeah this is something I have noticed too, but have not been able to pin down exactly. I think it has to do with the new scroll sync detection, although I'm not sure why that would lose the selection.

Looking into it.

**Comment by RickStrahl** [comment]
Thanks for tagging this - found the problem and fixed it. Issue was if there's a selection, when scrolling the cursor gets reset and that forces a new selection pointer and collapse of the selection.

Code now checks for a selection and if there is one just exits. There's no scroll sync while the selection is active but it should refresh at the end of the selection either via mouse up or by the new end cursor position.

**Comment by thnk2wn** [comment]
Cool. Wow, thanks for the quick fix! I'll give it another go when there's a new update.

**Comment by RickStrahl** [comment]
Yeah that's one that's bitten me quite a bit myself and you gave the incentive to go hunt this down. It's a simple fix too thankfully. 

That was a nasty one too...
