### ISSUE TITLE
Middle section toolbar commands all require selected text

### ISSUE THREAD

**Issue by thnk2wn** [RickStrahl/MarkdownMonster#282]
MM 1.8.0.0

All the toolbar buttons in the middle section (bold, italic, headings, etc.) all seem to require text selection to work. That may be by design and many times various commands may generally only be executed after text is selected. However this isn't always the case and it would seem they would work either way, or at least be disabled when they won't work or give a message etc. Markdown editors in GitHub, BitBucket etc. all seem to work either way, with or without selected text so it seems intuitive to expect the same in MM.

[2017-12-06_10-39-03.zip](https://github.com/RickStrahl/MarkdownMonster/files/1536436/2017-12-06_10-39-03.zip)

**Comment by RickStrahl** [comment]
I don't know - just because it works in online editors, doesn't mean it's a good idea. When would you ever want to italic or bold markers when there's no selection? 

I can see it for blockquote and headers, but the rest - not so much.

**Comment by thnk2wn** [comment]
Yeah the headers, lists, blockquote make more sense with no selection than bold, italics and such.

However even for bold and italic with no selection I'd expect it to create the markers and then to insert the cursor inside the markers where I'd begin typing whatever I wanted formatted there but I agree it's not as applicable there.

Pretty minor overall, just something I noticed.

**Comment by RickStrahl** [comment]
Ok, added support for insertions with cursor movement.

cfb94da07d02ee48c3917c88bd5ed3e4bfdbd52a

Should show up in 1.8.2

**Comment by thnk2wn** [comment]
Cool, thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
