### ISSUE TITLE
Remove formatting

### ISSUE THREAD

**Issue by jgiesbrecht** [RickStrahl/MarkdownMonster#283]
Once a line of text is say bolded there isn't a way to quickly (using a keystroke) return the text to a neutral state or apply different formatting to it.

**Comment by RickStrahl** [comment]
Yeah that's a long rabbit hole to go down since there are so  many possible permutations that can be used. There are a few simple use cases (like bold/italic) but most other cases are really difficult to delineate. Like what do you do if there are multiple markups applied (ie. a bold hyper link or bold italic) etc.

Since the text isn't actually tokenized markdown and it's just **text** I don't think this is something that can be done reliably in an effective way.

**Comment by jgiesbrecht** [comment]
How about a strip markup? That would return text to its vanilla form and allow the user to then apply any formatting they want? It would, however, be nice to just have a simple undo for the last command executed.

**Comment by RickStrahl** [comment]
You can always use Ctrl-z to undo changes for actual last input.

Stripping Markdown reliably for all situations is very tricky as there are a boatload of combinations. Single parsing is easy enough but nesting is really tricky. 

As a workaround to deal with this you can copy the rendered text from the browser and paste that to get back to unformatted text in the editor. Not exactly smooth but it fits those limited use cases where this needs to be done.

**Comment by RickStrahl** [comment]
Ok changed my mind after looking into this and finding out that Markdig includes support for unformatting markdown. 

* Added Edit Menu option
* Added Context Menu Option
* Added Ctrl-Shift-Z shortcut

Here's what this looks like:

![image](https://user-images.githubusercontent.com/1374013/33794464-d0fa1f70-dc70-11e7-9813-a2b75b18ca50.png)

Cleanup strips all Markdown markup but it's not 100% perfect on complex sections. Somethings that don't work well:

* Nested tags in general
* Images with titles embedded - titles will render as text 
* Code blocks loose spacing in many cases.

Still it works pretty good overall and can also be used to undo existing formatting easily enough. So highlighting a `**bold**` section will undo the text nicely and with the `Ctrl-Shift-Z` shortcut this is relatively quick and unobtrusive.
