### ISSUE TITLE
Links from TocGenerator don't work!

### ISSUE THREAD

**Issue by Andis59** [RickStrahl/MarkdownMonster#284]
I have already asked this on Daniel Vaughans github issue
https://github.com/DVaughan/MarkdownMonster-Addin-TocGenerator/issues/5

But he says that the problem is not in TocGenerator but in Markdown Monster so I ask here also.

I have just installed you TocGenerator adding and it works fine, except that the links don't work.
I have follow your note about removing base from head in the preview template I'm using, but nothing changes.

I'm not a HTML guru, but to get '`<a href="#foo">foo</a>`' to work you need to have an id="foo" on the element that we should jump to, e.g. "`<h1 id="foo">Foo </h1>`"

If I look at the html code that is produced, by Markdown Monster, there is no id's!

I have autolinks=true
here is a snippet from the settings.
```
"MarkdownOptions": {
    "AutoLinks": true,
    "Abbreviations": true,
    "AutoHeaderIdentifiers": false,
    "StripYamlFrontMatter": true,
    "EmojiAndSmiley": true,
    "MediaLinks": true,
    "ListExtras": true,
    "Figures": true,
    "GithubTaskLists": true,
    "SmartyPants": false,
    "RenderLinksAsExternal": false,
    "MarkdigExtensions": "emphasisextras,pipetables,gridtables,footers,footnotes,citations,attributes",
    "AllowRenderScriptTags": false,
    "MarkdownParserName": "MarkDig"
  },
```
I'm running Markdown Monster 1.8.1 and TocGenerator 1.1

What is wrong?
// Anders

**Comment by RickStrahl** [comment]
See response in original issue in @DVaughan's repo.

**Comment by RickStrahl** [comment]
Fixed issue with preview.js not navigating ID links for hashes.

70fd1af6af93923fa4a89d2b18da860b80d05f99
