### ISSUE TITLE
Enhancement Request: Add Support fot LaTeX

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#287]
Adding support for LaTeX would enhance immensely the capabilities to publish scientific work.

Highly anticipate this feature.

**Comment by RickStrahl** [comment]
This is beyond the scope of Markdown Monster. Again - if you really want this support an addin with a custom latext parser can be created, but it's not something I'll bake into the base version as it would break the edit UI and tooling that's specifically optimized for Markdown.
