### ISSUE TITLE
Add Text Find & Replace

### ISSUE THREAD

**Issue by kkbruce** [RickStrahl/MarkdownMonster#29]
If no text Find & Replace, 
I need to open notepad or vs code or sublime text to do it.
I don't want ;-)

**Comment by RickStrahl** [comment]
Ctrl-F, Ctrl-H. It's there.

**Comment by weggetor** [comment]
Hmm - not for me

**Comment by RickStrahl** [comment]
@weggetor - Interesting - I don't get it either anymore. Recent upgrade of Ace might have broken this. I think it might have to be explicitly enabled now. Will check. Will also add menu items to the Edit menu with the hotkeys (even though they won't actually do anything as it's auto-handled).

**Comment by RickStrahl** [comment]
Fixed. Caused by missing extension files in Ace Editor Configuration. 1ea9165330b0924eaee98a3f3408eaa0cd4efe90

Also updated searchbox styling, and added menu options to the edit menu.
6a5c2d5b92858fa44c7bf0ae8bde0bac6c6db672
