### ISSUE TITLE
Indent bullet or number when pressing `Tab` key on empty item

### ISSUE THREAD

**Issue by breki** [RickStrahl/MarkdownMonster#290]
Similar to #176, it would be a nice feature for the empty bullet or number to be indented one level higher when the new bullet/number line is auto-generated and the `Tab` key is pressed.

It's probably the same problem as in #176 - someone needs to dig into ACE to figure how to do this.

**Comment by RickStrahl** [comment]
Closing as this is essentially in the same vein as #176. It's referenced from there so when addressed we'll circle back to this.
