### ISSUE TITLE
Save as PDF returns error 1073741515

### ISSUE THREAD

**Issue by mindstretch23** [RickStrahl/MarkdownMonster#291]
Repro'd on Windows 10 and Windows 2016. 
.NET 4.6.2 is installed

Any idea how to fix this?
![save-as-pdf-error](https://user-images.githubusercontent.com/4995491/34636282-1ff4b4be-f25b-11e7-98ac-b0536e493ffb.png)

**Comment by RickStrahl** [comment]
Not sure. I can't duplicate it here - that document renders for me.

![image](https://user-images.githubusercontent.com/1374013/34638338-85997568-f26d-11e7-948f-46396296721a.png)

Not really sure what to try to pin this down. MM shells out to wktohtml.exe to run the PDF generation. Maybe you can shell out to the command line and run the command that's in the error message and see if you get additional error info on the command line.

**Comment by RickStrahl** [comment]
Closing since there's been no follow up. If you have more information please feel free to re-open this issue.
