### ISSUE TITLE
Pandoc PDF Creation error

### ISSUE THREAD

**Issue by HowardEdidin** [RickStrahl/MarkdownMonster#293]
Error: pdflatex not found. Please select a different --pdf-engine or install pdflatex

![image](https://user-images.githubusercontent.com/19954905/34743468-755778e6-f54f-11e7-93ae-88ec1d47f416.png)

**Comment by RickStrahl** [comment]
You probably need to have a Latex installation that supports PDF generation with Pandoc.

The combo I recommend that I know works:

```
choco install pandoc
choco install MikTex  
```
More info on the Pandoc extension project page:

https://github.com/RickStrahl/Pandoc-MarkdownMonster-Addin

**Comment by RickStrahl** [comment]
Also note that you can directly create PDF files from **File -> Save As Pdf**. This uses wkhtmltopdf and in my experience it produce much better PDF output then what you get with Pandoc.
