### ISSUE TITLE
PDF Generation Document Header issue

### ISSUE THREAD

**Issue by HowardEdidin** [RickStrahl/MarkdownMonster#294]
The header on pages 3 - 7 
The Doc title overlaps the section title.

![image](https://user-images.githubusercontent.com/19954905/34798860-3a2e3852-f623-11e7-8673-335e645f4105.png)

The pdf doc is attached. 

[Cosmos DB Data Consistency Models for Healthcare Integration.pdf](https://github.com/RickStrahl/MarkdownMonster/files/1620636/Cosmos.DB.Data.Consistency.Models.for.Healthcare.Integration.pdf)

I really don't want to have the section title in the header. Can you add a checkbox to disable it?

**Comment by RickStrahl** [comment]
Well you have really long titles and headers are single line so somwhere this will break. I think in this case it would be better to print without page headers.

**Comment by RickStrahl** [comment]
I made a few changes in the way the PDF document is generated and among them is to not show the sections in the title any longer. This way only the title shows - so a longer title will work (unless it's really long) without wrapping into the section name.

Section name can still be optionally used in the footer by explicitly embedding `[section]` into the footer (or it also works in the header).

![image](https://user-images.githubusercontent.com/1374013/34905530-a833f242-f7fe-11e7-8c53-ae34bc3a0993.png)
