### ISSUE TITLE
Save to pdf - enhancements

### ISSUE THREAD

**Issue by Andis59** [RickStrahl/MarkdownMonster#296]
I always use the Markdown to create an PDF, and I suggest some enhancements to the function.

1. Make the GeneratePdfWindow remember what I have selected the last time. I.e. Page Size, Orientation, Image DPI, Margins, Display PDF after generation...
2. Add a checkbox for selecting if bookmarks (--outline/--no-outline) should be generated or not. I have a lot of short texts for which there makes no sense of having bookmarks.

**Comment by RickStrahl** [comment]
Does the outline really get in the way? It would seem that that's a sidebar that usually is not visible and not really a concern?

It'd be easy enough to add, but my guess it it's just as well to always gen it IMHO.

**Comment by RickStrahl** [comment]
I've added the **Generate Table of Contents** option to the dialog.

![image](https://user-images.githubusercontent.com/1374013/34905538-c3703282-f7fe-11e7-9504-c861366368db.png)

There are a number of additional enhancements including:

* Copying the command line used to generate the PDF
* Cleaned up titles (only the title prints now on the left)
* Error messages are now displayed more clearly
* PDF Generation doesn't tie up the UI any longer

**Comment by Andis59** [comment]
Tried the new Save to PDF and the Generate Table of Contents works perfectly, Thank You!
The first point, that it should remember the last entered/selected values, seems not to be implemented?
If not remembered maybe a configuration?
