### ISSUE TITLE
Suggestion: do not reopen files by default

### ISSUE THREAD

**Issue by mikeyww** [RickStrahl/MarkdownMonster#298]
Suggestion: if command line has no parameters, start program with no open documents, unless a new option indicates to reopen the documents.

Version = 1.8.12

**Comment by RickStrahl** [comment]
That's a configuration option. 

`RememberLastDocumentsLength` determines how many of the last open documents are opened. Set this value to 0 if you don't want to remember tabs.

**Comment by mikeyww** [comment]
Thanks!

**Comment by RickStrahl** [comment]
Keep in mind that this affects both command line and interactive opening however.

**Comment by mikeyww** [comment]
OK.
