### ISSUE TITLE
Scrolling with preview

### ISSUE THREAD

**Issue by mikeyww** [RickStrahl/MarkdownMonster#299]
Synchronized scrolling does not work well with the preview, especially when scrolling up. When scrolling up in the main window, the preview window does not always match. I can often see text in the main window that is not visible in the preview.

Version = 1.8.12

**Comment by RickStrahl** [comment]
Need more details on what you're doing exactly. What sync mode are you using? Best mode in general is **Editor -> Preview** rather than **Editor and Preview** as there can be double sync issues. 

Additionally there are known issues if you have code blocks or images that take up most of the screen as these elements are not tagged with the necessary pragma lines to match editor to preview.

I see this occasionally usually in very code or image heavy documents but it's pretty rare for me. Can you provide a document that causes issues?

**Comment by mikeyww** [comment]
Many issues with scrolling are not working for me.  I have the following setting.
"PreviewSyncMode": "EditorToPreview",
When scrolling, the preview does not always adjust to correspond to the main window. In addition, even in the main window alone, I cannot see the last line of the file; it is hidden off screen. Incidentally, I use Windows display setting with 120 DPI.

![image001-20180111](https://user-images.githubusercontent.com/10785606/34824681-811578fa-f69d-11e7-983c-20b4f49a6e6d.png)
![image002-20180111](https://user-images.githubusercontent.com/10785606/34824679-7e6e4744-f69d-11e7-8dd1-774ad1640dfe.png)
![image003-20180111](https://user-images.githubusercontent.com/10785606/34824675-7b209eac-f69d-11e7-9bca-72cedde8a6fd.png)

Computer: TOSHIBA PORTEGE R930
Operating system: Microsoft Windows 7 Professional 64-bit Version 6.1.7601
Service pack: 1.0
Total physical memory (MB): 16262
Available physical memory (MB): 11605
Processor: Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz 64-bit
Processor type: Intel64 Family 6 Model 58 Stepping 9
BIOS: TOSHIBA Default System BIOS Version 6.80  
Motherboard: TOSHIBA PORTEGE R930 Version A0
Display name: Intel(R) HD Graphics 4000
Display resolution: 1366 x 768
Display dots per inch (DPI): 120

**Comment by RickStrahl** [comment]
Yes the issue here is that these are multi-page lists. List items are another of the items that aren'ttagged with line numbers in the markdown parser we use so the we can't sync the preview.

Can you open another large document that's mostly just paragraph text and verify that scrolling is more reliable with that?

**Comment by mikeyww** [comment]
Not working so well. 
![image004-20180111](https://user-images.githubusercontent.com/10785606/34825843-1a59deee-f6a2-11e7-9682-251f8b49e754.png)
Also: I use Github preview theme but change default font size from 16px to 14px.

**Comment by RickStrahl** [comment]
Ok so I took a look and there is a problem apparently when on an `untitled` document. Not quite sure why, but in an untitled document the preview is not syncing **at all** - the pragma lines aren't created. 

Can you verify that if you save the file above scroll sync is working?

Definite bug that looks like a regression based on the document file name.

**Comment by mikeyww** [comment]
Scrolling alone does not generate sync like it should. I also have to click on the line of interest to make the sync happen.  This seems unexpected from the user's perspective.
![image005-20180111](https://user-images.githubusercontent.com/10785606/34851925-3f2a523c-f6fa-11e7-8a53-23f975a7bc2c.png)
![image006-20180111](https://user-images.githubusercontent.com/10785606/34851921-3d6baaae-f6fa-11e7-87c9-44823f51e20a.png)

**Comment by RickStrahl** [comment]
Ok so the preview bug should be fixed now. 2309ec1140096e33eb8d517c18d4fdb365fb3bea - indeed a regression bug.

I'm not seeing what you see. MouseScroll or scrollbar scroll will move sync the preview for me.

Note: You have to be moving more than a screen. If the content is already visible on the same page the pointer won't update as the scrollbar is not precise in positioning (there's no way to accurately map a scroll position to a line - we can only look at what's in the viewport and use the document positioning roughly at the center of the page to figure out where the cursor sits). IOW, small scroll operations are often not going to move the preview, but if you scroll more than a screen you should see the preview move.

**Comment by RickStrahl** [comment]
BTW, thanks for your patience. These reports are all very useful weeding out little issues. Thank you.

**Comment by mikeyww** [comment]
Thank you!
