### ISSUE TITLE
Hangs on starting and opening new document

### ISSUE THREAD

**Issue by Anaerin** [RickStrahl/MarkdownMonster#3]
Fresh install, no preferences changed.

Open MM, click "File->New".

Tab "untitled" appears, but editor within does not, then application freezes.

Nothing added to errors log.

**Comment by RickStrahl** [comment]
Hmmm... that one's tricky since I can't dupe it here. 

Does the application actually freeze or is there just nothing displayed? I've had timing issues with the Web Browser control that hosts the editor. If that's the case you should be able to resize the Window which forces the UI to completely refresh.

Can you open an existing Markdown document?

One more thing - what OS are you running?

Thanks for your help.

**Comment by Anaerin** [comment]
The application freezes, you can't open move or resize the window at all.

Opening an existing document does the same thing, and the following was logged (once, despite multiple attempts):

````
2016-06-06 3:27:55 PM - Not enough quota is available to process this command
---
PresentationCore
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
````

And, after attempting to open a document, every attempt to open the program freezes on the splash screen with an open but blank (and transparent) window behind it as it tries to load that document again.

Having cleared the settings file (deleted the .json), it's still doing it. However, if you trigger the alert from bug #2 then the editor loads and appears to work properly. Which is decidedly weird.

**Comment by Anaerin** [comment]
Updated to 0.27, and this issue is still there, unfortunately.

**Comment by RickStrahl** [comment]
That's a bummer but I'm just not sure what would be causing that. I test MM on three different machines and none of them have this particular problem.

It sounds like there's a some sort of UI initialization problem.

The error message sounds like some sort of permissions problem. Is there anything special about your user profile

Wonder if it could have to do with the Insider build of Win10 you're running? I'm on 14342. Doubt it.

**Comment by RickStrahl** [comment]
Did a little research on that error and ran into this (second half of video)

https://www.youtube.com/watch?v=Hae1gbTNWks

Basically related to profile storage allocated on a roaming profile. Could it be that you're running out of space?

MM doesn't use much memory for storage, but it does run Web Browser controls for the editor (for each open document) and previewer and that might be what's causing an issue if resources are low.


Sorry for all of this - I appreciate you taking the time to look into this.

**Comment by Anaerin** [comment]
My system drive currently has 2.25TB/3.63TB free, and I'm running 16GB of RAM, of which 7.2GB is available. So I really don't think it's a storage issue. At least, I hope not.

**Comment by RickStrahl** [comment]
No this error seems to relate to profile storage if you are running a roaming profile:

http://blog.coultard.com/2012/01/fix-windows-error-0x80070718-not-enough.html

Not sure whether that applies to you, but worth checking out.

**Comment by Anaerin** [comment]
It doesn't apply to me, as I'm not running a profile storage, this is entirely a vanilla Windows install. It might also be because I had the log open at the time, and it was trying to update the log while Notepad2 had it locked.

I have no idea what the problem is, though.

**Comment by RickStrahl** [comment]
Thanks for trying.

Not sure what else I can check at this point, since I can't duplicate. I haven't heard this from anybody else either, but that doesn't mean it's not happening - I just may not hear about it.

I'm going to close this for now, but if you try again at some point in the future, feel free to reopen if there's more info.
