### ISSUE TITLE
Can we change path of the setting file

### ISSUE THREAD

**Issue by hikalkan** [RickStrahl/MarkdownMonster#30]
Can we change/configure the path of the setting file, ``MarkdownMonster.json``? It's an odd request, I know, but my path is ``C:\Users\Halilİbrahim\AppData\Roaming\West Wind Markdown Monster`` and the Turkish ``İ`` char become a problem and I'm constantly getting this error:

![error](https://cloud.githubusercontent.com/assets/1210527/19755367/09351cee-9c1e-11e6-8a63-4d19ac5747e3.png)

**Comment by hikalkan** [comment]
I realized that it was not the setting file, but the temporary files. Can we change it's path?

**Comment by RickStrahl** [comment]
@hikalkan Do you know why this is blowing up? I understand the issue with Turkish i when doing upper/lowercase conversions, but in this case we're just using your actual path. Do you have any idea why this is actually failing? 

It's hard to tell but I think you're saying the i is getting translated into a UTF-8 encoded value?

MM uses the user's temp path - so you can change that path to a different location in your Windows Environment settings. If this is causing problems I bet you're seeing it in other places as well?

I don't think I fix up the path that's used in any way (ie. no UTF-8 encoding) so the encoding must be coming from the Web browser control. If that's the case I'm not sure I can fix this on my end. I'll take a look...

**Comment by hikalkan** [comment]
Yes, the problem is the web browser control. I can edit the text but I can not see it in the right panel, and frequently getting this error.

And yes, the problem is fixed when I change Windows temp folder to another folder which does not contains "İ" :)

Thank you very much for your support.

**Comment by RickStrahl** [comment]
Just as a follow up I ended up fixing this issue. The problem was caused by the Web Browser control taking Unicode text and incorrectly doing a UTF-8 conversion on it. Using a Uri object instead however worked and properly encodes the file based URL so that the extended character (the turkish i) gets into the right place.

**Comment by hikalkan** [comment]
Thank you @RickStrahl for a better solution.
