### ISSUE TITLE
Preview sometimes opens with small font

### ISSUE THREAD

**Issue by mikeyww** [RickStrahl/MarkdownMonster#301]
The preview window sometimes opens with a font that is smaller than the one specified in the config file. This seems to be related to the one-second timer: I think that it happens when activating the preview window less than one second after completing other tasks.

Version = 1.8.12

**Comment by RickStrahl** [comment]
The preview window doesn't have a font size that is configurable via config file. Preview font size is determined by the CSS styling in the Preview folder and depends on the theme that is selected.

**Comment by mikeyww** [comment]
It's still coming up wrong occasionally, especially when first opening a file. In these cases, if I close the preview window and then open it again immediately, the font size changes to the right one.
