### ISSUE TITLE
How to change the color of syntax highlighting

### ISSUE THREAD

**Issue by mikeyww** [RickStrahl/MarkdownMonster#303]
How to change the color of syntax highlighting in the main editor window?

**Comment by RickStrahl** [comment]
You can select a different theme with the selector on the bottom right. 

![image](https://user-images.githubusercontent.com/1374013/34849263-ec50c854-f6c5-11e7-807a-38ad95aab7e8.png)

You can customize themes in the `.\Editor\scripts\Ace` folder. Any of the `theme-xxxx` files correspond to the themes in use. I recommend if you end up customizing you add a new theme by copying one of the existing ones which should then become available on the menu.

The most complete theme for Markdown is the default Twilight theme and I recommend you use that as a starting point.

Note these are standard ACE Editor theme. You can also check the ACE Editor site for additional themes and suggestions and or pull requests for adding new themes that become part of ACE editor itself.

**Comment by mikeyww** [comment]
Thanks!
