### ISSUE TITLE
Light Theme - color choice on new folder creation

### ISSUE THREAD

**Issue by mantis** [RickStrahl/MarkdownMonster#305]
Just checking out markdown monster having decided not to use it about a year ago (not sure why - it may have been if it was dark theme only back in the day!)

The colors when making a new folder on the light theme do not currently stand out:

![image](https://user-images.githubusercontent.com/16276382/34915383-b733e5c0-f91d-11e7-93b8-7f6dd256be2c.png)

**Comment by RickStrahl** [comment]
Thank you. Fixed. You can get **Latest pre-Release**  from the [download page](https://markdownmonster.west-wind.com/download.aspx) which includes these fixes.
