### ISSUE TITLE
Drag/drop image file doesn't do %20 space replacements

### ISSUE THREAD

**Issue by bladewolf55** [RickStrahl/MarkdownMonster#307]
Version 1.8.14

## Steps to Reproduce
1. Open new MM document
2. Create an image with spaces in the filename, e.g. `2018-01-15 18_07_57.png`
3. Drag the image into the document.
4. The Markdown should be `![](images/2018-01-15%2018_07_57.png)`, but is `![](images/2018-01-15 18_07_57.png)`

## More Information
I put my images in a folder named "images" under the Markdown file.

**Comment by RickStrahl** [comment]
Thank you. Fixed. Found another place in the paste operation with a similar issue.

**Comment by bladewolf55** [comment]
You rock. I look forward to the release.
