### ISSUE TITLE
Save to Gist, Open from Gist and Toolbar Menu Items - Duplicated

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#308]
Did we suppose to see in MM File --> **Save to Gist**, **Open from Gist**, Toolbar menu items duplicated?
![image](https://user-images.githubusercontent.com/701808/35077951-b6e583e6-fbcd-11e7-8a8d-58f5c1b37067.png)

**Comment by RickStrahl** [comment]
No but it looks like you have multiple different versions of this thing installed (indicated by the two different icons). Uninstall the addins from the Addin Manager. Perhaps you worked with the dev version of one? If after uninstalling one stays behind you may have to explicitly delete the addin from the `%appdata%\Markdown Monster\Addins` folder.

**Comment by ArthurZ** [comment]
This is odd as I have only one Gist add-on
![image](https://user-images.githubusercontent.com/701808/35123829-cec18934-fc71-11e7-9186-df99b20cb3de.png)
Which icon color is the old one?

**Comment by ArthurZ** [comment]
But I do have several "Gist" add-ons:
![image](https://user-images.githubusercontent.com/701808/35123906-1b8600b0-fc72-11e7-8cdf-850534f880a1.png)

**Comment by RickStrahl** [comment]
That's because the addin got renamed a while back and then you likely installed it again. Delete both folders then reinstall the addin from the addin managed.
