### ISSUE TITLE
Registered Markdown Parsers Drop Down Not Showing Any Items

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#309]
Does the Registered Markdown Parsers drop-down suppose to show at least one I have in settings as
`"MarkdownParserName": "MarkDig"`?
How, what can I configure more than one?
I'm on the latest MM, there is tooltip text, if I click the arrow down, it attempts to drop it down, but the actual unfold does not happen:
![image](https://user-images.githubusercontent.com/701808/35078169-f2e3b542-fbce-11e7-98f0-29f97a471254.png)

**Comment by RickStrahl** [comment]
If only Markdig is installed the drop down doesn't show.

Other parsers require an addin. There are two that I know of:

* Pandoc Addin
* CodePlex Addin
