### ISSUE TITLE
Open md creates new instance

### ISSUE THREAD

**Issue by HowardEdidin** [RickStrahl/MarkdownMonster#310]
Rick,

Would it be possible to open a doc in a new tab, instead of a new instance?

**Comment by RickStrahl** [comment]
Depends on settings - what you describe is the default, so you must have changed it at some point.

Set the the following setting in **Tools -> Settings**:

```
 "UseSingleWindow": true,
```

When `true` MM uses a single window for all documents. False and every time you open a file externally (ie from explorer or starting from desktop) a new instance is created. `true` is the default.
