### ISSUE TITLE
Add Git Pull to "Commit and Push"

### ISSUE THREAD

**Issue by VincentK76** [RickStrahl/MarkdownMonster#313]
When you are working with multiple people on the same repository the push can fail because someone else had made changes that you haven't pulled yet. Please add a Commit/Pull/Push action to be able to quickly send changes to your repository.

**Comment by RickStrahl** [comment]
Sigh - this becomes a big rabbit hole :-) 

It's something that has been asked and something I myself would like to see as well, but I really am not looking forward to rebuilding an entire Git client. The Commit to Git is meant as a convenient feature for quick changes. If you need something more complex I think the thing to do might be "open Git Client" instead.

**Comment by CADbloke** [comment]
Hey, I know a good tool for that ... https://github.com/RickStrahl/Commander-MarkdownMonster-Addin ;)

Love your work, btw, this  thing is awesome. :1st_place_medal:

**Comment by RickStrahl** [comment]
Just an update on this. 

I've started work on additional Git features. What's there now (1.10.11):

* Clone Git Repository
* Open folder in Git Client

Work in progress:

* Commit to Git Dialog 
    * Single File Commit (current behavior)
    * Commit all files
    * Show all pending changes and Commit selected files
* Git Status in File Browser 

The latter two will need a bit of work still so it's probably going to drag out the next update for a bit.
