### ISSUE TITLE
Suggestion: Port to Avalonia UI Framework

### ISSUE THREAD

**Issue by wcoder** [RickStrahl/MarkdownMonster#315]
> Avalonia UI Framework - Cross-platform .NET UI Framework with bindings and XAML

http://avaloniaui.net/

Using this framework adds an ability for use this editor on macOS, Linux, and will be a great demonstration powerful of .Net for cross-platform solutions.

What do you think about this?

**Comment by RickStrahl** [comment]
Unlikely :-) 

AvaloniaUI looks interesting for sure but it's not really compatible with WPF and looks to be pretty early in the development cycle and we're pretty far down the UI rabbit hole with this product. Also given that the the majority of the UI uses browser automation that code would even port in any way shape or form.
