### ISSUE TITLE
Upgrade issue

### ISSUE THREAD

**Issue by HowardEdidin** [RickStrahl/MarkdownMonster#316]
When upgrading to a new version, I get 
![image](https://user-images.githubusercontent.com/19954905/35780821-343f51a0-09a7-11e8-8cba-6e729246af5f.png)

![image](https://user-images.githubusercontent.com/19954905/35780825-3d859db4-09a7-11e8-9a67-23e9410412d9.png)

There are no instances running.

**Comment by RickStrahl** [comment]
Yes I see it from time to time that there's a hung instance of Markdown Monster sticking around.  I haven't been able to track it down however what causes that but I suspect after certain types of crashes there's a hanging instance of something keep MM alive. 

No resolution at this point and no idea how to track this down unless there's a reproducible scenario that causes this unfortunately.
