### ISSUE TITLE
A formatting icon for _underline_

### ISSUE THREAD

**Issue by mareklach** [RickStrahl/MarkdownMonster#318]
Next to the Bold, Italic and Strikethrough icons in the editor, it would be nice to also have an _Underline_ icon too.

Thank you,

**Comment by RickStrahl** [comment]
I conciously left that out since underline is such a rarely used feature these days. Is that important to you or are you just asking for completeness? Trying to not clutter up the toolbar as little as possible.

**Comment by RickStrahl** [comment]
Actually __underline__ is **not** underlined text - that translates to **bold**. Underlined text is `<u>underlined</u>` - there's no Markdown equivalent for underline except HTML markup.

Here's the BabelMark check for this scenario:
https://goo.gl/WfBSn4A

Which is another reason why I've been somewhat hesitant, but just to try it on for size I added it to the menu:

![image](https://user-images.githubusercontent.com/1374013/36180707-981ea502-10c5-11e8-9be3-6e6fe4dbeb8d.png)
