### ISSUE TITLE
Blog posts have the wrong date?

### ISSUE THREAD

**Issue by MattHoneycutt** [RickStrahl/MarkdownMonster#320]
I've noticed an odd thing when publishing blog posts to Wordpress and BlogEngine.NET.  It seems to set the publish date to a date that's in the past.  I can't figure out which date it is using.  For example, I just published a post today, and it set the post date to 1/25/2018.  

I do have several other documents open in Markdown Monster... it's almost like it's taking the earliest file date or something across all the open documents.... ?? 

Anyone else seen anything like that?  

Let me know what other info I can provide, I'm happy to help!  Thanks again for making such an awesome tool!

**Comment by RickStrahl** [comment]
Hmmm... I just tried this here publishing a post to my test Wordpress site and it goes there without any issues showing the current date. MM sets the date to the current date time when publishing always so I'm not sure how the date could be anything different.

That said - to make this process more transparent I've added the date to the meta data stored in the document, which has been a request for a few people for some time anyway:

![image](https://user-images.githubusercontent.com/1374013/36179161-58d21876-10bf-11e8-886e-603a99ca9b8d.png)

3bc29393a9a1c923b9ed0e2fa27dde7d78eac38b

This will also let you change the date when repositing a post. Tried this, changed the date and reposted and that showed the updated date in WordPress.

Now I'm not sure if this will fix the issue - it sounds to me like the Blog engine is perhaps doing something funky to change the date on you, but with this at least you'll know exactly what MM is sending to the server.

**Comment by MattHoneycutt** [comment]
Thanks for responding so quickly!  I've got the new version downloaded.  I'll try a test post tomorrow and see what happens.

**Comment by RickStrahl** [comment]
The binaries haven't been updated yet - only the source. I'll push out a new version in a few days. Watch for 1.94 or later.

**Comment by RickStrahl** [comment]
1.9.4 is out.

FWIW you should be able to try this out by  republishing. Try this:

* Open your post
* Open the Weblog Publishing Window
* Save Meta Data
* Exit that Window
* Edit the Meta Data postDate
* Re-open the Weblog Publishing Window
* Publish

Whatever the date is in the meta data should show up in Wordpress. At least that's what I see with the actual Wordpress site.

**Comment by MattHoneycutt** [comment]
I can't reproduce the issue now with the latest version.  I promise I had it happen to me multiple times before, I'm not crazy!  

I think it's safe to close this out.  I'll keep an eye on things, and if I see it happen again, I'll try to figure out a reliable set of reproduction steps.

Thanks!

**Comment by RickStrahl** [comment]
Well the latest version made a change that for sure uses the current date and then persists that date, so this should definitely fix whatever weirdness might have gone on before although I'm not sure what would have caused an arbitrary date to be used (unless it was in the meta data).

Now the date is explicitly in the meta data so you should always be able to see what the date is and if it's not right - change it and republish.
