### ISSUE TITLE
TOC Issue 

### ISSUE THREAD

**Issue by HowardEdidin** [RickStrahl/MarkdownMonster#324]
[Azure Cosmos DB Administration Essentials.zip](https://github.com/RickStrahl/MarkdownMonster/files/1729730/Azure.Cosmos.DB.Administration.Essentials.zip)

External links work, but the Links generated by the TOC add-in do not work.

**Comment by RickStrahl** [comment]
Oh Ok. 

You need to post that in the TOC addin repostitory. I don't own that addin - it's provided by a third party.

https://github.com/DVaughan/MarkdownMonster-Addin-TocGenerator/issues

**Comment by RickStrahl** [comment]
Taking a quick look I think the problem may simply be that you don't have the `AutoHeaderIdentifiers` flag enabled in the Settings file. I think the Addin is supposed to set that but with that turned on it works for me .

```json
MarkdownOptions: {
 "AutoHeaderIdentifiers": true,
}
```
Beyond that though - please file any issues with the author of the addin.
