### ISSUE TITLE
TOC as regular menu

### ISSUE THREAD

**Issue by Herby007** [RickStrahl/MarkdownMonster#325]
Most Markdown editors like Ulysses, Typora, Write! and so on offers a little TOC menu which is very comfortable. I know there is a plugin for MarkdownMonster - but this generates text in the preview. 
In my opinion it is much better to have a little pull down menu or so to direct in the editor to jump to the next section. #

**Comment by RickStrahl** [comment]
Yeah I've actually thought about that at some point. Now with improved support for multiple sidebar panes this might easier to add to the UI.

**Comment by Herby007** [comment]
Wow! Very fast answer!!! Like MardownMonster very much. Tested a lot Windows MarkdownEditors.
Not so important but nice to have
- spellcheck for German (per example with the Huffspell dictionaries)
- a editor theme which is mor "distraction free" (I now the distraction free button in the upper right corner). This means: not so colorfull, no 3D button - more the design of Writer! app per example ...

**Comment by Paulix** [comment]
Thumbs up for concept #2 (TOC document outline that lets you navigate the document in the editor.) 

If that is available, I will buy a licence  ;-) :-)

**Comment by RickStrahl** [comment]
So work has been done for getting a first cut of a document outline into MM.  Here's what it looks like now:

![image](https://user-images.githubusercontent.com/1374013/37550274-684703b6-292e-11e8-9ef3-c8d97dab92ef.png)

It'll go into a preview build (on the download page) later tonight.

**Comment by Paulix** [comment]
Perfectly, Then, there is nothing no more, what I'm missing. Thanks a lot.

Your mm has a great future.

**Comment by RickStrahl** [comment]
So this feature has been added and is now available (as preview for now) in Markdown Monster:

![image](https://user-images.githubusercontent.com/1374013/37641553-42eb45b8-2bbe-11e8-9119-c311e58fa08b.png)

To enable this for now you need to:

* Go to **View -> Document Outline**
* Click to check/uncheck the viewer
* Make sure the side bar is open
* Select the Outline tab on the bottom

When checked the Outline tab becomes available on the sidebar on the right - it's not visible for non-markdown windows.

Features:

* Shows document outline in real-time as you type
* Keeps in sync as you move through the editor
* Click on an item to navigate
* Button to create a TOC to embed into the document
