### ISSUE TITLE
Can't install Kava Docs add-on - needs version 1.9.6

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#327]
I see Kava Docs add-on as being available, but installs only over MM 1.9.6 that nowhere to be found
![image](https://user-images.githubusercontent.com/701808/36770078-2b66aade-1c16-11e8-9620-1b52649bedf8.png)

**Comment by RickStrahl** [comment]
You can get the latest preview release but the addin is internal so even if you get I t it’s probably not very useful to you at this point.
