### ISSUE TITLE
Crash at startup on new 0.57 version

### ISSUE THREAD

**Issue by weggetor** [RickStrahl/MarkdownMonster#33]
Hi Rick,
program crashes at startup now. Windows-Eventlog:

Anwendung: MarkdownMonster.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.IO.IOException
   bei System.IO.__Error.WinIOError(Int32, System.String)
   bei System.IO.Directory.DeleteHelper(System.String, System.String, Boolean, Boolean)
   bei System.IO.Directory.Delete(System.String, System.String, Boolean, Boolean)
   bei MarkdownMonster.ApplicationConfiguration..ctor()
   bei MarkdownMonster.mmApp..cctor()

Ausnahmeinformationen: System.TypeInitializationException
   bei MarkdownMonster.mmApp.get_Configuration()
   bei MarkdownMonster.App..ctor()
   bei MarkdownMonster.App.Main()

I tried to uninstall completely and had some trouble with glyphicons-halflings.ttf which was blocked by Windows but finally I solved this so no settings in AppData and no files in "Program Files" were left. Then fresh install but that does not solve the crash issue. So I leave it up to you

**Comment by RickStrahl** [comment]
Hmmm... Theres been a change to rename the `%AppData%\West Wind Markdown Monster` to `%appdata%\Markdown Monster` for consistency across the various folder names. I wonder why the delete of the folder would fail - should have full permissions in that folder.

Anyway - I've added a Try/Catch block around that code and I'm logging it out now to see if it happens elsewhere.

The downloads been updated.

**Comment by weggetor** [comment]
Still crashes:

Anwendung: MarkdownMonster.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.NullReferenceException
   bei MarkdownMonster.mmApp.Log(System.String, System.Exception)
   bei MarkdownMonster.ApplicationConfiguration..ctor()
   bei MarkdownMonster.mmApp..cctor()

Ausnahmeinformationen: System.TypeInitializationException
   bei MarkdownMonster.mmApp.get_Configuration()
   bei MarkdownMonster.App..ctor()
   bei MarkdownMonster.App.Main()

**Comment by RickStrahl** [comment]
Hmmm... where are you installing from? The Chocolatey package has not been updated - the main download link here:

https://markdownmonster.west-wind.com/download.aspx

has the latest (0.57.2)

I can't duplicate the failure and I've updated a few different machines.

Also looks like the crash is not getting into the log and forwarding to the bug logging service. Is the crash getting to the error dialog or is it hard crashing the application (ie. straight into the Windows error dialog).

if you still have problems  you can try this: Delete or rename the %appdata%\West Wind Markdown Monster folder if you have it and (optionally) manually copy the content into your %appdata%\Markdown Monster folder.

If there is still a problem though I'd love to find out what's causing it - cause a startup crash really sucks...

**Comment by weggetor** [comment]
Was the newest version, but manually renaming the "West Wind Markdown Monster" folder did the job - no more exceptions and the others isues are also gone. Search & Replace is working and downloading post from my blog with special chars in password works again also. Good job Rick and thank you for your help!

**Comment by RickStrahl** [comment]
What does the version number show for you? It should 0.57.2

Yeah that is really odd - the code that deals with the 'update' moving of the old settings files is fenced inside of a try/catch (after your initial report) so that shouldn't trigger an exception worst case it should just fail and continue (but create a log entry).  I really would love to find out why that was failing. Was there any more info in the log file (like line numbers after the second error you sent?)
