### ISSUE TITLE
Document shows changed asterisk when there's been no change.

### ISSUE THREAD

**Issue by bladewolf55** [RickStrahl/MarkdownMonster#335]
## Description
A document can easily be fooled into thinking there's a change (requiring save) when there's been no change.

## Steps to Reproduce
1. Install MM
2. Open, the SampleMarkdown will display
3. Ensure editor window does _not_ display the entire document.
4. CTRL-HOME. The document will gain an asterisk indicating it's been changed, and prompt to save.

## More Information
I discovered this when documenting reproduction steps for my previous issue.

**Comment by RickStrahl** [comment]
i think this might related to the #332 where the document changes linefeed settings on initial navigation.

What happens if you save the document, exit and restart? I bet you then won't see the changes as the new linefeeds settings match the saved file on disk.

**Comment by bladewolf55** [comment]
That might have been true. I just installed the latest version and it seems
both issues are fixed. Woo hoo! I think the new cursor behavior is a much
nicer experience. Clever solution!




--
Charles L Flatt
513-535-0764 (m)

"I believe in those whom I love and trust. All else is foolishness."
--Roland, The Book of Lost Things

**Comment by bladewolf55** [comment]
There is one small issue with the new version: If my cursor is at the
bottom of the page, and I paste a block of text, the editor window doesn't
scroll to the new cursor position.  But it's not major. Thanks for such a
quick response. Aloha!


--
Charles L Flatt
513-535-0764 (m)

"I believe in those whom I love and trust. All else is foolishness."
--Roland, The Book of Lost Things

**Comment by RickStrahl** [comment]
Hmmm... yes I think this is actually a problem if you paste text near the bottom of the view. The paste causes the editor to scroll, which in turn causes the scroll logic to kick in. The scroll moves the display down a couple of lines to force the active text into view.

Argh... scroll and scroll sync is easily one of the trickiest pieces in MM - so many unexpected side behaviors.

**Comment by RickStrahl** [comment]
Closing since the original issue of unintended doc dirty flag was related to CRLF conversions.

**Comment by RickStrahl** [comment]
Also fixed the end of document/viewport pasting issue.

3ea7d7458fffb27c3baa100bc11d7c4cb7b79577

**Comment by bladewolf55** [comment]
Dude, you are on fire!

I just installed, looks good. And this also fixed a bug where opening
documents by double-clicking the file was failing.

Thanks, Rick.


--
Charles L Flatt
513-535-0764 (m)

"I believe in those whom I love and trust. All else is foolishness."
--Roland, The Book of Lost Things

**Comment by RickStrahl** [comment]
Yeah the last update ripped a lot of the innards of MM out and replaced it with a more flexible layout and better bindings to manage all that. But there were a few side effects - specifically timing errors when loading and things not being available. It's been a day of fighting fires :-)

But things look good now in 1.9.16 I think. There probably will be another update tonight with a build in TOC generator option from the new Document Outline window.
