### ISSUE TITLE
Chinese IME weird effect

### ISSUE THREAD

**Issue by kkbruce** [RickStrahl/MarkdownMonster#337]
Weird effect that hurts eyes during Chinese input method composition

This is friend feedback https://www.youtube.com/watch?v=PuH9p7nTDfs&feature=youtu.be

**Comment by kkbruce** [comment]
We try Chrome, Firefox, Edge to load MM Ace Editor, Chinese IME is work, but IE very bad.
.NET Framework WPF WebBrowser Control default use IE render engine. 
We don't have any idea to change render engine. :-(

**Comment by RickStrahl** [comment]
Thanks @nightwing,

I'm not sure I understand how this affects the render layout of word wrapping in the editor? Can you explain how background and color would affect the word wrapping behavior?

Either way gave this a shot and and added it to the stylesheet we use for ACE and I don't see a difference in the rendering - as before for me the breaks render **eventually** but at much wider widths than adequate between non-chinese symbols.

I also see this failing both in Markdown Monster (IE Hosted), IE as well as Chrome. In all places I pretty much see the same behavior (with the suggested CSS style applied although that seems to make no difference):

Here's inside of MM:

![image](https://user-images.githubusercontent.com/1374013/38215918-eb2dfb84-3664-11e8-80ad-e999ddbd905a.png)

For reference the preview shows what we probably should also be seeing in the editor in terms of wrapping.

Here's Chrome:

![image](https://user-images.githubusercontent.com/1374013/38216008-2abbf756-3665-11e8-9ce3-bb6dc9e2f1fd.png)

It seems that this is not isolated to IE...

**Comment by RickStrahl** [comment]
Did @nightwing's fix for this work for you? I don't have a good way of testing this since I don't have Chinese character sets installed.

ajaxorg/ace#3622

**Comment by RickStrahl** [comment]
I'm going to close this since there is no follow up and this is really more of an Ace issue. If there's any additional info that is actionable here feel free to re-open this issue.

**Comment by RickStrahl** [comment]
Any chance you can check on this again with recent updates from ACE Editor? Version 1.12.12 is up to 1.40 of ACE editor which supposedly has a number of fixes around Asian language display.

**Comment by kkbruce** [comment]
I try three Chinese IME, feel is very good.

![MM Chinese IME Test](https://www.screencast.com/t/H5ZZuL5xW3)

I can finally promote MM for Chinese world.
