### ISSUE TITLE
Document links contain backslashes instead of forward slashes.

### ISSUE THREAD

**Issue by tbleken** [RickStrahl/MarkdownMonster#343]
This is the steps to reproduce : 
1. Open an existing md file, and press ctrl-k.
2. Press the ... to browse for files to link to
3. Select a subfolder, and click a file
4. Press Open,  
Now the link will have backlash(es) instead of forward slash(es).

**Comment by RickStrahl** [comment]
Fixed: 05ec6b0b8e117acf27ec2c905625cb945bbf6ba1
