### ISSUE TITLE
Add-in Load Failure stops all Addins from Loading

### ISSUE THREAD

**Issue by HowardEdidin** [RickStrahl/MarkdownMonster#345]
This happens sporadically 

![image](https://user-images.githubusercontent.com/19954905/38199555-c4b6feaa-3656-11e8-951a-e8953197da0a.png)

[MarkdownMonster.json.txt](https://github.com/RickStrahl/MarkdownMonster/files/1868281/MarkdownMonster.json.txt)

**Comment by RickStrahl** [comment]
This can happen if an addin fails to load. 

There should be more info in the error log **Help->Error Log**. I suspect it's the Kavadocs addin if you have that loaded. 

There should be better handling of this and we  do capture addin-failures internally, but somehow it bumps out of the whole addin processing loop and ends up installing none of hte addins.

**Comment by RickStrahl** [comment]
This should be fixed in 1.10.4 and later.
