### ISSUE TITLE
Feature  -Post to GitHub  

### ISSUE THREAD

**Issue by HowardEdidin** [RickStrahl/MarkdownMonster#346]
Would you find an add-in for posting to a GitHub Repository and Wiki beneficial?

**Comment by RickStrahl** [comment]
I'll be adding some additional Git functionality soon - it depends on what you want to build exactly whether it provides worthwhile value beyond the simple functionality I plan to add. 

Here's what we got:

MM already supports posting existing files to Github **Tools -> Commit and Push To Git** (alt-t-g) which works for files that are already under Git control.  

Here's what I want to add:

I want to expand that behavior to allow adding files to Git, and also optionally committing all changes. I also want to get display file change status in the folder browser. All this means integration with Lib2Git - currently MM just shells out to Git so there's not much control over the process.

**Comment by HowardEdidin** [comment]
I was thinking about publish to repository.




Howard S. Edidin  MCTS, MCP, Author, Trainer, TechNet Wiki Ninja
Senior Integrations and Cloud Architect – Healthcare and Life Sciences

[MVP_Logo_Horizontal_Preferred_Cyan300_CMYK_72ppi]
Microsoft Cosmos DB MVP
Microsoft Virtual Technical Specialist(P-TSP) Cosmos DB, Azure
Microsoft Azure Advisory Group
Azure DocumentDB Wizard

hedidin@edidingroup.com

[btn_viewmy_120x24]<http://www.linkedin.com/in/hedidin>

       [hl7 for biztalk small] <http://www.amazon.com/HL7-for-BizTalk/dp/143026764X/ref=sr_1_1?ie=UTF8&qid=1404753916&sr=8-1&keywords=HL7+for+BizTalk>

O: 224-360-3200
F: 847-816-8995
[Colorlogo-thumbs]<hhttp://www.hl7.org/>HL7 Gold Member

_______________________________________________________________________________
Disclaimer: This email and any attachments are sent in strictest confidence for the sole use of the addressee and may contain legally privileged, confidential, and proprietary data. If you are not the intended recipient, please advise the sender by replying promptly to this email and then delete and destroy this email and any attachments without any further use, copying or forwarding

**Comment by RickStrahl** [comment]
Can you be a little more specific? These one-liners are not very helpful...

**Comment by HowardEdidin** [comment]
Version 1.0.0


Configuration:

  1.  GitHub Log in – store credentials encrypted


The extension would do the following:

  1.  Select a Repository
  2.  (optional) Select a folder
  3.  Publish md document to a GitHub Repository (overwrite flag)






Extensibility:
These would be additional operations in Version 2.0.0

  1.  Download existing md documents from a GitHub Repository
  2.  Create new folder and Publish md document to folder
  3.  Publish md document to a GitHub Repository (overwrite flag) Wiki
     *   Requires Wiki to be created first




Howard S. Edidin  MCTS, MCP, Author, Trainer, TechNet Wiki Ninja
Senior Integrations and Cloud Architect – Healthcare and Life Sciences

[MVP_Logo_Horizontal_Preferred_Cyan300_CMYK_72ppi]
Microsoft Cosmos DB MVP
Microsoft Virtual Technical Specialist(P-TSP) Cosmos DB, Azure
Microsoft Azure Advisory Group
Azure DocumentDB Wizard

hedidin@edidingroup.com<mailto:hedidin@edidingroup.com>

[btn_viewmy_120x24]<http://www.linkedin.com/in/hedidin>

       [hl7 for biztalk small] <http://www.amazon.com/HL7-for-BizTalk/dp/143026764X/ref=sr_1_1?ie=UTF8&qid=1404753916&sr=8-1&keywords=HL7+for+BizTalk>

O: 224-360-3200
F: 847-816-8995
[Colorlogo-thumbs]<hhttp://www.hl7.org/>HL7 Gold Member

_______________________________________________________________________________
Disclaimer: This email and any attachments are sent in strictest confidence for the sole use of the addressee and may contain legally privileged, confidential, and proprietary data. If you are not the intended recipient, please advise the sender by replying promptly to this email and then delete and destroy this email and any attachments without any further use, copying or forwarding

**Comment by RickStrahl** [comment]
Hmmm... this all sounds kind of backwards to me. 

The normal Git workflow for this more likely is that you have a Github repo already then clone that down and edit/add files in that repo. At that point the current Git behavior allows publishing files already.

And why would you 'download' anything from a Github repo when you normally clone the repo and work with local files until you commit and push?

I'm going to close this seems to me would be better handled by integrated Git support which is already on the future todo list in #313.

If you think you have a unique use case where you really need to explicitly copy files to and from Git Repositories outside of Cloning, then an Add-in is something that lets you do this.
