### ISSUE TITLE
Long single string code snippets do not render correctly when exported to pdf

### ISSUE THREAD

**Issue by heydojo** [RickStrahl/MarkdownMonster#348]
**The issue**

Single line code snippets break when exported to pdf.

**How to reproduce the issue**

Add the following to a markdown document using either an inline code tag or a regular code tag:

> cmake -G "Visual Studio 15 2017 Win64" -DGLIBCONF_DIR:PATH=%CD%/vcpkg/packages/glib_x64-windows/include -DGLIBH_DIR:PATH=%CD%/vcpkg/packages/glib_x64-windows/include -DGLIB_LIB:FILEPATH=%CD%/vcpkg/packages/glib_x64-windows/lib/glib-2.0.lib -DGTHREAD_LIB:FILEPATH=%CD%/vcpkg/packages/glib_x64-windows/lib/gthread-2.0.lib -Denable-aufile=true -Denable-dbus=false -Denable-debug=false -Denable-floats=false -Denable-fpe-check=false -Denable-ipv6=true -Denable-jack=false -Denable-ladspa=false -Denable-libsndfile=true -Denable-midishare=true -Denable-pkgconfig=false -Denable-portaudio=false -Denable-profiling=false -Denable-pulseaudio=false -Denable-readline=true -Denable-trap-on-fpe=false %CD%/fluidsynth-1.1.10/

(The command is all one line and it is inside a quote tag in this report so that it can be copied and pasted for testing.)

Next, export a landscape pdf document with a 5px margin and no table of contents.

**Expected behaviour**

The code block appears in the pdf as:

```
cmake -G "Visual Studio 15 2017 Win64" -DGLIBCONF_DIR:PATH=%CD%/vcpkg/packages/glib_x64-windows/include -DGLIBH_DIR:PATH=%CD%/vcpkg/packages/glib_x64-windows/include -DGLIB_LIB:FILEPATH=%CD%/vcpkg/packages/glib_x64-windows/lib/glib-2.0.lib -DGTHREAD_LIB:FILEPATH=%CD%/vcpkg/packages/glib_x64-windows/lib/gthread-2.0.lib -Denable-aufile=true -Denable-dbus=false -Denable-debug=false -Denable-floats=false -Denable-fpe-check=false -Denable-ipv6=true -Denable-jack=false -Denable-ladspa=false -Denable-libsndfile=true -Denable-midishare=true -Denable-pkgconfig=false -Denable-portaudio=false -Denable-profiling=false -Denable-pulseaudio=false -Denable-readline=true -Denable-trap-on-fpe=false %CD%/fluidsynth-1.1.10/
```
or as:

```cmake -G "Visual Studio 15 2017 Win64" -DGLIBCONF_DIR:PATH=%CD%/vcpkg/packages/glib_x64-windows/include -DGLIBH_DIR:PATH=%CD%/vcpkg/packages/glib_x64-windows/include -DGLIB_LIB:FILEPATH=%CD%/vcpkg/packages/glib_x64-windows/lib/glib-2.0.lib -DGTHREAD_LIB:FILEPATH=%CD%/vcpkg/packages/glib_x64-windows/lib/gthread-2.0.lib -Denable-aufile=true -Denable-dbus=false -Denable-debug=false -Denable-floats=false -Denable-fpe-check=false -Denable-ipv6=true -Denable-jack=false -Denable-ladspa=false -Denable-libsndfile=true -Denable-midishare=true -Denable-pkgconfig=false -Denable-portaudio=false -Denable-profiling=false -Denable-pulseaudio=false -Denable-readline=true -Denable-trap-on-fpe=false %CD%/fluidsynth-1.1.10/```

**Actual behaviour**

The code block spans off the page and does not wrap. The contents of the code block are obscured by formatting.
An inline code block will not scroll to reveal the contents of the code tag.

**Summary**
It is really nice the way Markdown Monster picks up the formatting in the preview but when exported to pdf, the output of the code block is broken.

The exported pdf was viewed using both Chrome and Firefox. The issue can be reproduced in either application.

**Comment by RickStrahl** [comment]
Thanks for pointing that out. 

I added a  `@media print {}` style to set the word wrapping for all the style sheets that should address this. It'll be in the next update.

![image](https://user-images.githubusercontent.com/1374013/38782730-9178e282-4093-11e8-8c1c-3927cadbeed5.png)

For now you can use in the PreviewWindow use the right click menu to **Edit Preview Theme** then edit the CSS file and at the very end add:

```css
/* for PDF generation and print output */
@media print
{
    pre{
        white-space: pre-wrap;
        word-break: normal;
        word-wrap: normal;
    }
    pre>code {
        white-space: pre-wrap;
        padding: 1em !important;
    }
}
```

**Comment by heydojo** [comment]
Glad you got it fixed.
