### ISSUE TITLE
can't type korean fastly

### ISSUE THREAD

**Issue by tbop02** [RickStrahl/MarkdownMonster#349]
I am Korean user. this tool is awesome but It seems like doesn't support Korean typing well.

**Comment by tbop02** [comment]
Korean one word consist of at least 2 single character, vowol and consonant. They have to be combined when typing. But in this program characters just are separated like english. Its so weird.

I know it might be hard for English speakers to understand what i mean. But learning korean character is so easy if u see you tube video, Clever man can learn within 1hour. I recommend you to learn korean quickly if u have 1 hour.

This program is awesome except for this big issue. I hope it is fixwd

**Comment by RickStrahl** [comment]
Any chance you can check on this again with recent updates from ACE Editor? Version 1.12.12 is up to 1.40 of ACE editor which supposedly has a number of fixes around Asian language display.

**Comment by kkbruce** [comment]
I try #336 , ACE 1.40 doesn't seem to contain the  https://github.com/ajaxorg/ace/pull/3725 PR code.

**Comment by RickStrahl** [comment]
Since I haven't heard back on this I'm going to close this out - if there is additional information please feel free to open this issue back up.
