### ISSUE TITLE
Invalid License data during splash screen causes a crash.

### ISSUE THREAD

**Issue by daronyondem** [RickStrahl/MarkdownMonster#35]
I had the app installed by downloading the setup package. I uninstalled it. This time around I used Chocolaty to install it. When I ran it for the first time the app crashed.

![image](https://cloud.githubusercontent.com/assets/2984187/19920326/c21d7564-a0e0-11e6-8391-a9d811da7a13.png)

I can e-mail the memory dump if needed.

When I tried to debug below is the error I caught. 

![image](https://cloud.githubusercontent.com/assets/2984187/19920260/56863cfa-a0e0-11e6-802b-07fe76a71644.png)

It might be nice to ask for a new key when the current is somehow not working. Tough I'm not sure why my key would not work :(

**Comment by RickStrahl** [comment]
Thank you for the PR in #36. 

For more info please see that issue for the fix.
