### ISSUE TITLE
Crash on "Copy Markdown as HTML"

### ISSUE THREAD

**Issue by shawnwildermuth** [RickStrahl/MarkdownMonster#351]
I have a simple Markdown file (about 30 lines) that I want to copy to HTML (I like creating my emails for MailChimp in markdown then copy as HTML to paste it in their editor). When I try with 1.10.7 and 1.10.11 I get this error:

![image](https://user-images.githubusercontent.com/568272/39352949-44cb70d6-49d4-11e8-8a9a-31a92d20ffd9.png)

Ideas?

**Comment by RickStrahl** [comment]
Hmmm... not sure. 

Just tried here and I run into no issues. At first I thought this might be an issue with Administrative accounts - some operations like drag and drop from external and pasting from clipboard don't work, but I also tried running as Admin and not seeing the issue even in Admin mode.

It certainly looks like a security error of some sort...

**Comment by shawnwildermuth** [comment]
I am on a later version of Windows than you are (early access):

![image](https://user-images.githubusercontent.com/568272/39389523-57759fee-4a57-11e8-9c08-5c18598109b8.png)

Maybe this version will help. Any way to turn on verbose logging without building the app so I can give that to you?

**Comment by RickStrahl** [comment]
Shawn,

I'm pretty sure I know what line is causing the problem -  It's the call the Clipboard.SetData() that's failing:

![image](https://user-images.githubusercontent.com/1374013/39390396-dea2f7e6-4a48-11e8-98d0-df73af208153.png)

I added the exception handling now so at least this error doesn't blow you out of MM completely.

I still think the error is permissions related - maybe there's some policy change in the Windows update that restricts clipboard access in certain scenarios? What location are you running from?

**Comment by shawnwildermuth** [comment]
After an update to the OS and a reboot, seems to be working. Probably a wonky Win build. Sorry to waste your time. (Didn't update it yet)

**Comment by RickStrahl** [comment]
FWIW I see a few of these errors in the logs, so this is not an uncommon problem. But no idea where it's coming from...

IAC, there are few improvements around that particular issue that at least now won't crash MM. 

Thanks...
