### ISSUE TITLE
Improvement: bullet item iteraction with HOME, TAB, BACKSPACE and CTRL keys

### ISSUE THREAD

**Issue by alexaraujo** [RickStrahl/MarkdownMonster#354]
Just a few suggestions, in the same vein on how popular text editors (Google Docs, Word, etc) operates with bullets. They are nice to have since they improve usability by offering a well known experience to the user.

**A - Bullet item and HOME key**

_Once a bulleted item is inserted if you press the HOME key, the cursor don't move to the beginning of the line, but sits between the bullet and the text._ 

In these editors, a bullet seems as a special case: if there is a bullet in a line, it is the bullet that defines what consitute the beginning of the line. 

Yeah, that sounds a bit confusing I know. Just experiment with that in Google Doc and Word and you'll see what I'm talking about. This seems to be an important behavior for some of the remaining suggestions.

**B - Bulet item and TAB key**

_If you insert a new empty bullet item and press the TAB key, the bullet is indented to the right._

1. Press asterisk + space bar to initiate a bulleted list
2. Don't type any text, just press the TAB key: the bullet will move to the right
3. Press SHIFT+TAB and the bullet will move to the left

The same happens event if there is already some text on the bulleted item:

1. Press asterisk + space bar to initiate a bulleted list
2. Type some text and press HOME (notice the cursor don't move to the beginning of the line, but to a point between the bullet item and the text)
3. Press TAB key: the bullet and the text will move to the right
4. Press SHIFT+TAB to move the bullet and the text to the left

**D - Bullet item and Backspace**

_After moving to the beginning of the text in a bulleted item, if you press the backspace key the bullet is deleted._

1. Press asterisk + space bar to initiate a bulleted list
2. Type some text and press HOME: cursor move to a point between bullet and text
3. Type BACKSPACE: the bullet is immediately deleted

**E - Bullet item and CTRL + BACKSPACE**

_CTRL + BACKSPACE ignores single space._

Ctrl + backspace is a nice keystroke for deleting an entire word from a line. Normally this keystroke ignore single empty spaces:

1. Type some text, let's say *linus torvalds*
2. Press CTRL + BACKSPACE to delete *torvalds*.
3. Press CTRL + BACKSPACE to delete *linus*

That is not the case with Markdown Monster editor. It requires now two but three keystrokes in order to  delete _linus torvalds_:

1. Type *linus torvalds*
2. Press CTRL + BACKSPACE to delete *torvalds*
3. Press CTRL + BACKSPACE again and it will delete the single space that sits between *linus* and *torvalds*
4. Press CTRL + BACKSPACE one more time to delete *linus*

Now let's see what happens in popular text editors when CTRL + BACKSPACE is pressed in a bulleted item:

1. Press asterisk + space bar to initiate a bulleted list
2. Type a single word and, press CTRL + BACKSPACE to delete this word
3. Press CTRL + BACKSPACE again and the bullet will be deleted. 

As seen, just two keystrokes were needed to eliminate the entire line. Compare this to the editor behind Monster Markdown which requires three keystrokes to do the same task: the 1st keystroke to get rid of the _word_, the 2nd to get rid of the _space_ and the 3rd to get rid of the _bullet_.

**Comment by alexaraujo** [comment]
Oh, forgot to say sorry for typing so much!!! I know it sucks to read so long posts. I just tought it would be better to expose the complete picture so you can be in a better position to evaluate all the complexity involved and plan accordingly or just discard it as impractical. Thanks anyway for doing a great job in Monster Markdown. It is definitely the best markdown editor.

**Comment by alexaraujo** [comment]
Got it, thanks! I have no hope to see these behaviors being implemented in ACE editor since it has been around for so long that it would have a big impact in the way people use it and it certainly would broke some people heart.

Anyway, this doesn't seems to be strictly tied to the Markdown mode in ACE editor, but something that permeates every other mode since all of them shows the same behavior regarding bullets and keystrokes like those discussed before. Probably it is something at the editor's core. 

Eventually the way to go is by implementing or overridden some function in mode-markdown.js? Or implementing an extension? I'm not sure. I am still trying to understand ACE editor architecture...

So I spent some time looking at the ACE source code and I found an interesting property named _selectLongWords_. It enables the ACE editor to deal with spaces in a different way and allow us to get a little more closer to the previous discussed behaviors regarding CTRL-BACKSPACE. 

I changed editor.js in Markdown Monster, function configureAceEditor(), line 45 as follow;

```
var session = editor.getSession()
editor.session.$selectLongWords = true;
editor.setReadOnly(false);
...
```

Now if you type a few words and press CTRL-BACKSPACE it ignores any single space between words, which is good! Unfortunately it is not without problems:

1. Type some word and press ENTER
2. Start a bullet item (asterisk) and press CTRL-BACKSPACE

It delete the bullet... and also the word above it! That is a problem. 

It happens even without bullets, just words in different lines. And it also happens with some other shortcuts like CTRL-LEFT, CTRL-RIGHT, CTRL-SHIFT-RIGHT and CTRL-SHIFT-LEFT. They all act correctly until a point: the END-OF-LINE

So it seems ACE editor has some problems dealing with END-OF-LINE characters like \r or \n, at least with regard to the mentioned shortcuts. Maybe something that happens in Windows OS only, since it uses \r\n as end-of-line code, which is weird. Or maybe this is something that requires some other property to be set in the editor. I am not sure yet specially because I am not that good with javascript. 

I'm now inspecting ace/selection.js, specifically the functions moveCursorLongWordLeft() and moveCursorLongWordRight(), trying to figure out what it does and why it does that way. If you have some tips/hints on how to quickly setup a debug for this thing, it would be much appreciate!

**Comment by RickStrahl** [comment]
Alex,

Yeah the mode-markdown.js is amongst the most complicated syntaxes because it includes embedded support for HTML, CSS, JS, XML so it's a huge syntax file. I've built syntax files myself and it's relatively easy for single languages but in this mixed mode it's very difficult to even find where the base Markdown handling is managed. I suspect the bullet behavior is actually contained in the snippets not the language bit.

**Comment by RickStrahl** [comment]
Alex I'm going to close this, here since what we're dealing with are ACE Editor features that can be better handled in the ACE Editor issues. 

If you end up reporting issues with ACE, maybe link them back to this issue with a comment and link reference.
