### ISSUE TITLE
Critical Bug: Folder Browser allows creation of duplicate file names and overwites existing file without a notice

### ISSUE THREAD

**Issue by alexaraujo** [RickStrahl/MarkdownMonster#355]
1. Using the Folder Browser, create a new file. Let's call it _file1.md_.
2. Type some text in this file and save it.
3. Go back to the Folder Browser and create a new file with the exact same name as the previous one: _file1.md_.
4. Folder Browser now list two _file1.md_ even though there is only one in the disk.
5. From this point, whatever _file1.md_ you attempt to open will come completely blank, empty, with no previous typed text. Same with _file1.md_ in the disk: content was eliminated. Folder Browser simply replaced the previously created _file1.md_ without any notice.

**Comment by RickStrahl** [comment]
Thanks for this. Fixed by checking file existance first and clearing entered text and displaying a statusbar warning.
