### ISSUE TITLE
In EDITOR, when writing numbered list, please add configuration to disable auto-increment.

### ISSUE THREAD

**Issue by skleanthous** [RickStrahl/MarkdownMonster#357]
Please see:
![explanationofproblem](https://user-images.githubusercontent.com/8543464/39618035-e74dfc5c-4f79-11e8-93ee-91f9cebadb76.jpg)

Also, just to demonstrate see below gif:
![ezgif com-crop](https://user-images.githubusercontent.com/8543464/39618077-f47cae32-4f79-11e8-99b3-ed50e0775281.gif)

This relates to closed issue #356 which I agree I did not explain properly. I would _really_ love the option to not autoincrement in editor. It is very often that I type out ideas when brainstorming and autoincrementing in the editor results in very weird and nonsenical numbers, again in the editor. Result is fine.

To repeat again, I would like to have an option similar to what exists in Atom to stop autoincrementing the numbers when in editor and just keep it at number 1. I know it's a small point, but it becomes confusing far when some lists in editor are OK and other are not, and it breaks my mental flow to manually go back and change numbers to 1.

**Comment by skleanthous** [comment]
Seeing as there was responce on original issue, I'll close this one.

**Comment by RickStrahl** [comment]
Reopening since this issue is clearer on what's actually happening :-)

I've added conditional switch to enable the 'not-so-smart' autocomplete behavior. It is now OFF by default (ie. no bullet auto-completion).

db0c4c7ca9753641a25166e6ffdfd776684cec6c

**Comment by skleanthous** [comment]
@RickStrahl this works very nicely for me tbh. I do prefer to type it out over having it autocomplete. Feel free to close the ticket if you're happy with it, and awesome turnaround for resolution! 👍
