### ISSUE TITLE
Clone Git Repository issue when Folder doesn't exist

### ISSUE THREAD

**Issue by HowardEdidin** [RickStrahl/MarkdownMonster#360]
![image](https://user-images.githubusercontent.com/19954905/39650894-7a6c8230-4faf-11e8-8ef2-b024e6a07d9a.png)

**Comment by RickStrahl** [comment]
Again - why the heck can't you provide some context?

It works fine if you use a valid path, but it fails with the error you specify if the folder doesn't exist.

**Comment by HowardEdidin** [comment]
Look at the time the folder was created

![2018-05-04_16-16-22](https://user-images.githubusercontent.com/19954905/39653968-ab7c34d4-4fb8-11e8-8f7d-bfa1268b1052.png)

Look at the time I ran the app

![dsdsad](https://user-images.githubusercontent.com/19954905/39654048-014db496-4fb9-11e8-91a0-888015dd5c7b.png)

**Comment by RickStrahl** [comment]
Fixed. Command line needs to escape the path with spaces in it.  6e6854c

**Comment by HowardEdidin** [comment]
Version 1.10.16
