### ISSUE TITLE
Spell Check Context Menu Flickers On And Off Before Use

### ISSUE THREAD

**Issue by conradakunga** [RickStrahl/MarkdownMonster#361]
The context menu that suggests spelling corrections quickly appears and disappears, thus a user is unable to correct spelling errors.

Windows 10 Pro
Version	10.0.16299 Build 16299
8 GB RAM
.NET Framework 4.7.1

**Comment by RickStrahl** [comment]
Hmmmm... I can't duplicate that. Are you on a recent version? There were some changes around in 1.8 that changed the behavior by first forcing the cursor to the right click area. That said I can see this in some rare circumstances when right clicking really 'shallow'/fast.

I think the issue maybe alt click timings...

Can you try the following: Move the mouse over the text briefly before alt-clicking. Does that change the behavior? If that also doesn't work can you try using the Windows Context key (if you have one) which is on the right next to the alt key usually on full size keyboards just to confirm that the menu actually pops up.

**Comment by conradakunga** [comment]
I can confirm that the menu does, in fact, pop up. But it disappears almost immediately. 

Find attached a zip file of an MP4 outlining the experience.

If it sheds more light, the Windows 10 is a Virtual Machine running on OSX 10.13.4 via VMware Fusion 10.1.1

[MarkdownMonser.mp4.zip](https://github.com/RickStrahl/MarkdownMonster/files/1979510/MarkdownMonser.mp4.zip)

**Comment by RickStrahl** [comment]
I'm not sure I'm going to be able to do anything about this since this looks like a hardware timing issue. FWIW, I run MM under Parallels on OSx from time to time and it works there.

You can try setting off hardware accelleration in the app with this setting:

* [Turn of Hardware Assisted Rendering](https://markdownmonster.west-wind.com/docs/_4uj0kfglm.htm#Workaround:TurnoffHardwareAssistedRendering)

The issue described in the post is not relevant to you, but hardware accelleration on VM hardware can have some undesired timing effects. Give that a try.

**Comment by conradakunga** [comment]
Alas! This definitely does not address the issue. I guess this is one of those fringe cases that will be the very devil to reproduce.

Is this the built-in WPF spell check support?

**Comment by RickStrahl** [comment]
No - the editor is HTML based and it captures the right click and pushes the handling of the actual context menu to WPF. But the menu is popped up explicitly via code. 

Do other context menus work ok? In the Folder browser or over document tabs? Do those show Ok?

**Comment by conradakunga** [comment]
Everything else works brilliantly, in terms of context menus. Just the spell checking bit. Which forces me to copy and paste the text elsewhere for spell checking.

Perhaps it might be an idea to have a dedicated dialog that would not only sort my issue but also those who have  a workflow of typing first and editing later

**Comment by RickStrahl** [comment]
Unfortunately I don't know what else to suggest at this point. I can't duplicate this under any of the envrionments I run under including running under Parallels on the Mac. 

So this seems to be an issue with the VM hardware you're running under most likely. Maybe take a look at the mouse options in the VM - maybe there are some tweaks that allow slowing down clicks or how context menus are handled.

I'm going to close this, as there's nothing else I can think of what we can do here. Feel free to reopen if you find additional information that might help identify the issue. Thanks.
