### ISSUE TITLE
Sort the languages when embedding syntax coloured code

### ISSUE THREAD

**Issue by conradakunga** [RickStrahl/MarkdownMonster#362]
The dialog for editing & pasting code does not seem to list them in alphabetical order and it is difficult to use if you are not sure if the language you want is supported. And even if it is you need to cycle through using the keyboard. I would suggest this list be sorted

![sort](https://user-images.githubusercontent.com/1281845/39699743-234d3246-5203-11e8-92bd-dcf81b4bece8.png)

**Comment by RickStrahl** [comment]
Fixed in 662011d8ec64596325804e1d0446b7a286ef5fde
