### ISSUE TITLE
Cache the folder when browsing images to embed

### ISSUE THREAD

**Issue by conradakunga** [RickStrahl/MarkdownMonster#363]
The file dialog to embed images seems to always default to the directory of the active markdown document.

It becomes a bit tedious having to always navigate to the folder location if it is not in the root of the active markdown document.

Perhaps the file dialog could remember the last opened location?

**Comment by RickStrahl** [comment]
Hmmm... that should actually be happening.

Note you can also use the folder browser for this - open the folder browser in your target image path and then you can drag and drop the images into the document.

**Comment by RickStrahl** [comment]
After looking at the code I'm not actually sure if this should be changed. The code explicitly uses the current folder for images and only falls back to the last image location if there's no file open.

I think there are a multiple use cases for this.

1. If I'm writing a blog post I love the fact that I'm immediately in the right folder for my images. I hate having to first navigate BACK to this folder to now pick up my image.

2. When I'm writing docs (ie. many files) I probably do want to remember the last image folder. So I always land in the Images folder.

Not sure what the right choice is here.

Granted - I use the folder browser for this most of the time. I open my document, then use **Open Folder in Folder Browser** to open the document's folder and from there grab my images if they are external.

I think maybe given the ability to use the folder browser, remembering last image location is maybe the smarter choice.

**Comment by conradakunga** [comment]
Perhaps I can explain a bit better.

Given this folder structure; 

![screen shot 2018-05-07 at 21 35 41](https://user-images.githubusercontent.com/1281845/39718419-e75e7a56-523e-11e8-8a37-2f1ad37cc9f5.png)


the first time I invoke the browser it correctly starts at the root, (Chapter One) and I have to browse into Images to select the image, Image One.

If I later want to embed the second image, when I invoke the dialog it starts again at the root (Chapter One), and I have to open images again and then select the image I want.

Suppose the dialogue were to remember the fodler location of the last image embedded?

**Comment by RickStrahl** [comment]
Oh I understand...

I've switched the behavior to work with last remembered images. Lets see how that goes.

+++ Rick ---

**Comment by RickStrahl** [comment]
Fixed in 918034ec181e63a7e63877697ddbbb9bc086bc88
