### ISSUE TITLE
Any option to save several md-files as a single PDF or several HTML files with correct links?

### ISSUE THREAD

**Issue by Dennis-Petrov** [RickStrahl/MarkdownMonster#364]
Hi everyone.

I have a question about exporting as PDF/HTML.
Suppose there are 3 md-files in the same folder:

1) Test document:

```
# TestDocument

TOC:  
* [Chapter 1](Chapter-1.md)
* [Chapter 2](Chapter-2.md)
```

2) Chapter 1:

```
# Chapter 1

Text text text
```

3) Chapter 2:

```
# Chapter 2

Text 2 text 2 text 2
```

Is there any option option to save several files as a single PDF or several HTML files with correct links?
I've tried "Save as PDF" and "Save as HTML" commands, but their output is incorrect in this case - both commands generate links to  Chapter-1.md and Chapter-2.md. E.g., here is generated HTML:

```
<h1 id="testdocument">TestDocument</h1>
<p>TOC:</p>
<ul>
<li><a href="Chapter-1.md">Chapter 1</a></li>
<li><a href="Chapter-2.md">Chapter 2</a></li>
</ul>

```

Obviously, if one has such file structure, then he expects, that exported files will behave the same as they do inside editor. As it implemented now, export works correctly only when there are single file. But this is not a way to go with large documents, especially, when they being edited by a team.

**Comment by RickStrahl** [comment]
This is a bit beyond the scope of the editor. This is more project related. This gets into all sorts of crazy issues on what needs to be fixed up and how documents get combined. So I don't think this is something that should be implemented in the base editor.

However it could be handled by a custom addin that understands a 'project' structure  and knows what files belong to a project and know how to properly link other documents. 

I'm doing something like this in the KavaDocs addin (which is very rough at the moment) - unrelated to the PDF generation) Basically it has a concept of a project and so all links are under control of the rendering engine that everything runs through eventually for creating output.

IAC, I'm not inclined to provide this functionality unless somebody wants to tackle the logic for this and help out with it.
