### ISSUE TITLE
Setting to use system clipboard when in Vim mode

### ISSUE THREAD

**Issue by tethrbrian** [RickStrahl/MarkdownMonster#365]
I love that Vim mode is included by default! But if I want to copy something from MM to another application, I have to enter insert mode and use "Ctrl + C", rather than the Vim command "Y", which only allows pasting internally.

**Comment by RickStrahl** [comment]
Can you do me a favor and try this out on the ACE editor Kitchen Sink test page here:

https://ace.c9.io/build/kitchen-sink.html

Do you see the same behavior there?

**Comment by tethrbrian** [comment]
Ah, I didn't realize it was a third-party component. I'll bring it up over there. Thanks!
