### ISSUE TITLE
Minor Syntax highlighting issue

### ISSUE THREAD

**Issue by Philippe91** [RickStrahl/MarkdownMonster#366]
See the ! character:
![image](https://user-images.githubusercontent.com/8200618/39955354-d4a1f5c2-55cd-11e8-9a6a-a68d456aa108.png)

**Comment by RickStrahl** [comment]
The editor and syntax coloring is handled by ACE Editor and so I have little control over the rendering.

However I think the image rendering is actually consistent  across different markdown modes:

![image](https://user-images.githubusercontent.com/1374013/39971302-8a3054da-56ad-11e8-90fe-fde572ac3ea0.png)

IOW I think the way it renders is intensional.

If you feel you that this is not what you want can you can bring it up in the ACE Editor issues and see what they think on this particular rendering.

https://github.com/ajaxorg/ace/issues

Note that they are not super fast responding to syntax related issues. If you post there, please cross-link the new issue from here.

Thank you.

**Comment by RickStrahl** [comment]
Ok so I took a quick look and it looks like ACE is actually not explicitly highlighting images, but just highlighting links. I added the RegEx to handle images and with that it looks like this:

![image](https://user-images.githubusercontent.com/1374013/39971389-144a8266-56af-11e8-9140-25aa5b146f95.png)

It'll be in the next build but this needs to get back into  ACE.
