### ISSUE TITLE
DocFx Rendering for Note/Warning/Tip/Important/Caution

### ISSUE THREAD

**Issue by HowardEdidin** [RickStrahl/MarkdownMonster#367]
Can you provide support for the following?

> [!NOTE]
> <note content>
> [!WARNING]
> <warning content>
> [!TIP]
> [!IMPORTANT]

**Comment by RickStrahl** [comment]
Do you have a reference for these and how they are supposed to work?

**Comment by HowardEdidin** [comment]
https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html?tabs=tabid-1%<https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html?tabs=tabid-1%25>


Thanks,

Howard

**Comment by RickStrahl** [comment]
Added support for note boxes:

![image](https://user-images.githubusercontent.com/1374013/59550703-76ac6d00-8f09-11e9-9859-669542588a47.png)

Also refactored out all DocFx related processing into a [DocFxRenderExtension](https://github.com/RickStrahl/MarkdownMonster/blob/master/MarkdownMonster/RenderExtensions/DocFxRenderExtension.cs).
