### ISSUE TITLE
Edit Table doesn't seem to work?

### ISSUE THREAD

**Issue by BIOSMonkey** [RickStrahl/MarkdownMonster#369]
Using MM 1.10.21, I am trying to edit an existing pipe table by right clicking and choosing Edit Table, but it doesn't seem to do anything?

Also, the context function doesn't seem to recognize simple pipe tables (i.e. the Edit Table option doesn't show up at all), when they look like this:

```
Actions | Description
--- | ---
Summary | Reloads the page
Help | Launches the help
```

In summary, I was trying to "beautify" the simple tables like above into the nicer looking ones generated by the editor, like this:  

```
| Actions | Description       |
|---------|-------------------|
| Summary | Reloads the page  |
| Help    | Launches the help |

```

I had thought I would be able to just right-click the simple table, Edit Table and then save it back, but I am not getting the editor to show up?

So far to achieve what I want I've just been selecting the old table, cutting to clipboard, bring up the table editor, paste from clipboard, and then re-embed.  Works, but a lot of steps.

Am I doing something wrong?

**Comment by RickStrahl** [comment]
Took a look at this and there are really three issues here.

* Edit Table Option not Showing Up for some valid Tables
* Tables not picked up correctly in some cases
* Edit Table not showing up for tables that don't have leading |

I fixed all of these, although I think the latter option can potentially cause some problems if a line has a | character on it and would show the Edit Table option.

**Comment by BIOSMonkey** [comment]
Thanks Rick, downloaded the latest portable and it looks good ... much simpler to Edit and Embed 👍
