### ISSUE TITLE
SUGGESTION: Project support

### ISSUE THREAD

**Issue by BIOSMonkey** [RickStrahl/MarkdownMonster#372]
I use MM to generate the help contents for large web applications. These .md files exist in different "plugin" folders under /strings, and there are quite a lot of them.

I also maintain different versions of these applications, so switching between the different app versions and having to hunt down and load all the .md files is a little painful.

It would be really helpful to add Project support whereby I can save all currently open files as a "project" and then load them all in one shot whenever I switch between app versions.

**Comment by RickStrahl** [comment]
Yeah it's something I've thought about. It's on the list for a future update, but not on the near term horizon.

**Comment by RickStrahl** [comment]
Started working on this and it's now available in the latest pre-release build (1.17.6+).

![image](https://user-images.githubusercontent.com/1374013/59070723-8ec02480-8857-11e9-8ff3-69eea8e78380.png)

At this point the project contains only a set of filenames - nothing else really. Filenames are hardcoded to physical paths at the moment, but I think it would be a good idea to use project relative paths instead.
