### ISSUE TITLE
Copy/Paste HTML/RTF to MM

### ISSUE THREAD

**Issue by Mehul** [RickStrahl/MarkdownMonster#374]
Hey Rick,

Not sure you have this but a feature where I can copy webpage contents (html w/links, etc) and then to be able to paste/convert that in MM and have it turn into markdown?

**Comment by RickStrahl** [comment]
This not it?

![image](https://user-images.githubusercontent.com/1374013/40263737-a048b632-5acb-11e8-8540-4b1cea098489.png)

**Comment by Mehul** [comment]
Yes that's it, thanks! :)
