### ISSUE TITLE
On Windows 10 - shuts down automatically while working, lost data of unsaved files

### ISSUE THREAD

**Issue by ajit555** [RickStrahl/MarkdownMonster#375]
First of all, excellent software. I like it so much but worried to use it due to data loss

OS Name:  Microsoft Windows 10 Pro
OS Version : 10.0.17134 Build 17134
Markdown Monster version: 1.11

Don't know exact steps to reproduce but happens frequently (2-3 times a day). 

Below is my typical usage scenario:

1. Folder browser panel is open and it contains lots of folders (about 20), each containing 4-5 markdown files.
2. All folders are in live Microsoft OneDrive folder.

3. 4 to 5 markdown files are open, 2to 3 md files are new and not saved (those are the files I lost when Monster shut down and I did not get chance to save)

4. Markdown document outline panel is open and md file has about 1000 lines with 100 lines as heading lines displayed in document outline.

5. While working, I frequently put the laptop to sleep while Monster app is open. The laptop is on for about 10 hrs per day, with sleep mode every 2 hours.  In a day of usage, the Monster app shuts down about 2 to 3 times.

6. I convert from HTML to md using (https://euangoddard.github.io/clipboard2markdown/). When copying and pasting large data from site to Monster hangs Monster and it shuts down.

7. While working, suddenly Moster app shuts down, and all my unsaved data is lost.

Hope above is useful.

**Comment by RickStrahl** [comment]
Hmmm... I haven't seen anything like that and my usage seems similar to your's - long sessions and between 2-5 files open typically. I don't have any shutdowns.

You're seeing the app disappearing or do you get an error dialog?

If the app disappears that usually points to a hardware issue where Windows is essentially bypassed and no errors are trapped.

One thing you can try is turn of the Hardware Assisted Rendering (GPU) optimization:

https://markdownmonster.west-wind.com/docs/_4uj0kfglm.htm#Workaround:TurnoffHardwareAssistedRendering

**Comment by ajit555** [comment]
Thanks for the reply.

The app simply disappears and no error dialog pops up.

I have turned off the setting under Tools > settings and saved the configuration.
"DisableHardwareAcceleration": true

I do not know if it is a clipboard issue. Generally, on my computer, I did not face any clipboard issues with other applications.

I would use the app for a couple of days and let you know if the issue resolves.

I tried the in built html to markdown conversion, but found "https://euangoddard.github.io/clipboard2markdown/" better, especially I copy pate a lot of content containing html, javascript and css codes.

**Comment by RickStrahl** [comment]
Well, I don't know how to do anything about this this since there's nothing that fires on our end. Windows (or a hardware failure of some sort) is killing the app.  Maybe check the EventLog and see if there's more info there.

**Comment by ajit555** [comment]
After ["DisableHardwareAcceleration": true], one day went without Monster shutting down automatically. Would use for few more days and let you know.

**Comment by RickStrahl** [comment]
Assuming the disable hardware flag has addressed this issue...
