### ISSUE TITLE
BUG:  Pressing a certain key combination crashes current source tab

### ISSUE THREAD

**Issue by BIOSMonkey** [RickStrahl/MarkdownMonster#379]
Warning:  Don't try this with any unsaved work 

Place the cursor in the source window and press ctrl-F5.   The source disappears, and the file tab will crash when any operation is attempted on it.

I thought focus was in my main text editor when I did this, and a markdown file I had been working on for an hour disappeared.   Luckily the backup file saved it.

Apologies if you cannot reproduce this and it is some weird global key mapping on my side that I don't know about.  But other apps that bind it work fine (like my editor).

**Comment by RickStrahl** [comment]
Yup I see it - it's refreshing the browser. Shouldn't happen obviously :-)

**Comment by BIOSMonkey** [comment]
I suspected it might have to do with cache bypass but wasn't sure how MM worked under the hood.
