### ISSUE TITLE
Wordpress download only gets the excerpt

### ISSUE THREAD

**Issue by rprouse** [RickStrahl/MarkdownMonster#38]
Most of my recent Wordpress posts use the **Read More** tag to separate the excerpt seen on the front page of the blog and the full content. When downloading using MM, only the text from before the read more tag is downloaded.

I tried using the WordPress XML-RPC API and the metaWeblog API settings with the same results.

Not sure if it is helpful since I haven't used the API myself, but the [docs state](https://codex.wordpress.org/XML-RPC_WordPress_API/Posts#Notes),

>In the older metaweblog API, the "Introduction" and the "Read More" content for a post were returned in separate fields "description" and "mt_text_more". In the WordPress API, the two values are combined in the single "post_content" field, separated by the `<!--more-->` tag.

As an example, for [this post](http://www.alteridem.net/2016/06/18/nunit-3-testing-net-core-rc2/),

It downloads the following,

```html
# NUnit 3 Tests for .NET Core RC2 and ASP.NET Core RC2

<strong>Update:</strong> I have released <a href="https://www.nuget.org/packages/dotnet-test-nunit/">beta 1 of dotnet-test-nunit</a> which has been updated to the RTM of .NET Core 1.0. I have updated this post and the code on GitHub to reflect the changes.

The NUnit team has been working hard since .NET Core RC2 and ASP.NET Core RC2 was released last month to add full NUnit testing for .NET Core, and we are happy to announce the second alpha release of <a href="https://www.nuget.org/packages/dotnet-test-nunit/3.4.0-alpha-2">dotnet-test-nunit</a>.

In my previous blog posts, I explained how to use <a href="http://www.alteridem.net/2016/05/18/testing-net-core-rc2-using-nunit-3/">NUnit to test .NET Core using NUnitLite</a> which worked, but was not the ideal solution. The new <a href="https://www.nuget.org/packages/dotnet-test-nunit/3.4.0-alpha-2">dotnet-test-nunit</a> allows you to test from the command line using the `dotnet test` command and allows you to run your tests within Visual Studio.

<!-- Post Configuration -->
<!--
``xml
<blogpost>
<abstract>

</abstract>
<categories>
.NET,.NET Core,NUnit,Testing
</categories>
<keywords>
.NET Core, DNX, NUnit, TDD, Testing
</keywords>
<weblogs>
<postid>556</postid>
<weblog>
Alteridem
</weblog>
</weblogs>
</blogpost>
``
-->
<!-- End Post Configuration -->
```

Its also not doing a great job converting the HTML to MarkDown.

**Comment by RickStrahl** [comment]
@rprouse Hmmm... I need to look into that. MM only returns the content from the description field. 

FWIW, i have a test Wordpress account I use for testing and I don't see this behavior - is there anything sepecial that needs to be set to enable this behavior so I can test it?

As to Markdown Conversion: Markdown is a limited format so it can only represent so much of an HTML document. So if you have old Live Writer posts that have for example embedded code snippets, you're likely going to get a bit of HTML which is not optimal. I'll be looking more closely at this going forward to see if there is some post processing that can help - I can think of at least cleaning up formatted code snippets and turning them into plain text. For now the import is using a generic HTML to Markdown converter.

**Comment by rprouse** [comment]
@RickStrahl the only setting I have set that might cause it is for the RSS feed, under Settings, Reading, For each article in the feed, show - Summary.

This is for the feed though, so I am not sure if that is causing it.

The front page of my site only shows summaries. To get that to happen, I just Insert Read More tag which shows up in the HTML as `<!--more-->` and in the Visual Editor like this,

![image](https://cloud.githubusercontent.com/assets/493828/20020360/4a11bf80-a2a7-11e6-9b01-7b3b7118bac8.png)

For the HTML conversion comment, I realize that you can only convert so much, but I expected the simple tags like `<strong>` and `<a href>` tags to convert. See the HTML I posted above.

**Comment by rprouse** [comment]
From the docs I linked, it looks like for the Wordpress API, you should be using the `post_content` field, not the `description` field which only contains the excerpt.

**Comment by RickStrahl** [comment]
Can you create a new issue for the post import problem so I can track this separately?

I'm not sure what's happening as old html posts I'm importing are converting - with some limitations. But you're def right - those simple tags should convert.

**Comment by RickStrahl** [comment]
Ok, I fixed the import and the HTML conversion.

But...

Wordpress seems to create some crazy HTML which also screws up the markdown that is converted:

For my test post I get:

```html
<strong>This is a post </strong>that includes a Read More tag that separates the 'abstract' from the main content. Read more is stripped off  the document.<!--more-->

This is where the <strong>content goes </strong>after the <strong>read more </strong>text.
```
Notice the funky spacing of the `</strong>` tags. This then produces `**This is a post **that includes` which is funky at best. Easy to fix with **Replace All** operation. Looks like it's only bold that causes that - other tags appear to not do that.

**Comment by rprouse** [comment]
Ping me when 1.0.2 is up and I will test it for you. Thanks for the quick turnaround. Managing my blog was the feature that caught my attention. I usually find Visual Studio Code good enough for the rest of my Markdown needs.

**Comment by RickStrahl** [comment]
It's up - it doesn't say 1.0.2 online, but it's there. Choco is not updated yet.

**Comment by rprouse** [comment]
@RickStrahl works really well now, thanks, expect a purchase once I test a bit more 👍 

You in Bellevue this week for the MVP conf?

**Comment by RickStrahl** [comment]
Excellent!

Yes I'll be at the Summit. I'll arrive late tonight.

Oh and if you're an MVP you get a free license. Send an email - http://west-wind.com/contact/ along with your MVP profile.
