### ISSUE TITLE
After taking the update from May 23 rd getting Add-on Errors

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#380]
After taking the update from May 23rd I am  getting add-on errors.

I was able to fix those add-ons found in the Add-ins Manager, but not these:
---------------------------
The following addins failed to load
---------------------------
Unable to load addin PanDocMarkdownParserAddin

Unable to load addin PasteCodeAsGistAddin

Try updating each failing addin and Markdown Monster to the latest versions or uninstall each failing addins.
---------------------------
OK   
---------------------------

**Comment by RickStrahl** [comment]
Make sure you have the latest build from the Web site download. Those two addins have been updated and they work. But you need to uninstall first. **Make sure they actually  uninstall** then shut down MM and restart. Then re-install the addins after they've been removed and no longer show in the IDE.

The initial 1.11.4 release was unable to uninstall the some addins - 1.11.5 should work however.

 If they don't uninstall:

* Go to `%appdata%\Markdown Monster\Addins` and remove the folders specific addins that aren't working from there. Just remove the specific folder.

This effectively uninstalls those addins as well.

Then reinstall from the Addin Manager.

**Comment by ArthurZ** [comment]
I upgraded to 1.11.6, and got the same error, the only add-on that I found in the manager was the PasteCodeAsGist,, no Pandoc, removed the former, re-installed, the error did not go away. Deleted both folders from `%appdata%\Markdown Monster\Addins` and not on restart no more errors. But PaseteCodeAsGist is nowhere to be found, it does not appear in the Add-in Manager,

**Comment by RickStrahl** [comment]
The Gist addin has been renamed. It's Github Gist integration which includes the old functionality.

![image](https://user-images.githubusercontent.com/1374013/40590508-9f32f89e-61b4-11e8-8407-2973bf71f08e.png)
