### ISSUE TITLE
BUG:  Crash on clicking "outline" for blank doc

### ISSUE THREAD

**Issue by CollinChaffin** [RickStrahl/MarkdownMonster#381]
### To reproduce with latest version 1.11.6
1. Open MM with no prior docs open
2. Click "new doc" from start screen
3. Click "Outline" at the bottom of the outline/folder pane
4. Program crashes

**Comment by RickStrahl** [comment]
Thank you. Fixed.

**Comment by CollinChaffin** [comment]
Sorry didn't see this, thanks!
