### ISSUE TITLE
BUG: Startup OpenInPresentationMode setting not Honored

### ISSUE THREAD

**Issue by CollinChaffin** [RickStrahl/MarkdownMonster#382]
### To reproduce with latest version 1.11.6
1. In config, set "OpenInPresentationMode" to true
2. Re-open MM
3. Presentation Mode checkbox is checked on menu, toolbar is missing as if in that mode, yet all other normal non-presentation mode panes/elements still active
3. OPTIONAL: Re-click the F11 presentation mode on the menu to uncheck it, then repeat and watch as full presentation mode is properly applied

So, it is currently impossible in current (or the last version I ran) to actually start the app in presentation (or really anything but the default view) and it work properly.  I have not dug through all the code myself yet but it is clear the entire mode change is not being executed in the startup call vs the manual call.

**Comment by RickStrahl** [comment]
Yeah it turns out this is a timing issue. The mode is actually set, but it immediately gets reset by the regular UI initialization.

Checking to see where exactly the UI initialization happens - the quick fix for now is to fire the presentation mode code out of band - that works but there's a bit of flicker as the splitscreen layout shows up briefly before being replaced by presentation mode.

**Comment by CollinChaffin** [comment]
Sorry didn't see this, thanks!

**Comment by CollinChaffin** [comment]
Hi @RickStrahl wanted to ask this still seems to be a bug that hasn't changed so should this be closed?  Timing or not, it seems pretty silly to still have a setting specifically named `"OpenInPresentationMode": true,` that really doesn't work and opens up not in presentation mode, but in full dual-pane editor mode with the only real difference being that it appears almost a "broken" state missing only the toolbars, etc.

To use MM as not only an editor (for which it rocks) but also frankly a go-to markdown READER to (as the default) upon double-clicking markdown files, open them in a read-to-read state, this feature is pretty critical.  Right now, since it requires at the very least an additional F11 keypress to truly put it in the presentation mode, that seems absolutely no different than when I disable that option all together - since both require the same keypress.  Or is there a workaround or fix I've missed?

Thanks!

**Comment by RickStrahl** [comment]
Yup - timing issue was causing problems still. I guess this has been re-introduced when the startup loading sequence was updated.

Updated the checks for presentation mode.

Also added a new command line switch you can using:

```ps
mm .\myfile.md  -presentation
```

This should open in presentation mode.
