### ISSUE TITLE
Save icon remains disabled after making a spelling dictionary correction

### ISSUE THREAD

**Issue by sportflier** [RickStrahl/MarkdownMonster#383]
I noticed the following in a markdown document I was editing (MM 1.11.8):

- Document had been saved, so the save icon was disabled
- The word "organisational" was in my document, which is correct spelling in UK but not US, so word was highlighted indicating possible spelling error
- I opened the context menu and selected "organizational" to change spelling of the word
- After this change, the save icon was still disabled

**Comment by RickStrahl** [comment]
Fixed in 23e6d3f04d0e5624cee6f72ab8a03635c3c732ab
