### ISSUE TITLE
Left, right and single quotation characters trigger spelling errors

### ISSUE THREAD

**Issue by sportflier** [RickStrahl/MarkdownMonster#384]
MM Version 1.11.9

I have noticed that while the "neutral" double quotation mark does not trigger a spelling error (red underline) when adjacent to a correctly spelled word, this is not the case with the single quotation mark, the left double quotation mark, or the right double quotation mark.

Consider the following text:

contact us (no errors)
"contact us" (no errors)
'contact us' (has errors)
“contact us” (has errors)

![2018-06-05 12_23_55-markdown monster spelling bug md](https://user-images.githubusercontent.com/302203/40989364-92dced94-68bb-11e8-88c4-60b711a52e21.png)

**Comment by RickStrahl** [comment]
Added a fix for this. The fix should actually work well for any 'wrapping' blocks of text using quotes, brackets, paranthesis etc. more reliably than previously.
