### ISSUE TITLE
Product Registration - clicking 'Buy Registration Key' displays registration error

### ISSUE THREAD

**Issue by sportflier** [RickStrahl/MarkdownMonster#385]
MM 1.11.9

1. Select Help, Register Copy
2. On the Product Registration dialog, click "Buy Registration Key"
3. A message dialog appears with the text "Sorry, that's not the right key."

As a user I was expecting to be taken to a web page where I could purchase a registration key.

![2018-06-05 12_32_57-markdown monster registration error](https://user-images.githubusercontent.com/302203/40989710-acca270c-68bc-11e8-8aec-400618f0df8d.png)

**Comment by RickStrahl** [comment]
Funny you should mention that :-) Just did some work yesterday to clean up both the registration reminder form and register form.

Somehow the Buy link got mixed up with the registration link. I've clarified the form so now there are separate Register and Buy button:

![image](https://user-images.githubusercontent.com/1374013/40994238-91306a30-68b0-11e8-9ac3-88ce1848584b.png)
