### ISSUE TITLE
table editor feature suggestion: CSV import/export

### ISSUE THREAD

**Issue by christian-korneck** [RickStrahl/MarkdownMonster#391]
Just as a suggestion: It would be great if the table editor had CSV import/export, which would it make easy to copy data from/to Excel, Google Docs, etc.

**Comment by RickStrahl** [comment]
Well, I guess I had some time today :-)

![image](https://user-images.githubusercontent.com/1374013/41943453-5a9b6e80-7958-11e8-8a24-33245404b4f8.png)

The good news is, that the feature is in. The bad news is that it's very slow loading data into this custom table layout (ie. loading more than a 1000 columns gets very slow). Then again loading more than that into a Markdown document is probably not the best of ideas anyway...

**Comment by christian-korneck** [comment]
awesome! Can't wait to try it.

**Comment by christian-korneck** [comment]
thanks again!
