### ISSUE TITLE
Editor not correctly calculating text width

### ISSUE THREAD

**Issue by strandloper** [RickStrahl/MarkdownMonster#394]
I have the following font settings configured in version 1.12.2
```
"Font": "Fira Code Light",
"FontSize": 20,
```
Text width is not being calculated correctly with regard to positioning of the insertion pointer and span of selections. The screenshot below shows the result of pressing Shift-End from the home position on a line of text.

![image](https://user-images.githubusercontent.com/668433/41962139-9239ec08-79f4-11e8-8f8b-4dd4de111fd3.png)

Pressing End from anywhere in the line positions the insertion pointer to the same place as it appears in the screenshot above.

From the home position pressing Ctrl-Right to advance words correctly positions the insertion pointer to the beginning of the first word; pressing it again advances to just short of the end of the first word and the error in position increases as subsequent presses move through the line.

**Comment by RickStrahl** [comment]
Hmmm... Are you sure Fira Code Light is installed? On my machine `Fire Code Light` is very light and it works properly in terms of selection.  It doesn't look anything like what you have above.

![image](https://user-images.githubusercontent.com/1374013/41991414-2fe9e368-79fa-11e8-95df-e5c2a5c69b9d.png)

Can you try another font that you're sure is installed?

**Comment by RickStrahl** [comment]
Ok I take that back!

I see it now. 

So this appears to be a font specific issue - it looks like bold text is larger than non-bold text in the editor and that's what causing the kerning offsets to be off. This is not a problem in other fonts like Consolas or other Fira Codes but apparently this light version has different sizing for bold and non-bold text that's not consistent with the font base line sizing that Ace Editor uses to calculate offsets.

Can you take a look at a few other fonts and see what you find?

FWIW, there's nothing I can do about this here as the font management comes to Markdown Monster as part of the ACE Editor control I use in MM. The better place to raise this issue would be on the ACE Editor repo and we pick up any fixes that are made in the base editor.

https://github.com/ajaxorg/ace/issues

**Comment by strandloper** [comment]
Thanks for checking this out.

I have experimented with Fira Code, Fira Code Light, Envy Code R and Consolas; Fira Code Light is the only one of them affected by this problem.

As this issue is inherited from the editor control you use I'll close this issue and raise one under their repo.
