### ISSUE TITLE
Enhancement: Implement Jump to Anchor for embedded Anchor links

### ISSUE THREAD

**Issue by Philippe91** [RickStrahl/MarkdownMonster#399]
If I have a link such as:
```
[My Title](#my-title)
```
and somewhere else in the markdown file, a line such as:

```
## My Title
```

Then I can' find a way to jump to the line "My Title" by clicking on the link (neither markdown view ,nor html view).
Other Markdown Editors allow that. Well, as least 3 others that I know.
The standard mapping Title to Anchor name is:
* replace spaces with a -
* convert to lower case
* remove punctuation marks (don't replace with space)

Please implement this feature :)

**Comment by RickStrahl** [comment]
I think the better way for this is to use the document outline. Open the outline and it stays in sync with your document you can then jump anywhere in the document.

But yes that's a good suggestion and should be relatively easy to implement as we already allow for link parsing from the shortcut menu that parses the link.

**Comment by RickStrahl** [comment]
So I took a look at this. There's no way this can ever be reliable. Doing the reversing of anchor to value due to capitalization and removal of punctuation. Punctuation will break the reverse lookup for sure.

**Comment by Philippe91** [comment]
As mentioned previously, there is a standard for this, Look at this example that works with other markdown editors:
https://github.com/livingsocial/api-design/blob/master/README.md

Look how the anchor names are formatted:
The standard mapping "Title to Anchor name" must work like this:

convert to lower case
replace spaces with a -
remove punctuation marks (don't replace with space)

There are various source of info about this on the web, eg.
https://gist.github.com/asabaylus/3071099
https://stackoverflow.com/questions/6695439/how-to-link-to-a-named-anchor-in-multimarkdown

**Comment by RickStrahl** [comment]
Never mind I'm being dense - maybe it's time to go to bed :-) 

The code has to run through all the headers and encode them and then compare that to the anchor link captured from the link. That should work as long as the same encoding mechanism is used. THere are several different standards for this. MM uses Github style formatting by default but others are supported.

**Comment by RickStrahl** [comment]
This should do it: deea22cd4b19ed54d8be804f8b1acafb6ab42d50

**Comment by Philippe91** [comment]
Your change works fine here :)
Note that other editors provide the jump function from the HTML preview. Maybe you could consider this. But your current implementation is already excellent :)

**Comment by pethopal** [comment]
In Commonmark documentation I see a more robust, and a little schemantic solution:

> \[Whitespace\](@) is a sequence of one or more ....
>
> ...by \[whitespace\], the end of the line,...

It is like you had a business term inside the document.

**Comment by RickStrahl** [comment]
@Philippe91 Coming back to this now as I've implemented a few related functions to preview menus.

Not sure that we need a menu item there because when you click the link the preview **and editor** navigate which puts you into the right place. This is assumes two-way editor/preview mode.
