### ISSUE TITLE
Small bug with hovering mouse?

### ISSUE THREAD

**Issue by hwkmueller** [RickStrahl/MarkdownMonster#401]
You go with the mousecursor to the mainmenue. Click File: the submenue opens. Hover over to Edit, Tools, View: the submenues opens, Windows, Help: no submenue, you had to click.

**Comment by RickStrahl** [comment]
I took a look and I can't find a reasonable way to handle this more cleanly. I can break the behavior in other ways, but none of the ways are 100% correct. Out of all the ways this can be 'wrong' I think the current way is least intrusive.

So I'm not going to fix this for now unless someone wants to jump in and take this on as this would probably require digging in the custom MahApps main menu  definition triggers.

**Comment by RickStrahl** [comment]
Ok. Never mind :smile: Another tack made this work. Putting a dummy item and not removing items on close I actually was able to make this work.

Fixed with: 7d972e065eb1a16513bee4db0bb898ed67fb91b6
