### ISSUE TITLE
Picture Refreshing

### ISSUE THREAD

**Issue by Philippe91** [RickStrahl/MarkdownMonster#405]
If the markdown file has a link to a picture, and if the picture file is modified, then the HTML preview is not updated. One needs to close the reopen the markdown file.
I understand a picture file watching system is certainly over the top, but a manual command to refresh "deeply" the HTML preview, would be welcome.

**Comment by RickStrahl** [comment]
You can right click on the Previewer and click **Refresh Browser**:

![image](https://user-images.githubusercontent.com/1374013/42776768-e7b51552-88ec-11e8-9355-3e67045ddd0a.png)

Image operations that use the image link dialog also cause the preview to refreshed when completed so if you edit a link or use the image editor from there then re-paste the image it'll also refresh.

But for loose images, that MM doesn't track explicitly **Refresh Browser** is required.
