### ISSUE TITLE
Key Shortcut for "Inline Code in a Paragraph"

### ISSUE THREAD

**Issue by Philippe91** [RickStrahl/MarkdownMonster#406]
This is a command I use a lot, but unfortunately the key shortcut does not work with my french keyboard,
certainly because the ` character is special and Control ` fails.
Any idea how to solve this?

**Comment by RickStrahl** [comment]
Unfortunately not - sorry...

Ctrl-` is often mapped to something else (notable to open command window for me in VS code and ConEmu). 

The key mappings unfortunately are not changeable due to the fact that mappings occur both in the Javascript editor and also externally in the shell.

**Comment by marin-bratanov** [comment]
I would also love to see a way to alter the default keyboard shortcuts. In my case, Ctrl+` is used to open Ditto (a clipboard manager). Since I've been using Ditto far longer than MM, I'd rather be able to keep my current habits and form a new one for MM.
