### ISSUE TITLE
Behavior Request: Reduce minimum height and width

### ISSUE THREAD

**Issue by bladewolf55** [RickStrahl/MarkdownMonster#407]
## Issue
Markdown Monster's minimum width is 900 pixels, and minimum height is--800px? I believe these are unnecessarily high, and make the editor harder to use in several cases.

I suggest using minimum width/height of 200 pixels.

## Use Case
I'm a software engineer and run three modest monitors, all at 1920x1280. One is in portrait mode, and is where I keep MM open for my journal, along with email and a time boxing timer. As you'll see in the attached screen captures, at 900px, MM overlaps the timer. I could reduce the timer width, but then it becomes more difficult to read.

I built my own MM with min width/height of 200px. It works perfectly well, solves my problem, and is very usable.

## More Discussion
You discussed some pros and cons of these settings in issue [394](https://github.com/RickStrahl/MarkdownMonster/issues/394). I get what you're saying, and, you know, it's your editor. You should enjoy using it. That said, here's what I think:

*   I don't know of another text editor that has such large minimum dimensions. See Visual Studio, VS Codem Notepad++, Word, etc).
*   By enforcing those minimums, you take choice out of your users' hands. If they want to resize to a tiny box, let 'em! Maybe they have a good reason.
*   Toolbar buttons will get cut off, and they are today. Many application toolbars have a right-side dropdown to access hidden items. Is that an option for you?
*   If a user runs MM in distraction-free mode, the toolbar is irrelevant, but window size is important.

![20180709-082527](https://user-images.githubusercontent.com/2903411/42789579-46652df4-8923-11e8-9f5f-3b9e420f3723.png)

![20180709-083630](https://user-images.githubusercontent.com/2903411/42789580-467a3cee-8923-11e8-898c-ac0ab504c7e0.png)

![20180709-084349](https://user-images.githubusercontent.com/2903411/42789581-468f9d14-8923-11e8-8c25-8f0f16ba2013.png)

![20180709-084608](https://user-images.githubusercontent.com/2903411/42789582-46a4f3ee-8923-11e8-8d61-3c938aded6ff.png)

## Wrap Up
Thanks for considering this, Rick. I haven't directly contributed to MM as much as I want (except for a little coding, and paying the license). It just keeps getting better. This is an easy change that, I think, will please many users by reducing the "death by a thousand cuts."

**Comment by RickStrahl** [comment]
That's fair enough. This is not the first time this has come up and I've reduced the min-size on a few occasions actually, but I've always been trying to keep it to a size where the UI still works. It's both the toolbars and status bar that are an issue. The toolbar is mostly replicated on the menu so that's probably forgivable, but the status bar will lose settable options that currently are only set there (all the theming options).

If you're running 1080p you must be running with what 150% scale to get so little on your screen? Heck I run a 4k display at 100% and sometimes that feels crammed to me :smile:

I'll play around with this to see how small we can go and still have reasonable usability.

**Comment by RickStrahl** [comment]
So playing around with this. I fail to see how this is useful to anybody:

![image](https://user-images.githubusercontent.com/1374013/42803972-6d41a18a-895c-11e8-909a-95a5efde0167.png)

or even in distraction free mode without menus and status:

![image](https://user-images.githubusercontent.com/1374013/42803940-517670c0-895c-11e8-8909-6219a40ad650.png)

This seems pretty pointless to me, but...

I've added this for now: 20aa467b76600fb53e2a02e0ea7a3258a838ff46

We can play around with this and see whether this helps or hurts (in way off complaints that things are not visible).

**Comment by bladewolf55** [comment]
This is a good discussion, not just about MM, but about interface design, developer vs user perceptions, and assumptions. I'd like to make the case that, let's say, "over-minimizing" the window isn't about app usability. But first: All my monitors run at 100% 1280p, including the 15" laptop. One monitor is in portrait mode, because I've found that's effective for its use as my "always visible" area. By default, MM would take 70% of that width, even though it's completely usable to me at half that. I know it's a monster, but that's a lot of space to eat! (MM was literally getting in my way.)

![20180717-092806](https://user-images.githubusercontent.com/2903411/42830299-47f36a16-89a8-11e8-8dbc-6230dfe9389b.png)

Usability is in the user's eye, and in context. A user might need or want to resize the window to just a couple of important lines in order to position it over some other window (I've done this). She might use an unusually small font size and be able to use a smaller window. She might always run in distraction-free--per your second screen shot--and use MM like a sticky note. I think your second screen shot is completely usable, and is how I'd like to be able to use MM. Years ago I wrote a "quick note" app for just that need: always-on-screen, rapid entry, auto-save. 

I rarely (almost never) need the status bar. I sometimes use the toolbar or menu. But then again, I'm also keyboard-centric. 

My daily use case is a running journal. In fact, a running journal is what got me started seriously using Markdown, because of[ this article and app](http://markdownpad.com/news/2013/introducing-markdownpad-2/). (The developer, Evan Wondrasek, seems to have fallen off the earth.) When I need to create a blog entry, I open a new MM instance in a larger window (*thank you* for making that an option!)

Now, back to making my case. I've resized the following apps. With one exception, they get super-small--unusable. I propose that doesn't matter to the developers or their users. Has it mattered to you?

*   Notepad++ (122x32)
*   VS Code (190x110)
*   Visual Studio (200x200)
*   SQL Management Studio (200x200)
*   LINQPad (122x32)
*   Microsoft Word (136x40)
*   Balsamiq Mockups (800x600)
*   Paint.net (122x32)
*   Chrome Browser (515x113)

If it were me, I'd set the min window dimensions to zero and be done with it. The WPF controls already limit the size.

Does this make sense, where I'm coming from? I understand your usability goal. Hopefully this shows that "usability" can have different meanings depending on context.

Thanks, again, for being open to your users' opinions.

(BTW, regarding distraction-free mode, I'm hoping to work on a pull request that stores whether the user was last using distraction-free and return MM to that state on opening. If that worked, I'd use distraction-free 80% of the time.)

**Comment by RickStrahl** [comment]
Well you should have what you need with `MinWidth="390" MinHeight="220" ` which gives just enough to have a still usable window with some Chrome. Anything smaller than that most likely would be an accident :-) 

The default width MM starts up with is still set at 1000x700 which I would consider minimum usage size with Chrome enabled. But you can of course change that now. FWIW the original min size was 900x600 so even that should have been less than 50% of your screen.

**Comment by bladewolf55** [comment]
Thanks, Rick. I'll install the update today and check it out. It'll be a
big help.

 FWIW the original min size was 900x600 so even that should have been less
> than 50% of your screen.


​Not if I'm using a monitor in portrait mode, which I am. Then, my
monitor's width is 1280, so MM takes up 70%.

There are still lots of laptop users out there with 1400x1000ish
resolutions. The new minimums will help them, too.

--
Charles L Flatt
513-535-0764 (m)
​
"Lately, I've been getting through a lot by remembering to do my best and
never give up." --Jeff Hudson

**Comment by bladewolf55** [comment]
Works great! Thank you.
