### ISSUE TITLE
Feature: Jekyll Front Matter

### ISSUE THREAD

**Issue by hultqvist** [RickStrahl/MarkdownMonster#41]
[Jekyll Front Matter](https://jekyllrb.com/docs/frontmatter/) is a header of pages and post.

The beginning of the document looks like this.

```

---
layout: post
title: Blogging Like a Hacker

---
```

I suggest that Markdown Monster skip this header when rendering.
Possibly the title could be extracted and presented as a headline.

**Comment by evil-shrike** [comment]
+1 
it's not only for Jekyll, it's pretty common approach to embed metadata in md. [Assemble](http://assemble.io/) is another example.
I'd suggest to support 'title' option as doc title.

**Comment by RickStrahl** [comment]
FWIW - title already pulls in the post dialog from the `# header` 

It'll be in one of the next builds.

**Comment by RickStrahl** [comment]
Initial code for this has been added in 1.0.7 but only for publishing  - not for preview rendering. If you publish the header is stripped and the initial title is used as the post title.
