### ISSUE TITLE
If Snippet JSON KeyboardShortcut is Empty String, it Activates when Space is Entered

### ISSUE THREAD

**Issue by bladewolf55** [RickStrahl/MarkdownMonster#411]
**Version:** 1.12.10

## Steps to Reproduce
1.   Open MM with no SnippetsAddin.json (but with addin installed)
2.   Open New document
3.   Open Snippets addin, default snippet is created
4.   Close addin to save
5.   Test snippet expansion string, then delete all text
6.   Open Snippets addin
7.   Backspace over expansion string
8.  Close addin to save
9.   Press space bar. Copyright info is created. (**unexpected behavior**)
10. Close MM
11.  Open SnippetsAddin.json
12.  Set Shortcut value to null
13.  Open MM and new document
14.  Press space bar. Nothing happens (**expected behavior**)

## More Information
I discovered this by accident when creating a new snippet. It was temporarily baffling and distressing!

*Note:* I'm also seeing a problem with the new key bindings feature. I'm going to uninstall/reinstall MM, just in case it's a local issue. I do replace the .exe with a custom version. This should be a problem, since my sequence is:

1. Update using your updater.
2. Synchronize source
3. Apply my customizations
4. Replace the markdownmonster.exe with mine

I'll let you know either way if a clean install makes a difference.

**Comment by bladewolf55** [comment]
Issue exists in clean install. I'll write up the KeyBindings issue, too.

**Comment by RickStrahl** [comment]
Yeah I think the problem is that the value ends up being a an empty string (`""`) rather than null and the code checked for null only (odd that I did that). Changed logic to !string.IsNullOrEmpty()` and I believe that will fix it.

**Comment by bladewolf55** [comment]
It seems to be fixed, thanks. And...F12 to toggle Preview Browser! Yay! I missed this from when I was using Markdown Edit.
