### ISSUE TITLE
Export to Html fails with an error if the file you are manipulating has not been saved

### ISSUE THREAD

**Issue by conradakunga** [RickStrahl/MarkdownMonster#415]
My scenario is I am writing the markdown using backticks, but for my export to XML I don't want code to be rendered so I copy and paste to a new empty document and do a search and replace to get rid of the backticks. When I try to export I get this error

![image](https://user-images.githubusercontent.com/1281845/44029256-4e9c10e4-9f05-11e8-8947-4177b703ac8b.png)

Presumably, this is because the exporter expects the file to be an actually saved file.

Is it possible for such a scenario that if the exporter detects that the file has not been saved to generate a temp file and use that for export?

**Comment by RickStrahl** [comment]
Thank you... yes that's a bug. 

For now as a workaround you can either save the file first, or alternately export to the clipboard by selecting the text in the editor and using **Edit -> Copy Markdown Selection as Html** to get the Markdown converted to HTML copied onto your clipboard. From there you can paste it where ever you need.
