### ISSUE TITLE
`GitName` and `GitEmail` JSON settings are overriden back to null

### ISSUE THREAD

**Issue by breki** [RickStrahl/MarkdownMonster#416]
Even if I manually enter the values for `GitName` and `GitEmail` in the settings JSON file and save the file, the next time I load the file the values are back to `null`. I checked the file permissions and they seem to be OK (and the file modification time is updated to the moment I saved the file).

I installed MM through Chocolatey.

**Comment by RickStrahl** [comment]
Closing as this really the same issues as #417
