### ISSUE TITLE
**Commit to Git** dialog does not persist git name and email address

### ISSUE THREAD

**Issue by breki** [RickStrahl/MarkdownMonster#417]
Git name and email address are always empty. After I enter the values and commit (which closes the dialog), the next time I want to commit I have to reenter these values. Could be related to #416 

BTW I use TortoiseGIT and have these values entered in global .gitconfig file.

**Comment by RickStrahl** [comment]
Fix name and email databinding: 82c872d5841c5bd04c8c1e42d4afececed4b6c68

**Comment by RickStrahl** [comment]
Add auto-lookup from .gitconfig: 8a6673c22e240f7aa51e877c4a8751b127ae733a
