### ISSUE TITLE
Markdown rules not followed in SampleMarkdown.md

### ISSUE THREAD

**Issue by teacher4711** [RickStrahl/MarkdownMonster#419]
I'm no expert in Markdown but the following rules are not abided by in the SampleMarkdown.md document:

# Welcome to Markdown Monster
Here are a few tips to get you started:

Rule: Headings should be surrounded by blank lines

---

* To change **Editor or Preview Themes**, click on the drop-down lists on the bottom right status bar:  
![Image and Preview Themes on the toolbar](https://markdownmonster.west-wind.com/docs/images/EditorPreviewThemeUi.png) 

Rules:

* Lists should be surrounded by blank lines
* There is a trailing single space at the end of )
* There are multiple instances of trailing single spaces in the document

---

* For **dark editor themes** look at `twilight`,`vscodedark`, `monokai`, `terminal`
  
Rule: after a colon, there should be a blank space

---

### Line Continuation

@icon-gear Configuration

### Emojis

Rule: There must no be multiple consecutive blank lines. There are multiple instances of multiple consecutive blank lines

---

```markdown
Go to the Help Builder West Wind Html web site: 
<a href="http://west-wind.com/" target="top">Help Builder Site</a>.
```
---

Rule: Fenced block codes should be surrounded by blank lines

**Comment by RickStrahl** [comment]
While most of these may be CommonMark rules, most actual implementations are rather lenient on spacing for rules, when there isn't a conflict with some other rendering. 

I do appreciate these notes, but could you submit these as a pull request, so it's easier to work with the changes you're suggesting?
