### ISSUE TITLE
Open new file will show ace.js error

### ISSUE THREAD

**Issue by kkbruce** [RickStrahl/MarkdownMonster#42]
Hi

I upgrade (and re-install) to 1.0.3, 
If use New File always show this message in bottom, 

http://imgur.com/a/vvTCR

- Function is no problem
- Show Error Log no any data

Report for you.

**Comment by RickStrahl** [comment]
The error is displaying from the editor. The error logger shouldn't be on - my bad for shipping with the wrong flag. You can change the `isDebug` setting to `false` here:

```
var editorSettings = {
  "dictionary": "EN_US",
  "enableSpellChecking": true,
  "fontSize": 19,
  "isDebug": false,
  "showLineNumbers": false,
  "showPrintMargin": false,
  "tabSpaces": 4,
  "theme": "twilight",
  "wrapText": true  
};
```

in `C:\Program Files\Markdown Monster\Editor\editorSettings.json`.

**Comment by kkbruce** [comment]
Fast got 1.0.6, good job :-)
