### ISSUE TITLE
Suggestion: LanguageTool plugin

### ISSUE THREAD

**Issue by teacher4711** [RickStrahl/MarkdownMonster#420]
Hi,

LanguageTool, which you can have as a browser add-on, an integration into LibreOffice, etc. is also available as a plugin for many different languages. Visual studio code has it so that an integration into MarkdownMonster might be possible as well. It offers not only excellent language support but has also got a grammar checker and makes suggestions about typographic changes, such as replacing straight quotes with curly quotes or the insertion of ligatures, e.g. replacing -> with →.
The downside: So far, the visual studio code plugin does not allow to define exceptions (which the LibreOffice plugin does). Exceptions are important because, for example, a double blank character would be underlined and there would be a suggestion to delete it. In Markdown, however, double blank character shave a specific purpose.

**Comment by RickStrahl** [comment]
Closing - duplicate to #378
