### ISSUE TITLE
Suggestion: Linter

### ISSUE THREAD

**Issue by teacher4711** [RickStrahl/MarkdownMonster#421]
Hi!

To eliminate errors while writing Markdown or any other code, I consider a linter a valuable plugin. There are several GitHub projects that offer linting for Markdown, e.g. https://github.com/markdownlint/markdownlint.

**Comment by RickStrahl** [comment]
This sounds like a good idea for a plug-in rather than a main tool integration.

Leaving this here as an up for grabs.
