### ISSUE TITLE
Add to dictionary

### ISSUE THREAD

**Issue by teacher4711** [RickStrahl/MarkdownMonster#422]
I currently run the portable version of MarkdownMonster 1.12.12 and I don't seem to be able to add words to the dictionary.
I tested this with the en-US and German dictionary.
To verify if any changes were added/written to the included dictionaries in "MarkdownMonsterPortable\Editor" I opened the .dic files but there were no changes.
I also checked if changes had been made to files in another location within the MarkdownMonsterPortable\ folder within the given time frame I had added the words to the dictionaries, but there weren't any.

Could you please look into this issue.
Am I right to assume that any new words would be written to the '.dic' files?

Cheers
Mike

**Comment by RickStrahl** [comment]
The dictionaries are stored in the common folder. By default:

`%AppData%\Markdown Monster\DownloadedDictionaries`

If you're using the portable install it'll be in the common folder of the portable installation in `<install folder>\PortableSettings\DownloadedDictionaries`.

Just tried this here and it works for me. If writing to the custom dictionary fails most likely you don't have permissions to write there. Make sure you have MM installed in a folder where your user has WRITE access so configuration data in general can be updated.

**Comment by teacher4711** [comment]
Hi.
Sorry, does not work for me, neither in the installed version nor in the portable version.
At the moment (just to try MarkdownMonster), the portable version is on my Windows 10 x64 desktop, so I have full permissions there.
I also installed the installer version, which is now a sub-folder in my Downloads folder.

Since I have not / did not have to download the German or English dictionaries (because they come pre-installed), there is no such folder: "DownloadedDictionaries", neither in the %AppData% nor as a PortableSettings subfolder.

What might also be interesting is that when adding a word to the dictionary, the squiggly red line does not disappear.

Perhaps I should try making that subfolder myself.

Cheers
Mike

**Comment by RickStrahl** [comment]
MM creates the` DownloadedDictionary` folder when new custom dictionaries are added. But something on your end appears to be blocking the ability to write out the file. Maybe you need to add an exception for AV software to writing in your portable folder? 

When you add a word to the custom dictionary, do you see a message in the status bar? If so the write operation to the file is failing.

**Comment by RickStrahl** [comment]
So I've verified that this wasn't working when the folder didn't previously exist. I think when I was testing I had another language selected and it would automatically downlod that language which creates the folder.

Anyway - there's now an explicit check and creation in place that creates the folder if it doesn't exist when writing out a word to a custom dictionary.
