### ISSUE TITLE
Windows 7 32-Bit - Portable MarkdownMonster 1.12.12 crashes

### ISSUE THREAD

**Issue by teacher4711** [RickStrahl/MarkdownMonster#424]
Hi,

under Windows 7 32 Bit (German) the portable version crashes all the time.

In the attachment, you'll find the debug info from the error message window.
The attachments also show that net framework 4.7.2 is installed.
The tests were run on a virtual machine with VMware Player.

I also ran a test under VirtualBox with the virtual machine images provided by Microsoft (https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/). The Windows 7 32 Bit US version with NET 4.5 and NET 4.7 installed would not even start either the portable or the installation version.

Cheers
Mike
![net_frameword_installed](https://user-images.githubusercontent.com/6697859/44594957-e4937680-a7c7-11e8-800a-f192da829a73.png)
![markdownmonster_crash](https://user-images.githubusercontent.com/6697859/44594958-e4937680-a7c7-11e8-8295-483e3ae0342f.PNG)
![markdownmonster_crash_log01](https://user-images.githubusercontent.com/6697859/44594959-e4937680-a7c7-11e8-9c8a-2ef6fca79645.PNG)
![markdownmonster_crash_log02](https://user-images.githubusercontent.com/6697859/44594960-e4937680-a7c7-11e8-9ada-133ed9598138.PNG)

**Comment by RickStrahl** [comment]
If .NET 4.5 is installed MM will not run - it requires at least 4.6.2. It should tell you on startup that the runtime needs to be updated.

I have a HyperV VM setup for Windows 7 and MM runs fine in there. haven't tried portable - will test that latest.

Can you try setting the following key in the Settings and restart:

```json
"DisableHardwareAcceleration": true,
```

I suspect the issue may be related to video hardware drivers in those particular VMs.

**Comment by RickStrahl** [comment]
So what happened here?
