### ISSUE TITLE
Inconsistent upper-/lowercase naming scheme in menus, typos

### ISSUE THREAD

**Issue by teacher4711** [RickStrahl/MarkdownMonster#425]
# Inconsistencies

Please reconsider the upper- / lowercase naming scheme in the menus.  
As an example, see the following inconsistency: "Edit -> Find next occurrence", which has lower case letters, and "Window -> Close All But This Document", which has all uppercase letters.

## Further typos / punctuation mistakes:
* In "Edit -> "Toggle Spellchecking", 'spellchecking' is written as one word, but in the lower window which indicates when the toggle is active/inactive, spell-checking is written as two separate words.
[spell-checking](https://www.oxfordlearnersdictionaries.com/definition/american_english/spell-check?q=spell-check), see: verb-forms
* "If you forget your password," Here, please add a comma - which you mostly do - when a sentence starts with an if: Rule: [commas with conditional sentences](https://www.ego4u.com/en/cram-up/writing/comma?10)
* In the above message dialog, I would also reconsider the phrasing, which is too long and in parts, redundant.

![spell-checking](https://user-images.githubusercontent.com/6697859/44596533-d2680700-a7cc-11e8-9e4f-ceb73b3befc4.png)
![encrypt_message](https://user-images.githubusercontent.com/6697859/44596535-d2680700-a7cc-11e8-9253-56ef95239d4b.png)

**Comment by RickStrahl** [comment]
Fair enough. If you find additional ones please post them here.
