### ISSUE TITLE
Suggestion: Activation of multiple dictionaries

### ISSUE THREAD

**Issue by teacher4711** [RickStrahl/MarkdownMonster#426]
Since I often have to write in multiple languages, it would come in handy if I could activate multiple dictionaries.
Then, all the unnecessary spelling mistakes would be gone.
This would require to have an additional dialog in which to specify which dictionary an unknown word can be added to.

Thanks,
Mike

**Comment by RickStrahl** [comment]
While that's an interesting use case, I've never actually seen any editor do that sort of thing. I think this would also be confusing and in many, many cases provide completely and unworkable results and bad suggestions.

Overall I feel this will cause more problems than it solves.
