### ISSUE TITLE
Custom Words during spell checking

### ISSUE THREAD

**Issue by conradakunga** [RickStrahl/MarkdownMonster#428]
I am writing a technical resource and a lot of the jargon are not words the English dictionary recognizes.

When you **ignore** a word during a spell check session, where are these stored? If it is a writable store I would like to directly put the words I want ignored there in one sweep rather than one by one.

**Comment by RickStrahl** [comment]
The default location is:

`%appdata%\Markdown Monster\DownloadedDictionaries`

Or you can using **Setting -> Open Configuration Folder**  then click on the **DownloadedDictionaries** folder.

The file will be `language_custom.txt` (for example: `en-us_custom.txt`). You can add words into that text file one line per custom word.
