### ISSUE TITLE
Update About Dialog to Show Licensed Copy of MM

### ISSUE THREAD

**Issue by pkellner** [RickStrahl/MarkdownMonster#433]
**My suggestion:**

- If Not Registered ... what you have is great
- If Registered, add an "Update Registration" menu choice and include in that popup dialog the choice of unregistering or reregistering.  Do include what snagit does in the about, just a non-intrusive "this s/w is registered" label.  I often don't see any kind of unregister or update registration option on s/w.

I think Snagit is a good model to follow since they are somewhat like you.  I looked at Adobe tools and Microsoft and they make it complicated, though licensing is a lot more involved for them.

**Comment by RickStrahl** [comment]
Ok, so here are a few updates:

The About form now shows the status when registered:

![image](https://user-images.githubusercontent.com/1374013/45250849-ef362b80-b2f0-11e8-8d33-cb6571ee4118.png)

The Help Menu caption has been changed so it more accurately reflects the dialog which allows registration and unregistration.

![image](https://user-images.githubusercontent.com/1374013/45250859-2278ba80-b2f1-11e8-9bb1-ed7e0c803b7a.png)

cb7c1157b9630c4ca1679c21b4bafb397cc60d42
