### ISSUE TITLE
Triple ticks with syntax name broken

### ISSUE THREAD

**Issue by wanton7** [RickStrahl/MarkdownMonster#434]
````
```json
{
    "itemId": 1,
    "groupId": 1
}
```
````
Looks like this now
![image](https://user-images.githubusercontent.com/1009930/45282829-bced1f80-b4e4-11e8-9a01-15387f646cb8.png)

This used to work but when I updated to version 1.12.14 it broke.

**Comment by RickStrahl** [comment]
Thanks for reporting... 

Turns out it's an issue with the highlightjs package that MM is using - I've reconfigured it and it looks a few of the languages from before that were included by default are now missing.

Fixed by adding :common back in.  c7204514f628045097baacbd361ceeaa075c1a81
