### ISSUE TITLE
Adds two newlines after pasting text using `Shift+Insert` and immediately pressing a key

### ISSUE THREAD

**Issue by breki** [RickStrahl/MarkdownMonster#435]
When pasting text using `Shift+Insert` shortcut (standard Windows shortcut for pasting), the editor pastes the text, but when you then continue to write text by pressing a key, the editor inserts two newlines and writes the newly pressed character after the newlines. 

Example, if I paste `pasted text` and press `s`, the result would be:

```
pasted text

s
```

NOTE: the alternative pasting shortcut `Ctrl+V` works without this problem.

**Comment by RickStrahl** [comment]
Fixed. 865c79b438e652626918355a24deb12d600620b2

Ugh this was ugly. Still not sure what was causing that change, but explicitly trapping the key and adding to the keybindings is doing the trick.

**Comment by breki** [comment]
Cool, tested it, works. Thanks for the hard work!
