### ISSUE TITLE
System.Windows.Media.DrawingImage

### ISSUE THREAD

**Issue by jenstornell** [RickStrahl/MarkdownMonster#437]
![image](https://user-images.githubusercontent.com/927011/45423840-d2a14700-b694-11e8-8ab8-0ad54ad979fb.png)

**Comment by RickStrahl** [comment]
Hmmm... this is odd. I don't see this. This is on a file in the File browser I assume?

**Comment by jenstornell** [comment]
Yes, on Windows 10.

**Comment by RickStrahl** [comment]
Here's what I see.

![image](https://user-images.githubusercontent.com/1374013/45438433-c3ae9a80-b67c-11e8-8983-276a090a33eb.png)

This is the same spot right?

**Comment by jenstornell** [comment]
Yes, but I use the light theme.

**Comment by RickStrahl** [comment]
Yup must be a different in the MahApps handles these styles. Fixed in: 76178c33e6a475cf82132240e25a420e6ff5aa18
