### ISSUE TITLE
External Interpolated Variables

### ISSUE THREAD

**Issue by DaveJarvis** [RickStrahl/MarkdownMonster#438]
Consider adding interpolated variables sourced externally to the Markdown file. Here's one way this can work:

1. User opens external variables file (e.g., "variables.yaml", "variables.json", or "variables.toml").
1. MM parses keys and values into in-memory dictionary.
1. User opens Markdown file (e.g., "README.md").
1. MM substitutes all variable names with corresponding interpolated values (e.g., `${variable.name.full}` becomes `Jane Doe` in the preview).
1. User changes and saves value of `variable.name.full`.
1. MM re-interpolates the value and updates the preview.
1. User starts to edit the Markdown document.
1. User types `Ja`.
1. User presses `Ctrl+Space`.
1. MM replaces `Ja` with `${variable.name.full}` into the Markdown document, which is the first match for `Jane Doe` from the interpolated variable map.
1. MM updates the preview to show `Jane Doe`  in the final document.

Note that interpolated variables means that the variables can be recursively defined, such as:

```
variable:
  name:
    first: Jane
    last: Doe
    full: ${variable.name.first} ${variable.name.last}
```

See also:

![screenshot](https://user-images.githubusercontent.com/2131950/45590203-396a6e80-b8e8-11e8-8f9a-3d9f4ad7dae6.png)

**Comment by RickStrahl** [comment]
Yes that seems quite doable, but I think this ultimately would be a best fit for an addin rather than directly integrated.

This format for data that you're showing here - is that some sort of custom format? Specific to Scrienvar?  Where else is this used?

I think as far as syntax goes I'd want to go with Handlebar like expressions or else C# style format expressions unless there's a good reason to use `${ }` (Powershell?)

**Comment by DaveJarvis** [comment]
### Syntax

> I think as far as syntax goes I'd want to go with Handlebar like expressions or else C# style format expressions unless there's a good reason to use ${ } (Powershell?)

Also consider not hard-coding the syntax. In Java, properties files use `{}` syntax (without the preceding `$` symbol) are used for programmatic placement holders, such as:

```
message=Today's date is {0}.
```

Being able to mix and match the syntax should be possible. Lots of people are developing various ways of injecting variables into Markdown. Sadly, the Markdown standard doesn't define one particular syntax. Possibilities around the Internet include:

* `{{...}}` - Used by [Assemble](http://assemble.io/docs/Built-in-Variables.html), [Handlebars]([url](https://github.com/helpers/helper-markdown)), and others. Seems to be gaining popularity.
* `#{...}` - By [Aaron Parecki](https://aaronparecki.com/2012/09/01/2/some-enhancements-to-markdown)
* `$(...)` - Jekyll and Julia?
* `${...}` - Scrivenvar and explicit [bash variables](https://unix.stackexchange.com/a/358275/26227)
* `[%...]` - [Multimarkdown](https://ia.net/writer/support/general/markdown-guide)?
* `$...$` - YAML variables defined and available through [pandoc](https://pandoc.org/)

### Data Format

The data format is YAML, but really any data source should be possible, including:

* [YAML](http://yaml.org/)
* [TOML](https://github.com/toml-lang/toml)
* [XML](https://www.w3.org/XML/)
* [JSON](https://www.json.org/)

I chose YAML because it can be parsed by pandoc. The [Chain of Responsibility](https://www.dofactory.com/net/chain-of-responsibility-design-pattern) design pattern or the [Collector, Translator, and Formatter](https://www.codeproject.com/Articles/1076386/Collector-Translator-And-Formatter-Pattern) pattern would seem to apply here. (Alternatively, leaving conversion from one format to another could be considered out of scope and best left to a suitable externally written tool.)
