### ISSUE TITLE
Feature: Paste Image to Azure Blob Storage

### ISSUE THREAD

**Issue by MisterJames** [RickStrahl/MarkdownMonster#44]
My last step in publishing blog entries is uploading my images to Azure blob storage and updating all my image URLs in the post.

I would like to store my credentials for an Azure storage account.  This would permit for a feature where pasting an image into the document would upload the image to blob storage and the editor would inject the required markdown for the URL to the image.

**Comment by RickStrahl** [comment]
Thanks for posting, James.

What is your process when you publish your blog posts? Are you using static Git 'publishing' or are you actually pushing posts to a server?

While this can certainly be added as a fixed feature I wonder if this is really the best approach. Currently MM saves files to disk and then when posts are published pushes the images to the service to figure out where to put the images - this puts the responsibility and the opportunity to determine where the images go onto the server. 

As to hooking this up I there are a couple of ways this could be approached. 

1. **A plug-in that adds a menu option to perform the upload/embed link task**  
This would be somewhat in line what we do with the Screen Capture add-in where there's a separate UI that pops up that starts the screen capture then saves and writes out. The same approach could be used here to specify the name of the resource to save and where it goes (which storage account and what location/name to use for the blob). In your case you'd have an file picker or paste capture that can upload to Azure and then embed the URL to the image into the document. 

1. **Integrate as part of the Save File Functionality in MM natively**    
I like the idea of having multiple ways to save images - it would be cool to have a dialog that pops up whenever images or files are saved have an additional option to push them to Azure or some other upload service. While cool - I think this gets to be a problem picking what should be supported and managing the credentials to connect to each of these services, so I'm a little wary about this.

1. **Add additional Add-in Interfaces that explicitly capture Save Operations**  
Right now the Add-in interface doesn't explicitly have a way to detect when a document is saved, but it could be added which would allow more easily to create an add-in that works with existing save operations (as opposed to a separate button on the menu).

Any way that Azure storage would be implemented it requires storing credentials and encrypt them probably.

**Comment by MisterJames** [comment]
Thanks @RickStrahl.

I'm currently using Hexo + a dedicated branch on GitHub with auto-push to Azure. I'd be open to any changes in my process if I can automate the part about getting the images out.

Since moving my images off of my site in Azure and out to blob storage I've saved a Canadian tonne of cash on hosting costs, so I don't push the images up to my site. That's required me moving the images to Azure blob storage (manually) and getting the path resolved (using Redgate's Azure Explorer).

**Comment by RickStrahl** [comment]
Got it. 

So I just added a couple of small changes to the Add-in interface that allows intercepting `OnSaveImage(object image)` where the parameter is either a filename (if saved from a file picker) or a Bitmap object (when pasted from Clipboard). It's possible to create a plugin that then brings up it's own UI to allow saving the image to Azure. The nice thing about the Add-in extension is that it can capture both file loaded images or pasted images. A standalone addin that implements `OnExecute()` would have to handle those operations and UI on its own. This may still need some UI if you need to specify how the file is saved (name? location?). 

I can set up the base add-in, but I'm wondering what do you actually need to provide as parameters to Blob storage? Just push it into Blob storage as is and get a random Url back  or something else? What would you like your workflow to be and what do you need to specify.

Info can go into an Addin config file and can be encrypted.

I can set up the base Add-in and we can see about tweaking it after to fit your needs. 

It's a good idea - I'm sure you're not the only one. I figure I could create perhaps even a generic one that provides a few options for image posting (Azure Blog, Imgur, other image sites). Even if not this could serve as a template for any other services.

**Comment by MisterJames** [comment]
Personally, I don't care too much about the name, it could be a guid, but I could see how others might like to specify the name. You could autofill with a guid and let users change it.

From a storage perspective, I would need to specify the account and container, and path in the container. It would likely be preferable to have that as a one-time thing, then store that info encrypted as you suggest. When the URL is fetched, it looks like any other image URL (such as https://jcblogimages.blob.core.windows.net/img/2016/11/resize-pictures.png).  The only reason there is a name on this one is because I still have to curate them manually and it's quicker to type a couple words than to go and generate a guid :)

Thanks for taking this seriously!

**Comment by RickStrahl** [comment]
@MisterJames I've started putting together an add-in for this. 

Check it out here:
https://github.com/RickStrahl/SaveToAzureBlob-MarkdownMonster-Addin

Still needs some work especially re: config, but this should be a decent starting point.

**Comment by MisterJames** [comment]
Awesome stuff! ...and I'm not just saying it because it serves my needs ;)

Thanks again Rick...this is great.

**Comment by RickStrahl** [comment]
I'm going to close this issue and we can have any further discussions on this in the add-ins repo.

https://github.com/RickStrahl/SaveToAzureBlob-MarkdownMonster-Addin
