### ISSUE TITLE
Upgraded to version 1.12.16 - September 18, 2018 and MM does not open

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#440]
Hi Rick,
Today I upgraded MM to version 1.12.16 - September 18, 2018 and when it was launching after the installation it asked me if it can restart to apply changes (MM was not even running though).
I chose yes. And now it does not show up when I run it.

**Comment by RickStrahl** [comment]
Can you check two things:

* Check if Markdown Monster is running in your Task Manager? If so Kill the instance that's 'hidden'
* Check your `CommonFolder` path in the `MarkdownMonster.json` file - if that's invalid MM may not start (although there have been mitigations and that may actually be causing a problem). Maybe clear that key and let it reset, then restart MM.

**Comment by ArthurZ** [comment]
The 1st choice worked.
Thanks!

**Comment by RickStrahl** [comment]
Yeah it's not good that there's a hung instance, but I've seen this before as well. I think recent updates that are making some configuration changes have caused some weird circular processing during hte update that causes MM to not shut down properly. Should be fine going forward though.
