### ISSUE TITLE
Document typo about PostsFolder setting

### ISSUE THREAD

**Issue by darkthread** [RickStrahl/MarkdownMonster#441]
Document [Publishing a Blog Post](https://markdownmonster.west-wind.com/docs/_4rg0r0hmd.htm) says `You can always pick a different location or override the PostFolder setting in Tools->Settings, `, but it's in \AppData\Roaming\Markdown Monster\WeblogAddin.json and the setting name is **PostsFolder**, not **PostFolder**.

**Comment by RickStrahl** [comment]
Thanks. Fixed.
