### ISSUE TITLE
Odd issue with links

### ISSUE THREAD

**Issue by mvelosop** [RickStrahl/MarkdownMonster#443]
This is not rendered as it should in version 1.12.17 (nor 16 either)

```
in [GitHub](https://github.com/mvelosop) <br/> 
on [GitHub](https://github.com/mvelosop) <br/>
in [Microsoft](http://microsoft.com) <br/>
on [Microsoft](http://microsoft.com)
```
![image](https://user-images.githubusercontent.com/7357806/45966338-bdc49c00-c022-11e8-8bc5-e693e27ef43e.png)

**Comment by RickStrahl** [comment]
Whoa that's one heck of a strange bug...

It looks like on at the beginning of a line is causing this problem which seems very odd. Changing on to anything else seem to work.

**Comment by RickStrahl** [comment]
Ok after some experimenting this is actually due to a bug in the HtmlSanitation code that's been recently added.

If you go to **Tools->AllowScriptInMarkdown** and turn that on the failure goes away. 

Looks like a parsing error with an overeager RegEx expression that's reading too far forward.

**Comment by RickStrahl** [comment]
This is the issue in Westwind.Utilities:   3e7ed797edd7e91855a56641ae35ed6d24285c20

Fixed the issue over there and will update the package reference in MM for the next update.

Thanks for the report!

**Comment by mvelosop** [comment]
Great @RickStrahl, 

I see, looking for JS events, right?

Thanks!

**Comment by RickStrahl** [comment]
Yup. Verified with the updated library:

![image](https://user-images.githubusercontent.com/1374013/45981698-a5885900-bff1-11e8-8f51-5f23025eff6b.png)

as well as a couple of additional scenarios.

I've pushed up an update to the preview release.

**Comment by mvelosop** [comment]
Thanks! 

I know about the two spaces, this is for a customer that prefers not to use them! 🙂
