### ISSUE TITLE
Spell checker should not consider brackets

### ISSUE THREAD

**Issue by mvelosop** [RickStrahl/MarkdownMonster#444]
Hi,

The spell checker is considering the bracket to be part of the word:

![image](https://user-images.githubusercontent.com/7357806/46040751-1b331880-c109-11e8-961c-f882e298a834.png)

When I select docker it drops the bracket.

Best!

**Comment by mvelosop** [comment]
Something similar here also:

![image](https://user-images.githubusercontent.com/7357806/46041069-e1164680-c109-11e8-8426-8edc2468c565.png)

That didn't happen in the first case!

**Comment by RickStrahl** [comment]
Thanks. Looks like there was a group of symbols that wasn't included in the search expression to break words.

Fixed with: 4d8bc67e99f01e91da11182237f33de9c6bb93fa

![image](https://user-images.githubusercontent.com/1374013/46130700-a37eef80-c1d5-11e8-9f65-19478394b4e2.png)

**Comment by mvelosop** [comment]
Great tip, thanks!
