### ISSUE TITLE
Spell Checking in 1.13

### ISSUE THREAD

**Issue by Philippe91** [RickStrahl/MarkdownMonster#446]
I have just updated to 1.13, and the Spell Checking  option can't be activated anymore (Edit Menu).

**Comment by RickStrahl** [comment]
Yup - see that. You can use the window control box toggle instead. Not sure what happened to the edit menu setting, but should be an easy fix.

**Comment by RickStrahl** [comment]
Yup easy fix. Some of the configuration settings that were added to the menus lost their toggle state as things got moved around.

Fixed: 0fb56886ec442a5458609169ffc922f479b56c2b
