### ISSUE TITLE
Suggestion: add support for blogging on Github pages

### ISSUE THREAD

**Issue by stefanstranger** [RickStrahl/MarkdownMonster#449]
I'm looking into moving my blog to Github Pages. After some investigation it seems that Jekyll can help creating a blog on Github pages.

Would be nice if Markdown Monster would support this straight from the blogging options.

/Stefan

**Comment by RickStrahl** [comment]
Isn't Jekyll just using files to 'store' blog posts? You just store the files on disk in that location and you're done. IOW, I don't see how MM could help in this scenario since there's nothing to publish.
