### ISSUE TITLE
Document Outline Broken by TOC

### ISSUE THREAD

**Issue by DVaughan** [RickStrahl/MarkdownMonster#452]
My TOC addin adds a line:
`[//]: # (TOC Begin)` 
to demarcate the beginning of the TOC. This breaks the Document Outline pane. Subsequent headings are not shown in the document outline.

**Comment by RickStrahl** [comment]
BTW, when you chose this syntax:

```markdown
[//]: # (TOC Begin)

* [Using Both Visual Studio and Visual Studio Code](#using-both-visual-studio-and-visual-studio-code)
* [Open in Visual Studio Code as an External Tool](#open-in-visual-studio-code-as-an-external-tool)
* [Switch Me](#switch-me)

[//]: # (TOC End)
```

was that just a custom syntax or is this based on something (the header and footer)? It seems MarkDig is parsing this as a LinkReference block which seems correct - it appears to be rendering that correctly.

If so I wonder if I should just integrate that same syntax into the Document Outline Renderer which currently generates the HTML comment blocks.

**Comment by DVaughan** [comment]
I didn't come up with that. I found it somewhere when I was researching a way to create a hidden marker.

I rather like the way I can regenerate my TOC from anywhere in the document, so I'd like to retain that ability. But, the document outline is also helpful when working with large documents.

**Comment by RickStrahl** [comment]
It would be useful to find this if there is some sort of standard that is associated with this. 

Quick question: Does the built-in TOC do what you need or is there something your's does that the original doesn't (other than the delimiters which is open to change)? I feel like we should merge whatever overlap there is into the built-in one.

**Comment by DVaughan** [comment]
Yes, merging would be the way to go. 
I prefer the regeneration behavior in mine. I like that I hit the button and it regenerates the TOC at its existing location (not at the cursor position with a prompt). The purpose of the delimiters is to allow that behavior.

**Comment by RickStrahl** [comment]
That's easy to fix and I suppose that makes sense. Seems that would be the natural behavior and I thought it actually works like that but maybe not. I'll take a look.

Let me know if you can find the reference for where you based that parameter signature on.

**Comment by RickStrahl** [comment]
So I checked operation of the built-in outline generation and it **does replace the existing outline** if one exists already. Did you try this recently?

![image](https://user-images.githubusercontent.com/1374013/47464440-dee4ed80-d784-11e8-9480-a0b37b9e0110.png)

**Comment by DVaughan** [comment]
I see now that you're using an XML comment as the delimeter. I'm not sure why I didn't take that approach.
I'd say ditch the dialog. You could add an option for it, but my guess is that most users will intend to regenerate the TOC.
