### ISSUE TITLE
VSTS/Azure DevOps Wiki File Paths

### ISSUE THREAD

**Issue by akarel** [RickStrahl/MarkdownMonster#453]
## Issue
When working with a Visual Studio Team Services/Azure DevOps wiki, the root relative image paths for all the pages are `/.attachments/...` which doesn't work in Markdown Monster. When adding the image path in Markdown Monster it uses the local relative path, e.g. `../../.attachments/someimage.png`. While this format also works in VSTS, I'd like to be able to use the standard root relative path like the online editor defaults to. This would be true of any web reference that refers to the site's root path (`/etc`).

## Questions
1. Is there any setting that can be applied?
1. Or would this be a feature request?

**Comment by RickStrahl** [comment]
MM will always try to create a relative path if possible as long as it's within 2 levels. I think 90% of the time that's what we want. Physical paths tend to be something to be avoided to keep documents portable. 

I get that this is a special use case, but you should always be able to customize the path after it's pasted, right?

So what is the exact path?

**Comment by akarel** [comment]
In the VSTS wiki the `.attachments` folder is at the root of the wiki. So any images/file are referenced using the web root (i.e. `/.attachments`). In MM the file path is just based on the relative location to the folder path of the root folder in the file browser. So a page at the root level will show an image with the relative path of `.attachments/img.jpg` and one subfolder down would be `../.attachments/img.jpg`, etc. It's not a super important issue, just annoying that any images don't render. I quickly wrote a custom markdown parser to handle it, but I was mostly just curious if there was a setting I was missing that would mimic a web root relative path (`/...`).

**Comment by RickStrahl** [comment]
Finally played around with this a little more and I think I might have a good solution for this. Here's some thoughts on what I'm thinking and I have working now:

* Add a YAML Header that sets the path
* `previewWebRootPath: c:\temp\wiki\
* or using a relative path: `previewWebRootPath: ..\..\

Then in your content you can do:

---
useMath: true
previewWebRootPath: c:\temp\
---

```markdown
... some content:
![](/test.png)
... more content
```

and the `/` (or also `~/`) is fixed up to the path you specified above:

```html
 <p><img src="c:/temp/test.png" alt="" /></p>
```

This is only applied during preview.
