### ISSUE TITLE
There's a weird flashing dot in the corner of the editor

### ISSUE THREAD

**Issue by j2jensen** [RickStrahl/MarkdownMonster#457]
I'm just getting started trying MarkdownMonster. When I created a new repository and the README.md file showed up, I noticed that there's a little flashing pixel in the top left corner of the editor space (just below the title tab). It seems to flash at a slightly different cadence than the cursor. It flashes whenever MarkdownMonster is active. If the editor space is focused and then I switch focus to another app then it goes away. If any other portion of the app is focused and I switch focus to another app, the pixel continues blinking.

**Comment by RickStrahl** [comment]
I'm aware of that, but I have been unable to fix it. It's an IE Web Browser control thing and I believe it's related to the editor control that underlies the editor which is the text area that sits behind it. I've tried all sorts of things including moving the editor into negative space and even then that pixel shows. It seems to come and go. I don't see it right now but I have seen it in the past.

**Comment by RickStrahl** [comment]
Closing since there's no immediate fix for this.
