### ISSUE TITLE
Unordered and Ordered Lists have the same keyboard shortcut

### ISSUE THREAD

**Issue by bladewolf55** [RickStrahl/MarkdownMonster#459]
I've been meaning to bring this up for a while. Hovering over the toolbar icons, both unordered and ordered lists supposedly use CTRL-L.

CTRL-L only creates an unordered lists.

Or am I missing something?

(Also, for what it's worth, usability note: capitalizing keyboard shortcuts increases clarity, because keyboards always show capital letters).

**Comment by RickStrahl** [comment]
Latest version has a bit of work in cleaning up the keyboard short cuts and how they are presented. I decided on mixed case which seems to be the most common convention used on Windows.

As to numbered list - there is not shortcut for it at the moment. There's no good match that would match.

**Comment by bladewolf55** [comment]
My original comment about shortcut casing wasn't specific enough, and I see you're starting to change according to what I'd say is the most common case. The key label is upper case, the special key is mixed case.

Ctrl-F
Alt-E
Alt-Shift-H
and hopefully some day: Ctrl-J, K  and Ctrl-J, Ctrl-K

You've got higher priorities, but I wanted to follow up, clarify, and say thanks.
