### ISSUE TITLE
Is there a way to pick my own numbers for numbered items?

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#462]
I understand that markdown takes control of the numbering of numbered items, so I can number them

```txt
1. One
1. Two
1. Three
```

and they'll show up as

```txt
1. One
2. Two
3. Three
```

Ordinarily, I love this behavior, but I've suddenly found an unusual case where I want to number my numbered items deliberately in a way that doesn't increment by one all the time. Is there some way to get

```txt
1. One
3. Three
6. Six
```

to show up with those numbers instead of as follows?

```txt
1. One
2. Three
3. Six
```

I realize this is a _very_ unusual use-case, but I can't be the first person to run into it. By any chance, is there a trick to get this behavior?

**Comment by RickStrahl** [comment]
Yes there are certain edge cases in Markdown that are not easy to accomplish. Your best bet for those rare cases is to fall back to raw HTML.

this works:

```markdown
<div>
2. This is a test<br/>
5. This is another test <br/>
4. This is odd<br/>
1. Unknown<br/>
</div>
```
or maybe more consistently with regular lists:

```html
<ol>
<li value="3">This is a test<br/></li>
<li value="5">This is another test <br/></li>
<li value="1">This is odd<br/></li>
<li value="2">Unknown<br/></li>
</ol>
```

**Comment by bcmadsen** [comment]
That's perfect. Thanks!
