### ISSUE TITLE
Using proportional fonts cursor and textposition doesn't match

### ISSUE THREAD

**Issue by pit2511** [RickStrahl/MarkdownMonster#464]
# The Problem
If I add the proportional font "Roboto" instead of "consolas" in the configuration file and write a new text in an editor window, there is a growing distance and mismatch between the text entry point and the position of the cursor. 

# The version of Markdown Monster
I use the version 1.13.14 under Windows 10

**Comment by RickStrahl** [comment]
Proportional fonts are not supported. Only fixed width fonts can be used...

If you want to follow up on this you can do so on the ACE Editor repo which is what MM uses for editing. Based on this issue I don't see any change happening with this. 

https://github.com/ajaxorg/ace/issues/460
