### ISSUE TITLE
Viewer doesn't start the external program for file link to a PDF or other programs

### ISSUE THREAD

**Issue by pit2511** [RickStrahl/MarkdownMonster#465]
# The Problem
In my Markdown file a link to a pdf in this way `[Link](./docs/test.pdf)` is inserted. If I click in the Viewer on this link, the viewer doesn't open the installed Acrobat Reader with the adressed file test.pdf. If I send the same file via context menu to the Chrome Browser, the browser opens this link without problems. I have the same problem with other registered files e.g. ".xmind" for a mindmap by starting the installed mind mapping tool XMIND.

# The Version
I use the version 1.13.14 on window 10

**Comment by RickStrahl** [comment]
Ok I've added logic to open PDF files externally: 3009f0158845478aa52053e59497a2f5f0bfe946

Available in 1.13.15.2+  preview build now.
