### ISSUE TITLE
Back function in the viewer would be nice

### ISSUE THREAD

**Issue by pit2511** [RickStrahl/MarkdownMonster#466]
# The Suggestion
If I use links inside a markdown file to jump to another markdown files in the viewer, it would be nice to have a button or a keyboard shortcut in the viewer to return to the calling file or go backwards through the jump history. There should be the same functionality as in the web browser.

**Comment by RickStrahl** [comment]
I don't think so. The Web Browser Preview has no state - it's always tied to the active document and its rendered content. If you navigate off you've changed the context completely.  

If you want to go back you can use the tabs to jump back to another document.
