### ISSUE TITLE
Suggestion: Spell Check Command

### ISSUE THREAD

**Issue by conradakunga** [RickStrahl/MarkdownMonster#467]
Is it possible to add a button (and hotkey) to do global spell checking?

This would be brilliant for those of us who have a write - edit cycle so that you can concentrate on writing and then when done spell check or F7 and the engine cycles through all the identified misspelt words and prompts for correction.

Currently, you have to manually skim through the document to identify mistakes.

**Comment by RickStrahl** [comment]
Interesting - that sounds like a good idea. 

Took a quick look to see what it would take to make this work it looks doable. I have a prototype working for single page jumps. Not handling paging at this point as currently spelling errors are checked only on the active view port not for the entire document for performance. Will take a closer look tomorrow.

**Comment by RickStrahl** [comment]
Ok, I've added a couple of new commands to go to next and previous (F7 and Shift-F7 by default) spell checking error. 

Also fixed a few additional spell checking exclusion rules for url and inline markup.

Updated in 1.13.16 (1.14).
