### ISSUE TITLE
Toolbar (middle section) is grayed out

### ISSUE THREAD

**Issue by dergroncki** [RickStrahl/MarkdownMonster#469]
Windows 10 Pro

I am using the latest version. If I open a document the toolbar is grayed out. I need to open “Tools” -> “Settings” to activate the toolbar.

BTW: Editing text will not activate the toolbar.

**Comment by RickStrahl** [comment]
Not sure why you closed this - it does appear to be an issue - specifically when the application starts and re-activates a document. Flipping between tabs activates the toolbar properly but initial document selection apparently does not. Reopening since this is a bug.

**Comment by RickStrahl** [comment]
This should do it: 1576486bfaa8d8de2a763932074b56d1e301023a
