### ISSUE TITLE
Enhance to provide with a helper to create and fill in tables

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#47]
Please enhance the functionality to provide with a helper to create and fill in tables in a manner http://www.tablesgenerator.com/markdown_tables does, or preferably better.
This is because it is tedious to create wide tables with many rows by hand (writing a script is doable, but then it diminishes the value of the editor).

**Comment by ArthurZ** [comment]
And also adding a ToC helper would not harm either.

**Comment by RickStrahl** [comment]
Sound like great add-ins that you can build yourself...

**Comment by RickStrahl** [comment]
This is a good candidate for an add-in.

**Comment by RickStrahl** [comment]
Table Editor support will be landing in 1.88 or so.

Features:

* Interactive cell editing
* Tabbable interface - tab to next field
* Auto-inserted columns - tab after last field
* Easy to insert and delete rows and columns
* Support for **Pipe**, **Grid** and **HTML** tables
* Two-way editing - edit existing Markdown Tables in editor
* Formatted Markdown or HTML output (up to certain column widths)

![image](https://user-images.githubusercontent.com/1374013/34394622-7e397cc6-eafe-11e7-8842-1aed86af0338.png)

![image](https://user-images.githubusercontent.com/1374013/34394644-a4d435ce-eafe-11e7-9894-70f63023622a.png)

![image](https://user-images.githubusercontent.com/1374013/34394651-af275d12-eafe-11e7-9668-e18e44299df9.png)

**Comment by ArthurZ** [comment]
This is awesome .Just tested it. Works very well. 
Thank you very much Rick!
