### ISSUE TITLE
Bookmark links do not work in HTML Exported when viewed in Edge

### ISSUE THREAD

**Issue by dotnetgator** [RickStrahl/MarkdownMonster#471]
A link like `[Link](#Exercise1)` does not work when the document is output to HTML via Save As HTML and viewed in Edge. Clicking on the link has no effect. 

In particular, in the preview.js file that accompanies the output HTML, in the `$(document).on("click", "a"...` handler that starts on line 2, there is a call to `$("html").scrollTop($el.offset().top - 100);`  This call does not appear to function in Edge, though it works fine in both Chrome and Firefox on Windows.

Attaching MD file and generated self-contained HTML file (though it also happens when generating HTML with loose Asset files.)

[Test.zip](https://github.com/RickStrahl/MarkdownMonster/files/2725414/Test.zip)

**Comment by RickStrahl** [comment]
argh - bloody edge.

In Edge it only works with `$("body").scrollTop()` in all other browsers (including the IE WebBrowser control in the previewer) it works with "$("html").scrollTop()".

Fix is:

```javascript
 $("html,body").scrollTop($el.offset().top - 100);
```

Fixed in: d9085e60083ac9d9f0af60f55a2ae8caf6753daf
