### ISSUE TITLE
v1.14.7 installation doesn't use newest editor.htm

### ISSUE THREAD

**Issue by bladewolf55** [RickStrahl/MarkdownMonster#472]
Performing a clean install, the `AppData\Local\Markdown Monster\Editor\editor.htm` file doesn't include the latest change:
`<script src="editor-user-extensions.js"></script>`

**Comment by RickStrahl** [comment]
Did you grab 1.14.5.3 (pre-release)? 

Either way if it's not in there it will be in the next update.
