### ISSUE TITLE
Toolbar stay disabled when used

### ISSUE THREAD

**Issue by dlucazeau** [RickStrahl/MarkdownMonster#475]
I use the last version (01/06).
Steps to reproduce:
1. Select some text
2. Click H1 - it's the same behavior for B, I ...
3. Toolbar is disabled
4. My text is not marked as Header 1
5. I have to click elsewhhere is the editor to re-enable the toolbar
Help is welcome to continue evaluation.

**Comment by RickStrahl** [comment]
What is the exact version number you are running? (Help -> About).

Did you install the preview release (1.14.7.3 or later)? The full release hasn't been updated with toolbar changes yet - probably later today.

**Comment by dlucazeau** [comment]
Installed version is 1.14.7.3, and this is a completely new installation.
So I will wait the next full release.

**Comment by RickStrahl** [comment]
The new version is up now and it has this fixed. 1.14.8

Thanks for following up...

**Comment by dlucazeau** [comment]
Well done!
Thanks for the responsiveness.
