### ISSUE TITLE
Suggestion: Collapse Sections

### ISSUE THREAD

**Issue by Randy-Buchholz** [RickStrahl/MarkdownMonster#477]
The ability to collapse sections of the document at `#` levels would be nice. The `Document Outline` is helpful, but collapsing would allow viewing two sections of content at the same time. This is useful when they are related, but far apart.

Optionally, a horizontal split would be cool.

**Comment by Randy-Buchholz** [comment]
Found it :)

**Comment by RickStrahl** [comment]
Just for clarification. You can get code folding by:

* Enable Line Numbers
* Use the little arrows next to header blocks to collapse
* User the postfix glyph on a collapsed block to expand

**Comment by RickStrahl** [comment]
Code splitting is also possible in ACE - but I have to figure out how to make that work. It's part of the ACE [kitchen sink demo](https://ace.c9.io/build/kitchen-sink.html) - I don't think it's a built-in feature but specifically added for the demo.

**Comment by RickStrahl** [comment]
So spent a bit of time this weekend integrating the split editor feature from ACE into MM. Took a bit of doing but you can now split the editor and get two synced sub-windows that you can scroll and edit independently. Changes made in either pane are reflected immediately in the other.

![image](https://user-images.githubusercontent.com/1374013/51473033-49bfa980-1d1f-11e9-9804-b84569a91c23.png)


Pretty cool - but most of the hard work comes courtesy of ACE editor.

**Comment by Randy-Buchholz** [comment]
Looks nice Rick. This will be helpful.
