### ISSUE TITLE
Menu tooltip for "Underline" and "Strikethrough" both say "Strikethrough"

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#478]
On the menu, hover the mouse over the <strike>S</strike> icon until a tooltip appears. Note that it reads "Strikethrough".

![image](https://user-images.githubusercontent.com/42981101/51498518-a94ba280-1d7b-11e9-9472-9d93763572c6.png)

On the same menu, hover the mouse over the underlined-U icon until a tooltip appears. Note that it also reads "Strikethrough".

![image](https://user-images.githubusercontent.com/42981101/51498488-8d480100-1d7b-11e9-8438-2fdf97846079.png)

**Comment by RickStrahl** [comment]
Thank you. Fixed for the next update.
