### ISSUE TITLE
Bookmark

### ISSUE THREAD

**Issue by jnmwarren** [RickStrahl/MarkdownMonster#479]
Suggestion: It would be nice to be able to bookmark your place in a document. This is helpful if you have a long document and you close it. Then you can come back to the document and to a specific place in the document.

**Comment by RickStrahl** [comment]
That's not really possible as we don't store info for all documents. We do however, store document position for all open documents in the editor and when you close, then restart MM those will all restore with their last position intact.

**Comment by jnmwarren** [comment]
Thanks

John Warren 

    On Wednesday, January 23, 2019, 3:53:52 PM MST, Rick Strahl <notifications@github.com> wrote:  
 
 
That's not really possible as we don't store info for all documents. We do however, store document position for all open documents in the editor and when you close, then restart MM those will all restore with their last position intact.
