### ISSUE TITLE
Do not convert UTF-8 to UTF-8 w/BOM automatically

### ISSUE THREAD

**Issue by ferventcoder** [RickStrahl/MarkdownMonster#48]
I may have missed some setting, but it appears that MM is converting my UTF 8 files automatically instead of just leaving them as they are.

**Comment by RickStrahl** [comment]
Currently files are always saved with the default encoding which is UTF-8 with BOM.

Detecting BOM/BOMless UTF-8 should be easy enough, but dealing with all sorts of other encodings is a lot more tricky. Wonder if that would be necessary.

**Comment by ferventcoder** [comment]
For me, I'm hoping to leave the UTF8 as is.

**Comment by RickStrahl** [comment]
The main issue is if there's no BOM we have to assume the format is UTF-8 which is Ok for Markdown most likely but might be incorrect for other formats.

Why do you care about the BOM? Shouldn't your files have a BOM to properly identify them?

**Comment by RickStrahl** [comment]
I'm looking into it. This should be easy enough to fix for the UTF-8 case anyway.

**Comment by RickStrahl** [comment]
Will  do something along these lines:

```csharp
        /// <summary>
        /// Retrieve the file encoding for a given file so we can capture
        /// and store the Encoding when writing the file back out after
        /// editing.
        /// 
        /// Default is Utf-8 (w/ BOM). If file without BOM is read it is
        /// assumed it's UTF-8.
        /// </summary>
        /// <param name="srcFile"></param>
        /// <returns></returns>
        public static Encoding GetFileEncoding(string srcFile)
        {
            if (string.IsNullOrEmpty(srcFile) || srcFile == "untitled")
                return Encoding.UTF8;

            // *** Use Default of Encoding.Default (Ansi CodePage)
            Encoding enc;

            // *** Detect byte order mark if any - otherwise assume default
            byte[] buffer = new byte[5];
            FileStream file = new FileStream(srcFile, FileMode.Open);
            file.Read(buffer, 0, 5);
            file.Close();

            if (buffer[0] == 0xef && buffer[1] == 0xbb && buffer[2] == 0xbf)
                enc = Encoding.UTF8;
            else if (buffer[0] == 0xfe && buffer[1] == 0xff)
                enc = Encoding.Unicode;
            else if (buffer[0] == 0 && buffer[1] == 0 && buffer[2] == 0xfe && buffer[3] == 0xff)
                enc = Encoding.UTF32;
            else if (buffer[0] == 0x2b && buffer[1] == 0x2f && buffer[2] == 0x76)
                enc = Encoding.UTF7;
            else
                // no identifiable BOM - use UTF-8 w/o BOM
                enc = new UTF8Encoding(false);

            return enc;
        }
```

**Comment by ferventcoder** [comment]
Looks good!

**Comment by RickStrahl** [comment]
Addressed in 1.0.10.

adad528223cd9173c225edeb5168a40b7dd0a559

It'll go up in a little bit.

**Comment by RickStrahl** [comment]
1.0.10 is up on the Web site if you want to try it out.

**Comment by ferventcoder** [comment]
Still in the queue on Chocolatey's community repo? 👍

**Comment by RickStrahl** [comment]
Not pushed to choco just yet. You'd have to grab it from the download page or use Check for Updates on the Help menu.

**Comment by RickStrahl** [comment]
Chocolatey has been updated earlier

**Comment by ferventcoder** [comment]
Tab completion 👍 
![chocolateytabcompletion](https://cloud.githubusercontent.com/assets/63502/20579996/79d27a82-b195-11e6-8971-1b0dbc308c6f.gif)

**Comment by RickStrahl** [comment]
Nice!

**Comment by ferventcoder** [comment]
Announced back on Chocolatey's fifth birthday. I believe the first version it was in was 0.9.10. If you have a PowerShell profile, it may have already set itself there.
