### ISSUE TITLE
Save As

### ISSUE THREAD

**Issue by jnmwarren** [RickStrahl/MarkdownMonster#480]
Suggestion: It would be nice that when you do a Save As that you can save a .txt file as well as an .md file. Since a .md is really a type of .txt file.

**Comment by RickStrahl** [comment]
You can type in any name into the file prompt that you want including `.txt`, so that works fine. It's just not in the drop down list, which I think is reasonable given that markdown is generally not treated as a .txt file especially if you have an editor like MM installed :-)

**Comment by jnmwarren** [comment]
Thanks,

John Warren 

    On Wednesday, January 23, 2019, 3:55:24 PM MST, Rick Strahl <notifications@github.com> wrote:  
 
 
You can type in any name into the file prompt that you want including .txt, so that works fine. It's just not in the drop down list, which I think is reasonable given that markdown is generally not treated as a .txt file especially if you have an editor like MM installed :-)
