### ISSUE TITLE
C# expression suddenly don't work

### ISSUE THREAD

**Issue by physicsLoveJava** [RickStrahl/MarkdownMonster#482]
I used the Snippet Template Expansion very often.
but, today when i use it ,it alter a message box with information as below.

---------------------------
Snippet Execution failed
---------------------------
2 Errors:

Line: 0 - can't find source file “C:\WINDOWS\TEMP\13kz2z1h.0.cs”

Line: 0 - can't find source file
---------------------------
confirm
---------------------------

**Comment by RickStrahl** [comment]
Not much to go on here... 

Please explain what's happening and what your templates are.

**Comment by physicsLoveJava** [comment]
I delete all the C# expression and re-add the expressions, it's ok. I don't know what happened to my Markdown Monster. Thank you for your contribution, I really love this editor!!! :+1::+1: @RickStrahl :satisfied::satisfied:
