### ISSUE TITLE
Line indenting when formatting selected text as code

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#486]
Open new document.

Type single letter 'a' on first line, single letter 'b' on second line.

Select both lines. Press Alt-C to convert to text-as-code. Select "Text - plain text, no formatting". Select "Paste Code".

Now the document looks like this:

```txt
    ```txt
    a
    b
    ```
```

Now view the result in the Markdown Monster Preview, using the "Hipster" rendering theme.

(I notice this with other themes too, e.g., Dharkan and Westwind.)

I am expecting this to result in an indented lines that all have the same indentation. Instead, the first line is indented differently than subsequent lines are:

![image](https://user-images.githubusercontent.com/42981101/52676182-1f0bdf80-2ede-11e9-947a-27906ec32d08.png)

Now do the same steps, but instead of picking "Text", pick "C++", so that the result looks like this:

```txt
    ```cpp
    a
    b
    ```
```

Now the rendering in the preview window shows both the 'a' and the 'b' with the same indentation.

![image](https://user-images.githubusercontent.com/42981101/52676202-38149080-2ede-11e9-80c8-2d6f6ff86710.png)

What is causing the indented first line in the first example, and what should I do differently to fix that?

**Comment by RickStrahl** [comment]
`txt` is not a valid syntax. You'd want to use `text`.

Unfortunately that's some funky behavior in the highlightJs syntax converter that's causing this behavior. I have `txt` mapped in the text syntax, but the text handler is a special case and it ignores that mapping.

I believe `text` and `plain` both work to give you non-formatted formatting :-)

**Comment by bcmadsen** [comment]
Ah! Yes, indeed they do! Thanks!

But `txt` is what you get when you let Markdown Monster pick "Text - plain text, no formatting" from the "Embed Syntax Colored Code" menu, which is why I described the steps the way I did. Maybe that action should result in `text` instead of `txt`?

Also, meanwhile, I note that `perl` is problematic in the same way.

**Comment by RickStrahl** [comment]
So I took a closer look and there are some CSS issues that will help with this. Basically the styling need to have `display: block` for the `pre>code`  block to force the funky spacing to the right place.  I need to tweak the templates to make these all work right. 

As to `txt` vs. `text` MM actually fixes that up. This behavior was changed in highlightJS recently and the code doesn't reflect that change - i'll change and fix that.

Perl - ugh :-) I'll probably just remove that from the included syntax parsers in which case it'll just display as formatted text.

**Comment by RickStrahl** [comment]
Looks like this has been fixed with a recent update to highlightJs I've integrated. Also updated the code CSS to match what the other themes are doing.

![image](https://user-images.githubusercontent.com/1374013/52937446-35150800-3303-11e9-9692-36f6c4b64a3b.png)
