### ISSUE TITLE
Suggestion: Dockable shell window

### ISSUE THREAD

**Issue by GitSkunk** [RickStrahl/MarkdownMonster#489]
It'd be nice if we could have a shell window (or even better, something like ConEmu) docked at the bottom of MM. It'd be especially useful when working with things like Hugo. MM is pretty awesome for Hugo. :)

**Comment by RickStrahl** [comment]
Do you mean just tack it to the bottom, or an integrated shell window? I don't think I want to build an integrated shell experience, but I can see maybe creating an addin that attaches a terminal window that moves with the MM window.

If you're using ConEmu you should be able to activate your shell easily with `ctrl-\``. Getting back is more finicky though.

**Comment by RickStrahl** [comment]
Whipped up a little starter sample addin.

![image](https://user-images.githubusercontent.com/1374013/53298789-c4745c80-37d6-11e9-870e-eec263893cf9.png)

You can check it out here:
[Console-MarkdownMonster-Addin](https://github.com/RickStrahl/Console-MarkdownMonster-Addin)

You need to build this and make sure it ends up in your `%appdata%\Markdown Monster\Addins` folder
