### ISSUE TITLE
Feature request: Allow download of all blog posts

### ISSUE THREAD

**Issue by priyadarshan** [RickStrahl/MarkdownMonster#493]
I would like to use Markdown Monster to update and search all of my past blog posts.

Right now, one needs to click on each post, one by one. The window closes rigth after each click, so one needs to reopen it again and again.

Would you consider adding the option to download _all_ the posts from a given blog?

A check box "Download all", or the ability to select more posts at once and a check box to select all would be excellent!

Thank you for considering this.

**Comment by RickStrahl** [comment]
While I understand the need for this, I don't think this is a good idea. Downloads rely on potentially inaccurate HTML to Markdown conversions, so each document has to be pretty much reviewed carefully before it can be used, so I think it's fair enough to go through one at a time - update it then reupload from the original Markdown, I think. This can also quickly escalate as there's no way to know before you start downloading how many posts there are. I have 1500 posts in blog feed - I certainly wouldn't want to download all that at once - it would take forever.

I suspect this might be a useful feature for people trying to rescue their content from an existing blog for potentially moving to some other technology. Also useful, but again, you have to review each and every post carefully anyway to make sure the conversion from HTML is accurate and working properly.

For now I'm closing this as Won't fix. If others think this is something that should be in MM, upvote the original issue.

**Comment by priyadarshan** [comment]
I understand the need of manually checking. Thank you for the explanation.
