### ISSUE TITLE
Not prompting to save changes

### ISSUE THREAD

**Issue by paulmrozowski** [RickStrahl/MarkdownMonster#5]
If you open a new document, make changes, then do something like open the settings (and don't make change changes), you can click the Close button on the change document and it doesn't warn you to save changes.

**Comment by RickStrahl** [comment]
Hmmm... yeah I can duplicate. That's a regression of some sort this was working fine previously.

**Comment by RickStrahl** [comment]
Yup - due to a behavior difference in the Dragablz Tab control which doesn't activate when you click its close button. Changed logic to explicitly pick up the tab and now it works.

Uploaded new build 0.28.1 from the download site.
