### ISSUE TITLE
Upgrade to 1.0.10.0, 1.0.11.0 will crash

### ISSUE THREAD

**Issue by kkbruce** [RickStrahl/MarkdownMonster#50]
I upgrade 1.0.10.0 from Chochlatey, App will crash, This Event log:

.NET Runtime:

應用程式: MarkdownMonster.exe
Framework 版本: v4.0.30319
描述: 處理序已終止，因為有未處理的例外狀況。
例外狀況資訊: System.UnauthorizedAccessException
   於 System.IO.__Error.WinIOError(Int32, System.String)
   於 System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   於 System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions, System.String, Boolean)
   於 System.IO.FileStream..ctor(System.String, System.IO.FileMode)
   於 MarkdownMonster.mmFileUtils.GetFileEncoding(System.String)
   於 MarkdownMonster.MarkdownDocument.GetFileEncoding(System.String)
   於 MarkdownMonster.MarkdownDocument.Load(System.String)
   於 MarkdownMonster.MainWindow.OpenTab(System.String, MarkdownMonster.MarkdownDocumentEditor, Boolean, System.String, Boolean, Boolean, Boolean)
   於 MarkdownMonster.MainWindow.RestoreSettings()
   於 MarkdownMonster.MainWindow.OnLoaded(System.Object, System.Windows.RoutedEventArgs)
   於 System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   於 System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   於 System.Windows.BroadcastEventHelper.BroadcastEvent(System.Windows.DependencyObject, System.Windows.RoutedEvent)
   於 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(System.Object)
   於 MS.Internal.LoadedOrUnloadedOperation.DoWork()
   於 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   於 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   於 System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   於 System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   於 System.Windows.Interop.HwndTarget.OnResize()
   於 System.Windows.Interop.HwndTarget.HandleMessage(MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
   於 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   於 MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   於 MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   於 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   於 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

Application Error:

失敗的應用程式名稱: MarkdownMonster.exe，版本: 1.0.10.0，時間戳記: 0x58338e33
失敗的模組名稱: KERNELBASE.dll，版本: 10.0.14393.321，時間戳記: 0x57f4c4f0
例外狀況代碼: 0xe0434352
錯誤位移: 0x0000000000017788
失敗的處理程序識別碼: 0x3f0c
失敗的應用程式開始時間: 0x01d245fb7e06d694
失敗的應用程式路徑: C:\Program Files\Markdown Monster\MarkdownMonster.exe
失敗的模組路徑: C:\WINDOWS\System32\KERNELBASE.dll
報告識別碼: d64951d0-5ddf-4aca-b943-7cbca557a675
失敗的套件完整名稱: 
失敗的套件相關應用程式識別碼: 

I re-install from web download, I see 1.0.11.0, same problem, This Event log:

.NET Runtime:

應用程式: MarkdownMonster.exe
Framework 版本: v4.0.30319
描述: 處理序已終止，因為有未處理的例外狀況。
例外狀況資訊: System.UnauthorizedAccessException
   於 System.IO.__Error.WinIOError(Int32, System.String)
   於 System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   於 System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions, System.String, Boolean)
   於 System.IO.FileStream..ctor(System.String, System.IO.FileMode)
   於 MarkdownMonster.mmFileUtils.GetFileEncoding(System.String)
   於 MarkdownMonster.MarkdownDocument.GetFileEncoding(System.String)
   於 MarkdownMonster.MarkdownDocument.Load(System.String)
   於 MarkdownMonster.MainWindow.OpenTab(System.String, MarkdownMonster.MarkdownDocumentEditor, Boolean, System.String, Boolean, Boolean, Boolean)
   於 MarkdownMonster.MainWindow.RestoreSettings()
   於 MarkdownMonster.MainWindow.OnLoaded(System.Object, System.Windows.RoutedEventArgs)
   於 System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   於 System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   於 System.Windows.BroadcastEventHelper.BroadcastEvent(System.Windows.DependencyObject, System.Windows.RoutedEvent)
   於 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(System.Object)
   於 MS.Internal.LoadedOrUnloadedOperation.DoWork()
   於 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   於 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   於 System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   於 System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   於 System.Windows.Interop.HwndTarget.OnResize()
   於 System.Windows.Interop.HwndTarget.HandleMessage(MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
   於 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   於 MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   於 MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   於 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   於 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

Application Error: 

失敗的應用程式名稱: MarkdownMonster.exe，版本: 1.0.11.0，時間戳記: 0x5835f94e
失敗的模組名稱: KERNELBASE.dll，版本: 10.0.14393.321，時間戳記: 0x57f4c4f0
例外狀況代碼: 0xc000041d
錯誤位移: 0x0000000000017788
失敗的處理程序識別碼: 0x3f6c
失敗的應用程式開始時間: 0x01d245fc0b38ba8a
失敗的應用程式路徑: C:\Program Files\Markdown Monster\MarkdownMonster.exe
失敗的模組路徑: C:\WINDOWS\System32\KERNELBASE.dll
報告識別碼: 2259b951-eae8-468f-8ee9-333207286df3
失敗的套件完整名稱: 
失敗的套件相關應用程式識別碼:

**Comment by kkbruce** [comment]
I use command "choco install markdownmonster -version 1.0.6", then "upgrade 1.0.9" is work, then "upgrade 1.0.10" like report problem.

**Comment by RickStrahl** [comment]
Hmmm... the error seems to point at some sort of file access problem.

I've made one small change in GetFileEncoding logic to always read the file in shared mode (which wasn't happening before) so under some circumstances that could have caused an error.

Give another try with the latest current version. I'll post when I have it up.

**Comment by RickStrahl** [comment]
Can you try the build from here and see if that fixes it?

https://github.com/RickStrahl/MarkdownMonster/tree/master/Install/Builds/CurrentRelease

**Comment by RickStrahl** [comment]
I took a look at the logs and it looks your issue was with the sample file in the SampleMarkdown.md file which comes from an older version (and shouldn't be loaded from the write protected folder). Checking with the new code I see no error loading this file although you still can't save in that location. On 1.0.10 you can also get the app to launch I think by clearing the recent file list in MarkdownMonster.json file in the Configuration folder (`%appdata%\Markdown Monster\MarkdownMonster.json`)

**Comment by kkbruce** [comment]
1.0.12, Is work 💕

**Comment by RickStrahl** [comment]
Awesome! 

Thanks for reporting Bruce.
