### ISSUE TITLE
Vim keyboard handler doesn't seem to work

### ISSUE THREAD

**Issue by dracan** [RickStrahl/MarkdownMonster#500]
Hi,

Just trialling Markdown Monster, and I can't get Vim mode to work. I've opened settings, and edited the following based on [these instructions](https://markdownmonster.west-wind.com/docs/_4ti0sbx65.htm)...

![image](https://user-images.githubusercontent.com/567988/54862700-70598b00-4d36-11e9-870a-fdc8ea0189d3.png)

It looks like that documentation is slightly out of date anyway because of the nested `Editor` block in the JSON, but I suspect I edited the correct thing, as `"KeyboardHandler": "default"` already existed.

Unfortunately, Vim mode hasn't been enabled though in the editor. I've tried restarting the app.

Thanks,
Dan

**Comment by RickStrahl** [comment]
Can you try this again in 1.16.2 - looks like for some reason the keyboard handlers weren't migrated when I switched from global load on startup to localized load that handles both initial load and reload when configuration is changed.

Hooked it back up and looks like it's working.

**Comment by dracan** [comment]
Yep, will try when I get home. Thanks for the very quick fix! :-)

**Comment by dracan** [comment]
@RickStrahl Yep, can confirm that this works. Thanks again for the quick fix!
