### ISSUE TITLE
Suggestion: Allow external anchors

### ISSUE THREAD

**Issue by tsvx** [RickStrahl/MarkdownMonster#504]
Does Markdown Monster allow external links with anchors ?

I have tried internal links with anchors and they seem to work. I have tried external local links to the local markdown documents (like `[A link to file C](dirA/dirB/fileC.md)`) and they seem to work either.

Why not to allow the external (maybe local) links with anchors, like `[A link to Section 2 of the file D](fileD.md#section-2)` ?

**Comment by RickStrahl** [comment]
Do you mean for navigation to activate the local file? (as in the last issue you filed). IOW, you're asking that it should strip off the hash and open the file?

**Comment by tsvx** [comment]
> IOW, you're asking that it should strip off the hash and open the file?

No, not quite that. I suggested that it should open (or activate) the local file before the hash *and* go to the link provided after the hash (i.e., go to the linked place in that local file).

For it just resembles how an external link (with anchor) works in a browser.

**Comment by tsvx** [comment]
Here is what I meant. Sorry, I could make something wrong (new to collaboration here):  
There were the first PR #506 from me, just couldn't build the solution. Its commit is in this PR #507 too.
