### ISSUE TITLE
Can't move the vertical split

### ISSUE THREAD

**Issue by dracan** [RickStrahl/MarkdownMonster#505]
I think this is something recently introduced, as I could do this a few days ago. I can't move the virtual split anymore...

![MarkdownMonster2](https://user-images.githubusercontent.com/567988/55057385-f8a29d80-5060-11e9-8b31-e62be12f786e.gif)

**Comment by RickStrahl** [comment]
Not sure - not seeing that here... Does the other slider on the left work?

It's clearly trying to drag instead of grab, but I can't duplicate this on any of my 3 test machines running the latest version (1.16.4).

**Comment by dracan** [comment]
Yep, the slider on the left work fine.

Thinking about this - when I say it used to work - I was trialling it when my laptop was plugged into my dock, so would have been using my normal monitors when it worked correctly. However, I've just realised that when seeing this issue, I'm not docked, and it's just using my laptop screen. My laptop is a Surface Book 2, and uses 200% scaling. Could this issue be scaling not being taken into account somewhere? I'm not at home, so can't test it again when docked at the moment.

**Comment by dracan** [comment]
Just tried setting the scaling to 100% instead of 200%, signing out and back in again, but that still shows the same issue. So looks like it's not scaling.

Will test it again next time I'm docked to my monitors so see if it only happens on my laptop screen.

**Comment by RickStrahl** [comment]
Yeah I thought scaling might be the issue but I've tried setting the scaling mode on my monitors and it still works. If scaling was a problem though I would think that everything would be totally off.

This seems like something is interfering/overlaying on top of the window.

I did make a change in the latest version that's related to tab drag and drop but that only affects the actual tabitem header not the entire editor area (which sits inside of it).  Just to be sure - can you confirm you are on 1.16.4 or later? There were some intermediate builds that might have had drag operations set on one of the other objects. Latest is 1.16.4.1.

**Comment by dracan** [comment]
Just tried it when docked on my monitors, and it has the same problem - so much have been introduced recently. I'm using 1.16.3.7.

Just updated to 1.16.4.1, and it's now fixed! 🎉

**Comment by RickStrahl** [comment]
Ah yes - you had an intermediate preview build when I was screwing around with the drag and drop and probably had D&D set on the container rather than the tab.

Sorry about that, but that's the nature of the preview builds :-) Sometimes stuff slips through.

FWIW I've pushed up 1.16.4.2 which has your vim navigation stuff in it.

**Comment by dracan** [comment]
No worries - I can't complain given the speed you're knocking out these highlight/vim changes! 😁
