### ISSUE TITLE
Trying to map Show Document Outline to keys, failing

### ISSUE THREAD

**Issue by nonplayer** [RickStrahl/MarkdownMonster#508]
Just installed the trial to test out, I'm really needing to hotkey bind the Document Outline tab. My keybindings keep getting reset every time the software reopens, though. I tried searching the docs, but all I found were the default bindings, and no details on what I should do to properly update and save those updates.

I want to use Ctrl+Shift+O to do it. What is the proper function to open that tab? And what do I need to do to keep my changes?

**Comment by RickStrahl** [comment]
Currently there are no keybindings mapped to any of the sidebar tabs so I'm not sure what you would be binding the Ctrl-Shift-O to at this point. Most likely what you're using is an invalid command which is probably why the operation is failing and the file gets overwritten with the defaults again.

I've added explicit menu commands for the three sidebar tabs now however, and you can access them through the menu. The document outline is now accessible via `Alt-V-O`.

As to command shortcuts for these - I'm running out of keys to map with these combinations in a way that's consistent so I'm not sure if I want to excplicitly add mappable bindings for all of them (and if I add one I have to more or less add the others.

One thing that could be done is is use Ctrl-1, 2, 3 for the tabs in order for bindings but again those wouldn't be explictly custom mappable.

The updated menu options are available in the latest preview release.

**Comment by nonplayer** [comment]
This works great. Looks good. Thanks!
