### ISSUE TITLE
Suggestion: Books

### ISSUE THREAD

**Issue by Randy-Buchholz** [RickStrahl/MarkdownMonster#510]
Add the capability to group files into Books.

This can be a simple feature that can grow over time.

On the left, where Files, Outline, and Favorites are, add "Books". A basic book is just a collection of files. The basic function (once a book is created) is Add File:
1. In Books, right click  a Book - a context menu shows the list of files in Files. Select one, and it is linked to the book.
2. In Files, right click a File, the context menu has "Add to Book". Selecting this shows the list of Books. Selecting a Book from the list links the file to the book.

Features can grow over time. Books can have a file order, or hierarchy (progressive enhancement). Eventual capability could allow generation of "sites" (hyperlinked html files) from Books.

Similar capability would change Files into a Tree View, but this prevents sharing files across books.

**Comment by RickStrahl** [comment]
That's a pretty specific feature and maybe something that should be put into an Addin. 

I think the closest we have today in Markdown Monster is the Favorites tab which does allow you to group files together, but there are no group operations on them.

As an integrated feature for the main product - I don't see that happening. But as an addin it sounds like a good idea.
