### ISSUE TITLE
Cycling through tabs in drop down 

### ISSUE THREAD

**Issue by robcxyz** [RickStrahl/MarkdownMonster#514]
This is a suggestion purely for consideration. 

The thing I miss the most when transitioning from vscode to MM is the ability to hit ctrl+tab multiple times and cycle through a list of active tabs from a drop down.  In MM it simply goes right and left (ctrl+shift+tab).  It would be really nice to have ANY kind of way to shortcut to active tabs and I stress ANY as I'm not picky.  It can be through the favorites even as long as I have the ability to quickly add them to favorites (see [#513](https://github.com/RickStrahl/MarkdownMonster/issues/513)) though through a drop down would be absolutely best I'd say. 

Thanks and great tool.

**Comment by RickStrahl** [comment]
Not sure what you mean exactly. If you want to get an actual tab list it's on the Window menu. Alt-W gets you there then arrow keys to navigate.

Code's navigation is a bit different through the command palette which is nice but also a bit confusing if you're new to it. It works great for a pure development editor, but not so great for a more general purpose tool IMHO.

**Comment by robcxyz** [comment]
Alt+w was what I needed thank you so much. 

Definitely going to support your project and advise others to do the same.
