### ISSUE TITLE
I would love if I could copy an image, then paste it directly into a folder

### ISSUE THREAD

**Issue by pkellner** [RickStrahl/MarkdownMonster#516]
I would donate at least one case of beer if it would be possible for me to right click on a "media" folder in my Markdown Monster folder explorer, do a "paste" after I copied an image from something like snag-it, and have it prompt me for a name and put that image in the folder.

**Comment by pkellner** [comment]
Bonus points if it would create two files.  One the original size with some string appended to the name (like _full) and the other image scaled to some preset width or height (I'm hearing a ringing in my ear saying ... "that would be a nice contribution").

**Comment by RickStrahl** [comment]
That's going to be an expensive case of beer that you have to ship to Hawaii. :-)

![image](https://user-images.githubusercontent.com/1374013/57111949-bc0a3780-6cd9-11e9-9c81-9a4e93f30897.png)

**Comment by RickStrahl** [comment]
This feature is actually quite useful to me as well. 

But - you do know that you can paste images directly into the document - right?

As to the 2 image thing - I don't think that's a good idea. Too vague and undiscoverable. But you can easily double click the image and open in your favorite image editor (I use SnagIt's editor) and then use the resize default with a few clicks.

**Comment by pkellner** [comment]
I can't believe I actually doubted you on this Rick.  Of course it's there, and, I do owe you that case of beer.  email me your ground address and your favorite beer, and assuming there is not some law against shipping beer to that little island you live on, keep an eye out.

And, here is present number  2:

> Markdown Monster continues to outshine every major competitor's markdown editor I've tried. There is definitely something to be said for doing one thing and doing that one thing really really well.  My hat is off to the creators of this awesome editor.  Keep up the good work.

**Comment by RickStrahl** [comment]
To be clear I added this earlier - it's not actually in there **yet**. While I was there I refactored the menu logic which was getting too big to live in the file it was defined in. 

Don't worry about the beer - I was only joking :-)

**Comment by pkellner** [comment]
You deserve the beer.  Send me your address and favorite beer.  A deal is a deal.

**Comment by RickStrahl** [comment]
I've uploaded a new build 1.16.15.5 that has the change in it.

I suggest you also set up your Image Editor - you can then right click the image and open it in the editor and resize there (or resize and save as).

**Comment by pkellner** [comment]
I’ll check that out.  I always save a full size un-annotated version of every image I capture just in case (cause you never know).

**Comment by RickStrahl** [comment]
> Markdown Monster continues to outshine every major competitor's markdown editor I've tried. There is definitely something to be said for doing one thing and doing that one thing really really well. My hat is off to the creators of this awesome editor. Keep up the good work.

Appreciate that Peter. Do you think you can tweet this instead - all the customer quotes I use on the site are tweets:  

[Markdown Monster Quotes](https://markdownmonster.west-wind.com#Carousel2)

**Comment by pkellner** [comment]
Maybe I'm missing something.

I can right mouse button inside the markdown editor and it prompts me to paste an image.  I go and make up my own image name and save it.  It then puts it as a reference on in my markdown. I was expecting that from the project file browser, I could right mouse on the folder I want to put the image in, choose an option like "Insert Image From Paste Buffer" and then it would put it there.  From there,  I could drag it out into the editor.  I tend to collect all my images in my media directory, then put them in my docs, not make the docs first.  Am I missing a feature?

**Comment by pkellner** [comment]
moved to new issue
