### ISSUE TITLE
Enhance image insert to have more functionality

### ISSUE THREAD

**Issue by pkellner** [RickStrahl/MarkdownMonster#521]
Be great to have better functionality around inserting images.

- Create Multiple Image at Different Sizes
- Specify relative or absolute file location to store images (mask)
- Scale Image by Percent or Absolute Size with length, width or both specfied (both would skew)
- Camel or Pascal Case Filename option
- Image Border Option (round,square,thickness)
- Image Format (png,jpg)
- Remember Settings as preset (dropdown to toggle between named presets for different projects)

**Comment by pkellner** [comment]
The size option is great and will be a big help. 

I just talked to Snagit about how to what I want on their side and they don't have automation in their editor for macro capability, but they do have a very nice "preset" model on the capture side which I think would be helpful in Snagit.  That is, you can create several options combined together, then when you capture, that "pipeline" of options process.  That pipeline can be named so you can essentially have multiple presets that you use for different scenarios.

Regarding 'refresh' and remembering your last size.  I'm not following what you are doing there. It does not sound like what someone would think of as the intent of 'refresh'.

Regarding 'No'.  I think of the difference between enterprise and consumer tools is that enterprise tools have features like macro's, chaining effects, customizations and consumer tools don't. I think of MarkDownMonster as an enterprise tools so IMHO, it should be 'Yes'.  As a professional docs writer (at the moment anyhow), I tend to write articles like [this](https://github.com/pkellner/edge-developer/blob/dev-tools-chromium-gettingstarted-feature-pkellner/microsoft-edge/devtools-chromium/getting-started/index.md).  You can see I have a lot of screen shots and I have several patterns I use.  Two typical patterns are 1) border/width:500 . 2) noborder/width:300.

That said, I "waste" a lot of time doing an error prone process of saving, editing, resaving, editing, etc.  Snagit does have an option I now know where I can create a hotkey that "recaptures same as last" so that I can at least recapture a few images, each with a different preset (sadly, the mac version does not yet support resize).

So, as an enterprise tool, if I could paste in an image into MarkdownMonster and have it create multiple images with different postfixes, that would be huge and I'm sure not just valuable to me but many others doing the same thing.  Some of your objections cancel each other out if you make this option. For example, I agree that you should never loose your original, un modified image so making an image with borders would be bad. However, if you created multiple images, that border image becomes another image and you still have your original if later you want to do some hand manipulation on it.

Specifically, when I insert, I'd like to see a preset that create all these images (the reason for camel or pascal or snake case is for auto image creation).

edge-devtools-colorpicker.png
edge-devtools-colorpicker-withborder-preset1.png
edge-devtools-colorpicker-withborder-preset2.png
edge-devtools-colorpicker-withborder-preset2.png

where I could name my preset so it would actually come out as

edge-devtools-colorpicker.png
edge-devtools-colorpicker-withborder-withborder-w400px.png
edge-devtools-colorpicker-withborder-noborder-w200px.png
edge-devtools-colorpicker-withborder-preset2-50percent.png



If you were to do this, I know it's not much, but I'd be happy to make a few minute video explaining how I use the flow in building articles.

**Comment by RickStrahl** [comment]
Well I guess we have to disagree on the scope of what goes into a tool like MM. I don't disagree that those features are useful, but they are not appropriate for the **base editor**. Perhaps a more comprehensive and more specialized addin makes sense here but in the base feature set what you propose would just overwhelm the UI for the average user both in terms of what has to be on screen as well as configuration settings.

The other option that you have today is **you can use the Screen Capture functoniality that's built in** to bring up SnagIt automatically. That integrate initiates your capture and then opens the SnagIt editor optionally and from there you can use all of SnagIt's integration tools to create multiple images add effects etc. That seems like a more appropriate place to be doing all the mutations of images than inside of the editor which would never be able to compete with all the effects and features that a full blown image editor like SnagIt's editor provides.

**Comment by marcusyoung** [comment]
@RickStrahl What happened to the image resizing support you added. Seem to have gone?
