### ISSUE TITLE
GitHub-style task lists don't render correctly

### ISSUE THREAD

**Issue by NoahAndrews** [RickStrahl/MarkdownMonster#522]
When I make a task list, the checkboxes render with bullet points next to them.
![image](https://user-images.githubusercontent.com/10224994/57816087-019e1a00-7748-11e9-8c45-9e0d7fcd1fb7.png)

I'm using the default markdig engine, which is interestingly the _only_ engine to render this correctly on babelmark3.

Correct rendering:
- [ ] Task list item 1
- [ ] Task list item 2
- [ ] Task list item 3

**Comment by RickStrahl** [comment]
Which preview theme are you using?

**Comment by RickStrahl** [comment]
Never mind - looks like this is not right in all of them.

Fixed in: b607884d5c158e3282e427a9f041c8cae7c593b9

![image](https://user-images.githubusercontent.com/1374013/57827767-65bedf00-7744-11e9-9ba2-787d945d37e8.png)
