### ISSUE TITLE
Backup improvements

### ISSUE THREAD

**Issue by NoahAndrews** [RickStrahl/MarkdownMonster#523]
It would be great if we could have our settings synced/backed up automatically to a Git repository, like the Jetbrains IDEs support. We should be able to backup the dictionary too, with or without that feature.

**Comment by RickStrahl** [comment]
Hmmm... good idea...

Wonder if we should use Gists instead... Easier than having to deal with repository commits etc. there's already support for Gist integration via the Gist Addin. Maybe that could be an additional feature of the addin.

**Comment by RickStrahl** [comment]
Thinking this could now be added to the new Settings screen. A few options: backup to a backup file location, backup to gist (if Gist support is installed).

One concern is that some settings (paths in particular) are machine specific. Some paths (like recently used etc.) MM is smart enough to remove the bad paths. But for other things like program locations, favorites etc. they may be off if restored to a different machine. Some more thought required here.

**Comment by RickStrahl** [comment]
Basic Settings backup has been added to the Settings form. For now just file based backups. 

![image](https://user-images.githubusercontent.com/1374013/64224881-0a992f80-ce8e-11e9-86fe-080114cd05fc.png)

Backups to Gists will be added later.
