### ISSUE TITLE
how to compile 1.17

### ISSUE THREAD

**Issue by dan-42** [RickStrahl/MarkdownMonster#524]
Hi,

so first of all, MM looks really great! I just started using it, to see if it will suite my needs.
But the very first run is very promising.

So I tried out of curiosity to compile the project, cloned from git.
But opening the Solution always states 
```sh
git\MarkdownMonster\MarkdownMonster\MarkdownMonster.csproj : error  : Project file is incomplete. Expected imports are missing.
```
when going back to ``` 1.16 ``` I can run MM without any issues.

I do have installed ``` .NET core 3.0 preview5 ```  but that did not help.
Is there anythiong else that needs to be installed or changed in visual studio?
I run Visual Studio 2017 Community

Thank you very much!

-dan

**Comment by RickStrahl** [comment]
I believe you need vs 2019 and the 3.0 sdk because of the dotnetcore project formats.

I need to update the docs for requirements.
