### ISSUE TITLE
Manual Heading IDs no longer rendered. Problem with AutoHeaderIdentifiers?

### ISSUE THREAD

**Issue by lozzadude** [RickStrahl/MarkdownMonster#525]
Heading ids details: https://www.markdownguide.org/extended-syntax/#heading-ids

Previously

```### My Great Heading {#custom-id}```

would get rendered as:

```<h3 id="custom-id">My Great Heading</h3>```

I installed the new version of MarkdownMonster just now & I think the introduction of AutoHeaderIdentifiers has broken this. The previous version I was using was 1.12.12 (Aug 16, 2018).

When I turn off AutoHeaderIdentifiers this now gets rendered as:

```<h3>My Great Heading {#custom-id}</h3>```

Is this an issue with markdig or MarkdownMonster?

**Comment by RickStrahl** [comment]
Hmmmm that seems to work for me... (1.17.3)

![image](https://user-images.githubusercontent.com/1374013/58620785-a732ac80-8263-11e9-89b3-f25dc9b1c5fe.png)

**Comment by RickStrahl** [comment]
### Custom Attributes {#custom-id .note }
