### ISSUE TITLE
Question: Is there any way to open XLS and PPT files from "Preview"?

### ISSUE THREAD

**Issue by ragingtom** [RickStrahl/MarkdownMonster#526]
Is there any way to open more types of files (not just PDF) from the "Preview"? I would like for PowerPoint (ppt), Excel (xls) and couple other file types to launch their linked application. 

Thank you!

Tom

**Comment by RickStrahl** [comment]
Added additional explictly handled extensions including most Word documents that should now open in the appropriate applications.

Note this is handled through MM and only works inside of MM. if you export your HTML to run in a browser the default browser behavior will kick in which likely won't do anything with most document types.

Fix is in: a96690b3fdded33e5021a5ea0c82436e6846b1f9

**Comment by ragingtom** [comment]
Thank you. This is awesome ! 

Is there any reason to white-list file extensions? I would allow any file to be opened, as long as it exists on the file system. I have custom graph data (*.xgr) that also needs to "pop". *.7z files also come to mind as "good to have".

**Comment by RickStrahl** [comment]
The fear is that you may have something that starts executing. .exe/cmd/bat/ps is probably not a good idea if you were to just shell execute it. There are all sorts of other formats. But maybe we can add a whitelist config property that you can add to if needed.

I'll add .7z.

**Comment by ragingtom** [comment]
Customizable white list would be nice! Please find time to add it :)

Alex

**Comment by RickStrahl** [comment]
So no customizable list but I've reworked how files are opened which should allow for most file types to be opened if they are mapped in Windows. Known text file types will open in the editor, executables open in explorer (most common types) and everything else shell executes.

Take a look in 1.17.5.2 and later.

**Comment by ragingtom** [comment]
I test all extensions that I use and all of them work as expected! Thank you!
