### ISSUE TITLE
Dictionary from one revision to another

### ISSUE THREAD

**Issue by jnmwarren** [RickStrahl/MarkdownMonster#527]
I have been adding words to MM 1.17.3 and then I just upgraded to MM 1.17.5. I then copied the file PortableSettings/DownloadedDictionaries/en-US_custom.txt to the new revision 1.17.5. However, the new revision did not see the words that I had already added to the file revision 1.17.3. Is there a way to copy added words from one revision to another without having to keep adding those words in every new revision.

**Comment by RickStrahl** [comment]
That should just work assuming you copy it into the same folder and the portable install is configured the same way.

But - that's one of hte problems with portable installs - you're responsible for maintaining file locations and support files. If you use the full install it'll use a fixed shared location that doesn't need updates and you can choose to put that shared location into a sharable location like Dropbox.

One way for you to do all this with a shared install is to install to something like DropBox in which case the app should work from anywhere you have access to DropBox (or OneDrive) etc. including your configuration.

**Comment by jnmwarren** [comment]
I will try an install to Dropbox. Would you do the install as portable then?

**Comment by RickStrahl** [comment]
If you want to share between machines and setups yes.

You can also point your configuration folder to a different folder (dropbox or other shared folder) from a full install.

[Sharing Configuration Settings on DropBox/OneDrive](https://markdownmonster.west-wind.com/docs/_4x20odmu3.htm)
