### ISSUE TITLE
Adding a table of contents without headings results in an error

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#529]
Create a new document. Add text, but don't add any headings. Instruct MM to add a table of contents.

![image](https://user-images.githubusercontent.com/42981101/59706611-a2ec1600-91b5-11e9-8b6f-4ff135f906be.png)

Doing so results in an error, but probably shouldn't. Yes, this user is asking for something that doesn't make sense in this situation, but MM should be able to deal gracefully with this, perhaps by gently reminding the user that it can't add a table of contents if there are no headers in the document.

![image](https://user-images.githubusercontent.com/42981101/59706714-e2b2fd80-91b5-11e9-99cb-1a9f2345a816.png)

As it is, the error message seems a wee bit harsher than it really needs to be.

**Comment by RickStrahl** [comment]
Thank you. Fixed. 46074377db94e26614da0aa0ed6629ba6d402b11
