### ISSUE TITLE
Feature: Allow "scroll to markdown" from context menu in preview window

### ISSUE THREAD

**Issue by crowcoder** [RickStrahl/MarkdownMonster#53]
It would be very handy to be able to go to the markdown line from the preview window, with a context menu or similar method.

**Comment by RickStrahl** [comment]
You can set the preview mode globally to `PreviewAndBrowser` which keeps both panes in sync, both ways.

Use Tools -> Settings to get to the Settings file, then change the `PreviewSyncMode` property to `PreviewAndBrowser`. 

![image](https://cloud.githubusercontent.com/assets/1374013/20652060/9ef7338a-b496-11e6-81ef-4002f8524e16.png)

More info on modes here in the docs: 
http://markdownmonster.west-wind.com/docs/_4nk01yq6q.htm#SettingValues

**Comment by RickStrahl** [comment]
FWIW, v1.0.17 and later now have dropdown on the statusbar that lets you change this more easily:

![](http://markdownmonster.west-wind.com/docs/images/PreviewModeSelection.png)

There have also been some fixes to a few issues that made the sync not work in a few edge case scenarios.
