### ISSUE TITLE
Copy and Paste in Project Explorer Seems to just copy path

### ISSUE THREAD

**Issue by pkellner** [RickStrahl/MarkdownMonster#532]
I may be confused, but I'm use to webstorm where I select a file in my file explorer. do control-c, go to the top of another directory tree and do control-v and the file copies there.  Is this not the behavior expected in MM?

I can show-in-explorer, and then do it in explorer (and get what I expect).  I'm a little sick this week so may be missing obvious things (more than usual anyhow).

**Comment by RickStrahl** [comment]
That's not implemented in MM. The file Explorer only has so many features - it's not a complete Explorer replacement (although it's slowly getting there  :-))

You can drag and drop files between trees.

I'll take a look about copy/paste operations.

**Comment by RickStrahl** [comment]
I've added basic support for Cut, Copy and Paste operations. It works with files copied within the folder browser, as well as with Explorer files (or any other apps that use the FileDrop Shell APIs).

![image](https://user-images.githubusercontent.com/1374013/59961149-702d7080-9488-11e9-9876-a91ff87dfec8.png)

It's probably still a little rough, but if you want to take a look, grab the latest preview release from the download page.

**Comment by pkellner** [comment]
thanks!
