### ISSUE TITLE
Create new document from template

### ISSUE THREAD

**Issue by fullcavediver** [RickStrahl/MarkdownMonster#533]
Please allow the creation of a document from template. This feature is often used when creating documentation in MD format.

Thank You!

**Comment by RickStrahl** [comment]
You can pretty much what you want with Snippet Templates. You can create your templates as code snippets and then embed those with shortcut text, hotkeys or by opening the snippet tool.

![TemplateExpansion](https://user-images.githubusercontent.com/1374013/60042378-75e6aa00-9672-11e9-9008-381ed6520ee6.gif)

Note that you set up a template with a shortcut expansion key that when typed in editor is expanded. You can also use C# code expressions in the snippets.

File templates aren't a bad idea, but would require a whole separate opening UI to make that happen...

**Comment by fullcavediver** [comment]
Hi Rick,

as a matter of fact, snippets are better then templates. Thank you very much for the quick solution.
