### ISSUE TITLE
New document - UTF-8 (with BOM)

### ISSUE THREAD

**Issue by fullcavediver** [RickStrahl/MarkdownMonster#534]
If I create a new document with Markdown Monster portable, it is in UTF-8 format and I don't any possiblity to change to UTF-8 (no BOM). Is it a bug, or I'm doing something wrong?

**Comment by RickStrahl** [comment]
Currently there's no support for setting encoding. MM will preserve encoding of existing files, but when you create a new document it'll be UTF-8 (no BOM).

**Comment by RickStrahl** [comment]
Added ability to set the encoding of the document in the statusbar.

![image](https://user-images.githubusercontent.com/1374013/60057281-d852a100-9698-11e9-8107-e732bf39209a.png)

**Comment by fullcavediver** [comment]
that's perfect! Thanks a lot, Rick! Cool!
MM always created UTF-8 with BOM file and I had to convert it with notepad ++. Now this procedure is obsolete :-) Thank you for the prompt solution!
