### ISSUE TITLE
Horizontal scrollbar not enabled in editor when word wrap shut off

### ISSUE THREAD

**Issue by brandonh-msft** [RickStrahl/MarkdownMonster#535]
If I go to `View | Toggle Word Wrap` and uncheck it, I get this:
![image](https://user-images.githubusercontent.com/20270743/60057284-d8eb3780-9698-11e9-85b8-9b98fbf9f456.png)

Notice how they aren't wrapping, but they're cutting off on the righthand side. The horizontal scroll bar for the editor is disabled:
![image](https://user-images.githubusercontent.com/20270743/60057315-f15b5200-9698-11e9-9cd8-3b28f5ae902f.png)

**Comment by brandonh-msft** [comment]
If I go to `View | Toggle Word Wrap` and uncheck it, I get this:
![image](https://user-images.githubusercontent.com/20270743/60057284-d8eb3780-9698-11e9-85b8-9b98fbf9f456.png)

Notice how they aren't wrapping, but they're cutting off on the righthand side. The horizontal scroll bar for the editor is disabled:
![image](https://user-images.githubusercontent.com/20270743/60057315-f15b5200-9698-11e9-9cd8-3b28f5ae902f.png)

**Comment by brandonh-msft** [comment]
oo found it! `Toggle Centered Layout`

I turned this off and got back to me left-aligned text. However, when word wrap is shut off the horizontal scroll bar doesn't enable; this seems necessary to get to the text that isn't wrapped.

I'll leave this open, but I'm changing the title.

**Comment by RickStrahl** [comment]
Ok I can sort of duplicate this behavior. 

It works properly if I use Alt-Z hotkey to toggle.

However, if I use the menu to toggle the mode then the horizontal scrollbar is disabled. Not really sure what is different there because behind the scenes this is all going through the same settings and bindings. Ultimately the horizontal scrollbar handling is automatic in the browser control.

I have a feeling this one won't be fixable as its an IE quirk, but I'll see what I can dig up.

**Comment by RickStrahl** [comment]
Odd - tried to capture the failure with ScreenToGif and I was unable to make it actually fail. Running without it though it fails pretty consistently but only if I use the menu to toggle modes. Very odd.

![ScrollbarIssues](https://user-images.githubusercontent.com/1374013/60058969-54e87e00-969f-11e9-9445-649a449acdd6.gif)

**Comment by RickStrahl** [comment]
Give this a try in 1.18.5.2 or later.

**Comment by brandonh-msft** [comment]
will do - i'm using chocolatey and I don't think we've got anything past 1.18 out there right now. But I'll update once I get a new version.

**Comment by RickStrahl** [comment]
1.18.5 went out to Chico today but it doesn’t have this fix in it yet.
