### ISSUE TITLE
Alt+Z keyboard shortcut doesn't toggle word wrap

### ISSUE THREAD

**Issue by brandonh-msft** [RickStrahl/MarkdownMonster#536]
`View | Toggle Word Wrap` says the keyboard shortcut is `Alt+Z` but when I do that shortcut, word wrap doesn't toggle.

**Comment by RickStrahl** [comment]
Hmmm... I can't duplicate that behavior. You might want to check your key bindings to make sure Alt-Z isn't mapped to something else?

**Comment by brandonh-msft** [comment]
looks like the ever-useful nVidia GeForce Experience is mapped to this system-wide 🙄

**Comment by RickStrahl** [comment]
Ooops...
