### ISSUE TITLE
[Chocolatey] Don't create shims for other EXEs

### ISSUE THREAD

**Issue by bc3tech** [RickStrahl/MarkdownMonster#537]
When installing MM (portable) from choco, many extraneous shims are created:
~~~
markdownmonster.portable package files upgrade completed. Performing other installation steps.
Extracting C:\ProgramData\chocolatey\lib\MarkdownMonster.Portable\tools\\MarkdownMonsterPortable.zip to C:\ProgramData\chocolatey\lib\MarkdownMonster.Portable\tools...
C:\ProgramData\chocolatey\lib\MarkdownMonster.Portable\tools
 ShimGen has successfully created a shim for MarkdownMonster.exe
 ShimGen has successfully created a shim for mm.exe
 ShimGen has successfully created a shim for pingo.exe
 ShimGen has successfully created a shim for wkhtmltopdf.exe
 ShimGen has successfully created a shim for csc.exe
 ShimGen has successfully created a shim for csi.exe
 ShimGen has successfully created a shim for vbc.exe
 ShimGen has successfully created a shim for VBCSCompiler.exe
 The upgrade of markdownmonster.portable was successful.
~~~

I think we should be creating shims just for mm.exe and MarkdownMonster.exe 

You can avoid creating the others by [creating shim ignore files](https://chocolatey.org/docs/create-packages#how-do-i-exclude-executables-from-getting-shims) as part of the install script.
I tried to fork your repo and do the work as a PR, but it doesn't look like the choco build files are up-to-date in `master` as there isn't even a `\tools\` directory (which is ref'd by the `.nuspec` file)

Let me know if you need assistance! You can see an example of this in [my chocolatey build for Franz](https://github.com/bc3tech/chocolatey/blob/master/Franz/tools/chocolateyinstall.ps1#L20).

**Comment by RickStrahl** [comment]
The `tools` folder was excluded for some reason (accident). Some of the files are generated (the zip and verification.txt). But it's there now.

**Comment by RickStrahl** [comment]
Seems to me the way this would have to be fixed is by adding the `.ignore` files into the distribution for `pingo.exe.ignore` and `wkhtmltopdf.exe.ignore`?

**Comment by bc3tech** [comment]
yup if those files are statically present, that'd be what you could do to make sure they aren't shimmed.

**Comment by RickStrahl** [comment]
Added these to the `.\build` file

```
# dont' add shims for support exes
out-file -filepath ..\Distribution\pingo.exe.ignore  -InputObject ""
out-file -filepath ..\Distribution\wkhtmltopdf.exe.ignore  -InputObject ""

out-file -filepath ..\Distribution\roslyn\csc.exe.ignore  -InputObject ""
out-file -filepath ..\Distribution\roslyn\csi.exe.ignore  -InputObject ""
out-file -filepath ..\Distribution\roslyn\vbc.exe.ignore  -InputObject ""
out-file -filepath ..\Distribution\roslyn\VBCSCompile.exe.ignore  -InputObject ""
```
I guess next release explicitly uninstall first, then re-install.

Can't remember whether shims are also created in the full install...

**Comment by bc3tech** [comment]
They are - I had to add one for Franz for its `FranzSetup.exe` :/

**Comment by gep13** [comment]
Shims will automatically be created for any .exe that is placed in the package folder, I.e c:\programdata\chocolatey\lib\markdownmonster(.portable).  If the files are placed outside of this folder, for example in the Program Files folder then shims are not automatically created but you can create them in your chocolateyInstall.ps1 file if required.

You also have the option of creating the .ignore files in your chocolateyInstall.ps1 file rather than adding physical files into your package, if you would prefer to go that route.

**Comment by bc3tech** [comment]
thanks for the insight Gary!

**Comment by RickStrahl** [comment]
@gep13 I added the ignore files to the portable package but only for Chocolatey. The standalone version doesn't have them - IOW, they get added when the package is built.

From Gary's description it sounds like the full package won't add shims so there should be nothing to do there - MM adds its own global pathing to MarkdownMonster.exe and mm.exe.

**Comment by gep13** [comment]
@RickStrahl sounds perfect.

In the next release of the portable package, you might want to look at what happens with the existing shims, i.e. in an upgrade scenario.  Off the top of my head, I can't say what will happen.  It could be that you need a one addition to the chocolateyInstall.ps1 file to remove the shims, if they exist.  But worth checking if they get removed as part of the upgrade.
