### ISSUE TITLE
Issues using the Folder Browser

### ISSUE THREAD

**Issue by akordowski** [RickStrahl/MarkdownMonster#538]
I discovered some issues using the `FolderBrowserSidebar`. This is tested with the version 1.18.5.

* In a empty folder create a new folder
* The 'folder up' icon disappears
* Creating a new file, creates a file in the new folder, not in the current folder
* 'Refresh folder' brings the 'folder up' icon back
* Go to the new folder
* Create a new file
* 'Refresh folder'
* File is disappearing
  * The file is actually created in the `C:\Users\username\AppData\Local` folder, not in the current folder.
  * Trying to create a file with the same name returns the error 'The file already exists'

![markdownmonster](https://user-images.githubusercontent.com/9746197/60197892-aa0fc580-9840-11e9-9433-f8f5fcb891e8.gif)

**Expected behavior**

* The 'folder up' icon should not disappear
* New folders/files should be created beneath the 'folder up' icon

I would like to contribute a bugfix.

**Comment by RickStrahl** [comment]
Can you try this in 1.18.10 or later as there have been changes how the `..` folder is handled. I think this is working correctly now but please check your exact use case if you have a chance.

**Comment by RickStrahl** [comment]
There are a few more fixes related to renaming that are related to this problem in post 1.18.10 (not out yet).
