### ISSUE TITLE
A setting "CenteredModeMaxWidth" should probably be DPI aware

### ISSUE THREAD

**Issue by mdonatas** [RickStrahl/MarkdownMonster#541]
On 4K screens the default MD editing column is too narrow. It's basically an equivalent to 485px on a 1920px width screen.

Suggestion is to multiply it by DPI scaling.

On the other hand if it was your intention to have it look this way on a 4K screen, think how wide it is on 1920px screens :)

Maximized view on a 4K screen.
![image](https://user-images.githubusercontent.com/483659/60278012-54522080-9907-11e9-9916-f9f0d92a73f6.png)

**Comment by RickStrahl** [comment]
Well the max-width is set with a fixed pixel width and you can adjust that.

While I can detect that it's an expensive operation to do and that restyling of the editor happens relatively frequently. Also - the value becomes meaningless if it's adjusted so I think the better choice is to adjust the value in the settings to fit your needs. It's also going to cause issues if you move hte editor across windows with multiple resolutions.

There are no easy solutions that work well with this AFAIK.

**Comment by RickStrahl** [comment]
Turns out - RestyleEditor/GetJsonStyleInfo already retrieves the DPI ratio anyway, so this is actually an easy fix and it seems to work nicely.

**Comment by mdonatas** [comment]
This kind of turnaround is just amazing. You really do love this product :)
Also Github is a great tool in all of this interaction, I probably wouldn't have bothered with these reports had I needed to send an email or somesuch.
Thanks!

**Comment by RickStrahl** [comment]
Thank you. If the issues are useful and relatively easy to get in I'm more than happy to get them in as soon as they come up. Bigger feature issues can sit for a while though before I decide to tackle them...
