### ISSUE TITLE
double-clicking on an empty area in a document bar should open new document

### ISSUE THREAD

**Issue by mdonatas** [RickStrahl/MarkdownMonster#542]
Opening a new document when an empty area on a tab-bar is double-clicked is a rather common behavior in tabby apps. Notepad++, VS Code, various browsers support that.

This would be nice. I've hit this issue withing the first minute of opening MM for the first time.

**Comment by RickStrahl** [comment]
Thanks - added. Bear to find the right place to intercept this but small fix :-)

**Comment by mdonatas** [comment]
Thanks!
