### ISSUE TITLE
Insert Link then Paste as a Reference inconsistency

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#543]
1. Ctrl+N to start a new document.

1. Ctrl+K to insert a link.

1. Add `https://www.apple.com/` to both Link Text and Link edit boxes.

1. Click the "Link as a Reference" checkbox. (Why? Because I want to know what it does.)

1. Click "Paste Link".

At this point, nothing happens. I still don't know what "Link as a Reference" does, but that's not the bug I'm here to report.

Now do all of the same steps, except for one change. This time, instead of pressing Ctrl+K to insert a link, now hover over and then click the "Insert Link (Ctrl+K)" menu toolbar button, but otherwise, do all of the same things.

This time, we get one of those panicky "Something went wrong" message boxes.

![image](https://user-images.githubusercontent.com/42981101/60376294-bae84480-99c2-11e9-8e1b-4cb94e22e3cb.png)

It seems to me that if nothing is going to happen in the first case, nothing should happen in the second case.

Now that I'm here anyhow, I'll go ahead and ask this:

I checked the online documentation looking for help on "Link as a Reference". If it's there, I missed it. So what would be an expected use case where I might want to use "Link as a Reference", and what should I expect it to do for me?

**Comment by RickStrahl** [comment]
Yup I can duplicate that. References work by creating a label with a referenced link that's referenced at the end of the document.

Looks like this works Ok with a selection, but totally fails when you just paste the image, or even if you change the text of the label - the label text is completely ignored.

Fixed two issues:

* Data conversion issue failure  
(reversion when switched to Reflection based COM for .NET Core 3.0)
* Not properly picking up the link text

Both should be fixed now.

**Comment by bcmadsen** [comment]
I'm still able to reproduce this situation with the new build, 1.18.6.0.

![image](https://user-images.githubusercontent.com/42981101/60454213-1fd0b400-9be8-11e9-9fe9-41ba6e622dc5.png)

![image](https://user-images.githubusercontent.com/42981101/60454263-3d9e1900-9be8-11e9-90b7-e52b5b9fe926.png)

![image](https://user-images.githubusercontent.com/42981101/60454271-4393fa00-9be8-11e9-8918-203cabf360eb.png)

**Comment by RickStrahl** [comment]
Please give a repro. Works for me with:

* No text selected
* With text selection in place

![LinkReferences](https://user-images.githubusercontent.com/1374013/60454928-003a8b00-9bea-11e9-8918-b8f4dfd1c703.gif)

**Comment by bcmadsen** [comment]
When you bring up the "Embed Link" dialog, are you doing that with "ctrl+K" on the keyboard? I don't see your mouse hovering over the toolbar button, so I'm guessing you're not using that button.

Do this: 
* Start with an empty document. Keep it empty throughout the experiment. Literally, don't type anything into the edit window. Literally, start with a blank document, and keep it that way.
* Then click on the toolbar button -- do NOT use "ctrl+K" to bring up the Embed Link dialog.
* Then do what you're doing -- enter http://www.apple.com and select Link as a reference and Paste Link.

You should see that "Something went wrong" error if you do all of those things.

Weirdly, the "Something went wrong" error only appears if you use the toolbar button, but doesn't if you use "ctrl+K" from the keyboard.

**Comment by bcmadsen** [comment]
Postscript: the video is helpful -- thank you for that -- and I see now how I can use this feature to add a link as a reference -- but only if there is already text in the document. Your examples work for me too, in that case. However, I'm suggesting that you'll find that if the document is empty, your example doesn't add a referenced footnote. It simply does nothing at all.

**Comment by RickStrahl** [comment]
Ok I can duplicate that now. Super edge case though as you're unlikely to start a document with a link. 

Fixing...

**Comment by bcmadsen** [comment]
Yes, I agree with that, especially now that I see what it's supposed to do. I needed it to see it do something though, before I was able to understand that.

**Comment by RickStrahl** [comment]
26f305f20ba4730db6e3b4882284ac54219275b0

**Comment by bcmadsen** [comment]
Got it -- thank you!
