### ISSUE TITLE
Default file extension

### ISSUE THREAD

**Issue by matthewdw** [RickStrahl/MarkdownMonster#547]
I'd like to suggest having a default file extension when using the file browser to create new files.  I right click and select "new file" and intuitively I will just give it a name without an extension.  Without realising, this causes file association to break as well as things like sending to PDF.

For me, I'd like the default to be .md but I can imagine some people may want different extensions so it could be configurable.

**Comment by RickStrahl** [comment]
The problem with that is if you need to create a file that doesn't have an extension as is common these days in source and documentation repositories. It's a little more effort to type an extension but it gives you the full range of options.

**Comment by RickStrahl** [comment]
The problem with that is if you need to create a filename that doesn't have an extension (which these days tends to be common in documentation or code repos). Frankly I think it's better being explicit than appending a default extension.

**Comment by matthewdw** [comment]
Well it could work like Windows explorer.  The default being set in the options somewhere.  I suspect most people use .md for 95% of the files they create.  Personally, I keep forgetting to put .md whenever I create the new file which causes mild irritation each time I double click the new file and get Windows asking me which program I want to open it in!

![327DBA81-9A42-4BD1-87B9-A9E77ACF7DE5](https://user-images.githubusercontent.com/52383197/60766209-4e460780-a09e-11e9-9b2d-b09e2719700f.GIF)

**Comment by RickStrahl** [comment]
Hmm yeah I like that actually... I’ll take look.

**Comment by RickStrahl** [comment]
Added this functionality:

![NewFileBrowser](https://user-images.githubusercontent.com/1374013/60918438-9da15900-a293-11e9-9304-b037bcee3786.gif)

**Comment by matthewdw** [comment]
Looks great!

**Comment by matthewdw** [comment]
Hi Rick.  I've just downloaded 1.18.8 to try out this feature.  Would you consider enhancing this little feature even further and having the filename portion (README) pre-highlighted as soon as you create the new file?  Your screen capture above suggests this is how it works but actually you have to manually highlight README in order to choose your own file name.

This is really just nit picking and already the feature is great!

**Comment by RickStrahl** [comment]
You need to download the preview release (1.18.8.5 or later I think).

**Comment by matthewdw** [comment]
Ah ha no its a bug when creating files in sub directories.  Will raise a bug.  Thanks.
