### ISSUE TITLE
Switching between tabs (documents) using Ctrl+Tab does not update the focus

### ISSUE THREAD

**Issue by breki** [RickStrahl/MarkdownMonster#551]
When you use Ctrl+Tab hotkey to switch between multiple open documents, the app does not change the focus to the newly top/active document (and there is no blinking cursor there). Instead, anything you type still ends up in the previously active document that is now hidden underneath the top document.

Version: 1.18.8

**Comment by RickStrahl** [comment]
Thanks for catching this one...

**Comment by breki** [comment]
No problem, it was not that difficult since I switch between documents
constantly ;-). Enjoy your vacation!
