### ISSUE TITLE
"Markdig.Syntax.Inlines.CodeInline" unexpected

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#552]
Open a new document. Enter this text:

```text
# One
# `Two`
# Three
# Four `Five`
# Six
```

Now open the Document Outline:

![image](https://user-images.githubusercontent.com/42981101/61403100-69c4c580-a889-11e9-9d12-56cfb0209f0e.png)

Note the "Markdig.Syntax.Inlines.CodeInline" appearances there.

**Comment by RickStrahl** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/1374013/61580360-75c2b880-ab11-11e9-9591-6a4bbcdbfe00.png)
