### ISSUE TITLE
Can HTML character codes be color-coded in bullet lists?

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#553]
Open a new document. Add this text:

```text
&ldquo;Lorem ipsum dolor sit amet &hellip; consectetur adipiscing elit,&rdquo;
* &lsquo;sed do eiusmod &hellip; tempor incididunt&rsquo;
* &lsquo;ut labore et dolore &hellip; magna aliqua.&rsquo; 
```

Observe the result:

![image](https://user-images.githubusercontent.com/42981101/61414533-0e073600-a8a3-11e9-9acb-c7f714d59566.png)

Notice that the HTML character codes (\&hellip;, \&rdquo; and so forth) are color-coded except when they appear in a bulleted list. If it's not a problematic ask, can we color code them there too?

**Comment by RickStrahl** [comment]
This formatting comes from ACE editor and their default Markdown processing.  Their Markdown syntax processor is super complicated.

The best thing to do to get this fixed would be to raise this in the ACE repository...
