### ISSUE TITLE
Right clicking an red underlined word results in error dialog popup

### ISSUE THREAD

**Issue by umernalla** [RickStrahl/MarkdownMonster#554]
If I right click a word which is red underlined in the editor, an error dialog pops up stating 'Specified cast is not valid'

![MMerror](https://user-images.githubusercontent.com/7393520/61644663-01b51b80-ac9d-11e9-96e6-e1409648c2e7.png)

I am using registered version 1.18.8

**Comment by umernalla** [comment]
Ok - just installed 1.18.10 - and it seems to be fixed...

**Comment by RickStrahl** [comment]
Yes there was a brief bug in a recent version (not the last one) that caused this. Has been fixed for a bit.
