### ISSUE TITLE
File is not saved until MM is closed

### ISSUE THREAD

**Issue by markusvdr** [RickStrahl/MarkdownMonster#555]
I open my readme.md from within Visual Studio with MM. Edit the file and press Ctrl+S, which should save the file. I continue to build the final release and send it to my client, just to discover afterward that the readme.md released with the code has not changed.  Of course, once I close MM all the updates to my file is there.  Is there a way to actually save the file when you save the file.

**Comment by RickStrahl** [comment]
That shouldn’t be the case. What does the save indicator show on the tab after you save? It’s the * symbol if the file is dirty....

Save operations are synchronous for explicit save operations so if Ctrl-s fails for any reason it
 Should show you an error message.

FWIW I can’t duplicate this, so it’d  be helpful if you could describe your exact steps for saving and maybe explicitly save and check the file on disk with a second editor. Thanks.

**Comment by RickStrahl** [comment]
So I took a closer look at this and I can't see the behavior you describe.

An easy way to test this is by using MM and VS Code in combination to open the same document. Open the doc in MM, then open VS Code with the same file and put the editors side by side. Now make changes to the document in MM and Save - you should immediately see the saved content also in VS Code.

When I do this I immediately see the changes reflected in the file in VS Code, which indicates that the changes are saved.

If this is not the case there are a few things that could be a problem:

* Missing File Permissions
* Disk failure (full disk, out of space etc.)
* Invalid File name

Any of those errors however should show an error message either as a pop up message box or on the toolbar (if auto-saving).

**Comment by markusvdr** [comment]
Hello Rick, 

 

I tried replicating the problem again (immediately after your initial quick reply on the problem – thanks - unfortunately, I already closed VS and MM), and the saving worked (Just as you described) after starting VS and MM. 

 

I have not used MM since, and suspect it may be related in the way I use VS with my projects, sometimes VS can remain open for days. 

 

When/if I reproduce the problem I will make detail notes. It might very well be permission related. Here are some things I know

*	I am using an older MM version 1.13.14.
*	auto-saving was off.
*	When the problem occurred I also tried saving through the menu (Clicking File/Save) which did not work. 
*	Disk space on SSD is OK. 

 

I think it must be something else on my PC that caused the problem.  The file is obviously saved by MM but did not reflect in Smart GIT or VS.

So no action is required from your side until I can replicate the problem. 

 

Best regards,

Markus Van Der Riet

**Comment by markusvdr** [comment]
Hello Rick, 

 

Replicated the problem sort of.

 

I opened MM alone (without VS). MM opens with a couple of files that I edited previously. 

 

I edited a line and saved it (it worked). The name of the file is README.md.

 

I undo the save (or I edited the file – I cannot remember) . In any case, the file was dirty. 

I added three letters: “qwe”

I just left it there. Later the computer was in sleep mode. 

 

Later today I tried to save the file, and the file would not save, it remained dirty: 

See the screenshot below: 

 



 

The MM backup file exists, and the original does not contain “qwe” 

 



 

Now I can continue to edit the file README.md, it remains dirty and I cannot save the file. 

 



 

I also checked via process explorer (from sysinternals)  if README.md was opened by MM, it was not.

 

This is not exactly the behavior I have seen before (the render of the mark-down was never missing), but I think it shows there is some file state mismatch after sleep. 

 

I hope this helps.

 

Best regards

Markus Van Der Riet

**Comment by RickStrahl** [comment]
Hmmm... it looks like some other problem as the preview apparently isn't there either? If the menu is disabled there likely is some problem with detection of the active document which is not good.

Are you on the latest version (1.18.x?)  There have been a number of fixes in 1.17 I think, related to the document state and also the preview refresh that might actually fix the issue you are describing.

**Comment by markusvdr** [comment]
I updated from 1.13.x to 1.18.10 and so far has not seen the same problem. I think the problem is related to the way I work by keeping the MM and VS open for many days. I will report the problem if I can reliably repeat the behavior. 
Thanks.
