### ISSUE TITLE
Editor is using UNIX-style newlines

### ISSUE THREAD

**Issue by bladewolf55** [RickStrahl/MarkdownMonster#556]
I pulled the latest source for MM and also TOC, and I'm puzzled because of the information found in 

<https://github.com/RickStrahl/MarkdownMonster/issues/332>

I'm seeing \n used for linefeeds, as returned in the `MarkdownDocumentEditor.GetMarkdown()` method.

And the TOC addin only converts Environment.Newline, which on Windows is of course \r\n.

`string[] lines = markdown.Split(new string[] { Environment.NewLine }, StringSplitOptions.None);`

For my own sake, I'm going to build this workaround in TOC, but hopefully the line endings become consistent soon.

```csharp
// UNIX line endings workaround
markdown = markdown.Replace("\r", "").Replace("\n", Environment.NewLine);

string[] lines = markdown.Split(new string[] { Environment.NewLine }, StringSplitOptions.None);
```

**Comment by alexwiese** [comment]
I believe this is what the TOC addin should be doing:

    string[] lines = markdown.Split(new string[] { "\r\n", "\n" }, StringSplitOptions.None);

This way it will split on both **CRLF** and **LF** plus it doesn't have the limitation of doing a "double split" on **CRLF**. It can also handle a mixture of different line endings. 

Example:

    "Line 1<LF>\nLine 2<CR><LF>\r\nLine 3<CR>\rLine 3 continued"
         .Split(new string[] { "\r\n", "\n" }, StringSplitOptions.None);

Result:

    Line 1<LF>
    Line 2<CR><LF>
    Line 3<CR> Line 3 continued

**Comment by bladewolf55** [comment]
@alexwiese That's sensible code. I think the issue is one Rick previously addressed, which is that MM should be using \r\n on Windows. Extending that, MM should also use \n on Linux, and \r on Mac.

In short, the ACE editor should be using whatever the OS's default linefeed characters are. If this were working, then the TOC addin wouldn't need to be changed because Environment.NewLine would automatically work on Linux and Mac as well.

We could debate converting end-of-line if passing documents around, but for this issue I think the solutions are (and were previously):

*   Windows version of MM definitely uses standard linefeed: \r\n
*   TOC code remains as is, using Environment.NewLine

**Comment by alexwiese** [comment]
@bladewolf55 that's OK so long as Markdown Monster/ACE is the only thing editing the file. For example I have MD files in a git repo, when I commit them git automatically converts the line endings for me.

**Comment by bladewolf55** [comment]
@alexwiese I agree. How other apps convert line endings isn't my concern here. GIt, for instance, can be configured so it doesn't convert line endings, but the reason it does is to try to keep Windows line endings as \r\n, as I'm sure you realize.

So, now we wait for @RickStrahl, who is, of course, busy just like the rest of us. I'm hoping this is just a regression bug and he can pull the correct linefeed behavior from a previous commit.

**Comment by bladewolf55** [comment]
Or, @alexwiese, it might be something for you as a contributor. I just started a new job and can't make time to figure it out and make a pull request.

**Comment by RickStrahl** [comment]
I think this should be an easy fix. I’m traveling this week without a computer though and can’t look at this until I get back this weekend.

**Comment by bladewolf55** [comment]
Thanks, Rick!

**Comment by RickStrahl** [comment]
So a little more background. 

MM doesn't do anything specific to the newlines in a document. ACE can deal with NewLines either as CRLF or just LF and it will by default leave them in the specificied format it is loaded with (which may include mixed modes).

I believe the default though is unix and so as you edit new text will end up with Unix line endings.

I started out with explicitly enabling Windows line endings but there were a lot of complaints. Honestly I'm not sure that we should care about Windows line endings anymore at this point. Even Notepad now can properly manage `\n` and display line breaks properly, so I'm not sure where you might have issues with Unix linebreaks.

The big problem is there's no good way to detect the format, and then if you pick one you'd have to explicitly convert the document which slows everything down as you'd have to read and replace.

So as far as MM's main handling of line breaks goes I think the way it currently works is Ok - there haven't been any recent complaints so the \n seems to be better than \r\n which causes problems with other systems and Git sharing usually.

**Comment by RickStrahl** [comment]
The TOC issue then needs to be fixed to default to using unix style line endigings for consistency to treat it like other text entered. But @alexwiese's point of course is spot on - for reading it should be able to convert either type.

**Comment by bladewolf55** [comment]
How about a config setting passing through to `editor.session.setNewLineMode("windows")`? One problem I see is for AddIn writers and people like me who write snippets and C# commands. I expect Environment.NewLine to work correctly, as the author of TOC obviously did as well. By defaulting to Windows line endings--since MM is currently Windows-only--it's a non-surprising experience.

You're right that other editors handle all three line ending styles, but many convert to the OS environment, notably VS Code and Notepad++. VS Code allows setting the line-endings to use on new documents, and converts on copy/paste, but detects a document's endings on open and maintains them.

<https://stackoverflow.com/a/39532890/1628707>

I'd love to live in a world where there's only one line ending sequence--my choice would be CrLf because it's technically correct--but I don't see it happening and I think we still need to care about them. Do you both see a conventional pattern that MM could follow? VS Code is now a major multi-platform editor, so it could be a good model. 

1. Default to OS end of line for new documents and pasting.
2. Leave alone (but detect) opened documents' end of line.
3. Allow the user to set the default, and to convert the document's ending.

If this is something you're interested in, I can pursue it in a couple of weeks after returning from vacation.

**Comment by RickStrahl** [comment]
The problem I see with this is that you constantly will end up changing file endings if you're dealing with files out of Github. If a repo is maintained with Unix style endings and you set up for Windows style endings you're effectively touching every line in the file to change the line endings. While Git is now better about fixing up line breaks for repos, it's still a problem in edge cases and certainly in your local file comparison tooling. Personally I prefer to keep things in whatever format they are and let Git deal with it which minimizes needless conversions.

As I said, MM uses ACE Editor's default which is Unix style `\n`. I ask again why do you even need Windows style line endings given that just about any editor these days understands `\n` just fine? I'm not trolling, I'm just trying to understand because I've gone through this process when I removed the original CRLF formatting some time ago and my conclusion was that `\r\n` is just not necessary anymore. At this point it just seems a lot easier all around to use `\n` and not explicitly set anything to `\r\n` - I just see no upside to that anymore.

The other reason I'm hesitant is that adding explicit crlf/lf selection complicates a number of other support tasks that will have to explicitly convert things. It also requires reformatting the entire document each and every time it's saved which adds some overhead that I'd prefer to avoid unless there's a good reason.

I'll take a look at what VS Code does with this to perhaps get a better feel for why we might need CRLF support.

**Comment by bladewolf55** [comment]
(I know this has become super long. I'll end up writing a blog post on the topic.)

I appreciate your thoughtfulness on this, Rick. Let me be sure I understand your concerns.

1.   MM would be constantly changing line endings if working with documents created on other OSs and stored in a Git repo.
2.   There are other methods in MM that would have to convert endings.
3.   Why even worry about line endings? Just use LF in Windows.

The short answer to all of the above is:

> Following the principle of least surprise, MM should behave like other text editors with regards to newlines. It's what your customers will expect.

Here's the good news: The ACE editor *already behaves like other text editors*. See my testing, below. The only thing that I'd like is setting a user-configurable default newline sequence.

## Behaviors
I think I haven't been clear about the proposed behavior, and how VS Code (VSC) works today.

*Constant Linefeed Changing*

> Again, spoiler: ACE does this already.

1.   MM would detect a newly opened document's linefeed environment. If a new doc, then the MM default is used. This is how VSC works.
2.   MM would *not* change line endings if the opened document uses LF. This is how VSC works.
3.   MM *would* change line endings on copy/paste to match the document's linefeed environment, same as VSC.

I think there wouldn't be the continuous linefeed conversions that you're worried about. Also, whatever's happening in VSC has no performance drag I've seen.

*Why even worry?*

Let's answer that with, 

## "What's MM's copy/paste/open behavior with respect to line endings today?"

I tested this using HxD and Notepad++. HxD does no conversion of text, N++ uses CRLF by default.

**Test Round 1 - Verify existing document behaviors**
1.  Create new MM doc, and copy/paste N++ lines into it.
2.  Copy/paste MM lines into HxD.  
    The CRLF is preserved.
3.  Manually enter new text lines after the previous ones in MM.
4.  Clear HxD, copy/paste new MM lines into HxD.  
    The new text lines *maintain* CRLF. No mixed-mode.
5.  Insert a new text line at the top of the MM doc. Clear/copy/paste that line with linefeed into HxD.  
    CRLF is maintained.

**Test Round 2 - Verify new document behaviors**
1.  Open new MM doc
2.  Press [Enter]
3.  Copy/Paste from N++ at cursor
4.  Select all, copy/paste to HxD  
    LF is used. N++ linefeeds were converted.

1.  Save a N++ file, and a MM file. Close files in MM.
2.  Open the MM file and verify in HxD.  
    LF is used.
3.  Open the N++ file and verify in HxD.  
    CRLF is used.

ACE works just like VS Code, N++, Visual Studio, et. al. Which means all of your edge cases using GitHub will still exist. 

My opinion--and what I'm seeing so far in almost every other text editor--is that a text editor *should* 

1.  Default to the OS's standard linefeed sequence precisely because it's expected.
2.  Respect the linefeed sequence in an existing document.
3.  Avoid mixing linefeed sequences.
4.  Let the user configure a different New Document default if desired.
5.  Ideally, let the user *change* the line endings. But this might be out of scope for MM's purpose.

**Editors Tested**  
*   Markdown Monster
*   Visual Studio
*   VS Code
*   Notepad++
*   LINQPad (always converts to CRLF)

## Market and Usage

Being technical, a Git repo isn't "maintained" in Unix-style. That's strictly a maintainer desire/request. It's the user's configuration that determines whether and how line endings are converted. (Unless the repo itself has a .gitattributes file) 

[Configuring Git to handle line endings - GitHub Help](https://help.github.com/en/articles/configuring-git-to-handle-line-endings)

I agree with you on this point; I want to not worry about what line endings I'm using and let Git take care of it.

What about non-Git users?

I don't know what you've found the typical MM user's demographic to be, but I'm honestly not sure it matters.

*   If they're all coders, then they--like I--will mostly expect the editor to behave like all their other editors with regards to line feeds.
*   If they're not coders, but share files with other users via email, DropBox, etc., then all bets are off. *Except* that the editor should respect the original document (which ACE) does.

Previously, I said that as a coder I'd expect Environment.NewLine to work. Given the above testing, I have to change my mind. There's no guarantee that any text editor's file that's open will be using the platform's standard newline sequence. So, in the TOC addin--in fact, any place a linefeed is manually replaced--a custom function should be used that allows for any sequence.

## Wrapup
In the end, while I understand, sympathize and even agree with you on not wanting to worry about line endings, we still have to. But because of how ACE works, the change I'm requesting (and would happily work on) becomes a lot easier, right? 

Thanks for taking time with this. It's not a small detail, and I'm not surprised it's taking a few iterations to fully address.

One more thing: would you like me to code and submit a pull request for TOC? Or is there a separate maintainer for me to contact? I can't get to it for two weeks, but would be happy to help since it's affected me multiple times. (I use TOC a lot in documentation.)

**Comment by RickStrahl** [comment]
I think we should keep this open. I will take a closer look at the LF issue once I am back home and have more time and a better work environment.

What I think would be relatively easy to do is:

* Add a config switch for unix,windows, default (default to unix - leave as is)
* Set the editor on init (that part is easy enough)
* Anywhere we inject anything respect the appropriate carriage return format
* Do nothing for save/load operations (same as now - ie. let ACE handle it)

**Comment by RickStrahl** [comment]
I've added the configuration switch and the code that applies it to the editor. 7420056c1fe8f39bf67cf5acca53d9afdabe26ae

For now the update code for TOC is not there yet.

**Comment by RickStrahl** [comment]
As to the TOC addin you have to take that up with the Addin author and his repository.

FWIW, The document outline in MM natively can produce a TOC so you may not need the TOC addin. To do this:

* Open the Document Outline Panel
* Click on the TOC icon in the Panel Header

**Comment by bladewolf55** [comment]
Merci de Paris! I'll with with the TOC maintainer. I add TOC for export,
for external documentation.

**Comment by RickStrahl** [comment]
Have you tried the built-in support? What does the other TOC tooling do that the built-in does not? We should add that if it's something important so no separate addin is required.

**Comment by bladewolf55** [comment]
Well, heck, I didn't know that TOC feature existed!

The only differenceI immediately see is that the TOC Addin ignores headings before the insertion point. This is handy because a user can then get this output, which works well for documentation.

# TITLE (Heading 1)

## Contents

* [Heading 2](#heading-2)
	* [Heading 3](#heading-3)
		* [Heading 4](#heading-4)


## Heading 2

### Heading 3

#### Heading 4


If you add that feature (possibly as an option), I can safely uninstall the addin. In the meantime, I'm *still* going to uninstall it and just fix the TOC by hand as needed.

**Comment by bladewolf55** [comment]
Thanks for the changes, Rick. One unrelated question (which I can open separately if you want). Forking the MM repo from GitHub no longer results in a build-able solution. It depends on having a related folder. Is this your intent?

```xml
<Reference Include="Westwind.TypeImporter">
      <HintPath>..\SupportAssemblies\Westwind.TypeImporter.dll</HintPath>
    </Reference>
```

**Comment by RickStrahl** [comment]
Just tried it and it works for me. I can build the project.

There are occasional compilation problems with SDK projects and external references - says it can't resolve a reference. You can clean and rebuild and it'll work. Not sure why that is or even how to reliably reproduce it but I see it occasionally too.

But it should just work with a clean pull. If you have an existing project you likely have to clean the project or potentially wipe the `bin` folder.
