### ISSUE TITLE
Presentation mode is broken with the preview type set to external window

### ISSUE THREAD

**Issue by NoahAndrews** [RickStrahl/MarkdownMonster#559]
The main window just shows a blank white screen

**Comment by RickStrahl** [comment]
Yeah that's not right. Have to see how to fix that. I think what'll need to happen is to reset the view to internal preview when presentation mode is active as it depends on the internal viewer holding the preview pane.

**Comment by NoahAndrews** [comment]
Yeah, that's what I was thinking.

**Comment by RickStrahl** [comment]
Fixed in recent update.

**Comment by RickStrahl** [comment]
No, you have to grab the preview release from the download page.

**Comment by NoahAndrews** [comment]
Ahh, I didn't know that was a thing.
