### ISSUE TITLE
HTML preview in new Window

### ISSUE THREAD

**Issue by kkbruce** [RickStrahl/MarkdownMonster#56]
Have possible  open HTML preview in new Window?

**Comment by Mehul** [comment]
+1

**Comment by RickStrahl** [comment]
So you want an external window so you can do what exactly? Move the window to  a separate monitor or leave it up?

**Comment by Mehul** [comment]
Hmm, I would prefer just to have a keyboard shortcut like Alt-M or something that opened the preview in the default browser.

**Comment by RickStrahl** [comment]
Alt-v-p opens the current rendered output in the default browser. It re-renders the entire view.

We can't keep that in sync though, because MM does all sorts of direct DOM manipulation to improve the preview speed.

**Comment by Mehul** [comment]
Ah yes, nice, missed that ALT-V-B opens in browser. Thanks, that helps me and you're probably right about Bruce's suggestion.

**Comment by kkbruce** [comment]
I want move the window to a separate monitor.

**Comment by RickStrahl** [comment]
Added initial support for external preview window and options to switch between internal and external preview modes.

Added in: 212f453bbfcd3096f1c6b4597695dc5eefa4605c and 12747e07678b164ff8a2ade5bc50765ebc04b9bc

**Comment by RickStrahl** [comment]
Here's what this looks like:

![image](https://user-images.githubusercontent.com/1374013/33289237-fba3505a-d362-11e7-91bc-4934554f6d08.png)

There will also be support for docking the preview window and always force the Preview window to the top of the Window stack.

**Comment by kkbruce** [comment]
Thanks @RickStrahl
