### ISSUE TITLE
Clean clone of MarkdownMonster repo doesn't build correctly

### ISSUE THREAD

**Issue by bladewolf55** [RickStrahl/MarkdownMonster#561]
Rick: I decided to open a separate issue for this, since I have more information for you. For reference, here's the previous history.

**2019-08-24 [charles]**

Thanks for the changes, Rick. One unrelated question (which I can open separately if you want). Forking the MM repo from GitHub no longer results in a build-able solution. It depends on having a related folder. Is this your intent?

```xml
<Reference Include="Westwind.TypeImporter">
      <HintPath>..\SupportAssemblies\Westwind.TypeImporter.dll</HintPath>
    </Reference>
```

**2019-08-24 [rick]**

Just tried it and it works for me. I can build the project.

There are occasional compilation problems with SDK projects and external references - says it can't resolve a reference. You can clean and rebuild and it'll work. Not sure why that is or even how to reliably reproduce it but I see it occasionally too.

But it should just work with a clean pull. If you have an existing project you likely have to clean the project or potentially wipe the `bin` folder.

**Today [charles]**

> But it should just work with a clean pull.

Sorry, but it doesn't. I did find one setting to change in VS 2019, described below, but a clean clone of just MM won't build properly.

I cloned to a completely separate folder tree so there wouldn't be any relative references resolved, i.e. C:\_Test\MarkdownMonster.

The first error I had to resolve was this, which was occurring in multiple projects. Importantly, the MarkdownMonster project wouldn't load. I did have Microsoft.NET.Sdk.WindowsDesktop in folder (`C:\Program Files\dotnet\sdk\2.2.203\Sdks`, but not the 2.2.300 folder, despite installing every SDK and runtime hosting.

> C:\_Test\MarkdownMonster\MarkdownMonster\MarkdownMonster.csproj : error  : The project file cannot be opened by the project system, because it is missing some critical imports or the referenced SDK cannot be found.
> 
> Detailed Information:
> C:\Program Files\dotnet\sdk\2.2.300\Sdks\Microsoft.NET.Sdk.WindowsDesktop\Sdk not found. Check that a recent enough .NET Core SDK is installed and/or increase the version specified in global.json.
> 

I found the solution to this issue here. Since I'd never had problems using the .NET Core SDK prereleases before, I didn't know to check this setting.

<https://github.com/dotnet/arcade/issues/3035#issuecomment-502720454>

After explicitly enabling "Use previews of the .NET Core SDK," the solution loaded all the projects and resolved the NuGet dependencies.

However, when I built the MarkdownMonster project (before any others, as you've stated), although the build succeeded I got two instances of this error.

> Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1605	Detected package downgrade: Westwind.Utilities from 3.0.29 to 3.0.26. Reference the package directly from the project to select a different version. 
 ScreenCaptureAddin.Test -> ScreenCaptureAddin -> Westwind.Utilities (>= 3.0.29) 
 ScreenCaptureAddin.Test -> Westwind.Utilities (>= 3.0.26)	ScreenCaptureAdd.Test	C:\_Test\MarkdownMonster\Tests\ScreenCaptureAddIn.Test\ScreenCaptureAdd.Test.csproj	1	

And, when I further built the entire solution, I got these additional errors.

> Error	CS0012	The type 'DotnetObject' is defined in an assembly that is not referenced. You must add a reference to assembly 'Westwind.TypeImporter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.	MarkdownMonster.Test	C:\_Test\MarkdownMonster\Tests\MarkdownMonster.Test\MarkdownTests.cs	21	Active
> 
> Error	CS0012	The type 'ObjectProperty' is defined in an assembly that is not referenced. You must add a reference to assembly 'Westwind.TypeImporter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.	MarkdownMonster.Test	C:\_Test\MarkdownMonster\Tests\MarkdownMonster.Test\MarkdownTests.cs	62	Active
> 
> Error	CS0012	The type 'ObjectProperty' is defined in an assembly that is not referenced. You must add a reference to assembly 'Westwind.TypeImporter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.	MarkdownMonster.Test	C:\_Test\MarkdownMonster\Tests\MarkdownMonster.Test\MarkdownTests.cs	63	Active
> 
> Error	CS0246	The type or namespace name 'DotnetObject' could not be found (are you missing a using directive or an assembly reference?)	MarkdownMonster.Test	C:\_Test\MarkdownMonster\Tests\MarkdownMonster.Test\MarkdownTests.cs	39	Active
> 
> Error	CS0234	The type or namespace name 'TypeImporter' does not exist in the namespace 'Westwind' (are you missing an assembly reference?)	MarkdownMonster.Test	C:\_Test\MarkdownMonster\Tests\MarkdownMonster.Test\MarkdownTests.cs	9	Active

Please note the TypeImporter errors. This is what I reported before. The only place I've seen the TypeImporter assembly is as part of the KavaDocs addin projects. In MarkdownMonster.csproj it's referenced in a relative parent folder. 
```txt
    <Reference Include="Westwind.TypeImporter">
      <HintPath>..\SupportAssemblies\Westwind.TypeImporter.dll</HintPath>
    </Reference>
```

Since I don't have that project, or the SupportAssemblies folder, on my machine, there's no way the assembly can be loaded.

Maybe that assembly should become a  NuGet package and MM references it that way?

**Comment by RickStrahl** [comment]
Several things:

You need to have a .NET 3.0 Preview SDK installed.

If you're building from Visual Studio 2019.2 you need to make sure you enable Preview SDKs - this is a change that they made that broke this for me anyway.

For more info see here:

[Visual Studio 2019.2 and .NET 3.0 SDK Projects not Loading](https://weblog.west-wind.com/posts/2019/Aug/21/Visual-Studio-20192-and-NET-30-SDK-Projects-not-Loading)

The `Readme.md` file was recently updated with instructions to this effect:

https://github.com/RickStrahl/MarkdownMonster#installation

**Comment by bladewolf55** [comment]
I think you didn't read my entire text, since I directly addressed enabling preview SDKs. The issue is MarkdownMonster is referencing `Westwind.TypeImporter.dll`, which is _only_ on your machine.

**Comment by RickStrahl** [comment]
You need the 3.0 SDKs not 2.x... The desktop SDKs only work with 3.0 tooling.

I fixed the test project ref yesterday but I guess hadn't checked that in. Done.

The type importer issue is as I mentioned in the other thread: You have to clean the project and rebuild - it'll build eventually. I'm not sure why this fails - the file is there in the location specified, but there's some sort of timing issue in the build process that fails to pick up dependencies sometimes.

**Comment by bladewolf55** [comment]
This is probably frustrating for you, but it's equally so for me because you keep saying I need to do things that I've already done--and communicated--, and assuming I haven't done what I have. Maybe I've made some assumptions, too.

The one thing I erred in is that the `TypeImporter` error is in the Test project. I apologize, I stand corrected about the path to SupportAssemblies existing for the MarkdownMonster project. However, the error I pointed out *does* exist on test.

Here are the exact repro steps.

**Prereqs:**   
*   .NET Core 3 preview installed (I have preview 8)
*   .NET Full 4.6+ installed (I have 4.8)
*   Visual Studio 2019 > Tools > Options > Environment > Preview Features > Use previews of the .NET COre SDK = true

**Steps**  
1.  Create an empty folder in a completely separate area. Ideally, test on a clean virtual machine. In my case, I created `c:\_test\mm`.
2.  In a command line in that folder, run:  
    `git clone https://github.com/RickStrahl/MarkdownMonster.git`
3.  Change to the MarkdownMonster folder, open MarkdownMonster.sln. Allow the dependencies to resolve.  
    If necessasry, open Manage NuGet Package for solution and restore packages. I didn't have to do this because of previous work. I did *not* update any packages.
4.  Right-click MarkdownMonster project and Build. (Configuration= Debug)
5.  Build succeeds with no errors (thanks for fixing the reference versions)
6.  Right-click Solution and Build All (or F6).

Errors below are in MarkdownMonster.Test, MarkdownTests.cs. 

> At this point, with your previous fix plus the VS preview features setting, I can do what I need, especially make my workaround changes so that the Roslyn snippets addin delay is removed. 
>
> But if anyone wants to run tests, they'll need to take some extra step. I suspect the problem is that MarkdownMonster.Test,csproj is one folder deeper than MarkdownMonster.csproj, and when Test tries to use the MarkdownMonster project reference is fails finding `..\SupportAssemblies\Westwind.TypeImporter.dll` because that relative path from Test doesn't exist.

```txt
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0012	The type 'DotnetObject' is defined in an assembly that is not referenced. You must add a reference to assembly 'Westwind.TypeImporter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.	MarkdownMonster.Test	
C:\_test\mm\MarkdownMonster\Tests\MarkdownMonster.Test\MarkdownTests.cs	21	Active

Error	CS0012	The type 'ObjectProperty' is defined in an assembly that is not referenced. You must add a reference to assembly 'Westwind.TypeImporter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.	MarkdownMonster.Test	C:\_test\mm\MarkdownMonster\Tests\MarkdownMonster.Test\MarkdownTests.cs	62	Active

Error	CS0012	The type 'ObjectProperty' is defined in an assembly that is not referenced. You must add a reference to assembly 'Westwind.TypeImporter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.	MarkdownMonster.Test	C:\_test\mm\MarkdownMonster\Tests\MarkdownMonster.Test\MarkdownTests.cs	63	Active

Error	CS0246	The type or namespace name 'DotnetObject' could not be found (are you missing a using directive or an assembly reference?)	MarkdownMonster.Test	C:\_test\mm\MarkdownMonster\Tests\MarkdownMonster.Test\MarkdownTests.cs	39	Active

Error	CS0234	The type or namespace name 'TypeImporter' does not exist in the namespace 'Westwind' (are you missing an assembly reference?)	MarkdownMonster.Test	C:\_test\mm\MarkdownMonster\Tests\MarkdownMonster.Test\MarkdownTests.cs	9	Active
```

Thanks for following up; I know MM isn't your main gig.

**Comment by RickStrahl** [comment]
Ok so took a closer look and now I see what you're saying. Not sure why this didn't trigger in the builds previously - I only see this if I explicitly build the MarkdownMonster test project because I have it disabled in the build by default.

Anyway - I explicitly added a reference to the TypeImporter project pointing at the actual location in the test project and that should fix the issue as it now gets the correct hint path.

**Comment by bladewolf55** [comment]
Confirmed, builds perfectly now. And I've successfully built with my modifications, so "my" MM is back!

Also, thanks again for the linefeed setting. That reduces pain for me and probably others.
