### ISSUE TITLE
New version modal prevents closing on installation

### ISSUE THREAD

**Issue by daveaglick** [RickStrahl/MarkdownMonster#565]
I noticed what appears to be a UX bug (or at least an unintended behavior due to the upgrade flow):
- If there's an available update, MM pops open a modal asking if you want to download and install it
- If you select "yes" on the modal, a browser window opens to the MM website to download the new version, _but the modal stays open_
- When the new version is downloaded and installation kicks off, it recognizes MM is running and offers to close it
- If you opt to close the running instance the still-open modal prevents you from doing so (or at least I assume it's the modal preventing close) and the application crashes
- Installation then proceeds correctly

**Comment by RickStrahl** [comment]
So your suggestion would be, when you click the Register button to close the form? It didn't seem obvious to do that before, but I think that would make sense.

**Comment by daveaglick** [comment]
I think that would resolve this. And it makes sense too - if I've clicked "Yes" I wouldn't expect the dialog to remain open given that I'm now on the hook to do some stuff in a different application.

On note - it's a "Yes"/"No" (not a "Register") button (just want to make sure we're thinking of the same thing).

**Comment by RickStrahl** [comment]
Yeah it's just MessageBox - I actually have a richer generic preview window that has custom buttons and can have rich text to display (for change log for example), but haven't hooked it up yet.  I should put that back on my todo list.
