### ISSUE TITLE
Thought MM crashed but it came back after about 30 seconds

### ISSUE THREAD

**Issue by pkellner** [RickStrahl/MarkdownMonster#567]
I'm running MM on a Parallels VM with literally nothing else happening. Just writing my first blog entry in markdown here.  I typed:

And boom, dead in water. couldn't click anywhere on the editor screen. The menu worked so I did a file/save (phew, cause I had not saved for a while).  After collecting the screen shot and starting this issue, MM came back and had saved all my typing and blurted it out.

Just FYI, not sure what else to collect.
![mm-crash1](https://user-images.githubusercontent.com/241170/64478070-b0cb8a80-d157-11e9-86cc-8b671f861a04.png)

**Comment by RickStrahl** [comment]
I think I know this problem although I don't have a solution for it at this time. It's related the HTML fenced code syntax. I see this here too but not as severe as you describe. It happens only with html syntax which is very weird. 

The way to work around this is to use arrow keys to navigate up or down or the mouse after the `html` text.

This is an ACE Editor bug but I've not been able to duplicate it in a way that it can be reported or even debugged outside of MM either. It doesn't happen with Chrome (externally) and it's not anywhere as noticably slow with IE outside of MM.

**Comment by RickStrahl** [comment]
So just updated to the latest version of ACE and the `html` fenced code block issue seems to have resolved itself. Now typing 

````
```html
````

no longer locks/slows down the editor. Give this a try in 1.19.2.2 or later.

**Comment by pkellner** [comment]
1.19.2, same problem with ```HTML .

**Comment by RickStrahl** [comment]
You need 1.9.2.2 which has the updated scripts.

**Comment by pkellner** [comment]
That is a fast release cycle!

**Comment by RickStrahl** [comment]
Yup - why wait when a bug gets fixed :-) This one is actually a pretty annoying one that I've been cursing for a while myself. Really glad it's addressed by an ACE Editor update since there wou;dn't have been a good solution for this otherwise.

**Comment by pkellner** [comment]
no hanging after typing ```html in 1.19.3 for me.  Thanks!!!!
