### ISSUE TITLE
Allow ViM keybinding

### ISSUE THREAD

**Issue by oschwab** [RickStrahl/MarkdownMonster#57]
Hello, 
It would be nice to manage other keybindings (ViM would be great in my case).

How to do it *seems* to be explained here :

http://stackoverflow.com/questions/15485153/enable-vim-mode-in-gist-ace-editor

Could do it by myself, but I never played with GitHub and I'm afraid it would take me too long.

**Comment by RickStrahl** [comment]
Can you check and see how well VIM support works by doing:

* Open MM and focus on the editor
* Press `Ctrl-,`
* Change the editor mode to VIM

How well does that work?

If that works for you you can add the following script to the bottom of `Editor\editor.html`:

```html
<script>
    ace.require("ace/lib/net").loadScript("https://rawgithub.com/ajaxorg/ace-builds/master/src-min-noconflict/keybinding-vim.js", 
function() { 
    e = document.querySelector("#Editor").env.editor; 
    e.setKeyboardHandler(ace.require("ace/keyboard/vim").handler); 
}) 
</script>
```

which will force the editor into VIM mode every time it starts.

I don't know enough about VIM to know how well this works, but the cursor is changing so I assume it has an effect :-)

**Comment by RickStrahl** [comment]
Yeah Ctrl-, just adjusts the current editor instance that's running - that's to be expected. What I was after knowing is whether Vim support works properly or not.

**Comment by RickStrahl** [comment]
Added explicit configuration option: `EditorKeyboardHandler` that can take `default`,`vim` or `emacs`.

f807b4066a6bc09c41e5ec0d3ce25e79c08d264e
