### ISSUE TITLE
[Suggestion] Stick preview pane to current editor position.

### ISSUE THREAD

**Issue by jovibor** [RickStrahl/MarkdownMonster#570]
Atm, even if i don't scroll Editor window, Preview window will change its preview position depending on mouse line click. Whenever i click within editor it changes preview position in some strange way (for me at least).
This is both - distracting and unintuitive.

Would be very helpful to implement some option, to allow changing preview state **only** when "Edit" window  scrolls, if possible.
Thanks.

**Comment by RickStrahl** [comment]
I don't think you really can get away from adjusting the viewport when clicking. Text that might be at the top or bottom of the editor may not be visible in the editor at that time so the preview has to be adjusted on a click. If you click and the text is in the center the preview doesn't scroll - it's only on the edges that the view will be updated - ie. when the selected text is not in the center region which is + or - a few lines from the top of the preview.

That's pretty common behavior for editors and previewers - checking VS Code and it's doing something similar although it looks their threshold for moving the screen is much smaller so maybe not as noticable.

**Comment by jovibor** [comment]
Here's an algorithm:
1. We make it so that the topmost line of the Edit window is always visible at the top in Preview window.

2. That's it. No matter what we do from now on, we don't change preview viewport **until** user scrolls an Edit window.

Once again, don't make it the default - just an optional.

**Comment by RickStrahl** [comment]
Unfortunately it's not as easy as that. First line is a very relative term depending on what you're displaying. It may not be text or a single line.

A lot of trial an error has gone into the scroll operation and I need to revisit it. But for the time being I'm not going to mess with it until I have more time.

**Comment by RickStrahl** [comment]
There have been a number of changes in the scroll algo which may or may not be better for you.

But it's more consistent in terms of how the cursor position is displayed (basically close to the top of the page).

I've been experimenting with your idea of always syncing the top of the editor to the top of the preview window, but haven't gotten that to work reliably. The main reason for this this that editor and preview don't necessarily match. If you're working on a large document and you have a block of code or image, the bottom of your editor maybe way below what is rendered in the preview - IOW, the difference between the editor lines and the preview lines makes a simple scenario not workable I think.

Check out the updates in 1.19.5 and see if that helps at all.

**Comment by jovibor** [comment]
> Check out the updates in 1.19.5

You mean 1.19.6.5
Yes, i see your changes. At least it's now more consistent with respect to currently clicked line in editor and the top of the preview.

Well, it's not exactly what i was talking about but still, at least some algorithm might be noticed,
it's definitely better than before. Will see how the things will go on )

**Comment by RickStrahl** [comment]
Closing for now - unless we can come up with a more actionable path here.
