### ISSUE TITLE
I got a "Something went wrong..." error when i add new *.md file.

### ISSUE THREAD

**Issue by supershowwei** [RickStrahl/MarkdownMonster#573]
I was upgrade MarkdownMonster from 1.17.8 to 1.19.4.

I got a "Something went wrong..." error when i add new *.md file, but it's working in 1.17.8.

![](https://i.imgur.com/V6i18El.png)

How can i help you to shut this trouble?

**Comment by RickStrahl** [comment]
Can you try the latest download (1.19.9) - there has been some work around an issue that I think has been resolved.

See #572 - from the sounds of it, this is the same issue.

**Comment by supershowwei** [comment]
Thanks a lot.
