### ISSUE TITLE
Math equations fail to display correctly. Version 1.19.6

### ISSUE THREAD

**Issue by hans1984x** [RickStrahl/MarkdownMonster#575]
Math equation fail to display correctly. File something.md is a copy of the sample document explaining the use of MathJax - this file displays correctly. File Eq_fail.md is a copy of the first few lines of something.md pasted into a new file and fails to display  the equations

eg $E=mc^2$ is displayed as \(E=mc^2\).

Note: useMathematics is set to true in the config file.
[mdFiles.zip](https://github.com/RickStrahl/MarkdownMonster/files/3640483/mdFiles.zip)

**Comment by RickStrahl** [comment]
Thanks @hans1984x. Yup - looks like a regresssion from changed behavior a while back that incorrectly was looking at the raw Markdown instead of the generated HTML output. Fixed.

**Comment by hans1984x** [comment]
Thanks Rick.

Hans
hans1984x@gmail.com
On 23/09/2019 14:23:08, Rick Strahl <notifications@github.com> wrote:
Thanks @hans1984x [https://github.com/hans1984x]. Yup - looks like a regresssion from changed behavior a while back that incorrectly was looking at the raw Markdown instead of the generated HTML output. Fixed.
