### ISSUE TITLE
Can't open project in Visual Studio

### ISSUE THREAD

**Issue by yangshuairocks** [RickStrahl/MarkdownMonster#576]
I downloaded the repo and tried to open it using Visual Studio 2017 and got the following errors:

> C:\my_projects\MarkdownMonster-master\MarkdownMonster\MarkdownMonster.csproj : error  : Project file is incomplete. Expected imports are missing.
> 
> C:\my_projects\MarkdownMonster-master\AddIns\WebLogAddin\WebLogAddin.csproj : error  : Project file is incomplete. Expected imports are missing.
> 
> C:\my_projects\MarkdownMonster-master\AddIns\ScreenCaptureAddin\ScreenCaptureAddin.csproj : error  : Project file is incomplete. Expected imports are missing.
> 
> C:\my_projects\MarkdownMonster-master\AddIns\Snippets-MarkdownMonster-Addin\SnippetsAddin\SnippetsAddin.csproj : error  : Project file is incomplete. Expected imports are missing.

Anything else should I do before opening it? Thanks.

**Comment by RickStrahl** [comment]
You need vs 2019... it uses the newer sdk style projects that are not supported in vs 2017.
