### ISSUE TITLE
Error when refreshing a new unsaved document

### ISSUE THREAD

**Issue by SauerKraut51** [RickStrahl/MarkdownMonster#577]
***Error occurs when pressing F5 to refresh while focus is on the editing window***

- **10/2/2019 1:16:49 PM** - AppDispatcher: Exception has been thrown by the target of an invocation.

Exception from HRESULT: 0x800A1393
Markdown Monster v1.19.5.0
6.1.7601.24520.amd64fre.win7sp1_ldr_escrow.190828-1732 - en-US - NET 4.8 - 32 bit
en-US - en-US    

- **10/2/2019 1:17:21 PM** - Handled: AceEditor.setfocus() failed
Exception from HRESULT: 0x800A1393
Markdown Monster v1.19.5.0
6.1.7601.24520.amd64fre.win7sp1_ldr_escrow.190828-1732 - en-US - NET 4.8 - 32 bit
en-US - en-US

**Comment by RickStrahl** [comment]
This should be fixed in 1.19.8.1.

Modified the keybinding behavior to use ids instead of the command names which caused problems for multiple keys bound to the same command. In this case both f5 and ctrl-f5 were bound to the same command and f5 was ignored.
