### ISSUE TITLE
wkhtmltopdf.exe crashes due to missing MSVCP140.dll

### ISSUE THREAD

**Issue by mibere** [RickStrahl/MarkdownMonster#579]
Windows 8.1 (German), 64bit, .NET 4.8, Windows updates as of 2. October 2019
Markdown Monster 1.19.8.1 installed via _MarkdownMonsterSetup.exe_ in default folder (C:\Users\xxxxx\AppData\Local\Markdown Monster)

Actions:

* _File_ menu -> _Save To_ -> _Save to Pdf_
* in _Save as Pdf File_ dialog change nothing (all default) -> [_Generate PDF File_]
* in _Save output to PDF file_ dialog just press [Enter]

=> app crash of _wkhtmltopdf.exe_:

![appcrash](https://user-images.githubusercontent.com/17352825/66152356-96cb7d80-e619-11e9-9555-9bc8d4924ed8.png)

By executing the PDF creation command line manually in a CMD it shows that the file _MSVCP140.dll_ is missing:

![missingfile](https://user-images.githubusercontent.com/17352825/66152484-d72afb80-e619-11e9-87b7-d5b49029a485.png)

**Comment by mibere** [comment]
The file _MSVCP140.dll_ seems to be part of _Microsoft Visual C++ 2015 Redistributable_, and that is not installed on my system.

MM should include the file (in the _wkhtmltopdf.exe_ folder?), or should install the _Microsoft Visual C++ 2015 Redistributable_.

**Comment by RickStrahl** [comment]
Thanks for reporting. 

What version of .NET are you running? I suspect using a newer .NET Version will address this on Windows 7-8.1. 

This is the first report I have of this. MSVCP140.dll is part of the Windows install, but it's possible that on old versions of Windows (and .NET) so I'm not super keen to add this to the installer. Especially given that shortly we'll be bumping up the .NET Framework requirement to .NET 4.7.2 which I believe includes the dll.

For now a quick way to install it:

```ps
choco install vcredist140
```

I can also add this to the Chocolatey installs although that breaks the no-admin installer as these files need to go into the system folder.

**Comment by mibere** [comment]
My Windows 8.1 was a nearly fresh install, with nearly no other software installed - even no manually installed .NET.

Saving to PDF was successful after manually installing a _Microsoft Visual C++ 2015 Redistributable_ - now the DLL exists.
This was the first time I had to do that. Other software installers include such a needed Redistributable package, or download and run it automatically.
