### ISSUE TITLE
Equation display problem

### ISSUE THREAD

**Issue by hans1984x** [RickStrahl/MarkdownMonster#580]
The failure to display maths equations correctly has returned with last update.

**Comment by RickStrahl** [comment]
What version?

Please be more specific and post an example that doesn't work, preferrably with a screen shot (you can just paste it from the clipboard here).

**Comment by hans1984x** [comment]
Sorry I assume you would remember my bad. 
Version 1.19.81 3 Oct 2019
input:
$$
a = b + c
$$
Output
\[a = b + c\]
Hans

**Comment by RickStrahl** [comment]
Hmmm... works for me:

![image](https://user-images.githubusercontent.com/1374013/66248233-5ffc7280-e6c0-11e9-83f4-300a6f4b8428.png)

Also make sure you have Math processing enabled in the settings.

![image](https://user-images.githubusercontent.com/1374013/66248270-d00af880-e6c0-11e9-86af-fac7b5299ba7.png)

I did notice that the code is not checking  for the useMath yaml header when it probably should - added that.

https://markdownmonster.west-wind.com/docs/_59l0mv2uw.htm

**Comment by hans1984x** [comment]
Hi Rick
Done the following totally uninstall MM from my system including the directory in AppData. Downloaded latest version of MM from the web site; also downloaded the math example document.
Result: Math example document works. A newly created file fails as per my previous message. 

If I remember correctly you said it was a regression problem - It appear to be a quick fix at the time.

Hans
hans1984x@gmail.com
On 05/10/2019 11:36:40, Rick Strahl <notifications@github.com> wrote:
Hmmm... works for me:
[image] [https://user-images.githubusercontent.com/1374013/66248233-5ffc7280-e6c0-11e9-83f4-300a6f4b8428.png]
Also make sure you have Math processing enabled in the settings.
[image] [https://user-images.githubusercontent.com/1374013/66248270-d00af880-e6c0-11e9-86af-fac7b5299ba7.png]
I did notice that the code is not checking for the useMath yaml header when it probably should - added that.
https://markdownmonster.west-wind.com/docs/_59l0mv2uw.htm [https://markdownmonster.west-wind.com/docs/_59l0mv2uw.htm]

**Comment by RickStrahl** [comment]
Did you turn on useMathematics in the settings? It's off by default (although I switched it to on by default in 1.19.8.2)

Maybe grab the latest download (1.19.8.2) which has some additional logic to check for the presence of math content as well as the new default setting behavior. No need to uninstall - just reinstall, but make sure that useMathematics in the settings is set.

**Comment by hans1984x** [comment]
Yes I had checked the setting and checked the json file to make sure it was set.

Version 1.19.8.2 works as designed.

Thanks


Hans
hans1984x@gmail.com
On 07/10/2019 07:25:07, Rick Strahl <notifications@github.com> wrote:
Did you turn on useMathematics in the settings? It's off by default (although I switched it to on by default in 1.19.8.2)
Maybe grab the latest download (1.19.8.2) which has some additional logic to check for the presence of math content as well as the new default setting behavior. No need to uninstall - just reinstall, but make sure that useMathematics in the settings is set.

**Comment by RickStrahl** [comment]
Thanks for verifying. Just FYI the useMath header shouldn't be necessary in most situations, but it's an explicit forced override that ensures it works even if auto-detection for some reason does not.

**Comment by hans1984x** [comment]
Thanks for your help Rick. 

Regards

Hans
hans1984x@gmail.com

As a 30+ year veteran software engineer I found non verification by clients was annoying at the best of times

On 07/10/2019 07:46:56, Rick Strahl <notifications@github.com> wrote:
Thanks for verifying. Just FYI the useMath header shouldn't be necessary in most situations, but it's an explicit forced override that ensures it works even if auto-detection for some reason does not.
