### ISSUE TITLE
The tooltip is not populated after saving a new file

### ISSUE THREAD

**Issue by paulmrozowski** [RickStrahl/MarkdownMonster#582]
v 1.19.6.2

Create a new file, save it. Hover over the tab for this document - it will show "untitled" instead of the document path.  If you close, then re-open the document this is populated correctly.

**Comment by RickStrahl** [comment]
Ah yes - looks like this was just assigned when the tab was opened and not updated. Switch to use a binding instead alongside the rest of the tab bindings.

Thanks Paul.
