### ISSUE TITLE
Table Editor Navigation Issue Selecting Text

### ISSUE THREAD

**Issue by thnk2wn** [RickStrahl/MarkdownMonster#584]
Markdown Monster Version 1.19.9

Edited an existing (piped) table. The cell contents wrap in row being edited. On the end of the line I tried to hit Shift+Up to start selecting some text to replace and noticed the selection disappeared and the focus appeared lost / changed.

From what I can tell it's because there's some built-in arrow key navigation to navigate grid cells. However I'd think that with Shift pressed and/or text selected (and/or with wrapped contents) that it would be context aware and not do that behavior. That'd be more consistent with say editing a table in Word. Actually even without shift Word seems to navigate "lines" within a wrapped cell with the arrow keys before navigating to another row. Probably harder to pull off in WPF but thought I'd share anyway.

[2019-10-09_15-04-47.mp4.zip](https://github.com/RickStrahl/MarkdownMonster/files/3709018/2019-10-09_15-04-47.mp4.zip)

**Comment by RickStrahl** [comment]
Thank you. Fixed for next update in 1.19.12
