### ISSUE TITLE
[Feature Request] - Translate the UI

### ISSUE THREAD

**Issue by timunie** [RickStrahl/MarkdownMonster#590]
Do you plan to translate the UI someday? I can provide the German translations.

Happy coding
Tim

**Comment by RickStrahl** [comment]
Thought about it yes. Done anything about it no...

**Comment by timunie** [comment]
If you want me to I can give some input / help on this topic. I am using ResX-Files for translations in my program and using the [ResXManager](https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager) 

If you give me a :+1: I will start translation (I know it will take a few weeks to get it done and there will be a few issues related to this).

Happy coding
Tim

**Comment by kkbruce** [comment]
I can provide Traditional Chinese translations.

**Comment by RickStrahl** [comment]
Closing - just don't have the dev resources for it.
