### ISSUE TITLE
Add shortcut keys for Table Editor

### ISSUE THREAD

**Issue by Andis59** [RickStrahl/MarkdownMonster#592]
It would be nice if there was a shortcut to the _Insert Row Below_ .
So you can add rows when writing the values without using the mouse.

**Comment by RickStrahl** [comment]
In a way there's already a shortcut:

* Use the Windows Context Menu key (next to left Alt key on most Win keyboard)
* Press the shortcut key for the context menu item

Ok so the shortcuts aren't there at the moment but I've added them just now.

With that the shortcut basically becomes:

* Context Key - B  (insert row below)
* Context Key - A (Insert row above)
* Context Key - D (Delete row)
* Context Key - L (Insert Column Left)
* Context Key - R (Insert Column Right)
* Context Key - L (Delete Column)

Is that close enough?

If we add hotkeys then all these have to should be mapped and frankly I'd rather avoid that.

**Comment by Andis59** [comment]
This is more than _close enough_
Waiting for the update...

**Comment by RickStrahl** [comment]
It’s up on the download page

**Comment by Andis59** [comment]
The contex key will show the menu but there is no action if I press any of the Keys (B A D L R L)
also it's a bit "strange" to have Insert Column Left and Delete Column as the same Key?

The version that i can download is 1.19.11.2

**Comment by Andis59** [comment]
In version 1.19.12.0 everything works!

Thank You!
