### ISSUE TITLE
Nested markdown elements not correctly syntax-highlighted

### ISSUE THREAD

**Issue by Structed** [RickStrahl/MarkdownMonster#593]
When I mix a Style like `**bold**` with another, it is not correctly "syntax-highlighted" in the editor.

## Actual Behavior
I have seen this issue now in multiple combinations, I think. The one I can confirm right now is Bold mixed with italic and/or hyperlinks:

```
*italic*

**bold**

[Link](https://github.com/RickStrahl/MarkdownMonster)

***[Mixed](https://github.com/RickStrahl/MarkdownMonster)***
```

![image](https://user-images.githubusercontent.com/29922/67214872-c99ab180-f420-11e9-9a54-06ce2e6defc2.png)

## Expected Behavior:
The "Mixed" string in the editor should be bold, italic and have a distinguishable styling for the link - a mixture of the styles which are applied when you use those styles individually.

**Comment by RickStrahl** [comment]
Yes this is an issue with the ACE Editor Markdown highlighting. It only captures one of the two formattings and in this case bold wins out as it's the last reg ex that hits it.

This is a minor issue though and frankly not worth fussing over, but if you think it's worth pursuing you might want to file an issue on the [ACE Editor Github repo](https://github.com/ajaxorg/ace/issues).  If you do report over there use the Kitchen Sink demo that they have as your reference.

Note that the default themes actually don't use bold or italic at all - those are added by MM, but ACE doesn't add both for triple  stars.

![image](https://user-images.githubusercontent.com/1374013/67258673-809d2a00-f42d-11e9-854e-cc10cf7555f9.png)

Closing here.

**Comment by Structed** [comment]
Thanks for the feedback and referencing this with ACE!

**Comment by RickStrahl** [comment]
So took another swing at this and I actually managed to fix it (temporarily) by making a change to ACE editor's Markdown mode which I reference in the [issue over there](https://github.com/ajaxorg/ace/issues/2443).

Whether this will stick depends on whether this makes it into ACE proper though or else this will get wiped out with the next update.

The site download for 1.19.12 has this fix in it.

**Comment by Structed** [comment]
wow - that was quick - thank you!

But this is not working for me. Got 1.19.12 (via chocolatey), but it didn't change the behavior. It looks exactly the same as I posted above.

I have also tried the `_` version for italic. Here's the full example:

```
*italic*

_italic 2_

**bold**

[Link](https://github.com/RickStrahl/MarkdownMonster)

***Bold & Italic***

**_Bold & Italic 2_**

***[Mixed](https://github.com/RickStrahl/MarkdownMonster)***

**_[Mixed 2](https://github.com/RickStrahl/MarkdownMonster)_**
```

![image](https://user-images.githubusercontent.com/29922/67304729-90cc0c80-f4f4-11e9-9b44-1d5f1c21bf86.png)

**Comment by RickStrahl** [comment]
Where did you get .12 from? The Chocolatey build I believe doesn't have it, while the download site does.

**Comment by Structed** [comment]
oh, I see! Fetched the pre-release from the download pages. I can confirm it's working. Thanks a bunch!
Though indeed a minor issue, I am very happy about it!
