### ISSUE TITLE
Skipping cursor (again)

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#595]
I've read "Skipping cursor in v1.9.12", issue #334, and I understand that that's fixed. I'm seeing something very similar in the current build, 1.19.12. It took me a while to figure out how to repro it, but at last I think I have a description for how to do it.

From what I can tell, in order to make this happen, you need to have headers, and a table, and a full page that exceeds the height of the editor window. So, fill a page from to bottom with "# asdf" lines, maybe with blank lines between them. Then, at the bottom of the page, add a table, e.g.
```text
| a | b | c |
|:-:|:-:|:-:|
| 1 | 2 | 3 |
| 4 | 5 | 6 |
```

Now, edit that table to make it not a table. I do this by adding text immediately under the table:
```text
| a | b | c |
|:-:|:-:|:-:|
| 1 | 2 | 3 |
| 4 | 5 | 6 |
asdf
```
If you wait a moment for the preview window to redisplay such that the table stops being a table and becomes a string of text, at that moment the edit window cursor will hop up to the top of its window unexpectedly.

Like I say, for some reason this doesn't become a problem if there are no "# Header" lines in the text, and also if the text isn't taller than the edit window. (I notice that having text taller than the edit window was also one of the criteria for issue #334.)

In case you're curious, I encounter this because I tend not to use the optional first and last (leftmost and rightmost) bars when I'm building my tables, and so I see this when I'm beginning to add a new row to the table. However, this occurs with or without those leftmost and rightmost bars. To work around this, I make sure to use the leftmost bars; that way, the new row I'm adding never causes the table to become invalid, and therefore this skipping cursor doesn't happen.

**Comment by RickStrahl** [comment]
I don't think the issue is the specific content - that it happens with your table rendering is perhaps incidental. It has to do with the rendering at the very bottom of the document that causes the skipping. 

**I think** what happens is that there's a situation where the line number to jump is invalid or missing and that jumps to the top perhaps. That should be easy to fix if I can duplicate it reliably.

**Comment by RickStrahl** [comment]
Thanks for the repo - that did in fact work to fail every time. What the sample does is it renders the table, and then doesn't and that causes a scroll operation to fire with a line number that is larger than the current document's line and that randomly navigates by jumping to the top of the view port.

Ok so I think I fixed this simply by making sure that the `gotoLine()` in the editor doesn't go past the length of the document. I added a number of checks in there - for invalid (non-number) line numbers, for below 0 and greater than the actual available lines which defaults to the last line.

Using the above scenario (which is similar to what I've been seeing randomly), this works. Cool. Thank you - that was bugging me too. Let's see if it holds for all scenarios.

**Comment by RickStrahl** [comment]
Still not quite fixed - there appears to be still some sort of timing issue. Checking again.

**Comment by RickStrahl** [comment]
One more try at this. I think it's now working as it should although the fix is ugly.

1e74e8549bfb99b27492b33d6ea074092092abde

Basically there's now special handling for the last page and a when the scrollbar is all the way at the bottom it pins the cursor to the bottom, refreshing without reselecting.
