### ISSUE TITLE
Recent documents in the left-hand gutter?

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#598]
This isn't a bug, and I'll understand if you choose not to implement this, but I have an idea for something that would make the UI a little easier to navigate. You know the Recent Documents list that's currently living inside the File menu. How would you feel about putting an icon on the left-hand gutter that displays that list where the Favorites and Files are listed now? Imagine a new icon that lives here, in other words --

![image](https://user-images.githubusercontent.com/42981101/69449982-f50b0780-0d10-11ea-83ef-4f7d26201b5c.png)

-- that puts that list where the Favorites are.

As I see it, that would make the Recent Documents a little easier to find and navigate to. I don't know about the rest of you, but I use that list a *lot*, and having it closer at hand would be a helpful addition.

**Comment by RickStrahl** [comment]
There's already an access key in the toolbar: Click the drop down button next to the folder in the toolbar...

![image](https://user-images.githubusercontent.com/1374013/69484173-39131080-0dd4-11ea-84ec-82a149c76c3b.png)

**Comment by RickStrahl** [comment]
I also added a shortcut to the menu option so you should now be able to open the recent menu with:

Alt+F+R
