### ISSUE TITLE
Add Auto-Save/Backup Copy Functionality

### ISSUE THREAD

**Issue by RickStrahl** [RickStrahl/MarkdownMonster#60]
NOTE: This topic is primarily here for  discussion of how to best implement this feature.

Markdown Monster should automatically create a backup copy of the open file every few minutes (configurable) so that in case of a failure of some sort the document text is not lost.

Here are some starter thoughts:

### Approaches
* Use `.md.tmp` files to create backup file - delete when doc is closed
     * Pro: Easy to implement, easy to figure out what it means
     * Pro: Easy to known when to ask for auto-recover (ie. file exists on open)
     * Con: extra file that might show up in source control commit dialogs
* Use temp file in Temp Folder   
      * Pro: No interference with source control
      * Con: Messy to track
      * No good way to auto-recover

Please discuss.

**Comment by Mehul** [comment]
Not sure how Sublime handles it but I love the way it does it. I use the portable version so the autosave is great when I work on different machines.

**Comment by RickStrahl** [comment]
Oh really? I didn't know Sublime does that. How could it possible get that across machines?

**Comment by Mehul** [comment]
@RickStrahl Yes, I use dropbox to store files and it must store the temp files in dropbox too because I'll open a new document, edit it, close sublime w/o saving, and when I open it at home, it's there.

**Comment by Mehul** [comment]
@RickStrahl speaking of which, is it possible to have a portable version of MM that I can use in a similar way please? :)

**Comment by RickStrahl** [comment]
MM is portable as is. Once installed you can copy it to a ZIP file and unzip elsewhere and it should just work. The only thing missing will be file association, command line support (path set) and possibly some edge case security issues with configuration updates (missing permissions). 

But the main application is fully self contained as long as .NET 4.5+ is installed.

**Comment by Mehul** [comment]
Nice, I'll may try that. Btw, these links maybe helpful:
http://superuser.com/questions/894021/where-does-sublime-text-store-its-un-saved-windows
https://github.com/Microsoft/vscode/issues/101

**Comment by RickStrahl** [comment]
@Mehul FWIW I've created a portable distribution that gets published now on the download page:
http://markdownmonster.west-wind.com/download.aspx

Click the **Portable Zip** link. If you run into issues with this please open a separate issue so we can track this better.

**Comment by Mehul** [comment]
That's awesome, thanks, I'll give it a try now.

**Comment by Mehul** [comment]
@RickStrahl Portable version (and alt--v-b fix) is working great, thanks. Still would love to see that auto save. :)

**Comment by RickStrahl** [comment]
Added auto-backup save functionality that updates in the background while editing your document. If MM crashes the backup file is persisted and when you repopen MM and hte affected file, both the original file (which might be incomplete) and the backup file are opened and you can copy the text from the backup file into the actual document.

Files are named `*.saved.bak`.

0904c9be9c2f37d5a67dc4064bc8228a5027f32a

**Comment by RickStrahl** [comment]
This feature is now available in 1.0.28. You have to explicitly set the `AutoSaveBackups` config setting.

**Comment by Mehul** [comment]
@RickStrahl thank you for adding this. Here's the feedback :)

I've enabled the feature in config, however, when I close MM, and if I have any unsaved files, it prompts me to save them first. I suppose this feature that I'm describing is probably close to AutoSaveDrafts or something.

**Comment by RickStrahl** [comment]
It's not meant to be auto-save - it's auto-backup, so if you crash the auto-saved version is available to you.

**Comment by Mehul** [comment]
Fair enough. Do you still plan to add auto-save? Just curious. It's not as important but I do find it it convenient.

**Comment by RickStrahl** [comment]
I suppose it'd be easy to implement auto-save as we could just write to the actual underlying file rather than the backup file. If supported the option would be off by default cause frankly it's not a good idea most of the time. If you're screwing around with a document, experimenting etc. there's then no way back to abort changes (other than Ctrl-z many times to last save).

**Comment by RickStrahl** [comment]
1.0.31 is live now (from the download page) that adds true Auto-Save behind a new `AutoSaveDocuments` flag. Documents are written to disk immediately (after a 1 second type delay) when this mode is active.
