### ISSUE TITLE
Could not test MarkDownMoster Editor as Trial

### ISSUE THREAD

**Issue by MichaelRobl** [RickStrahl/MarkdownMonster#601]
We have Installed MarkdownMoster Editor on two Windows 10 Maschines. On both maschines we could not use 'pro' features like 'Paste Html as Markdown'. So what must we do to use the free version as a trial version?

**Comment by RickStrahl** [comment]
Yes some of the 'premium' features have nags attached to them. You can retry as they are set on intervals to nag.
