### ISSUE TITLE
Particular H3 not syntax highlighted - may be indicative of a general bug

### ISSUE THREAD

**Issue by MarshP** [RickStrahl/MarkdownMonster#602]
[03_Information_assets - Copy.txt](https://github.com/RickStrahl/MarkdownMonster/files/3923161/03_Information_assets.-.Copy.txt)
In a document pictured (cannot attach a md doc so also attached as txt), the latest H3 is marked up correctly in preview but is not syntax highlighted in any of the syntax themes.
![image](https://user-images.githubusercontent.com/10521654/70165324-a23f3180-16ba-11ea-8392-41e346cc8abd.png)

Win 10 Pro, MM 1.20

**Comment by MarshP** [comment]
Solved. There are exactly two leading spaces on the blank line above. When removed MM sees the end of the list.

**Comment by RickStrahl** [comment]
Yes two spaces are significant in Markdown and refer to a **soft line break**. The next line is treated as a continuation of the previous paragraph and treated as part of the paragraph.

So this is valid.
