### ISSUE TITLE
Current advice to add `IRenderExtension` into `OnApplicationStart` causes an exception

### ISSUE THREAD

**Issue by Smurf-IV** [RickStrahl/MarkdownMonster#607]
Using the latest build 1.20.x
Creating an addin that would like to perform `IRenderExtension`
Followed advice to add into `OnApplicationStart` from https://markdownmonster.west-wind.com/docs/_5i30sba89.htm#hooking-up-a-renderextension-in-onapplicationstart

throws an exception:
![image](https://user-images.githubusercontent.com/2418812/71167036-d20a3f80-224b-11ea-8987-7458b81b8f07.png)

Was able to break it down to the following:
![image](https://user-images.githubusercontent.com/2418812/71166856-70e26c00-224b-11ea-91c0-924ddb66f031.png)

**Comment by Smurf-IV** [comment]
to solve the above I did this:
```C#
        public override void OnModelLoaded(AppModel model)
        {
            base.OnModelLoaded(model);
            RenderExtensionsManager.Current.RenderExtensions.Add(new ToggleRavenVisibility());
        }
```

**Comment by RickStrahl** [comment]
Thanks for reporting. Turns out there's an incorrect reference bug that caused this error that is referencing the model when it's not actually necessary.
