### ISSUE TITLE
Insert Link dialog says 'Embed Image'

### ISSUE THREAD

**Issue by Mehul** [RickStrahl/MarkdownMonster#61]
![mdm-error](https://cloud.githubusercontent.com/assets/174004/20815348/554ab970-b7d2-11e6-8aaa-038055c1e85a.png)

Checked PasteHref.xaml.cs and text looks correct there but somehow it says embed image (as you can see from image.

**Comment by RickStrahl** [comment]
Fixed. Thanks Mehul.
