### ISSUE TITLE
The ability to add a frame to the bottom, so that enhanced parsers can report "Real-time" Logging in a "Wide" window.

### ISSUE THREAD

**Issue by Smurf-IV** [RickStrahl/MarkdownMonster#611]

**Comment by RickStrahl** [comment]
I'm not sure that this is needed. 

If you're creating an addin you can create your own window and I would argue that it's better to display any sort of console info in that window rather than on the main window.

What would you want to display there? We do have the status bar for basic messages and notifications.

**Comment by Smurf-IV** [comment]
The plugin I want to run takes the MetaData  (attributes) from the object-blocks and validates its:
- Format, Content, 
- Conditional requirements, 
  - based on previous content
It then takes a step into the block to then discover if the data contained is correct and can be cross referenced.
And there can be many blocks in a page.
Hence the need to have it contained within a window that is not "Hidden" when MM is maximised like the existing "console" style one is.
As the user then corrects , adds more cross reference content, fixes spelling, the log window is being updated (slight delay to allow typing etc.) to show current state.

**Comment by RickStrahl** [comment]
Ok... I've added a console window:

![image](https://user-images.githubusercontent.com/1374013/71696947-8b900700-2d5a-11ea-9c9a-828bfed9eccd.png)

Which is accessible via `Model.AppModel.Console`.  There are `Write()`, `WriteLine()`, `Clear()`, `Show()`, `Hide()` methods on the console (beyond UI properties for the panel control).

**Comment by Smurf-IV** [comment]
Thanks for this.
Just had an exception when trying to call this during Load:
![image](https://user-images.githubusercontent.com/2418812/71811301-3a3e8b00-306c-11ea-96f0-caaf6630f5e8.png)
Should this cache the message, or return a useful error, as everything that is being used (i.e. even Console) is not null therefore not testable via plugin code.

**Comment by Smurf-IV** [comment]
Also: *(Should this be raised as a separate [Bug] as this is not a released feature yet?)*
If you dump a large amount of text on the first API call (i.e.`WriteLine` with lot's of lines and carriage return within it!), the Console Window fills the entire app screen. 
It does not limit it's size to 10 lines etc.

**Comment by Smurf-IV** [comment]
Also:
Each new line written the Console makes the console window size increase (Probably the cause of the previous comment)
This is the version i am using:
![image](https://user-images.githubusercontent.com/2418812/71811985-f3ea2b80-306d-11ea-9f40-56d8180c428c.png)

**Comment by Smurf-IV** [comment]
Setting the MaxHeight to 40 has a weird effect:
- Text is not visible
- Dragging the splitter causes this to happen:
  - ![image](https://user-images.githubusercontent.com/2418812/71812217-8be81500-306e-11ea-9a00-f45f1205ffe1.png)

**Comment by RickStrahl** [comment]
Please try 1.20.10. There have been several updates to the console panel.

**Comment by Smurf-IV** [comment]
Without specifics, of what 1.2.10.1 gave; I just tested the window height, after each add.
It filled the screen as before:
![image](https://user-images.githubusercontent.com/2418812/71877108-4f74f180-3120-11ea-97d7-155c69526375.png)

**Comment by RickStrahl** [comment]
I don't understand what you're saying. Are you saying the window grows each time you add something when the window is full? 

I don't see that here.  The console should scroll down with new entries showing the last entry.

![image](https://user-images.githubusercontent.com/1374013/71881672-d00f0000-30d6-11ea-84e7-d1c1f16c35dc.png)

**Comment by Smurf-IV** [comment]
> 
> I don't understand what you're saying. Are you saying the window grows each time you add something when the window is full?

Yes, It starts small, and then continues to grow up the screen until it occupies the whole of the MM app area as each line is added.

Code snippet below:
```C#
public class AddItAll : MarkdownMonster.AddIns.MarkdownMonsterAddin
{
...
        public override void OnDocumentUpdated()
        {
            base.OnDocumentUpdated();
            var doc = Model.ActiveDocument;
            if ((doc != null)
                && doc.IsActive
                )
            {
                ...
                Model.Console.WriteLine(text);
                ...
            }
        }
...
}
```

**Comment by Smurf-IV** [comment]
I have just recreated the scroll bar, and now I know Why you _may_ not be seeing the issue.

If I resize the console window _after_ it has been created (By using the mouse) I get a scrollbar and everything is as you describe.

**BUT**, If I do nothing but just edit away inside the editor without resizing the console after it has displayed, then I get the problem as i have described.
HTH.

**Comment by Smurf-IV** [comment]
Why was this closed? It's still an issue!

**Comment by RickStrahl** [comment]
Because it's fixed with the above fix. Grab 1.20.10.3...

**Comment by Smurf-IV** [comment]
I can confirm that the scrollbar is on by default and works as expected with v1.20.10.3. 
Thanks
