### ISSUE TITLE
Definition lists?

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#613]
How do you feel about supporting the colon syntax for definition lists?

I notice that MM supports just about everything [here](https://www.markdownguide.org/extended-syntax), although not the bit about Definition Lists described in the middle of that page.

It's not a high priority, but I'd use it if MM supported it.

**Comment by bcmadsen** [comment]
Oh! I just discovered https://github.com/lunet-io/markdig/blob/master/src/Markdig.Tests/Specs/DefinitionListSpecs.md

Turns out, you are supporting definition lists after all!

I was confused because I was expecting
```
First Term
: This is the definition of the first term.
```
to act as a definition list, when, instead, there needs to be more than one space after the colon for this to work:

```
First Term
:    This is the definition of the first term.
```

That's a bit of a surprise, but as long as there's some way to get DL's, I can work with that.

**Comment by RickStrahl** [comment]
Hmmm... yeah that is a surprise. In fact I pasted some text just now from the Markdig specs as is and it didn't work which made me scratch my head because I know that did work in the past because I added specific styling for the definition lists.

But that syntax surely sucks. Looks like it takes 3 spaces to work.

Test
:   Sub text here

**Comment by bcmadsen** [comment]
Agreed on all points. But again, it's a minor priority for me, so I'm happy with what's here.

**Comment by RickStrahl** [comment]
Also added an issue on the MarkDig Repo:

https://github.com/lunet-io/markdig/issues/384

Let's see what they sayeth :smile:

**Comment by RickStrahl** [comment]
Closing for now since this works, even with the somewhat funky behavior in MarkDig. If more information becomes available with the MarkDig issue.
