### ISSUE TITLE
Suggestion: add target options for links (top, blank, etc)

### ISSUE THREAD

**Issue by Mehul** [RickStrahl/MarkdownMonster#62]
By default, the link dialog will use target="top". Didn't see any documentation to change it in settings. Could you please add a setting to allow blank, top, etc.?

**Comment by RickStrahl** [comment]
You can do that already if you use the HREF dialog. 

![image](https://cloud.githubusercontent.com/assets/1374013/20816487/9b013086-b7c6-11e6-8b38-1a2659d9fecc.png)

The problem is there's no support for that in markdown so the embedded link will be HTML.

**Comment by RickStrahl** [comment]
target=top basically forces the rendering to go a new window called `top`.  It'll open a new tab and then open subsequent windows in that same tab.

What behavior do you think you want? _blank is the only real option that still works properly per HTML5 spec, which in turn forces to open a new tab each time.

**Comment by Mehul** [comment]
I use _blank and I'd be happy with just that. However, I was suggesting that if you make it an setting then you could provide other options.

**Comment by RickStrahl** [comment]
Fixed.

261c49de5ed80d0fd2253e1926080c9c649dc3be
