### ISSUE TITLE
add markdown monster to the PATH

### ISSUE THREAD

**Issue by paule96** [RickStrahl/MarkdownMonster#620]
Hi @RickStrahl,

if it possible to add Markdown Monster install directory to the PATH? (~\AppData\Local\Markdown Monster)

That would be make it easy to open directories from the command line. So you can type:

```bash
MarkdownMonster.exe ./
```

That would be helpful. :)

**Comment by RickStrahl** [comment]
Markdown Monster **automatically** adds the install path to the User path.

Here's more info:
[Open Files from the Command Line](https://markdownmonster.west-wind.com/docs/_4x313dneu.htm)

Not sure why that wouldn't work for you. MM installs the path during installation and for the portable version on first application startup and then on subsequent startups.

**Comment by paule96** [comment]
Hm if I restart my PC, after installing I see the variable. Is it possible without a restart? Or can the installer ask for restart?

Also what is wired is that the deinstallation don't remove the path entry. (I restart the PC after deinstallation to validate this)

**Comment by RickStrahl** [comment]
You shouldn't need to restart. But you do need to restart the Terminal - anything that's already running will have to restart to see a change in the Windows Environment unless it has some explicit way to reload it.

**Comment by paule96** [comment]
I have restart the powershell before I test this. So this is a realy wired behavior. I try the install and deinstallation tomorrow again.
