### ISSUE TITLE
Snippet Template - csc.exe missing

### ISSUE THREAD

**Issue by pmgeuze** [RickStrahl/MarkdownMonster#625]
I am unable to execute the Snippets Template due to an error related to roslyn/csc.exe.

![image](https://user-images.githubusercontent.com/12847134/73092653-fab8d100-3eaa-11ea-84e8-7c065ee19a5f.png)

![image](https://user-images.githubusercontent.com/12847134/73092675-02787580-3eab-11ea-9002-03c1256f9f9b.png)

I am only trying to run the included snippet for Date Time, which looks great, when I get this error.

I found that there is a csc.exe-config file and I renamed it csc.exe but the error was still there. 

I have also uninstalled, downloaded, and reloaded the program again with the same error, and missing file.

I cannot find any error log data to attach.

I look forward to being able to create report snippets to my reporting template.

Thank you again for such a great program.

**Comment by RickStrahl** [comment]
Thanks for reporting. 

Interesting I didn't see this because the installer left behind the `csc.exe` on a new install from older versions so it was working here.

Fixed by changing the build script to not exclude csc.exe

4d7c136f27ff0a905089aeb210eac4d52ced7163

**Comment by pmgeuze** [comment]
Thank you for your quick and effective response.
