### ISSUE TITLE
DocFX Flavored Markdown

### ISSUE THREAD

**Issue by pmgeuze** [RickStrahl/MarkdownMonster#626]
I see that the Settings allows for changing the type of MarkdownParser that can be used in MM. I believe I want to try DocFX Flavored Markdown, for the UID functions and some additional functions.

The best I can understand is that DFM is an extension for VisualCode and not something you can download as a separate Markdown for MM.

Please let me know if I am missing something in how to use UID in MarkDig, or how to select DFM as the default Markdown Parser. 

I hope to use MM for Markdown, instead of using VS just to access the DFM functions.

Thank you as always for your product and continued support.

**Comment by RickStrahl** [comment]
In order to use a custom Markdown parser you have to create an Addin and implementat the `IMarkdownParser` interface.

The process takes a little bit of an effort as you have to create the .NET Addin project, but it's pretty straight foraward to implement a new Markdown Parser to add to MM.

**Comment by pmgeuze** [comment]
Thank you for the input, I will look in to doing that as a project.
