### ISSUE TITLE
Memory Error - Crash - Recovery - Saving Settings

### ISSUE THREAD

**Issue by pmgeuze** [RickStrahl/MarkdownMonster#627]
Sir,

I have noticed over a number of days, on different machines, writing different sized documents, that I will cause a shutdown of MM when I am trying to save the Settings to a ZIP file.

In my last case, I set the Font to 24 -> 22 ->20, and then the Zoom from 125% -> 100% and then save to ZIP -> selected folder location, before receiving the error message "**OutOfMemoryException**".

In most cases, I could select "**OK**" to continue, or restart MM with no apparent loss of data.

[MarkdownMonsterErrors.txt](https://github.com/RickStrahl/MarkdownMonster/files/4159330/MarkdownMonsterErrors.txt)

**Comment by RickStrahl** [comment]
I think this is related to this issue:

https://weblog.west-wind.com/posts/2016/dec/15/wpf-rendering-ducechannel-crashes-due-to-image-loading

One thing you can try is disable hardware rendering:

![image](https://user-images.githubusercontent.com/1374013/73993115-606a7b80-48f5-11ea-9584-d2717a5c512e.png)

and see if this improves the errors...
