### ISSUE TITLE
View Menu item for "Toggle centered layout" has unreadable text

### ISSUE THREAD

**Issue by Smurf-IV** [RickStrahl/MarkdownMonster#628]
V 1.21.1
Windows 10 x64 1903
![image](https://user-images.githubusercontent.com/2418812/74220286-168fe580-4ca7-11ea-9583-292c163379c8.png)

**Comment by RickStrahl** [comment]
Thank you. Fixed hardcoded color value. This makes it not stand out but it works in both Light and Dark themes. Highlighting shows only in 

![image](https://user-images.githubusercontent.com/1374013/74320557-f141bc80-4d24-11ea-8af9-d08c9dfffd6a.png)

![image](https://user-images.githubusercontent.com/1374013/74320589-ff8fd880-4d24-11ea-8fa6-f7edfa916a4b.png)



![image](https://user-images.githubusercontent.com/1374013/74320472-c5263b80-4d24-11ea-9cd5-df0a69904c53.png)

![image](https://user-images.githubusercontent.com/1374013/74320510-d53e1b00-4d24-11ea-9060-90ce493ef49d.png)
