### ISSUE TITLE
Documentation states to "Open From URL" but this does not work

### ISSUE THREAD

**Issue by Smurf-IV** [RickStrahl/MarkdownMonster#629]
V 1.21.1
Location attempting to open
`"https://github.com/RickStrahl/MarkdownMonster/blob/master/SampleDocuments/MathJax.md"`

Instruction is found in

`https://markdownmonster.west-wind.com/docs/_59l0mv2uw.htm#icon-info-circle-sample-document`

MM just opens a new blank file.

FYI: Clicking on the link does open the `MathJax.md` file in the browser, so the file does exist.

**Comment by RickStrahl** [comment]
Thanks - turned out to be a timing bug where the document was updated before the editor document has been loaded. Rather than using a Dispatcher and delaying I've added a new method to the Markdown Editor now that now fires a new 'event' when the document has been loaded.
