### ISSUE TITLE
Suggestion: Add possibility to post to git(hub)

### ISSUE THREAD

**Issue by weggetor** [RickStrahl/MarkdownMonster#63]
Hi Rick,

I have some projects on Github (like a lot of other people), and it would be nice to download and edit README.MD file directly with MM. I know I can edit it with MM in my project directory and then publish the doc from there, But downloading, editing and pushing back to Github would be a very nice feature that should have a very good advertising effect for MM also.

**Comment by RickStrahl** [comment]
Yeah that's something I've thought about, but this is best handled by an add-in rather than base functionality.

**Comment by RickStrahl** [comment]
If we can have more discussion on what this would look like that would be great. 

In a nutshell this would have to be scoped tightly as this can get away quickly. Simple behavior commit and push of a single file if there are no other commits pending. But what happens if other files are staged since git doesn't support partial commit and push operations.

Discuss.

**Comment by M-Zuber** [comment]
>But what happens if other files are staged since git doesn't support partial commit and push operations.

Would the following be feasible?
1. unstage 
2. stash all except the selected file
3. commit
4. apply stash 

If this is done from a `git` perspective, you get support for any git remote for free and it does not have to be Github specific.

**Comment by RickStrahl** [comment]
That could work. I presume you could do this with LibGit. Anybody want to take a stab at that with an Addin? I can help set up the add-in, but don't have time to deal with the Git related features right now.

**Comment by gep13** [comment]
@RickStrahl looks like it should be possible, yes: https://github.com/libgit2/libgit2sharp/blob/3f9b415fa1edfc31ce1ec2b4b3d18441c34adfff/LibGit2Sharp/Stash.cs

**Comment by M-Zuber** [comment]
Stashing alone might not be the answer though as takes *all* files, this needs real git chops.

**Comment by RickStrahl** [comment]
I suppose it could be short cut by checking for staged files, and if any are staged asking if you want to commit all. Otherwise if not then just stage and commit the file being edited. I'd guess in most of the cases the edited file is the only one to commit or it might be the right time to commit what's pending (at which point you might want to open your preferred Git client or the Command Prompt.

**Comment by alexwiese** [comment]
I think this is what you want

    git commit --only README.md -m "Updated README.md"
    git push

I've tested it and it will bypass any currently staged/unstaged changes.

**Comment by RickStrahl** [comment]
FWIW, I've just put out a pre-release of a Commander C# Scripting addin which should allow automation of this process without having to create an addin. 

https://github.com/RickStrahl/Commander-MarkdownMonster-Addin

One simple way I've started using this is to open my GitClient with a hotkey like this:

![image](https://cloud.githubusercontent.com/assets/1374013/22999825/985d64fc-f381-11e6-9d89-437b826e50d2.png)

This loads the active repo with the relevant file pre-selected for commit and ready to type in the commit message.

For creating something more automated I think you'd still want to use an Addin to handle the commit message and any potential push issues if you need to make sure you're not pushing more than just the one file. This is one reason I like using the Git Client as above - I can see what's pending more easily.

**Comment by RickStrahl** [comment]
FWIW, here's a [Command Addin Snippet](https://github.com/RickStrahl/Commander-MarkdownMonster-Addin) that commits the current file to git and pushes to Origin:

```cs
var doc = Model.ActiveDocument.Filename;
var docFile = Path.GetFileName(doc);
var docPath = Path.GetDirectoryName(doc);

Directory.SetCurrentDirectory(docPath);

Console.WriteLine("Staging " + docFile);
bool result = Model.ExecuteProcess("git.exe","add --force -- \"" + docFile + "\"");
Console.WriteLine(result ? "Success" : "Failed");

Console.WriteLine("Committing...");
result = Model.ExecuteProcess("git.exe","commit -m \"Updating documentation for " + docFile +"\"");
Console.WriteLine(result ? "Success" : "Failed");

if (!result)
   return null;

Console.WriteLine("Pushing...");
result = Model.ExecuteProcess("git.exe","push --porcelain --progress --recurse-submodules=check origin refs/heads/master:refs/heads/master");
Console.WriteLine(result ? "Success" : "Failed");
```

**Comment by RickStrahl** [comment]
Closing this and moving discussion to #190.

**Comment by RickStrahl** [comment]
I've added support for committing and pushing to Git. The option is available for:

* The active document (Tab context menu and Tools menu)
* Any file in the Folder Browser (File context menu)

Here's what the option looks like on a tab of the active document:

![image](https://user-images.githubusercontent.com/1374013/26871800-40088ffc-4b29-11e7-9af9-97e42a56e2df.png)
