### ISSUE TITLE
`Markdown.UseMathematics` no longer respected

### ISSUE THREAD

**Issue by Smurf-IV** [RickStrahl/MarkdownMonster#630]
V 1.21.1
With the `Markdown.UseMathematics` set to true, the LaTex expressions are no longer rendered.

![image](https://user-images.githubusercontent.com/2418812/74220977-e6e1dd00-4ca8-11ea-8d73-4128ba4b4c14.png)

Workaround:
Need to go to the Edit Menu and set the "Allow script tags..." to then enable the formulae to be displayed
![image](https://user-images.githubusercontent.com/2418812/74221064-21e41080-4ca9-11ea-9f32-072961c94f23.png)

**Comment by RickStrahl** [comment]
Yes, that's by design. 

I'm not sure that I'd want to automatically enable script tags because it's a potential security vector, but at the very least there probably should be a note in the description to point that out.

**Comment by Smurf-IV** [comment]
I do not remember having to enable the scripts tags before 1.21 to get the mathematics to be displayed correctly. 
That is what this bug is trying to say.

**Comment by RickStrahl** [comment]
Added a note to the Settings text that Allow Script Tags in Markdown has to be set as well.

![image](https://user-images.githubusercontent.com/1374013/74311605-f64a4000-4d13-11ea-8ebf-0114bdae2ac9.png)

**Comment by Smurf-IV** [comment]
Will the documentation all be updated,
Or can it automatically set that option if it is not when the user enables the "Use Mathematics"
Also, will the tooltip on the Allow script menu item also state that it will disable Mathematics, etc.

(It all gets a bit confusing !)

**Comment by RickStrahl** [comment]
I don't want to enable the script rendering automatically because it's a potential security risk. It's off by default. Script rendering will affect a number of things. UseMathematics is on MermaidGraphs is another. The Gist Addin (for embedding Gists) another.

I'll add some UI to let users know if they scripts off.
