### ISSUE TITLE
On a dual screen set-up - Closing MM will cause the "Save changes dialog" to appear on the other monitorr

### ISSUE THREAD

**Issue by Smurf-IV** [RickStrahl/MarkdownMonster#632]
V 1.21.1
Run Application on Monitor 2
Make edits to a file
Close MM without saving
"Save Changes Dialog" appears on Monitor 1

MoreInfo: the "MM is hungry etc" displays on the monitor that the application was running on !

**Comment by RickStrahl** [comment]
Simon, can you send me your contact info to shoot a license your way for your help on all of these issues?

https://west-wind.com/contact/
