### ISSUE TITLE
`Model.Console.WriteLine` does not do anything with the colored brush passed to it

### ISSUE THREAD

**Issue by Smurf-IV** [RickStrahl/MarkdownMonster#633]
V 1.21.1
                    Model.Console.WriteLine(text, System.Windows.Media.Brushes.Red);
is still displayed as black text

Nothing states that this is a WIP.

**Comment by RickStrahl** [comment]
Added suppport:

![image](https://user-images.githubusercontent.com/1374013/74490247-ffe6bb80-4e6b-11ea-92d3-338a4f16bb13.png)
