### ISSUE TITLE
`AddMenuItem` example needs to be updated to reflect current implementation

### ISSUE THREAD

**Issue by Smurf-IV** [RickStrahl/MarkdownMonster#634]
V 1.21.1
documentation @ https://markdownmonster.west-wind.com/docs/_4zv0o3r46.htm#Adding-Menu-Items-to-the-Markdown-Monster-Menu

states that the api uses `menuItemName: "ButtonOpenFromHtml"`
This is no longer valid.

Also
the description of the API on that page needs to be modified to use the correct variable names
i.e. 
``` C#
    public bool AddMenuItem(
      MenuItem mitem,
      string menuItemNameForInsertionAfter = null,
      string menuItemTextForInsertionAfter = null,
      int mode = 0)
```

**Comment by RickStrahl** [comment]
Fixed.

https://markdownmonster.west-wind.com/docs/_4zv0o3r46.htm
