### ISSUE TITLE
Weird things happen when setting the Height of the console window

### ISSUE THREAD

**Issue by Smurf-IV** [RickStrahl/MarkdownMonster#635]
V 1.21.1
- Start MM
- Writeline to the console (This makes it display in a default size)
- Use the Black line above to increase the size of the window
-- All is good

- Close MM and now add the following line (after the initial writeline)
-- `Model.Console.Height = 200;`
- Restart MM
- Writeline to the console (This makes it display in a default size)
-- This is not as expected as the size should be larger
- Use the Black line above to increase the size of the window
-- once you get above a certain size the windows become detached
-- see enclosed video (Save and remove the ".renameMe.zip" extension)

[Sizing Console.mp4.renameMe.zip](https://github.com/RickStrahl/MarkdownMonster/files/4186017/Sizing.Console.mp4.renameMe.zip)

**Comment by RickStrahl** [comment]
The console height isn't stored between restarts. There are already so many window size settings saved and given that this is an edge feature not even used internally by MM (only by addins at this point anyway) the complexity of managing yet another window setting is not warranted here. That may change in the future but right now, not so much.

I appreciate the video, but please don't attach videos as separate files here. It's better to upload to a service and link that than having to download and locally play a video file. Thanks.

I guess I'm not sure what you mean by 'become detached'. I played around with the sizing and it looks to me that you can certainly do funky stuff with sizing the console with it filling the entire window, but that's pretty much of your own doing.

![ConsoleResize](https://user-images.githubusercontent.com/1374013/74568414-03398000-4f1c-11ea-93db-472f831ec6e2.gif)

**Comment by RickStrahl** [comment]
Actually looks like the console size **is** actually saved between restarts, so perhaps you're not running the latest version?

**Comment by Smurf-IV** [comment]
Sorry I missed this, I've been on another project and away. Will let you know when I need to program this again, and re-open if I do. Do not assume, that non-coms that it has "Gone-away" :-)
