### ISSUE TITLE
Hitting Ctrl key marks document as changed (on unregistered version only)

### ISSUE THREAD

**Issue by bartlannoeye** [RickStrahl/MarkdownMonster#637]
I noticed some strange behavior today:

Part 1: unregistered version MarkdownMonster (repaved my machine).
- Opened existing md file (tracked in git repo, edited with MarkdownMonster before).
- Selected line of text
- Hit Ctrl (to copy with Ctrl+C)
- Document is marked as changed (* behind filename)
- Saving document shows it as tagged in GitKraken (but with no changes)

Managed to undo changes and repeat steps above with same result.

Part 2: registered MarkdownMonster with my key
- Repeat steps above
- Document is not marked as changed

Running on Windows 10. Document is UTF-8 encoded and line-endings are LF (according to Notepad++).

**Comment by RickStrahl** [comment]
Hmmm... I can't duplicate that. 

But my suspicion is that it has something to do with the CRLF handling which is global for the editor.

![image](https://user-images.githubusercontent.com/1374013/74309910-f6484100-4d0f-11ea-850e-a12d7ede1c45.png)

If you have a CRLF setting other than what the document on disk has stored on disk, the document is translated when loaded. This happens asynchronously so it doesn't show immediately as updated but the first few keystrokes likely trigger the conversion at which point you see the changed document.

I can't make this happen though any way I try.
