### ISSUE TITLE
Unable to close/exit Document Tab - No document in Editor box

### ISSUE THREAD

**Issue by pmgeuze** [RickStrahl/MarkdownMonster#645]
I have a folder of .md files. I load the first file which opens a tab in the Editor view, but with no data in the Editor. I can then open additional files, including the first file, but now in an additional tab.

After working on the documents, I can close all the documents, except for the first tab, which is still empty.

I have tried this with different files as the first file and I still get the same issue.

MM does not throw an error, this is submitted as an observation.

image showing first file open as empty tab.
![2020-02-27 09_15_25-W__Cases_ia200006_Narrative_Report_IA200006 md  - Markdown Monster](https://user-images.githubusercontent.com/12847134/75454110-e604a880-5942-11ea-9d5e-c440560c00da.jpg)

Image showing two tabs with same file.
![2020-02-27 09_14_46-W__Cases_ia200006_Narrative_Report_IA200006 md  - Markdown Monster](https://user-images.githubusercontent.com/12847134/75454129-eb61f300-5942-11ea-91f2-ba496c7b2ca7.jpg)

Error Log
[MarkdownMonsterErrors.txt](https://github.com/RickStrahl/MarkdownMonster/files/4262091/MarkdownMonsterErrors.txt)

Please message me for actual .md file used due to sensitive data.

Thank you.

**Comment by RickStrahl** [comment]
Looks like there's a problem with running out of memory.

So a couple of question:

* Is this a consistent that's repeatable for you?
* Is it only this one document, or others?
* Is the machine running low on resources?
* Any chance to try this same doc on a different machine?

I see the error as:

```
AppDispatcher: Insufficient memory to continue the execution of the program.
Insufficient memory to continue the execution of the program.

PresentationCore
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
```

This error is a WPF internal error, usually associated with a hardware rendering. I actually wrote about this here a while ago:

https://weblog.west-wind.com/posts/2016/Dec/15/WPF-Rendering-DUCEChannel-Crashes-due-to-Image-Loading

There are a couple of suggestions:

* Make sure you have the latest video drivers on your machine
* You can disable HardWare rendering in Markdown Monster

To disable Hardware rendering:

* Goto to Tools | Settings
* Type *Hardware* into the search box
* Check **Disable Hardware Acceleration**
* Restart MM

This disables Hardware GPU rendering and uses Software rendering instead and that typically fixes these sort of errorrs.
