### ISSUE TITLE
RTL Processing in Editor and Previewer

### ISSUE THREAD

**Issue by RickStrahl** [RickStrahl/MarkdownMonster#646]
I've added some basic RTL and LTR switching support to the editor which allows for editing individual paragraphs as RTL content.

> RTL support is available in [preview versions](https://markdownmonster.west-wind.com/download.aspx) (1.21.2.4+). It may get pulled for later releases

To do this:

* Go to Settings
* Check 'Enable Right To Left'
* Use Ctrl-Alt-Shift-R and Ctrl-Alt-Shift-L to toggle between RTL and LTR for a paragraph

### Background
ACE Editor has some support for this built in and this via the `ext-rtl.js` module which basically adds the hotkey commands that are bound to default hotkeys for switching  between RTL and LTR modes.

This works in the editor, and displays what appears to be correct, but frankly I can't tell what the appropriate and expected behavior for RTL text in any of the languages that use RTL, **so I need some help in understanding all the issues and what the behavior should be**.

### Saving RTL State
There are two issues related to RTL in Markdown Monster:

* Editor Support for editing in RTL mode
* Displaying RTL content in the Previewer and in rendered output

It looks like ACE handles the editor part just fine. However, it also appears that ACE injects additional content into the document to identity RTL formatted text. So if you switch to RTL editing mode, save the document, shut down and re-open the RTL text immediately shows with the original RTL formatting  rather than requiring explicitly switching into RTL paragraph mode.

There are a few problems with all of this:

* It seems other editors don't see RTL and if you open a saved document it'll just show 'as is' in LTR
* ACE inserts extra characters into the document which throw of MarkDig when rendering into HTML

What characters?

### RTL Rendering Weirdness
RTL rendering has to be enabled in MarkDig via the `UseGlobalization()` extension which is enabled when setting the `Enable Right To Left` configuration setting in MM.

RTL rendering in MarkDig works by looking for RTL specific characters in the Markdown content during rendering and if it finds it adjusts the output for RTL by adding `text-direction` and `right` styling to paragraphs.

This works find for text that is displayed without RTL formatting (or saved) in the editor. But when the formatting is enabled then the extra characters that ACE injects are causing any RTL text to be treated as one very long paragraph.

![image](https://user-images.githubusercontent.com/1374013/75834465-22c80980-5d60-11ea-8fbe-07e00a1c6811.png)

Notice the first block rendering correctly in the preview with the paragraphs displaying correctly. The second block doesn't find the paragraph breaks and treats the whole thing like a single paragraph.

In a hex editor you can see that the RTL text is formatted differently for breaks:

![image](https://user-images.githubusercontent.com/1374013/75835175-44c28b80-5d62-11ea-98c9-7517a69eea84.png)

It looks like ACE is adding characters `20 2B` after any line breaks. Guessing this breaks MarkDig which treats these as white space and a line continuation.

Frankly I have no idea what this does, but since ACE can detect this format and re-display the text as RTL when re-opening there must be hints in there that ACE can deal with. Other editors like NotePad, Word, Code however don't see that and just show the text as LTR. 

Again I need some help what the expected behavior should be. Is ACE just doing something specific to ACE editor or this some sort of standard editor behavior for RTL marked text?

In the editor this looks fine, the problem is MarkDig is not rendering correctly, presumably due to the extra characters after the line break treating the 

I've also raised a general issue on the ACE repository with hopefully more information on how RTL is expected to be handled:

https://github.com/ajaxorg/ace/issues/4204

**Comment by HamedFathi** [comment]
@RickStrahl 

Thank you so much. The current achievement is so cool.

![image](https://user-images.githubusercontent.com/8418700/75863386-9d9f2c00-5e15-11ea-8653-22015ab36bbd.png)

Two questions:

1. Is it possible to change font of the preview and the final PDF output? (Although the Editor works perfectly)

2. Is it possible to change the shortcuts (Ctrl-Alt-Shift-R and Ctrl-Alt-Shift-L)? (Just like Windows, Left/Right Alt+Shift)

**Comment by RickStrahl** [comment]
The fonts are controllable via Preview Themes, You can [customize or create a new Preview Theme](https://markdownmonster.west-wind.com/docs/_4nn17bfic.htm) and then switch to that for printing.

As to the hotkeys - I'm using the default keys that the extension uses. I have to see if that can be remapped easily without re-implementing the entire extension.

For now I just want to see whether this will work. Did you try longer text and multi-paragraph? I think this is where this is likely to break and stop being useful.

I'm a little afraid adding this functionality as it will lead to a slew of potential issues that I'm going to have a hard time even understanding correctly 🤣

**Comment by RickStrahl** [comment]
So I'm looking at the hotkeys and what should those be? Unfortunately ACE doesn't support differentiating between left and right keys. Also Word seems to use Right-Shift and Left-Shift. 

I don't really see RTL working anywhere else really. 

In short it won't work with the same commands as you suggest. Also I think it's a bad idea to muck with that as some computers may not have those keys on the right.

I've made it a little easier with Alt-Shift-R and Alt-Shift-R.

I think I figured out a way around the rendering issue by stripping out the RTE and LTE marker characters so breaks are now rendering properly.

Unfortunately it looks like there's another more serious bug regarding layout. Text that wraps using Arabic or Hebrew text seems to not size itself properly in Internet Explorer where a full line of text goes just beyond the end (or the beginning) of the line. It works with western fonts but in Hebrew and Arabic, both extend beyond the end of the line 😦   It works in Chrome (although there too the width isn't right but at least it's too short, not to wide) but in Internet Explorer the sizing just seems off. Not holding out much hope this will get fixed because it's an IE only bug, but @HamedFathi  if you could just play around with that to see just how bad that is it would be useful.

I've looked at what the RTL processing is actually doing and it's basically manually recalculating positions in the editor which is some pretty whacky code. I have no idea how I could possibly fix this myself...

Latest build (1.21.3.8) has these latest changes in it.

**Comment by HamedFathi** [comment]
@RickStrahl 

> Is it possible to change the font of the preview and the final PDF output? (Although the Editor works perfectly)

In the latest version (1.21.4.0) it works.

> I don't really see RTL working anywhere else really.

If you mean other Markdown tools, Yes, AFAIK Markdown Monster is the first one to support RTL.

> I've made it a little easier with Alt-Shift-R and Alt-Shift-R.

Cool

---

Something is weird, especially with **Curser**. 

* Curser is not in the correct location (At the beginning or end of a line)
* The lines in a paragraph are not justified. (In preview too)
* I found a red dot between some characters!

Please see this Gif file:

![test](https://user-images.githubusercontent.com/8418700/75995869-4c289700-5f12-11ea-97c1-e8ffd7b9a3bb.gif)

Even with all these problems, I believe this feature is valuable enough.

**Comment by RickStrahl** [comment]
Can you try the above with **Toggle Centered Layout** off? Does the cursor off the side still cause problems?

Unfortunately, the odd behavior of the cursor is mostly IE related it seems. In testing the editor standalone I don't see these discreprancies in Chrome, but I see them in IE. I suspect it's the difference in Font and Margin handling for the RTL fonts that's causing these issues. If that's the case there really nothing much I can do about it at this time (until MM switches to a Chromium browser which hopefully will be as soon as there's an Edge based Chromium WebView2).

The RTL module in ACE is crazy hacky as it's basically repositioning the cursor explicitly after each key typed. IOW, ACE doesn't really support RTL natively it's just faking it by recalculating cursor positions.

This is why I think for now at least I won't be able to keep this support inside of MM. There'd be too many issues that can't get addressed. But for the moment lets see what can be done with this.
