### ISSUE TITLE
Could we have consistent way of handling hashtags in the path?

### ISSUE THREAD

**Issue by sanychsamara** [RickStrahl/MarkdownMonster#647]
Is there any consistent way to link to a file that has a hashtag anywhere in the path?

In order for link anchor to render correctly I need to prefix hashtag with a slash.  But in order for file/image to link correctly I need to url encode file path. 

Ideally I would like for hashtags to be transparently supported without encoding. 

Example 
```
[\#Hashtag\test.pdf](%23Hashtag\test.pdf)
```

Alex

**Comment by RickStrahl** [comment]
I'm not quite sure what you're asking. Hashtags are supported and you don't need to encode them.

```markdown
* [Content Injection with Response Rewriting in ASP.NET Core 3.x](#content-injection-with-response-rewriting-in-aspnet-core-3x\test.pdf)
```

This renders the HREF as you would expect:

```text
/path#content-injection-with-response-rewriting-in-aspnet-core-3x%5Ctest.pdf
```
