### ISSUE TITLE
Remember Save To PDF Settings between Runs

### ISSUE THREAD

**Issue by jongliko** [RickStrahl/MarkdownMonster#650]
Hi,

Is this possible to make the Export Settings Window remember last choices or a way to set default values. For example A4 and 200dpi.

It will be a really greate features,

Thanks Nicolas

**Comment by RickStrahl** [comment]
Yeah a few people have asked for this.

This will require some additional configuration settings that store this information in the configuration.

**Comment by RickStrahl** [comment]
Fixed in: 9ad306fb
