### ISSUE TITLE
[Feature Request] Choose tables size. (ex: 3x3)

### ISSUE THREAD

**Issue by jongliko** [RickStrahl/MarkdownMonster#651]
Hi,

Just an idea. When creating tables it could be greate to have a way to choose the table size. Like 3 x 3.

I have seen this in [https://ui.toast.com](url)

![image](https://user-images.githubusercontent.com/5091679/78135859-dd603000-7422-11ea-9ff5-019bd4b690bf.png)

If it's too complicated maybe just two inputs like this 

[https://github.pytes.net/tail.writer/](url)

![image](https://user-images.githubusercontent.com/5091679/78136323-b0604d00-7423-11ea-98d0-3f1dc6690524.png)

Thanks again for your greate works,

Nicolas

**Comment by RickStrahl** [comment]
You've always been able to add columns via the menus. And rows are auto-created by tabbing, so a UI for this is really not necessary.
