### ISSUE TITLE
Option to download online images and replace their url with local path

### ISSUE THREAD

**Issue by parasiteoflife** [RickStrahl/MarkdownMonster#652]
Title says it all. It would be possible to add such feature?
It would be nice to have that in the context menu when right clicking on a url pointing to an image.

**Comment by RickStrahl** [comment]
It's already there. 

Use File -> Save To -> Save to HTML

![image](https://user-images.githubusercontent.com/1374013/78464799-5496fd80-7689-11ea-8c51-a3d7bf3b5f1d.png)

**Comment by RickStrahl** [comment]
Ok, so I added this feature after some thought:

![image](https://user-images.githubusercontent.com/1374013/78966687-3885c880-7a9c-11ea-8651-3a15cabe6c3a.png)

Image goes in the last image folder or the document's image folder and the path gets embedded as a relative path.
