### ISSUE TITLE
[Feature Request] LateX Autocompletion

### ISSUE THREAD

**Issue by kxxt** [RickStrahl/MarkdownMonster#655]
Hi,

Before using MarkdownMonster,I use VSCode with plugins to edit markdown.

One of the plugins , [Markdown All in One](https://github.com/yzhang-gh/vscode-markdown)'s autocompletion feature is very useful for math typing.

The implement of the above plugin's autocompletion feature is [here](https://github.com/yzhang-gh/vscode-markdown/blob/master/src/completion.ts).

It would be nice if you could port this feature to Markdown Monster.

Thanks for your great work.

**Comment by RickStrahl** [comment]
Markdown Monster isn't a code editor but a text. I know it would be really nice to provide popup help but currently there's no implementation for auto-completion of any sort in the editor. I believe ACE provides that feature, but MM doesn't use it and the Markdown syntax we use doesn't expose any auto-complete features at all AFAIK.

The Markdown syntax also is a mix of a bunch of languages rolled together so it's actually perhaps the most complex of languages supported.

The way this can be done is to create a custom language and override the start `mode-markdown.js` functionality.

So from my end this is a no go, but if anybody wants to take a crack at it and gets the basics of it working I'm willing to change my mind :-) 

For now this is a no-go.
