### ISSUE TITLE
PreviewSyncMode EditorToPreview does not follow changes within code block

### ISSUE THREAD

**Issue by SMTStuck** [RickStrahl/MarkdownMonster#659]
If in the preview window there is a code block off the end of the page and edits are made to the end of said code block the preview window does not scroll to those changes.

![CodePreviewTracking](https://user-images.githubusercontent.com/28392792/81425450-8a7b4600-914f-11ea-9866-e65f3aaeb399.gif)

**Comment by RickStrahl** [comment]
Yes that's a known issue - reason is that the Markdown generation can't pragma lines for code blocks (or other block elements) because they get rendered on the client side.

So this is not something that's going to be fixed.
