### ISSUE TITLE
Please add export to formats as PDF, Word

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#66]
Notably missing support for export to PDF, Word, LaTex and ePub.

Please add.

**Comment by RickStrahl** [comment]
You'd already asked this before... please don't repeat questions.

This is beyond the scope of what Markdown Monster should handle IMHO.

**Comment by ArthurZ** [comment]
I added about PDF I recall.
Tools as Typora has it via Pandoc and even more formats.
PDF is really necessary as the most common standalone media distribution.
