### ISSUE TITLE
No more than 5 documents restored upon startup

### ISSUE THREAD

**Issue by SMTStuck** [RickStrahl/MarkdownMonster#660]
If the application is closed with more than 5 documents open, after loading the app up again there are never more than 5 documents restored.

**Comment by RickStrahl** [comment]
This is configurable via a setting.

![image](https://user-images.githubusercontent.com/1374013/81550243-a9c6ce80-931b-11ea-94d0-dc1f8e6a24d7.png)

**Comment by SMTStuck** [comment]
No, with respect you're mixing up a recent document count and loading last workspace.

That setting _should_ be for the number of recent documents available from "File -> Recent Documents".

When I load up the application it should be able to fully restore my last workspace - there is absolutely no reason I would only want want half of it loaded. It should either be supported or not at all, not relegated to a mixed up setting for the recent document count.
