### ISSUE TITLE
Enhancement: Option for Tab + Shift Tab to move to last used tab.

### ISSUE THREAD

**Issue by SMTStuck** [RickStrahl/MarkdownMonster#662]
As per the request, it would be nice if there was an option for tab and shift and tab to move to the last used tab rather than to the next or previous tab in the tab list.

**Comment by RickStrahl** [comment]
I'm not sure what you mean. Tab and Shift Tab are valid and widely used  editor commands so those keys are not going to be remapped.

Current tab navigation is via Ctrl-Tab/Ctrl-Shift-Tab. There's only so many keys to go around.

**Comment by SMTStuck** [comment]
My apologies, that should have been control and tab, not shift and tab and I have not explained it too well. So shall try again:

It would be nice to include an option for Ctrl-Tab to jump to the last active tab. rather than the next one in the tab listing. Load up Visual Studio and have a few tabs open, select two at random that are not next to each other and try holding Ctrl and tapping Tab. It shows the tab listing by most recently accessed and releasing Ctrl will go to the last accessed tab.

**Comment by RickStrahl** [comment]
Nice to have, but won't fix. Currently we don't track what tab was active last.

**Comment by HeyJoel** [comment]
I'm also interested in this feature, I find it much more useful to toggle between two files that to cycle through all open docs. Two apps I know of that make this optional are FireFox and Notepad++. In Notepad++ it's referred to in settings as "Enable MRU behavior", in FireFox it's "Ctrl+Tab cycles through tabs in recently used order".
