### ISSUE TITLE
V 1.22.5.9 Update just made text unreadable

### ISSUE THREAD

**Issue by Smurf-IV** [RickStrahl/MarkdownMonster#665]
I had the previous general version. (1.22.0.0)
Just installed and re-opend the file I was working on;
And Gotr this:
![image](https://user-images.githubusercontent.com/2418812/82876903-641c1f80-9f31-11ea-864e-213d13e2b254.png)

<br />
<br />
<hr />
<br />
FYI: These settings / themes

![image](https://user-images.githubusercontent.com/2418812/82877274-df7dd100-9f31-11ea-899c-6aeef842e534.png)

**Comment by RickStrahl** [comment]
Ugh. Thanks for reporting this...

Fixed. This is a regression that is specific to the VsCode Light theme. It was broken when the styling of the various themes was changed to use transparent backgrounds. 

Checked the other syntax themes and other ones seem Ok, so for now switch to another theme or if you want to fix this add the following into:

`Editor\Ace\scripts\theme-vscodelight.js`

and find this style and update it:

```js
.ace-vslight {\
background-color: #FCFCFC;\
color: #333;\
}\
```

Specifically the `color` setting was missing previously.
