### ISSUE TITLE
various errors using jekyll weblog publishing and wsl2

### ISSUE THREAD

**Issue by cosmicfilament** [RickStrahl/MarkdownMonster#666]
I have been testing MarkdownMonster with wsl2 and keep getting the same errors saying that The system cannot find the file specified when I publish my post.
The markdown file gets saved even though the error is generated.
But, If I embed an image in a markdown file, the image never gets published.

Currently my weblog api url path is set to a directory in the wsl file system. But if I use a different folder that is mounted in the regular windows file system. I get the same errors.

![error popup](https://user-images.githubusercontent.com/31672618/83072658-2b696c80-a03d-11ea-9906-ac76477600a6.png)
![jekyll pub setup tab](https://user-images.githubusercontent.com/31672618/83072662-2c020300-a03d-11ea-9066-d7e601198f8b.png)

[MarkdownMonsterErrors.txt](https://github.com/RickStrahl/MarkdownMonster/files/4691879/MarkdownMonsterErrors.txt)

**Comment by RickStrahl** [comment]
The error is on the launch command and it's failing on the bash command line. 

Is the post created in the target output folder? Those are two separate steps. You can clear the Launch command which will skip the server Jekyll server launch. But the failure I think is apparently that `bash` is not found. Basically you need to find a command line that works to launch the server from cmd or powershell. The above is the only thing that worked for me but maybe somebody more familiar with how to get wsl launched and execute a command can find a better way.

**Comment by RickStrahl** [comment]
Also I don't think you that we can access the Jekyll files in a WSL folder that is not mounted to the Windows OS. The path has to be a windows path. 

For example I can't do this from CMD or Powershell:

When I do this for example:

```dos
dir \\wsl$\Ubuntu\mnt\c\projects\test\jekyll\help
```

I get access denied.

Markdown Monster has to be able to get at the files via a Windows accessible path and permissions.

**Comment by RickStrahl** [comment]
Take a look at 1.22.5.15 which has a number of updates to the Jekyll publishing. It won't fix the wsl path issue (which looks like it might be a WSL bug), but at least it shouldn't crash anymore.

**Comment by RickStrahl** [comment]
@cosmicfilament Could you try using: 

```
c:\windows\SysNative\bash.exe
```

in your command line please. Note that this is important because without the SysNative reference bash.exe will not be found which is why your launch command is failing.

**Comment by cosmicfilament** [comment]
Hi Rick.
This is the first time that I have ever opened a bug report on a github project. I am really surprised how quickly you responded.
So I dl'd 1.22.6 and used your other suggestions outline above and now it works great.
thanks.

**Comment by RickStrahl** [comment]
Nice! 

Can you verify what paths you're using and whether images are getting into the `/assets` folder? 

Publish works for me **except** for the images - the `/assets` folder is not creating for me which is some odd conflict with WSL - curious if for you this is working?

**Comment by RickStrahl** [comment]
Never mind - I figured out the problem. Looks like the path was being corrupted by the code stripping off the leading double backslash which caused the files to go to the wrong place. Operator error :smile:

Looks like it works now including pushing issues.

Thanks for reporting this - it was a use case I didn't think would actually work, but it does.

To summarize:

* Native WSL LInux paths work for publishing
* Bash.exe **has to use** the `NativeSys` explicit path
