### ISSUE TITLE
Added Javascript Tags in HTML Output

### ISSUE THREAD

**Issue by DMiradakis** [RickStrahl/MarkdownMonster#667]
Rick,

First off, thanks for this **awesome tool**. As a Business Intelligence Analyst, I am very big on documentation and release notes, and docs.microsoft.com inspired me to learn markdown and eventually find MM. I spend hours in MM on many days.

Quick question for you:

Is there a quick and simple way to add additional `<script>` tags when you take a markdown document in MM and `View Html Source` or `Save As HTML`. There are some useful Javascript files I would like to reference if possible. I searched other issues for this, but I couldn't quite find it.

I use the GitHub preview theme and DocFX parser settings in MM, and I see that MM auto-includes a jQuery script, a preview script, and a highlighting script.

![image](https://user-images.githubusercontent.com/53345819/83175785-1abf0200-a0e2-11ea-96ad-9fa616630d68.png)

Thanks!

**Comment by RickStrahl** [comment]
Yes there are a number of ways to add script to a page.

MM uses HTML templates to render so the if this is a global change the best way to do this is create a custom theme and add the script directly into the page template. Check out this topic in the docs:

[Switching and Customizing Themes](https://markdownmonster.west-wind.com/docs/_4nn17bfic.htm#theme-customization)

You basically copy one of the existing theme folders, change the name of the folder to your new theme name and then edit `Theme.html` by adding your scripts there. Then in the editor you select that theme when you need to use that template.

The other way is to simply add scripts into the page. Markdown is a superset of HTML so HTML actually works in the page including embedding script tags. You may have to enable script rendering for the preview (**Edit -> Allow Script Tags in Markdown**) if these scripts need to run in the preview.

**Comment by DMiradakis** [comment]
@RickStrahl I had read that in the documentation months ago and **completely** forgot about it. Thanks for the informative answer!
