### ISSUE TITLE
[Behavior] Optional Ctrl-L Behavior 

### ISSUE THREAD

**Issue by Randy-Buchholz** [RickStrahl/MarkdownMonster#676]
An edge case, but I'll throw it out there...

I spend a lot of time in Visual Studio and Ctrl-L to select a line is second nature. A switch to map line selection to Ctrl-L would make me swear a lot less lol.

**Comment by RickStrahl** [comment]
I don't think that's standard behavior. For me Ctrl-L deletes the current line in Visual Studio?

**Comment by Randy-Buchholz** [comment]
My typing mistake, didn't add cut after select. I think Ctrl-L is actually - select current line and cut, because it is available to paste. My basic need is moving lines around, like ordering lists with ctrl-l then ctrl-v

But thinking about selection, progressive selection by mouse and keyboard would be great. Using the mouse, double click currently selects the word the cursor is in. It would be nice to have subsequent double clicks expand that selection -  Line, Sentence, Paragraph. Also have a shortcut key for that.

**Comment by RickStrahl** [comment]
Alt-UpArrow/Alt-DownArrow moves lines up and down (same as VS Code). 

Click selection - sort of works. Double click to select and double click again to expand selection out. It's not super reliable though. You have to click pretty fast, but the functionality is there. Anyway that's a different issue.
