### ISSUE TITLE
Only the last image is posted to a Jekyll blog

### ISSUE THREAD

**Issue by LocalJoost** [RickStrahl/MarkdownMonster#679]
If I post a blog with 3 images to a local Jekyll blog setup, only the very last image in the blog post is actually transferred to my blog structure. To make things worse, if I have copied images over manually, it _deletes_ them first. So any 'post' needs to be followed by manually checking and copying images, kind of defying the purpose of the Jekyll post option

**Comment by RickStrahl** [comment]
Hmmm... verified. Not really sure what's happening there but taking a look now. Definitely looping through all the images, but something's going wrong with the writing of the files.

**Comment by LocalJoost** [comment]
Fixed already ? :)

**Comment by RickStrahl** [comment]
Ok thank you for reporting this. This was a stupid error that was in fact deleting all images but the last  before copying the images. I didn't catch this as I was testing posts with single images to verify the images were copied (duh!).

Anways, this should work in the next update.

While here I also made some additional changes to the Preview Url so preview navigation should hopefully work better than it did before.

**Comment by RickStrahl** [comment]
Updated with 1.23.15.3 at https://markdownmonster.west-wind.com/download.aspx

**Comment by LocalJoost** [comment]
Downloaded, installed and tested. Fix confirmed. Thanks!
