### ISSUE TITLE
On slow network the version check returnes "it is up to date" when it is not

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#68]
Hi,

I guess the new version check function times out, however reporting the editor is up to date whereas it is not.

**Comment by RickStrahl** [comment]
Added logic to handle longer timeout for explicit checks and make the explicit check check for 5000ms closing timeout check a little longer at 1500ms.

635b0a33d9eb5a9917c30d7a25e52166cc6003c9
