### ISSUE TITLE
[Feature Request] Citation Support (bibtex)

### ISSUE THREAD

**Issue by marcusyoung** [RickStrahl/MarkdownMonster#690]
Citation and references can be handled fine currently via the Pandoc addin.

They are entered in the document using an @ followed by the citation key, usually like:

@young2020paper or [@young2020paper]

What would be great is if when the @ key is entered MM parses a defined bibtex file (a simple text file, could be specified in YAML) and filters the options as you begin typing the author, showing the possible bibtex keys and associated titles, then allowing you to select the one you wanted which would then insert the  key at the cursor.

**Comment by RickStrahl** [comment]
Can you point to a reference for this functionality?

I ran into this but it's pretty haphazardly described here and they don't show the reference file only the markdown.

If I understand this correctly this works by referencing a `csl` file on the Pandoc commandline?

If so can you try the following:

* Go into the PanDoc configuration (click on the down arrow on the Pandoc toolbar icon)
* Pandoc Markdown Monster addin Cnfiguration
* Change the first command line at the top and include your csl file with a hard coded full path

the line of code in question should look like this in the JSON configuration:

```json
"PandocCommandLine": "-f markdown -s \"{fileIn}\" -o \"{fileOut}\"",
```

add in something like this (or whatever other command line you think is required to pull in the pandoc element.

```json
"PandocCommandLine": "-f markdown -s \"{fileIn}\" -o \"{fileOut}\" --csl=c:/Users/rick/Documents/writing/chicago.csl 
",
```


Save and quit (the parser has to be unloaded for a config change) then check your document.

It that roughly the behavior required?

Not sure if there's a good way to automate that behavior, but first lets see if we can get the desired Pandoc behavior to run by coercion.

**Comment by marcusyoung** [comment]
The Pandoc side of things is working fine already via the plugin, using:

```
-f markdown -s "{fileIn}" -o "{fileOut}"  --filter pandoc-citeproc
```

The csl file is optional.

The feature request relates only to making it easier to add the citation keys (like @young2020paper) to the markdown document that Pandoc picks up. That requires parsing of a BibTeX file by the editor as you start typing a citation. So as I type @y the list of matching citation keys would show up and I could click on one and insert it into the document. Based on what you've said elsewhere about being limited to functionality of the ACE editor then this may not be an option.

**Comment by RickStrahl** [comment]
I can interact with the editor and we can pop up lists from the host app, so that's possible. But it's a matter of how this can work without interfering with other stuff.

As I said I need better reference to figure out what even needs to happen here. Is there a spec of some sort for how the list is laid out and how it's parsed?

Most likely this feature would have to be part of the PanDoc addin since I don't think Markdig support the syntax for rendering.

**Comment by marcusyoung** [comment]
There are parsers available for many languages I think. For example, this is one for C:

https://metacpan.org/pod/distribution/Text-BibTeX/btparse/doc/btparse.pod

Here's a guide to the bibtex file:

https://www.bibtex.com/e/entry-types/
