### ISSUE TITLE
Flashing white pixel on dark themes

### ISSUE THREAD

**Issue by marcusyoung** [RickStrahl/MarkdownMonster#692]
This is pretty minor, but once you know it's there, quite distracting!

There's a flashing white pixel or two on the dark themes up on the left-hand side of the first tab. See this video:
 
http://youtu.be/SIQ5UgaU8Lw?hd=1

It only appears once you've clicked on the document area (and seems to be in step with the flashing cursor).

**Comment by RickStrahl** [comment]
Unfortunately a known issue. Looked into it a bunch of times - it's an artifact of the IE WebBrowser control and there appears to be no way to fix this (including clipping the rendering area which doesn't work with this Windowed control).

We'll have to live with this unfortunately. The good news is that I've been looking into using the Chromium based WebView in the future, once that stabilizes a bit. Prototype is running but there are a number of pre-release issues with that at this point. Hopefully in the next few months.
