### ISSUE TITLE
[Feature Request] Typewriter scrolling

### ISSUE THREAD

**Issue by marcusyoung** [RickStrahl/MarkdownMonster#694]
This fixes the scroll point about one-third from the top of the document being edited.

It means the focus when typing is always at that point. Without this you get to the bottom of the document and are always looking down at the last line of the document, unless you add loads of returns to get you back up to a reasonable viewing position.

Happy to do a screencast of another editor that does this if I'm not making sense.

**Comment by RickStrahl** [comment]
Yeah that's not going to happen. All of the core editor features (except for a handful of small enhancements) come from the underlying ACE editor and that's not something that editor supports. I think the closest thing it has is overscroll which allows for extra white space on the bottom when you scroll to the end of the document so you're not on the last line of the editor.

Personally I can't even see how that feature is helpful. I dont' know of a single editor that supports this (at least with default settings) so it seems kind of a very specialized feature of limited utility to very few people.

**Comment by marcusyoung** [comment]
I use it in Writemonkey 3 (and it's in other specialist software aimed at writers, e.g. Scrivener, as well as addons for atom, visual code studio, codemirror). I guess it's the sort of thing you may not appreciate until you've used it. It's very good ergonomically as your head is always in a good position (not looking down). Here's a video of it in visual code studio:

https://marketplace.visualstudio.com/items?itemName=andyhuzhill.typewriterscrollmode

**Comment by RickStrahl** [comment]
So I'm not going to look into this because this is pretty obscure feature and it involves really the core mechanics of the editor which is [ACE Editor](https://ace.c9.io/). If this is of interest to you can perhaps request the feature with ACE and if it gets implemented there it'll also make it into MM eventually.
