### ISSUE TITLE
Would like to be able to add custom top level attributes to front matter

### ISSUE THREAD

**Issue by LocalJoost** [RickStrahl/MarkdownMonster#695]
To support GitHub Issues comments, I have to add "comment_issue_id: xyz"  where xyz equals a number to the front matter. Unfortunately MDM deletes all custom attributes from the front matter and the customfields option writes it within a customfields tags.

**Comment by RickStrahl** [comment]
Can you provide an example for the actual markdown with the front matter.

**Comment by RickStrahl** [comment]
Ok, so added better support for top level properties in the YAML and preserving those values in the Weblog addin. The reason this didn't happen before is that the YAML runs through a serializer that will only serialize/deserialize properties it knows about, so any arbitrary additional YAML values are ignored.

Switched to manual field parsing and then adding any extraneous properties to a temporary collection which is written out when saving the meta data again.

This will work with top level property values, but won't with nested properties which is more complicated but maybe not as important.

**Comment by LocalJoost** [comment]
Thanks. Sorry I forgot to supply a clear example. I simply forgot, going to a bit of a busy time here. Is there a version I can test already?

Joost van Schaik

Senior Software Architect Mixed Reality
Windows Development MVP & Windows Insider MVP

LinkedIn: https://linkedin.com/in/joostvanschaik
Blog: https://localjoost.github.io
Twitter: https://twitter.com/localjoost

"The world as I envision it in my head is such a more interesting place"
________________________________

**Comment by RickStrahl** [comment]
Latest from the download page has this change in it...

**Comment by LocalJoost** [comment]
I am truly sorry, but either we understood each other incorrectly, or it simply does not work. I have the following stuff in my front matter in MDM

---
title: 'Solution: Visual Studio 2019 and Unity 2019.4.x LTS are very slow when adding/changing files'
categories: ''
keywords: Unity3d, Visual Studio 2019, Visual Studio Code
weblogName: LocalJoost
featuredImageUrl: https://LocalJoost.github.io/assets/2020-09-15-Solution-Visual-Studio-2019-and-Unity-20194x-LTS-are-very-slow-when-addingchanging-files/SetVsCodeAsEditor.png
postDate: 2020-09-15T21:31:30.2832072+02:00
comment_issue_id: 359
---
The red text (emphasis me) is simply stripped when I post to a Jekyll blog

Using 1.24.2, Sep 11, 2020

Kind regards,


Joost van Schaik

Senior Software Architect Mixed Reality
Windows Development MVP<https://mvp.microsoft.com/en-us/PublicProfile/4034925> & Windows Insider MVP<https://insider.windows.com/en-us/mvps/joost-van-schaik>

[cid:image010.png@01D66290.EFE73CD0]

LinkedIn<https://linkedin.com/in/joostvanschaik>  Blog<https://dotnetbyexample.blogspot.com>  Twitter<https://twitter.com/localjoost>

Sent from mail for Windows 10

"The world as I envision it in my head is such a more interesting place"

**Comment by RickStrahl** [comment]
Not sure - it's working for me in 1.24.2...

![Weblog_MetaData](https://user-images.githubusercontent.com/1374013/93270383-b8e7de00-f74c-11ea-8b57-25f9ef5ff4b6.gif)

Notice that Save MetaData does the same as posting. I put the custom property at the top so you can see it reorganzing.

**Comment by LocalJoost** [comment]
Hi Rick,

You are correct as far as the original file is concerned.
But then I hit “weblog/post to weblog” and it does not appear in the file that turn up in the path I defined in “Weblog Api Url or Local Path”.

This is, and stays in the file I edit indeed:
---
title: 'Solution: Visual Studio 2019 and Unity 2019.4.x LTS are very slow when adding/changing files'
categories: ''
keywords: Unity3D, Visual Studio 2019, Visual Studio Code
weblogName: LocalJoost
featuredImageUrl: https://LocalJoost.github.io/assets/2020-09-15-Solution-Visual-Studio-2019-and-Unity-20194x-LTS-are-very-slow-when-addingchanging-files/SetVsCodeAsEditor.png
postDate: 2020-09-15T21:46:56.9494761+02:00
comment_issue_id: 359
---

But the file that gets posted says only
---
layout: post
title: 'Solution: Visual Studio 2019 and Unity 2019.4.x LTS are very slow when adding/changing files'
date: 2020-09-15T00:00:00.0000000+02:00
tags: unity3d visual-studio-2019 visual-studio-code
featuredImageUrl: https://LocalJoost.github.io/assets/2020-09-15-Solution-Visual-Studio-2019-and-Unity-20194x-LTS-are-very-slow-when-addingchanging-files/SetVsCodeAsEditor.png
---


Joost van Schaik

Senior Software Architect Mixed Reality
Windows Development MVP<https://mvp.microsoft.com/en-us/PublicProfile/4034925> & Windows Insider MVP<https://insider.windows.com/en-us/mvps/joost-van-schaik>

[cid:image010.png@01D66290.EFE73CD0]

LinkedIn<https://linkedin.com/in/joostvanschaik>  Blog<https://dotnetbyexample.blogspot.com>  Twitter<https://twitter.com/localjoost>

Sent from mail for Windows 10

"The world as I envision it in my head is such a more interesting place"
