### ISSUE TITLE
Am I missing snippets that I should have?

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#696]
Referring to: https://markdownmonster.west-wind.com/docs/_5ne1ccv4t.htm

I came to this page looking for guidance on installing a page break. And the "Page Break Toolbar Dropdown" described there works great and does what I need.

The second method described there shows a bunch of snippets -- including the pagebreak one -- that I don't have. I have five: cwmm, datetime, blogmatter, mathtex, and mermaid. But not pagebreak. and not the others that appear in the last screenshot on that page.

Is the pagebreak snippet supposed to be installed by default or am I supposed to be adding it manually? If the former, why don't I have it? And if the latter, then I want to suggest that the text on that page could be more clear about that, because I get the distinct impression that I should already have this snippet based on the way that text reads.

**Comment by RickStrahl** [comment]
Those are test snippets that I created. They don't come by default.
