### ISSUE TITLE
Posting to Jekyll blog makes all keywords appear in lowercase and replaces spaces by dashes

### ISSUE THREAD

**Issue by LocalJoost** [RickStrahl/MarkdownMonster#699]
Before post, in the _original_ file:
`keywords: Unity3D, Visual Studio 2019, Visual Studio Code`

After post, in the _posted_ file:
`tags: unity3d visual-studio-2019 visual-studio-code`

In blog posts I migrated using the scripts supplied with Jekyll tags are shown like this:
```
tags:
- Windows Mixed Reality
- Unity3D
- HoloLens2
```

Jekyll picks that up nicely. Is is possible change MDM to follow this pattern? Optionally, if necessary?

**Comment by RickStrahl** [comment]
Hmmm... this looks like this this has changed from previous instructions. Both formats are valid BTW, but I can see how the proper case versions would be better. I'll take a look. This ties in with your other bug for the missing custom properties - same issue as what I fixed generically for the meta data - there is a fixed structure that holds the Jekyll post information that gets serialized into Yaml. I will have to manually parse the properties to capture the extra non-schema properties.

**Comment by RickStrahl** [comment]
So this turned out a bit easier than I thought at least in the outbound direction of creating a Jekyll post. With the additions I added recently in the MetaData (related to your other bug report) it's fairly easy to add in the extra values as the meta data already captures that. A few small updates for the Jekyll serializer did the trick.

![image](https://user-images.githubusercontent.com/1374013/93425327-73630800-f855-11ea-92d3-bec30c489ea9.png)

There's a little more work that needs to happen here to handle the custom field formatting properly...

**Comment by RickStrahl** [comment]
Give another try in 1.24.4...

b7a68b4c

**Comment by LocalJoost** [comment]
Hi,

Thanks for picking this up so fast but 1.24.4 creates other problems.

Original front matter before posting in original file:
---
title: 'Solution: Visual Studio 2019 and Unity 2019.4.x LTS are very slow when adding/changing files'
categories: ''
keywords: Unity3D, Visual Studio 2019, Visual Studio Code
weblogName: LocalJoost
featuredImageUrl: https://LocalJoost.github.io/assets/2020-09-15-Solution-Visual-Studio-2019-and-Unity-20194x-LTS-are-very-slow-when-addingchanging-files/SetVsCodeAsEditor.png
postDate: 2020-09-15T21:46:56.9494761+02:00
comment_issue_id: 359
---

Front matter after posting in original file
---
comment_issue_id: 359
---

Everything is gone but my comment_issue_id

Posted file after posting:
---
layout: post
title: 'Solution: Visual Studio 2019 and Unity 2019.4.x LTS are very slow when adding/changing files'
date: 2020-09-17T00:00:00.0000000+02:00
categories: []
tags: []
featuredImageUrl: https://LocalJoost.github.io/assets/2020-09-17-Solution-Visual-Studio-2019-and-Unity-20194x-LTS-are-very-slow-when-addingchanging-files/SetVsCodeAsEditor.png
comment_issue_id: 359
---

It removes the tags, and also messes up the post date.

But – it retains the comment_issue_id.

Joost van Schaik

Senior Software Architect Mixed Reality
Windows Development MVP<https://mvp.microsoft.com/en-us/PublicProfile/4034925> & Windows Insider MVP<https://insider.windows.com/en-us/mvps/joost-van-schaik>

[cid:image001.png@01D68D2A.45EA8AB0]

LinkedIn<https://linkedin.com/in/joostvanschaik>  Blog<https://dotnetbyexample.blogspot.com>  Twitter<https://twitter.com/localjoost>

Sent from mail for Windows 10

"The world as I envision it in my head is such a more interesting place"

**Comment by RickStrahl** [comment]
Aargh - posted a non-latest wrong version. Check 1.24.5...

**Comment by LocalJoost** [comment]
Hi,

By the time I checked it was 1.24.6. This seems to work properly – for both the things I reported.

Thanks, well done! And Aloha 😉

Joost van Schaik

Senior Software Architect Mixed Reality
Windows Development MVP<https://mvp.microsoft.com/en-us/PublicProfile/4034925> & Windows Insider MVP<https://insider.windows.com/en-us/mvps/joost-van-schaik>

[cid:image010.png@01D66290.EFE73CD0]

LinkedIn<https://linkedin.com/in/joostvanschaik>  Blog<https://dotnetbyexample.blogspot.com>  Twitter<https://twitter.com/localjoost>

Sent from mail for Windows 10

"The world as I envision it in my head is such a more interesting place"

**Comment by RickStrahl** [comment]
Thanks for your hell @LocalJoost!
