### ISSUE TITLE
Suggestion: Add Files TreeView option to open/switch files

### ISSUE THREAD

**Issue by Mehul** [RickStrahl/MarkdownMonster#70]
![sublimetreefolder](https://cloud.githubusercontent.com/assets/174004/20912064/d5a86278-bb21-11e6-9ff8-2c1b0cd20176.png)

**Comment by ArthurZ** [comment]
+1 thanks @Mehul

**Comment by RickStrahl** [comment]
I'm not sure I want to get into that. MM isn't a general purpose editor where you constantly are opening and closing a boat load of files.

But - if you think you want that you can think about creating an add-in that does that.

**Comment by Mehul** [comment]
Fair enough. Go ahead and close this.

**Comment by RickStrahl** [comment]
I might revisit this later once some more pressing features have been settled.
