### ISSUE TITLE
Pasting with Ctrl-Shift-v Looses Formatting

### ISSUE THREAD

**Issue by Randy-Buchholz** [RickStrahl/MarkdownMonster#703]
### Reproduce
Copy text (ctrl-c)
```
const workerPort = new Worker("/WorkerConstructor.js");
workerport.onmessage = (message) => console.log(message.data);
```

Paste with ctrl-shift-v
```
const workerPort = new Worker("/WorkerConstructor.js"); workerport.onmessage = (message) => console.log(message.data);
```
The code is pasted on a single line.

Pasting with right mouse=>paste works as expected.

#### Question
Why Ctrl-V  (cap V) to paste? Ctrl-v doesn't seem to be taken. (it just writes "v")

Also, I noticed that pasting code from Visual Studio inserts "dots" with pink background in place of spaces. Is this intentional? I assume VS puts them there, but are they not stripped/replaced for a reason?

**Comment by RickStrahl** [comment]
Ctrl-Shift-V (Paste as HTML) is a different operation than Ctrl-V (Paste text).

Ctrl-Shift-V copies as HTML. So text that's on the clipboard as plain text will render as HTML which strips line breaks. That's to be expected. When you copy from VS code and Ctrl-Shift-V you getting the HTML representation of the text which will include the formatting that VS code uses (same as if you were to paste into Word or Outlook by default for example). If you want the plain text use Ctrl-V.

FWIW MM **does not** put text as HTML onto the clipboard so it's always text that goes onto the clipboard.

**Comment by Randy-Buchholz** [comment]
There is a bug with ctrl-v but it may be hidden so you are not seeing it. Pasting with ctrl-v pastes a `v` and throws a JavaScript error asking if you want to debug. In the debugger dialog I selected "don't show again" and "no" to debugging. Now it functions correctly. Sorry I didn't get a screen grab for you. I think the error was something about length. You may be able to reproduce on a clean install.

**Comment by RickStrahl** [comment]
Debugger dialog is due to Windows Script debugging setting (which affects internet explorer/Web Browser control). By default that's off - if on it will show that dialog on any script error.

Not sure about the error itself but most likely due to clipboard corruption or similar. Usually re-copy and paste works just fine.
