### ISSUE TITLE
Paste HTML table into markdown table

### ISSUE THREAD

**Issue by VictorZakharov** [RickStrahl/MarkdownMonster#707]
I just found that I have to retype everything cell by cell, because pasting puts all content into the first cell.

![image](https://user-images.githubusercontent.com/8978766/95788588-cf307d80-0ca9-11eb-9f09-f21bf8a2da85.png)

I tried CTRL+V, Paste from Clipboard button, Load from CSV -> Import from Clipboard - none of those worked correctly.

Guess I could save as CSV in Excel and import here, but it's too late, I already converted a table with >50 cells. Would be great to have this as a default behavior for copy/paste, same as Excel.

**Comment by RickStrahl** [comment]
What are you pasting exactly?

Paste won't work with CSV - only works with HTML or Markdown tables. If you're trying to import CSV you need to dump to file and import from that. 

That said CSV is a very imprecise format so there are lots of scenarios where CSV imports can fail. MM uses a library for the CSV parsing that does a much better job than my original manual import code I had written. But there are edge cases regardless.

**Comment by VictorZakharov** [comment]
HTML table, from an HTML page, like this one - https://www.w3schools.com/html/html_tables.asp.
You can try pasting it into Excel - it's correctly distributed into columns. I also pasted into Notepad, it looks like values are tab separated.

**Comment by RickStrahl** [comment]
Hmmm... works for me:

![tableCopying](https://user-images.githubusercontent.com/1374013/95914863-081c3100-0d42-11eb-9b96-daf742c13a2d.gif)

**Comment by VictorZakharov** [comment]
I normally work in a VM. It looks like it can only paste from Chrome and that Chrome has to be running in the same session (guest to guest). Even then it tends to paste some random <br> in almost all cells, but I was surprised that it handled bolded text. Test data was taken from here:
- http://www.neolisk.com/techblog/phenomx49500vsphenomiix4955

If I try to paste from IE in the same session, or from host (running MM in a VM), then it doesn't work.
Paste output in Notepad seems to be identical in both cases, so I'm not sure why behavior is different.

If you have a VM to try, you might be able to reproduce the issue I'm talking about.
I'm using Win 8 VM under Win 10 host, and VMWare Workstation 15 for hypervisor.

MM is running in a Win 8 guest VM. There are no issues pasting images from host -> guest. So I can right click a browser image, copy, and directly paste inside VM in MM, which then prompts me for path. Not sure why pasting a data table is such a different experience.

**Comment by RickStrahl** [comment]
No I'm not going to try this on a VM. If there's not valid HTML on the clipboard it's not going to work, but that's not the problem of MM - that's your envioronment.

Also, if you're running as an Admin (without UAC) the clipboard will do weird stuff and may not work either. Again - that's Windows interfering and nothing that we can do on our end with that.

**Comment by RickStrahl** [comment]
FWIW, I did try it on a VM on my server via RDP and it works there as well.

So there's something else going on in your environment that's likely mangling the HTML on the clipboard. Not sure how you can test that though.

**Comment by RickStrahl** [comment]
FWIW your other example works as well - although that's a decidedly badly formatted HTML table (GIGO):

![image](https://user-images.githubusercontent.com/1374013/95923715-cdba9000-0d51-11eb-9048-117f7db2158e.png)

**Comment by VictorZakharov** [comment]
I connected directly via VMWare console/app, not via RDP, maybe it matters.
In this last case - I think it should be removing html tags such as this `<br>`.

**Comment by VictorZakharov** [comment]
Pasting into Notepad gives me this content:
![image](https://user-images.githubusercontent.com/8978766/95924152-07f15500-0d85-11eb-8753-d041027469bc.png)

But MM says "No HTML Table to process found".
![image](https://user-images.githubusercontent.com/8978766/95924171-12135380-0d85-11eb-90bc-32aaa12a0b04.png)

**Comment by RickStrahl** [comment]
Hi Viktor,

Thanks for checking this out...

Well that tells you there's no HTML on the clipboard to process meaning your environment is eating it. I can't change what's on your clipboard.

> In this last case - I think it should be removing html tags such as this <br>.

I don't think so. HTML markup is valid in pipe tables and it may be significant. If the author creates garbage tables you'll get garbage output and as you can see the rendering is actually correct (as the `<br>` has no effect).

**Comment by VictorZakharov** [comment]
If you are correct, Excel will fail to paste same as MM. I will try tomorrow. I currently don't have it installed on that VM.

Regarding stripping HTML tags, I think it should be an option then. Sometimes I want to paste without format. Office has this feature, paste with/without formatting.

**Comment by VictorZakharov** [comment]
You were right, guest Excel is malformed also when pasted HTML table previously copied on host.
So I guess browser and MM has to be from the same session. Learning every day.
Thanks!

**Comment by RickStrahl** [comment]
It's not really malformed, but just not HTML. It's just plain text and very likely that your VM access client simply doesn't replicate the clipboard properly - it just does text. Maybe you should RDP into the server - that seems to work fine.

**Comment by VictorZakharov** [comment]
RDP works fine - just tested. I will use that - thanks again. @RickStrahl
