### ISSUE TITLE
distraction free mode

### ISSUE THREAD

**Issue by pit2511** [RickStrahl/MarkdownMonster#709]
Hello Rick,
in this closed issue "Distraction free mode doesn't hide enough #170" is described, how to hide different parts of the editor in distraction free mode. In version 1.24.12 of MM the tabs area is not disapearaing, if I define "DistractionFreeModeHideOptions": "toolbar,statusbar,menu,preview,maximized,tabs,maxwidth:650" in the configuration json or directly via Settings.

**Comment by RickStrahl** [comment]
Can't duplicate:

![image](https://user-images.githubusercontent.com/1374013/96517236-4adb7e80-1204-11eb-8d15-5d28ea307fa7.png)

**Comment by pit2511** [comment]
Thank you for the quick answer, Rick.
Then the problem lies elsewhere. I use the string in the configuration in exactly the way you described and the TABs are not hidden

**Comment by RickStrahl** [comment]
Let's not close this - let's try to figure out why this isn't working on your end. 

Usually when things are not working right it's some funky combination of modes that together end up causing somethings to cancel out. However, the tabs only get hidden by this flag.

I notice your window is very small or you're using very large fonts (in the other bug report) I wonder if that could have something todo with it, but I tried that too and while the experience sucks in a cramped window like that it does all work as far as I can tell.
