### ISSUE TITLE
"Copy as HTML" resets preview split

### ISSUE THREAD

**Issue by bleroy** [RickStrahl/MarkdownMonster#71]
Repro: Drag the preview separator to make the preview take more space, then click edit/copy markdown selection as HTML.

Expected: nothing happens besides the HTML going into the clipboard
Actual: the preview resets itself to the default size

**Comment by RickStrahl** [comment]
Fixed.

9c31033dd9af55774f87008896fe932016dae2fc

It'll be in post 1.0.21 releases

**Comment by bleroy** [comment]
That was fast :) Thanks!
