### ISSUE TITLE
Selecting tabs in the tabs area containing many tabs

### ISSUE THREAD

**Issue by pit2511** [RickStrahl/MarkdownMonster#710]
Hello Rick,
the attached picture is showing the issue I have on two independant Windows 10 computer with MM version 1.24.12
![issue](https://user-images.githubusercontent.com/45687370/96459377-5a69c000-1222-11eb-8228-cd038c5839dd.png)
Best regards
Peter

**Comment by RickStrahl** [comment]
Hmmm... can't duplicate that. Works for me he

![WindowList](https://user-images.githubusercontent.com/1374013/96516561-1c10d880-1203-11eb-8c87-f799eafd7dc2.gif)

re. Also - the window list is also on the Window menu (Alt-W).

**Comment by pit2511** [comment]
Thank you Rick.
No idea what the problem is then.

**Comment by RickStrahl** [comment]
What's your environment that you're running under? Virtual machine maybe or Remote access?

Also you can try perhaps turning off hardware accelleration - sometimes video card issues can cause problems.
