### ISSUE TITLE
Insert Link action uses %2520 for encoding a space...

### ISSUE THREAD

**Issue by mattslay** [RickStrahl/MarkdownMonster#711]
If I use the Insert Link action in the toolbar to link to another md file, if the filename has a space in it, Monster is encoding the space with "%2520"  instead of %20.

![image](https://user-images.githubusercontent.com/309016/96778027-afd3d780-13b0-11eb-8b2b-ba66f158f641.png)

**Comment by RickStrahl** [comment]
Fixed. Thank you.
