### ISSUE TITLE
Copy paste feature

### ISSUE THREAD

**Issue by VictorZakharov** [RickStrahl/MarkdownMonster#713]
When I copy files in explorer, it adds a copy with a "copy" suffix. When I do in MM, it says cannot copy with the same file name.
It should work the same as in explorer.

![image](https://user-images.githubusercontent.com/8978766/97085876-20b40300-15ee-11eb-9362-9f0506a0ef92.png)

**Comment by VictorZakharov** [comment]
Explorer behavior on CTRL+C/CTRL+V.

![image](https://user-images.githubusercontent.com/8978766/97085890-50630b00-15ee-11eb-9472-2b237aeaeae8.png)

**Comment by RickStrahl** [comment]
Fixed in the lastest preview release.
