### ISSUE TITLE
At the end of the front matter two accolades are added which breaks Jekyll blogs

### ISSUE THREAD

**Issue by LocalJoost** [RickStrahl/MarkdownMonster#714]
```code
---
layout: post
title: Generic MRKT2 Extension Service Inspector for MRKT 2.5
date: 2020-10-25T00:00:00.0000000+02:00
categories: []
tags:
- HoloLens2
- MRKT2
- Unity3d
- Windows Mixed Reality
featuredImageUrl: https://LocalJoost.github.io/assets/2020-10-25-Generic-MRKT2-Extension-Service-Inspector-for-MRKT-25/afterupgrade.png
{}
---
````

**Comment by RickStrahl** [comment]
Hmmm... that's strange. Looks like an accidental text injection in the code perhaps. 

When does this happen? When it copies the files into the Jekyll folders, or when you create a new post?

**Comment by LocalJoost** [comment]
The latter. When I Click Weblog/Post to weblog


Joost van Schaik


Senior Mixed Reality Software Architect

Windows Development MVP<https://mvp.microsoft.com/en-us/PublicProfile/4034925> & Windows Insider MVP<https://insider.windows.com/en-us/mvps/joost-van-schaik>



[cid:image001.png@01D663EB.DCAF7900]



LinkedIn<https://linkedin.com/in/joostvanschaik>  Blog<https://dotnetbyexample.blogspot.com>  Twitter<https://twitter.com/localjoost>



Sent from mail for Windows 10 on my over-the-top-specced HoloLens 2 development beast



"Where we go we don’t need… roads"

**Comment by RickStrahl** [comment]
So I can't duplicate this behavior.

Here's what I get (left MM entry, right output generated):

![image](https://user-images.githubusercontent.com/1374013/98511970-a4363c80-2209-11eb-98d1-cf1a37498584.png)

Can you post your original YAML Frontmatter header?

+++ Rick ---

**Comment by LocalJoost** [comment]
Of course. Here’s my more extensive repro:

Original front matter:
---
title: Model driven Mixed Reality apps using UniRx and MRKT extension service, part 1
weblogName: LocalJoost
postDate: 2020-11-02T19:27:41.4663084+01:00
---

On posting, I add these keywords:

HoloLens2,MRKT2,Unity3d,Windows Mixed Reality

[cid:image001.png@01D6B675.8E33B2F0]

Resulting front matter after clicking “Post to Weblog”:

---
layout: post
title: Model driven Mixed Reality apps using UniRx and MRKT extension service, part 1
date: 2020-11-02T00:00:00.0000000+01:00
categories: []
tags:
- HoloLens2
- MRKT2
- Unity3d
- Windows Mixed Reality
featuredImageUrl: https://LocalJoost.github.io/assets/2020-11-02-Model-driven-Mixed-Reality-apps-using-UniRx-and-MRKT-extension-service,-part-1/spagetti.png
{}
---

Mind you, this is the front matter of the resulting post in the _posts folder of the Jekyll site.

Does this help?

**Comment by RickStrahl** [comment]
Can you post the complete meta data that's in your original post after you post please..

**Comment by LocalJoost** [comment]
I assume you mean front matter. This is after the post, original file

---
title: Model driven Mixed Reality apps using UniRx and MRKT extension service, part 1
keywords: HoloLens2,MRKT2,Unity3d,Windows Mixed Reality
weblogName: LocalJoost
featuredImageUrl: https://LocalJoost.github.io/assets/2020-11-02-Model-driven-Mixed-Reality-apps-using-UniRx-and-MRKT-extension-service,-part-1/spagetti.png
postDate: 2020-11-02T19:27:41.4663084+01:00
---


Joost van Schaik


Senior Mixed Reality Software Architect

Windows Development MVP<https://mvp.microsoft.com/en-us/PublicProfile/4034925> & Windows Insider MVP<https://insider.windows.com/en-us/mvps/joost-van-schaik>



[cid:image001.png@01D663EB.DCAF7900]



LinkedIn<https://linkedin.com/in/joostvanschaik>  Blog<https://dotnetbyexample.blogspot.com>  Twitter<https://twitter.com/localjoost>



Sent from mail for Windows 10 on my over-the-top-specced HoloLens 2 development beast



"Where we go we don’t need… roads"

**Comment by RickStrahl** [comment]
No I mean what's in the original MM post. When you use the Post form it'll update the local post and add the meta info you entered into the form into the front matter of the **original** post (so it's there next time you post).

Where are those categories that you added?

**Comment by RickStrahl** [comment]
Ok I think I got it... no need to post anything else for now. I can see the `{}`. Checking now...

**Comment by RickStrahl** [comment]
Ok... so looks like this was a simple fix. The problem arises when there are no 'extra values' and to serialize and the YAML serializer apparently then creates `{}` as the 'empty' object rather than a blank field. Looks like this is fixed. Look for it in the next update.

**Comment by LocalJoost** [comment]
I assumed it to be something simple. For you, that is 😉

Joost van Schaik

Senior Mixed Reality Software Architect

Windows Development MVP<https://mvp.microsoft.com/en-us/PublicProfile/4034925> & Windows Insider MVP<https://insider.windows.com/en-us/mvps/joost-van-schaik>



[cid:image001.png@01D69962.534601F0]



LinkedIn<https://linkedin.com/in/joostvanschaik>  Blog<https://dotnetbyexample.blogspot.com>  Twitter<https://twitter.com/localjoost>



Sent from mail for Windows 10 on my Insider’s SP4



"Where we go we don’t need… roads"
