### ISSUE TITLE
command-line-features no effect

### ISSUE THREAD

**Issue by kkbruce** [RickStrahl/MarkdownMonster#718]
I can't test the effect of MM.exe

https://github.com/RickStrahl/MarkdownMonster#command-line-features

example

![image](https://user-images.githubusercontent.com/2024682/98560814-1f1f5600-22e3-11eb-9086-4788777d9bb6.png)

**Comment by RickStrahl** [comment]
I can't duplicate...

Can you make sure you're on the latest version - we did have an issue with an intermediate version a little while back where filenames/folders weren't properly forwarding, but that's been fixed since.

**Comment by kkbruce** [comment]
I from Chocolatey get MarkdownMonster v1.24.14 and from Help --> Check for New Version --> get 1.24.18.8.
I waiting for a new version from Chocolatey and test again.
