### ISSUE TITLE
Images + MM

### ISSUE THREAD

**Issue by weggetor** [RickStrahl/MarkdownMonster#72]
Hi Rick,
really like the integration with Snagit. But if you save all your md documents in one folder you end up with a mess of images in that folder. Would be better to automatically create a subdirectory with the name of the document and save the images in this directory instead of saving them all in the same root

**Comment by RickStrahl** [comment]
You can change the folder when you click **Finish** in SnagIt. Isn't that enough?

I added some additional logic to use the LastImageFolder **if** no document is open yet (ie. **Untitled**)
3c275738a6461bb52044baf1789227566a0a568b

**Comment by weggetor** [comment]
OMG - facepalm - please close this issue... quick !
