### ISSUE TITLE
When GetPost (MetaWeblog) doesn't serialize the wp_post_thumbnail correctly

### ISSUE THREAD

**Issue by shawnwildermuth** [RickStrahl/MarkdownMonster#722]
When I retrieve a post from Metaweblog, the wp_post_thumbnail isn't turned into a featuredImageUrl. Here is a GetPost result you can use to test:

```
<methodResponse>
  <params>
    <param>
      <value>
        <struct>
          <member>
            <name>dateCreated</name>
            <value>
              <dateTime.iso8601>20201114T15:03:22</dateTime.iso8601>
            </value>
          </member>
          <member>
            <name>description</name>
            <value>
              <string>&lt;p&gt;I hope you're watching the .NET Conf happening this week. If you have, you know that .NET 5 was finally released. This version isn't a long-term support (LTS) version, but that doesn't mean that many people will be using it in production...at least I will be.&lt;/p&gt;
&lt;p&gt;With this in mind, I decided to update three of my big Github projects to use .NET 5. Part of this process was upgrading the libraries I've created to .NET Standard 2.1. If you're relying on .NET Standard 2.0, the older versions are still there. Let's talk about each project:&lt;/p&gt;
&lt;h3 id="wildermindsmetaweblog"&gt;WilderMinds.MetaWeblog&lt;/h3&gt;
&lt;p&gt;I built this simple plugin for .NET Core to expose the MetaWeblog API that LiveWriter and Markdown Monster use to allow you to author blog posts. I'm using this in the WilderBlog project (below). There is a minor fix to allow Featured Image support, but otherwise it's identical to the older version. You can see the status of the project here:&lt;/p&gt;
&lt;blockquote&gt;
&lt;p&gt;MetaWeblog: &lt;a href="https://github.com/shawnwildermuth/MetaWeblog"&gt;&lt;img src="https://github.com/shawnwildermuth/metaweblog/workflows/BuildAndTest/badge.svg" alt="Build"&gt;&lt;/a&gt; &lt;a href="https://www.nuget.org/packages/WilderMinds.MetaWeblog"&gt;&lt;img src="https://img.shields.io/nuget/v/WilderMinds.MetaWeblog.svg" alt="NuGet"&gt;&lt;/a&gt;&lt;/p&gt;
&lt;/blockquote&gt;
&lt;h3 id="wildermindsrsssyndication"&gt;WilderMinds.RssSyndication&lt;/h3&gt;
&lt;p&gt;A lesser used project is the RssSyndication project. I wrote this because early versions of ASP.NET Core didn't have support for RSS Syndication. Not sure if this is supported yet, but I'm still using it so I should keep it up to date. No bug fixes in this version. Just an update to .NET Standard 2.1:&lt;/p&gt;
&lt;blockquote&gt;
&lt;p&gt;RSS Syndication: &lt;a href="https://github.com/shawnwildermuth/rsssyndication"&gt;&lt;img src="https://github.com/shawnwildermuth/RssSyndication/workflows/Build/badge.svg" alt="Build status"&gt;&lt;/a&gt; &lt;a href="https://www.nuget.org/packages/WilderMinds.RssSyndication"&gt;&lt;img src="https://img.shields.io/nuget/v/WilderMinds.RssSyndication.svg" alt="NuGet"&gt;&lt;/a&gt;&lt;/p&gt;
&lt;/blockquote&gt;
&lt;h3 id="wilderblog"&gt;WilderBlog&lt;/h3&gt;
&lt;p&gt;Lastly, my example project for ASP.NET Core is my actual blog (this site). It's not a general purpose blog engine, but my hope that it's a good example of building sites with ASP.NET Core. In updating this project from 3.1, I didn't have change any code. Just upgraded to .NET 5 and updated all the packages. The only real change was that the Azure Storage API wrappers I'm using were depreciated so I needed update to the new broken out packages. But that was a minor change.&lt;/p&gt;
&lt;blockquote&gt;
&lt;p&gt;WilderBlog: &lt;a href="https://github.com/shawnwildermuth/wilderblog"&gt;&lt;img src="https://github.com/shawnwildermuth/WilderBlog/workflows/WilderBlog-Build/badge.svg" alt="Build"&gt;&lt;/a&gt;&lt;/p&gt;
&lt;/blockquote&gt;
&lt;p&gt;Are you ready to upgrade to .NET 5? Or are you holding off for .NET 6?&lt;/p&gt;
</string>
            </value>
          </member>
          <member>
            <name>title</name>
            <value>
              <string>Updating My Projects to .NET 5</string>
            </value>
          </member>
          <member>
            <name>categories</name>
            <value>
              <array>
                <data>
                  <value>
                    <string>ASP.NET Core</string>
                  </value>
                  <value>
                    <string>.NET 5</string>
                  </value>
                  <value>
                    <string>.NET</string>
                  </value>
                  <value>
                    <string>C#</string>
                  </value>
                  <value>
                    <string>Open Source</string>
                  </value>
                </data>
              </array>
            </value>
          </member>
          <member>
            <name>wp_post_thumbnail</name>
            <value>
              <string>https://wilderminds.blob.core.windows.net/img/Updating-My-Projects-to-.NET-5%2Fmeasurewood.jpg</string>
            </value>
          </member>
          <member>
            <name>postid</name>
            <value>
              <i4>29</i4>
            </value>
          </member>
          <member>
            <name>userid</name>
            <value>
              <string>shawnwildermuth</string>
            </value>
          </member>
          <member>
            <name>wp_slug</name>
            <value>
              <string>2020/11/14/Updating-My-Projects-to-NET-5</string>
            </value>
          </member>
        </struct>
      </value>
    </param>
  </params>
</methodResponse>
```

**Comment by RickStrahl** [comment]
Isn't that the response you're showing? The response is what you're returning with the posted result...

**Comment by shawnwildermuth** [comment]
No, this is the response the server sends back to MarkdownMonster (note: the wp_post_thumbnail is included) but when it is turned into Markdown, the featuredImageUrl isn't included in the post metadata. Remember, this is using the "Download Post" feature of the addin, not creating a new post.

**Comment by RickStrahl** [comment]
Right - but what I'm saying is **you are generating this** on the server and sending it back. MM just requests the MetaWeblog entry by Id and then your code is creating the MetaWeblog Response and sending it back - what comes back from the server is up to you. MM doesn't control that? What am I missing here?

It looks to me your server app is getting hte wp_post_thumbnail, which means that MM's publishing is giving it to you in the format that your MetaWeblog implementation needs to read it (which is the 'standard' way). The `FeaturedImageUrl` is something that MM uses in its internal meta data stored with a post, but that's never actually sent to the server except in the full Markdown content which is optional and includes the original Markdown Front Matter header. But this Raw Markdown is an optional extra field that MM sends and it's not used by MetaWeblog unless you explicitly pull it out on the server (I do in my implementation so I can get the full original post text from any published post at any time).

So... `FeaturedImageUrl` doesn't really mean anything to the server and I'm pretty sure it doesn't get sent (i have to check). MM basically builds up a MetaWeblog request from the Meta data, but it's not using the meta data as is. 

If the wp_post_thumbnail is set that's what actually gets sent to the server for WP and MetaWeblog. FeaturedImageUrl is more of a helper to let you manually override the value without having to dig into the nested YAML syntax.

The way the featured image is determined is:

* Checks to see if wp_post_thumbnail is set
* If not checks FeaturedImageUrl and uses it if set
* If not scans the document and finds the first image (if the Don't Infer Featured Image isn't checked)

I may be totally misunderstanding your issue but it looks to me that MM is doing the right thing here. Maybe can you capture both the inbound and outbound data and then point at what you'd expect to see?

**Comment by shawnwildermuth** [comment]
So when you receive the document back from NewPost, do you take the wp_post_thumbnail and set the header for featuredImageUrl in the metadata?

**Comment by RickStrahl** [comment]
When using NewPost the process goes like this:

* Take your meta data and turn it into MetaWeblog publish format
* Publish with the actual publish format (per MWL spec RPC structures, plus some extra data in custom_fields (like mt_markdown)
* Result comes back - MM picks up postId, permalink and a URL if I recall

The image will be set as part of the publish process and should end up in the meta data either in `wp_post_thumbnail` or - if it pre-exists - in featuredImageUrl. I have to look at the code, but FeaturedImageUrl is just meant to be a simpler way to provide an explicit image, but it's not directly related to the MWL data that gets sent.

**Comment by RickStrahl** [comment]
Maybe we should back up here - what are you trying to accomplish exactly? A repeatable post? If `wp_post_thumbnail` is present it should just reuse that so that would be where it should be stored.

**Comment by shawnwildermuth** [comment]
I am hoping to get the featureImageUrl as metadata so I can change it when I read old blogposts. (Reading of blogposts via GetPost). Likely posts that I didn't originally write with MM

**Comment by RickStrahl** [comment]
Well if you didn't write them with MM then that data isn't there in GetPost() obviously. 

Are you talking about importing posts from the Weblog Posts Page? That's a completely different issue and handling for that is separate from new/edit post processing.

**Comment by RickStrahl** [comment]
So took a look at the code responsible for saving meta data and it looks like there had been some changes here recently that did change the previous behavior where the data was updated from the live post. The timing was changed and that has caused the featured imageUrl to not be updated in the meta data. I've fixed that, so after posting a new blog post here's what I get now:

![image](https://user-images.githubusercontent.com/1374013/99596254-0f1a0d00-299a-11eb-93e6-8b200df69c6f.png)

Note the permalink and featuredImageUrl are set in that data in the editor after the post. Previosuly this wasn't happening due to the invalid timing of the save operation before the post was made.

Note though that this would not have affected what gets sent to the server as the meta data would always be processed as before.

So - this should fix the first scenario (I thought) we talked about. The second scenario of retrieving posts from the server - that I don't think is handled and I'm not sure should even be handled as the featuredImageUrl will be updated when the post is reposted.

**Comment by shawnwildermuth** [comment]
Looks good. I'll grab the code and test.

**Comment by RickStrahl** [comment]
Preview release is on the site if you don't want to build.

**Comment by RickStrahl** [comment]
Is this what you were after - ie. when posting? Or when pulling down a blog post separately from the post listing (ie, non-MM generated posts).

**Comment by shawnwildermuth** [comment]
Both really.
