### ISSUE TITLE
Split Screen doesn't use current editor style/theme

### ISSUE THREAD

**Issue by bladewolf55** [RickStrahl/MarkdownMonster#725]
## Steps to Reproduce
1.  Open a file in MM
2.  Choose View > Split Screen > Beside

Expected: The new pane uses the same style/theme as the existing pane
Actual: The new pane seems to use a default dark theme.

To get the correct style to display:   
1.  Click inside the original pane
2.  Click outside the app so the MM window loses focus
3.  Click inside the new pane

![2020-11-16_11-32-14](https://user-images.githubusercontent.com/2903411/99293574-17d6db80-2800-11eb-86b2-5e12665c25de.gif)

## Environment
Version 1.25
Windows 10 Pro x64

## More Info
This problem has existed for as long as I've been using split screen (a very useful feature) and I'm finally reporting it.

**Comment by RickStrahl** [comment]
Fixed in eeed8d78...

Settings weren't being applied when the new split pane was created, so ended up using the default settings in `editor-setting.json`. Fixed.

**Comment by bladewolf55** [comment]
Thank you!

**Comment by bladewolf55** [comment]
Confirmed working in latest release. Thanks again.
