### ISSUE TITLE
Images & MM 2nd

### ISSUE THREAD

**Issue by weggetor** [RickStrahl/MarkdownMonster#73]
I often use MM to create static content for my website without using the automatic upload to the blog (this is used for my blog only), 
In this case I have to copy the html into clipboard, paste it into the editor, change the image path to the appropiate url where images live in my CMS, copy the images manually and paste the changed html to my CMS.

It would be great if you  introduce a variable in the metadata where I can put my destination path and when copying md to html it changes automatically the image path to the configured path in the metadata

**Comment by RickStrahl** [comment]
Sounds like a great idea for an add-in :-)

**Comment by weggetor** [comment]
When I upload the images first and include the right url its working fine. But if I work on a post I do not want to capture an image, upload it, insert the link, write more text, see that the image does not fit my needs, upload a new one etc. etc.

But you are right! I implemented it as an AddIn and its working like a charm - so no need to do it in the core!
