### ISSUE TITLE
WebView Chromium Addin Error: 'Couldn't find a compatible Webview2 Runtime installation to host WebViews.'

### ISSUE THREAD

**Issue by RickStrahl** [RickStrahl/MarkdownMonster#730]
When the WebVIew Browser is activated WebView Preview Runtime is not installed the application fails with an exception that the desired runtime was not found.

**Comment by RickStrahl** [comment]
For this to be fixed we need to:

* Check for the WebView2 Runtime to be installed
* Check and ensure the Runtime version is high enough
* If not installed or out of date link and run the WebView Runtime installer download
* Download and Install Link: https://developer.microsoft.com/en-us/microsoft-edge/webview2/

### Other Notes
In future versions of Windows the Runtime may ship with Windows 10, but for now the WebView Runtime has to be explicitly installed. It's also installed with the WebView2 NuGet packages and Canary installs so it may already be present.

**Comment by RickStrahl** [comment]
Ok so this has been fixed with check to see if the WebView2 runtime is installed. If it's not you will be prompted to download and install it optionally.

Current runtime has a number of issues so there may be some minor interop issues occasionally. These are fixed in the next release of the WebView2 runtime.

Eventually the WebView2 runtime will be available as part of the Edge browser install or Windows Update, but for the time being the runtimes have to be explicitly installed. Currently - since this is an addin and the runtime is not small, MM does not distribute this runtime, so that's why the manual download and install. If MM goes to using WebView2 for all rendering (ie. both editor and preview) then we'll have to rethink this strategy and either will have to distribute the runtime or force it as part of the Setup routine. 

For now the manual download should address this issue.

**Comment by javageek68** [comment]
@RickStrahl   I just downloaded webview2 via nuget package and got this error.   Does this mean I have to install something else?  How will this work on my user's machines?

**Comment by beef3000** [comment]
In case anyone else runs across this, make sure you install the webview2 runtime as the same user you're running your apps or dev environment as. I had this problem even though I had installed the runtime, but I reinstalled it as the same user I was launching VS as and it started working. I need to run VS under an administrator account. It would be nice if the runtime was installed for all users, or there was an option to do so.

**Comment by Benjamin-Shin** [comment]
I changed from Cromium to Webview2 because of the edge operating in evergreen mode. Is it right to install Webview2 runtime separately even though it is the latest version of Edge? (111.x)

**Comment by dliedke** [comment]
Even with Webview2 runtime extension correctly installed, it was not finding automatically in VSIX VS.NET extensions and I was facing the error message.

It only worked when retrieving the Webview2 runtime path from registry and then setting up with CoreWebView2Environment.CreateAsync() 

I will leave here a code sample to try helping other people because I had a hard time with this one.

```
public ToolWindowControl()
{
    InitializeComponent();

    InitializeAsync();
}

private async void InitializeAsync()
{
    string userDataPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "ToolExtension", "WebView2");

    if (!Directory.Exists(userDataPath))
    {
        Directory.CreateDirectory(userDataPath);
    }

    // Retrieve the webview 2 path
    string edgeWebView2Path = GetEdgeWebView2Path();

    // Set webview 2 path and user data path for the browser
    CoreWebView2Environment environment = await CoreWebView2Environment.CreateAsync(edgeWebView2Path, userDataPath);
    await webView.EnsureCoreWebView2Async(environment);

    webView.Source = new Uri("https://www.google.com");
}

public string GetEdgeWebView2Path()
{
    string keyPath = @"SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{2CD8A007-E189-409D-A2C8-9AF4EF3C72AA}";
    using (RegistryKey key = Registry.LocalMachine.OpenSubKey(keyPath))
    {
        if (key != null)
        {
            object pathObject = key.GetValue("pv");
            if (pathObject != null)
            {
                return pathObject.ToString();
            }
        }
    }
    return null;
}
```

**Comment by RickStrahl** [comment]
This addin works only with v1 of Markdown Monster. v2 uses the WebView natively, so no need for this. And if you for some reason use it anyway, it's likely going to fail.

If you want Chromium browser integration the latest version (v2+ actuallY) provide that. The addin is ancient and old and pre-dates the WebView release.
