### ISSUE TITLE
Save Project To

### ISSUE THREAD

**Issue by PeteHollyer** [RickStrahl/MarkdownMonster#732]
One of the Awesome aspects of MM, is your "Project".  This allows for multiple files in a single endeavor.  With Markdown I can link to Headers in same file, and link across files;  BUT I can only export (Print To) PDF/HTML of a single file.  
Why not the whole project?

Pete

**Comment by RickStrahl** [comment]
How would that even work? How could MM know what the order of documents is?
And how would all of that go together?

It's not as simple as you think it is :smile:  There's additional tooling required to configure the document structure - IOW a documentation solution. KavaDocs does something along those lines by using a managed TOC with the project layout. But even that currently doesn't produce a PDF. There are also size issues that are problematic with the tooling we use to produce PDF (wkHtml2Pdf) which flounders with large HTML documents.

**Comment by PeteHollyer** [comment]
Order would be Project Order, found in Project XML.

Think of HTML Export.  I have a project of 20 interrelated docs each with images etc...
We export project, all files are converted to individual html in the destination folder. Order here is Irrelevant
As for PDF
Basically, you would "concatenate" documents into one temporary file, in order found in Project Project XML.
Then PDF the temporary file.

**Comment by RickStrahl** [comment]
But there is no order in a project. The files are just files. For a PDF that would make no sense at all when see the TOC.

Projects are just container not organizers. For that you need a documentation solution like KavaDocs Addin or that knows something about the structure of the document.
