### ISSUE TITLE
Support to add favorite folders

### ISSUE THREAD

**Issue by marchamon** [RickStrahl/MarkdownMonster#733]
Most of the time, I'd like to save folders as favorites instead of files. I couldn't find a way to make it work through the UI and I have to update the JSON directly to create this kind of favorites.

I didn't find anything in the documentation about favorite folders, I presume it isn't a feature (yet). Do you plan to add something like this?

**Comment by RickStrahl** [comment]
You can add folders.

You should be able to do any of the following:

* Drag and drop from Explorer (looks like this is broken - bug)
* Find the folder in Folder Browser then Add to Favorites
* Manually add the folder by adding and specifying a path rather than a file

**Comment by RickStrahl** [comment]
The D&D issue has been fixed. 45dc93c1
