### ISSUE TITLE
[Feature Request] Go to previous text cursor position

### ISSUE THREAD

**Issue by IgorBuchelnikov** [RickStrahl/MarkdownMonster#738]
Save history of text cursor positions and allow to move over it.

**Comment by RickStrahl** [comment]
No idea how that would work.

**Comment by IgorBuchelnikov** [comment]
A new history entry is created when
1) mouse click on the document text
2) transition through the document outline

The current history entry changes when 
1) a keyboard button is pressed (arrow key, symbol key)
2) clipboard paste

The same feature exists in MS Visual Studio.

**Comment by RickStrahl** [comment]
Where is that feature in Visual Studio? Are you sure you're not thinking of the document navigation (alt-rigtharrow/leftarrow)?

Honestly I don't see how this is useful. What do you expect to happen when you go back? And what exactly is an 'entry'?

**Comment by IgorBuchelnikov** [comment]
MS VS feature is called "Navigate Forward And Backward"
https://www.visualstudiotips.co.uk/tip/navigate-forward-and-backward/
An entry is the text cursor position. On go back the current text cursor position changes and the document view is scrolled to it.

**Comment by RickStrahl** [comment]
Thanks for the link. Actually didn't know that VS would do same file navigation on those nav ops.
