### ISSUE TITLE
[bug] Incorrect display of the header with a link in the document outline

### ISSUE THREAD

**Issue by IgorBuchelnikov** [RickStrahl/MarkdownMonster#739]
For example header

`# [ObservableComputations](https://github.com/IgorBuchelnikov/ObservableComputations)`

is displayed as 

`Markdig.Syntax.Inlines.LinkInline`

The same issue is for headers with *italic*

**Comment by RickStrahl** [comment]
Thanks - I'll take a look. 

This sounds familiar and seems like something I previously fixed but perhaps that was for the embeddable TOC.
