### ISSUE TITLE
Ctrl+C (Copy) puts file into dirty state

### ISSUE THREAD

**Issue by JohnGoldsmith** [RickStrahl/MarkdownMonster#740]
Hello Rick,

As per #40 and #206 just selecting text and hitting Ctrl+C puts the file into a dirty state.

Steps to repro on my machine are:

* Open .md file
* Select some text
* Press Ctrl+C (note i's on the 'c' keystroke that the state changes)
* Observe file is in dirty state

Based on v1.25.12.2 32bit

Is that a new known issue?

Thanks

John

**Comment by RickStrahl** [comment]
I can't duplicate that.

![CopyOp](https://user-images.githubusercontent.com/1374013/103244356-d0646480-4900-11eb-9d64-44a38b787add.gif)

Note I'm selecting then Ctrl-C before moving to the new line to paste the text. 

The document is not marked as 'dirty' until I manually place the cursor and start typing or pasting.

**Comment by JohnGoldsmith** [comment]
Hi, Trying your steps I can confirm that, once saved by MM, the file is no longer marked as dirty when copying (Ctrl+C).  I notice that both the original and when saved identify as UTF-8 (no BOM) in the statusbar.

Looking at the two files in HexEdit I'm wondering if this is a line endings issue?  Diffing the two files shows the original (left) to be using CRLF and the copy, saved in MM, (right) to be just LF.

![CrLf](https://user-images.githubusercontent.com/2076297/103275498-3a8e0f80-49bc-11eb-890b-5bf101ca3615.png)

My git config has core.autocrlf set to true (both machine and user).

Does shine a light on the problem at all?

**Comment by JohnGoldsmith** [comment]
Ok, with a little more digging I seem to have solved my own problem.  I had _Linefeed Mode_ (Tools / Settings / Editor) set to 'Lf'.  Changing it to "Cr Lf" means I can now open the same original file, hit Ctrl+C and the file remains in an unchanged state.

So please go ahead and close this issue and thank you for responding so quickly.

Best regards

John

![MM_Linefeed_Settings](https://user-images.githubusercontent.com/2076297/103285832-0c69f900-49d7-11eb-8c98-7df67f1742d3.png)

**Comment by RickStrahl** [comment]
Oh yes I forgot about this. And yes that this the issue which is similar to the encoding issue. I should probably add a FAQ item for this into the documentation :smile:

So to clarify: If you have a file that has a different line feed format, and then you open it in MM, it will open the document and convert the LF settings to the specified format. So first time you type a character and MM checks for Dirty state, it detects the difference in the doc and that's when you see the dirty indicator.

I've been through a few iterations with this and as much as this seems a little confusing I don't know how else to manage this and maintain decent performance for the dirty check. Basically the dirty check just compares the original text vs. the current text and if not exactly equal flags the doc as dirty which technically is correct.

As you point out the best solution here is to match the LF mode to your original document, or whatever your preference is in the first place and this won't be a problem. FWIW, you can see the LF mode in the status bar too and you can set it from there.

![image](https://user-images.githubusercontent.com/1374013/103325215-df294500-49ee-11eb-97ea-e742ae58e64b.png)

**Comment by JohnGoldsmith** [comment]
Is there sense in making line endings a doc level setting, in addtion the global one do you think?

Anyway, I will be more careful of all line endings in the future :)

Thanks again for your help and great tool of course.

John
