### ISSUE TITLE
mmcli.exe doesn't generate packagedhtml without full path for input and output documents

### ISSUE THREAD

**Issue by jbratu** [RickStrahl/MarkdownMonster#746]
I noticed a bug while generating documents with mmcli.exe. the mmcli.exe -i and -o operate differently depending on whether full or relative paths are supplied.

For example, If I use this command the output HTML file will not be packaged and the images inside are not shown.
```
C:\TEMP>mmcli.exe markdowntohtml -i "test.md" -o "test.html" --theme "Dharkan" --rendermode packagedhtml
---------------------------------
Markdown Monster Console v1.25.15
---------------------------------
Command: markdowntohtml
Created file: test.html
 Output Mode: packagedhtml
```

If I change my command to include the full path to the input and output files then the packagedhtml file will get created correctly.
```
C:\TEMP>mmcli.exe markdowntohtml -i "C:\temp\test.md" -o "C:\temp\test.html" --theme "Dharkan" --rendermode packagedhtml
---------------------------------
Markdown Monster Console v1.25.15
---------------------------------
Command: markdowntohtml
Created file: C:\temp\test.html
 Output Mode: packagedhtml
```

The c:\temp\test.md document is:
```
Hello World!
![](assets/image.png)
How are you?
```

And the image c:\temp\assets\image.png file does exist at the path located.

I would expect that since my working directory was already c:\temp I should be able to use relative or absolute paths.

**Comment by RickStrahl** [comment]
Should be fixed in 1.26
