### ISSUE TITLE
Download page is failing with a "Server Error in '/' Aplication

### ISSUE THREAD

**Issue by fardad** [RickStrahl/MarkdownMonster#748]
![image](https://user-images.githubusercontent.com/518125/105701916-059cac00-5ed9-11eb-8661-1fe74a310dd6.png)

**Comment by RickStrahl** [comment]
Thanks... temporary error due to a corrupted version file that was uploaded. Fixed, as well as the code in the download page that retrieves the version file in case it can't be loaded.
