### ISSUE TITLE
mmcli.exe prompts for source material if html output file doesn't exist.

### ISSUE THREAD

**Issue by jbratu** [RickStrahl/MarkdownMonster#752]
Issue #746 was fixed but there is still a slight issue with the functionality. When using mmcli.exe to generate packagedhtml output from a markdown document I found that mmcli will display an 'Open' dialog and prompt for the location of the source markdown document even though it was specified in the command line. Oddly enough, if the output HTML file already exists then mmcli.exe does not prompt and everything works as expected.

For example, make sure c:\temp\test.html file does not exist. Use this command the output HTML file and mmcli.exe will prompt for the location of the test.md document.
```
C:\TEMP>mmcli.exe markdowntohtml -i "test.md" -o "test.html" --theme "Dharkan" --rendermode packagedhtml
---------------------------------
Markdown Monster Console v1.25.15
---------------------------------
Command: markdowntohtml
Created file: test.html
 Output Mode: packagedhtml
```

The c:\temp\test.md document is:
```
Hello World!
![](assets/image.png)
How are you?
```

And the image c:\temp\assets\image.png file does exist at the path located.

The output packagedhtml file is generated but because the open dialog appears and prompts for the file I can't run this from a script automatically.

Strangely enough, if test.html exists and you re-run the command to over-write it then mmcli.exe does not prompt for the source location of the markdown document.

**Comment by RickStrahl** [comment]
Thanks for catching this. I fixed the path fixups in the last set of fixes with the mmCli, but there was a naming bug assigning the filenames incorrectly and that was breaking the entire process. Should work now with partial and relative paths.
