### ISSUE TITLE
Pipe tables do not render correctly

### ISSUE THREAD

**Issue by MikeYeager** [RickStrahl/MarkdownMonster#756]
| Tag | Value to use | 
| :----- | :-------------- | 
| Owners | TryPhotino | 
| ProjectUrl | https://tryphotino.io | 
| Copyright | TryPhotino 2021 | 

Should preview as a table. Instead it previews like this in MDM:
| Tag | Value to use | | :----- | :-------------- | | Owners | TryPhotino | | ProjectUrl | https://tryphotino.io | | Copyright | TryPhotino 2021 |

**Comment by MikeYeager** [comment]
We did some more testing and found that the issue is that we had a <br> tag after the table. If there is not a blank line between the table and the <br> tag the table is not rendered correctly. Other viewers don't have this reaction to the <br> tag.

**Comment by RickStrahl** [comment]
What kind of tag?

If it's an HTML block tag  (like a `<div>` there needs to be a space before and after the tag) - that's in the markdown spec. Anything between tags is considered HTML unless it's separated out.

This is proper markdown:

![image](https://user-images.githubusercontent.com/1374013/109216694-f7041780-7758-11eb-8fcc-ebc0da120f6c.png)

while this is treated as content in an HTML tag:

![image](https://user-images.githubusercontent.com/1374013/109216623-db007600-7758-11eb-816a-27264723c4d1.png)

Note that the first one basically treats the block as a wrapper (which is what you want most likely) while the second treats the markdown as plain text. 

Also check out this behavior on BabelMark:

[Babelmark table wrapping](https://babelmark.github.io/?text=%3Cdiv+style%3D%22font-size%3A+2em%3B+margin%3A+1em%22%3E%0A%7C+Tag+%7C+Value+to+use+%7C+%0A%7C+%3A-----+%7C+%3A--------------+%7C+%0A%7C+Owners+%7C+TryPhotino+%7C+%0A%7C+ProjectUrl+%7C+https%3A%2F%2Ftryphotino.io+%7C+%0A%7C+Copyright+%7C+TryPhotino+2021+%7C%0A%3C%2Fdiv%3E%0A%0A)

Notice that all the common mark compliant parsers (like Markdig) use the interpretation I mention. The main exception here is PanDoc which is not Common Mark compliant.

**Comment by MikeYeager** [comment]
Thanks Rick. We noticed with more experimentation that other tools seem to consider a line break as white space. MDM considers 2 line breaks (no spaces) as white space. Neither actually seems to meet the spec, just an oddity I guess.
