### ISSUE TITLE
Show images when writing (enhancement)

### ISSUE THREAD

**Issue by ehguille** [RickStrahl/MarkdownMonster#758]
Hello,

It would be great to be able to have an inline preview of the images in the editor, so you don't need to have the preview windows open and, if needed, you can check the image at one sight so it's easier to write about it.

Regards.

**Comment by RickStrahl** [comment]
You can sort of do this by using the context menu and Edit Image Url which shows an image preview.

Not going to provide overlay images - too much of a pain to get positioned and sized in the right place and honestly just adds a bunch of noise to the editor.
