### ISSUE TITLE
Not seeing weblog configuration

### ISSUE THREAD

**Issue by devbhosale** [RickStrahl/MarkdownMonster#760]
Rick,
I am not able to see weblog configuration window anywhere. I am on 1.26.4.5

I already followed documentation on 
https://markdownmonster.west-wind.com/docs/_4rg0qzg1i.htm

**Comment by RickStrahl** [comment]
What are you not seeing exactly? The configuration 'page' is a tab on the Weblog publishing Window. You can open that from **Weblog -> Open Configuration** on the menu, or by opening the Web log form from the Weblog (RSS) icon on the toolbar then going to the **Web Logs** tab.

![image](https://user-images.githubusercontent.com/1374013/110907464-852be200-82b1-11eb-9c00-f683b7f000ae.png)

**Comment by devbhosale** [comment]
@RickStrahl  thanks for the response. I don't see the icon or the tab for "weblog" here is the screenshot.

also, clicking on file-> new weblog post does not open any window. 

can you please re-open the issue?

![image](https://user-images.githubusercontent.com/520223/110938140-6a815980-8301-11eb-99af-f87e7830461d.png)

**Comment by devbhosale** [comment]
@RickStrahl  see above.

**Comment by RickStrahl** [comment]
Hmmm... that sounds like the addin fails to load. Can you look in the error log and see if there's any additional information about the load failure? **Help -> Show Error Log**.

**Comment by devbhosale** [comment]
Rick, Thanks for the assistance. I deleted the weblogaddmin.json that did not help. However, the issue was that, it seems the program was hardcoded to look for 'Markdown Monster Weblog Posts' folder. But the folder was not already created and it did not exist. There might be some edge case bug around this.

3/13/2021 8:07:40 AM - Load Addin Classes failed for: weblogaddin.dll
Could not find file 'C:\Users\MyUSERNAME\Documents\Markdown Monster Weblog Posts'.
Markdown Monster v1.26.4.5
10.0.19041.1.amd64fre.vb_release.191206-1406 - en-US - NET 4.8 - 32 bit
en-US - en-US

**Comment by devbhosale** [comment]
Once I created the folder, I can see the Weblog menu item open again.

**Comment by RickStrahl** [comment]
Hmmm... I suspect you're using a portable install and you installed to a folder where your user doesn't have rights to create files or directories perhaps?

If you use the portable install make sure you install into a folder that has read/write access and can create folders.
