### ISSUE TITLE
Images : Paste as base64

### ISSUE THREAD

**Issue by globeinthesky** [RickStrahl/MarkdownMonster#761]
Hello, I can't paste as base64 like I used to do. When I click Embed Image nothing happens.
There is a “data:image/jpeg;base64…” in the Web URL or Local Image File, but the reference doesn’t go in the document like it used to do.
I have to copy the full content (of the the Web URL or Local Image File) and paste it myself and add the reference block ![][image_ref_123] [image_ref_123]: data:image/jpeg;base64…
Am I missing something?

I have version 1.26.4

**Comment by RickStrahl** [comment]
What are you doing to add the image as base64? Through the Paste Image dialog?

Looks like that's working for me:

![PasteAsBase64](https://user-images.githubusercontent.com/1374013/110908739-557dd980-82b3-11eb-9566-5cf0940da49b.gif)

**Comment by globeinthesky** [comment]
Hello, yes I am doing exactly the same thing and nothing happens after I click Embed Image.
The option save to disk works.
I have reinstalled Markdown with chocolatey and still doesn't work.
Since it works on your side it seems that something is wrong with my system. I will try different things.

**Comment by globeinthesky** [comment]
OK, well I uninstalled the program and
downloaded the version from your site https://markdownmonster.west-wind.com/download.aspx.
It works ok now. Weird...
