### ISSUE TITLE
Spell Checker / Word Formatting UI Use Cases?

### ISSUE THREAD

**Issue by davegi** [RickStrahl/MarkdownMonster#762]
While evaluating MM's spell checker, I could not find a way to invoke the spell-check context (right-click) menu via a keystroke (I expected `<SHIFT>-<F10>`) but instead:

- the "Close document..." context menu appeared w/o any spell checker related menu items
- after pressing `<ESC>` (multiple times) to release the "Close document..." context menu, the document:
  - no longer has focus
  - no longer displays the cursor
  - requires a mouse click to restore focus and I'm guessing in turn thee cursor

Is there a way to invoke the spell checker from the main context menu? If not, what's the suggested methods for:
- performing spell checking on the word under the cursor w/a keystroke (_i.e.,_ not w/the mouse, I don't want to take my hands off the keyboard)
- I noticed that `<F7> ` & `<SHIFT>-<F7>` are mapped to next/prev, but is it possible to spell check the selected word, or for that matter an entire document, w/wrap-around: again w/keyboard only

On a completely separate note, what's the _keyboard_ use case for making something say italic/bold? While typing, I typically know the next work I want to be in italic and so tend to hit `<CTRL>-i`, which of course inserts `**`, which means I often end up w/ `**word` - not really my intent😎.

Thanks,
djg

**Comment by RickStrahl** [comment]
Well it's a context menu so whatever your context menu key is on your keyboard (there's a dedicated windows key for that).

On my Dell XPS Laptop that key is `fn-Ctrl`. On my main keyboard that key is on the number pad by the scroll lock. Your keyboard may vary or have some other key combo for that.

**Comment by RickStrahl** [comment]
Hmmm...

The intention is that the selection is marked with `*italic*` on each side. But if there's no selection the behavior should be different.

I don't think creating the open bracket only would be appropriate, but rather add `**` and then move the cursor into the empty italic block.  In fact that's how GitHub does it here - give it a try.
