### ISSUE TITLE
How to make a minimalistic theme?

### ISSUE THREAD

**Issue by it19862** [RickStrahl/MarkdownMonster#765]
How to make a minimalistic theme? 
For example, in the style `stackoverflow.com`.

**MarkdownMonster**
I opened the document `SampleMarkdown.md` in MarkdownMonster.
The result: I have huge fonts, huge line spacing, like for the blind...

**Another program**
I opened the file `SampleMarkdown.md` in another program.
Result: everything looks fine.

**MarkdownMonster**
![2021-03-20_22-40-58](https://user-images.githubusercontent.com/18245828/111883726-2f042080-89ce-11eb-930b-0e229aabc44b.png)

**Another program**
![2021-03-20_22-40-59](https://user-images.githubusercontent.com/18245828/111883767-670b6380-89ce-11eb-9d15-da857d77bc85.png)

**Comment by RickStrahl** [comment]
Maybe pick a different theme? Blackout is a pretty blocky theme. Try GitHub or Dharkan (bottom right corner drop down).

* [Themes in Markdown Monster](https://markdownmonster.west-wind.com/docs/_4rg0mw5c2.htm)
* [Switching and Customizing Themes](https://markdownmonster.west-wind.com/docs/_4nn17bfic.htm)

The second link describes how you can create your own themes by copying an existing theme or creating one from scratch.
