### ISSUE TITLE
How are folders sorted? 

### ISSUE THREAD

**Issue by it19862** [RickStrahl/MarkdownMonster#766]
How are folders sorted? 
How do I change the sorting principle?

![2021-03-20_23-07-34](https://user-images.githubusercontent.com/18245828/111884214-35e06280-89d1-11eb-8e40-0b2fa15f7d25.png)

**Comment by RickStrahl** [comment]
Folder list is alpha sorted, unless you drag and drop in which case the file or folder goes whereever it's dropped.
