### ISSUE TITLE
Save as Styled HTML

### ISSUE THREAD

**Issue by daughtkom** [RickStrahl/MarkdownMonster#77]
It would be great to be able to save the HTML as it is seen in the preview window, including the theme.  

Maybe options to:
* Save just the converted markdown as HTML (current functionality)
* Save styled HTML as multiple files (HTML and CSS separately)
  * great for if I have multiple pages of documentation in separate files, no need to repeat CSS in each
* Save styled HTML as single file (merge CSS into the HTML file for a single file)
  * suitable for handing to someone, or embedding as a Help file into another application, etc

**Comment by RickStrahl** [comment]
yes it would be nice, but it's actually not quite an easy task and something that most browsers already provide very well.

You can do this today by:

* View -> View in Web Browser
* From there Save As

In Chrome and Firefox this will save into a folder structure that contains all the dependencies so it can render the same. 

I'm going to look into this - I suppose it's not **that** difficult to parse the entire document and move all images/styles etc. but it seems like adding features that browsers already provide with more options.

**Comment by daughtkom** [comment]
To be honest if I had realized that View in Web Browser was there I wouldn't have suggested.  I was looking in the File menu and didn't think to look in View.  

I still think it could be useful, but I imagine that my need was already met and didn't know it.

**Comment by RickStrahl** [comment]
Yeah I was thinking earlier that it might be a good idea to have a link in the File menu as well. Adding a menu option there.
