### ISSUE TITLE
Switch position between codes and preview

### ISSUE THREAD

**Issue by liugaocn** [RickStrahl/MarkdownMonster#770]
I don't know if there is already a view setting for this.
Most of the time, I am viewing markdowns and switching from one file to another or from one header to another. So I think it is best for me to preview it on the left and modify on the right because I want the preview window close to the File and Folder Browser.

**Comment by liugaocn** [comment]
I guess it is designed to write markdowns, but sometimes we read markdowns more than write. 
It is not easy for me to locate my code when I spot something wrong in preview window. So I hope there is a quick button which takes me to where my code is. 
Besides, It is better if the code window can scroll automatically  when I scroll the preview window. Like magnetic.

**Comment by RickStrahl** [comment]
So we now have this functionality:

![EditorPreviewDisplay](https://user-images.githubusercontent.com/1374013/119274175-7c199400-bbc3-11eb-88f3-dd0f89810131.gif)
