### ISSUE TITLE
span tag without syntax highlight

### ISSUE THREAD

**Issue by liugaocn** [RickStrahl/MarkdownMonster#772]
There is no highlight for span tag. 

I use span tags to format texts, but there is no syntax highlight.

**Comment by RickStrahl** [comment]
I assume you closed this because it's actually working?

![image](https://user-images.githubusercontent.com/1374013/113356162-8f079a80-92dd-11eb-9eb9-2b57fe0650c0.png)

Any hint why you think it wasn't? Setting? Wrong edit mode? Not having HTML tag mode enabled?

**Comment by liugaocn** [comment]
Usually it works fine. But it doesn't in unordered lists. 

![image](https://user-images.githubusercontent.com/50794111/113430520-e6f0ef00-940c-11eb-844a-29dda86df498.png)
