### ISSUE TITLE
[Feature Request] Keyboard controls to tab back over to Document Outline

### ISSUE THREAD

**Issue by nonplayer** [RickStrahl/MarkdownMonster#777]
The latest update adds some useful keyboard navigation tools to the document outline:

> When navigating by keyboard, ENTER and SPACE selects, and TAB moves the focus into the editor.

It would be fantastic if there was a way to TAB _back_ to the Outline, say CTRL-Tab or such.

**Comment by RickStrahl** [comment]
Can't really do that as Tab and Ctrl-Tab in the editor already has key assignments. Tab - obviously to tab in text, and Ctrl-Tab uses Windows standard document navigation.

You can use the keyboard short cut which is `alt-v-o` and that gets you back to the doc outline selection.

**Comment by nonplayer** [comment]
On my installation, Alt-v-o does not give you keyboard control of the Outline. In fact, I'm not really finding any times in which you would have direct keybaord control of the Outline outside of deliberately clicking into it.

**Comment by nonplayer** [comment]
Correction: Alt-v-o does not give you Control of the Outline unless it was previously hidden. If you are in a doc and the outline is already open, alt-v-o does nothing.

**Comment by RickStrahl** [comment]
Thanks... Yeah you're right. The selection of the list is tricky. Just put in a fix that should handle this.

Please check in 1.26.10.2+ when it's released.
