### ISSUE TITLE
Print the preview

### ISSUE THREAD

**Issue by daughtkom** [RickStrahl/MarkdownMonster#78]
Allow an option to print the preview pane.  I assume this would use IE's default print dialog.  I don't have much use for paper copies usually, but this is an easy way to allow me to "Print as PDF", which I often need, and presumably easier than actually writing code to generate the PDF.

**Comment by RickStrahl** [comment]
I have to see what you actually get from the WB print dialog. 

FWIW, as I mentioned in the previous request: You can use **View -> View in Web Browser** to get the view into the browser and you can then print and save from there. 

This is why I kind of reluctant to bring this into the MM as you get more options in the actual browser. I don't think you can actually get to PDF printing directly from the WB.

**Comment by RickStrahl** [comment]
Looks like you can press Ctrl-P in the Preview to get to the Print dialog. From there you can print to a PDF printer (Microsoft PDF is installed by Windows (or perhaps Office?).

**Comment by RickStrahl** [comment]
Ok I've added print support on the menu via Ctrl-P.

3e8600c2d797ed5b80deb954774002ea5c769cc9

Note you can use Internet Explorer -> File -> Page Setup to configure print options like removing the headers and footers or customize them.

**Comment by RickStrahl** [comment]
Available now in 1.0.23 (site only at the moment - not chocolatey)
