### ISSUE TITLE
Cryptic error message -- MM can't find something that it needs ... but what??

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#780]
This greets me after upgrading from version 1.26.5.0 to 1.26.11.2. Can you please help me decipher it?

![image](https://user-images.githubusercontent.com/42981101/114585148-310d7800-9c38-11eb-9fba-f15ba3175253.png)

**Comment by RickStrahl** [comment]
Are you compiling from source and running a Debug build?

That looks like a debug path that's hard coded for my local development for the preview.

**Comment by RickStrahl** [comment]
Never mind. Just checked and I screwed up. I didn't use the `DEBUG` flag around my local code. Missed it cause of course it works on all my local machines that are finding that path.

Updated the package. 1.26.11.3

**Comment by bcmadsen** [comment]
Thank you for fixing that so promptly ... but now I have a new problem.

https://markdownmonster.west-wind.com/download

wants me to download

https://west-wind.com/files/MarkdownMonsterSetup.exe 

and when I do that and view its file properties, that file still is version 11.2, not 11.3.

**Comment by bcmadsen** [comment]
Oh, I see now that I can get the Latest Pre-Release, which is https://west-wind.com/files/MarkdownMonsterSetup_Latest.exe, and that has the right version number.

**Comment by bcmadsen** [comment]
Perfect. Thank you again. It's working great now!

**Comment by RickStrahl** [comment]
Version number on the home and download pages sometimes cache, so after uploads may not show for a few minutes.
