### ISSUE TITLE
TOC Generator exception

### ISSUE THREAD

**Issue by st7for** [RickStrahl/MarkdownMonster#781]
Dear Sir
This message refers to Markdown Monster ver. 1.26.12 running on Windows 10 10.0.17763.107.
An exception is always thrown when I try to insert a table of content (see attached screenshot). 
How can I fix it ?
Please, feel free to ask any information I can provide.
Best regards.

![1618498442](https://user-images.githubusercontent.com/82597973/114892812-64553000-9e0d-11eb-854a-e27af13cd503.jpg)

**Comment by st7for** [comment]
Auto Number causes troubles, also. Here the error log:

```
15/04/2021 19:59:54 - AppDispatcher: L'inizializzatore di tipo di 'MarkdownMonster.AddIns.BaseAddinConfiguration`1' ha generato un'eccezione.
Impossibile trovare il metodo 'Void MarkdownMonster.AddIns.BaseAddinConfiguration`1.set_ConfigurationFilename(System.String)'.
Markdown Monster v1.26.12.0
10.0.17763.1.x86fre.rs5_release.180914-1434 - it-IT - NET 4.7.2 - 32 bit
it-IT - it-IT    
---
AutoNumberAddin
   in AutoNumberAddin.AutoNumberAddinConfiguration..ctor()          
---------------------------
```

**Comment by RickStrahl** [comment]
The TOC Generator is a third party addin. Please post your Issue with the owner of that repository.

https://github.com/DVaughan/MarkdownMonster-Addin-TocGenerator
