### ISSUE TITLE
Open File and Folder Browser is disabled on the welcome screen

### ISSUE THREAD

**Issue by twwilliams** [RickStrahl/MarkdownMonster#782]
The icons to open the folder browser don't show up, either, and the keyboard shortcut described in the documentation at https://markdownmonster.west-wind.com/docs/_4wu1cjyka.htm doesn't work, either.

I thought that might have been disabled in the free version, so I purchased a license but that doesn't change anything.

![image](https://user-images.githubusercontent.com/1378042/115580266-2b411380-a284-11eb-8c31-cb22436fc5e5.png)

Is there a setting I'm missing?

**Comment by twwilliams** [comment]
I figured out that if I checked the Visible box in the graphical settings (the link on the welcome screen went to the JSON version of settings) and then typed in a path in the left nav window, I could get it to show up.

The icons described in the documentation still don't show up, nor is the link on the welcome screen active, but I do know how to make it work now.

**Comment by RickStrahl** [comment]
This is a bug, but you can use `ctrl-shift-b` to show the folder browser. 

I think what happened here is that the menu options were all created as a group and the same filter for open document checking was applied - but shouldn't. I'll take a look.

**Comment by RickStrahl** [comment]
Fixed for next update.
