### ISSUE TITLE
Adjust the location displayed in Preview to match the Editor display?

### ISSUE THREAD

**Issue by dainsburg** [RickStrahl/MarkdownMonster#784]
It seems the top line shown in the Preview pane matches wherever the cursor is in the Editor. This is disconcerting as you can click anywhere in the Editor screen and the Preview will scroll the content to put that point at the top. So the two displays never show the same section of the document being edited.
It would be better if the top line of the Preview showed the top line visible in the Editor, as that way both panes would show the same content starting from the top. If there's a slight disparity at the bottom because the markdown is adding space in the Preview, that's fine because we always know where the top is and can scroll down a little if needed.

Thanks!

**Comment by RickStrahl** [comment]
Sorry not going to happen.

Precise placement of the preview is very difficult for a number of reasons and the current state is as close I can get it to provide semi-consistent linked view. There are a ton of factors involved and I've tweaked this endlessly and the current state is the best compromise I've been able to come up with.
