### ISSUE TITLE
How Do I Make This Use a Light Theme

### ISSUE THREAD

**Issue by RealDotNetDave** [RickStrahl/MarkdownMonster#786]
I went to the options and chose a light theme, but nothing happens when I do. It seems there is more to change like Editor Theme, but I don't know what values I can use to get it to work. It defaults to vscodedark but what are the other values?

My feeling is that if I chose a light theme, MDM should do the rest.

**Comment by RickStrahl** [comment]
What theme did you change? 

There are three themes that can be changed:

* Application Theme  (set in window header and restart)
* Editor Theme  (set on status bar bottom right)
* Preview Theme (set on status bar bottom right)

If you change the Application theme the editor and preview themes are defaulted to appropriate themes. You can then change the Editor and Preview themes individually using the drop downs in the bottom right status bar.
