### ISSUE TITLE
Clicking On The Preview Window Does Not Hightlight Editor

### ISSUE THREAD

**Issue by RealDotNetDave** [RickStrahl/MarkdownMonster#787]
It would be really helpful if I click on the preview window, it would move the cursor in the editor window to the same location. Currently, it's difficult to sync it up.

**Comment by RickStrahl** [comment]
Make sure your preview sync is set to Editor and Preview:

![image](https://user-images.githubusercontent.com/1374013/115972817-6cd3f780-a4ec-11eb-9bd3-af7e8d9c85ac.png)

Clicking won't do it - and shouldn't have to because it should be in sync with the editor, but scrolling will.
