### ISSUE TITLE
PreviewWebRootPath is not recognized

### ISSUE THREAD

**Issue by dyardy** [RickStrahl/MarkdownMonster#788]
I am trying to setup PreviewWebRootPath in my mdproj file as follows....(below)

It is loaded, and active however when viewing an md file with an image ... as follows

*my markup file looks like...

```
---  
title: Update to Blog 
createdAt: 2021-04-24
updatedAt: 2021-04-24
author:  
  name: Admin  
tags:  
  - general
---  

new blog
![](/articles/images/174-1747591_seinfeld-scripts-kramer-avatar-michael-richards-kramer.png)

```

*my mdproj file looks like...

```
{
  "ActiveFolder": "D:\\_Projects\\GitHub\\GitHub\\abc\\def.com\\Site\\content\\articles",
  "ActiveSidebarIndex": 0,
  "OpenDocuments": [
    {
      "Filename": "D:\\_Projects\\GitHub\\GitHub\\abc\\def.com\\Site\\content\\articles\\new-blog-engine-static.md",
      "IsActive": true,
      "LastEditorLineNumber": 14,
      "LastImageFolder": null
    }
  ],
  "PreviewWebRootPath": "D:\\_Projects\\GitHub\\GitHub\\abc\\def.com\\Site\\static"
}

```

**Then using shift f12 and view source the path is still**

```

<p>Yes I am updating blog and web site as part of personal brand update.3</p>
--
  | <p><img src="D:/_Projects/GitHub/GitHub/abc/def.com/articles/images/174-1747591_seinfeld-scripts-kramer-avatar-michael-richards-kramer.png" alt="" /></p>
  |  
  | <!-- End Markdown Monster Content -->

```

I was needing and expecting the path to be 
D:/_Projects/GitHub/GitHub/abc/def.com/Site/static/articles/images\174-1747591_seinfeld-scripts-kramer-avatar-michael-richards-kramer.png

It doesn't appear that is recognized at all.  Any ideas? (in fact if i type anything in the path it is not recognized at all)
"PreviewWebRootPath": "D:\\_P**ddd**rojects\\GitHub\\GitHub\\abc\\def.com\\Site\\static" (it appears that the mdproj acts more like a marker file than anything).  If i remove the mdproj  the path looks just like what is in the md file like /articles/images/... (if i put the mdproj file back in place the path changes to what was shown D:/_Projects/GitHub/GitHub/abc/def.com/articles/images/174-1747591_seinfel....)  

I am using version 1.26.12.4 of Markdown Monster

**Note**..if i add the following direct to my markdown file it works as desired (however I really do not want to add this to every md file)
previewWebRootPath: D:\\_Projects\\GitHub\\GitHub\\abc\\def.com\\Site\\static

**Comment by RickStrahl** [comment]
That should work. I haven't looked at this in a long while so I had to actually try it out which is a bit tricky, but from what I see it works.


![image](https://user-images.githubusercontent.com/1374013/115974888-c5f75780-a4fb-11eb-8b93-83a7a17d2197.png)

Note too that order is important:

https://markdownmonster.west-wind.com/docs/_5fz0ozkln.htm#site-relative-path-overrides

but the project `WebRootPreviewPath` in an MD proj file has pretty high priority.

I'd recommend you put the `.mdproj` file into the project's Web root folder. it doesn't have to but that will be the most reliable place. Note too that first an open project, then a project on disk is used. If you have multiple `.mdproj` files at different subfolder levels you may run into trouble with the wrong one getting hit first.

**Comment by RickStrahl** [comment]
Playing around with this some more I'm now seeing some inconsistent behavior.

Looks like there's a bug with the Chromium preview not updating the preview path.  Can you confirm that you're using the Chromium Preview rather than the default IE preview? (The blue Chromium icon in the Toolbar)

Found the issue: 

The preview path is set when a preview is requested and the  Chromium WebView handler apparently didn't set this on every refresh. It eventually updates it through other mean, but not initially. 

Fixed for next update.

**Comment by dyardy** [comment]
I am using Chrome preview.
Do you know when the next update is?

**Comment by RickStrahl** [comment]
It's up now on the download page (1.26.14.1)

**Comment by RickStrahl** [comment]
Please also note that if the `.mdproj` file is in what amounts to the PreviewWebRootPath, then you don't have to set the value in the `.mdproj` file. It's only required if the path is different otherwise MM will use the .mdproj file as the project root.

**Comment by dyardy** [comment]
I appreciate your help.

Something still seems odd.

My root path is (I put the following mm.mdproj in this directory)
D:\_Projects\GitHub\GitHub\abc\def.com\Site

My markdown files are in this path
D:\_Projects\GitHub\GitHub\abc\def.com\Site\content\articles

Here is my mm.mdproj
```
{
  "ActiveFolder": "D:\\_Projects\\GitHub\\GitHub\\abc\\def.com\\Site",
  "ActiveSidebarIndex": 0,
  "OpenDocuments": [
    {
      "Filename": "D:\\_Projects\\GitHub\\GitHub\\abc\\def.com\\Site\\mm.mdproj",
      "IsActive": true,
      "LastEditorLineNumber": 11,
      "LastImageFolder": null
    },
    {
      "Filename": "D:\\_Projects\\GitHub\\GitHub\\abc\\def.com\\Site\\content\\articles\\new-blog-engine-static.md",
      "IsActive": false,
      "LastEditorLineNumber": 14,
      "LastImageFolder": null
    }
  ],
  "PreviewWebRootPath": "D:\\_Projects\\GitHub\\GitHub\\abc\\def.com\\Site\\static\\"
}
```

within my markdown i am referencing the image via 
`![](/articles/images/174-1747591_seinfeld-scripts-kramer-avatar-michael-richards-kramer.png)`

I cannot see the image in the preview.  If I preview and look at the source.the path to the image is

`<p><img src="D:/_Projects/GitHub/GitHub/abc/def.com/Site/articles/images/174-1747591_seinfeld-scripts-kramer-avatar-michael-richards-kramer.png" alt="" /></p>`

You can see here that it is missing/ignoring the PreviewWebRootPath variable which says that path includes the word 'static'  Something still is not right here.  

In your last comment, you mentioned that I could put the mdproj in the static directory..which i did try then it displays the image correctly in the preview.  By doing this the path to the image is relative to the location of the mdproj file (and so far the PreviewWebRootPath is ignored)

**Comment by dyardy** [comment]
With respect to the preview icon in the toolbar..it looks like this.
![tEfgPg1iJ8](https://user-images.githubusercontent.com/261526/115978634-c1a85a00-a54e-11eb-8ce0-6e85da603360.png)

When i mouse over i see 
![8cjk4wa1FF](https://user-images.githubusercontent.com/261526/115978659-0633f580-a54f-11eb-89f9-511b49637ccd.png)

clicking on it..takes me to install webview runtime, i follow the instructions installing the evergreen bootstrapper but monster doesnt recognize the product is installed? 

![0awpMvDJK1](https://user-images.githubusercontent.com/261526/115978669-177d0200-a54f-11eb-863b-3b06f3c89cc8.png)

**Comment by RickStrahl** [comment]
Hmmm... I can't duplicate your scenario. When I have the .mdproj file in the root and the paths set up differently it uses the path in the `PreviewWebRootPath` for me. I can't get it to not use it.

Note that if the path is invalid or doesn't exist it'll fall back to the next folder/file match, so perhaps the path is not right or escaped incorrectly in the JSON file? Make sure the path is good. The next fallback would be the location of the `.mdproj` file in the root folder which seems is what you're seeing.


As to the WebView runtime - I've seen this on occasion. Usually, shutting down MM and starting back up makes it then work. 

Also Edge Canary builds will override the runtime explicitly installed, so if an older Edge Canary build is installed it can through things off.

**Comment by RickStrahl** [comment]
Can you set up a simple repro folder structure and zip it up? I'm just not able to duplicate this...

**Comment by dyardy** [comment]
Hello, yes I have created a repo with my setup.  You can find here [https://github.com/dyardy/markdownmonstersample](https://github.com/dyardy/markdownmonstersample)

You can find similar screenshot in the c:\web\images directory as well.

![screenshot](https://user-images.githubusercontent.com/261526/116239505-bad93d00-a730-11eb-8f48-88ad67511c1b.png)

**Comment by RickStrahl** [comment]
Ok, so took a look and sure enough it wasn't working. Not quite sure why my example was working but your's wasn't. The problem was that the code was in fact not checking inside of the document for the `PreviewWebRootPath`. Added that code and now it works:

![image](https://user-images.githubusercontent.com/1374013/116498967-b3a45300-a846-11eb-88cb-90b04917d23b.png)

Also found another related bug - if there's a space in the folder specified it wouldn't render, so there's some additional escaping that's now provided.

**Comment by dyardy** [comment]
I downloaded version 1.27.1

1) if i double click on mm.mdproj , it loads in MarkdownMonster however the parameter "PreviewWebRootPath": "c:\\Web\\SubFolder1" is removed

2) because of #1, i loaded MarkdownMonster from shortcut, then loaded project mm.mdproj and I still do not see the kramer image

mm.mdproj looks like

```
{
  "ActiveFolder": "C:\\Web\\",
  "ActiveSidebarIndex": 0,
  "OpenDocuments": [
    {
      "Filename": "C:\\Web\\mm.mdproj",
      "IsActive": true,
      "LastEditorLineNumber": 11,
      "LastImageFolder": null
    },
    {
      "Filename": "C:\\Web\\SubFolder1\\SubFolder2\\test.md",
      "IsActive": false,
      "LastEditorLineNumber": 18,
      "LastImageFolder": null
    }
  ],
  "PreviewWebRootPath": "c:\\Web\\SubFolder1"
}
```


I tried removing spaces from kramer image so it was kramer.png and still no luck

with the above settings i would assume that number2.jpg would not be displayed and kramer.png would be displayed as the previewpath was c:\web\subfolder1

```
---  
title: Update to Blog 
createdAt: 2021-04-24
updatedAt: 2021-04-24
author:  
  name: Admin  
tags:  
  - general
---  

this image lives in the images directory
![](/images/number2.jpg)

this image lives in subfoler1/images

![](/images/kramer.png)


```

**Comment by RickStrahl** [comment]
Yes there seems to be a problem opening the .mdproj file in Markdown Monster. But let's leave that aside - that's a separate issue. Open the file externally, or use `Open in Editor` to edit. If you have a project open and manually edit the file, then your open project will override the saved setting when the project is closed. That's another separate issue/bug.

To set the value and have it take:

* Close the project
* Change the value in the `.mdproj` file
* Save

Reopen the project.

Now, the project does not need to be open to respect the `PreviewWebRootPath` - MM will find the file and open it looking for the key (in .1.27.1).

So - all that in place assuming the key is in the file it should work. See my screen shot above - it's respecting the preview path from the .mdproj file and showing the Kramer pic.

Now there's still an oddity here where sometimes the image does not display in the IE previewer. In the Chrome previewer it works, but not in the IE one. It looks like IE is not allowing for the OS path, while Chrome is. You can see this with the Chrome preivewer (which should now work without the reinstall prompt - another issue there that was fixed) or by using Show in Web Browser (Shift-F12).

**Comment by RickStrahl** [comment]
So the issue you're seeing is stupid (from my end): The `PreviewWebRootPath` was marked not to serialize so in your open project the value was a) not getting written back out to disk, and b) even if you had it not getting written back in. Instead it defaults to the project path.

So fixed that and now it works with the project open - or not open. Check it in 1.27.2. I think this should address both the rendering of the image from the right place as well as the disappearing value in the project file.

**Comment by dyardy** [comment]
Great! (I was able to download and things worked out great) - Thank you!
