### ISSUE TITLE
The "Register your copy" link on the "About" dialog is incorrect

### ISSUE THREAD

**Issue by hugodahl** [RickStrahl/MarkdownMonster#789]
When opening the "About" dialog (Help -> About), clicking the "Register your copy" link goes to a different URL than the one followed in "Help -> Software Registration -> Buy Registration Key".

The one in the "About" dialog goes to "https://markdownmonster.west-wind.com/purchase.aspx", which might have been meant as "https://markdownmonster.west-wind.com/purchase" since that's where the "Buy" button on the main Markdown Monster site links to. However, the "Software Registration" link from the application goes to "https://store.west-wind.com/product/order/markdown_monster".

**Comment by RickStrahl** [comment]
Thanks for checking... The Markdown Monster WebSite has been redesigned recently so all the URLs have changed. This results in broken links for older versions of MM.

The latest version should have these links updated and also be more consistent. Try downloading 1.26.12.1+.
