### ISSUE TITLE
Once a new update is installed MM does not honor the editor-preview sync selection

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#79]
Upon installing a new update MM does not honor the previously made editor-preview sync selection even though it retains the correct selection.

To make the functionality work one needs to re-apply the choice.

**Comment by RickStrahl** [comment]
This is probably unrelated to the version update unless you're updating from an older version that used the old logical value.

Please take another look when you run into it again and perhaps look at what the actual markdownmonster.json file contains (before you exit so the value isn't overwritten with whatever the UI sets).

**Comment by RickStrahl** [comment]
Is this on your Win7 machine? If so this is related to the #64 and should be fixed. Please check again with post 1.0.23.0.

**Comment by RickStrahl** [comment]
Closing this - you can reopen if this is still an issue.
