### ISSUE TITLE
Searching for "Preview Sync Mode" doesn't find Preview Sync Mode

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#790]
In the MM Settings window, searching for "preview" or "sync" or "mode" finds Preview Sync Mode, but "preview sync", "sync mode", "preview mode", and "preview sync mode" all fail to do so. (Incidentally, "preview mode" finds neither "Preview Sync Mode" nor "Preview Mode".)

![image](https://user-images.githubusercontent.com/42981101/116288558-7d7faa00-a746-11eb-8c88-0dd2e1473741.png)

Meanwhile:

![image](https://user-images.githubusercontent.com/42981101/116288717-a43de080-a746-11eb-9165-fa2b3ae504e7.png)

... although this works:

![image](https://user-images.githubusercontent.com/42981101/116288783-b6b81a00-a746-11eb-924d-b59d8110e9b3.png)

This is a bit of a surprise, since some other searches for multiple keywords work just fine:

![image](https://user-images.githubusercontent.com/42981101/116288889-cfc0cb00-a746-11eb-994f-79e3e665a69f.png)

![image](https://user-images.githubusercontent.com/42981101/116289372-48c02280-a747-11eb-93fa-080215427656.png)

Incidentally, while we're on the subject, this is what I find in the documentation for PreviewSyncMode (without spaces, which makes it difficult to search for "Preview Sync Mode", by the way):

![image](https://user-images.githubusercontent.com/42981101/116289896-c126e380-a747-11eb-88bc-11bc03067e75.png)

This documentation should include the NavigationOnly setting, and it seems to me that it would be helpful to include a sentence or two about what they do -- at least how NavigationOnly is different from the others. I found that in the Change Log in the list of changes for version 1.21, but having it in this documentation too would be extra helpful.

**Comment by RickStrahl** [comment]
Not that surprising actually - the search routine checks for simple text matches of what you typed in either the property name (ie. PreviewSyncMode) or the help text. In this case the help text doesn't include Preview Sync Mode so no match.

I've clarified the help text (which wasn't very good in the first place) to include Preview Sync Mode so that will trigger next time. 

Perhaps it's a good idea to also do a search on `FromCamelCase()` if no match is otherwise found.

**Comment by RickStrahl** [comment]
So added support for also searching the de-camelized property name. So should now work with any property names even if it doesn't show up in the Help Text.

Thanks. Good catch!
