### ISSUE TITLE
Check for new version indicates a new version. Download page has error

### ISSUE THREAD

**Issue by mberkien** [RickStrahl/MarkdownMonster#791]
Hi,
When I select the option "Check for new version" the window that appears indicates that versin 1.26.14.1 is available.

![afbeelding](https://user-images.githubusercontent.com/40051471/116361393-399dab00-a801-11eb-8e6e-4bb25e3534f6.png)

After clicking Yes (Ja in Dutch) an windows opens, stating that there is some error in XML:

![afbeelding](https://user-images.githubusercontent.com/40051471/116361609-71a4ee00-a801-11eb-9a86-2e1c1a7d67f3.png)

**Comment by RickStrahl** [comment]
Yes - we've changed the Web site so links are broken.

Fixed in the new version but you have to update this version manually.

**Comment by mberkien** [comment]
Ah, thank you for the answer. I was able to download and install directly from your site.

Bye for now!
