### ISSUE TITLE
Support img html tag with height/width/style support

### ISSUE THREAD

**Issue by dyardy** [RickStrahl/MarkdownMonster#792]
Is it possible to resize the image via markdown?

I am using MM with static blogging site.  This gives me the result that I am looking for when I deploy however..notice the attributes width or style?

`<img src="/articles/images/174-1747591_seinfeld-scripts-kramer-avatar-michael-richards-kramer.png" alt="kramer" width="200" style="padding:20px;"/>`

If I use this format MM doesn't not support the path and I get [x] in the preview.

**Can we leverage the project parameter PreviewWebRootPath to also be supported within <img tag?**

**or does MM recognize something like** ![](/articles/images/kramer.png){:style="float: right;margin-right: 7px;margin-top: 7px;"}

![FcrwB7MCOh](https://user-images.githubusercontent.com/261526/116793755-a54c7600-aa96-11eb-81b7-bf76ff771017.png)

**Comment by RickStrahl** [comment]
Markdown natively doesn't support that, but you can use raw HTML to do this. There's also a Markdown extension that you can turn on in MM (courtesy of Markdig) for additional attributes, but... you have to make sure that's supported by the Markdown implementation that ends up rendering the Markdown on your site or Site Generator.

The MM Setting is `Generic Attributes` in Settings to enable this:

![image](https://user-images.githubusercontent.com/1374013/116799899-1b051180-aa98-11eb-81b5-ba7614771891.png)

You can use CSS style syntax for id and classes:

```markdown
### Seinfeld Follies{#Follies .header1}
```

But again - make sure your site generator or markdown parser on the live site supports these as these are not standard Markdown tags.

**Comment by RickStrahl** [comment]
I've added a topic to the docs for this:

https://markdownmonster.west-wind.com/docs/_61g0yzn1y.htm
