### ISSUE TITLE
MERMAID does not render in internal preview and Add-In Manager does not work

### ISSUE THREAD

**Issue by patrickblattner** [RickStrahl/MarkdownMonster#796]
Hi Rick,

I bought your great Markdown editor because it can do a lot more in most areas than the ones I've been using. But there is one thing that doesn't work, which I really need. It is about MERMAID.js. Unfortunately I can't motivate the editor to render MERMAID diagrams in the preview window. All options are configured or enabled as described in the documentation, but unfortunately without any effect. See attached config. When I view the diagram via View > External Preview, everything works as desired, but not with the internal preview.

In addition, the Add-in Manager does not work. The LogFile is attached. It doesn't matter if I open the editor as admin, use the installed or portable variant, it doesn't work in any way.

Best regards,
Patrick

[MarkdownMonsterErrors.txt](https://github.com/RickStrahl/MarkdownMonster/files/6471909/MarkdownMonsterErrors.txt)

[MarkdownMonster.zip](https://github.com/RickStrahl/MarkdownMonster/files/6471963/MarkdownMonster.zip)

**Comment by RickStrahl** [comment]
Mermaid charts should work, assuming you've enabled them and script rendering. Make sure you use the Chromium addin, or else you need to use external rendering.

![image](https://user-images.githubusercontent.com/1374013/118213631-2efb2c80-b423-11eb-8040-05b54572c2b8.png)

I tried this today and noticed that I had to restart for the change of settings to work, but after that everything worked as expected. I think this has to do with the script page injection in the initially rendered document.

Updated docs with current instructions (updated for Chromium previewer which is newer than what was in the old docs):

[Rendering Mermaid Diagrams In Markdown Monster](https://markdownmonster.west-wind.com/docs/_5ef0x96or.htm)

**Comment by RickStrahl** [comment]
I'm going to close this issue and create a new one for the Addin-Manager. Please use separate issues in the future to make it easier to track issues.

Thank you for your help. Aloha.
