### ISSUE TITLE
The table editor should handle long text better

### ISSUE THREAD

**Issue by timunie** [RickStrahl/MarkdownMonster#799]
Hi @RickStrahl 

## What is the problem
I recently added long text into the table editor and did not find a good way to navigate inside the long text. For an example please see the image below. 

![image](https://user-images.githubusercontent.com/47110241/118397038-7c111580-b652-11eb-9951-ddb04e806670.png)

*The blue highlighted text is wrapped but not fully visible*

## What ideas do I have to solve this
It would be nice if there is a way to have either:
- The Row height should resize if the text wraps
- Ability to adjust row height by  mouse dragging 
- or add a ScrollViewer to the TextBox

## Any additional ideas?
Maybe using the build in WPF-`DataGrid` would be an alternative. I see the following benefits
- Supports Column and Row resizing out of the box
- Support sorting out of the box
- Supports adding rows by empty placeholder
- Supports deleting rows by DEL-Key
- Supports Colum rearrangement

I can try to make a proposal if you want me to.

I think this would also solve #312 and #392

Happy coding
Tim

**Comment by RickStrahl** [comment]
Hi Tim - that's not going to happen.

I used the DataGrid in the original version of MM's table editor and it was terrible. Stock DataGrids in any Microsoft products are just shit - they have funky UI behavior, are insanely difficult to customize behavior and still they behave like crap when it comes to selections etc.. Yes there are features that would be nice to have but don't justify the pain to me.   Just say no to DataGrids from Microsoft :-).

The second version that I used was using a custom list control - that worked great for UI functionality (exactly what I wanted for behavior) but it started failing with large tables (as some people are doing tables with thousands of rows - go figure). Tried to optimize that but wasn't able to make that performant. It was also difficult to maintain.

So I'm into the HTML route now, which gives me full control plus a sensible model to customize as well as good performance even for large sets. The new table editor is still under some level of construction so your bug report is welcom, but at the moment I'm holding off for the next overhaul until I get through the Chromium conversion for the editor and other support forms (like the Table Editor) as that will make working with the HTML based code significantly easier.

**Comment by RickStrahl** [comment]
As to the rowheight issue in the grid - that's a bug. It happens to be related to Internet Explorer's event handling in the control - doesn't happen in Chromium which is why I'm at the moment holding off with modifications since the goal is to switch over all controls to use Chromium soon.

There are a number of weird issues like this with IE control (up arrow navigation on the top field for example will jump focus out of the control). All small issue, but annoying.  I'll take another look at see if I can get the resizing to work properly - probably fixable with a CSS tweak.

Thanks.

**Comment by timunie** [comment]
Hi Rick,

thank you for the detailed and fast feedback. Don't stress you to solve this issue soon as I can really live with the way it is now. 

But if I find something that also may be a thing for other users I open a ticket, because I think the more user feedback you get the better MM will be. :-). 

Really looking forward to the new Chromium Version 😄

**Comment by RickStrahl** [comment]
Hey I really appreciate you taking the time and the feedback is very valuable! I'm aware of some of the issues and I prioritize, but when issues come in it pushes them up on my todo list so it's good. 

I know the Table Editor needs some more love, but just haven't had the time to do more cleanup work with it and as I said some issues are unfortunately IE only so I'm hoping some will just clear up when switching to the Chromium version.

Again thanks Tim.

ps.
In the future it might be worthwhile to wait for my feedback before a PR to save you some time. As you know by now, I often have very strong opinions of what I want to implement :smile:

**Comment by RickStrahl** [comment]
Take a look at 1.27.6.1 (pre-release) which includes better support for 'auto-grow' behavior in the editor.

**Comment by timunie** [comment]
Hi Rick, 

> Take a look at 1.27.6.1 (pre-release) which includes better support for 'auto-grow' behavior in the editor.

I just installed the latest pre-release and what should I say? It is *exactly* the behavior I wanted to have. 👍 Should I keep the ticket open or can I close it? 

Happy coding
Tim

**Comment by timunie** [comment]
**Off-Topic**

Ok I owe you one more answer: 

> In the future it might be worthwhile to wait for my feedback before a PR to save you some time. As you know by now, I often have very strong opinions of what I want to implement 😄

I know this already. But sometimes I want to be sure that my idea even works, so I try to implement a draft before I say something very stupid. For example I wanted to propose a treeview-like TOC until I noticed that it updates just too frequently. So I need to check if it works for me first, before I open a ticket. 😉
