### ISSUE TITLE
[Feature request]: Create hyperlink from Document Outline

### ISSUE THREAD

**Issue by timunie** [RickStrahl/MarkdownMonster#801]
Hi Rick, 

I like the way one can make links from one section to a different section by using the header ID. I also know that the dialog already uses the Clipboard-Content to suggest a Link. From a users point of view I have two more ideas / suggestions. 

## Idea 1: Adding a ContextMenuItem to the TOC:
- Adding a new Item `Insert link at curor position` which opens the Link-Editor
  ![image](https://user-images.githubusercontent.com/47110241/118450903-fbefbc00-b6f4-11eb-9d04-9eeb176f0c9a.png)
  
  ![image](https://user-images.githubusercontent.com/47110241/118451240-5426be00-b6f5-11eb-9b15-0a33b166d1c8.png)

- Prevent selection of the TOC-Item on right click as the user might not want to navigate on right click. For me I also don't want to navigate if I copy the header ID, because I most often want to paste it at the position where I was writing.

## Idea 2: Add a Drop-Down to the Link-Editor: 
Alternatively the Link-Editor could offer a drop-down where the Needed link can be selected from. For example:
- change the `TextBox` to be a `ComboBox` 
- or add a `DropDownButton` next to the Control (see https://mahapps.com/docs/controls/dropdownbutton )
![image](https://user-images.githubusercontent.com/47110241/118453758-e0d27b80-b6f7-11eb-8dba-1a49a7ae5245.png)

This was my last idea for now, I will not spam more ideas for the next time ;-) 

Happy coding
Tim

**Comment by RickStrahl** [comment]
I like both of these ideas.

The first context menu item should probably be:

* Insert Link for Selection

**Comment by timunie** [comment]
The Text is up to you 🤣

**Comment by RickStrahl** [comment]
Take a look at 1.27.6.2 and later...

![image](https://user-images.githubusercontent.com/1374013/118745525-36e41380-b80b-11eb-832a-8d762d2b9392.png)

**Comment by RickStrahl** [comment]
And here's part 2 in the Link dialog:

![image](https://user-images.githubusercontent.com/1374013/118748726-174fe980-b811-11eb-8b58-45f27704cb24.png)

**Comment by timunie** [comment]
Hi @RickStrahl 

This looks really great 👍 . I love the `#`-Symbol as icon as it is directly related to how headers are defined. Much better than my ▼. 

If you don't mind let me say what I would change / wish:
At the moment the context menu is grayed out if no text is selected. I think some folks could think this may confuse one, So my idea is that instead either one of these actions are performed if no text selected: 

- Open the LinkEditor pre-filled with the Header-Text as `Link Text:` and the Header-ID as the `Link:`
- or at the Caret-Position  insert a Link which looks like `[The Header Text](#TheReferenceId)`


Happy coding 
Tim

**Comment by RickStrahl** [comment]
Done.

If there no selected text the dialog is pre-filled with the Header text. 1.27.7.1+

**Comment by timunie** [comment]
Ok I'll test it as soon as it is available as a prerelease. At the moment the latest I found is 1.27.6 on the internet page.
