### ISSUE TITLE
Question on buying license for using in commercial app

### ISSUE THREAD

**Issue by assopri** [RickStrahl/MarkdownMonster#805]
Hi! If I buy license from here https://markdownmonster.west-wind.com/purchase#License for 49$, will I be able to use MarkdownMonster in my commercial app without any extra fees?

Another question - can I somehow make it work in Winforms app?

**Comment by RickStrahl** [comment]
I’m not sure what you mean, but my initial reaction is no you can’t. Markdown Monster is not a redistributable product but is licensed per user. Each user using it requires a separate license (or one of the multi-user or company wide licenses.

+++ Rick ---
