### ISSUE TITLE
Download link is broken

### ISSUE THREAD

**Issue by tndata** [RickStrahl/MarkdownMonster#806]
The download link that is opened after you do a "Check for new version" is broken. It tries to open this page that returns a 404. (Version 1.25.16.3)

https://markdownmonster.west-wind.com/download.aspx

**Comment by RickStrahl** [comment]
Sigh - yes the Web Site was updated a while back and old links have been broken.

I've added redirects (should have done this a while ago) so it should work now with the old URLs too.
