### ISSUE TITLE
MetaWeblog Addin: Post download not formatted correctly

### ISSUE THREAD

**Issue by Heleboel** [RickStrahl/MarkdownMonster#807]
This weekend I've implemented the MetaWeblog API in my website, and when I was testing it I saw that when I download a blogpost, the Markdown formatting is screwed up. It seems that the first couple of newlines/empty lines are removed, resulting in a blogpost that is not readable anymore. By the way, I store my blogpost as markdown, not as HTML, so there is no need to convert it from HTML back to markdown.

I added 3 screenshots: the first one shows the MetaWeblog API response for the Post download. The newlines and empty lines are there. The second screenshot shows how it looks like in Markdown Monster for the first couple of lines, and the third one shows that at some point the formatting is correct.
![XmlRpcResponse](https://user-images.githubusercontent.com/43875295/120979259-b6636380-c775-11eb-99e3-c90db10f93a0.png)
![Markdown Monster 1](https://user-images.githubusercontent.com/43875295/120979311-c54a1600-c775-11eb-8daa-34a9cc4f2ebd.png)
![Markdown Monster 2](https://user-images.githubusercontent.com/43875295/120979312-c5e2ac80-c775-11eb-99d6-1133a37e427c.png)

**Comment by RickStrahl** [comment]
Blog body content in the meta web log data is supposed to be in HTML format, so that's what the assumption is with the incoming data.

If you want to post markdown back to the client you can modify your MetaWeblog output to add an `mt_markdown` custom field. MM will pick that up and use that in lieu of the main html body of the post. Likewise MM will post `mt_markdown` to the blog in addition to the formatted HTML in the body.

[Custom Markdown Format includes Markdown](https://markdownmonster.west-wind.com/docs/_4nb0sg47p.htm)

**Comment by Heleboel** [comment]
Thanks for your answer Rick. I am already doing that, returning the markdown in the custom_field `mt_markdown`. But for some reason it is not picked up by Markdown Monster. I reviewed my code and the response sent to Markdown Monster, and at first sight I had the wrong casing in the response (`Key` instead of `key` and `Value` instead of `value`), but fixing this did not give the expected result.

In the screenshot you see how the response is formatted (the string value is collapsed). Maybe you can tell me what's wrong with it?
![XmlRpcResponse with custom_fields](https://user-images.githubusercontent.com/43875295/121134908-3ea83e00-c834-11eb-9d74-9cce984e6db2.png)

**Comment by RickStrahl** [comment]
Your `mt_markdown` value is missing the `</string>` tag.

**Comment by Heleboel** [comment]
Rick, the `</string>` closing tag is there, but it is not shown because Notepad++ collapsed it.

But I did another test with a really short blogpost, so the opening and closing tags are visible. But unfortunately, still no luck. Is there some way that I can debug this myself? Because I do not want to bother you too much.

Below is the complete `methodResponse` xml. There is not much content in it (description is empty for example), but the XML structure should be correct, right?

```
<methodResponse>
  <params>
    <param>
      <value>
        <struct>
          <member>
            <name>dateCreated</name>
            <value>
              <dateTime.iso8601>00010101T00:00:00</dateTime.iso8601>
            </value>
          </member>
          <member>
            <name>description</name>
            <value>
              <string></string>
            </value>
          </member>
          <member>
            <name>title</name>
            <value>
              <string>Angular: a Custom Form Control with validation</string>
            </value>
          </member>
          <member>
            <name>categories</name>
            <value>
              <array>
                <data />
              </array>
            </value>
          </member>
          <member>
            <name>permalink</name>
            <value>
              <string>angular-a-custom-form-control-with-validation</string>
            </value>
          </member>
          <member>
            <name>postid</name>
            <value>
              <i4>23</i4>
            </value>
          </member>
          <member>
            <name>wp_slug</name>
            <value>
              <string>angular-a-custom-form-control-with-validation</string>
            </value>
          </member>
          <member>
            <name>link</name>
            <value>
              <string>angular-a-custom-form-control-with-validation</string>
            </value>
          </member>
          <member>
            <name>custom_fields</name>
            <value>
              <array>
                <data>
                  <value>
                    <struct>
                      <member>
                        <name>key</name>
                        <value>
                          <string>mt_markdown</string>
                        </value>
                      </member>
                      <member>
                        <name>value</name>
                        <value>
                          <string>blogpost.Contents</string>
                        </value>
                      </member>
                    </struct>
                  </value>
                </data>
              </array>
            </value>
          </member>
        </struct>
      </value>
    </param>
  </params>
</methodResponse>
```

**Comment by Heleboel** [comment]
I added the `id` in the collection and now it is working. Thanks for pointing out, Rick. This issue can be closed now.
