### ISSUE TITLE
Is WinGet-oriented upgrade available?

### ISSUE THREAD

**Issue by BurstX** [RickStrahl/MarkdownMonster#808]
Hi there!
WinGet is released now, but wingetting MDmonster has some issues:

![image](https://user-images.githubusercontent.com/3790231/122670521-2e487980-d1cb-11eb-89a1-7ddfb3cc89df.png)

Is upgrading MDmonster via WinGet is supposed to work already or not?

Previous relevant issue -- #708

**Comment by RickStrahl** [comment]
Don't know - I don't maintain the Win-Get install nor how it runs. 

Just tried installing latest which is 1.28 and it works. Didn't try updating though.
