### ISSUE TITLE
[Feature Request] League\CommonMark block-level Attributes implementation 

### ISSUE THREAD

**Issue by Flowman** [RickStrahl/MarkdownMonster#809]
Can we copy the implementation of block-level Attributes.

https://commonmark.thephpleague.com/2.0/extensions/attributes/
https://kramdown.gettalong.org/syntax.html#attribute-list-definitions -> Block Inline Attribute Lists

You can assign any attribute to a block-level element. Just directly prepend or follow the block with a block inline attribute list. That consists of a left curly brace, optionally followed by a colon, the attribute definitions and a right curly brace:
```
> A nice blockquote
{: title="Blockquote title"}
```
This results in the following output:
```
<blockquote title="Blockquote title">
<p>A nice blockquote</p>
</blockquote>
```
```
Test line
{: .test}
```
This results in the following output:
```
<p class="test">Test line</p>
```

**Comment by RickStrahl** [comment]
I think this Is this what you're looking for? Extra Attributes:

[Custom Attributes on Markdown Tags](https://markdownmonster.west-wind.com/docs/_61g0yzn1y.htm#generic-attributes-extension)

Provided as part of the Markdown Parser we use.

[](https://github.com/xoofx/markdig/blob/master/src/Markdig.Tests/Specs/GenericAttributesSpecs.md)

Keep in mind that while MM can render this, it requires that if you host Markdown that is parsed on a server somewhere that the server supports it!

+++ Rick ---

**Comment by Flowman** [comment]
Yeah I know about the inline one. But looking for block level implementation.
