### ISSUE TITLE
Every MM upgrade keeps adding entry C:\Program Files\Markdown Monster to System PATH

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#81]
Rick,
this is potentiality a huge issue as it may cripple OS:
Looks like every MM upgrade appends a new `C:\Program Files\Markdown Monster` to the System PATH env. variable!
Now I had issues starting programs.

**Comment by RickStrahl** [comment]
Ugh - nice catch Arthur. Looking into it.

**Comment by ArthurZ** [comment]
No luck yet? 
Ahh, it is of the unwillingly "nice" ones, just install a new update and you will see C:/progarm files/Markdown Monster or something prepended to an already existing entry for MM in the %PATH%.
Will cripple user systems eventually. 
When you upgrade need to check if the entry already exists and correct.
Not sure what you use as an installer, some slick ones have this functionality built in.

**Comment by RickStrahl** [comment]
I use Inno and it doesn't have a native solution for that but can be handled with some script. I've already updated the installer so this won't be a problem for the next releases.

Now fixing the path...

**Comment by RickStrahl** [comment]
I'm going to also ship a Powershell script for a bit that will allow fixing the path:

9a226380a0ab3b941ee80973e61dc2ae682be8ef

**Comment by ArthurZ** [comment]
Yeah, it stopped adding the same thing. But question is if I need to run the Posh script to clean an older installation? Or it does it on its own?

**Comment by RickStrahl** [comment]
No not at the moment. I can't figure out how to get the POSH script to fire reliably from Inno. For now you have to manually run it.
