### ISSUE TITLE
New Install: Security warning for md files and preview

### ISSUE THREAD

**Issue by theschnarr** [RickStrahl/MarkdownMonster#811]
![Screen Shot 2021-06-29 at 1 48 10 PM](https://user-images.githubusercontent.com/28270373/123865406-bec83d80-d8e0-11eb-95a4-69161703b5ae.png)

I installed Markdown Monster, via the setup exe, on my Windows 10 VM (a setup which has worked previously), but I'm unable to make any edits to markdown files.  All .md files opened display as blank tabs with a security warning at the top (See screenshot).  I've tried selecting "allow blocked content..." but nothing changes in the tab contents.  The preview window shows how the markdown renders, but I can't edit the .md file itself.

**Comment by RickStrahl** [comment]
Not sure. I think this has to do with Internet Explorer Security settings. that may not allow local file editing.  Are you running on a network share? If you do I think that changes the security zone and that could be responsible for this behavior.

You can try running the latest preview of Markdown Monster 2.0 which doesn't use the old IE based control, but uses a Chromium renderer. It's a preview though and there are  a few rough edges still.

**Comment by RickStrahl** [comment]
I'm going to close this since we're now very close to release of v2 which doesn't use the IE control any longer and does not have this issue.
