### ISSUE TITLE
[Chocolatey] EXEs are being shimmed that shouldn't be

### ISSUE THREAD

**Issue by bc3tech** [RickStrahl/MarkdownMonster#812]
When installing the `.portable` version via Chocolatey, shims are created for multiple EXEs that shouldn't have shims:

~~~
Extracting C:\ProgramData\chocolatey\lib\MarkdownMonster.Portable\tools\\MarkdownMonsterPortable.zip to C:\ProgramData\chocolatey\lib\MarkdownMonster.Portable\tools...
C:\ProgramData\chocolatey\lib\MarkdownMonster.Portable\tools
 ShimGen has successfully created a shim for mm.exe
 ShimGen has successfully created a shim for mmcli.exe
 ShimGen has successfully created a shim for pingo.exe
 ShimGen has successfully created a shim for wkhtmltopdf.exe
 ShimGen has successfully created a shim for csi.exe
 ShimGen has successfully created a shim for vbc.exe
 The upgrade of markdownmonster.portable was successful.
  Software installed to 'C:\ProgramData\chocolatey\lib\MarkdownMonster.Portable\tools'
~~~

Ideally we'd only shim `mm` and, maybe, `mmcli` when installing via chocolatey.

There's detail on how to do this [here](https://docs.chocolatey.org/en-us/create/create-packages#how-do-i-exclude-executables-from-getting-shims).

**Comment by RickStrahl** [comment]
I don't want any files shimmed because MM adds itself to the user path.

People install from other sources than Chocolatey, so the shims are not a reliable way to get access to the short exes.

**Comment by RickStrahl** [comment]
Maybe the better way to handle this is to move all the third party EXEs into a secondary folder and launch them from there. That way only MM's native files are accessible via the path (mm.exe, MarkdownMonster.exe, mmCli.exe)
