### ISSUE TITLE
Pandoc addin not installing properly

### ISSUE THREAD

**Issue by paulmassey** [RickStrahl/MarkdownMonster#814]
I've installed the pandoc add-in but I have a couple of problems...

Firstly, it is listed as a random number rather than as Pandoc:
![Screenshot 2021-07-06 180819](https://user-images.githubusercontent.com/1185646/124640344-2fdd9700-de85-11eb-9ce2-16c256b97a38.jpg)

Secondly, I can't find the configuration form and runner anywhere. Is there supposed to be an extra button or menu option somewhere?

**Comment by RickStrahl** [comment]
Ugh... it's a version problem as I'm in the middle of the 2.0 conversion. The Addins currently have been upgraded to v2, so the new ones at the old locations don't work with v1 any more.

I'm going to have to add new branches so the old versions can be found and used. Updating and that should work but it'll take a bit.

The other option you use now: You can install the 2.0 preview which works with the new versions of addins.

**Comment by RickStrahl** [comment]
You can now download 1.28.4 that fixes the addin-loading issues.

Not sure what would cause the weird name you have unless that's a custom plug-in perhaps (looks like a generated name). IAC give the new version (or the v2 Preview) a try.

**Comment by paulmassey** [comment]
Thanks, that's fixed it.
