### ISSUE TITLE
Can't Update for Access Denied to FontAwesome.ttf 

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#82]
I was able to upgrade MM many times until today:
---------------------------
Error
---------------------------
C:\windows\Fonts\FontAwesome.ttf
An error occurred while trying to replace the existing file:
DeleteFile failed; code 5.
Access is denied.
Click Retry to try again, Ignore to skip this file (not recommended), or Abort to cancel installation.
---------------------------
Abort   Retry   Ignore   
---------------------------

Aborting the installation wipes Markdown Monster out.
Update 2: reran the installer with option `Ignore` and it brought it back.

**Comment by RickStrahl** [comment]
You can ignore the message and go on - the installation will complete fine since the font is already installed. The font is registered already. Previously the fonts weren't installing properly, although I'm not sure why the font is getting locked.

**Comment by RickStrahl** [comment]
Changed install behavior to only install if it doesn't exist.
