### ISSUE TITLE
The 2.0.021 update does not recognize my copy of MM as registered

### ISSUE THREAD

**Issue by djfm501** [RickStrahl/MarkdownMonster#821]
I just updated my MM copy to 2.0.0.21 and now when I start MM it says I am using the evaluation version 122 times.  The "Registered.key" file exists and is located in "...\AppData\Local\Markdown Monster" with a timestamp of 2020-12-06 which was the date I  purchased MM.

I tried using Help->Register but it didn't like the value of the registration key found in the confirmation email you sent me.  I think I am missing something here

My order confirmation # is 93428736

**Comment by RickStrahl** [comment]
Version 2.0 is a major version upgrade so the old registration key won't work. Version 2 requires a new license and uses a different licensing scheme.

You can find upgrade information for Markdown Monster here:

https://markdownmonster.west-wind.com/purchase#upgrades

Or you can continue using the older version. Download links for older versions are on the download page.
