### ISSUE TITLE
After upgrade to MM 2.x, double-clicking a file doesn't load the file

### ISSUE THREAD

**Issue by bladewolf55** [RickStrahl/MarkdownMonster#826]
Version: 2.0.3  
Upgraded via: Chocolatey  
Upgraded from 1.x -latest

**Steps to Reproduce**  
1.  Double-click a Markdown file in File Explorer

Expected: Markdown Monster application opens and file is displayed  
Actual: MM opens, but file isn't loaded

**More Information**  
MM is set to always open new instances. I haven't done any more troubleshooting such as clean reinstall, change settings, in case you want me to try anything specific while the problem exists.

**Comment by RickStrahl** [comment]
Only happens when MM opens a new window for every file. Works when using singleton window.

Checking what changed here - looks like the path through that checks for singleton doesn't run the command line opener if it's not a singleton window.

**Comment by RickStrahl** [comment]
Ok after looking at this this was another one of the side effects of the async conversion in v2. It's a timing issue with command line files. Actually caused a few other problems, which have now been fixed. 

Update in 2.0.4 has the fixes.

**Comment by bladewolf55** [comment]
Thank you!

--
Charles L Flatt
"There's some folks that, if they don't know, you can't tell 'em." --Louis
Armstrong

**Comment by bladewolf55** [comment]
Confirmed, works now.
