### ISSUE TITLE
Enable Bullet Auto Completion isn't honored at first launch

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#829]
In Markdown Monster Settings, uncheck / turn off Enable Bullet Auto Completion. Close and restart Markdown Monster.

Start a new document. Start typing a numbered list:

```text
1. asdf
```

Hit return, and see this:

```text
1. asdf
2.
```

If I understand correctly, unchecking the Enable Bullet Auto Completion checkbox is supposed to turn off that behavior, so that hitting return at this point should not give me a "2.".

Meanwhile, I notice that this behavior changes after I bring up the Markdown Monster Settings window. I don't need to change any of the settings. I do this to confirm that the Enable Bullet Auto Completion is really off -- which it is -- but I don't need to change anything: just the act of launching that window causes this behavior to change to the way I think it should have been from the start. If I open and immediately close the Markdown Monster Settings window and go back to typing a new numbered list, the act of hitting return after "1. asdf" does not result in a "2." on the next line, which is what I expect and want to see.

**Comment by RickStrahl** [comment]
Hmmm... yes I see this. 

It's a bit simpler than this - it looks on the first pass when the document loads the setting doesn't 'take'. On the second pass (if you activate another tab, then re-activate the current tab) then it starts working.

Not quite sure why that is though. It's an event handler that's applied to the document that intercepts the special key operations. I'm going to play around with the order of various options - I suspect that has something to do with it as there are other operations that effect auto-completion of other things.

**Comment by RickStrahl** [comment]
Crap - nothing a good old `setTimeout()` can't fix:

```js
if (!style.enableBulletAutoCompletion) {
    window.setTimeout(function() {
            console.log('setting next line indent');
            te.editor.session.getMode().getNextLineIndent = function(state, line) {
                return this.$getIndent(line);
            };
        }, 100);
}
```

Works with that in place. Will be in 2.0.6+.
