### ISSUE TITLE
Implement autosave feature

### ISSUE THREAD

**Issue by weggetor** [RickStrahl/MarkdownMonster#83]
Hi Rick,
I had now the second unexpected crash in MarkDownMonster (something in jscript.dll or similar) and lost all my work. Would be nice if you could implement some autosave feature.

**Comment by RickStrahl** [comment]
It's on the list of features, but it'll be a bit of work to implement.

We already have an issue for this so I'm closing this one.

Ctrl-s, man. Ctrl-s :-)

**Comment by RickStrahl** [comment]
FWIW I've implemented initial auto-save functionality:

0904c9be9c2f37d5a67dc4064bc8228a5027f32a

**Comment by RickStrahl** [comment]
Feature is not available in v1.0.28 at https://markdownmonster.west-wind.com/download.aspx
