### ISSUE TITLE
The emoji's I'm embedding in my markdown document are not surviving the conversion to PDF

### ISSUE THREAD

**Issue by babyboomer53** [RickStrahl/MarkdownMonster#830]
I'm creating a markdown document using the editor in the IntelliJ IDEA integrated development environment. The document includes a couple of embedded emojis. When I use _Markdown Monster's_ _Save as PDF_ dialog to convert the document to PDF, the emojis are not preserved.

![Step-1](https://user-images.githubusercontent.com/38309112/127209259-a3144b06-f7cb-4f18-831c-428d2215e042.png)

![Step-2](https://user-images.githubusercontent.com/38309112/127209264-56668cfd-09e9-41c4-917f-852183d58bc0.png)

![Step-3](https://user-images.githubusercontent.com/38309112/127209265-e1a726ba-a622-4bd0-a4bb-2a771451b43d.png)

![Step-4](https://user-images.githubusercontent.com/38309112/127209266-1b19521c-b81b-4105-b710-2ad4342e9c57.png)

![Step-5](https://user-images.githubusercontent.com/38309112/127209267-b6c84479-cbec-48ff-a73b-41d76689cef4.png)

![Step-6](https://user-images.githubusercontent.com/38309112/127209268-bd2a15d1-dc9b-4410-917e-962007c21b17.png)

![Step-7](https://user-images.githubusercontent.com/38309112/127209271-34fbe849-1e77-44ff-941a-7419e2d647b0.png)

I have attached the original markdown as well as its PDF counterpart.

[README.md](https://github.com/RickStrahl/MarkdownMonster/files/6887906/README.md)
[README.pdf](https://github.com/RickStrahl/MarkdownMonster/files/6887916/README.pdf)

**Comment by RickStrahl** [comment]
Hmmm... interesting. Looks like wkhtml2pdf doesn't use the same CSS ordering as the HTML view does.

Try this:

In the Preview browser:

* Right click -> Edit Theme
* Open `theme.css`
* Find the `@media print {` section on the bottom
* Add the following:

```css

/* for PDF generation and print output */
@media print {
  html, body {
    font-family:  "Segoe UI Emoji", "Apple Color Emoji", -apple-system, BlinkMacSystemFont,"Segoe UI", Helvetica, Helvetica, Arial, sans-serif;
  }
  ... 
```

By forcing the emoji fonts to the front of the order wkhtml2pdf recognizes the emoji. Unfortunately this also affects the rest of the fonts, so I think effectively this uses Segoe UI Emoji as the main font and overrides whatever the main font is. For most this is Segoe Ui, but even there the Emoji version is not as clean as the standard font which is why we don't use this configuration by default.

**Comment by babyboomer53** [comment]
Thank you, Rick! It looks like that's working! I haven't done any CSS stuff in several years. I had to brush the cobwebs away. There is another problem, however. Ever since I upgraded to the latest version of Markdown Monster, I get the following error every time I open the application:  I haven't been able to figure out how to disable/remove this Add-in. Should I just remove the directory? Cheers, Edgar Sent from Mail for Windows 10 From: Rick StrahlSent: Tuesday, July 27, 2021 10:39 PMTo: RickStrahl/MarkdownMonsterCc: babyboomer53; AuthorSubject: Re: [RickStrahl/MarkdownMonster] The emoji's I'm embedding in my markdown document are not surviving the conversion to PDF (#830) Hmmm... interesting. Looks like wkhtml2pdf doesn't use the same CSS ordering as the HTML view does.Try this:In the Preview browser:Right click -> Edit ThemeOpen theme.cssFind the @media print { section on the bottomAdd the following:/* for PDF generation and print output ***@***.*** print {  html, body {    font-family:  "Segoe UI Emoji", "Apple Color Emoji", -apple-system, BlinkMacSystemFont,"Segoe UI", Helvetica, Helvetica, Arial, sans-serif;  }  ... By forcing the emoji fonts to the front of the order wkhtml2pdf recognizes the emoji. Unfortunately this also affects the rest of the fonts, so I think effectively this uses Segoe UI Emoji as the main font and overrides whatever the main font is. For most this is Segoe Ui, but even there the Emoji version is not as clean as the standard font which is why we don't use this configuration by default.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by RickStrahl** [comment]
Can you reformat this issue please?

**Comment by babyboomer53** [comment]
I do not understand your request. Do you want me to resubmit the Add-in issue separately? Sent from Mail for Windows 10 From: Rick StrahlSent: Wednesday, July 28, 2021 10:48 AMTo: RickStrahl/MarkdownMonsterCc: babyboomer53; AuthorSubject: Re: [RickStrahl/MarkdownMonster] The emoji's I'm embedding in my markdown document are not surviving the conversion to PDF (#830) Can you reformat this issue please?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by RickStrahl** [comment]
Don't reply via email - your email client is butchering your responses. Look on the GitHub Issues site to see what it's done :smile:

**Comment by babyboomer53** [comment]
Yikes! Okay. I made the change to the CSS file that you recommended and it seems to have made the difference. I don't have a lot of files with emoji's that I can test with.

**Comment by RickStrahl** [comment]
That fix should work for all of them, but as mentioned it basically forces the use of that specific font (on Windows at least) which may have other side effects in rendering as it's not quite the same character set as the regular `Segoe UI` (and it's black and white rather than color icons).

**Comment by babyboomer53** [comment]
Incidentally, I elected to restore the original theme.css file containing its version of the media query. As predicted (see Rick's comment earlier in this thread), the font changed globally, and I didn't really like the way it looked. I can achieve the desired result (except that the emojis will be black-and-white) by first opening the preview in a web browser and opening a context menu:

![Screenshot-0](https://user-images.githubusercontent.com/38309112/128639527-4dae46d8-5d22-49b8-9929-69429f67fa56.png)

… then following the steps to print it to a PDF file (i.e., Microsoft print to PDF);

![Screenshot-1](https://user-images.githubusercontent.com/38309112/128639569-d8f9691c-40a1-49ce-b496-302964d6dfa7.png)

Once the document is opened in a browser window, left click anywhere in that view.

![Screenshot-2](https://user-images.githubusercontent.com/38309112/128639584-0125d76b-d604-4085-b944-70976817187d.png)

After the preview finishes building, you'll see the following:

![Screenshot-3](https://user-images.githubusercontent.com/38309112/128639594-8a0fbebe-360d-4a63-8269-dbfbb057820c.png)

Press **Print** to save the document in PDF format.

![Screenshot-4](https://user-images.githubusercontent.com/38309112/128639650-5e65d2fc-e0a4-483e-8c6f-35e68602a90d.png)

**Comment by RickStrahl** [comment]
Yeah you can also do this directly out of the preview window by using the Print option. It'll open the same Chromium print dialog in the previewer.

The previwer does a much better job than then the wkhtml2pdf, but you have no control over headers and footers other than to turn them on or off. There are no options.

But if you use any kind of scripted components in your output (code snippets, MathMl, Mermaid charts etc.) the Print option will be a better choice.
