### ISSUE TITLE
Settings - Editor Font always rollback to "Consolas" - MM 2.x

### ISSUE THREAD

**Issue by kkbruce** [RickStrahl/MarkdownMonster#832]
I upgrade to MM 2.x; I feel that the font is a bit strange.

It is found during modification (regardless of GUI or JSON) that it will always be changed back to the default value (Consolas) after modification.

**Comment by RickStrahl** [comment]
I think this works just fine, but you have to use a proportional font (Consolas, Courier New, Fira Code, Hasklig etc.) If you choose a non-existing or non-proportional font, the value reverts to the default which is Consolas.

**Comment by kkbruce** [comment]
I think I know the reason. I entered "FiraCode" as "Fira Code".
