### ISSUE TITLE
Block editing not working

### ISSUE THREAD

**Issue by bladewolf55** [RickStrahl/MarkdownMonster#834]
Version: 2.0.5.

In MM 1.x, block editing was allowed after:

* Ctrl+Alt+Down arrow
* Alt+Shift+Select

It appears block editing isn't enabled at all, now.

**Comment by bladewolf55** [comment]
I'm seeing a small change with 2.0.7. Now, pressing Ctrl+Alt+Down Arrow, then releasing the keys, results in the Alt menu being activated. If I press Escape, the Alt menu is deactivated and block editing works.

The same is true for Shift+Alt+Drag/Select.

**Comment by RickStrahl** [comment]
Hmmmm... I can see why that's happening. The WebView control doesn't automatically pass out Alt-key menu handling so I explicitly capture alt-key handling and activate the menu. Looks like there needs to be more logic there to prevent key combos like ctr-alt to or Alt-Shift to trigger.

Not sure that this will ever be perfect unfortunately. Let me poke around with this.

**Comment by RickStrahl** [comment]
Ok... so looks like I can pick up the keys as long as they are literally held at the same time (ie. not Ctrl then Alt, but actual both held down Ctrl-Alt).

Give this a try in 2.0.7.1 or later.

**Comment by RickStrahl** [comment]
Fixed in 2.0.7.3 and later.

**Comment by bladewolf55** [comment]
Looks good, thanks.
