### ISSUE TITLE
Conversion HTML crashes

### ISSUE THREAD

**Issue by vincenthel** [RickStrahl/MarkdownMonster#835]
Hi Rick,

Conversion to HTML (self contained) crashes

Where can I catch the error log ?

Best regards

**Comment by RickStrahl** [comment]
Help -> Show Error Log

**Comment by vincenthel** [comment]
This error, and a old one (TOC)

20/08/2020 17:24:38 - Couldn't add menu item: MainMenuTools 

13/07/2021 19:19:50 - AppDispatcher: La valeur n'est pas comprise dans la plage attendue.
La valeur n'est pas comprise dans la plage attendue.
Markdown Monster v2.0.0.13
10.0.19041.1.amd64fre.vb_release.191206-1406 - fr-FR - NET 4.8 - 64 bit
fr-FR - fr-FR    
---
Microsoft.Web.WebView2.Core
   à Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON reason)
   à Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
   à System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   à System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   à System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   à System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   à System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   à System.Windows.Input.InputManager.ProcessStagingArea()
   à System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   à System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   à System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   à System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   à System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   à System.Windows.UIElement.Focus()
   à System.Windows.FrameworkElement.OnPreviewGotKeyboardFocus(Object sender, KeyboardFocusChangedEventArgs e)
   à System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   à System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   à System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   à System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   à System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   à System.Windows.Input.InputManager.ProcessStagingArea()
   à System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   à System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   à System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   à System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   à System.Windows.Interop.HwndKeyboardInputProvider.OnSetFocus(IntPtr hwnd)
   à System.Windows.Interop.HwndKeyboardInputProvider.FilterMessage(IntPtr hwnd, WindowMessage message, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
System.ArgumentException
---------------------------

31/07/2021 08:17:19 - Editor WebView Control Process Failed: RenderProcessUnresponsive Unresponsive

02/08/2021 08:50:45 - Editor WebView Control Process Failed: RenderProcessUnresponsive Unresponsive

**Comment by RickStrahl** [comment]
I can't replicate that.  It works for me.

Can you provide steps and if possible the document that you're doing this with?

**Comment by RickStrahl** [comment]
Probably related to #838.

Can you try this in 2.0.9, please? The error is likely not consistent if it occurs(ed).

**Comment by vincenthel** [comment]
With 2.0.9, it's OK.
Thank you !

**Comment by RickStrahl** [comment]
Thanks - keep in mind it might be inconsistent. If it comes back please let us know here.
