### ISSUE TITLE
When converting to PDF, lines in (Java) code blocks are being split across page breaks.

### ISSUE THREAD

**Issue by babyboomer53** [RickStrahl/MarkdownMonster#836]
When converting my Markdown documents to PDF, I've noticed that lines in the code blocks (e.g., ```java) are getting split horizontally by (soft) page breaks. I'm referring to them as "soft" because these are not explicit page breaks that I have placed in the document. I'm assuming they are being generated dynamically by the conversion process. An example follows:

![Mark down to PDF conversion problems](https://user-images.githubusercontent.com/38309112/128601840-9fb8ed63-ee3f-4eab-abff-038a97f9be83.png)

I've tried changing the page orientation and margins, to no avail. I've also tried placing page breaks in the code section where the anomalies are occurring, but the problem simply moves to other lines in the document.

[README.md](https://github.com/RickStrahl/MarkdownMonster/files/6949170/README.md)
[Homework6.pdf](https://github.com/RickStrahl/MarkdownMonster/files/6949171/Homework6.pdf)

**Comment by RickStrahl** [comment]
Unfortunately there's nothing that I can do about this as the printing to PDF is controlled by the Chromium PDF generation engine in `wkhtml2pdf`. 

An alternative is to use the Print feature on the HTML Preview and then print to PDF. It looks like the native Edge Chromium printing does a better job with the code formatting than `wkhtml2pdf``, but there's less control over options and unfortunately that process can't be automated externally.

**Comment by babyboomer53** [comment]
Understood. Thank you.

**Comment by RickStrahl** [comment]
I created an issue with `wkhtml2pdf` to see if it can be handled at that end. 

However, I doubt this will get addressed since that repo is not very active - there are over 1k outstanding issues so not much chance of this getting addressed.
