### ISSUE TITLE
Frequent failure saving new file with long file name

### ISSUE THREAD

**Issue by bladewolf55** [RickStrahl/MarkdownMonster#837]
## Environment
Version: 2.0+  

## Description and Repro
Several times I've followed these steps to create a new file:

1. Open MM > New Document (using link or Ctrl+N doesn't seem to matter)
2. Enter some text
3. Ctrl+S (and probably File > Save) to open save dialog
4. Enter a long file name, approx 42 characters, and OK to save

Expected: File is saved with name.
Actual: Dialog box unexpected error. File is not saved.

## More Information
I tried to consistently reproduce this, and found that while it will happen a lot, it may not happen all the time.

It's possible this is more likely with a long file path?

## Impact
While I often create a new Markdown file by creating the file in Explorer first, where this bug impacts me is creating a blog post. I'll create a new document, add metadata and start the post, then try to save the file and lose all that work.

**Comment by RickStrahl** [comment]
I'm guessing there's some problem with the file name that's the problem. The filename itself being too long may not be the problem but the path + file > 512 characters perhaps? 

It would be good if you could capture the file name that you're trying to save to.

FWIW, I use this scenario (Ctrl-N, Edit, Ctrl-s) quite frequently for creating and saving files and I haven't seen issues.

A repro would be helpful so there's someting that hopefully duplicate. 

But even assuming there is a problem with invalid filename, it certainly sounds like the error handling should be better so more info is available on why the save fails.

Can you also clarify exactly what happens on the failure? Not clear whether this is a an error where the file doesn't save, dialog and you can retry or is this a hard failurewhere the app exits?

**Comment by bladewolf55** [comment]
> I'm guessing there's some problem with the file name that's the problem. 

Doubtful. I could reproduce the problem with the filename `12345678901234567890123456789012345678901234567890123456789012`

I just checked and the full file path was 197 characters, so that's not it either.

The failure is an unhandled exception. I get prompted to cancel or debug since I have debugging tools installed. I've never debugged but might tray that next time, too, in case it gives a clue. Closing the prompt immediately closes the app.

I wish I had a consistent repro, but wanted to get you the info since it's leading to lost data. Maybe surrounding the save with a try..catch can at least help log the problem?

**Comment by RickStrahl** [comment]
Can you take a look at your error log and see what you find there? Help -> Show Error Log. Last few entries should relate to that error.

I'll take a look.

**Comment by bladewolf55** [comment]
```
7/30/2021 11:12:35 AM - Editor WebView Control Process Failed:
RenderProcessUnresponsive Unresponsive
```

**Comment by RickStrahl** [comment]
That's something else...

I've played around with this on my end and I can't duplicate this behavior with any length of file. Even if I put a really long filename in that exceeds the 512 boundary I get an error that I can't save but it doesn't crash the app hard:

![image](https://user-images.githubusercontent.com/1374013/128615970-4b9bd5cd-7eb5-4cc0-a7ad-d84e27799768.png)

**Comment by RickStrahl** [comment]
I've added some additional error handling around the UI based save operation command, so if this is directly related to the save operation you should then see an error dialog with hopefully a little more information.

**Comment by bladewolf55** [comment]
Roger. I'll try to reproduce it once I've updated.

**Comment by bladewolf55** [comment]
Rick, I'm going to put this on hold for a week or so. I'm seeing a problem with a utility I wrote that's having trouble accessing files, even though it runs from my account.

There may be problems with my computer's permissions, which would account for the MM symptoms (unless someone else reports the same thing).

**Comment by RickStrahl** [comment]
Regardless though the failure should not result in an unhandled exception, but I think that is fixed now. So even if it still fails would be good if you retry that now with 2.0.8.3+ which has the fix in it.

**Comment by bladewolf55** [comment]
Will do.


--
Charles L Flatt
"When you can balance a tack hammer on your head, you will head off your
foes with a balanced attack!" --The Sphinx, Mystery Men

**Comment by bladewolf55** [comment]
Version: 2.0.8.3

## Repro:

1. Open MM
2. Click New File
3. Enter "asdf"
4. Save to folder, typing file name 12345678901234567890123456789012345678901234567890

## Debug Info
I accepted the debugging prompt. Here's the output from VS 2019.

```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{4D00C0D1-9434-4EB6-8078-8697A560334F}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
  Source=mscorlib
  StackTrace:
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.Wpf.WebView2.Uninitialize(Boolean browserCrashed)
   at Microsoft.Web.WebView2.Wpf.WebView2.Dispose(Boolean disposing)
   at System.Windows.Interop.HwndHost.Finalize()
```

## Screen Shots
![image](https://user-images.githubusercontent.com/2903411/128652404-2ddacb57-5358-47fc-969e-2aeb9b10820f.png)

![image](https://user-images.githubusercontent.com/2903411/128652420-ea7efde4-bfa7-4058-93b6-71380ffcc2ec.png)

**Comment by RickStrahl** [comment]
Same issue as #838 most likely.

Closing and referring to that issue.
