### ISSUE TITLE
SampleMarkdown.md Footnote Suggestion

### ISSUE THREAD

**Issue by CheetahChrome** [RickStrahl/MarkdownMonster#839]
Upon reading the documentation, I found have this suggestion

Footnotes is understood if markdown is read directly, but the text needs to show the literal command for the actual footnote anchors. Something like this would be better:

```
Here is some text that includes a Footnote [^1] (`[^1]`) in the middle of its text. And here's another footnote (`[^2]`) [^2]. The actual footnotes render on the very bottom of the page.
```

**Comment by RickStrahl** [comment]
Not sure what you're asking/saying here.
