### ISSUE TITLE
AccessViolationException when opening Settings

### ISSUE THREAD

**Issue by alexwiese** [RickStrahl/MarkdownMonster#84]
Error when opening Markdown Monster and clicking Tools -> Settings. It doesn't happen every time, seems to be intermittent.

> Application: MarkdownMonster.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.AccessViolationException
>    at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
>    at System.Windows.Application.RunDispatcher(System.Object)
>    at System.Windows.Application.RunInternal(System.Windows.Window)
>    at MarkdownMonster.App.Main() 

> Faulting application name: MarkdownMonster.exe, version: 1.0.28.0, time stamp: 0x5853c05d
> Faulting module name: jscript9.dll, version: 11.0.14393.576, time stamp: 0x584a77ab
> Exception code: 0xc0000005
> Fault offset: 0x00000000001445e7
> Faulting process id: 0x35b4
> Faulting application start time: 0x01d25a768c52d17e
> Faulting application path: C:\Program Files\Markdown Monster\MarkdownMonster.exe
> Faulting module path: C:\Windows\System32\jscript9.dll
> Report Id: 846c64ac-d9ab-490f-9ad3-3e0af9d5c725
> Faulting package full name: 
> Faulting package-relative application ID:

**Comment by RickStrahl** [comment]
Can you do me a favor and install the latest version (1.0.30 or later).

I switched to a 32 bit binary which seems to have alleviate some of the jittery COM Interop issues with much better stability for both the editor and preview which use the WebBrowser.

FWIW, I've not seen or heard about failures in Settings which is just a JSON file opened in the editor. But I've seen exceptions for the jscript.dll failures that are internal to the WebBrowser. Also, could you post your log if there's anything related to this failure? (Help -> Show Error Log)

**Comment by alexwiese** [comment]
No worries. I've installed the latest version and it is working fine now.

FWIW the error log didn't have anything useful in it relating to this issue.

> 20/12/2016 2:42:25 PM - Unable to send telemetry: The operation has timed out
> 20/12/2016 2:46:36 PM - Unable to send telemetry: The operation has timed out
> 20/12/2016 3:01:58 PM - Unable to send telemetry: The operation has timed out
> 22/12/2016 8:53:17 AM - Unable to send telemetry: The operation has timed out
> 22/12/2016 8:55:32 AM - Unable to send telemetry: The operation has timed out

**Comment by RickStrahl** [comment]
That's great. Thanks for confirming.
