### ISSUE TITLE
Custom add-on no longer loads after 2.x upgrade

### ISSUE THREAD

**Issue by deanebarker** [RickStrahl/MarkdownMonster#842]
I did the paid upgrade to 2.0.

My custom Markdown parser stopped working. I went into Visual Studio and found that I had to modify some code (most of the methods now want a `Task` returned, instead of `void`). Fixed all that, recompiled, republished.

But, it still doesn't work.

I put the DLL in the same place --

```
C:\Users\deane\AppData\Roaming\Markdown Monster\Addins\[addin name]\
```

-- but it's no longer loaded when MM starts up. It doesn't work when MM starts normally, nor when I run debug mode out of Visual Studio. MM works normally, it just doesn't believe my add-in exists.

I've searched through the doc and these issues, but didn't find anything that addressed the issue.

**Comment by RickStrahl** [comment]
This should still work but as you point the addin interfaces have changed to better support integration with the editor which is now mostly via async interface. 

For a custom parser addin though there aren't any changes. Take a look at the [Pandoc Addin](https://github.com/RickStrahl/Pandoc-MarkdownMonster-Addin/blob/master/PanDocMarkdownParserAddin/PanDocMarkdownParserAddin.cs) which has been updated for v2.

**Comment by deanebarker** [comment]
I figured it out -- the shortcut for the app changed from `AppData\Roaming` to `AppData\Local`. Moving my add-in over to that folder structure made it work. No idea why 2.x set up a shortcut pointing to somewhere different, though.

**Comment by RickStrahl** [comment]
Hmmm... you might have had the addin installed in the wrong place. The addins should install into the Common settings folder which by default is `%appdata%\MarkdownMonster\Addins`.

By default this applies:

* The application installs into `%appdatalocal%\Markdown Monster` by default
* Application settings go into `%appdata%\Markdown Monster` 

Native addins shipped with Markdown Monster go into the install location. Any third party addins should install into the user folder (ie. `%appdata%\Markdown Monster\Addins\yourAddin\`)

Now this may change if:

* You're running a portable install - in that case the common folder lives below the install folder by default 
* You've changed the common folder to some other location

`%localappdata%\Addins` may work too but it's not recommended as that folder may be occasionally cleared out by the installer. It's meant only for the built-in addins (WebLog, Screen Capture and Snippets). All other addins should go to the common folder.
