### ISSUE TITLE
Error dialog fails to pop up when posting a blog entry fails (issue #824)

### ISSUE THREAD

**Issue by joemclain** [RickStrahl/MarkdownMonster#844]
I hate to bring this up this error dialog issue again.

You said in https://github.com/RickStrahl/MarkdownMonster/issues/824

>`This was fixed some time ago. IT doesn't show error info unfortunately because the XmlRpc library unfortunately doesn't surface the full error information 😢`

I understand and can see the XmlRpc does not return the specific error, but does return a generic error. This error should be displayed, but will normally NOT be displayed. Because:

The MessageBox that attempts to show the error uses the addin instance variable `WeblogForm` as it's parent window. This variable will be null unless `OnExecute()` was called on the addin which it will not normally happen since we all just use the Weblog top level menu item (and don't select Tools->Add'ins->Weblog which causes `OnExecute()` to be called).

Anyway, the MessageBox call in `SendPost()` should use the WeblogForm instance created in `Command_WeblogForm()`.

I could fix and push this issue, but I assume you'll want to look at it yourself.

-joe mclain-

**Comment by RickStrahl** [comment]
```cs
void Command_WeblogForm()
{
	WeblogFormCommand = new CommandBase((parameter, command) =>
	{
		var action = parameter as string;
		if (string.IsNullOrEmpty(action))
			return;

		if (action == "openweblogfolder")
		{
			ShellUtils.OpenFileInExplorer(WeblogModel.Configuration.PostsFolder);
			return;
		}
		else if (action == "openblogpost")
		{
			var link = StringUtils.ExtractString(Model.ActiveDocument?.CurrentText, "\npermalink: ", "\n",
				true);
			if (!string.IsNullOrEmpty(link))
				mmFileUtils.ShowExternalBrowser(link);
			return;
		}

		// actions that require form to be open
		WeblogForm = new WeblogForm(WeblogModel)
		{
			Owner = Model.Window
		};
              var form = WeblogForm;
		form.Model.AppModel = Model;
		form.Show();
...
}
```

Seems like the better way is to create the form and use the `Addin.WeblogForm` variable so it is set as expected. In theory that should always be the case, but that one was missed.

**Comment by joemclain** [comment]
I'll do my best to check this over the weekend.

**Comment by joemclain** [comment]
This appears to work correctly now.

**Comment by RickStrahl** [comment]
Thanks for verifying!
