### ISSUE TITLE
Uninstall addin option unavailable when no configuration

### ISSUE THREAD

**Issue by joemclain** [RickStrahl/MarkdownMonster#845]
In the addin documentation at https://markdownmonster.west-wind.com/docs/_52a19sbgx.htm it says if you don't require configuration you can set `ExecuteConfigration` to null. When I do this the option to uninstall the addin is not present. This is in the toolbar where there would normally be a dropdown.

-joe mclain-

**Comment by RickStrahl** [comment]
Fixed. Updated in 2.3.17
