### ISSUE TITLE
AddinMenuItem, Toolbar Icons, and Keyboard shortcut keys

### ISSUE THREAD

**Issue by joemclain** [RickStrahl/MarkdownMonster#848]
If the `FontawesomeIcon` property is not set on an `AddinMenuItem` instance there is no icon on the toolbar ** **this is to be expected** **. However, any keyboard shortcut that is associated with the menu item  will not be functional.

I doubt this should be considered a bug since any interactive addin should have an icon in the tool bar.

I'm just pointing this out in case you'd like to document it.

**Comment by RickStrahl** [comment]
That is by design. There shouldn't be a shortcut without a visual clue. Basically the idea for 'invisible' addins is those that tie into the infrastructure and interactive addins that use the User interface (including keyboard I suppose :smile:) to interact.
