### ISSUE TITLE
Introduce Presentation Mode as a New Feature

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#85]
Hi @RickStrahl,

It'd be nice to have an ability to present right from MM.
May be even a Slideshow support :wink: 
Merry X-Mas!

**Comment by RickStrahl** [comment]
Not sure what you're looking for in this request.

**Comment by ArthurZ** [comment]
A command (key bound to say F11) to display only the preview pane. 
I often present in meetings so saving my work in a portable format as PDF/HTML is often un-necessary.

**Comment by RickStrahl** [comment]
Implemented as of 1.0.35

4da40b320cbb1acece4ec601b68e633b2660ba50

1.0.35 is now available from the download page.

**Comment by ArthurZ** [comment]
I like it. Works as intended 🥇
