### ISSUE TITLE
Snippets slow when used first time

### ISSUE THREAD

**Issue by realB12** [RickStrahl/MarkdownMonster#850]
Optimisation Request
When typing a Snippet's ExpansionString in the Editor for the first time, the ExpansionString disappears and nothing happens on my machine (windows 10)  till the replacing string is written after 5-8 seconds. 
This delay is happening only when activated the first time after MM has been launched. Next times the Snippet works in milliseconds. 
So, maybe there is a reason for this (not delaying MM load times in case the Snippets-part might not be used?). 
For me this is not a problem, but just something that could be optimized. e.g. a configuration switch, that loads the "Snippet-Part" always at initial load time rather than when being used first time.

**Comment by RickStrahl** [comment]
Yeah this is a known issue. The problem is that few people use snippets and the snippets engine uses Roslyn and the whole compiler platform which is **very** slow to load. So the first load takes a few seconds (depending on your machine of course).

Previously I had some logic that would start the load process during startup on a separate thread, but the problem with that is that it adds a ton of memory on startup that is slow to release and makes MM look much bigger in terms of memory size used. I ended up removing the pre-loading code at some point.

I need to take another look at this. There could be an option that lets you enable the pre-load on load as an option that's off by default.

**Comment by realB12** [comment]
Hi Rick, 
Thx for commenting on this. For me, it is enough to know that this is not a bug. I can live with it. No hurry :-)
Shall I close the issue?

**Comment by RickStrahl** [comment]
It seems there's a bigger problem here than just initial startup. Seems to be async related where the insertion is delayed until something happens in the UI outside of the Editor itself. 

I'll have to take a look and see and probably update more code to run proper async here.

**Comment by RickStrahl** [comment]
Finally taking another look at this today. So I played around with this some - on my current setup I see first snippet that contains code is definitely lagging a bit as the compilers have to load - after that it's generally fast. I added an explicit flag in the Snippets configuration called `PreloadCSharpCompiler` which defaults to `false` but can be enabled which should speed up `{{exp}}` expansions with C# code. Razor expansions still have additional overhead as the Razor engine has to spin up on first load.

In additiona I did see an occasional lag which appears to be UI based (ie. async) which I have now added some mitigations for. Not seeing that anymore.

So check this out in 2.1.5.7 and later which will have these changes in them - make sure to set the `PreloadCSharpCompiler` flag in the JSON config.

**Comment by RickStrahl** [comment]
Another releated issue: Plain snippets without compiled code run very fast. C# Snippets take a little bit of time to fire up the first then run fast. A recompile or compliing of other snippets first time is a little slow but reasonable. 
Razor Snippets are slow especially on first load. First load of Razor snippets can take a couple of seconds or more to load. Subsequence new snippet compilation is still on the slow side but more reasonable.

There are ways that C# snippets could be optimized, but Razor execute/compilation will always be slow and there's no way I know of to precompile effectively and store. Even if we did, there'd still be the Razor Runtime startup which is slow no matter what.

**Comment by RickStrahl** [comment]
Side note. As I'm considering moving MM to .NET 6.0 in the near future the Razor engine may get ditched leaving only the C# snippet engine. Considering building a simple code parser that can execute with much less resource use, using the same execution engine that the C# snippets use now.

**Comment by realB12** [comment]
Forgot go close. Sorry for that.
