### ISSUE TITLE
Slash and Backslasch issue with drag&drop

### ISSUE THREAD

**Issue by realB12** [RickStrahl/MarkdownMonster#854]
When I drag/drop an **PICTURES** into a *.md file I am getting **Slashes** such as 
<pre>![](pics/AlgoliaLogo.png)</pre>
When doing the same with other **FILES** I am getting **Backslashes**
<pre>[..\..\_TOOLS.md](..\..\_TOOLS.md)</pre>
The problem is that in the Markdown Preview (at least under Windows) both - the picture and the hyperlink to the file are displayed correctly, but the **hyperlink navigation - when being clicked in the Preview - fails** (but works when I replace all Backslashes with Slashes). 

I am not sure whether this is just a "Windows" issue. 

However, could we have a configuration option that specifies the generic use of slashes when drag/dropping stuff? 

For me this is not a serious problem, but an inconvenience when having to manually replace all Backslahes with Slashes to get all Links working in the preview - or is there an elegant/efficient way to do this (automatically?).

**Comment by realB12** [comment]
btw: 

When drag/dropping files: wouldn't it be more convenient to have the link-name to be the filename only, rather than putting all the path into it? 

Currently it looks like

<pre>[..\..\TOOLS.md](..\..\_TOOLS.md)</pre>

What I would like to have is

<pre>[TOOLS.md](..\..\_TOOLS.md)</pre>

**Comment by RickStrahl** [comment]
This should be fixed in 2.1.1.4 and later.

**Comment by RickStrahl** [comment]
So the above fixes I made affect dragging and dropping out of the Folder Browser into a document with relative links. I think that's likely the most common scenario.

### Secondary and related issue

After some additional checking I see that Explorer drag and drop is broken in v2. Looking into it but haven't found a way yet to capture the drop events from OS files being dropped. Stay tuned.
