### ISSUE TITLE
Please scale preview panel

### ISSUE THREAD

**Issue by DangerMouseB** [RickStrahl/MarkdownMonster#858]
I.e. in a manner similar to the editor scale pulldown.

**Comment by RickStrahl** [comment]
You can use standard browser scaling with Ctrl-Scroll wheel or Ctrl-+/-...

Not adding additional controls to the preview. You can modify themes, if you want default sizing to be different or as mentioned you can manually zoom in or out.

**Comment by DangerMouseB** [comment]
Ah thx - it's useful to know about ctrl +/- I didn't find it anywhere. For my need just having it easier to know it exists would suffice (e.g. update help of add zoom to the view menu.

Are there any handy examples of modifying the css/themes? - I really like your Westwind theme though I find it helpful to have the paragraphs etc to be a little more compacted together.
