### ISSUE TITLE
Soft Line Break/Soft Return not working in v2

### ISSUE THREAD

**Issue by martink777** [RickStrahl/MarkdownMonster#867]
Recently upgraded from MM v1 to v2 and have discovered soft line breaks (Shift+Enter) do not actually insert a soft break - Instead, shift+enter seems to add line breaks _above_ the block of text where the cursor is currently positioned.

V1 behaviour - 3x soft returns followed by 3x hard returns:

https://user-images.githubusercontent.com/63983836/137236856-d0c1ec90-a628-407a-b1bf-09ba6395e197.mp4

V2 behaviour - 3x soft returns followed by 3x hard returns:

https://user-images.githubusercontent.com/63983836/137236871-40bf0fe7-bf77-4208-9cfa-974b0b9c78e3.mp4

At the moment I have rolled back to using version 1 as I frequently use soft line breaks to present a list of documentation items without using actual list `<li>` elements.

**Comment by RickStrahl** [comment]
I can confirm - looks like the line break is entered at the top and that's certainly a bug.

Just so you know, you can use two spaces at the end of the line for the soft linebreak which is the Markdown line break sequence. Also `_` at the end of the line also works.

`Shift-Enter` is supposed to enter two spaces. I think it's doing just that but there's a async timing issue and MM ends up adding it in the wrong place.
