### ISSUE TITLE
If a file opened in MM is edited by another program MM errors out and unable to display it

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#87]
If a file opened in MM is edited by another program MM errors out and unable to display it.

The error message 
```
---------------------------
Markdown Monster Error
---------------------------
Yikes! Something went wrong...
Cannot perform runtime binding on a null reference
The error has been recorded and written to a log file and you can
review the details or report the error via Help | Show Error Log
Do you want to continue?
---------------------------
Yes   No   
---------------------------
```

**Comment by RickStrahl** [comment]
Example please? What application?

**Comment by RickStrahl** [comment]
I don't see that. Using Sublime. I see the dialog pop up, and if I accept the editor updates and all works.
Using the latest version?

**Comment by ArthurZ** [comment]
Yes, the latest. It does not for me.

**Comment by RickStrahl** [comment]
What shows in the log?

**Comment by ArthurZ** [comment]
Please remind me how to turn on the logging. Thx!

**Comment by RickStrahl** [comment]
You don't turn it on - it's on. Look at your error log in Help -> Show Error Log. You might want to clear the log (just delete all content) then make MM fail.

**Comment by RickStrahl** [comment]
Is this still happening?

**Comment by ArthurZ** [comment]
Thank you for the follow-up, I tried to reproduce and this time got a polite dialog 
![image](https://cloud.githubusercontent.com/assets/701808/23042848/417fd830-f468-11e6-8b31-0233bf205ccc.png)
So, yes, it works, does not crash MM, nice!

**Comment by ArthurZ** [comment]
Ohh, reading the text, in English, the proper grammar is:

`Would you like TO reload it?`
😸

**Comment by RickStrahl** [comment]
That's great. Still not sure why that wasn't happening before.

Fixed type.
