### ISSUE TITLE
Problems with HTML

### ISSUE THREAD

**Issue by vincenthel** [RickStrahl/MarkdownMonster#873]
Hi Rick,
I have some problems with the latest version.
1) Crashing always after HTML (self contained)
"Editor WebView Control Process Failed: RenderProcessUnresponsive Unresponsive"
2) Generating PDF erase the HTML version
3) The personalised colors are not respected in PDF conversion (OK in HTML)
Thanks in advance
_Vincent_

**Comment by vincenthel** [comment]
Can you test with this file please, which always crashes during HTML conversion (**with embedded styles** and my theme)
[Suite_Nouveautes.md](https://github.com/RickStrahl/MarkdownMonster/files/7448355/Suite_Nouveautes.md)

**Comment by RickStrahl** [comment]
Tried it a bunch of times, with my themes, your themes, different types of exports. It works for me every time...

![HtmlRenderbug](https://user-images.githubusercontent.com/1374013/139600628-7dd302a8-93df-4825-9477-66e99fb4cac6.gif)

**Comment by RickStrahl** [comment]
And... just for good measure here's the PDF generation as well:

![HtmlRenderAndPdfbug](https://user-images.githubusercontent.com/1374013/139600824-19bb903f-d836-4f2b-b00f-0e73c63063ec.gif)

**Comment by vincenthel** [comment]
I downloaded the latest version and everything looks OK. Thank you
