### ISSUE TITLE
Error When Deleting File From Sidebar

### ISSUE THREAD

**Issue by conradakunga** [RickStrahl/MarkdownMonster#877]
MM v 2.1.3

I have this structure

![image](https://user-images.githubusercontent.com/1281845/139012960-316eb407-96df-46a6-8199-99ce4efd7533.png)

If I delete the **last** file, `test.md`, I get this message

![image](https://user-images.githubusercontent.com/1281845/139013074-76fbd5b5-ddc4-46df-b0d1-273bef8ec8a9.png)

The file, however, does seem to actually be deleted

**Comment by RickStrahl** [comment]
Thank you fixed.

Fixed the off by one index error for re-selection of new item in the list and updated the UI to give a status message on success or failure along with delete count if multiple files are deleted.
