### ISSUE TITLE
Editor freezing when clicking a hyperlinked *.html doc in Preview

### ISSUE THREAD

**Issue by realB12** [RickStrahl/MarkdownMonster#882]
Hi Rick, 
in a *.md file I have the following link:` [documentation.html](../../07_EXP/2_EVA/THEMES/ThemeFischer/Delta/documentation.html)`
In the preview window this link is displayed correctly.
However, when I click it all the Editor freezes. Cannot even close it and have to purge the app from the Task-Manager. 
Monster is in version 2.1.6
Windows 10 Pro newest updates

P.S. Opening this HTML file from the File-Browser works.

**Comment by RickStrahl** [comment]
You're clicking in the preview?

**Comment by RickStrahl** [comment]
Ok, see it now. Fixed for next update.

**Comment by realB12** [comment]
Thank you so much! Great response time!
