### ISSUE TITLE
Preview pane not showing

### ISSUE THREAD

**Issue by bradykelly** [RickStrahl/MarkdownMonster#883]
I have just installed Markdown Monster in the hope of having a decent MD editor, as well as a good preview pane. When I open a markdown file, it shows only the edit pane. Instructions on how to show the preview pane are not working:

- **F12 Shortcut Key**: This key is still bound the same as it was before installing Markdown Monster, i.e. Go to declaration.
- **Preview Toggle  in the top Window menu next to the close box**: I can't find this menu/toolbar
- **On the menu via View -> Html Preview**: I cannot find any such item on the View menu

All these options aside, from your docs it looks like the preview pane should open by default when I open a markdown file but it does not open.

**Comment by RickStrahl** [comment]
Hmmm... Yes the preview pane should open by default. 

What is your screen resolution? In really small horizontal resolution it's possible the preview is entirely collapsed on the right. Can you post a screen shot with the preview enabled (the world icon in the window's title bar on the right).

**Comment by bradykelly** [comment]
My screen resolutions are 1920x1080 and 1366x768, and the preview pane shows on neither screen. I don't have a world icon, I think because my title bar and menu bar are somehow merged, but I can't find an option for that:
![image](https://user-images.githubusercontent.com/5706812/141613657-05ea190d-6448-4977-922b-a81f1986f975.png) And I don't have anything to drag on the right margin to expand the preview pane.

**Comment by RickStrahl** [comment]
@bradykelly - this is a screen shot of Visual Studio? Markdown Monster is not an addin, it's a standalone application you have to run (or Open With... in Visual Studio).

**Comment by bradykelly** [comment]
My bad. I found MM whilst browsing add-ins, and assumed the add-in (there is one for a template) was the real deal. Thanks, Rick.
