### ISSUE TITLE
Screen capture with SnagIt (latest trial) does not work

### ISSUE THREAD

**Issue by posinautinc** [RickStrahl/MarkdownMonster#885]
Hi,

I installed Markdown Monster (installer and portable) along with latest SnagIt trial. When I do a screen capture from Markdown Monster it successfully launches SnagIt and I can capture a screen and end up in the SnagIt editor. However when I click on the editor's 'finish' button I'm asked to save the file.

No matter what location or filename, it always fails to save with a message about invalid parameters.

**Comment by RickStrahl** [comment]
Let me take a look. SnagIt has been having issues with their COM interface implementation not properly exiting the Preview form.

FWIW a quick alternative is to use SnagIt's native capture (from the SnagIt control panel or via hotkey), capture to editor and then copy to clipboard (Ctl-a, Ctl-C), then paste into MM at the desired or current cursor position. I've actually found that to be more efficient than using the addin (hence I didn't notice the failure 😄).

**Comment by posinautinc** [comment]
Hi Rick,

Thanks for looking into this. I tried your recommendation and am seeing a strange issue. Allow me to explain the steps.

1. Open markdown monster. Type in some text but do not save the file.
2. Open snagit, capture an image, select it and copy to clipboard (as you advised).
3. paste it into the unsaved and untitled markdown monster.
4. You're prompted to save the image to disk. I saved it to downloads folder and markdown shows as:

 ![](file:///C:\Users\Nic\Downloads\myfile.png)

Issue: preview does not show image.

4. Click insert image, select the same file and embed image. the same markdown is created.

Issue: second image also does not show in preview.

5. Now save the untitled markdown to the downloads folder.

6. Now if I use snagit to copy and paste or use embed image to select an image the markeup looks like this:

![](anotherfile.png)

and it shows in the preview.

**Comment by posinautinc** [comment]
Hi Rick,

I think the initial comment and my second comment above are unrelated issues.

Regarding the snagit integration, I already have the markdown file saved to disk before I initiate the built in screen capture.

**Comment by RickStrahl** [comment]
Still looking into this. It looks like the image captured from SnagIt's capture utility is in some format that .NET doesn't natively understand - it's a different image type than a captured image from the editor via Ctrl-c. Grrr....

Looking into it. Comes back to this nightmarish clipboard management stuff: 

https://weblog.west-wind.com/posts/2020/Sep/16/Retrieving-Images-from-the-Clipboard-and-WPF-Image-Control-Woes

**Comment by RickStrahl** [comment]
Pasting images into an unsaved file is not a good idea because it'll end up hardcoding the path because there's no path to make the embedded file relative to. If you save first, you'll get a relative path which will work much better.

That said it looks like there's been a behavior change, with the browser control not allowing Windows style paths with backslashes or `file:///` urls. That used to work just fine, so surprised to see that break. Looks like the file format that does work is: `c:/temp/test.png`.

Have to take another look and see what has changed with that.

Regardless though I'd highly recommend saving the document first, so you don't end up with hardcoded paths.

**Comment by RickStrahl** [comment]
Both issues fixed. Updates in 2.1.7.11

**Comment by posinautinc** [comment]
Thanks Rick. Appreciate the fast turnaround on the bugs. I can confirm the 2.1.8 version is good.

Will be trying out Markdown Monster further over the next weeks.
