### ISSUE TITLE
Markdown tables (remove gridlines)

### ISSUE THREAD

**Issue by dyardy** [RickStrahl/MarkdownMonster#889]
Is it possible to remove gridlines with markdown monster?  I am wanting to layout content in table type structure, is there another approach I should be using if I want to remove the gridlines?

**Comment by RickStrahl** [comment]
You can change the style sheets on the theme. Basically:

* Copy existing theme
* Modify theme.css
* Save
* Switch to new theme (may have to restart)

![image](https://user-images.githubusercontent.com/1374013/144767727-87de4941-fb5d-4551-809c-891f0e75cc41.png)


More info in this help topic:

[Switching and Customizing Preview Themes](https://markdownmonster.west-wind.com/docs/_4nn17bfic.htm)
