### ISSUE TITLE
Store md files in OneDrive

### ISSUE THREAD

**Issue by rockfordlhotka** [RickStrahl/MarkdownMonster#89]
I switch between various computers and devices on a regular basis. It would be ideal if MM stored my files in a cloud-shared folder such as via OneDrive.

In reality, on my computers I have my Documents library set to include OneDrive and DropBox, and I have the default save location set to the OneDrive folder.

Unfortunately MM goes directly to my _local_ Documents folder, not the Documents library, so it ignores that OS level preference.

An easy answer (for me anyway) would be if MM honored the Documents library, so files were saved to the default save location within the library; for me that would be my OneDrive folder structure.

**Comment by RickStrahl** [comment]
Hmmm... MM should remember the last location you saved to and use that for your next save location by default. Failing that it'll go to Documents.

I wasn't aware of a Documents Library - i have to see how to get at that folder. That would definitely make a better default.

New Blog posts are created in DropBox folder or Documents and that's a bit more heavy handed, but you can of course move files as needed.

**Comment by rockfordlhotka** [comment]
Remembering the last save location will solve my problem - I'll just force a save into my OneDrive folder and everything should be fine from that point forward I'd think. Thanks Rick.

**Comment by RickStrahl** [comment]
So is this what you want to see when the location can't be resolved?

![image](https://cloud.githubusercontent.com/assets/1374013/21510995/a7573592-cc3e-11e6-9e88-2b67c636e79f.png)

**Comment by RickStrahl** [comment]
One more thing:

For new blog posts you can specify the folder where new posts are created (for **File -> New Weblog Post** or from the Weblog Addin Window) via configuration setting in the `weblogaddin.json` and the 
`PostsFolder` which defaults to `<userProfile>\DropBox\Markdown Monster Weblog Posts`. You can change that to a OneDrive folder.

**Comment by rockfordlhotka** [comment]
I can't figure out how to change the new blog post location. I thought I changed the config file, but that didn't seem to make a difference, and you can't enter the path (only the filename) in the dialog.

**Comment by RickStrahl** [comment]
Hmmm... works for me :-)

Here's what I'm doing. 

* Start MM
* Tools -> Open Configuration Folder
* Edit `weblogaddin.json`
* Set `"PostsFolder": "C:\\Users\\rick\\OneDrive\\Markdown Monster Blog Posts",
* Save `weblogaddin.json`
* File -> New Weblog Post
* Fill out form
* New post pops up
* Right click on tab -> Open Folder
* Find myself in `C:\\Users\\rick\\OneDrive\\Markdown Monster Blog Posts\Test Post`

Note that you have to use `New Weblog Post` to use that config setting. If you just create a new document the logic described earlier is applied.

**Comment by rockfordlhotka** [comment]
OK, I got that working - thank you!

**Comment by RickStrahl** [comment]
Did you figure out why it wasn't working before? Anything that needs addressing (other than UI for the config settings :-))

**Comment by rockfordlhotka** [comment]
Yes, it was something that happened in the processing controller outside the computer and past the keyboard 😄  So a UI would have probably avoided my problem, but a little more attention to detail also worked.
