### ISSUE TITLE
Request to support hashnode as weblog

### ISSUE THREAD

**Issue by thgossler** [RickStrahl/MarkdownMonster#892]
See https://hashnode.com/, a very easy to use blogging site with custom domain support.

**Comment by RickStrahl** [comment]
I don't see any sort of API for adding posts. If you can provide more information of what you think can be done I might consider it.

From what I see they require you to use their Markdown Editor online to compose posts which is not conducive to automation. Probably on purpose (same as Medium does to force you to stay on the platform).
