### ISSUE TITLE
Newly added files incorrectly appear in the filtered folder view

### ISSUE THREAD

**Issue by deanebarker** [RickStrahl/MarkdownMonster#895]
This is a very minor bug, but if you filter the folder view for a string in the file name, then add new files, the new files will show up in the filtered view even though they don't match the filter.

So, if you filtered the folder view for "foo," it would accurately show files like `foobar.md` and `foobaz.md`. If you kept this filter in place, and then added a file called `gumby.md`, that will also show up in the filtered folder view, even though it doesn't match the "foo" filter.

Again, a minor bug, but I thought you'd want to know.

**Comment by RickStrahl** [comment]
Fixed.
