### ISSUE TITLE
Winget upgrade no more working

### ISSUE THREAD

**Issue by Trobeloo** [RickStrahl/MarkdownMonster#898]
Winget upgrade is no more working.
Available upgrade detection is ok:
![image](https://user-images.githubusercontent.com/2814461/147813485-f6a21e00-531e-461c-9536-9c07fd0040d7.png)

Tried the following 2 syntax:
❯ winget upgrade  WestWind.MarkdownMonster
No applicable update found.

❯ winget upgrade  Markdown-Monster
No applicable update found.

**Comment by RickStrahl** [comment]
I don't actually maintain the WinGet repo - they're automatically updated. I can't check but the manifests are there and the version exists.
