### ISSUE TITLE
Single newline line continuation

### ISSUE THREAD

**Issue by NavalOrange** [RickStrahl/MarkdownMonster#899]
Hey there, Markdown Monster is a really cool program and I've mostly been happy with it so far, but is there any way to have an option to have single newline line continuation? 

```
pizza//no extra whitespace
party
```
rendered to
```
pizza//no extra whitespace
party
```

I found a piece of documentation saying `By default Markdown adds paragraphs at double line breaks. Single line breaks by themselves are simply wrapped together into a single line. If you want to have soft returns that break a single line, add two spaces at the end of the line.`

I'm using MM to write notes, and having to rewire my brain to double space everything is driving me crazy so far.

Apologies in advance if there is already a setting for this, I was trying to find it, but this is the closest thing I could find to a forum

**Comment by RickStrahl** [comment]
Yeah sorry, no. :smile:

That's basic Markdown functionality and that's just the way it works.  You can use two spaces or an underscore at the end of a line to force line breaks.
