### ISSUE TITLE
Access violation exception

### ISSUE THREAD

**Issue by bleroy** [RickStrahl/MarkdownMonster#90]
This happened after pasting text into an existing document. It happened twice in 24h, I don't have much more info than that because I have no symbols or even a debug build.

```
System.AccessViolationException was unhandled
Message: An unhandled exception of type 'System.AccessViolationException' occurred in System.Dynamic.dll
Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```

**Comment by RickStrahl** [comment]
What version are you running? If you haven't updated to the recent 32 bit updates give that a try. I've seen a lot of these odd browser crash issues disappear.

**Comment by RickStrahl** [comment]
Any better with newer versions?

**Comment by bleroy** [comment]
OK, I'll update and keep you posted if that happens again.
