### ISSUE TITLE
Characters cut off on Mermaid charts in MM when using fontawesome icons

### ISSUE THREAD

**Issue by sqlposh** [RickStrahl/MarkdownMonster#902]
### Steps to reproduce

1. Open new .md document
2. Type the following mermaid chart code
```
<div class="mermaid">
graph LR
    rs[fa:fa-reply-all Response #2]
</div>
```
3. Settings --> Mermaid Diagrams checked
4. Settings --> Mermaid Diagrams Url  using the default 
`https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js`
5. Settings --> Allow Script Tags in Markdown
6. Settings --> Web Browser Preview Executable
`"C:\Program Files\Google\Chrome\Application\chrome.exe"`

### Expected Behavior
It's expected that all of the text rendered is visible (Live Editor displays it properly)

![image](https://user-images.githubusercontent.com/59573341/150202470-8b39424d-c2ff-4f38-922e-19906d73d1db.png)

### Actual Behavior
The text for the node is cut off on the right as long as FA icon is in the text
![image](https://user-images.githubusercontent.com/59573341/150202372-439775a1-432d-46bd-afdc-dcf10dd32e00.png)

**Comment by RickStrahl** [comment]
There's nothing that I can really do about that - that's Mermaid's rendering that's causing this issue. I think the problem is that the Font-Awesome characters are probably not returning proper font widths and therefore when Mermaid writes out the labels the width calculation might be off. 

The way around this is to add a space (or more) at the end to force Mermaid to render a little wider.

**Comment by sqlposh** [comment]
If it were Mermaid, wouldn't their live editor have the same artifact?

**Comment by sqlposh** [comment]
Mental note, adding spaces doesn't help as they seem to get scrubbed.  

But U+FFA0 HALFWIDTH HANGUL FILLER seems to work around it :)

**Comment by RickStrahl** [comment]
Ok... so I'm noticing differing behavior depending on whether the page is first rendered, or whether it's refreshed after a change is made. 

Initial load exhibits the behavior you describe. To simulate if I go into the preview and **Refresh Browser** I see the trimmed behavior. As you say - extra spaces don't help in that scenario.

If I then make a change to the document which forces the preview to refresh - then the spacing works correctly.

I suspect what's happening is some sort of timing issue, that when the page gets rendered Font-Awesome may not be fully initiailized and font-sizes not available when Mermaid starts rendering. On a refresh MM just injects the new JavaScript and then explicitly reruns mermaid on the page, but it ensures that all resources are loaded.

i'll take look and see if there's some way to delay the mermaid render slightly by running out of band (`setTimeout()`) - that might help with the initial difference.

**Comment by sqlposh** [comment]
If I right click on the preview window and select "View in Web Browser" it will exhibit the same behavior.  

![image](https://user-images.githubusercontent.com/59573341/150209243-afb5effa-f770-4447-865c-2bdd04a21e51.png)

Does that imply it's not really a timing issue or am I misunderstanding the depth of your statement?
(BTW, this isn't me being argumentative, I'm trying to play around with it and understand it more.   And love this product so much, I bought it with my own money instead of asking my employer to pick it up)

**Comment by RickStrahl** [comment]
Yeah that's because it's using the same generated script.

I've got it working on initial load now with a slight delay, but I broken something else in the process. 

Long story short I think I can fix this after all.

**Comment by sqlposh** [comment]
Does it help or hurt us that we're using the graph keyword instead of flowchart?  I think they're synonyms as far as mermaid is concerned, but I'm noticing slightly different look and feel between them

![image](https://user-images.githubusercontent.com/59573341/150215070-e6315487-bc8f-4ec5-983b-c2c80505bce0.png)

It'd b nice if the words when using flowchart keyword weren't smooshed against the top of the child node

**Comment by RickStrahl** [comment]
Those are Mermaid rendering issues. Different charts, different renderers I guess - MM doesn't do anything other than get Mermaid into the page. The rest is internal to Mermaid so if there's something that doesn't work/look right you probabliy need to file an issue with the Mermaid repo.

**Comment by RickStrahl** [comment]
Give 2.3.2 a try...

**Comment by sqlposh** [comment]
So, clicked Check for New Version from the app, it showed 2.3.2 was available.  Went to download page, it says 2.3 and now that I've run the install, it still says 2.3

**Comment by sqlposh** [comment]
No dice.  Open the file and it's still cut off

![image](https://user-images.githubusercontent.com/59573341/150220951-47373948-ee17-4aac-a187-dab6912d06e1.png)

**Comment by RickStrahl** [comment]
Can you send me your file or paste or attach it here?

**Comment by sqlposh** [comment]
emailed

**Comment by RickStrahl** [comment]
Can duplicate. Not quite sure what's going on as I can't seem to get it to render on first load no matter how long I delay - yet it works when the page is updated. So for you you should see the correct rendering if you make a change in the page and the preview is updated.

**Comment by sqlposh** [comment]
It's all good.  It's a simple enough workaround that only needs to be done once per session.  Thanks for talking it through with me!

**Comment by RickStrahl** [comment]
actually no - everytime you reactivate the tab it'll do a full refresh and that resets it again.

I've played around with this quite a bit and I can't make it work even in a plain HTML page. I can see what happens with break points:

* Content loads
* Mermaid renders and renders correctly without FontAwesome icons (fixed squares show)
* Then the icons pop in after and push the content out of its box 

But no matter how long I delay, or how I apply the Mermaid rendering it doesn't change the behavior.

I've put together a JsFiddle that basically does what MM does in a more simplified way:

https://jsfiddle.net/rstrahl/h7gL4b0m/14/

To see the problem:

* Load the page once (see cut of labels)
* Make a change and save or re-run (labels not cut off)
* Now refresh the browser
* Page re-loads completely (see cut of labels)

No matter how long the timeout I put the font-awesome icons push the text out of the graphic label space.

**Comment by RickStrahl** [comment]
One more thing, this behavior can also be seen in the Mermaid Live Editor:

![image](https://user-images.githubusercontent.com/1374013/150251738-f90f6f37-91f5-4231-a442-ac9f4313bc64.png)

[Sample on Mermaid Live Editor](https://mermaid-js.github.io/mermaid-live-editor/edit/#eyJjb2RlIjoiZ3JhcGggVERcbiAgICBBW2ZhOmZhLXJlcGx5LWFsbCBDaHJpc3RtYXNdIC0tPnxHZXQgbW9uZXl8IEIoR28gc2hvcHBpbmcpXG4gICAgQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG4gICAgQyAtLT58T25lfCBEW0xhcHRvcF1cbiAgICBDIC0tPnxUd298IEVbaVBob25lXVxuICAgIEMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdXG4gICIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJkYXJrXCJcbn0iLCJ1cGRhdGVFZGl0b3IiOmZhbHNlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6dHJ1ZX0)

Add a [fa:fa-reply-all label] into the chart and you can see the same behavior. it works upon initial editing (page is updated dynamically), but if you then reload the entire page with a Browser Refresh you see the truncated label as per image above.
