### ISSUE TITLE
Issues with unseparated Grid Tables in MM v2.3.5

### ISSUE THREAD

**Issue by jbridgy** [RickStrahl/MarkdownMonster#904]
Grid tables that are not separated by an empty line as in the following example are not handled correctly by the commands `Format Table` and `Edit Table`.
```
+----+----+
| A1 | B1 |
+====+====+
| A2 | B2 |
+----+----+
+----+----+
| A1 | B1 |
+====+====+
| A2 | B2 |
+----+----+
```
Issues:
1. The command `Format Table` applied to either table **deletes** both tables and silently writes the file [MarkdownMonsterErrors.txt](https://github.com/RickStrahl/MarkdownMonster/files/7921663/MarkdownMonsterErrors.txt).

2. The command `Edit Table` applied to either table pops up the error message
![image](https://user-images.githubusercontent.com/98041047/150702426-1d54e395-27d6-4114-b0f8-e4e7cadce6ee.png)
and writes the file [MarkdownMonsterErrors.txt](https://github.com/RickStrahl/MarkdownMonster/files/7921673/MarkdownMonsterErrors.txt).

**Comment by RickStrahl** [comment]
Fixed for next update (2.3.6+).
