### ISSUE TITLE
Right click menu is not working under the 3rd layer of the "Files" tree view

### ISSUE THREAD

**Issue by lavoiekeven** [RickStrahl/MarkdownMonster#906]
![image](https://user-images.githubusercontent.com/16387206/151223327-59f1e7ad-13dd-4626-861a-cc062ec7b659.png)

In this image, the right click menu works on file test1.md, tes2.md and test3.md but not on test4.md.

The menu just don't shows. You also can't rename the file test4.md within Markdown monster.

**Comment by RickStrahl** [comment]
Whoa - good catch. 

Not sure why that would be - logic for each level is pretty much the same, so very odd that this isn't working three levels down. Will take a look.

**Comment by RickStrahl** [comment]
Fixed and updated in 2.3.6.1+.

**Comment by lavoiekeven** [comment]
Good job!
