### ISSUE TITLE
Make upgrading easier 

### ISSUE THREAD

**Issue by Mehul** [RickStrahl/MarkdownMonster#91]
One feature that I'd love is a 'check for updates' or automatically notify me when there is a new update and then download that new set of packages, close MM, update it, and reopen it. And I'd like this for the portable version too. :)

**Comment by RickStrahl** [comment]
Uh - MM already checks every 7 days and there's Help -> Check for Updates.

The installer is small so it's better to do a full install. There are too many problems with in-app download install and virus scanners to do this in a more automated fashion and frankly I prefer to let the user have control over the update process (it takes you directly to the download page).

**Comment by Mehul** [comment]
Fair enough. I mostly was looking to avoid going to the page, download zip, and extract process.

**Comment by RickStrahl** [comment]
The default install isn't a Zip file. Yeah it's an extra step but it outweighs the issues that in app installs cause.

Original version had it but as I said it got flagged by AV so people were complaining updates aren't working. By explicitly downloading and installing the full installer can take care of things that the app on its own can't.

For portable - yeah more work, but then again why are you running the portable if you are doing the frequent updates? :-)
