### ISSUE TITLE
Feature Request  - In Place Preview/Live Preview

### ISSUE THREAD

**Issue by rbharathkumar** [RickStrahl/MarkdownMonster#910]
Hi,
Thank you for all the hard work on the wonderful editor.
To me no other markdown editor looks so good on Windows as this one does...
Let alone coming close on the long feature list...

Would like to understand if Markdown Monster has an in place/Live preview feature like the one available in Typora (Not my intention to compare - just as an example)
It would be of immense use for devices with small screens say 13 inch netbooks/laptops, where having an editor pane and a preview pane alongside each other is a little difficult to manage.

Thank you..

**Comment by RickStrahl** [comment]
No that's not available. MM is a code editor not a visual editor and there are no plans to provide that functionality.

The whole point of a tool like MM is that visual HTML editors are always a compromise that make many things difficult to represent properly in Html. I understand why people want it, but MM is not a tool that will support this.
