### ISSUE TITLE
Unexpected empty node in Mermiad stateDiagram with a choice, fork or join

### ISSUE THREAD

**Issue by sqlposh** [RickStrahl/MarkdownMonster#911]
## SUMMARY
There's an unexpected empty node in a Mermaid stateDiagram which has a `<<choice>>` directive.  This isn't seen in the live mermaid editor, nor in VSCode.  

Normally I would chalk this up to a Mermaid bug, but I'm only seeing it in MM. 

## MM has additional empty node in the top right of the diagram
![image](https://user-images.githubusercontent.com/59573341/154162607-a2d991d7-0f1c-42f3-a680-adb3f44d968c.png)

## VSCode does not have this
![image](https://user-images.githubusercontent.com/59573341/154161975-cf621c5e-f509-4b6d-ad92-e43176c9c092.png)

## Live editor does not have this
![image](https://user-images.githubusercontent.com/59573341/154162296-594b8ab8-33ed-4e5f-a179-8609e3365a42.png)

Link to the live editor [LINK](https://mermaid-js.github.io/mermaid-live-editor/edit/#pako:eNpNjk0LwjAMQP9KCIyCbBePZQwE50kUnB7EeihtdIWtk60VZOy_230I5pQ8HuT1qBpNyDGKemON49AzV1JNjAPT9JC-cmyAIYqE7Zx0tDXy2co6ea-FhTATBAVpqsrGKMqymd9Wd0iSDNR8quk4ny45cLhS9093m30x4sNRWIyxpraWRoemfrQETj0CeViXIoHCDkH1Lx2-59q4pkX-kFVHMUrvmuJjFXLXevpJS_diDV-3xE2v)

I'm guessing it has something to do with the double `<<` and `>>`?  Incidentally, if I don't use  `<<choice>>` and  just use normal nodes, this doesn't show up.
![image](https://user-images.githubusercontent.com/59573341/154163808-5b0d5ffc-19f1-4d16-8485-66d0124eea0f.png)

It looks like it also happens with `<<fork>>` 
![image](https://user-images.githubusercontent.com/59573341/154163242-3cb83335-4921-41b7-8ba3-6d4795b2ee02.png)

... and `<<join>>`
![image](https://user-images.githubusercontent.com/59573341/154163631-4d05326d-5d49-4088-b3a4-f7b62004193c.png)

**Comment by RickStrahl** [comment]
Looks like it's a problem with the `<< >>` syntax - most likely encoding. Did you try this with  the triple tick syntax instead (like in your Code example)?

**Comment by RickStrahl** [comment]
So digging into this it looks like the HTML block that is generated has to be HTML encoded.

MM now generates an unencoded block:

```html
<div class="mermaid">
%%{init: {'theme': 'default'}%%
stateDiagram-v2
	state c <<choice>>
	[*] --> c
	c --> TRUE : Yes
	c --> FALSE : NO
</div>
```

which produces the extra node. If changed to this:

```html
<div class="mermaid">
%%{init: {'theme': 'default'}%%
stateDiagram-v2
	state c &gt;&gt;choice&lt;&lt;
	[*] --> c
	c --> TRUE : Yes
	c --> FALSE : NO
</div>
```

then it works.

This should be an easy fix - as long as that doesn't break something else :smile:

**Comment by sqlposh** [comment]
Interesting...

Yeah, the triple tick was the first thing I tried, I think I even started to mention that in my issue text, but for some reason I trimmed that out.  Either way, it had the same effect, with or without.

Hopefully this only fixes and doesn't unfix something else 😄

**Comment by RickStrahl** [comment]
This is fixed in the latest update ( 2.3.16+)

**Comment by sqlposh** [comment]
So if I use the DIV syntax, it's still there in v2.3.16
If I use the triple-tick syntax, it looks like it should

This is expected behavior, yes?  Your earlier statement about needing to encode any of that ourselves when using the DIV syntax is kinda implying that the triple-tick syntax is the preferred syntax? 

I've been using the DIV syntax because that's what the default mermaid snippet you have uses, plus I prefer the white formatting given to the DIV code than the light-blue formatting of the tick syntax, but I'll use whatever works :) 

Thanks!

**Comment by RickStrahl** [comment]
Correct. triple syntax encodes, `<div>` syntax does not as it's raw HTML that you have to provide. The `<div>` syntax should follow exactly what the Mermaid documentation shows (ie. encoded text - which I don't remember seeing mentioned in the docs incidentally 😄.

The default snippet shows both, but it's been updated either way.

Official documentation is here:

https://markdownmonster.west-wind.com/docs/_5ef0x96or.htm
