### ISSUE TITLE
MarkdownMonster source missing

### ISSUE THREAD

**Issue by anders-eriksson** [RickStrahl/MarkdownMonster#912]
I just cloned this repo and it doesn't contain the source for MarkdownMonster!

Has it been removed or moved to another repo?

**Comment by gep13** [comment]
@anders-eriksson did you see the information here:

https://github.com/RickStrahl/MarkdownMonster#source-code-no-longer-available-here

**Comment by anders-eriksson** [comment]
No, I missed it!
Sorry!

**Comment by RickStrahl** [comment]
Source code access is available by request...

https://markdownmonster.west-wind.com/purchase#SourceCode
