### ISSUE TITLE
Toc generator Addin refuses to install

### ISSUE THREAD

**Issue by warbe-maker** [RickStrahl/MarkdownMonster#914]
I tried to install the TOC generator. It claims version 1.99.99 or later and refuses to install. My installed version is 2.3.16 !!!
Any help is very much appreaciated.

**Comment by andermikael** [comment]
Isn't the TOC generator more or less deprecated?
Included in Markdown Monster you have Insert document outline
Select Document Outline in the tree sausage menu and up to the right there is a small button for inserting the outling into your document.

[Document outline](https://andis59.se/images/MarkdownMonster-TOC.jpg)

**Comment by warbe-maker** [comment]
Thank you very much for this quick reply. I'll do it in the future as suggested.
RegardsWalter
-- 
 Gesendet mit Tutanota, der sicheren & werbefreien Mailbox. 



19. Feb. 2022, 14:25 von ***@***.***:

**Comment by RickStrahl** [comment]
As @andermikael pointed out, most of the TOC addin features are integrated into the bookmark sidebar. I think you'll find what you need there.

The addin is a third party addin, so if you do go that route, post an issue on that GitHub repo.

**Comment by RickStrahl** [comment]
As @andermikael pointed out, most of the TOC addin features are integrated into the bookmark sidebar. I think you'll find what you need there.

The addin is a third party addin, so if you do go that route, post an issue on that GitHub repo.

**Comment by warbe-maker** [comment]
Dear Rick,

I just like to mention that I so often miss an Undo/Redo feature in MarkdownMonster. It happens every now and then that I have to spend some time to re-type complete paragraphs. On the other hand I would not miss at all the table editing support.
Thank you very much for the great product.

Best regardsWalter -- 
 Gesendet mit Tutanota, der sicheren & werbefreien Mailbox.
