### ISSUE TITLE
PlantUml

### ISSUE THREAD

**Issue by dinandv** [RickStrahl/MarkdownMonster#916]
Hi,

I really love MarkdownMonster!

There is, however, something I really miss (or can't find yet): rendering plantuml

I frequently include uml diagrams in my markdown files using plantuml. In vscode that works perfect, but as a markdown editor I prefer MarkdownMonster above vscode

Do you have any plans to include support for this?

![Image 408](https://user-images.githubusercontent.com/20665162/155726139-53085bfd-cb10-4042-b46a-44d9ac7ae6f8.png)
s

**Comment by RickStrahl** [comment]
No, but it's possible to create an addin with a render extension...

[Create a Markdown Monster RenderExtensions in an Addin](https://markdownmonster.west-wind.com/docs/_5i30sba89.htm)

**Comment by dinandv** [comment]
Thanks for your answer, I'll look into it!

**Comment by StevenTCramer** [comment]
Did someone make an addin?

**Comment by RickStrahl** [comment]
I'm going to take a look. 

It looks like it's relatively easy to use the PlantUml server to generate images and embed them. 

My concern originally was with requirements for libraries loading, but if there's an easy way to get this to render without dependencies it's easy enough to implement as a RenderExtension.

**Comment by RickStrahl** [comment]
Implemented in 3.3.5.

* [More info](https://markdownmonster.west-wind.com/docs/_6x60qvpvi.htm)

https://github.com/RickStrahl/ImageDrop/blob/master/MarkdownMonster/PlantUML.gif?raw=true
