### ISSUE TITLE
mmcli markdowntohtml hangs for some reason

### ISSUE THREAD

**Issue by djfm501** [RickStrahl/MarkdownMonster#917]
The mmcli vesion is 2.3.17
The input file is t.md:

# This is a test markdown file

asdfsa nsdfnsdf sdf 
234 sdr

The command use:
mmcli markdowntohtml -i t.md -o t.html

All I see is:
--------------------------------
Markdown Monster Console v2.3.17
--------------------------------
Command: markdowntohtml

I have to do a ^C to abort and t.html is not created.

I tried creating a dummy t.html.  mmcli still hung and the dummy t.html was not updated.

I brought up markdown monster, opened t.md and did a file->save to>html and that worked.

Is there something I am missing?

David (DJFM501)

**Comment by RickStrahl** [comment]
I see that too. That's definitely a bug. I'll take a look.

**Comment by RickStrahl** [comment]
Fixed. 2.3.17.4 and later.

This turned out to be a strange issue related to async processing from the 2.0 conversion code. Ended up explicitly loading the document synchronously and that works fine now. Thanks.
