### ISSUE TITLE
Please Add Functionality to Save Images and Files to Cloud Hosting Providers

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#92]
Please add functionality to save files and images to the commonly found Cloud hosting providers as OneDrive, GDrive, DropBox, and images to any image sharing services like imgur, Flikr, Photobucket, etc.

**Comment by RickStrahl** [comment]
Uh - you can save to OneDrive, DropBox, GoogleDrive etc. just by saving to those folders on your computer. There's nothing special that has to happen to make that work the save dialog will let you save those files.

For other providers that require uploads it's more complicated as there's no single protocol. This is perfect for Addins for the providers you use. I've created the save Images to [Store Images to Azure Blob Storage Addin](https://github.com/RickStrahl/SaveToAzureBlob-MarkdownMonster-Addin) that does what you ask for Azure storage. Other providers will need a custom addin.
