### ISSUE TITLE
`Quote Text` (Ctrl+Q) appends empty line in MM v2.3.18 (and before)

### ISSUE THREAD

**Issue by jbridgy** [RickStrahl/MarkdownMonster#920]
The command `Quote Text` (Ctrl+Q) appends an empty line.
Example:
Before applying Ctrl+Q to line 2:
```markdown
line 1
line 2
line 3
```
After:
```markdown
line 1
> line 2
> 
line 3
```

**Comment by RickStrahl** [comment]
One more thing that I just noticed too: A quote block followed by a non-quote prefixed line that isn't separated by a blank line is treaded as part of the block:

![image](https://user-images.githubusercontent.com/1374013/157317862-910f5e31-d3f5-422f-a707-6d99d8b9b7a6.png)

will render as one line as Markdown treats linefeeds as continuations.

**Comment by RickStrahl** [comment]
I did add a changes however to make some scenarios more natural:

* If you don't have a select and press Ctrl-Q - MM now selects the entire line and adds the quote mark at the beginning and no linefeed is added
* If you select a single line no Linefeed is added

The former behavior is a definite improvement. Not quite sure if the no linefeed for single lines is the right call for consistency.

Thoughts?

**Comment by jbridgy** [comment]
> That's not what MM does. It creates this output from the second line selection and `ctrl-q`:
> 
> ```gfm
> line 1
> > line 2
> 
> line 3
> ```
> 
> This is by design as the quote is meant to be a block, so there's a line break after it...

My description was correct but incomplete because there several similar cases. I described case 1 and you described case 2.
```markdown
## Case 1
Before applying Ctrl+Q when line 2 **including** line break is selected:

line 1
line 2
line 3

After:

line 1
> line 2
> 
line 3

## Case 2
Before applying Ctrl+Q when line 2 **excluding** line break is selected:

line 1
line 2
line 3

After:

line 1
> line 2

line 3

## Case 3
Before applying Ctrl+Q when cursor is on line 2 at column 1 without selection:

line 1
line 2
line 3

line 1
> line 2
line 3
```
