### ISSUE TITLE
Automatic unregistering every few days

### ISSUE THREAD

**Issue by jbridgy** [RickStrahl/MarkdownMonster#923]
Every few days MM automatically unregisters itself writing a message to MarkdownMonsterErrors.txt such as:

> 2022-03-08 11:10:37 - Unregister: _My License Key_
> 
> 2022-03-13 10:14:11 - Unregister: _My License Key_

My first suspicion was that this happens after updating to the latest version of MM but it turned out to be wrong.

After unregistering it is hard to use MM, of course. Every now and then MM pops up a message such as:

![image](https://user-images.githubusercontent.com/98041047/158054296-150aac40-8734-42df-9402-e6813a39a24b.png)

![image](https://user-images.githubusercontent.com/98041047/158054286-b4666c92-6627-410c-a440-672af896e83c.png)

If you continue unlicensed then the generated PDF-file will contain the following line at the bottom of the last page (or second to last page):

> created with the evaluation version of Markdown Monster

So you are actually forced to re-register immediately.

**Comment by RickStrahl** [comment]
MM checks the license about once a week. It does so a few times but if it fails on all those attempts it removes the license and it has to be reapplied. Is it possible you're not connected to the internet and you're sure your license is applied in the first place?

**Comment by jbridgy** [comment]
> MM checks the license about once a week. It does so a few times but if it fails on all those attempts it removes the license and it has to be reapplied.

I don't know any other app with the same checking policy but maybe as a small company you have to do that.

> Is it possible you're not connected to the internet and you're sure your license is applied in the first place?

Yes and yes. I'm not permanently connected to the internet but only when necessary. My license was and is currently registered (activated) for 2 of 5 machines. As mentioned above the unregistering is even logged in MarkdownMonsterErrors.txt.

Obviously I did not use MM frequently enough while I was connected to the internet. After all now I know that the reported behavior is intentional.

**Comment by RickStrahl** [comment]
Believe me when I say that I don't want to do this and I'm truly sorry to hear this is a problem for you as a registered user. 

But unfortunately we have lots of people putting in bogus information in the registry and if we don't check online we can't validate the license. This product has come from a background of 'trust users to do the right thing' and open source code for its first 3 years, which was utterly abused with a ~300:1 registration ratio and worse outright stealing and rebranding of the source open code.

If this was people trying to casually avoid paying for a license and get away with using the non-registered version that would be one thing and I'm Ok with that, but people are actively trying to work around the licensing with bogus licenses which indicates actual bad intent. Even now I see 3:1 bogus license count in my logs!

The license check is done on startup and it does so in the background several days before it expires so there's a bit of leeway between the lookup failing and the license being removed as it re-checks.

This is to say I'm sorry but I know of no other way than online validation to make this work better...
