### ISSUE TITLE
MM 2.4 does not support nested blockquotes anymore

### ISSUE THREAD

**Issue by jbridgy** [RickStrahl/MarkdownMonster#924]
MM 2.4 does not support [nested blockquotes](https://www.markdownguide.org/basic-syntax/#nested-blockquotes) anymore as an overreaction to issue #920.
This unfortunate change is also stated in the [MM Changelog](https://github.com/RickStrahl/MarkdownMonster/blob/main/Changelog.md).

**Comment by RickStrahl** [comment]
I'm not sure what you mean by not supported. You can certainly enter nested blockquotes and render them correctly.

What's changed is that you can't create them with the quote tool. I think that's a fair trade off for the improved behavior for the much more common single quote case.

Do you actually use nested quotes? Seems like an odd feature to begin with.

**Comment by jbridgy** [comment]
> I'm not sure what you mean by not supported. You can certainly enter nested blockquotes and render them correctly.
> 
> What's changed is that you can't create them with the quote tool. 

You are right.

> I think that's a fair trade off for the improved behavior for the much more common single quote case.

I don't know exactly what you mean but my feeling is that preventing a function (in this case the nesting button) from being reapplied is not a good idea.

> Do you actually use nested quotes? Seems like an odd feature to begin with.

Yes, occasionally I need a small blockquote within a large blockquote.

**Comment by RickStrahl** [comment]
Noted, but not adding this functionality for this edge case. 

In most cases what people would want is to be able to select a block of text and get a single block quote. If single quotes already exist in there they would remain and other lines would add them.  Worst case for nested quotes would be that the tool essentially does nothing...
