### ISSUE TITLE
Single-Click on a File in FileBrowser shows as Files Copy???

### ISSUE THREAD

**Issue by realB12** [RickStrahl/MarkdownMonster#927]
Hi Rick, 

Have Version 2.4 under Windows 64 Bit Pro. 

When single-clicking on a file in the FileBrowser im getting a confirmation message that files and folders are copied (see pic)?? 

This on top of the issues or being related to the issue I have reported on #926. 

<img width="204" alt="image" src="https://user-images.githubusercontent.com/3463881/158330797-099c1b4b-b89a-45f4-8e0b-5eb0a3509f26.png">

**Comment by RickStrahl** [comment]
I'm guessing what's happening is that you're moving the mouse a bit while clicking and releasing which initiates a drag and drop operation. Are you using a mouse pad that's overly sensitive and moving the mouse cursor? I don't see this unless I explicitly move the mouse around a bit to go beyond the drag initiation zone.

I can widen that zone out a bit, but I'm using the Windows configured measures for this now...

**Comment by RickStrahl** [comment]
I'm guessing what's happening is that you're moving the mouse a bit while clicking and releasing which initiates a drag and drop operation. Are you using a mouse pad that's overly sensitive and moving the mouse cursor? I don't see this unless I explicitly move the mouse around a bit to go beyond the drag initiation zone.

I can widen that zone out a bit, but I'm using the Windows configured measures for this now...

**Comment by RickStrahl** [comment]
Ok so I took a look at the code for this and noticed that the single click operation wasn't properly updating the mousepointer for drag detection. So it looks like any movement would trigger the drag operation and potential subsequent drop attempt. I've fixed that and that should certainly help. It'll be in the next update.

**Comment by RickStrahl** [comment]
Give this a try in 2.4.2+

**Comment by realB12** [comment]
> re you using a mouse pad that's overly sensitive and moving the mouse cursor?

Yeah, I am using a Logitech GS02 Gamemouse on a large screen. I have reduced the sensitivity now and the situation has improved. Thanks for mentioning.

**Comment by realB12** [comment]
I will try next version and will let you know

**Comment by realB12** [comment]
Have tested with 2.4.4. seems to be fixed. Thanks.

**Comment by realB12** [comment]
Have tested with 2.4.4. seems to be fixed. Thanks.

**Comment by RickStrahl** [comment]
Made one additional related change here that significantly improves folder browsing of documents via single click operation. The preview windows that are displayed (in Editor mode) are now being reused rather than closing and creating a new tab. This is much quicker and happens with no flicker and the related UI jankiness.

Another side effect of the work that was done related to this bug in the last week.

Thanks! All great usability improvements. Wil be in 2.4.7+
