### ISSUE TITLE
MM 2.4 has lost the `Edit Table` and `Format Table` commands

### ISSUE THREAD

**Issue by jbridgy** [RickStrahl/MarkdownMonster#928]
The very convenient context menu commands `Edit Table` and `Format Table` are not available anymore with MM 2.4.
I reinstalled MM 2.3.18 to get them back.
Are there keyboard shortcuts for them?

**Comment by RickStrahl** [comment]
Thank you. Found the problem. Should be fixed in 2.4.3+
