### ISSUE TITLE
New document does not appear in Recent Documents

### ISSUE THREAD

**Issue by andermikael** [RickStrahl/MarkdownMonster#929]
If I open MM and I have no document in it. 
I create a new document and write somethings in it.
I save it!
I then exit MM using the right upper corner X, or if I use File
When I start MM not only isn't the document opened, but it's not in the Recent documents list!

This also happens if I open a document using double click in File Explorer.

Have I made some strange configuration or...

MarkdownMonster v 2.4.5.1
Windows 10

**Comment by RickStrahl** [comment]
Interesting - this is a bug, but I suspect this has been a bug for a long time. The recent list updates when tabs are switched and I think the scenario when the file new, then saved and it's the only file open, the tabs never get changed so it never makes it into the recent files list.

**Comment by RickStrahl** [comment]
Fixed and updated in 2.4.5.2.

Added recent file after every SaveAs operation (which is what untitled goes through). This should also fix a similar issue if you use Save As and save to a new filename - those files too weren't updated in the recent list until the tab was reactivated.

**Comment by andermikael** [comment]
Downloaded and checked!
Works perfectly

Thanks!
