### ISSUE TITLE
Drag&Drop within table editor of MM 2.4.5.2 does not work correctly

### ISSUE THREAD

**Issue by jbridgy** [RickStrahl/MarkdownMonster#931]
Drag&Drop within the table editor of MM 2.4.5.2 works correctly if the source cell and the target cell are equal.
Otherwise the dropped text is not inserted at the drop position but the content of the target cell is completely replaced by the text to be moved or copied.

EXAMPLE:
```markdown
+-------------+----------------+
| Header 1    | Header 2       |
+=============+================+
| hello world | hello universe |
+-------------+----------------+
```

If you apply the `Edit Table` command to the table above and try to move "world" in cell A1 to cell B1 at any position within "hello universe" by drag&drop then you get the following result:

```markdown
+----------+----------+
| Header 1 | Header 2 |
+==========+==========+
| hello    | world    |
+----------+----------+
```
instead of:
```markdown
+-------------+----------------------+
| Header 1    | Header 2             |
+=============+======================+
| hello world | hello world universe |
+-------------+----------------------+
```

**Comment by RickStrahl** [comment]
There's no support for table cell aware drag and drop. The editor drag and drop is purely editor (text) drag and drop. It takes the current selection and drops at whereever you put the cursor regardless of what structure is there. This is not a WYSIWYG editor :smile:

**Comment by jbridgy** [comment]
I think you missed the point.
1. This issue is about simple table cells containing a string. The "structure" of the string does not matter here.
2. When dragging the selected part of cell A to another cell B then the mouse pointer indicates an **insertion** at an exact position within the string of cell B. However the table editor does something else on dropping the selected text. It **replaces** the entire string of cell B by the selected text instead of inserting it. From my **user perspective** this is clearly a **bug**.

![image](https://user-images.githubusercontent.com/98041047/159125106-7a93ff98-0dca-4956-a7ff-37f9bbc1e226.png)

3. You are right in so far as the table editor is not a WYSIWYG editor. But WYSIWYG (What You See Is What You Get) is about formatting/rendering and this issue has nothing to do with that.
4. Regarding the **importance** of this issue I would like to point out the following:
   - Tables are the weakest feature of the Markdown language.
Therefore a table editor is the most important feature of a Markdown editor in order to actually use Markdown in many cases. Personally I bought MM because of its table editor.
   - I think MM has the best table editor compared with other Markdown editors but there is much room for improvements.
     What I miss most apart from drag and drop is the ability use as many toolbar buttons as possible to add Markdown formatting within the table editor.

It seems to me that you labeled this issue as `not a bug` because the table editor is not fully under your control. If this is the case then maybe you have no other choice currently.

**Comment by RickStrahl** [comment]
No that's not it - the table editor was recently re-written as an HTML editor. The drag and drop you see is whatever the HTML/browser view supports, not something that MM actually adds. There's no D&D support at all (at least as far as I can remember maybe I better double check what I wrote :smile:).

There's no implicit support currently for any of the markdown features of the main editor, because it's not the editor that we're running in those input fields and most of the features wouldn't work there anyway. Only a handful of Markdown Commands work.

I can see maybe adding a few shortcuts for a few simple thing like Bold, Italic, code.

The key feature of the table editor is the ability to quickly format a layout, and add/edit columns and rows somewhat interactively. The fact that Markdown is supported inside of cells is somewhat incidental and becomes utterly unmanageable outside of a tool like this at all - which begs the point to keep those features to an absolute minimum.

**Comment by jbridgy** [comment]
> ... the table editor was recently re-written as an HTML editor. The drag and drop you see is whatever the HTML/browser view supports, not something that MM actually adds.

Do you mean that the table editor of MM is actually written as an HTML page including logic written in JavaScript, unlike the main editor of MM written in C#?

> There's no implicit support currently for any of the markdown features of the main editor, because it's not the editor that we're running in those input fields and most of the features wouldn't work there anyway. Only a handful of Markdown Commands work.

Sounds interesting. Which "Markdown Commands" work in the table editor? Until now I assumed that there is none.

> I can see maybe adding a few shortcuts for a few simple thing like Bold, Italic, code.
> 
> The key feature of the table editor is the ability to quickly format a layout, and add/edit columns and rows somewhat interactively. ...

Great! A few shortcuts for commands like `Bold`, `Italic`, `Inline code`, ... would already help a lot because now you have to either enter the corresponding Markdown manually or leave the table editor, apply these commands in the main editor and finally apply command `Format Table`.

**Comment by RickStrahl** [comment]
> Do you mean that the table editor of MM is actually written as an HTML page including logic written in JavaScript, unlike the main editor of MM written in C#?

Yes the table editor - and also the main editor - are all HTML components. The table editor is an explicit component I created. The Main Editor is a Javascript editor component (ACE Editor) with heavy customizations to allow for custom functionality on top of the base editor..

> BTW: It would be nice to have keyboard shortcuts for the commands Edit Table and Format Table. These commands need to be applied all the time in documents with tables.

Yeah I think that's your particular use case - for most people this is not so common. The big problem with shortcuts is that there only so many two-chord key combinations that are available and most of them are already in some sort of use. So I don't see this happening.
