### ISSUE TITLE
Make the "search in subfolders" button persistent across sessions

### ISSUE THREAD

**Issue by deanebarker** [RickStrahl/MarkdownMonster#934]
The "Search in Subfolders" button defaults to "off." I always forget to press it, even though it's the only way I search.

Could you make this persistent, so its state is maintained across sessions?  If it was last on, have it still be on when you re-open the app?

**Comment by RickStrahl** [comment]
Added. 

2.4.9.3+

**Comment by deanebarker** [comment]
Confirmed. Wonderful. Thank you.
