### ISSUE TITLE
Suggestion: Faster Project Switching

### ISSUE THREAD

**Issue by realB12** [RickStrahl/MarkdownMonster#935]
I often have to switch between projects. 
Saving the current and opening another is many clicks. 
Question: 
a) what is the most effective way to switch between projects
b) could we eventually have an additional Tab in the sidebar for opening from a list of previously saved projects? 
c) how can I create a toolbar icon(s) that would open specific projects?

**Comment by RickStrahl** [comment]
Project support in MM is pretty minimal at this point. There's been very little interest in this feature as folders, plus a `.markdownmonster` configuration file can do most of the work without requiring an explicit project.

I'm not inclined do much work here...

As to shortcuts - how about you add your project files as favorites in a group?
