### ISSUE TITLE
Command Line Parameter for Update Check

### ISSUE THREAD

**Issue by OLLI-S** [RickStrahl/MarkdownMonster#941]
Please add a command line parameter that checks for available updates of Markdown Monster.
Currently I can do this in the menu "Help -> Check for New Version".

**Comment by RickStrahl** [comment]
Why?

**Comment by OLLI-S** [comment]
I want to keep my system up to date for security reasons.
For Markdown Monster there are many releases within a short period, so I often start Markdown Monster, check for updates and close it (I am using Markdown Monster not regularly, use it from time to time).
With such a command line parameter I can integrate the update check of Markdown Monster to a batch file that I wrote to update some apps.

**Comment by RickStrahl** [comment]
Seems to me if you're really concerned about keeping things up to date you should be using the Chocolatey or WinGet installs.

**Comment by OLLI-S** [comment]
After your posting I started using **WinGet** an indeed, there werte many app updates available.
Thank you, issue solved.

**Comment by OLLI-S** [comment]
I accidental saw, that on the Markdown Monster Website there is an update available, but un WinGet there is NO update available.
How long does it take, until updates are available on WinGet?

**Comment by OLLI-S** [comment]
The Update for Markdown Monster was released 2 days ago:

![image](https://user-images.githubusercontent.com/8037790/164093290-8303768e-cdab-4dce-ba86-63111a04fe14.png)

Currently there is no update available on WinGet:

![image](https://user-images.githubusercontent.com/8037790/164093936-461d68f7-e0fb-480c-9c21-f7130d8065ba.png)

But the package is installed:

![image](https://user-images.githubusercontent.com/8037790/164093978-38a35971-9ce0-4f0e-b9ea-0a9899c73abd.png)

Are you @RickStrahl responsible for packaging the WinGet package or is this done by WinGet?

**Comment by RickStrahl** [comment]
We don't update packages on WinGet - it's auto-deployed by the Azure bots on the WinGet repository. It'll update when they update it.

We manually update the chocolatey package, but it may also be out of date as packages go through approval each time which varies.
