### ISSUE TITLE
[Suggestion] Mode without Editor

### ISSUE THREAD

**Issue by shawnwildermuth** [RickStrahl/MarkdownMonster#942]
I'd love to have a mode that just showed the preview (turning off the code) as I use MM for notes for my videos and i'd like to just see the rendered version instead of exporting to HTML and opening a browser. Thoughts?

**Comment by RickStrahl** [comment]
There is - it's called presentation mode (click the monitor toggle icon or `F11` in the right control box). You can also set `OpenInPresentationMode` to have MM open in this mode.

But there's no permanent mode that acts just like a document browser - it only works on initial document and then you'd have to `F11` to flip into presentation mode.

Another new related feature is that you can have the file browser show only a rendered preview. Setting `MarkdownPreviewMode`.

**Comment by shawnwildermuth** [comment]
Actually, the F11 is all I need. Just didn't see it. Perfect. I'm closing this.
