### ISSUE TITLE
Preview doesn't render images w/o title attribute

### ISSUE THREAD

**Issue by Schelmenzunft** [RickStrahl/MarkdownMonster#945]
This is a correct md image reference but will not be rendered in preview:

```markdown
![Unknown Icon](../img/IcoUnknown16.png)
```

You have to add at least an empty title attribute to it:

```markdown
![Unknown Icon](../img/IcoUnknown16.png "")
```

Only then it's displayed in preview.

**Comment by RickStrahl** [comment]
No that's not correct. I have **never** used extra title attribute and images render just fine. 

![image](https://user-images.githubusercontent.com/1374013/164399225-501e2f21-f79e-413d-9402-76ec54183524.png)

There must be something else going on.

**Comment by Schelmenzunft** [comment]
Seems to have been a temporary local issue. After saving the files and reopening MM everything is rendered as expected.

**Comment by RickStrahl** [comment]
Ah I think I know what the problem is:

**When you have a file that is `Untitled` there's no relative path** you can relate to, so relative paths don't work - **until you save the file and give it file name and location**. Once you have location you can use relative paths.

**Comment by Schelmenzunft** [comment]
Sounds like you found it. Will take a closer look before submitting another issue.





AKG Software Consulting GmbH
Franz-Josef Knelangen


Uhlandstraße 12
79423 Heitersheim
Germany

Tel.: +49 (0)7634 5612-611
Fax: +49 (0)7634 5612-300
E-Mail: ***@***.***
Internet: www.akgsoftware.de<http://www.akgsoftware.de>

Geschäftsführer: Dipl.-Ing. Artur K. Günther, Dipl.-Ing. Arno Brüggemann, Dipl.-Ing. (FH) Bernhard Feser, Dipl.-Ing. Jens Günther
Sitz der Gesellschaft: Heitersheim, HRB 310383 (Amtsgericht Freiburg)

Von: Rick Strahl ***@***.***>
Gesendet: Donnerstag, 21. April 2022 09:42
An: RickStrahl/MarkdownMonster ***@***.***>
Cc: Franz-Josef Knelangen ***@***.***>; State change ***@***.***>
Betreff: Re: [RickStrahl/MarkdownMonster] Preview doesn't render images w/o title attribute (Issue #945)



Externe E-Mail: Vorsicht beim Öffnen von Anhängen und Klicken auf Links!


Ah I think I know what the problem is:

When you have a file that is Untitled there's no relative path you can relate to, so relative paths don't work - until you save the file and give it file name and location. Once you have location you can use relative paths.

**Comment by Schelmenzunft** [comment]
Hi Rick,

thought the problem is gone but today I passed some MD example files over to my colleague. He opened it, the referenced bitmaps were there but were not displayed. Moving the files form network to local drive and restarting MM didn’t help.

Any clue where to look further?

Greetings,
Franz-Josef





AKG Software Consulting GmbH
Franz-Josef Knelangen


Uhlandstraße 12
79423 Heitersheim
Germany

Tel.: +49 (0)7634 5612-611
Fax: +49 (0)7634 5612-300
E-Mail: ***@***.***
Internet: www.akgsoftware.de<http://www.akgsoftware.de>

Geschäftsführer: Dipl.-Ing. Artur K. Günther, Dipl.-Ing. Arno Brüggemann, Dipl.-Ing. (FH) Bernhard Feser, Dipl.-Ing. Jens Günther
Sitz der Gesellschaft: Heitersheim, HRB 310383 (Amtsgericht Freiburg)

Von: Rick Strahl ***@***.***>
Gesendet: Donnerstag, 21. April 2022 09:42
An: RickStrahl/MarkdownMonster ***@***.***>
Cc: Franz-Josef Knelangen ***@***.***>; State change ***@***.***>
Betreff: Re: [RickStrahl/MarkdownMonster] Preview doesn't render images w/o title attribute (Issue #945)



Externe E-Mail: Vorsicht beim Öffnen von Anhängen und Klicken auf Links!


Ah I think I know what the problem is:

When you have a file that is Untitled there's no relative path you can relate to, so relative paths don't work - until you save the file and give it file name and location. Once you have location you can use relative paths.
