### ISSUE TITLE
Suggestion: Restructure Document in Document Outline by Drag&Drop

### ISSUE THREAD

**Issue by jbridgy** [RickStrahl/MarkdownMonster#949]
Would be nice when we could restructure the document by drag&drop within the Document Outline as it is possible within the Navigation pane of Word and LibreOffice Writer, that is:

1. Change order of headings (including their bodies).
2. Demote heading (eg: H1 -> H2)
3. Promote heading (eg: H2 -> H1)

**Comment by RickStrahl** [comment]
You asked this before and the answer hasn't changed. Won't add due to too many potential failure points in moving code around - the Markdown document model isn't strong enough to support this reliably.

**Comment by jbridgy** [comment]
> Won't add due to too many potential failure points in moving code around - the Markdown document model in MarkDig isn't strong enough to support this reliably.

It's a pity. Would it help to forward this suggestion (in adjusted form) to [Markdig](https://github.com/xoofx/markdig/issues)?

> You asked this before and the answer hasn't changed.

Well, I "asked this" in a related suggestion of @realB12 (see link above) and two days later I created this suggestion because @realB12 asked me to do so. Until now you did not respond to the original suggestion.
