### ISSUE TITLE
Suggestion - Add in an AsciiDoc parser

### ISSUE THREAD

**Issue by alanrwest** [RickStrahl/MarkdownMonster#95]
AsciiDoc is another markup variant like Markdown, but offers a lot more features in terms of formatting, output, etc. Would it be possible to add in an AsciiDoc parser into the application? There is a Javascript based parser available here: https://github.com/asciidoctor/asciidoctor.js (I believe that the Atom AsciiDoc previewer uses it: https://github.com/asciidoctor/atom-asciidoc-preview)

**Comment by ArthurZ** [comment]
I wish also [Textile ](https://txstyle.org/) could be supported. Besides, I worked with [ReStructuredText](http://docutils.sourceforge.net/rst.html) which I found a tad more difficult to use, but in return it comes with more power than Markdown.

**Comment by RickStrahl** [comment]
These formats are too obscure at this point to warrant adding as a feature. 

We may look at this again in the future...
