### ISSUE TITLE
Interactive Table Editor - Load From CSV - Can't Open A File or File is Empty

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#953]
Using Interactive Table Editor - Load From a CSV file. The file is a comma-delimited and is of 250KB in size. Has "s as text qualifier.
However, MM does not load it. I see a promptly vanishing error message in the bottom of the dialogue: Can't Open File `c:\tmp\ABC.csv` or File is Empty.
The file gets opened in Excel via data import w/o errors.

**Comment by RickStrahl** [comment]
250k in size and you want to load this into Markdown? 

MM uses a CSV component to load the CSV, so we're bound by the limitations of that tool. 

For starters we need a sample. Is the size the problem? The format? Where is the CSV?
