### ISSUE TITLE
Unable to resize Console Add-in

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#956]
I would love to use the console add-in, alas, it appears to obstruct everything on the screen, yet lacks the usual Window controls.
This is what I see:
![image](https://user-images.githubusercontent.com/701808/167322528-a4d5778d-54d5-4ff7-9d5b-06fcf87618b4.png)

**Comment by RickStrahl** [comment]
Submit this to the addin repository, please:

https://github.com/RickStrahl/Console-MarkdownMonster-Addin
