### ISSUE TITLE
[Feature Request] Add support for `Revealjs` presentations

### ISSUE THREAD

**Issue by rleyvasal** [RickStrahl/MarkdownMonster#958]
It would be great to be able to create markdown presentations with `MarkdownMonster` and [revealjs](https://revealjs.com/)

The following implementations provide a way to create `revealjs` presentations with markdown.
[vscode-reveal](https://marketplace.visualstudio.com/items?itemName=evilz.vscode-reveal)
[quarto revealjs](https://quarto.org/docs/presentations/revealjs/)

**Comment by RickStrahl** [comment]
This is not within the scope of Markdown Monster's core editor application.

But if anybody is interested they can build an Addin that supports this. I'm not that familiar with reveal.js but I think most of this can be done via a render extension.
