### ISSUE TITLE
Ctrl-W to close current tab

### ISSUE THREAD

**Issue by slolife** [RickStrahl/MarkdownMonster#96]
I'd like to suggest that you make Ctrl-W close the current tab, following normal close-tab workflow (like prompting for save, etc.).

**Comment by RickStrahl** [comment]
Added

16ca5b64e69b3bb26a03a0bc15ca51e271b93cc4

**Comment by ArthurZ** [comment]
In some OS implementations it is Ctrl - F4. Has to support it, too.

**Comment by punker76** [comment]
I think Ctrl-W is enough and IMO the best for this, cause it needs only one hand :-D

**Comment by RickStrahl** [comment]
Yeah but it's easy enough to add and Arthur is right it's a Windows convention for closing child Windows maybe more so than Ctrl-W (never used that - Ctrl-F4 is what I would use but tend to use tab close). 

So now we have:

* Ctrl-W
* Ctrl-F4 (added)
* Middle Click
* Close button on Tab

That oughta be enough dammit :-)
