### ISSUE TITLE
Bug: `Edit Table` keeps trailing empty lines in grid table

### ISSUE THREAD

**Issue by jbridgy** [RickStrahl/MarkdownMonster#962]
`Edit Table` of mm v2.5.12 keeps trailing empty lines within cells of a grid table.

Original grid table:
```markdown
+----------+----------+
| Header 1 | Header 2 |
+==========+==========+
| 1        | 1        |
| 2        | 2        |
| 3        |          |
| 4        |          |
+----------+----------+
```
![image](https://user-images.githubusercontent.com/98041047/171572306-fd39b82e-d261-4635-b6cd-2c5a45daab5b.png)

After deleting line 4 in cell A2 using `Edit Table`:

![image](https://user-images.githubusercontent.com/98041047/171572532-2d6d4efa-7b67-46c6-9802-f349a1e221d2.png)

```markdown
+----------+----------+
| Header 1 | Header 2 |
+==========+==========+
| 1        | 1        |
| 2        | 2        |
| 3        |          |
|          |          |
+----------+----------+
```

Expected:
```markdown
+----------+----------+
| Header 1 | Header 2 |
+==========+==========+
| 1        | 1        |
| 2        | 2        |
| 3        |          |
+----------+----------+
```

**Comment by RickStrahl** [comment]
Fixed 2.5.19+

Fixed at the source when the values are pulled out of the HTML which should potentially fix a few other related issues.
