### ISSUE TITLE
HTML snippet will insert a paragraph

### ISSUE THREAD

**Issue by anders-eriksson** [RickStrahl/MarkdownMonster#965]
I have this snippet
`<div style="color:Orange;">{{await Model.ActiveEditor.GetSelection()}}</div>`

It works, BUT I get an new paragraph just before the marked selection

I have in the md file
`Select layout Remote`

I select Remote and run the snippet
I get
`Select layout <div style="color:Orange;">Remote</div>`

The HTML is
`<p>Select layout <div style="color:Orange;">Remote</div></p>`
But in the preview (and in the html) I get a new paragraph just before Remote (or after layout...)

[The resulting preview](https://andis59.se/files/Question.png)

**Why?**

MM: 2.5.1522
Windows 10 Pro

**Comment by RickStrahl** [comment]
You're inserting a `<div>`  which is an HTML block element and renders a break.

Use a `<span>` for inline text expansions.

**Comment by anders-eriksson** [comment]
Thank you very much!
