### ISSUE TITLE
Scoop installation does not work

### ISSUE THREAD

**Issue by msd** [RickStrahl/MarkdownMonster#970]
Installing markdown monster via scoop  gives an error and the installation fails.

OS: Windows 10

Command: `scoop install markdown-monster`

Error: `Can't shim 'mmcli.exe': File doesn't exist`

**Comment by msd** [comment]
The full log
```
Installing 'markdown-monster' (2.6.7) [64bit]
Loading MarkdownMonsterPortable.zip from cache.
Checking hash of MarkdownMonsterPortable.zip ... ok.
Extracting MarkdownMonsterPortable.zip ... done.
Linking ~\scoop\apps\markdown-monster\current => ~\scoop\apps\markdown-monster\2.6.7
Creating shim for 'mmcli'.
Can't shim 'mmcli.exe': File doesn't exist.
```

**Comment by RickStrahl** [comment]
We don't maintain the Scoop package - that is third party so you probably need to check with the authors of the package.

If there's a problem with the raw portable install from the download site, please repost as a new issue.
