### ISSUE TITLE
Working with two different document tabs and they all of a sudden match one tab

### ISSUE THREAD

**Issue by madmax1242** [RickStrahl/MarkdownMonster#971]
I was working with two document tabs and copying one part of one tab to another. I then realize that both tabs are the same content. Now I have had issues in the past where this would happen and I would restart MM and it would be fine. 

I would like to know how to turn on versioning so that if this happens again, I can restore from a previous version.

**Comment by RickStrahl** [comment]
Not sure I understand what you're describing here. 

Documents are isolated, so are you saying you have two different documents open and the content on both is the same? If that's the case that would be very strange and certainly something we would have heard about by now. 

If you have the same document open in multiple single instances - the content of the same documents will sync as each open tab checks for file changes of the underlying file on disk.

Please clarify what you're actually doing...

**Comment by RickStrahl** [comment]
Closing due to no further info.
