### ISSUE TITLE
TOC generator features

### ISSUE THREAD

**Issue by SMTStuck** [RickStrahl/MarkdownMonster#972]
Any chance of more features regarding the TOC generation? A couple of examples:

- It would be nice to be able to specify the indent level per TOC as opposed to a monster setting.
- Similarly, having the ability to supress a particular heading thus all children of that heading, irrespective of indent level setting.

**Comment by RickStrahl** [comment]
There's no way to really store this information since Markdown natively doesn't have support for this. So I'm not sure how this would work.
