### ISSUE TITLE
SampleMarkdown.md Text typo

### ISSUE THREAD

**Issue by DevolutionsChristine** [RickStrahl/MarkdownMonster#973]
Hello and thank you for your program. I'm exploring its functionality and found some typos in the SampleMarkdown intro text. Here is the list I found if you would like to check it out.

1. Line Continuation section:  To show all white space and returns in a document you can use View → **Show** Invisible Characters.

Should be: **Toggle**

2. Links section: You can easily link using [text](link) **sytnax**:

Should be: **syntax**

3. Images section: or by dragging and dropping images into the document from **the the** Folder Browser, Windows Explorer or a 

Remove double **the** and finish sentence Windows Explorer or a …

4. Emojiis section:  You can also embed **Emojiis** into your markdown using the Emoji dialog or common 

Should be: **Emojis**

5. Comment Blocks section: This footer is **comming** across just fine.

Should be: **coming**

6. Unordered Lists section:  This text is part of the third item. Use a soft return (shift-enter or two spaces or \) **at end of the the list** item to break the line and continue at the bullet indentation.

Should be: **at the end of the list**

7. Ordered Lists section: If you want **to** lines to break (like after the bold headers) use soft returns.

Should be: **the**

8. Indented Code Blocks section: Using **and** indented text block for code

Should be: **an**

**Comment by RickStrahl** [comment]
Thank you for the corrections. Updated.
