### ISSUE TITLE
MM 2.6.8 supporting mermaid code blocks?

### ISSUE THREAD

**Issue by JimStamperJR** [RickStrahl/MarkdownMonster#974]
Markdown Monster version - 2.6.8:This might not be an issue, but I'm not able to view/create mermaid code blocks (even after saving, exiting, and reopening - or Shift-F12 (Chrome)). **I'm not sure if I need some sort of plugin for MM?**

something like this: 
![image](https://user-images.githubusercontent.com/111536738/190450817-b43e7564-bcea-4ddb-9d01-41ad32902c79.png)

**Comment by JimStamperJR** [comment]
Sorry to waste your time ... needed to turn on the "setting" and restart MM .. my bad.

**Comment by JimStamperJR** [comment]
my bad .. it's in the product, just took a bit to find it :)

**Comment by RickStrahl** [comment]
Glad you found the documentation :smile:

For those arriving here at a later point in time, this is the documentation link that provides more info on enabling Mermaid in Markdown Monster:

[Rendering Mermaid Charts](https://markdownmonster.west-wind.com/docs/_5ef0x96or.htm)
