### ISSUE TITLE
MM mermaid - Azure DevOps wiki, VSCode plugin, and Chrome Browser Plugin

### ISSUE THREAD

**Issue by JimStamperJR** [RickStrahl/MarkdownMonster#975]
I don't know if this is a issue that can be resolved (or not) but I thought I'd share what I'm finding ....

Is the mermaid block ( in the context of a markdown file ) a international/global format ? or do I need to create 2 sets of markdown documents - one for MM and one for ADO?... just asking the question.

It appears that Azure Devops (and it's support for mermaid blocks) is using ':::' as the "key" and MM is using '```' as the key?

Works in MM
Fails in VSCODE plugin
Fails in Azure DevOps wiki
Fails in Chrome w/MD plugin

![image](https://user-images.githubusercontent.com/111536738/190485353-8f86f47a-f68c-4ea9-8c1c-a989a53f55d6.png)
 VS Azure DevOps
![image](https://user-images.githubusercontent.com/111536738/190485647-d40fcba0-29c2-488c-bf61-a3996e2e6d43.png)

**Comment by RickStrahl** [comment]
MM uses standard Mermaid and Markdown syntax and has a shortcut to embed Mermaid by using the ````mermaid` syntax instead of the more verbose HTML syntax. At the end of the day the HTML syntax is what renders the output, but the server that does the rendering has to support it.

Note that the triple tick syntax is common. GitHub supports it:

````
```mermaid
graph LR
  A --- B
  B-->C[forbidden]
  B-->D(access);
```
````

renders to:

```mermaid
graph LR
  A --- B
  B-->C[forbidden]
  B-->D(access );
```

VS Code is supposed to support Mermaid in Markdown as of late versions but I don't know offhand what the syntax for that is. Neither the MM's markdown syntax, the ::: syntax or HTML works for me.

So if you have some examples that work I can take a look and see if I can add that to the Mermaid RenderExtension that drives the conversion into in the previewer. But ultimately it seems to me that the devops portal should support the triple tick syntax which is common while I have no idea what `:::` is.


+++ Rick ---

**Comment by JimStamperJR** [comment]
Attached is MM (all formats work) and attached is the same Azure DevOps samples where the ‘=======’ divides pass (above) and fail (below).

I don’t expect MM to change as you stated, I’m thinking I’ll need to create a separate wiki location for each repo 😊 – one for MM (Which I use) and one for ADO (which we use for wikis)

Note: all the samples were taken from https://mermaid-js.github.io/mermaid/#/ (I just had to remove the blank lines in the samples – not sure why?)

FYI: another pet peeve (of mine) … might be a NEATO thing for ADO but if you use a #(number) in a MD it automajically injects a link to a ADO task.. just thought I’d share.

Thanks / Wado,
Jim Stamper
Siemens Digital Industries Software
Got Issue? GTAC<https://support.sw.siemens.com/en-US/support-case/open>

**Comment by RickStrahl** [comment]
Not sure what I'm looking for here, but you can't attach to a reply email on a GitHub issue :smile: You can drop a file into the issue though on GitHub.

**Comment by JimStamperJR** [comment]
I don’t expect MM to change as you stated, I’m thinking I’ll need to create a separate wiki location for each repo 😊 – one for MM (Which I use) and one for ADO (which we use for wikis)

Note: all the samples were taken from https://mermaid-js.github.io/mermaid/#/ - can't take credit for any of it (I just had to remove the blank lines in the samples – not sure why?)

MM versions of mermaid blocks..(they also work in VSCODE w/proper extension added)
[markdownWITHmermaid.md](https://github.com/RickStrahl/MarkdownMonster/files/9584234/markdownWITHmermaid.md)

ADO versions of mermaid blocks... (ADO does not appear to support all types, I added a '===' string to separate the supported from the unsupported)
[markdownWITHmermaidonAzureDevOps.md](https://github.com/RickStrahl/MarkdownMonster/files/9584242/markdownWITHmermaidonAzureDevOps.md)

MM - MarkdownMonster
ADO - Azure DevOps support for Markdowns in wikis
