### ISSUE TITLE
Using Git/Pull is not updating the local repo with changes in the remote repo

### ISSUE THREAD

**Issue by JimStamperJR** [RickStrahl/MarkdownMonster#976]
Below is the 4 steps I use to "attempt" to update my local copy of a file that was changed in remote repo:

Just a simple case, where I'm making the MODs, but with a team ... that's usually not the case.
1. MOD file in the remote repo (Azure DevOps Repo)
2. Commit those changes
3. In MM, perform a pull 
4. In MM, the file should be updated?

**Note: If I go to a cmd window and execute git pull - the file is updated**

Q: Do I have something configured wrong? I don't know that I configured anything special for MM?

Thanks for any info!

![image](https://user-images.githubusercontent.com/111536738/191556199-26fb84bf-b039-4070-923d-af16e1816026.png)

**Comment by RickStrahl** [comment]
There shouldn't be anything special to configure. Assuming the repo has its remote properly configured and can pull that should just work (looks like it is since you can pull from cmd).

When you pull do you see any sort of error message in the status bar of the Git window?

**Comment by JimStamperJR** [comment]
First: I apologize for these questions (I'm in no way a git SME... and I typically use VSCODE for most of my git commands: pull, push, commit, mv)

I don't see any message other than "**Changes have been pulled from the remote origin**"

![image](https://user-images.githubusercontent.com/111536738/191564891-b430053d-297b-4086-bb59-4ba637471138.png)

**Comment by RickStrahl** [comment]
If you have the file open in your editor and it has changes when you pull the changes don't show in the editor - you should get notified when you save that the file on disk differs. If the file is unchanged in the editor ti should update.

There are two issues here:

* Does the pull work?
* Does the editor updated if the document is loaded

Which is it? To check the former close the document in MM and just do the change only/pull  and see what you get when you re-open the file. For the latter repeat above but have the document open in the editor with a) no active changes and b) with active changes.

**Comment by JimStamperJR** [comment]
Test 1:
1. MOD file outside of MM and commit
2. exit MM (no active changes in MM)
3. git pull (DOS cmd)
4. start MM and file is updated

Test 2:
1. MOD file outside of MM and commit
2. start MM (no active changes in MM)
3. git pull (in MM)
4. file is not updated

Test 3:
1.  MOD file outside of MM and commit
2. start MM (make a change to a file)
3. git pull (in MM)
4. The same errors I get when I attempt this from a DOS shell (I end up using a combination of git reset --hard, git pull , git stack and git pop 
 
![image](https://user-images.githubusercontent.com/111536738/191576081-4ac1ecd1-e40b-4797-a88e-e495fa708f85.png)

**Comment by RickStrahl** [comment]
I've fixed the issue - the problem was that the branch selection was being ignored and the pull tried to always pull from master.  There was also an issue with the error message being ignored which has also been fixed. 

This should work now or at minimum you should see error information in the status bar...

Give the latest pre-release update  a try (2.6.9.3)
