### ISSUE TITLE
Hello! 2.6.9.x often freezes at startup in Windows 10, and the program crashes

### ISSUE THREAD

**Issue by zhouxinghong** [RickStrahl/MarkdownMonster#979]
Hello! 2.6.9.x often freezes at startup in Windows 10, and the program crashes
Hello! 2.6.9.x often freezes at startup in Windows 10, and the program crashes
System: Windows 10 19044 x64 RAM 10GB CPU i5 3210

**Comment by zhouxinghong** [comment]
![2022-09-28_2xxxx](https://user-images.githubusercontent.com/54253524/192787852-780a20d4-cfe9-4822-af01-458b73f2de9e.png)

**Comment by RickStrahl** [comment]
Not much to go on.

Can you post the relevant content of your log files (remove any license information)...

**Comment by zhouxinghong** [comment]
The program seems to start normally again now. There is no more freezing and crashing.
Another question? 
How to set up automatic line breaks for blocks of code.
