### ISSUE TITLE
Hello! Paste the network image into the note in .png format, and the size of the image increases a lot, which is not the size of the original image on the network. Win 10 19044x64 2.9.9

### ISSUE THREAD

**Issue by zhouxinghong** [RickStrahl/MarkdownMonster#980]
Hello! Paste the network image into the note in .png format, and the size of the image increases a lot, which is not the size of the original image on the network.
Win 10 19044x64
 2.9.9

**Comment by RickStrahl** [comment]
Images from the clipboard aren't of any specific format so you're not copying the image file, but the bitmap.  Depending on which format you save the image in the 

* For ScreenShots, clip art, non-photos use `.png`
* For photos or other hi-detail images use `.jpg`

The default is `.png` which is optimized for screen shots etc. but works badly for photos or other hi-detail content resulting in very large image sizes. Photos can use `.jpg` and will compact much better in that format.

To choose a format just use the appropriate extension when you save the file.

MM will also create optimized files of both PNG and JPG in your saved location and you can preview and check the size in the Folder browser. MM however will not choose which to embed, but use whatever format you choose (with the default being .png) when you save the file.

**Comment by zhouxinghong** [comment]
I think there is a problem with the image generation algorithm, which needs a lot of improvement, you can refer to the image generation algorithm of similar editors such as Typroa and I have tried many editors which generate the same network image of almost the same size

**Comment by RickStrahl** [comment]
LOL... You provide no example, don't acknowledge the potential solution I offered and no details on what type of image or what you're even doing. 

It's not helpful if you actually want to see this addressed.
