### ISSUE TITLE
Expanded Edit Windows does not Left Justify Text

### ISSUE THREAD

**Issue by CheetahChrome** [RickStrahl/MarkdownMonster#981]
When the editor is expanded horizontally the edit text becomes centered in the window, creating padding before and after the main edit text.

![image](https://user-images.githubusercontent.com/1110966/192792693-cdb98c49-f79b-413e-909a-cb1dd2087f0c.png)

The expectation is that the edit box would be left justified.

Version 2.69

**Comment by RickStrahl** [comment]
This is controlled by a setting via **Centered Layout** and a max layout width:

![image](https://user-images.githubusercontent.com/1374013/192853408-d5b0a68c-d820-409f-8a04-1f1d65a39158.png)

More info here:

[Editor Padding and Centered Layout](https://markdownmonster.west-wind.com/docs/_5ed0rj891.htm)
