### ISSUE TITLE
Bug: mmcli markdowntopdf does not work in 2.6.9 anymore

### ISSUE THREAD

**Issue by a-wissing** [RickStrahl/MarkdownMonster#983]
double checked that the input file exists.
also tried 
  - rel path .\
  - abs path c: ...

cmd output:
D:\Documents\X_Browser\dokumentation\docs>mmcli markdowntopdf -i "blabla.de.verX.md" -o "blabla.de.pdf" --theme Github --page-size A4
-------------------------------
Markdown Monster Console v2.6.9
-------------------------------
Command: markdowntopdf

Unbehandelte Ausnahme: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei mmcli.MarkdownToPdfProcessor.<MarkdownToPdf>d__7.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei mmcli.CommandLine.CommandLineProcessor.<HandleCommandLineArguments>d__4.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei mmcli.Program.<Main>d__0.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei mmcli.Program.<Main>(String[] args)

**Comment by RickStrahl** [comment]
This should be fixed in 2.6.10...
