### ISSUE TITLE
Generate catalogs

### ISSUE THREAD

**Issue by cfbsks** [RickStrahl/MarkdownMonster#985]
Does MM support to auto-generate catalogs? 
I had looked around and found nothing to generate a catalog for my markdown file.

**Comment by RickStrahl** [comment]
I have no idea what you mean by 'catalog' in this context.

**Comment by cfbsks** [comment]
It means a directory of a markdown file.

**Comment by cfbsks** [comment]
![image](https://user-images.githubusercontent.com/76492899/198873402-07e092ca-9569-40e0-9d59-3abf496ef8db.png)
[src](https://www.jianshu.com/p/b0a18eb32d09)
like this

**Comment by RickStrahl** [comment]
MM doesn't auto-generate but you can manually generate it.

* From the Bookmark Sidebar

![documentoutline-toc](https://user-images.githubusercontent.com/1374013/203870619-4c8d2941-9bf5-499a-8f5f-de7b48cc2cbe.gif)

**Comment by cfbsks** [comment]
Alright thanks
