### ISSUE TITLE
Vertical scroll-bar inconvenience

### ISSUE THREAD

**Issue by jovibor** [RickStrahl/MarkdownMonster#988]
Good day,

In Chrome (as an example), when window is maximized I can simply put mouse cursor to the right screen side and still be able to use a scrollbar.

In MM it's impossible. 
Scrollbar active area has little indent, so I must point a cursor *exactly* to it. Aggravates the situation the fact that MM's scrollbars are quite thin, it's harder to hit.

Can scrollbars behavior be changed to correspond Chrome-like style, or at least be a bit wider, may be through some option?
Thanks.

**Comment by jovibor** [comment]
> I suppose most people use the scroll wheel these days to navigate, not the scrollbar.

This is not true. Especially for huge documents with dozens of "screens" of information.

> If you want the default wide and ugly scrollbar you can remove those two tags altogether and you get back the standard banded Chrome scrollbar.

Thanks, this worked.
But still, even this "ugly" scroll-bar has this nasty indent that causes this whole inconvenience in the first place.🍻

**Comment by RickStrahl** [comment]
Not sure what you mean by 'indent'. The default toolbar is what Chromium uses natively.

**Comment by jovibor** [comment]
> Not sure what you mean by 'indent'.

Put the mouse cursor maximum to the right screen-side. Try to grab a scroll-bar with mouse click. It doesn't work/not grabs.
With Chrome it works/grabs.
Hope it more clear now.

**Comment by RickStrahl** [comment]
What does that mean: _Put the mouse cursor maximum to the right screen-side._ 

Can you provide a screen capture? I have no problems grabbing the scrollbar thumb and moving it as expected either in the current mode or in default browser styling.

**Comment by jovibor** [comment]
I'm not sure I can explain better...
1. Maximize MM window, you can even F11 to go full-screen.
2. Bring the cursor to the right side of the screen, the cursor is barely seen at this moment. It's basically behind the scroll-bar.

If you now do mouse-click, scrolling is not happening at all. Cursor is out of scroll-bar-rectangle.
To make scroll working you must bring the cursor few pixels to the left (an indent).

At the same circumstances scrolling in Chrome works as expected.

**Comment by RickStrahl** [comment]
I don't understand what you mean, sorry. What does the cursor have to do with the scrollbar and what the heck is this indent you talk about?

Are you saying the text is overscrolling the screen? Where? In the editor? In the Preview? 

Could you please record a screen capture to show what you're talking about, because I don't understand what you are talking about...
