### ISSUE TITLE
feat: basic vim emulation

### ISSUE THREAD

**Issue by DuNuNuBatman** [RickStrahl/MarkdownMonster#99]
One feature that would be a "nice to have" would be basic vim navigation and editing in the editor.

**Comment by DuNuNuBatman** [comment]
In your twitter feed, I did notice a mention on VIM keybindings, but I can't seem to find it in the documentation.

**Comment by RickStrahl** [comment]
You can use the `EditorKeyboardHandler` configuration setting to select `vim`:

![image](https://cloud.githubusercontent.com/assets/1374013/21698448/0ea0fa32-d33b-11e6-8f66-3c5a523acfa7.png)

Go to **Tools -> Settings** then look for the key in the file.

**Comment by DuNuNuBatman** [comment]
That's so awesome! I've been wanting a markdown editor with basic vim support! Thanks!

**Comment by RickStrahl** [comment]
Courtesy of Ace Editor :-)
