### ISSUE TITLE
Anomalies with `Insert Row Below`, `Insert Row Above` and `Delete Row` in the Table Editor

### ISSUE THREAD

**Issue by jbridgy** [RickStrahl/MarkdownMonster#992]
With mm v2.7.9 the commands `Insert Row Below` (Alt-Shift-Down), `Insert Row Above`  (Alt-Shift-Up) do not work if the cursor is in the last row and the last row is empty. As a result it is not possible to quickly append some empty lines by hammering Alt-Shift-Down multiple times.

The opposite with command `Delete Row` (Alt-Del) does not work either. For example when the cursor is in the last row then you cannot quickly delete trailing trash rows by pressing Alt-Del multiple times. This fails because the cursor is not automatically moved to the last row when the previously last row has been deleted. Instead the cursor position seems to be undefined in this case.

Sometimes the command `Delete Row` behaves very bad by deleting all empty rows, not just one.

The command `Insert Row Above` (Alt-Shift-Up) is missing in the top row (aka header row). This is inconvenient for example when you have loaded a table without header and want to add a header afterwards.

**Comment by bigonroad** [comment]
Just saw this appeared, I actually had documenting this in more depth on my to do list all week and missed someone had done it. Similar issues to those described in #993

**Comment by bigonroad** [comment]
### Details for recreating error
Also the Alt-Shift-Up/Down doesn't work consistently. Sometimes it will not insert a row until unclicking and reclicking in an area, or until creating one with a different method.

In this screenshot, clicking on either row and using the shortcut will not create rows. Right clicking licking either row allows me to select new row from the context menu, which works, and future use of the keyboard shortcuts work.

![209148886-6edacd12-c17e-411f-988d-7091522126fa](https://user-images.githubusercontent.com/821716/210273806-47bf6f97-a849-4123-8e6b-8521ab18c0be.png)

This is reproducible, just:

- Create any table with two rows
- Click on bottom one
- Create a new row above the bottom one with Alt-Shift-Up
- Delete the bottom row with Alt-Del
- Now try to create new rows with Alt-Shift-Up or Alt-Shift-Down; will not do anything

**Comment by jbridgy** [comment]
The screenshot of @bigonroad above shows a table consisting of a header row and an empty non-header row. If the cursor is in the header row of such a table then `Insert Row Below` (Alt-Shift-Down) just moves the cursor into the empty non-header row, but incorrectly does not insert a new row.

This may be a new aspect or just a consequence of not allowing multiple empty rows. The latter follows from the first sentence of the initial post which states that the commands `Insert Row Below` (Alt-Shift-Down) and `Insert Row Above` (Alt-Shift-Up) do not work if the cursor is in the last row and the last row is empty.

**Comment by RickStrahl** [comment]
That behavior is by design to avoid having a bunch of empty rows at the end of the table. 

You do know that you can quickly add rows just by tabbing past the last item in the table, right? You tab on the last item and it creates a new empty row and moves the cursor into the first element of that row.

![TableNewRowsViaTab](https://user-images.githubusercontent.com/1374013/211174668-c9f9ea95-3ae5-4a9d-8cbc-88b96ba620bb.gif)

It doesn't seem useful to 'pre-create' a whole bunch of empty rows in that scenario?

It's easy enough to enable (in fact remove the check for adding empty rows) but just not sure that's the right thing to do...

**Comment by RickStrahl** [comment]
So I updated the editor to (for now) allow adding blank lines to the bottom. Previously those lines would get stripped during the table HTML rendering process (which occurs after any field change or operaiton).

Also fixed the focus issues with new rows and last line deletion - focus should now go correctly into the last row on both of those operations and the editor should now also scroll down to the last row.

Update is the Preview Release (`2.7.11.2`) on the download page.

**Comment by jbridgy** [comment]
> That behavior is by design to avoid having a bunch of empty rows at the end of the table.
> 
> You do know that you can quickly add rows just by tabbing past the last item in the table, right? You tab on the last item and it creates a new empty row and moves the cursor into the first element of that row.
>
... 
> It doesn't seem useful to 'pre-create' a whole bunch of empty rows in that scenario?
> 
> It's easy enough to enable (in fact remove the check for adding empty rows) but just not sure that's the right thing to do...

Adding a bunch of empty rows at the end of the table by tabbing is not efficient, especially when the table has many columns.
Empty rows are useful when you already have a normal text that you want to distribute into a table by dragging and dropping the pieces. Sometimes it is sufficient to finally apply `Format Table` and you are done.

Furthermore I realized another little flaw of the table editor: When you change a table and finally press the `x` button of the table editor instead of `Embed Table` (Ctrl-Enter) then all changes are discarded without asking the user. This is not consistent with the `x` button of the document or the app.

**Comment by RickStrahl** [comment]
_Adding a bunch of empty rows at the end of the table by tabbing is not efficient, especially when the table has many columns.
Empty rows are useful when you already have a normal text that you want to distribute into a table by dragging and dropping the pieces. Sometimes it is sufficient to finally apply Format Table and you are done._

As mentioned I added the empty row addition back in in the latest updates. 


> press the x button of the table editor instead of Embed Table (Ctrl-Enter) then all changes are discarded without asking the user.

Adding the dialog would just add UI overhead here IMHO. The only way to cancel is via the manual UI operation of clicking the button - it's already a deliberate UI operation. Additional prompting doesn't add any security - you're not going to press that button by accident and even if you do, you're not making a permanent change to anything as it doesn't affect a file written to disk.

**Comment by jbridgy** [comment]
> As mentioned I added the empty row addition back in in the latest updates.

Yes, I know and appreciate that. I just wanted to show you a concrete **use case** because you doubted the usefulness.
Maybe you followed my suggestion only because you realized that the previous "intellisense" (or rather "intellinonsense" as it can be found also in other apps) made the code complex and possibly caused issue #993.

**Comment by jbridgy** [comment]
> Adding the dialog would just add UI overhead here IMHO. The only way to cancel is via the manual UI operation of clicking the button - it's already a deliberate UI operation. Additional prompting doesn't add any security - you're not going to press that button by accident and even if you do, you're not making a permanent change to anything as it doesn't affect a file written to disk.

Certainly one can get used to the current behavior of the Table Editor's `x` button and it may be costly for you to change it but your argument concerning the user is not correct. The changes made with the Table Editor are not immediately written to disk regardless whether you leave it by `Embed Table` (Ctrl-Enter) or `x`. With the former these changes are inserted into the document as modification which you can then save to disk (Ctrl+S) or undo (Ctrl+Z). However with latter these changes are lost and this can be annoying, especially when you made many changes to a large table.

**Comment by RickStrahl** [comment]
Touché on the new lines. Now that it's there it makes a lot of things behave properly - a lot of the 'weirdness' were described in #993 (and this) issue were related to the special behavior of the last row. Hopefully this accounts for some of the hard to track errors that I've seen of this in my logs.

Can we close this issue and move the close prompt to a separate issue please?

**Comment by jbridgy** [comment]
OK. Added issue #997 for buttons of Table Editor, especially `Cancel` and `x` (close).
